### ISSUE TITLE
Firedrake on Archer

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#1000]
The following occurs when I import from firedrake on Archer:

...
ImportError: No module named defs
Rank 147 [Tue Jan 31 22:59:29 2017] [c1-1c2s8n2] application called MPI_Abort(MP
I_COMM_WORLD, 1) - process 147
  File "h5py/_objects.pyx", line 1, in init h5py._objects (/fs2/y07/y07/fdrake/f
iredrake/src/h5py/h5py/_objects.c:7792)
...

Looks like h5py is not quite set up right?

**Comment by wence-** [comment]
Think I fixed it.
