### ISSUE TITLE
h5py build cannot find PETSc

### ISSUE THREAD

**Issue by robertsawko** [firedrakeproject/firedrake#1013]
I am currently trying to build firedrake on my laptop using the universal script. I am running Arch Linux here so cannot use `apt-get`. I invoke the script with the following: `python firedrake-install --no-package-manager --log --minimal-petsc`, but after some time it breaks with:

```
Successfully cloned repository h5py
Checking out branch firedrake
Successfully checked out branch firedrake
Traceback (most recent call last):
  File "firedrake-install", line 719, in build_and_install_h5py
    ["-c", "import petsc; print petsc.get_petsc_dir()"]).strip()
  File "firedrake-install", line 345, in check_output
    return subprocess.check_output(args, stderr=subprocess.STDOUT, env=env)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/rsa/projects/firedrake/bin/python', '-c', 'import petsc; print petsc.get_petsc_dir()']'returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "firedrake-install", line 1206, in <module>
    build_and_install_h5py()
  File "firedrake-install", line 723, in build_and_install_h5py
    raise InstallError("Unable to find installed PETSc when building h5py")
__main__.InstallError: Unable to find installed PETSc when building h5py
```

**Comment by wence-** [comment]
Hi Robert,

I'm not quite sure what's going on.  But one thing that looks suspect to me is:

```
File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
```

Right now, firedrake doesn't run with python 3.  We think it's probably not a lot of work, but haven't quite completed py3kifying it yet.

It looks like the default python on your system is python 3.

Can you try running with python2?

(We should add some error checking to firedrake-install that determines if the python version is sufficient).

**Comment by wence-** [comment]
(Additionally, if you run the install procedure with `--log`, there will be more debugging output in `firedrake-install.log`, if the installation fails again, can you please include that?)

**Comment by robertsawko** [comment]
Sorry, I've actually did run it with log but didn't notice that Github won't support `.log` files. I can confirm that my python default is python3. I will have a look now how can I change it.

Side note. Is there any way to rerun the failed installation? At the moment I just keep deleting the directory and rerunning from the beginning.

[firedrake-install.log.zip](https://github.com/firedrakeproject/firedrake/files/782705/firedrake-install.log.zip)

**Comment by dham** [comment]
Hi Robert. You should be able to run python 2 by explicitly specifying it:
```
    python2 firedrake-install
```

**Comment by robertsawko** [comment]
Thanks, yes, that's what I am doing, but it's stuck on `virtualenv` installation step.

**Comment by dham** [comment]
Can you try running python2 and importing virtualenv manually?

**Comment by robertsawko** [comment]
You reply really fast, thanks.

So I've done somehting slightly different. The problem was that it was picking my system wide installation `pyhon3-virtualenv`. I've done an awful thing of uninstalling it and installing `python2-virtualenv`.  Now it's running. Just got onto compiling PETSc step.

**Comment by robertsawko** [comment]
Okay, it has definitely built. I am now running `make alltest` and I am getting mostly dots, so I think I am fine. Maybe it's worth mentioning somewhere, if you're not doing it already, that `python3` is not supported.

**Comment by wence-** [comment]
Thanks, yes, we don't explicitly say no py3k anywhere I think.
