### ISSUE TITLE
Build system update.

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#1015]
We have a number of issues with the build system:
1. We've outgrown Travis.
2. Building PETSc every time consumes a lot of resource and makes builds slow.
3. To a lesser extent the same issue occurs when packages which depend on Firedrake constantly rebuild Firedrake.
4. Drone doesn't support OSX.

To address 1., we've procured a Mac mini and a new 16 core server. The question is what to run on them.

I have had a lot of  success running Jenkins on my home iMac. The new UI looks really good and doesn't suffer from the performance issues we've seen on Drone. Interfacing with Github to trigger builds, report results and share authentication seems to have been pretty flawless. Jenkins also seems to have a much larger and more active community than Drone. I therefore want to raise the possibility of just running Jenkins for our whole build system.

In a related move I also have a proposal for dealing with issues 2. and 3.:
5. We could set up a build test for the Firedrake branch of PETSc. 
6. On successful builds, this would tar up the build and scp it somewhere (such as the Jenkins server itself). 
7. We then change the Firedrake build to simply download this tarball, unpack it and set PETSC_DIR appropriately. 
8. Jenkins allows us to keep the build script on the build server, so we could do this without introducing Firedrake-specific commits into PETSc.
9. Similarly, if an environment change necessitates a rebuild of PETSc, this can be achieved simply by rerunning the PETSc build.
A similar approach could be taken to Firedrake as a dependency of other packages.

I've looked at the issues we had with Jenkins last year. I think I have verified that they all either have been fixed or are no longer applicable, with the one exception of containerised builds. That one I simply haven't tried (because it's in any event not applicable to Mac). As we concluded last year, containerised builds are not a show-stopper.

**Comment by dham** [comment]
I presume (though @tmbgreaves correct me if I'm wrong) that the plan is that jenkins.ese.ic.ac.uk remains the build master and the one machine visible to the outside world. 

I would therefore guess that the next steps would be:
1. get the new Mac in the data centre and configured so that relevant people can log into it with college credentials. I guess @tmbgreaves needs to do this.
2. Install Jenkins on jenkins.ese.ic.ac.uk and point it at the Mac so that we get the Mac builds happening there. I am happy to do this once the Mac is up (assuming @tmbgreaves trusts me not to break other things ;).

**Comment by tmbgreaves** [comment]
1. I've raised this within ESE to figure out what the best route is to request the new power/network provisioning (we already have the space, as we have 1U spare after replacing existing systems with 1U broadberrys).

2. Absolutely fine to give you sudo on jenkins.ese, David - feel free to prod me if I forget. The system will be up for replacement at some point and we *may* shift it over to AWS (at which point we could turn into buildbot.fluidity-project.net / jenkins.firedrakeproject.org) but I'll make sure you are involved with discussion on that when it happens.

**Comment by wence-** [comment]
Done.
