### ISSUE TITLE
Helmholtz jupyter notebook is missing

### ISSUE THREAD

**Issue by robertsawko** [firedrakeproject/firedrake#1016]
[Jupyter notebook for Helmholtz equation](https://nbviewer.jupyter.org/github/firedrakeproject/firedrake/tree/notebook-updates/docs/notebooks/example-spd-helmholtz.ipynb/) appears to be missing.

It is referenced on [Firedrake Jupyter notebooks](http://www.firedrakeproject.org/notebooks.html) website.

Other notebooks appear to be there.

**Comment by wence-** [comment]
Thanks, fixed in master.
