### ISSUE TITLE
Matrix-free  scripts are missing

### ISSUE THREAD

**Issue by robertsawko** [firedrakeproject/firedrake#1017]
It seems that all scripts referenced in matrix-free support section [here](http://www.firedrakeproject.org/matrix-free.html).

For example [this](http://www.firedrakeproject.org/rayleigh-benard.py) script.

**Comment by robertsawko** [comment]
I was hoping I can give you a merge request with this, but I am a little bit confused. It seems to be that you somehow generate the code from `file.py.rst` in e.g. `` `here <poisson.py>`__``. For the basic tutorials like Helmholtz this works fine, but for matrix free page it doesn't.

**Comment by wence-** [comment]
Thanks.  The way those bits are pulled together is a bit magic.  I will have a go at fixing the links.

**Comment by wence-** [comment]
Thanks, fixed in master.

**Comment by robertsawko** [comment]
Well, thank you for fixing it. I can see this is now split into separate sections. Can I ask  what this "little bit of magic" involves? I know rst a bit, but didn't know you can blend it with real code in this fashion.

**Comment by wence-** [comment]
We use [pylit](https://github.com/gmilde/PyLit) to write literate demo files.  For example [the rayleigh-benard example](https://raw.githubusercontent.com/firedrakeproject/firedrake/master/demos/matrix_free/rayleigh-benard.py.rst) is just normal rst with code blocks.  Pylit transforms the rst into comments and the code blocks into code which makes it runnable.

The other magic is how the documentation build system pulls everything together.  My previous approach of "including" the demo files meant that the links in them were pointing to the wrong place.
