### ISSUE TITLE
Missing link in the documentation

### ISSUE THREAD

**Issue by robertsawko** [firedrakeproject/firedrake#1018]
I am looking through the manual now and I came across a missing link. It's in the [variational-problems](http://www.firedrakeproject.org/variational-problems.html), the UFL link at the bottom. It's probably because it was a link to old fenics docs.
https://fenicsproject.org/olddocs/ufl/dev/ufl.html

Was that meant to be pointing here?
http://fenics.readthedocs.io/projects/ufl/en/latest/

**Comment by wence-** [comment]
Thanks, I found a bunch more as well (this is fixed in #1021).
