### ISSUE TITLE
Support for FacetAvg

### ISSUE THREAD

**Issue by tkarna** [firedrakeproject/firedrake#1020]
Currently firedrake/tsfc does not support UFL's `FacetAvg` operator. This would however be useful for slope limiters at the boundaries. See #835 and https://github.com/thetisproject/thetis/pull/90.

For the purposes of slope limiting we only need to compute `FacetAvg` of functions. That is, it is not necessary to support expressions, e.g. `FacetAvg(sin(f))`.

**Comment by miklos1** [comment]
I just had a look at how UFL pullbacks are applied, and apparently the averaging is applied in the reference space, rather than in the physical space. How big of a problem is that?

**Comment by dorugeber** [comment]
For practical use, it's probably fine.  It's only bad if you have some silly nonlinear mapping from the reference facet to the physical facet.  I think it's 'perfect' on quads, probably not on prisms or hexes.

**Comment by tkarna** [comment]
For a highly deformed prism mesh the difference might be significant. But for the slope limiters it's probably fine as the treatment of the boundaries is not exact anyway.

**Comment by miklos1** [comment]
Tracking it here: firedrakeproject/tsfc#107.

**Comment by wence-** [comment]
This was finally fixed by firedrakeproject/tsfc#158
