### ISSUE TITLE
annoying numpy Deprecation Warning

### ISSUE THREAD

**Issue by APaganini** [firedrakeproject/firedrake#1025]
I like generating meshes through functions. However, I do not like 
that the following code (despite working properly)

```
from firedrake import *

mesh = UnitSquareMesh(3, 3)

x = SpatialCoordinate(mesh)
xcoord = interpolate(x[0], FunctionSpace(mesh, "CG", 1)) 
with xcoord.dat.vec_ro as x:
    print "no problem here\n"

class myExpression(Expression):
        def eval(self, value, x): 
            value[0] = x[0]
            value[1] = x[1]

        def value_shape(self):
            return (2,)

W = VectorFunctionSpace(mesh, "CG", 1)
mesh_fct = Function(W).interpolate(myExpression())
mesh2 = Mesh(mesh_fct)

x = SpatialCoordinate(mesh2)
xcoord = interpolate(x[0], FunctionSpace(mesh2, "CG", 1)) 
with xcoord.dat.vec_ro as x:
    print "\nannoying warning here"
```

returns the following annoying Deprecation Warning

```
no problem here

/Volumes/Scratch/Users/paalbert/Documents/FIREDRAKE/firedrakeAdjoint/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2699: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)

annoying warning here
```

As said, it's not urgent, it's not a bug, but it's annoying.

**Comment by dham** [comment]
Hi Alberto, feel free to file a pull request ;).

**Comment by APaganini** [comment]
fair reply ^_^

**Comment by APaganini** [comment]
some hints on where to start? I have no idea of what's going under the bonnet when I call

`with xcoord.dat.vec_ro as x:`

**Comment by wence-** [comment]
Look in `compile_python_kernel` in `firedrake/interpolation.py` I think.

**Comment by APaganini** [comment]
lawrence is right, replacing `numpy.rank` with `numpy.ndim` in `firedrake/interpolation.py`
removes the annoying warning.  I'll try to ask for a pull request, hope it won't be too messy

**Comment by APaganini** [comment]
solved, see pull request [https://github.com/firedrakeproject/firedrake/pull/1030](#1030)
