### ISSUE TITLE
Installation issues on MacOSX

### ISSUE THREAD

**Issue by michakraus** [firedrakeproject/firedrake#1046]
I have an issue with the installation of firedrake on MacOSX (actually two, but the EIGEN issue was already mention in #1044 and can be easily bypassed by creating `firedrake/lib/python2.7/site-packages/petsc/lib`). Importing firedrake after installation, I get the following error from h5py:

> (firedrake) $ python2.7
Python 2.7.13 (default, Apr  4 2017, 08:46:44)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>
> import firedrake
>
> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mkraus/Development/Libraries/firedrake/src/firedrake/firedrake/__init__.py", line 31, in <module>
    from firedrake.checkpointing import *
  File "/Users/mkraus/Development/Libraries/firedrake/src/firedrake/firedrake/checkpointing.py", line 4, in <module>
    from firedrake import hdf5interface as h5i
  File "firedrake/hdf5interface.pyx", line 3, in init firedrake.hdf5interface (firedrake/hdf5interface.c:2333)
  File "/Users/mkraus/Development/Libraries/firedrake/src/h5py/h5py/__init__.py", line 34, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5r.pxd", line 21, in init h5py._conv (/Users/mkraus/Development/Libraries/firedrake/src/h5py/h5py/_conv.c:7886)
  File "h5py/_objects.pxd", line 12, in init h5py.h5r (/Users/mkraus/Development/Libraries/firedrake/src/h5py/h5py/h5r.c:3573)
  File "h5py/_objects.pyx", line 1, in init h5py._objects (/Users/mkraus/Development/Libraries/firedrake/src/h5py/h5py/_objects.c:8099)
ImportError: dlopen(/Users/mkraus/Development/Libraries/firedrake/src/h5py/h5py/defs.so, 2): Symbol not found: _H5Rdereference1
  Referenced from: /Users/mkraus/Development/Libraries/firedrake/src/h5py/h5py/defs.so
  Expected in: flat namespace
 in /Users/mkraus/Development/Libraries/firedrake/src/h5py/h5py/defs.so

I was able to fix this by manually re-building h5py, i.e.,

```
cd /Users/mkraus/Development/Libraries/firedrake/src/h5py
export HDF5_DIR=/Users/mkraus/Development/Libraries/firedrake/lib/python2.7/site-packages/petsc
export HDF5_MPI=ON
python setup.py install --inplace
```

but I wonder if there is an issue in the installation script.

I am on El Capitan 10.11.6 and did the default installation using no external packages or compilers other than what comes with OSX or HomeBrew.

**Comment by wence-** [comment]
Hmm, interesting.  Effectively that is all the install script does.  I'll try and reproduce and see if I can see what broke.  This might take a week or so because everyone is away for the Easter break.

**Comment by wence-** [comment]
@michakraus I wonder if you tried again with this problem (or figured out what was going on).  In any case, we hopefully ameliorated the eigen install problems recently, so a newly download `firedrake-install` will hopefully no longer break.  Do please let us know if it does.

**Comment by michakraus** [comment]
Thanks for asking. In the meanwhile (not too long after filing the original issue) I installed firedrake on another Mac with macOS 10.12 and did not run into this issue but only into the eigen problem. I did not re-install it on the machine where the error originally appeared, though.

**Comment by wence-** [comment]
OK, thanks.  I will close for now, please do get in touch if you run into any problems.
