### ISSUE TITLE
Consider installing Eigen ourselves rather than relying on PETSc

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#1051]
While passing `--download-eigen` to PETSc seemed like an easy and neat way ensuring we have an Eigen installed in Firedrake, it turned out to be a source of much pain and frustration. Pains include(d):

- Mercurial dependency
- Cloning the Eigen repository sometimes just fails
- Bugs in the install recipe maintained by PETSc; Eigen does not seem to be a priority for PETSc
- We have no control over which version of Eigen is fetched to install

**Comment by thomasgibson** [comment]
I'm all for it. Are you suggesting that we need to maintain a "Firedrake-version" of Eigen on github (like with PETSc)?

**Comment by miklos1** [comment]
> Are you suggesting that we need to maintain a "Firedrake-version" of Eigen on github

I inclined to think that that would be good idea.

@thomasgibson: But don't start working on it until someone (David or Lawrence, probably) affirms that we want to do this.

**Comment by miklos1** [comment]
Related: #1044, #1045, #1054, and #1058 so far.

**Comment by wence-** [comment]
As a corollary here.  I think we should stop relying on pip to install PETSc.  That way, when things fail, the configure.log/make.log is still available and we can ask people to provide it.  We can forward it on to the PETSc team if necessary.

We can fake the result of the `pip install` by providing our own `petsc` package that points to the right place.

**Comment by wence-** [comment]
Done in #1069.
