### ISSUE TITLE
Non-homogeneous Dirichlet conditions on vector-valued function spaces not applying

### ISSUE THREAD

**Issue by thomasgibson** [firedrakeproject/firedrake#1056]
I encountered this problem while working on a dual formulation of the Poisson equation where a non-homegeneous Neumann condition is enforced on the primal variable. This means, in the dual formulation, that the Neumann condition becomes a strong boundary condition enforced on the flux space.

Here is a small example demonstrating the bug:
```python
from firedrake import *

mesh = UnitSquareMesh(2, 2)

V = FunctionSpace(mesh, "RT", 1)
f = Function(V)

# Apply a strong condition at the top of the square domain
bc = DirichletBC(V, Constant((0.0, 10.0)), 4)

bc.apply(f)
```
Now if we view the data contained in the function via `f.dat.data`, we get:
```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```
It appears that the `bc` is being treated as "homogeneous". However, if we use `Expression` instead:

```python
bc = DirichletBC(V, Expression(("0.0", "10.0")), 4)
```
we obtain:
```
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., -5., 0., 0., -5., 0.])
```
So it seems that there is a issue here. Similarly, we get different results if we use
```python
bc = DirichletBC(V, Constant((10.0, 0.0)), 4)
```
or
```python
bc = DirichletBC(V, Expression(("10.0", "0.0")), 4)
```
When using `Constant`, it seems that only the first argument is being considered. Perhaps I am missing something?

**Comment by miklos1** [comment]
I'm guessing from the source code that projection happens for `Expression`, but for `Constant` it goes down into the rabbit hole known as `firedrake/assemble_expressions.py`. Feel free to debug and fix it. I guess you want to go with projection somehow when the target space is RT or similar.
