### ISSUE TITLE
Installation fails on my Mac OS Sierra (v. 10.12.3)

### ISSUE THREAD

**Issue by baracd** [firedrakeproject/firedrake#1057]
Hello, I'm failing at installing firedrake, 
I typed 'PETSC_CONFIGURE_OPTIONS="--download-eigen=0" python firedrake-install --log --disable-ssh'

and the terminal returned this

```
Installing command line tools...
Installing required packages via homebrew. You can safely ignore warnings that packages are already installed
Creating firedrake virtualenv in '/Users/baracd/Applications/firedrake'.
/Users/baracd/Applications/firedrake/bin/pip install -U setuptools
/Users/baracd/Applications/firedrake/bin/pip install -U pip
[('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/_CodeSignature/CodeResources', '/Users/baracd/Applications/firedrake/Python.app/Contents/_CodeSignature/CodeResources', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/_CodeSignature/CodeResources'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/_CodeSignature', '/Users/baracd/Applications/firedrake/Python.app/Contents/_CodeSignature', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/_CodeSignature'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/Info.plist', '/Users/baracd/Applications/firedrake/Python.app/Contents/Info.plist', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/Info.plist'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '/Users/baracd/Applications/firedrake/Python.app/Contents/MacOS/Python', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/MacOS/Python'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS', '/Users/baracd/Applications/firedrake/Python.app/Contents/MacOS', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/MacOS'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/PkgInfo', '/Users/baracd/Applications/firedrake/Python.app/Contents/PkgInfo', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/PkgInfo'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/Resources/PythonApplet.icns', '/Users/baracd/Applications/firedrake/Python.app/Contents/Resources/PythonApplet.icns', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/Resources/PythonApplet.icns'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/Resources/PythonInterpreter.icns', '/Users/baracd/Applications/firedrake/Python.app/Contents/Resources/PythonInterpreter.icns', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/Resources/PythonInterpreter.icns'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/Resources', '/Users/baracd/Applications/firedrake/Python.app/Contents/Resources', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/Resources'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/version.plist', '/Users/baracd/Applications/firedrake/Python.app/Contents/version.plist', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/version.plist'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents', '/Users/baracd/Applications/firedrake/Python.app/Contents', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app', '/Users/baracd/Applications/firedrake/Python.app', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app'")]
Traceback (most recent call last):
  File "firedrake-install", line 1219, in fix_osx_virtualenv_python
    shutil.copytree(appsrc, appdest)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/_CodeSignature/CodeResources', '/Users/baracd/Applications/firedrake/Python.app/Contents/_CodeSignature/CodeResources', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/_CodeSignature/CodeResources'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/_CodeSignature', '/Users/baracd/Applications/firedrake/Python.app/Contents/_CodeSignature', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/_CodeSignature'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/Info.plist', '/Users/baracd/Applications/firedrake/Python.app/Contents/Info.plist', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/Info.plist'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '/Users/baracd/Applications/firedrake/Python.app/Contents/MacOS/Python', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/MacOS/Python'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS', '/Users/baracd/Applications/firedrake/Python.app/Contents/MacOS', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/MacOS'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/PkgInfo', '/Users/baracd/Applications/firedrake/Python.app/Contents/PkgInfo', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/PkgInfo'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/Resources/PythonApplet.icns', '/Users/baracd/Applications/firedrake/Python.app/Contents/Resources/PythonApplet.icns', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/Resources/PythonApplet.icns'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/Resources/PythonInterpreter.icns', '/Users/baracd/Applications/firedrake/Python.app/Contents/Resources/PythonInterpreter.icns', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/Resources/PythonInterpreter.icns'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/Resources', '/Users/baracd/Applications/firedrake/Python.app/Contents/Resources', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/Resources'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/version.plist', '/Users/baracd/Applications/firedrake/Python.app/Contents/version.plist', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents/version.plist'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents', '/Users/baracd/Applications/firedrake/Python.app/Contents', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app/Contents'"), ('/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app', '/Users/baracd/Applications/firedrake/Python.app', "[Errno 1] Operation not permitted: '/Users/baracd/Applications/firedrake/Python.app'")]
Cloning firedrake

Successfully cloned repository firedrake.
Checking out branch master
Successfully checked out branch master
Cloning the dependencies of firedrake
Cloning ufl

Successfully cloned repository ufl.
Checking out branch master
Successfully checked out branch master
Cloning fiat

Successfully cloned repository fiat.
Checking out branch master
Successfully checked out branch master
Cloning FInAT

Successfully cloned repository FInAT.
Checking out branch master
Successfully checked out branch master
Cloning tsfc

Successfully cloned repository tsfc.
Checking out branch master
Successfully checked out branch master
Cloning PyOP2

Successfully cloned repository PyOP2.
Checking out branch master
Successfully checked out branch master
Cloning the dependencies of PyOP2
Cloning petsc

Successfully cloned repository petsc.
Checking out branch firedrake
Successfully checked out branch firedrake
Apply temporary --download-eigen fix
Cloning petsc4py

Successfully cloned repository petsc4py.
Checking out branch firedrake
Successfully checked out branch firedrake
Cloning COFFEE

Successfully cloned repository COFFEE.
Checking out branch master
Successfully checked out branch master
/Users/baracd/Applications/firedrake/bin/pip install --no-binary mpi4py -vvv Cython>=0.22

Traceback (most recent call last):
  File "firedrake-install", line 1317, in <module>
    run_pip_install(["Cython>=0.22"])
  File "firedrake-install", line 625, in run_pip_install
    check_call(pipinstall + pipargs)
  File "firedrake-install", line 365, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=env))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/Users/baracd/Applications/firedrake/bin/pip', 'install', '--no-binary', 'mpi4py', '-vvv', 'Cython>=0.22']' returned non-zero exit status -6

```

the log is here 
[firedrake-install.txt](https://github.com/firedrakeproject/firedrake/files/964230/firedrake-install.txt)

Can you please help me?

**Comment by wence-** [comment]
Hmm, this appears to be similar to the problem that #1039 is attempt to address.  Thinking about it some more, I am inclined to just remove this code from the installer.  The only thing that is not available without it is the MacOS GUI backend to matplotlib.

Can you try downloading the firedrake-install script from here: https://raw.githubusercontent.com/firedrakeproject/firedrake/no-osx-framework-munging/scripts/firedrake-install

Removing your failed installation directory, and try again?

Thanks!

**Comment by baracd** [comment]
Hi,

Thank you for the fast reply! The installation worked but when I run "make alltest" to test it it stops at 

tests/regression/test_zero_integrand.py .
tests/slate/test_assemble_tensors.py FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFxFFFx
tests/slate/test_facet_tensors.py FFFF
tests/slate/test_facet_tensors_extr.py FFFFFFFFFF
tests/slate/test_hybrid_poisson_sphere.py F

Does this mean there's a problem with the installation?

**Comment by thomasgibson** [comment]
This probably means that you do not have Eigen installed properly, which has been an ongoing issue. Does everything else pass? If so, you should be okay for now until we fix the Eigen installation problem. This only matters if you want to use hybridization.

**Comment by miklos1** [comment]
`PETSC_CONFIGURE_OPTIONS="--download-eigen=0"` will make the SLATE tests fail. Are there any failures outside `tests/slate/`? If everything else passes, then your installation is mostly fine, except that SLATE won't work for you.

**Comment by baracd** [comment]
I also get:

tests/regression/test_facet_elements.py F

But everything else seems to pass up to the slate tests. It doesn't appear to be able to continue testing after the slate tests.

**Comment by wence-** [comment]
Hmm, that test probably should not fail.  Can you please run:

```
py.test tests/regression/test_facet_elements.py
```

And post the resulting backtrace on failure?

If you want to run all the tests excluding the slate ones (which we expect to fail), you can run:

```
py.test tests -k 'not slate'
```

**Comment by baracd** [comment]
I get the following when I run py.test tests/regression/test_facet_elements.py:

======================================================= test session starts ========================================================
platform darwin -- Python 2.7.10, pytest-2.9.2, py-1.4.33, pluggy-0.3.1
benchmark: 3.0.0 (defaults: timer=time.time disable_gc=False min_rounds=5 min_time=5.00us max_time=1.00s calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/baracd/Applications/firedrake/src/firedrake, inifile: 
plugins: xdist-1.16.0, benchmark-3.0.0
collected 1 items 

tests/regression/test_facet_elements.py F

======================================================================================== FAILURES =========================================================================================
_________________________________________________________________________________ test_all_dofs_on_facets _________________________________________________________________________________

    def test_all_dofs_on_facets():
        mesh = UnitSquareMesh(5, 5)
        V_elt = FiniteElement("BDM", triangle, 1)
        # BDM has all dofs on facets, so these should be the same
        W1_elt = FacetElement(V_elt)
        V = FunctionSpace(mesh, V_elt)
        W1 = FunctionSpace(mesh, W1_elt)
        f = Function(V).assign(1)
        g = Function(W1).assign(1)
        n = FacetNormal(mesh)
    
>       assert abs(assemble(dot(f, f)*dx) - assemble(dot(g, g)*dx)) < 1e-13
E       assert 1.0658141036401503e-13 < 1e-13
E        +  where 1.0658141036401503e-13 = abs((58.333333333333464 - 58.333333333333357))
E        +    where 58.333333333333464 = assemble((Dot(Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object...e), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 1)), 2)) * dx))
E        +      where Dot(Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object...e), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 1)), 2)) = dot(Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object at ...ne), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 1)), 2), Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object at ...ne), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 1)), 2))
E        +    and   58.333333333333357 = assemble((Dot(Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object...e), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 1)), 7)) * dx))
E        +      where Dot(Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object...e), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 1)), 7)) = dot(Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object at ...ne), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 1)), 7), Coefficient(WithGeometry(FunctionSpace(<firedrake.mesh.MeshTopology object at ...ne), Mesh(VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2), 1)), 7))

tests/regression/test_facet_elements.py:17: AssertionError
================================================================================ 1 failed in 7.21 seconds =================================================================================

**Comment by dham** [comment]
Don't worry about this error. Basically 1e-13 is an arbitrary estimation of the amount of roundoff error which will occur, but this is dependent on compiler, libraries, and maybe even processor. In this case, the observed error is 1.07e-13 which is very unlikely to indicate a problem. We should just relax the tolerance on this test slightly.

**Comment by wence-** [comment]
OK, this looks like a case where we should probably just relax the tolerance on the test slightly.

What this test is doing is checking that a finite element that only has degrees of freedom on facets is equivalent to the restriction of that finite element to one with degrees of freedom only on the facets.  However, these lead to slightly different numerical answers because the basis evaluation is not identical in the two cases.  Effectively we reorthogonalise the basis when constructing the restricted element from the input one: as a result we might expect some minor variations in the final digits.  So I think this is probably fine, I will push a proposed fix.

**Comment by baracd** [comment]
I ran the tests excluding the slate ones and everything else worked. Thank you for your help!
