### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by ediemiglio** [firedrakeproject/firedrake#1058]
Hi to everybody, I am trying to install Firedrake but I the installation stops trying to install Eigen. I am attaching the log file. Any help is welcome.
Thanks in advance
    Regards
        Edie

[firedrake-install.log.txt](https://github.com/firedrakeproject/firedrake/files/964556/firedrake-install.log.txt)

**Comment by miklos1** [comment]
Looks the same as #1044 which was supposedly fixed by #1045.

**Comment by wence-** [comment]
I agree, to try and get a more sensible error message, can you please do:

```
cd firedrake/src/petsc
./configure --prefix=/home/edie/firedrake/test-petsc-install PETSC_ARCH=arch-python-linux-x86_64 --with-shared-libraries=1 --with-debugging=0 --with-c2html=0 --with-cc=/usr/bin/mpicc --with-cxx=/usr/bin/mpicxx --with-fc=/usr/bin/mpif90 --download-chaco --download-metis --download-parmetis --download-scalapack --download-hypre --download-mumps --download-netcdf --download-hdf5 --download-exodusii --download-eigen
```

If that succeeds, I don't know what was going on.  If it fails (which I suspect it will) please post the output of `configure.log`.

**Comment by rckirby** [comment]
We are still having trouble on our end -- my student wasn't able to build
after downloading the supposed fix.  I will see if disabling eigen works
for her.

On Fri, Apr 28, 2017 at 9:26 AM, Lawrence Mitchell <notifications@github.com

**Comment by wence-** [comment]
Dear @ediemiglio, @rckirby, I just made some changes to the install script that hopefully makes downloading and install eigen more robust.  Please download the install script anew from https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install and try again.  Hopefully things will work, but if not, we would love to know so we can attempt to fix them.
