### ISSUE TITLE
installing on macbook sierra 10.12.3

### ISSUE THREAD

**Issue by gerard423** [firedrakeproject/firedrake#1066]
I was not able to install firedrake. Could you please look into the log file attached?
[firedrake-install.txt](https://github.com/firedrakeproject/firedrake/files/989603/firedrake-install.txt)

**Comment by miklos1** [comment]
It says your Fortran compiler does not work. Where is your Fortran and MPI installation from?

**Comment by gerard423** [comment]
Thanks. I don't know where they are from. Should I install new ones? Which ones would you recommend?

**Comment by wence-** [comment]
Aha, can you try compiling:

```sh
$ cat test.f90
program main
use mpi
end program main
$ mpif90 test.f90 -o test
$ ./test
```

To see what happens?

**Comment by gerard423** [comment]
I created a file test.f90 in which I have
program main
use mpi
end program main
I then run the command mpif90 test.f90 -o test and got the following message:
FATAL:/opt/local/bin/../libexec/as/x86_64/as: I don't understand 'm' flag!

**Comment by wence-** [comment]
OK, this looks like the problem that the wrong assembler is being used.  I suspect you also have macports installed on the machine, and some of the binaries from macports are appearing in your PATH.  Can you provide the output of `env` in the shell?

**Comment by gerard423** [comment]
Hi

Here is the output.

TERM_PROGRAM=Apple_Terminal
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/cp/w9x_v1y13nz40g_cn14115l80000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.XPoL9oQsPU/Render
TERM_PROGRAM_VERSION=388
TERM_SESSION_ID=0B710858-2985-4E16-9E09-5278CE9DF43A
USER=gerard
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.vfENKrQFJf/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/lib:/opt/X11/bin:/usr/local/ff++/openmpi/3.50-2/bin:/Library/TeX/texbin:/Users/gerard/Library/Python/2.7/bin
PWD=/Users/gerard/Desktop/MathHome6/Fenics/Python
DBUS_LAUNCHD_SESSION_BUS_SOCKET=/private/tmp/com.apple.launchd.IfAbP7O06T/unix_domain_listener
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
HOME=/Users/gerard
SHLVL=1
LOGNAME=gerard
DISPLAY=/private/tmp/com.apple.launchd.MvZOptuQ7e/org.macosforge.xquartz:0
SECURITYSESSIONID=186a7
_=/usr/bin/env

**Comment by wence-** [comment]
OK great.  It looks like your `.profile` (or `.bashrc`) inserts `/opt/local/bin` and `/opt/local/sbin` at the front of PATH, and therefore you pick up some components that are installed there that are incompatible with (amongst others) mpif90.  If you say:

```
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/lib:/opt/X11/bin:/Library/TeX/texbin:/Users/gerard/Library/Python/2.7/bin
```

Then I hope things will work.  But you should arrange that your path is sanitised in this way before running firedrake.

**Comment by gerard423** [comment]
I modified my .profile file which is copied below. It has not worked yet. I am also adding below the output for env as well as attaching the new log file I get after running the installation.

.profile
========================================================================
# for use with firedrake
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/lib:/opt/X11/bin:/Library/TeX/
texbin:/Users/gerard/Library/Python/2.7/bin
# end editing for firedrake

# MacPorts Installer addition on 2017-01-31_at_22:55:23: adding an appropriate PATH variable for use with MacPorts.
#export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# added by Anaconda3 4.2.0 installer
#export PATH="/Users/gerard/anaconda/bin:$PATH"

=======================================================================

output of env

TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/cp/w9x_v1y13nz40g_cn14115l80000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.XPoL9oQsPU/Render
TERM_PROGRAM_VERSION=388
TERM_SESSION_ID=FCD16196-1988-49A3-8566-8BE920F22C51
USER=gerard
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.vfENKrQFJf/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/lib:/opt/X11/bin:/usr/local/ff++/openmpi/3.50-2/bin:/Library/TeX/texbin:/Users/gerard/Library/Python/2.7/bin
PWD=/Users/gerard
DBUS_LAUNCHD_SESSION_BUS_SOCKET=/private/tmp/com.apple.launchd.IfAbP7O06T/unix_domain_listener
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/gerard
LOGNAME=gerard
DISPLAY=/private/tmp/com.apple.launchd.MvZOptuQ7e/org.macosforge.xquartz:0
SECURITYSESSIONID=186a7
_=/usr/bin/env
[firedrake-install.txt](https://github.com/firedrakeproject/firedrake/files/993488/firedrake-install.txt)

**Comment by wence-** [comment]
Ah, apologies, you will need to start a new terminal for these changes to be picked up in the shell (notice how the `env` output still contains `/opt/local/bin` in `PATH`.

**Comment by gerard423** [comment]
I closed all terminals and restarted the computer. The output of env is below. I still have /opt/local/bin in PATH.

TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/cp/w9x_v1y13nz40g_cn14115l80000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.UvvQ5gAWBL/Render
TERM_PROGRAM_VERSION=388
TERM_SESSION_ID=A921EF52-7B64-4631-8897-683B0E7BC123
USER=gerard
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.omaRraZGKs/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/lib:/opt/X11/bin:/usr/local/ff++/openmpi/3.50-2/bin:/Library/TeX/texbin:/Users/gerard/Library/Python/2.7/bin
PWD=/Users/gerard
DBUS_LAUNCHD_SESSION_BUS_SOCKET=/private/tmp/com.apple.launchd.AuFgeTudHa/unix_domain_listener
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/gerard
LOGNAME=gerard
DISPLAY=/private/tmp/com.apple.launchd.acWpJSvUxo/org.macosforge.xquartz:0
SECURITYSESSIONID=186a7
_=/usr/bin/env

**Comment by wence-** [comment]
Hmmm, that is confusing.  Does mac ports run something on startup to ensure that `.profile` is modified?  Can you confirm that both `.profile` and `.bashrc` do not modify PATH?

**Comment by gerard423** [comment]
How can I find out? 
I inserted the path into ~/.bashrc without any result. The file I edited is ~/.profile.
