### ISSUE TITLE
Can't set MUMPS options in solver_parameters dictionary

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#1076]
MUMPS options such as `"mat_mumps_icntl_24": 1` apparently insist on being global, and therefore putting them inside `solver_parameters` doesn't work since we append the `firedrake_n_` string to the beginning.  Currently, I think the only option is to set these at the command line: `python foo.py -mat_mumps_icntl_24 1`.

```
from firedrake import *

mesh = UnitSquareMesh(64, 64)

V = FunctionSpace(mesh, "P", 2)

x, y = SpatialCoordinate(mesh)
f = Function(V).interpolate(sin(2*pi*x)*sin(2*pi*y))

u = TrialFunction(V)
v = TestFunction(V)

a = dot(grad(u), grad(v))*dx
L = f*v*dx

out = Function(V)

params = {"ksp_view": True,
          "ksp_type": "preonly",
          "pc_type": "lu",
          "pc_factor_mat_solver_package": "mumps",
          "mat_mumps_icntl_24": 1,
          }

solve(a == L, out, solver_parameters=params)

print out.dat.data
```

Running the above code, one can see in the KSPView that ICNTL(24) isn't set.  However, passing the option at the command line with no prefix does the right thing.

**Comment by wence-** [comment]
You could say options_prefix="". But thus sounds like a petsc snafu

**Comment by juan42** [comment]
MATSOLVERMUMPS is a matrix type. Thus its a matrix option. The prefix in the solver options is assumed to apply for the solver prefix and _not_ the matrix prefix.

**Comment by wence-** [comment]
OK, so the solvers should also set the options prefix on the operators they make...
