### ISSUE TITLE
Local solver kernels

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#108]
Request: kernels that assemble local matrices (including mixed function spaces), and then apply direct solver (BLAS) to local matrix/RHS system, and write output to chosen field.

This would be great for reconstructing the mass flux from the density advection to feed to the other advection schemes in the dynamical core project, but I have a possible workaround that is less efficient but will get it working.

**Comment by miklos1** [comment]
@colinjcotter: What is the state of this? Is it implemented already?

**Comment by colinjcotter** [comment]
It is not, we are discussing to implement something like this to use
hybridisation. The main thing is that it needs to be able to operate on
mixed function spaces.

**Comment by colinjcotter** [comment]
My comment about on 23rd Dec 2014 only applies to the Helmholtz case, as it turns out, where pressure can be eliminated analytically. For Poisson, and more complicated things, it is necessary to assemble a local mixed function space block and invert it. We'll need to sketch out a plan for that.

**Comment by wence-** [comment]
Coming as part of @thomasgibson's work.

**Comment by thomasgibson** [comment]
Related to #975

**Comment by wence-** [comment]
Basic functionality is there, please raise specific slate issues.
