### ISSUE TITLE
Saving of fields to hdf5

### ISSUE THREAD

**Issue by cbrel** [firedrakeproject/firedrake#1080]
Dear all,

I've been trying for long to save the fields, evaluated at the grid points, to an hdf5 file in an efficient way. I've searched extensively, and what I've found on the documentation or on google was not satisfactory (the .at() uff method is rather inefficient and the Checkpoint object does not exactly tailor my goals). Up to now I can save the degrees of freedom of the function, but I would need something like the fenics function vertex_to_dof_map in order to evaluate the fields efficiently on the mesh. Is there an equivalent of this function in firedrake?

Thanks in advance,

**Comment by dham** [comment]
I think you've jumped ahead a few steps here. Rather than asking for `vertex_to_dof_map`, which is a FEniCS implementation detail, can you explain mathematically what you're trying to achieve?

**Comment by cbrel** [comment]
Thanks for the quick reply.
Well, I just want to save the fields in a format which is not a .pvd file, because I need to post process them and to plot the results in different ways.
Given a mesh and a space (let's take it for simplicity a CG space of degree 1), I define a Function "u" on this space, which will be the solution of a certain PDE.
Then:
u.vector().array() ->returns the degrees of freedom of the object
u.at([x,y]) ->allows to evaluate the function at a point or on a list of points (but it's inefficient)
I would like to evaluate the function "u" on the mesh.
I was asking for an equivalent of the vertex_to_dof_map because that's how I know it is done in Fenics, and it might have been similar here.

**Comment by dorugeber** [comment]
> I would like to evaluate the function "u" on the mesh.
What does this mean?

**Comment by juan42** [comment]
If I understand you correctly you want to save coordinates and solutions or fields at those coordinates?

PETSc has a Viewer for that purpose where you just need to define your vectors you want to write to the HDF5 file (and then describe them appropriately with XDMF for paraview). You could get the coordinates for example with an interpolation of them to an appropriate function space.

I also proposed this on slack as a general way for data output.

**Comment by cbrel** [comment]
Yes exactly, @juan42. 
I was not aware of this PETSc Viewer, which might be exactly what I need. How is it to be used inside firedrake?

**Comment by dham** [comment]
I think @dorugeber has the right question. What do you mean by "evaluate u on the mesh"?

**Comment by cbrel** [comment]
I replied already, saying that I meant, was @juan42 wrote.
So, I mean that I want to save the values that my function has at particular points, that is the grid points, the coordinates.

**Comment by dham** [comment]
OK. In that case, the fact that Firedrake treats the coordinates as a first class Function comes to your aid.

If `m` is a `firedrake.Mesh` then `m.coordinate` is a `firedrake.Function` . By default, the mesh elements are flat so `m.coordinate` is in vector CG1. if f is a `firedrake.Function` in CG1 then `f.dat.data_ro` is a numpy array of coefficient values, and `m.coordinate.dat.data_ro` is a numpy array containing the corresponding vertex locations, in the same order (hence you don't need `vertex_to_dof_map`). 

You can also achieve similar effects for any f in CGn or DGn by simply interpolating the coordinate function into the corresponding vector function space. Life is more complex if you want to deal with H(div) and H(curl) spaces.

**Comment by dorugeber** [comment]
And if your function `u` isn't in CG1, but is in some higher-order space, you can interpolate `u` into a CG1 function f: `f.interpolate(u)`, then continue as above.

(If your function `u` is from some (partially-) discontinuous space, probably you don't want to be sampling this directly at the vertices).

**Comment by cbrel** [comment]
Should this be different from f.dat.data or f.vector().array()? 
I've tried it, but I still get the degrees of freedom of the function, like with the other two methods..

**Comment by miklos1** [comment]
> So, I mean that I want to save the values that my function has at particular points, that is the grid points, the coordinates.

I guess this means you want to interpolate your field onto a function space similar to your coordinate function space. But others have said this is already, so ...

> Should *this* be different from f.dat.data or f.vector().array()?

'this' = ?

**Comment by cbrel** [comment]
> 'this' = ?
The method f.dat.data_ro. It gives me the same as f.dat.data or f.vector().array()

> I guess this means you want to interpolate your field onto a function space similar to your coordinate function space. But others have said this is already, so ...
I don't define a space for the coordinates, should I? The coordinates are given by the grid: I just want to know the values of the function on the grid points.

**Comment by dham** [comment]
In Firedrake, the coordinates are always given by a `Function` in a `FunctionSpace`. This is always true and automatic. It is a CG1 space by default, but you can do other things.

If `f` is in the scalar or vector `FunctionSpace` corresponding to the `VectorFunctionSpace` that the coordinates are in, then `f.dat.data_ro` is the value of the `Function` `f` at the points given by `m.coordinate.dat.data_ro`. If you are in CG1, these points are also the mesh vertices.

`.data_ro` is the same data as `.data`, but `data_ro` is an assertion that you have not changed the data, which matters for the automation of parallel data exchanges.

**Comment by juan42** [comment]
Okay here is my quick and dirty writeup

https://gist.github.com/juan42/e6673392cd17cd488bdc7b40603438b4

This needs to refined for vectors and other elements of course. You need to postprocess the h5 file with Matthews script which is in your firedrake/petsc installation located at:
```
$FIREDRAKE_FOLDER/src/petsc/bin/petsc_gen_xdmf.py out.h5
```
Then open the out.xmf in paraview or VisIt

**Comment by alexanderzimmerman** [comment]
Aside from the improvements mentioned in #1649 , isn't the functionality requested in this issue already covered by `firedrake.DumbCheckpoint`? Can the issue be closed, or are there limitations that aren't documented?
