### ISSUE TITLE
incompatibility of plot with FEniCS leads to hang

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#1082]
Reported by @rckirby, I have not tried to verify.

```
from firedrake import *
L = FiniteElement("Lagrange", triangle, 1)
plot(L)
```

(in FEniCS, FFC has some rudimentary `plot` facility to visualise DOFs on a `FiniteElement`).  I guess we aren't doing enough sanity-checking in our own `plot`ter.

**Comment by danshapero** [comment]
The plotting API was rewritten in #1522 ; the above code gives an error. We could add a new function specifically to visualize DOFs but that isn't in the API now.
