### ISSUE TITLE
interpolate method with self-referencing expression produces wrong result

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#1083]
The following code

    from firedrake import *
    mesh=UnitSquareMesh(10, 10)

    V=FunctionSpace(mesh, "CG", 1)
    u = Function(V)
    u.assign(1.0)
    u.interpolate(u + 1.0)
    print u.dat.data.max()

gives a max of 6.0 instead of 2.0. Replacing `interpolate` with `assign` gives the correct result.

**Comment by miklos1** [comment]
This is a [known issue](http://firedrakeproject.org/mesh-coordinates.html), but thanks for registering it on GitHub.

**Comment by wence-** [comment]
Can we raise an error here?

**Comment by miklos1** [comment]
We might as well just fix the problem then...

**Comment by wence-** [comment]
The error patch would look like this, I think:
```diff
diff --git a/firedrake/interpolation.py b/firedrake/interpolation.py
index 2a0d231..7571657 100644
--- a/firedrake/interpolation.py
+++ b/firedrake/interpolation.py
@@ -193,6 +193,8 @@ def _interpolator(V, dat, expr, subset):
         co = mesh.cell_orientations()
         args.append(co.dat(op2.READ, co.cell_node_map()))
     for coefficient in coefficients:
+        if coefficient.dat == dat:
+            raise ValueError("Can't have output target as lvalue in interpolation")
         args.append(coefficient.dat(op2.READ, coefficient.cell_node_map()))
 
     return partial(op2.par_loop, *args)
```

**Comment by miklos1** [comment]
But if you detected this problem, then you could just interpolate into a temporary, then copy from the temporary to the real target with `assign`, and release the temporary.
