### ISSUE TITLE
Non-UFL functionals

### ISSUE THREAD

**Issue by zoegoss** [firedrakeproject/firedrake#1085]
I want to be able to optimise functionals in thetis that can not currently be expressed in UFL. To do that currently you have to find a workaround and calculate the derivative yourself.

Using OpenTidalFarm as an example (since I believe it works similarly), typical functionals are  power functionals  of the form `J_power = c_t * u**3 * dx` and cost functionals of the form `J_cost = ct * dx`. This enables the user to optimise with respect to UFL combinations of the power and cost functionals such as `functional = J_power - 1600 * J_cost`. 

However I need to be able to minimise the Levelised Cost of Energy (LCOE) which is the discounted cost (which can be thought of as a function of the number of turbines) and the discounted energy (function of the power) i.e. `LCOE = f(N)/g(P)` where `N` is the number of turbines calculated as `assemble(J_cost)` and the power `P` as `assemble(J_power)`. This currently requires me find the gradient myself using the chain rule and work around to put that gradient into the (reduced) functional.

**Comment by miklos1** [comment]
@funsim: can `fenics_adjoint` solve this?

**Comment by wence-** [comment]
I believe @funsim thinks that this is doable with `fenics_adjoint`.  This issue is partly a reminder to look at this stuff next week.

**Comment by dham** [comment]
As discussed in the meeting, Firedrake adjoint 2 can basically do this, though a few more operators need to be overloaded. @zoegoss is going to look into how to do this with our help.

**Comment by wence-** [comment]
This is now basically working on our end (`pyadjoint`-based `firedrake-adjoint` is now the default).  Missing pieces in the differentiation should be reported there.
