### ISSUE TITLE
Firedrake install issues

### ISSUE THREAD

**Issue by thangel** [firedrakeproject/firedrake#1094]
Hi! I am helping an UROP student in AMCG to get a setup with firedrake & thetis. We had some issues with sudo privileges earlier but now that seems to be sorted. However, the install seems to be crashing once it tries to install petsc.

I attach a log of the process in case it is of help. It hopefully is something straightforward that I am missing.

Than
[firedrake-install.txt](https://github.com/firedrakeproject/firedrake/files/1095213/firedrake-install.txt)

**Comment by miklos1** [comment]
checking whether a simple MPI-IO Fortran program can be linked... noconfigure: error: unable to link a simple MPI-IO Fortran program

Please try to compile a simple MPI Hello, world! in Fortran and see if that fails or succeeds.

**Comment by thangel** [comment]
Thanks Miklos, it turns out the problem had to do with the Fortran version in the system. If I remember correctly, we switched with Stephan to an earlier version of Fortran

**Comment by miklos1** [comment]
@thangel: so can we close this then?

**Comment by thangel** [comment]
It depends on whether this is a recurring issue with Fortran compatibility issues during the install that one might wish to look into . I have not encountered this before but now I guess I know how to overcome this so from my point of view it can be closed.
