### ISSUE TITLE
Creating FunctionSpace on an ExtrudedMesh with a high-order element is very slow

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#1098]
Too much time is spent [calculating bottom and top masks for geometric BCs](https://github.com/firedrakeproject/firedrake/blob/master/firedrake/functionspacedata.py#L211). The FInAT function that is called there uses GEM technology, and the algorithm used has not been optimised for elements with very many basis functions.

**Comment by wence-** [comment]
Yes, I noticed this as part of the variable layers stuff, but didn't dig into it.
