### ISSUE TITLE
install script ignores petsc configuration

### ISSUE THREAD

**Issue by malagala** [firedrakeproject/firedrake#1099]
hi,
i want to skip downloading eigen during the firedrake install; to this end i use

`curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install`
`PETSC_CONFIGURE_OPTIONS="--download-eigen=0" python firedrake-install`

as suggested before. however, i still see `Downloading Eigen from 'https://bitbucket.org/eigen/eigen/get/3.3.3.tar.gz' to 'eigen-3.3.3.tgz'` in the terminal, which indicates that this configuration didn't work

here is the install log:
[firedrake-install.txt](https://github.com/firedrakeproject/firedrake/files/1137800/firedrake-install.txt)

thanks for the help

**Comment by juan42** [comment]
This is due to a regression with the installation of Eigen with the PETSc installer. This lead to a patch from @wence- who took care of installation failures.

May i ask why you want to prevent the installation of Eigen?

**Comment by malagala** [comment]
thanks for responding

does that mean there is no way the eigen download can be disabled?

my reason is that, possibly due to my laptop not having enough ram, firedrake-install fails during the part of the script where it reads something along the lines of 'eigen tarball hash valid'

looking up previous issues related to this on github, i found that i most likely won't need it anyway (since i'm only using firedrake for a brief summer project and so won't be delving into anything too complex)

**Comment by juan42** [comment]
The Eigen install is just a tarball extraction. It doesn't compile anything so its not a limiting factor. The failure occurs here
```
gfortran: internal compiler error: Killed (program f951)
```
can you try to download PETSc and compile it seperately for testing? If that doesn't work consult the PETSc mailinglist, since they always have some advice for installation.

**Comment by wence-** [comment]
Hmmm, I agree with @juan42 here that this isn't an Eigen error.  Instead, as you say, during compilation of petsc there is an error.  This occurs when compiling the PETSc fortran interfaces.  How much ram does your laptop have?  This shouldn't be too expensive...

**Comment by danshapero** [comment]
I had the same issue when trying to install firedrake in a docker container. I was only able to fix it by increasing the memory available from 2G to 4G.
