### ISSUE TITLE
Fix cache dir location

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#1107]
**TODO**
- [x] There should be a single FIREDRAKE_CACHE_DIR environment variable, and the TSFC and PyOP2 chaches should default subdirectories of it.
- [x] The default value of FIREDRAKE_CACHE_DIR should be $VIRTUAL_ENV/cache

**RATIONALE**
- Independently setting the locations of the two caches is almost never needed and just confuses users.
- Having different firedrake installs share caches is a potential source of bugs.

**Comment by miklos1** [comment]
Thought it would be nice to set cache dir in `firedrake_configuration`.

**Comment by dham** [comment]
Potentially yes, though this would require a mechanism for users to modify the firedrake_configuration accordingly (currently it just records what they did during install)

**Comment by wence-** [comment]
We could set it in firedrake parameters, and have an update callback that pushes it out to os.environ?

**Comment by dham** [comment]
Isn't it the other way around?

**Comment by wence-** [comment]
I was just thinking about how you inform PyOP2 where the cache directory is.

**Comment by dham** [comment]
cf #1113

**Comment by wence-** [comment]
File arrive as part of #1108.

**Comment by wence-** [comment]
Fixed in #1114.
