### ISSUE TITLE
Error when trying to add two Globals

### ISSUE THREAD

**Issue by sebastkm** [firedrakeproject/firedrake#1121]
```
mesh = IntervalMesh(10, 0, 1)
V = FunctionSpace(mesh, "R", 0)
v = TestFunction(V)
f = assemble(v*dx)
f += f # Which results in f.dat += f.dat
```
This produces the error:
`TypeError: unsupported operand type(s) for +=: 'Global' and 'Global'`

**Comment by dham** [comment]
Confirmed. I'll have a go at adding the required operations on to Globals.

**Comment by dham** [comment]
Fixed in https://github.com/OP2/PyOP2/pull/531
