### ISSUE TITLE
--install-help vs --install_help

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#1127]
A small inconsistency/mistake I just noticed in the `firedrake-install` script.

Line 166 ("`firedrake-install`") has `parser.add_argument("--install-help"`, ...
Line 215 ("`firedrake-update`") has `parser.add_argument("--install_help"`, ...

The help strings in the lines above (165, 214) both refer to `install_help`; note that `python3 firedrake-install --install_help` actually fails.

The minimal change would be to change Line 166 to use `install_help`, however our other options use hyphens rather than underscores, so probably better to change the other references to hyphens.

**Comment by dorugeber** [comment]
Option was added in 8287c52, but the tweak 72e9844 wasn't thorough enough.

**Comment by dham** [comment]
This should definitely be hyphens in every case. I'll push a fix.

**Comment by wence-** [comment]
We should just change everything to `--install-help`.

**Comment by wence-** [comment]
Fixed in  3906a32
