### ISSUE TITLE
Complete boundary labels on topology once

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#1135]
I realised why I needed a globaltolocal in the boundary node creation routines, it was because when assembling into off-process entries I still need to discard.  Consider:

```python
from firedrake import *
from firedrake.mesh import _from_cell_list as create_dm
import numpy
from pyop2.datatypes import IntType

dm = create_dm(2, [[0, 1, 2],
                   [1, 2, 3],
                   [1, 3, 4]],
               [[0, 0],
                [1, 0],
                [0, 1],
                [0.5, 1],
                [1, 1]],
               COMM_WORLD)

dm.createLabel("Face Sets")

if COMM_WORLD.rank == 0:
    dm.setLabelValue("Face Sets", 14, 2)
    dm.setLabelValue("Face Sets", 13, 4)
    dm.setLabelValue("Face Sets", 11, 4)
    dm.setLabelValue("Face Sets", 10, 1)
    dm.setLabelValue("Face Sets", 8, 3)

if COMM_WORLD.rank == 0 and COMM_WORLD.size == 2:
    sizes = numpy.asarray([1, 2], dtype=IntType)
    points = numpy.asarray([0, 1, 2], dtype=IntType)
else:
    sizes = None
    points = None

mesh = Mesh(dm, reorder=False, distribute=(sizes, points))

V = FunctionSpace(mesh, "CG", 1)

u = TrialFunction(V)
v = TestFunction(V)

bc = DirichletBC(V, 0, 2)

assemble(u*v*dx, bcs=bc).M.handle.view()
```

This applies bcs to 2 rows of the matrix, but I get:
```
Mat Object: 2 MPI processes
  type: mpiaij
row 0: (0, 0.0833333)  (3, 0.0416667)  (4, 0.0416667) 
row 1: (1, 0.0833333)  (2, 0.)  (3, 0.)  (4, 0.0208333) 
row 2: (1, 0.)  (2, 1.)  (3, 0.) 
row 3: (0, 0.0416667)  (1, 0.)  (2, 0.)  (3, 1.)  (4, 0.0416667) 
row 4: (0, 0.0416667)  (1, 0.0208333)  (3, 0.0416667)  (4, 0.125) 
```

**Comment by wence-** [comment]
I shall do the quick fix to get this working again, but thinking about it, we do bc node determination sort of wrong.  We say:

> Nodes are on a subdomain boundary if they are in the closure of a facet that has a given marker.

But this may not get everything we want with the new halos.  Consider
```
+----+----+
|\ 1 | 2 /
| \  |  /
|  \ | /
| 0 \|/
+----+
```

With rank 0 owning cell 0 and rank 1 owning cells 1 and 2.  Imagine now applying a `DirichletBC` on the right-most facet.  That means that the bottom right node (in a CG1 function space) is killed.  But rank 0 doesn't know that that dof is on a boundary (because it only sees cell 1 which does not have an external facet attached to that node).

I think the more topologically correct way of doing things is to "complete" the boundary label onto entities in the closure of facets (calling `DMPlexLabelComplete`), this requires communication.  Then we can ask the label for all topological points with a given mesh marker, and create the appropriate boundary nodes that way.

Thoughts?

**Comment by wence-** [comment]
Fixed by #1136, but one could still do it "better" I think, at least for topological entities.

Assuming the relevant labels have been "completed", then this code DTRT:
```python
def topological_boundary_nodes(V, sub_domain):
    section = V.dm.getDefaultSection()
    dm = V.mesh()._plex
    ids = dm.getLabelIdIS("Face Sets").indices
    if sub_domain == "on_boundary":
        indices = ids
    else:
        assert not set(sub_domain).difference(ids)
        indices = sub_domain
    maxsize = 0
    for j in indices:
        for i in dm.getStratumIS("Face Sets", j).indices:
            if dm.getLabelValue("exterior_facets", i) == -1:
                continue
            maxsize += section.getDof(i)
    nodes = numpy.full(maxsize, -1, dtype=int)
    idx = 0
    for j in indices:
        for i in dm.getStratumIS("Face Sets", j).indices:
            if dm.getLabelValue("exterior_facets", i) == -1:
                continue
            off = section.getOffset(i)
            for k in range(section.getDof(i)):
                nodes[idx] = off + k
                idx += 1
    return numpy.unique(nodes[:idx])
```

**Comment by wence-** [comment]
For geometric, it's more complicated, I can do something, but it gives different results to currently.  Right now geometric boundary conditions are applied to dofs that have non-zero support on the facet.

At corners (where two different markers collide) this does something different to the case where you ask, which dofs have non-zero support on entities that are in the closure of the facet.

**Comment by lrtfm** [comment]
Are the elements in 'Face Sets' including the closure of the faces, i.e. including the vertex of the faces?

**Comment by wence-** [comment]
Since the merge of #2007, after the mesh is initialised, yes. All points in the closure of the faces are marked with the relevant label value.
