### ISSUE TITLE
Error when adding ufl.Zero to Function defined on Real elements

### ISSUE THREAD

**Issue by sebastkm** [firedrakeproject/firedrake#1141]
I don't know if this is supposed to be supported, but the following code block
```
mesh = IntervalMesh(10, 0, 1)
V = FunctionSpace(mesh, "R", 0)
f = Function(V)
f += 0*f

# or
v = TestFunction(V)
g = assemble(v*dx)
g += 0*f
```
produces
`AttributeError: 'NoneType' object has no attribute '_extruded'`

**Comment by dham** [comment]
Definitely a bug. Please file an issue and I’ll look at it when my normal life resumes after the H2020 deadline on 26 September


On 14 Sep 2017, at 14:20, Sebastian Mitusch <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't know if this is supposed to be supported, but the following code block

mesh = IntervalMesh(10, 0, 1)
V = FunctionSpace(mesh, "R", 0)
f = Function(V)
f += 0*f

# or
v = TestFunction(V)
g = assemble(v*dx)
g += 0*f


produces
AttributeError: 'NoneType' object has no attribute '_extruded'

**Comment by danshapero** [comment]
I'm closing this issue because I can't reproduce it on a recent install of Firedrake.
