### ISSUE TITLE
Error in Firedrake install - potentially due to old mpi in the system

### ISSUE THREAD

**Issue by thangel** [firedrakeproject/firedrake#1146]
Hi all, I was trying to install an updated version of firedrake in my machine and it failed. Stephan and I reckon that it must be because of the mpi version in my system.  (mpicc --version: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4 ).

I am moving to a newer workstation, but thought I would log this in case this needs to be looked at. It would be nice to have the latest version of firedrake on this machine too.

[firedrake-install.txt](https://github.com/firedrakeproject/firedrake/files/1317853/firedrake-install.txt)

**Comment by wence-** [comment]
Try now.

**Comment by thangel** [comment]
thanks, it worked now!
