### ISSUE TITLE
Python venv error? (Cannot import firedrake).

### ISSUE THREAD

**Issue by changyoonpark** [firedrakeproject/firedrake#1158]
Hi, thanks for the awesome software. I really want to try this out (I am using a Mac).

I am having issues within the venv. After installing, I enter the virtual environment with

`. (install dir)/firedrake/bin/activate`

after activation, I try

` python -c 'import firedrake'`

I get the following list of errors 

> *** Process received signal ***
> Signal: Segmentation fault: 11 (11)
> Signal code: Address not mapped (1)
> Failing at address: 0x0
> [ 0] 2   libsystem_platform.dylib            0x00007fffc68a4b3a _sigtramp + 26
> [ 1] 3   ???                                 0x00007fff524608a8 0x0 + 140734573709480
> [ 2] 4   libopen-pal.20.dylib                0x00000001102f17ca mca_base_framework_components_register + 42
> *** End of error message ***
> Segmentation fault: 11

I would appreciate it if I can get some support with this issue.

Thanks,
Chang

**Comment by miklos1** [comment]
Do you only get this when importing firedrake, or anytime you launch python in the venv?
