### ISSUE TITLE
Integration over undefined subdomains using an exodus mesh

### ISSUE THREAD

**Issue by DiSiKi** [firedrakeproject/firedrake#1162]
Hi,

during my work with firedrake and exodus meshes I accidentally forgot to declare subdomains in the mesh generation (with trelis).  If I run the code:
``` 
from firedrake import * 
mesh = Mesh('box.e')
V = VectorFunctionSpace(mesh, "CG", 1)
assemble(Constant(1.0)*ds(99,domain=mesh))
```
with the mesh
![box](https://user-images.githubusercontent.com/24552132/32771263-79e962f6-c922-11e7-9b74-82e82e946c36.jpg)
it returns ``` 0.0 ``` although the integration area is undefined.
Looking in the unique markers ```mesh.topological.exterior_facets.unique_markers``` gives ```[]```.

Using the same box meshed with Gmsh the code returns the expected Error:
```LookupError: {99} are not a valid markers (not in [0])```
Checking the unique markers  returns ```array([0], dtype=int32)```.

I am not sure if this is a desired behavior or an error.

Regards,
Dirk

**Comment by wence-** [comment]
Can you provide the mesh please for debugging? I don't have easy access to exodus-generated meshes.

Thanks!

**Comment by DiSiKi** [comment]
I sent you an e-mail with the mesh I used for testing.

**Comment by wence-** [comment]
Thanks, I think the referenced branch fixes things.

**Comment by DiSiKi** [comment]
Thanks a lot.
