### ISSUE TITLE
Is there a way to reuse LU factorization?

### ISSUE THREAD

**Issue by kamccormack** [firedrakeproject/firedrake#1185]
I am solving a time-dependent linear poroelastic problem. In fenics I use a mumps solver and save the factorization between timesteps with:

solver = LUSolver()
solver.set_operator(A)
solver.parameters["reuse_factorization"] = True

Is there an equivalent in Firedrake? Calling a mumps solver is more complicated, using:
            parameters = {
			"ksp_type": "preonly",
			'pc_type': 'lu',
			"pc_factor_mat_solver_package": "mumps"}

Is there any way to save the LU factorization here?

**Comment by wence-** [comment]
If you make a LinearVariationalSolver, then when you call solve in a loop the factorisation will be reused.

**Comment by wence-** [comment]
To expand slight on my answer:
```python

a = some_bilinear_form
L = some_linear_form
uh = Function(V) # solution variable

problem = LinearVariationalProblem(a, L, uh)
solver = LinearVariationalSolver(problem, solver_parameters={"ksp_type": "preonly", "pc_type": "lu", ...})

while ...:
    solver.solve() # Since a does not change, the factorisation in the PC will be reused.
```

You can also do this with assembled matrices:
```
A = assemble(a)
solver = LinearSolver(A, solver_parameters={...})

while ...:
    b = assemble(L)
    solver.solve(uh, b)
```

**Comment by kamccormack** [comment]
Thanks! Using the LinearSolver works great (I need to update the RHS within the time loop). 

I was trying to accomplish this with "solve(A, uh, L, bcs=self.bcs, solver_parameters=params)" and modify the solver parameters.

**Comment by wence-** [comment]
I note that if you use a `LinearVariationalSolver`, the right hand side will also be updated in the time loop for you.  For the variational solvers, we always solve in residual form `F(u) = 0`, and so we always update the residual every time you call `lvs.solve()`, but we reuse the jacobian.

**Comment by rckirby** [comment]
The problem with the original approach is that each successive call to
"solve" creates a new LinearVariationalSolver, which in turn creates a new
PETSc solver, so the factorization has to be recomputed.
