### ISSUE TITLE
Zenodo citation for Firedrake version used in TAS spectrum analysis

### ISSUE THREAD

**Issue by jychang48** [firedrakeproject/firedrake#1194]
{"firedrake": "c4b38f13d04e94fda6bfcf58c2e430bbb50b052f", "PyOP2": "4dca8adc4c2086d155c4847fd0f8424179b45df3", "tsfc": "020e55b9d670766e37c7282d5d03ae9956005123", "COFFEE": "029d2afcb0b0461802d9b793cd82b140cb749994", "ufl": "4fbc66b400fe07496a052b9e559af530d6e34b4a", "FInAT": "5b1aa340b64fc6470c1aebe91649ffdcfb328026", "fiat": "393c09d39af4486705a7b3e514db5559fe602ac0", "petsc": "b31f67cfb4c7be76d31008842d469cfb00db9b2c", "petsc4py": "dcee39638a23248f3ad8e12e6f8283bbbe6ed9aa", "message": "Version of Firedrake used in 'Comparative study of finite element methods using the Time-Accuracy-Size (TAS) spectrum analysis'"}

**Comment by jychang48** [comment]
It won't let me attach the firedrake.json file so I just copied and pasted the text here

**Comment by wence-** [comment]
Thanks Justin. I'll try and get these for you tomorrow.

**Comment by dham** [comment]
Here's the DOIs:
PyOP2: https://doi.org/10.5281/zenodo.1189452
FInAT: https://doi.org/10.5281/zenodo.1022065
COFFEE: https://doi.org/10.5281/zenodo.836678
FIAT: https://doi.org/10.5281/zenodo.1189458
Firedrake: https://doi.org/10.5281/zenodo.1135096
TSFC: https://doi.org/10.5281/zenodo.1189448
UFL: https://doi.org/10.5281/zenodo.1189453
PETSc: https://doi.org/10.5281/zenodo.1022071
petsc4py: https://doi.org/10.5281/zenodo.1022068
