### ISSUE TITLE
OpenMPI 3.0.0 + mpi4py breaks parallel tests.

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#1199]
There appears to be an issue which prevents subprocess launching of mpi jobs when mpi4py has been imported and the MPI library is OpenMPI 3.0.0

This causes all the parallel tests to fail because of the way the test launcher works. Note that this is not a problem in Firedrake itself and Firedrake will still work in parallel on machines with OpenMPI 3.0.0. 

The issue has been reported upstream: https://bitbucket.org/mpi4py/mpi4py/issues/95/

**Comment by danshapero** [comment]
Can this issue be closed now that Firedrake is building its own PETSc and MPICH?

**Comment by wence-** [comment]
I think so, yes.
