### ISSUE TITLE
Colour bar handling for plotting tools

### ISSUE THREAD

**Issue by bastorer** [firedrakeproject/firedrake#1201]
As a feature request it would be nice to be able to:
  1) pass a flag to firedrake.plot that turns off the colour bar (cbar=False, for example)
  2) pass an axes object for the colour bar (i.e. the cax argument in matplotlib.pyplot.colorbar) (cax=Ax_object, for example)

**Comment by wence-** [comment]
Hi, sorry for the late response.

I agree that this kind of stuff would be nice.  The plotting functionality is quite self-contained.  Would you like to have a go at doing this?  We can provide guidance if necessary.

**Comment by bastorer** [comment]
Sure, I'll take a crack at it. I'll let you know if I run into any problems.

**Comment by wence-** [comment]
Hi @bastorer, did you make any progress on this?
