### ISSUE TITLE
Assembled matrices on R always have type "python"

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#1204]
Consider the following code:

```
from firedrake import *

mesh = UnitSquareMesh(2, 2)
#V = FunctionSpace(mesh, "R", 0)
V = FunctionSpace(mesh, "CG", 1)
u = Function(V)
v = TestFunction(V)

F = inner(u, v)*dx

problem = NonlinearVariationalProblem(F, u)
solver  = NonlinearVariationalSolver(problem, solver_parameters={"mat_type": "aij"})

print(solver.snes.ksp.getOperators()[0].getType())
```

It yields `seqaij`, as expected.

But if instead I choose `V = FunctionSpace(mesh, "R", 0)`, then it yields `python`. This means I can't solve any algebraic problems (e.g. polynomials), as LU doesn't work.

**Comment by dham** [comment]
Isn't this just a PETSc limitation? Nothing about R space gives you anything which looks like a normal PETSc operator so we have to use nests and provide our own solver via the python interface.

**Comment by pefarrell** [comment]
Ah. I was expecting a 1x1 seqaij or dense matrix. I bumped into this because in defcon I call `ksp.solve` inside my wrapper that does the deflation, and I guess that doesn't know about firedrake's special tricks.

**Comment by pefarrell** [comment]
Ah. I was expecting a 1x1 seqaij or dense matrix. I bumped into this because in defcon I call `ksp.solve` inside my wrapper that does the deflation, and I guess that doesn't know about firedrake's special tricks.
