### ISSUE TITLE
Installation fails on ubuntu16.04 

### ISSUE THREAD

**Issue by ZhouleiJoeStone** [firedrakeproject/firedrake#1217]
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/1908501/firedrake-install.log)

**Comment by ZhouleiJoeStone** [comment]
when build PETSc, I got some error messages:
Traceback (most recent call last):
  File "firedrake-install", line 1072, in <module>
    install("petsc/")
  File "firedrake-install", line 552, in install
    build_and_install_petsc()
  File "firedrake-install", line 658, in build_and_install_petsc
    run_pip_install(["--ignore-installed", "petsc/"])
  File "firedrake-install", line 527, in run_pip_install
    check_call(pipinstall + pipargs)
  File "firedrake-install", line 364, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=env).decode())
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/zhoulei/zhoulei/Project/firedrake/firedrake/bin/python', '-m', 'pip', 'install', '--no-binary', 'mpi4py', '--no-deps', '-vvv', '--ignore-installed', 'petsc/']' returned non-zero exit status 1

**Comment by dorugeber** [comment]
Lines 1823-1828 of that log are
```
Error during download/extract/detection of METIS:
    Unable to download metis
    Could not execute "git clone https://bitbucket.org/petsc/pkg-metis.git /tmp/pip-_p11j5ov-build/arch-python-linux-x86_64/externalpackages/git.metis":
    Cloning into '/tmp/pip-_p11j5ov-build/arch-python-linux-x86_64/externalpackages/git.metis'...
    fatal: unable to access 'https://bitbucket.org/petsc/pkg-metis.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
    Unable to download package METIS from: git://https://bitbucket.org/petsc/pkg-metis.git
    ```

Perhaps there was a problem with your network connection at that time, or a problem with Bitbucket?  Delete the firedrake virtualenv folder and try running the install script again.

**Comment by ZhouleiJoeStone** [comment]
I'm new to firedrake, what is the firedrake virtualenv folder ? Where can I find it?

**Comment by stephankramer** [comment]
It will be a new folder called **firedrake**, located in the same place you ran the install script from. Remove that entire folder, and run the script again.

**Comment by ZhouleiJoeStone** [comment]
Thank you.
I try to delete firedrake and re-install it several times. But it  always failed.
Do I have to install firedrake totally from beginning by deleting firedrake folder when I want to re-install firedrake?
Is there anyway to re-install firedrake from last failed installation? Because I install firedrake through VPN in china, the network connection is not stable.

**Comment by aaronlhe** [comment]
Hi Zhoulei, seems that your network is unable to download METIS from https://bitbucket.org/petsc/pkg-metis/get/v5.1.0-p5.tar.gz

Can you try to download using the link manually first ?
________________________________

**Comment by ZhouleiJoeStone** [comment]
Thank you everyone! Finally, I successfully install firedrake with minimal_petsc.

**Comment by wence-** [comment]
Great!  In theory it would be possible to create an "offline" mode of firedrake-install that in step one just repeatedly tries to download all the necessary dependencies and then in step two actually builds and installs.  However, actually traversing the dependency tree properly is likely prone to error, so we don't do that.

Unfortunately, as you see, this does mean that you do need a stable internet connection during installation.
