### ISSUE TITLE
How to activate the venv of firedrake in spyder3

### ISSUE THREAD

**Issue by ZhouleiJoeStone** [firedrakeproject/firedrake#1218]
Hello!
In the installation document, the user can activate the venv in each shell from which you use Firedrake by the command "source firedrake/bin/activate". In the **Ubuntu terminal**, I successfully activate the firedrake environment. 
Now, I want to activate the firedrake environment in Spyder3. I try to "source firedrake/bin/activate" in the shell and run Spyder3 in the same shell, but Spyder3 can't detect the module named firedrake.
So, how can I use firedrake in Spyder3 ???

**Comment by wence-** [comment]
You need to tell Spyder where the python binary in the venv is located.  I think it might be sufficient to say in `Preferences -> Python interpreter` to use the python in the venv (type `which python` after activating the venv in the shell).

This lack of ease of switching between virtual environments seems to be a known issue with Spyder (e.g. see discussion at spyder-ide/spyder#5852).

**Comment by ZhouleiJoeStone** [comment]
Thank you @wence- . It works.

**Comment by duyuan11** [comment]
My solution is 


source firedrake/bin/activate
which python # tell the path 
pip install spyder # You must do this! 
spyder
Tools->Preferences->Python interpreter
