### ISSUE TITLE
Supplying a mix of "on_boundary" and integer subdomain DirichletBCs

### ISSUE THREAD

**Issue by andreasbock** [firedrakeproject/firedrake#1226]
I have inherited `DirichletBC` to set certain `Discontinuous Lagrange Trace` variables to zero on the interior mesh according to my variational problem. In this connection I have discovered a bug in line 490 of `firedrake/firedrake/functionspacedata.py`. I am providing a list of `DirichletBCs` objects e.g.:

```bcs = [DirichletBC(V, val, "on_boundary"), MyCustomDirichletBC(V, val, dummy_domain, my_custom_params)```

 to the `solve(a == L, bcs=bcs)` interface leads to a

```TypeError: '<' not supported between instances of 'tuple' and 'str'```. 

Only the `self.nodes` of my `MyCustomDirichletBC` is actually used, not the `dummy_domain`.

**Comment by wence-** [comment]
FWIW, very late to the party, this was fixed in #1418.
