### ISSUE TITLE
Reference request for R space

### ISSUE THREAD

**Issue by CsatiZoltan** [firedrakeproject/firedrake#1231]
Firedrake writes about the [R space](https://www.firedrakeproject.org/r-space.html). Could you provide me some references (books, articles) where I can read more about it? I am interested in the theoretical aspects.

**Comment by dorugeber** [comment]
This is just the space of constant functions (constant over the domain, not just each cell).  Equivalent to real numbers.

**Comment by CsatiZoltan** [comment]
Ok, thanks.
