### ISSUE TITLE
Unexpected behaviour of bc.homogenize()

### ISSUE THREAD

**Issue by florianwechsung** [firedrakeproject/firedrake#1237]
While lifting some bcs by hand and I noticed that `bc.homogenize()` can result in some unexpected behaviour. Here is a minimal example, i would have expected that the two solves give the same results.

```
from firedrake import *

mesh = UnitSquareMesh(100, 100)
V = FunctionSpace(mesh, "CG", 1)

u = TrialFunction(V)
v = TestFunction(V)
bc = DirichletBC(V, 1, "on_boundary")

A = inner(u, v)* dx + inner(grad(u), grad(v))*dx
b = inner(Constant(1), v)*dx

hbc1 = bc.homogenize()
hbc2 = DirichletBC(V, 0, "on_boundary")

u1 = Function(V)
solve(A == b, u1, hbc1)

u2 = Function(V)
solve(A == b, u2, hbc2)

print(assemble(inner(u1-u2, u1-u2) * dx))

```

**Comment by wence-** [comment]
`bc.homogenize()` homogenises `bc` in place and returns `None`.  So `hbc1` is actually `None` in this case.

If you want a homogenized version of a bc separately, use the free function `homogenize`:

```python
bc = ...
hbc = homogenize(bc)
...
```

**Comment by florianwechsung** [comment]
Oh of course, I'll go hide in shame now...  Closed.
