### ISSUE TITLE
Install issue with HDF5

### ISSUE THREAD

**Issue by jhill1** [firedrakeproject/firedrake#1243]
Hi,
Looks like there's an issue with downloading HDF5 from https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.18.tar.gz (I get a 404 error in the browser).

Log attached for info.
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/2118579/firedrake-install.log)

**Comment by dorugeber** [comment]
That link hasn't worked for a long time, but the backup sources are also down right now: https://lists.mcs.anl.gov/pipermail/petsc-users/2018-June/035574.html

**Comment by drhodrid** [comment]
I was having the same issues as @jhill1 yesterday, but seems to be fixed now.

**Comment by jhill1** [comment]
Likewise. Seems to have worked just now. Closing.
