### ISSUE TITLE
Installation Fails due to version libtool

### ISSUE THREAD

**Issue by sniperlucian** [firedrakeproject/firedrake#1254]
Trying to install with scrip as explained. However it fails installing libspatialindex due to wrong version of libtool, see below.

Please help to proceed ....

Making all in src
make[1]: Entering directory '/home/user/work/FEM/firedrake/src/libspatialindex/src'
Making all in storagemanager
make[2]: Entering directory '/home/user/work/FEM/firedrake/src/libspatialindex/src/storagemanager'
depbase=`echo Buffer.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../../libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"spatialindex\" -DPACKAGE_TARNAME=\"spatialindex-src\" -DPACKAGE_VERSION=\"1.8.6\" -DPACKAGE_STRING=\"spatialindex\ 1.8.6\" -DPACKAGE_BUGREPORT=\"mhadji@gmail.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DPACKAGE=\"spatialindex-src\" -DVERSION=\"1.8.6\" -DHAVE_FCNTL_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_PTHREAD_H=1 -DHAVE_SYS_RESOURCE_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_STDINT_H=1 -DHAVE_FEATURES_H=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MEMSET=1 -DHAVE_MEMCPY=1 -DHAVE_BCOPY=1 -DHAVE_SRAND48=1 -I. -I../../include     -Wall -Wno-long-long -pedantic -std=c++98  -O2 -DNDEBUG -MT Buffer.lo -MD -MP -MF $depbase.Tpo -c -o Buffer.lo Buffer.cc &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: Version mismatch error.  This is libtool 2.4.2, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2
libtool: and run autoconf again.
Makefile:391: recipe for target 'Buffer.lo' failed
make[2]: *** [Buffer.lo] Error 63
make[2]: Leaving directory '/home/user/work/FEM/firedrake/src/libspatialindex/src/storagemanager'
Makefile:406: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/user/work/FEM/firedrake/src/libspatialindex/src'
Makefile:533: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by miklos1** [comment]
Perhaps your libtool is too old? [This](https://savannah.gnu.org/forum/forum.php?forum_id=6987) suggests that libtool 2.4.2 was released 7 years ago... What system are you installing on?

**Comment by sniperlucian** [comment]
wow fast ;)

you right - just figured out that anaconda is messing, since it has included the old version. Any suggestion how to let anaconda in parallel ?

**Comment by miklos1** [comment]
`firedrake-install` does not work on anaconda python, because anaconda does not support virtual environments. You need to use another Python distribution, version 3.5 or later.

**Comment by sniperlucian** [comment]
anaconda actually support and manages virtualenv 

https://conda.io/docs/user-guide/tasks/manage-environments.html


but seems it doesnt get allong with the venv created by firedrake installation. firedrake seems to work fine now, just need to find out how to install jupyter inside of this venv.

**Comment by miklos1** [comment]
I usually just `pip install jupyter` inside the venv and then run it from there.
