### ISSUE TITLE
PyOP2/TSFC error using conditional in complex

### ISSUE THREAD

**Issue by orpembery** [firedrakeproject/firedrake#1255]
In the complex branch, using `ufl.And` to define a subdomain via a conditional expression results in a PyOP2 error.

According to @wence-, it looks like TSFC is dropping the `real()` function surrounding the coordinates.

Attached files:
[compile-errors.txt](https://github.com/firedrakeproject/firedrake/files/2219289/compile-errors.txt)
[compile-log.log](https://github.com/firedrakeproject/firedrake/files/2219290/compile-log.log)
[terminal-error-log.log](https://github.com/firedrakeproject/firedrake/files/2219291/terminal-error-log.log)
[mwe.txt](https://github.com/firedrakeproject/firedrake/files/2219292/mwe.txt)

(compile-errors.txt and mwe.txt should be '.err' and '.py' respectively, but GitHub wouldn't allow them to be uploaded)

Running mwe.py in the complex branch reproduces the error.

I obtained terminal-error-log.log as output to the terminal, and the compile errors and log are contained in compile-errors.txt and compile-log.log respectively.

**Comment by dham** [comment]
confirmed. the compiler is overly aggressive in dropping real nodes. I'll try to get to the bottom of this tomorrrow

**Comment by miklos1** [comment]
not confirmed yet, but quite possibly `real(x[0])` is assigned to a temporary variable through common subexpression elimination, and of course the type of that temporary variable is `double complex`...

**Comment by miklos1** [comment]
> quite possibly `real(x[0])` is assigned to a temporary variable through common subexpression elimination, and of course the type of that temporary variable is `double complex`...

Suspicion confirmed:
```c
    double complex  t3  = creal(creal((((((0.333333333333333) * (coords[0]))) + (((0.333333333333333) * (coords[2]))))) + (((0.333333333333333) * (coords[4])))));
```

**Comment by miklos1** [comment]
Forwarded this issue to firedrakeproject/tsfc#171.
