### ISSUE TITLE
Solving with preassembled matrix into *vector* solution appears broken

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#1262]
There are tests for preassembled matrices, but they all solve into a function. If I make the following change however:
```
$ git diff tests/regression/test_solving_interface.py
diff --git a/tests/regression/test_solving_interface.py b/tests/regression/test_
index fd6a377..fc70331 100644
--- a/tests/regression/test_solving_interface.py
+++ b/tests/regression/test_solving_interface.py
@@ -134,7 +134,7 @@ def test_linear_solves_equivalent():
 
     # Solve the system using preassembled objects
     sol3 = Function(V)
-    solve(assemble(a), sol3, assemble(L))
+    solve(assemble(a), sol3.vector(), assemble(L))
     assert np_norm(sol.vector()[:] - sol3.vector()[:]) < 5e-14
```
I get the following error when running the test:
```
tests/regression/test_solving_interface.py:137: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
firedrake/solving.py:126: in solve
    return _la_solve(*args, **kwargs)
firedrake/solving.py:227: in _la_solve
    lvp = vs.LinearVariationalProblem(a=A.a, L=0, u=x, bcs=bcs)
firedrake/variational_solver.py:270: in __init__
    F = ufl_expr.action(J, u)
firedrake/ufl_expr.py:192: in action
    return ufl.action(form, coefficient)
../ufl/ufl/formoperators.py:118: in action
    return compute_form_action(form, coefficient)
../ufl/ufl/algorithms/formtransformations.py:421: in compute_form_action
    return replace(form, {u: coefficient})
../ufl/ufl/algorithms/replace.py:61: in replace
    mapping2 = dict((k, as_ufl(v)) for (k, v) in mapping.items())
../ufl/ufl/algorithms/replace.py:61: in <genexpr>
    mapping2 = dict((k, as_ufl(v)) for (k, v) in mapping.items())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

expression = <firedrake.vector.Vector object at 0x7fcf93203eb8>

    def as_ufl(expression):
        "Converts expression to an Expr if possible."
        if isinstance(expression, Expr):
            return expression
        elif isinstance(expression, float):
            return FloatValue(expression)
        elif isinstance(expression, int):
            return IntValue(expression)
        else:
            raise UFLValueError("Invalid type conversion: %s can not be converted"
>                               " to any UFL type." % str(expression))
E           ufl.log.UFLValueError: Invalid type conversion: <firedrake.vector.Vector object at 0x7fcf93203eb8> can not be converted to any UFL type.

../ufl/ufl/constantvalue.py:413: UFLValueError
```

This used to work and is currently breaking firedrake_adjoint where it is used [here](https://bitbucket.org/dolfin-adjoint/pyadjoint/src/735301ddcb9dfc166cbc8b389da0bc30eb41d7b9/fenics_adjoint/solving.py?at=master&fileviewer=file-view-default#solving.py-162) where in the case of firedrake_adjoint `linalg_solve==firedrake.solve`. This breaks any adjoint calculation with SolveBlocks (e.g. the tests/firedrake_adjoint/test_burgers_newton.py pyadjoint test).

This change seems to have been introduced in the ee7a253db98b89935ac90f779b41e51a9fd695c4 merge (1951865852cb316f93ac51e31be3ea19b72ff701 works).

**Comment by wence-** [comment]
Does this fix things?

```diff
diff --git a/firedrake/solving.py b/firedrake/solving.py
index cfc099de..407bb0aa 100644
--- a/firedrake/solving.py
+++ b/firedrake/solving.py
@@ -25,6 +25,7 @@ import firedrake.linear_solver as ls
 import firedrake.variational_solver as vs
 from firedrake import solving_utils
 from firedrake import dmhooks
+import firedrake
 
 
 def solve(*args, **kwargs):
@@ -224,6 +225,8 @@ def _la_solve(A, x, b, **kwargs):
                              options_prefix=options_prefix)
 
     # linear MG doesn't need RHS, supply zero.
+    if isinstance(x, firedrake.Vector):
+        x = x.function
     lvp = vs.LinearVariationalProblem(a=A.a, L=0, u=x, bcs=bcs)
     mat_type = solver_parameters.get("mat_type")
     appctx = solver_parameters.get("appctx", {})
```

**Comment by stephankramer** [comment]
Ugh, sorry hadn't seen that master appears to be generally broken: test_solving_interface.py doesn't pass without my change either. The two lines further down:

     mat_type = solver_parameters.get("mat_type")
     appctx = solver_parameters.get("appctx", {})

are also problematic. If solve is called for a pre-assembled matrix with no solver_parameters argument, then solver_parameters is None at that point. I'm not entirely sure what the correct fix for mat_type is, should it be obtained from the provided matrix A?

**Comment by wence-** [comment]
Oh, how did this stuff ever pass, or maybe I just didn't check (I thought I did).  We should definitely turn `solver_parameters=None` into `solver_parameters = {}`.  The `mat_type` is known in `assemble`, but not explicit in the `Matrix` object.  Can you add that?

**Comment by stephankramer** [comment]
Fix here: https://github.com/firedrakeproject/firedrake/tree/fix-preassembled-solve
Passes regression tests locally. I do have a failing demo (geometric_multigrid). Let's see what Jenkins says.

Reason I ask about `mat_type` is that even with `solver_parameters={}` we have `mat_type=None` and it isn't immediately obvious to me whether that's a valid argument value for `_SNESContext` where it is a required argument.

**Comment by wence-** [comment]
This GMG demo fails seemingly at random (I can never reproduce).  Perhaps it can be run under valgrind to give a clue?

I think we do need to deduce the mat_type (and pmat_type) from the provided matrices.  I think that needs adding this information to the `Matrix` class so we can get it easily.  An ImplicitMatrix could get a class property `mat_type = "matfree"`, at the point of calling `assemble` when we construct a `Matrix`, we know the mat_type, and so could set it.
