### ISSUE TITLE
Install firedrake on macOS

### ISSUE THREAD

**Issue by matlong** [firedrakeproject/firedrake#1281]
Someone can help me to resolve my installation bugs please? 

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/2353090/firedrake-install.log)

**Comment by wence-** [comment]
Hmm, it's not obvious that anything broke.  Can you run `brew doctor` and post the output please?

**Comment by matlong** [comment]
Here are the outputs :

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/lauxlib.h
  /usr/local/include/lua.h
  /usr/local/include/luaconf.h
  /usr/local/include/lualib.h

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/liblua.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  pkg-config
  libtiff
  gmp
  python@2
  libpng
  freetype
  mpfr
  hdf5
  gcc
  webp
  emacs
  lua
  fontconfig
  netcdf
  gd
  node
  udunits
  jpeg
  fftw
  szip
  git
  libmpc

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

**Comment by matlong** [comment]
Thanks for your answer, however I got new issues as :

Building PETSc. 
Depending on your platform, may take between a few minutes and an hour or more to build!
Traceback (most recent call last):
  File "firedrake-install", line 1120, in <module>
    install("petsc/")
  File "firedrake-install", line 622, in install
    build_and_install_petsc()
  File "firedrake-install", line 728, in build_and_install_petsc
    run_pip_install(["--ignore-installed", "petsc/"])
  File "firedrake-install", line 597, in run_pip_install
    check_call(pipinstall + pipargs)
  File "firedrake-install", line 435, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=env).decode())
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 376, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/Users/loli/firedrake/bin/python', '-m', 'pip', 'install', '--no-binary', 'mpi4py', '--no-deps', '-vvv', '--ignore-installed', 'petsc/']' returned non-zero exit status 1.

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/2353829/firedrake-install.log)

**Comment by matlong** [comment]
Hi, thanks for your answer, here is the mpi issue :

` use mpi
   1
Erreur fatale: Cannot read module file « mpi.mod » opened at (1), because it was created by a different version of GNU Fortran `

And here are information about my gfortran : 

`Utilisation des specs internes.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/gfortran/libexec/gcc/x86_64-apple-darwin16/6.3.0/lto-wrapper
Cible : x86_64-apple-darwin16
Configuré avec: ../gcc-6.3.0/configure --prefix=/usr/local/gfortran --enable-languages=c,c++,fortran,objc,obj-c++ --build=x86_64-apple-darwin16 --with-gmp=/Users/fx/devel/gcc/deps-static/x86_64 --with-mpfr=/Users/fx/devel/gcc/deps-static/x86_64 --with-mpc=/Users/fx/devel/gcc/deps-static/x86_64 --with-isl=/Users/fx/devel/gcc/deps-static/x86_64
Modèle de thread: posix
gcc version 6.3.0 (GCC)`

**Comment by matlong** [comment]
OK, please have a look these outputs :

`mpif90 -show

gfortran -I/usr/local/Cellar/open-mpi/3.1.2/include -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/usr/local/Cellar/open-mpi/3.1.2/lib -L/usr/local/opt/libevent/lib -L/usr/local/Cellar/open-mpi/3.1.2/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi`

`which gfortran

/usr/local/bin/gfortran`

**Comment by wence-** [comment]
OK, the `mpif90` line looks good, and in theory the `gfortran` one looks good too.  But it seems that that gfortran is not supplied by homebrew.  I have something like:

```
$ gfortran --version
GNU Fortran (Homebrew GCC 8.1.0) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

And
```
$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/8.1.0/libexec/gcc/x86_64-apple-darwin17.5.0/8.1.0/lto-wrapper
Target: x86_64-apple-darwin17.5.0
Configured with: ../configure --build=x86_64-apple-darwin17.5.0 --prefix=/usr/local/Cellar/gcc/8.1.0 --libdir=/usr/local/Cellar/gcc/8.1.0/lib/gcc/8 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-8 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-checking=release --with-pkgversion='Homebrew GCC 8.1.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-nls
Thread model: posix
gcc version 8.1.0 (Homebrew GCC 8.1.0)
```

Whereas your gfortran is version 6.3.0.  So I conclude that `/usr/local/bin/gfortran` is probably not being provided by homebrew.

Did you try fixing the "brew link" errors that were reported by `brew doctor`?
If it is correctly installed, the gfortran binary should be something like:

```
$ ls -l $(which gfortran)
lrwxr-xr-x  1 xxx xxx  32  6 Jul 11:30 /usr/local/bin/gfortran -> ../Cellar/gcc/8.1.0/bin/gfortran
```

**Comment by matlong** [comment]
Right, I reinstall and relink gcc with brew, finally problems are resolved, alltest are passed. Thank you very much.

**Comment by wence-** [comment]
Wonderful!  Do let us know if you run into any other problems.  I'll close this issue now.
