### ISSUE TITLE
Bessel functions inside PyOP2 kernels return 0

### ISSUE THREAD

**Issue by benSepanski** [firedrakeproject/firedrake#1290]
When called from PyOP2 function, bessel functions (in particular j0, j1, jn, and y0, y1, yn) return a value of 0.0.

Note that calling an equivalent function in a C file after running gcc -lm foo.c returns the correct values

As an example, when I run the below code, it prints a value of 0.0 rather than the correct 0.009.
`from pyop2 import op2

eval_bessel = op2.Kernel("""
void eval_bessel(double* bes_val, double* x) {
    *bes_val = j0(*x);
}
""", "eval_bessel")

singleton = op2.Set(1)

x = op2.Dat(singleton, [2.387])
bessel_at_x = op2.Dat(singleton, [0.0])

op2.par_loop(eval_bessel, singleton, bessel_at_x(op2.WRITE), x(op2.READ))

print(bessel_at_x.data[0])`

**Comment by stephankramer** [comment]
The issue appears to be that the PyOP2 is compiled in C99 mode (`-std=C99`) which restricts some of the functions offered by `math.h` including the Bessel functions. You can probably reproduce this in your standalone code with `gcc -std=C99 foo.c -lm`. It still compiles, but uses an "implicit function declaration" which incorrectly assumes the result to be integer. To include the Bessel functions in `math.h` you can add:

     op2.configuration['cflags'] = '-D_XOPEN_SOURCE'

**Comment by benSepanski** [comment]
Thank you! This fixed it.
