### ISSUE TITLE
Firedrake installed correctly but make all test does not finish cleanly

### ISSUE THREAD

**Issue by emersodb** [firedrakeproject/firedrake#1305]
I've attached both the install log and the make all test output
[error.txt](https://github.com/firedrakeproject/firedrake/files/2454474/error.txt)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/2454475/firedrake-install.log)

**Comment by dham** [comment]
Hi, this is a known issue with the test harness. Basically, the test harness fails to run parallel tests on MacOS at the moment due to limitations in OpenMPI 3. Firedrake still works fine in parallel on Mac, it's just the tests which fail. You actually have a working install.
