### ISSUE TITLE
Install issue on Ubuntu 17.10

### ISSUE THREAD

**Issue by cjlh** [firedrakeproject/firedrake#1313]
Hi,

I'm trying to install Firedrake on Ubuntu 17.10, however the install script fails when trying to build PETSc. The terminal output is:

```
[...]

uccessfully cloned repository COFFEE
Checking out branch master
Successfully checked out branch master
Installing petsc/
Downloading Eigen from 'https://bitbucket.org/eigen/eigen/get/3.3.3.tar.gz' to 'eigen-3.3.3.tgz'
Checking Eigen tarball integrity
Eigen tarball hash valid
Building PETSc. 
Depending on your platform, may take between a few minutes and an hour or more to build!
Traceback (most recent call last):
  File "firedrake-install", line 1120, in <module>
    install("petsc/")
  File "firedrake-install", line 622, in install
    build_and_install_petsc()
  File "firedrake-install", line 728, in build_and_install_petsc
    run_pip_install(["--ignore-installed", "petsc/"])
  File "firedrake-install", line 597, in run_pip_install
    check_call(pipinstall + pipargs)
  File "firedrake-install", line 435, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=env).decode())
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/caleb/university/Level 3/L3 Project/Firedrake/firedrake/bin/python', '-m', 'pip', 'install', '--no-binary', 'mpi4py', '--no-deps', '-vvv', '--ignore-installed', 'petsc/']' returned non-zero exit status 1.


Install log saved in firedrake-install.log
```

And my log file is attached.

I tried to delete the created `firedrake` dir + log file and reinstall with the `--minimal-petsc` option, and with `PETSC_CONFIGURE_OPTIONS` set to `--download-eigen=0`, but neither of these seem to help at all in solving the issue.

Any help would be much appreciated.

Cheers.

**Comment by dham** [comment]
The first thing that I notice is that there are spaces in your directory names. While this is theoretically allowed, a *lot* of software does not handle this correctly. I bet something in the PETSc build process is not safe against spaces in paths. Please try installing Firedrake somewhere where there are no spaces in the paths. If that fails, please then post the `firedrake-install.log` file you get as that contains much more debugging information.

**Comment by wence-** [comment]
Here's the log: [firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/2495543/firedrake-install.log)

The pertinent line in the PETSc configure failure:

```
Invalid download location: /home/caleb/university/Level for key download-eigen
```

So I think indeed the spaces are causing all the trouble. Can you try again following @dham's suggestion and run again in a directory with no spaces in the name.

(We should probably check this early on and bail out with a useful error message).

**Comment by cjlh** [comment]
@dham Apologies, it appears I actually forgot to attach the log file before submitting.

I've re-ran the install script in a path without spaces, and it all appears to have installed correctly. Thanks to the both of you for your help!
