### ISSUE TITLE
Installing Paraview after Firedrake clobbers mpich with openmpi for mpirun

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#1325]
(This is on a clean Ubuntu 18.04.1)

This has a nasty failure mode: `mpirun -n X python foo.py` simply runs X independent copies of foo.py, with no obvious indication to the user that the _wrong thing_ is happening.

Can be fixed with `sudo update-alternatives --config mpirun`, and choosing the mpich option, at least if you have admin rights.

Two suggestions:
1) Ideally, the right mpirun should be used automatically (within the virtualenv, if not system-wide)
2) Some way of (automatically) verifying that `mpirun -n X` isn't just running X serial copies.

**Comment by dorugeber** [comment]
Definitely not all @jandrej's fault ;-)

**Comment by wence-** [comment]
What installed mpirun?
In the install script we can do:

`mpirun -n 2 python -c "import mpi4py; from mpi4py import MPI; if MPI.COMM_WORLD.size != 2: raise RuntimeError"` or similar?

**Comment by wence-** [comment]
These days our preferred way of fixing this is telling
`firedrake-install` what mpicc, mpicxx, mpirun, etc... you are going
to use. This then puts symlinks in the virtualenv bin directory, so
when you activate it, you get the right versions of everything.
