### ISSUE TITLE
Is there an elegant way to detect whether a form evaluates to a zero matrix?

### ISSUE THREAD

**Issue by thomasgibson** [firedrakeproject/firedrake#1326]
Consider the following example:
```python
from firedrake import *
from firedrake.formmanipulation import split_form

mesh = UnitSquareMesh(8, 8)
V = FunctionSpace(mesh, "RT", 1)
U = FunctionSpace(mesh, "DG", 0)
W = V * U

u, phi = TrialFunctions(W)
v, psi = TestFunctions(W)

form = inner(u, v)*dx - phi*div(v)*dx + div(u)*psi*dx
split_forms = dict(split_form(form))
```

This corresponds a mixed discretization of the Poisson equation. In terms of global matrices:
```
| A -B^T |
| B    C |
```
The (1,1)-block (`C`) is a zero matrix. The split form corresponding to this block (`split_forms[1, 1]`) is a form with integrands containing (nested within indexed `ListTensor`s) the `ufl.classes.Zero` object.

My question: is there a nice, elegant way to check whether a given form is just going to be a zero-block? Or do I just need to write some sort of function that dives into the expression and searches for `Zero` operands? I would rather not reproduce any existing functionality if I don't need to!

**Comment by wence-** [comment]
What do you need this for? UFL simplifies late because it is expensive to do.

**Comment by thomasgibson** [comment]
I would like to start trying to do zero-simplification in Slate. Currently, if you want to assemble the expression `C + B  * A.inv * B.T` and `C` happens to be a zero matrix, then we generate a temporary for `C` initialized to zero and go from there. Zero temporaries will alway be created and you can imagine how this occurs in more complex expressions. I think it's a bit wasteful and want to attempt to remove these in the compiler. Do you beleive it's not worth doing?

**Comment by wence-** [comment]
When you call tsfc you know if the form is zero (tsfc makes an empty kernel). So drop it then.

**Comment by wence-** [comment]
Do you still need to do this? I guess it's dropped down the list a
bit. I think the right way if to compile the terminals with TSFC, see
if they are zero, and do zero-simplification on reconstruction at that
point.

**Comment by wence-** [comment]
I think this will fall out by magic in the @sv2518 slate->gem transition.
