### ISSUE TITLE
Using spectral elements and GPU support?

### ISSUE THREAD

**Issue by CarlosCuetoM** [firedrakeproject/firedrake#1345]
Hi! 

I’ve been looking into firedrake as a possible library for an acoustic wave propagation project and I wanted to ask a couple things, in case you could orient me about it:

- I’ve seen there’s currently no support for GPU, but have seen mentions here and there about it. Are there plans to support it at some point?
- Is it possible to do spectral elements in fenics? With spectral referring to using Legendre polynomials at the GLL collocation points, which should result in a diaginal mass matrix.

Thanks!

**Comment by dham** [comment]
Hi Carlos,

Thanks for your interest. We did do some work on GPUs a number of years back. Coincidentally there is now a PhD student who is interested in GPUs so it's possible that in a year or so we might have some capability again, but no guarantees.

On spectral elements I have better news. Firedrake supports GL and GLL elements on intervals, quads and (structured) hexahedra. Furthermore we automatically generate sum factorised code, so the spectral element support uses the optimal complexity assembly algorithms. The form compiler does also notice the diagonalisation cancellation, though at the moment you still get a full sparse matrix structure which happens to be diagonal (there are ways around this but they are slightly hacky). 

We also support matrix-free solvers and preconditioners, including GMG. This is presumably also important to you if you want spectral elements.

Finally, I will cheekily point out that you asked about FEniCS. FEniCS doesn't support high order elements on quads and hexes - you need Firedrake for that!

**Comment by CarlosCuetoM** [comment]
Hi David,


Thanks for the quick response. The possibility of having GPU support at some point is encouraging, although not the highest priority at the moment, so we could live with the current status. Is there any particular reason why you didn't continue with that GPU work back then?

The support for spectral elements is quite relevant, as I think it could bring us great performance gains, and I appreciate you pointing out the lack for it in FEniCS, I hadn't had much response to my question there!

I will start playing with the available examples and reading the documentation, and might try to implement an spectral element toy script for the acoustic wave equation to see how that looks.


Thanks!
Carlos

**Comment by dham** [comment]
Basically, back then we didn't have a sane way of assembling matrices on a GPU, and we couldn't do matrix free. Now there still isn't a good way to do matrix assembly on a GPU, but we can do matrix free, so it's more interesting. We're also in the process of replacing our final code generation layer with Loo.py, which can generate OpenCL and CUDA, so we have a potential pathway to GPU.

**Comment by rckirby** [comment]
Carlos, Please check out the matrix-free demos -- those grow out of the
work I did with Lawrence Mitchell:
https://epubs.siam.org/doi/pdf/10.1137/17M1133208
He has also greatly extended this to hook up GMG and many other things
under the same interface.

We have some support for Schoeberl's additive Schwarz (solve Q^1 on the
original mesh coupled with vertex-patch problems), although I believe this
isn't supported on extruded meshes (so you get quads but not hexes).

It should be possible to do this, as well as set up the Q_1^{iso)/Q_k
preconditioner for a generic bilinear form, although it will take some
legwork to make the resulting matrix come out sparse.  This is a to-do on a
recently-submitted grant proposal.

So, there's a lot we do support, but still work to be done on this.

**Comment by CarlosCuetoM** [comment]
Thanks David and Robert. That all sounds great, I'm looking forward to diving into firedrake as soon as I have some spare time, I think it all looks great. I might come up with a million more questions about existing functionality as I go, though!
