### ISSUE TITLE
Proposal: deprecate `bc.apply(some_matrix)`

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#1362]
The use of `bc.apply` to apply boundary conditions to an already assembled matrix is an unfortunate API-compatibility wart with dolfin. Arguably we have trained our users enough by now to use the form `assemble(a, bcs=bc)` instead, and we could deprecate, and then remove the ability to say:
```python
A = assemble(a)
for bc in bcs:
   bc.apply(A)
```

This would simplify the internal logic in both the matrix classes, and matrix assembly (which would no longer have to defer things until point of use).

WDOT?

**Comment by dham** [comment]
Yes. Let's do it.

**Comment by wence-** [comment]
Will happen in purge of lazy evaluation.

**Comment by wence-** [comment]
This was fixed in the merge of #1429.
