### ISSUE TITLE
errors while running tests on ubuntu

### ISSUE THREAD

**Issue by bastringue** [firedrakeproject/firedrake#1364]
Hello, while running make alltest, i get these errors...could you please tell me what can i do to fix this ? Thank you, 
Pierre
[log.txt](https://github.com/firedrakeproject/firedrake/files/2799047/log.txt)

**Comment by dham** [comment]
It rather strongly looks like the install failed. Can you please post firedrake-install.log. This should be in the directory containing the top level firedrake directory.

**Comment by bastringue** [comment]
Thanks for answering Dham, 
I have given up (for now): I test 'fenics' first and I come back to firedrake after...
Best regards
