### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by cjunho** [firedrakeproject/firedrake#1374]
I think the installation goes well. But when I run "the Simple Helmholtz equation" on introductory tutorials, "NameError: name 'UnitSquareMesh' is not defined" happens. How can I correct?
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/2843403/firedrake-install.log)

**Comment by wence-** [comment]
Apologies for the slow response. If I look in the install log I see:

```
2019-02-08 02:01:20,363 DEBUG  pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
```

and then:

```
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
```

So for whatever reason it looks like Python was installed without support for SSL. How did you obtain it?
