### ISSUE TITLE
Zenodo DOI for Model order reduction 

### ISSUE THREAD

**Issue by DiSiKi** [firedrakeproject/firedrake#1375]
Hello,
could somebody please generate a zenodo DOI for this firedrake.json file?

{"firedrake": "556fec2d04d05f31de2b19c728358c1a4a39100b", "PyOP2": "df3f03a371654444b3bc7deade0759f8ee9314ce", "tsfc": "3e8f358485eedbbcdf36bb5852cebe8b4e3bf28e", "COFFEE": "72a4464aa18fd408de5304ac467db18d7af2b670", "ufl": "5e6ed4230ce0aa7ccd7898ea2a342210e6df8605", "FInAT": "de6f2ab96464f81d984c7d77522db6464d780cf8", "fiat": "daacf42c19a83843ffcde3dc18fc0d5922feebcb", "petsc": "a5e237b8fc7f3a298210b8ff01718acaa38bc5a0", "petsc4py": "0c970efa25de846f31e60b66bd1ca0177df46286", "slepc": "576b59718eb9e20da380c922ff4f323e0e497a62", "slepc4py": "b59f91a8055b55697b8921f50aa0d77a789bdc72", "metarelease_info_file": null, "title": "Firedrake version for: A Comparison of Second-Order Model Order Reduction Methods for an Artificial Fishtail"}

**Comment by dorugeber** [comment]
@wence- @dham I've been trying to do this, but keep getting a 404 error for slepc4py

```
(firedrake) andrew@ubuntu:~$ firedrake-zenodo --input fishtail.json 
No commit specified for SLOPE. No release will be created for this component.
Releasing COFFEE
Releasing firedrake
Releasing FInAT
Releasing slepc
Releasing tsfc
Releasing ufl
Releasing petsc
Releasing PyOP2
Releasing petsc4py
Releasing slepc4py
Traceback (most recent call last):
  File "/home/andrew/firedrake/bin/firedrake-zenodo", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/andrew/firedrake/src/firedrake/scripts/firedrake-zenodo", line 688, in <module>
    prerelease=True)
  File "/home/andrew/firedrake/lib/python3.6/site-packages/github3/decorators.py", line 31, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/home/andrew/firedrake/lib/python3.6/site-packages/github3/repos/repo.py", line 1204, in create_release
    json = self._json(self._post(url, data=data), 201)
  File "/home/andrew/firedrake/lib/python3.6/site-packages/github3/models.py", line 156, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: 404 Not Found
```

**Comment by wence-** [comment]
Probable cause, the firedrake-core team only had Read permissions.

**Comment by wence-** [comment]
@DiSiKi Done as https://zenodo.org/record/2564747, the release tag is `Firedrake_20190213.0`, you can get the relevant bibtex entry with:
```
firedrake-zenodo --bibtex Firedrake_20190213.0
```

**Comment by DiSiKi** [comment]
@wence- and @dorugeber Thank you!
