### ISSUE TITLE
Installation script fails installing petsc

### ISSUE THREAD

**Issue by xywei** [firedrakeproject/firedrake#1380]
Here is the log file: [firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/2921756/firedrake-install.log)

Seems to be an issue caused by deprecated MPI-1 functions in `openmpi` (I am using `openmpi 4.0.0-1`). Any ideas to workaround this?

**Comment by dham** [comment]
I agree with your diagnosis, it looks like hdf5 have an mpi issue. See:  https://forum.hdfgroup.org/t/hdf5-does-not-compile-with-openmpi-4-0-0/5110

We can't do much except wait for them to release that patch. I guess the workaround is to either use an earlier OpenMPI or use MPICH. We tend to find MPICH more reliable than OpenMPI.

**Comment by xywei** [comment]
Thanks for the helpful information. Closing as it is hardly related to the project.

**Comment by wence-** [comment]
You could report upstreamish to petsc (they will need to update their hdf5 version)
