### ISSUE TITLE
Eigen library gone in Complex

### ISSUE THREAD

**Issue by benSepanski** [firedrakeproject/firedrake#1405]
Hi! I recently (Mar 28) updated my complex firedrake and am running into some issues. When I called `interpolate` I was getting an error. I fixed this by changing line 168 in interpolation.py to
```
ast, oriented, needs_cell_sizes, coefficients, _ = compile_ufl_kernel(expr, to_pts, coords, parameters=parameters)
```
(I just added the `, _` in mimicry of the corresponding line in the master branch). However, I am still having trouble with projecting from a `CG` space to a `DG` space. I tried the following example:
```
from firedrake import *

m = UnitSquareMesh(2, 2)
V = FunctionSpace(m, 'CG', 1)

f = Function(V).interpolate(Constant(1))

Vdg = FunctionSpace(m, 'DG', 1)
g = project(f, Vdg)
```
From which I got some compile errors from pyop2. When I checked the .err file, I found this:
```
/home/bensepan/dev/firedrake-complex/.cache/pyop2/0db4d20f9baa97ae3e0fdd70b6a21118_p68.cpp:6:10: fatal error: Eigen/Dense: No such file or directory
 #include <Eigen/Dense>
          ^~~~~~~~~~~~~
compilation terminated.
```
I went looking for my eigen directory. In master firedrake, there is an `eigen3` folder in `firedrake/lib/python3.6/site-packages/petsc/include`. However, in my complex install, the `eigen3` folder is absent. 
I tried completely re-installing complex firedrake, and the folder was still not there.

**Comment by wence-** [comment]
I think this is because Eigen doesn't work (being a C++ library) with C complex numbers. One possible fix would be to compile PETSc with the C++ compiler (and then everything is C++). We might be dropping Eigen soon, which would simplify things.

You can avoid this issue (it only comes up when you use slate) by saying: `project(..., use_slate_for_inverse=False)`

**Comment by benSepanski** [comment]
Thanks, that fixes everything!
