### ISSUE TITLE
Pin randomgen version to known-working?

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#1416]
Since randomgen is fast moving, occasionally our tests break when they change their interface and add a new feature that we don't yet handle.

I don't understand all the magic that is going on in these classes, but it would be good if we can pin the versions to known working and then update that version when we test that newer versions work instead.

Related, it doesn't appear that we do anything to update the `randomgen` package in `firedrake-update` which presumably means that if we add code that only works in newer versions, things will break for people too. (I do not think we should implement a package manager).

I cargo-culted a fix to get the most recent change working in a2c33281, but I don't really understand what I did.

**Comment by ksagiyam** [comment]
Yes, let's use v1.16.4 as it is working after your fix.   
Could we just say in "firedrake/requirements-ext.txt":
...
randomgen==1.16.4
...
and keep updating this version number after we test newer versions? This will update `randomgen` with `firedrake-update`, right?

**Comment by wence-** [comment]
Yes, I think that is right. Do you want to try?

**Comment by ksagiyam** [comment]
Sure.

**Comment by wence-** [comment]
Fixed in #1419
