### ISSUE TITLE
Failed test on Kubuntu 16.04

### ISSUE THREAD

**Issue by josephecmu** [firedrakeproject/firedrake#1424]
Hello,
I am installing on Kubuntu 16.04.

Using install instructions here:
[https://firedrakeproject.org/download.html](url)

Below is the output of the test:

Building extension modules
> Traceback (most recent call last):
>   File "setup.py", line 8, in <module>
>     import petsc4py
> ImportError: No module named petsc4py
>     Linting firedrake codebase
> /usr/bin/python: No module named flake8
> Makefile:8: recipe for target 'lint' failed
> make: *** [lint] Error 1

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/3094905/firedrake-install.log)

**Comment by wence-** [comment]
It looks from the installation log that everything worked successfully. However, for the tests, it looks like you did not activate the firedrake virtualenv before attempting to use firedrake (running the tests).

If you run:
```
source /export/home/math/josephe/firedrake/bin/activate
make test
```

Does everything succeed?

**Comment by josephecmu** [comment]
Thanks.

I believe tests would succeed.  The actual issue my user was having involved 'anaconda' python.
