### ISSUE TITLE
Post-loopy installation requires pyopencl

### ISSUE THREAD

**Issue by rckirby** [firedrakeproject/firedrake#1431]
After a fresh install, I need to "pip install pyopencl" before I can import firedrake.
Probably that should be added to the firedrake install script somewhere?

**Comment by rckirby** [comment]
And BTW, on my Mac, I had pip install pybind11 or else the pip install pyopencl failed.

**Comment by wence-** [comment]
It should not be necessary to install pyopencl at all.

**Comment by rckirby** [comment]
I have had two different machines with two different operating systems tell
me otherwise.

**Comment by wence-** [comment]
Ok. I will try and reproduce. What are the two OSes? macOS and ?

**Comment by rckirby** [comment]
macOS Mojave and Ubuntu 18.04.2 LTS

**Comment by wence-** [comment]
On macos I just did:

```
 curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
python3 firedrake-install
```

And the resulting virtualenv has no issues.

**Comment by rckirby** [comment]
Did you then try importing firedrake?  My installation completed and I
didn't have a problem until import time.

Also, do you have pyopencl installed elsewhere already?

**Comment by wence-** [comment]
```
$ pip list | grep pyopencl
```
```
$ python -c "import pyopencl"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyopencl'
```
So it's definitely not there.

```
$ python -c "from firedrake import *; print(COMM_WORLD.size)"
1
```

So that works.

**Comment by wence-** [comment]
I tried booting a clean ubuntu 18.04 in docker to reproduce this. I did:

```
docker run -ti ubuntu:18.04
...
$ apt update
$ apt install wget python3 mpich sudo
$ wget https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
$ python3 firedrake-install --disable-ssh --minimal-petsc
```

The resulting firedrake virtualenv does not contain pyopencl, and importing firedrake works fine.

Is it possible that you are using an old `firedrake-install` script?

What does `md5sum firedrake-install` say? I had:

```
$ md5sum firedrake-install
0a696f284111892de623042e4354406e  firedrake-install
```

**Comment by rckirby** [comment]
Ah, I was downloading the firedrake-install from the complex branch.  Has
that not been updated/do we use the one from master to build complex now?

**Comment by dham** [comment]
The complex branch is lagging at the moment. I’ll try to find the time to do a merge from master, which will hopefully fix this (or someone else can beat me to it 😉

Regards,

David

**Comment by wence-** [comment]
Ok. Closing for now.
