### ISSUE TITLE
Compiler options for Eigen in Slate

### ISSUE THREAD

**Issue by taupalosaurus** [firedrakeproject/firedrake#1436]
slate/slac/compiler.py:227: include_dirs.extend(["%s/include/eigen3/" % d for d in PETSC_DIR])

This assumes that Eigen is installed by and in PETSc, which is not necessarily the case. Eigen can be passed as a configure option. This can happen notably when developing an external module used in PETSc that also uses Eigen.

I am not sure what the best way to retrieve the include directory is. Maybe there's a PETSc command that is able to spit it out, or a environment variable that contains that information. 
What can be done for sure is parsing PETSc configure log, which recalls the include and lib dirs of external packages at the end.

**Comment by taupalosaurus** [comment]
Best option I can come up with so far: find the correct includes during the Firedrake install process, store it in an environment variable of the venv, and use it kernels. It might even be extended to other petsc external packages. 

I'm happy to try that if the idea is approved.

**Comment by wence-** [comment]
Can you use the approach here https://github.com/FluidityProject/fluidity/blob/master/petsc_makefile ?

**Comment by taupalosaurus** [comment]
Fixed in PR #1441
