### ISSUE TITLE
Install issue on ARM Ubuntu 18.04

### ISSUE THREAD

**Issue by jaimesouza** [firedrakeproject/firedrake#1439]
Hi,

I am trying to install firedrake on an ARM ThunderX machine, following the procedures in the website (https://www.firedrakeproject.org/download.html). But I did not succeed.

First, I tried with:

`python3 firedrake-install`

And I got the following error:

> Traceback (most recent call last):
>   File "firedrake-install", line 1196, in <module>
>     install("petsc/")
>   File "firedrake-install", line 670, in install
>     build_and_install_petsc()
>   File "firedrake-install", line 773, in build_and_install_petsc
>     run_pip_install(["--ignore-installed", "petsc/"])
>   File "firedrake-install", line 630, in run_pip_install
>     check_call(pipinstall + pipargs)
>   File "firedrake-install", line 467, in check_call
>     log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=env).decode())
>   File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
>     **kwargs).stdout
>   File "/usr/lib/python3.6/subprocess.py", line 418, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['/root/firedrake/bin/python', '-m', 'pip', 'install', '--no-binary', 'mpi4py,randomgen', '--no-deps', '-vvv', '--ignore-installed', 'petsc/']' returned non-zero exit status 1.

The log file is below:

[firedrake-install-1.log](https://github.com/firedrakeproject/firedrake/files/3194194/firedrake-install-1.log)

After that, I installed PETSc using the tutorial in (https://www.mcs.anl.gov/petsc/) and tried with:

`PETSC_DIR=/root/petsc-3.11.1 python3 firedrake-install --honour-petsc-dir`

This time, I got a diferent error:

> Installing h5py/
> Traceback (most recent call last):
>   File "firedrake-install", line 1201, in <module>
>     build_and_install_h5py()
>   File "firedrake-install", line 818, in build_and_install_h5py
>     install("h5py/")
>   File "firedrake-install", line 673, in install
>     run_pip_install(["-e", package])
>   File "firedrake-install", line 630, in run_pip_install
>     check_call(pipinstall + pipargs)
>   File "firedrake-install", line 467, in check_call
>     log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=env).decode())
>   File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
>     **kwargs).stdout
>   File "/usr/lib/python3.6/subprocess.py", line 418, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['/root/firedrake/bin/python', '-m', 'pip', 'install', '--no-binary', 'mpi4py,randomgen', '-vvv', '-e', 'h5py/']' returned non-zero exit status 1.

The log file is below:

[firedrake-install-2.log](https://github.com/firedrakeproject/firedrake/files/3194195/firedrake-install-2.log)

What could I do?

**Comment by dham** [comment]
Hi Jaime,

You appear to be hitting the issue that not everybody supports ARM very well, in this case the HDF5 people seem to have an issue.

Your first install failed because HDF5’s build system failed to diagnose the system type. I notice that the script claims to be over a decade old, so possibly telling PETSc to use a more recent hdf 5 might work.

Your second attempt failed because the PETSc you built didn’t have all the features that Firedrake needs. Specifically, it failed because you didn’t compile in HDF5. Running the following command will show the PETSc configure options that Firedrake uses:
firedrake-install --show-petsc-configure-options

One of those PETSc configure options will be --download-hdf5, which will probably fail for you. If you can find an hdf5 version that does build on your platform then you might be able to just download that and pass something like –download-hdf5=/path/to/my/hdf5/source.tgz

Regards,

David



    *******************************************************************************
             UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
    -------------------------------------------------------------------------------
    Error running configure on HDF5: Could not execute "['./configure --prefix=/root/firedrake/lib/python3.6/site-packages/petsc MAKE=/usr/bin/make --libdir=/root/firedrake/lib/python3.6/site-packages/petsc/lib CC="mpicc" CFLAGS="-fPIC -fstack-protector -g -O" AR="/usr/bin/ar" ARFLAGS="cr" CXX="mpicxx" CXXFLAGS="-fstack-protector -g -O -fPIC" F90="mpif90" F90FLAGS="-ffree-line-length-0 -g -O" F77="mpif90" FFLAGS="-ffree-line-length-0 -g -O" FC="mpif90" FCFLAGS="-ffree-line-length-0 -g -O" --enable-shared --with-default-api-version=v18 --enable-parallel --enable-fortran F9X="mpif90" --with-zlib=yes --with-szlib=no CPPFLAGS="" LIBS="-lz -lm"']":
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... no
    checking for mawk... mawk
    checking whether /usr/bin/make sets $(MAKE)... yes
    checking whether /usr/bin/make supports nested variables... yes
    checking whether /usr/bin/make supports nested variables... (cached) yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking build system type...bin/config.guess: unable to guess system type

    This script, last modified 2008-01-23, has failed to recognize
    the operating system you are using. It is advised that you
    download the most up to date version of the config scripts from

      http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
    and
      http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

    If the version you run (bin/config.guess) is already up to date, please
    send the following data and any information you think might be
    pertinent to <config-patches@gnu.org> in order to provide the needed
    information to handle your system.

    config.guess timestamp = 2008-01-23

    uname -m = aarch64
    uname -r = 4.15.0-36-generic
    uname -s = Linux
    uname -v = #39-Ubuntu SMP Wed Sep 26 06:05:44 UTC 2018

    /usr/bin/uname -p =
    /bin/uname -X     =

    hostinfo               =
    /bin/universe          =
    /usr/bin/arch -k       =
    /bin/arch              =
    /usr/bin/oslevel       =
    /usr/convex/getsysinfo =

    UNAME_MACHINE = aarch64
    UNAME_RELEASE = 4.15.0-36-generic
    UNAME_SYSTEM  = Linux
    UNAME_VERSION = #39-Ubuntu SMP Wed Sep 26 06:05:44 UTC 2018
    configure: error: cannot guess build type; you must specify one
    *******************************************************************************

**Comment by jaimesouza** [comment]
Hi David,

Thank you for the tips!

I was able to install firedrake on arm. First I had to install a few packages like: 

`apt install libpng-dev pkg-config libfreetype6-dev libffi-dev`

And then I executed the following commands:

```
curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install

wget https://support.hdfgroup.org/ftp/HDF5/prev-releases/hdf5-1.8/hdf5-1.8.18/src/hdf5-1.8.18.tar.gz
tar -xzvf hdf5-1.8.18.tar.gz
git clone git://git.savannah.gnu.org/config.git
cp config/config.sub hdf5-1.8.18/bin/config.sub
cp config/config.guess hdf5-1.8.18/bin/config.guess
tar -czvf hdf5-1.8.18.tar.gz hdf5-1.8.18

PETSC_CONFIGURE_OPTIONS=--download-hdf5=$PWD/hdf5-1.8.18.tar.gz python3 firedrake-install --show-petsc-configure-options
```
Regards,

Jaime

**Comment by wence-** [comment]
Good to know. Did you need to download the very newest versions of config.sub and config.guess to build HDF5? I'd like to report this appropriately upstream so that it can be fixed there (maybe it only needs PETSc to update the version of HDF5 they track, but maybe it also needs the HDF5 releases to come with a newer config.sub/guess)

**Comment by jaimesouza** [comment]
Yes, I needed to download newest versions of config.sub and config.guess. The old versions could not recognize the operating system. I used the same version of HDF5 downloaded by the firedrake instalation script.

**Comment by wence-** [comment]
If it is not too difficult, do you mind trying to build just HDF5
using the latest official release 1.10.5 from here
<https://www.hdfgroup.org/downloads/hdf5/source-code/>?

I think just untarring and running ./configure should give us enough
information. I'd like to know whether or not I should just prod the
PETSc folks to update the version they point at, or whether HDF5 needs
a newer config.guess/config.sub.

Thanks!

**Comment by jaimesouza** [comment]
No problem. I'll do that and post the result here.

**Comment by jaimesouza** [comment]
I have downloaded the newest version of HDF5 in https://www.hdfgroup.org/downloads/hdf5/source-code/ (hdf5-1.10.5.tar.gz). I was able to run ./configure and make to build HDF5 with no error and no need to update config.sub or config.guess.

**Comment by wence-** [comment]
> I have downloaded the newest version of HDF5 in
> https://www.hdfgroup.org/downloads/hdf5/source-code/
> (hdf5-1.10.5.tar.gz). I was able to run ./configure and make to build
> HDF5 with no error and no need to update config.sub or config.guess.
> 

Great. It turns out PETSc master already points at this release, it's
just I hadn't updated our PETSc branch pointer recently: will do so
soon, thanks for the confirmation.

**Comment by jaimesouza** [comment]
You're welcome. Glad to help.
