### ISSUE TITLE
Errors while running tests on ARM Ubuntu 18.4

### ISSUE THREAD

**Issue by jaimesouza** [firedrakeproject/firedrake#1442]
Hello,

While running make alltest, i get these errors:

[test.txt](https://github.com/firedrakeproject/firedrake/files/3213575/test.txt)

Here is the installation log file:

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/3213586/firedrake-install.log)

Please, could anyone tell me what I can do to fix this? 

Regards,

Jaime

**Comment by wence-** [comment]
Can you try doing 

```
export PYOP2_DEBUG=1
pytest tests/extrusion/test_real_tensorproduct.py
```

If that doesn't provoke a failure then it might be possible that it is an error in the optimisation pass in the compiler. What compilers do you use on this system?

**Comment by jaimesouza** [comment]
The test above was executed sucessfully:

```
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
rootdir: /root/firedrake/src/firedrake, inifile: setup.cfg
plugins: xdist-1.28.0, forked-1.0.2
collected 22 items

tests/extrusion/test_real_tensorproduct.py ......................        [100%]

========================= 22 passed in 937.34 seconds ==========================
```
About the compilers, I have gcc/g++/gfortran 7.4.0

**Comment by wence-** [comment]
Ok. Can we try to confirm some more things:

Firstly, this one should provoke the failure
```
unset PYOP2_DEBUG
pytest tests/extrusion/test_real_tensorproduct.py
```

And then I suspect that this will pass

```
export PYOP2_CFLAGS=-fno-tree-vectorize
pytest tests/extrusion/test_real_tensorproduct.py
```

**Comment by jaimesouza** [comment]
Using unset PYOP2_DEBUG:

[test-1.txt](https://github.com/firedrakeproject/firedrake/files/3213993/test-1.txt)

Using export PYOP2_CFLAGS=-fno-tree-vectorize:

```
===================================================================================== test session starts ======================================================================================
platform linux -- Python 3.6.7, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
rootdir: /root/firedrake/src/firedrake, inifile: setup.cfg
plugins: xdist-1.28.0, forked-1.0.2
collected 22 items                                                                                                                                                                             

tests/extrusion/test_real_tensorproduct.py ......................                                                                                                                        [100%]

================================================================================= 22 passed in 989.53 seconds ==================================================================================
```

**Comment by wence-** [comment]
Ok thanks. I wonder if it is the same as this bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90055

(Use -march=native

**Comment by jaimesouza** [comment]
Ok Lawrence. Thank you for your help!!!

**Comment by wence-** [comment]
I added a workaround, based on C compiler version, in PyOP2. If you `firedrake-update`, I hope that no more environment variable exports are necessary for the test to pass.

**Comment by jaimesouza** [comment]
I ran the tests again. It's working well. Thanks!!!
