### ISSUE TITLE
Slate tests failing on my mac

### ISSUE THREAD

**Issue by taupalosaurus** [firedrakeproject/firedrake#1446]
The following tests fail on my laptop (OS X 10.12.6, Python 3.7.0):

test_mimetic.py::test_hcurl_element[N1curl-1-CG-1]
test_mimetic.py::test_hcurl_element[RT-1-CG-1]
test_slate_hybridization.py::test_slate_hybridization[2-RTCF-True]
test_slate_hybridized_mixed_bcs.py::test_slate_hybridized_on_boundary[2-RTCF-True]
test_slate_hybridized_mixed_bcs.py::test_slate_hybridized_extruded_bcs[2-RTCF]

(details of the errors [attached](https://github.com/firedrakeproject/firedrake/files/3227883/f5bc19e8c.txt).)

The tests pass if `PYOP2_DEBUG=1` is set.

I created a brand new vanilla install to make sure it wasn't due to my exotic setups. Happy to provide more details or run more tests.

**Comment by wence-** [comment]
This suggests that the C++ compiler is generating bad code (perhaps relying on more alignment than is actually available?)

**Comment by taupalosaurus** [comment]
Is there interest in investigating that further ? (i.e. should I keep the venv that results in the issue ?)

**Comment by JDBetteridge** [comment]
I think this issue is sufficiently old that it's not being revisited. Feel free to open a new issue if this is still happening with newer compilers
