### ISSUE TITLE
Install fails on Mac (UNABLE to EXECUTE BINARIES for ./configure)

### ISSUE THREAD

**Issue by erizmr** [firedrakeproject/firedrake#1452]
Hi, I met a problem when installing Firedrake on mac.  The problem I met first is quite similar to https://github.com/firedrakeproject/firedrake/issues/1281. But I met a new problem after solving the old one. 

The log file is list below,
[firedrake-install.log.txt](https://github.com/firedrakeproject/firedrake/files/3278552/firedrake-install.log.txt)

And I tried to check my mpif90 compiler, it could compile the test code, but fail to execute it with an error:

dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/8/libgfortran.5.dylib
  Referenced from: /usr/local/opt/open-mpi/lib/libmpi_usempif08.40.dylib
  Reason: image not found
Abort trap: 6

I am wondering if someone could give any clues?

Thanks.

**Comment by dham** [comment]
It looks like you have two compiler build chains installed and you are getting a mix of both, which won't install. The gcc (and hence gfortran) from Homebrew which you want to be using is `/usr/local/Cellar/gcc/9.1.0/bin/gfortran` (I found this right at the top of your firedrake-install.log). Notice that that's a different compiler in a different location from the ones you post above. At the bottom of the log file, PETSc notices that you have the`F90` environment variable set and warns you that PETSc ignores this.

The recommended way to install Firedrake on a Mac is to use a completely clean Homebrew toolchain. So, check your environment variables. You would not expect to see any compiler-related variables (FC, F90, CC, ...) being set, or any MPI variables (MPICC, MPIF90 etc). Also check PATH and ensure that you are not adding another compiler to it. It's useful to note that Homebrew does not use `/usr/local/opt/` so you would not expect to see any paths starting with that in your PATH.

Finally, it's always a good idea to run `brew doctor` and tend to any complaints it raises.

**Comment by erizmr** [comment]
Thanks for your reply.
I found that the open-mpi relies on gcc8 which is not managed by brew.
After updating the open-mpi, the problem solved.

**Comment by wence-** [comment]
Thanks, closing.
