### ISSUE TITLE
Problem Installing Firedrake

### ISSUE THREAD

**Issue by Ismail1993** [firedrakeproject/firedrake#1457]
Hi all I am having some sort of difficulty installing firedrake onto my Mac. Here is the installation 'log' which I hope will show something. The problem is I don't quite know what is causing it and I need a solution.  

From the log I get a list of files and then:

2019-06-10 19:05:23,817 INFO   Creating firedrake venv in '/Users/Ibrahim/firedrake'.
2019-06-10 19:05:29,722 DEBUG  ensurepip unavailable, bootstrapping pip using get-pip.py
2019-06-10 19:05:36,324 DEBUG  Running command '/Users/Ibrahim/firedrake/bin/python get-pip.py'
2019-06-10 19:05:36,345 DEBUG  dyld: Library not loaded: @rpath/libpython3.6m.dylib
  Referenced from: /Users/Ibrahim/firedrake/bin/python
  Reason: image not found

2019-06-10 19:05:36,348 INFO 

Many thanks.

**Comment by dham** [comment]
This is not the installation log. Please upload the file `firedrake-install.log` this will have been written in the directory that you ran firedrake-install from.

**Comment by Ismail1993** [comment]
[Uploading firedrake-install.log…]()

**Comment by Ismail1993** [comment]
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/3307113/firedrake-install.log)

**Comment by dham** [comment]
It looks like something about your Python is broken. I also notice that it's python 3.6 which is older than current homebrew python. I suggest you do the following:
```
brew upgrade python
```
Then run `brew doctor` and fix anything it complains about.
 I would then open a new terminal, just to make sure you pick up the newly installed or upgraded Python and try again.

I would also most strongly recommend you do not use the `--honour-pythonpath` option to firedrake-install. Instead you should unset PYTHONPATH. (your Pythonpath doesn't have anything relevant in it anyway).
