### ISSUE TITLE
Zenodo for goal oriented mesh adaptation paper

### ISSUE THREAD

**Issue by jwallwork23** [firedrakeproject/firedrake#1460]
Please could I have a zenodo release?

.json doesn't seem to be a supported file type for attaching, so please find it pasted below:

```
{"firedrake": "30ad4595d2709456d398a656f078e34e9a859c89", "fiat": "58658a66d0af7c607b10027ff8aca9c0a194fd57", "PyOP2": "9a07a333c0665b12cdb9268d8b40a318cf3506f8", "loopy": "c9287a88822424706caaba921c9f2428f67db0ca", "FInAT": "685bc3cde320f59463eab10307bb2e57af21edc5", "tsfc": "8647dd51f0592a51798ccad2c7e3eb91211d0bb9", "petsc4py": "7a0eec3b3eacbc4ed0984d07510170bbe171eb76", "ufl": "0d56bd53823a1ccb92e92fc3604b8f9c4a6cc480", "COFFEE": "72a4464aa18fd408de5304ac467db18d7af2b670", "metarelease_info_file": null, "title": "Anisotropic Goal Oriented Mesh Adaptation in Firedrake"}
```

My self-built PETSc is using the branch `joe/adapt`, with most recent commit hash `a614912a57eb64ab03e9e5d802a1bb520ab3db33`. Please can you add this in manually? (It didn't seem to work when I used the command line option `--petsc [hash]`.)

Many thanks,
Joe

**Comment by wence-** [comment]
On it.

**Comment by jwallwork23** [comment]
Hm. It is the latest commit on my branch `joe/adapt`.
To get this branch, I did
```
git clone git@bitbucket.org:petsc/petsc.git .
git remote add barral https://bitbucket.org/nbarral/petscfork-adapt.git
git remote add firedrake https://github.com/firedrakeproject/petsc.git
git fetch barral barral/allinone
git checkout barral/allinone
git fetch firedrake firedrake

git checkout barral/allinone
git merge firedrake
git checkout -b joe/adapt
```
Then I used
```git push -u firedrake joe/adapt```
to push it to the `firedrakeproject/petsc` repo.

Did I do something wrong?

**Comment by wence-** [comment]
No idea about that, but I'm complaining about the Firedrake commit 30ad4595d2709456d398a656f078e34e9a859c89, which does not exist in firedrakeproject/firedrake.git.

**Comment by jwallwork23** [comment]
Oh okay sorry. Will look into it

**Comment by wence-** [comment]
FWIW, AFAICT, it also does not exist in jwallwork23/firedrake

**Comment by wence-** [comment]
OK, now you need to push petsc4py too, since 7a0eec3b3eacbc4ed0984d07510170bbe171eb76 doesn't exist in firedrakeproject/petsc4py.git

**Comment by jwallwork23** [comment]
Okay, have made new `joe/adapt` branches in both firedrake and petsc4py. Sorry about that

**Comment by wence-** [comment]
Release tag is `Firedrake_20190620.1`. Bibtex

```
@misc{zenodo/Firedrake-20190620.1,
 key   = {zenodo/Firedrake-20190620.1},
 title = {{Software used in 'Anisotropic Goal Oriented Mesh Adaptation in Firedrake'}},
 year  = {2019},
 month = {jun},
 doi   = {10.5281/zenodo.3250888},
 url   = {https://doi.org/10.5281/zenodo.3250888},
}
```

**Comment by jwallwork23** [comment]
Thanks very much @wence- !
