### ISSUE TITLE
Testing the installation

### ISSUE THREAD

**Issue by Ismail1993** [firedrakeproject/firedrake#1465]
MacBook-Pro:~ Ibrahim$ source firedrake/bin/activate
(firedrake) MacBook-Pro:~ Ibrahim$ cd firedrake/src/firedrake
(firedrake) MacBook-Pro:firedrake Ibrahim$ make alltest
    Building extension modules
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
    Linting firedrake codebase
/Users/Ibrahim/firedrake/bin/python: No module named flake8
make: *** [lint] Error 1
(firedrake) MacBook-Pro:firedrake Ibrahim$ 

It seems as if python modules being totally ignored. I want to pass the testing phase and obviously theres a problem, help really appreciated.

**Comment by wence-** [comment]
Apologies for the slow response. It seems likely that the installation did not complete cleanly (since although the virtualenv exists, not even numpy is available in it).

Can you post the contents of firedrake-install.log?

Thanks!
