### ISSUE TITLE
Crossed meshes not supported on CylinderMesh

### ISSUE THREAD

**Issue by ScottMacLachlan** [firedrakeproject/firedrake#1468]
For symmetry reasons, I'd like to use a crossed triangular mesh on a PartiallyPeriodicRectangleMesh, but this isn't supported in the underlying CylinderMesh.  Is it possible to add this functionality?  Thanks!

**Comment by dham** [comment]
Hi Scott, I'm not sure when I could commit resources to this, but I think I can tell you how to do it if you want to have a go. Basically lines 1257 to 1275 of `utility_meshes.py` hand code the mesh. If you added an option to the mesh constructor, and used it to switch onto a crossed mesh construction at this point, then everything else should just fall through.

The one thing you need to be aware of is that in specifying a mesh cell in firedrake, the vertices should be in ascending order (i.e. not clockwise or anticlockwise, but ascending index order).

**Comment by ScottMacLachlan** [comment]
Thanks, David!

If I'm reading this right, there's two steps:
1) Augment the list of vertices to include the midpoints of the quads (since these will be vertices in the crossed mesh that aren't vertices in the quad mesh).  Probably easiest to append these to the end of the list, just to not break the way that "cells" is formed for the quad mesh on line 1273.
2) Write an alternative to line 1276 that replaces each quad with 4 triangles.  The only magic here would seem to be correctly indexing the right midpoint for each quad.  (I.e., can I use some indexing magic here, or just a loop over the quads?)

Does that make sense?  Am I missing anything?  Thanks!

**Comment by wence-** [comment]
Hi Scott,

Option 2 also needs to produce the extra vertices.

I think you can probably do option 1 by cargoculting the equivalent `diagonal="crossed"` code from `RectangleMesh` (starting at line 353).

**Comment by pefarrell** [comment]
I've pushed an initial attempt in `pefarrell/crossed-cylinder-mesh`.

**Comment by miklos1** [comment]
Closing because #1483 is merged. If this is not correct, feel free to reopen.
