### ISSUE TITLE
Installation fails due to fortran compiler

### ISSUE THREAD

**Issue by smrfeld** [firedrakeproject/firedrake#1489]
Hello,

I am on Mac, I tried to install with the latest provided script:
`python firedrake-install`

I get the following error in the log:
`Fortran compiler you provided with --with-fc=mpif90 does not work.
    Cannot compile FC with mpif90.`
related to building petsc.

Please let me know if I should post more of the log.
Thanks

**Comment by smrfeld** [comment]
Update:

I eliminated this error by ensuring `brew install open-mpi` and `brew link open-mpi`.

However, now I get:
`Could not find a suitable archiver.  Use --with-ar to specify an archiver.`

I also cannot find a better explanation of this error.

**Comment by smrfeld** [comment]
One more....

I eliminated this with
`export PETSC_CONFIGURE_OPTIONS="--with-ar=/usr/bin/ar`

Now I get:
`Fortran error! mpif.h could not be located at: []`

How hard can it be?

**Comment by wence-** [comment]
Hi. Can you please provide the output of `brew doctor`. And also `mpif90 -show` and `mpicc -show`?

If you have the log from the most recent failed attempt, could you please upload it so we can see more details?

**Comment by danshapero** [comment]
@smrfeld There have been recent improvements to the Firedrake install script as of #1611 which hopefully will fix the problems you've been having. I'm closing this issue but if you reinstall with the new script and encounter more errors please raise another issue.
