### ISSUE TITLE
Request for a zenodo release

### ISSUE THREAD

**Issue by mc4117** [firedrakeproject/firedrake#1495]
Hi I was wondering if a zenodo release could be created. 

As I am principally using thetis I edited the firedrake-zenodo file so that it now also outputs an id for thetis to the json file as well. I hope this is the correct id and if not please do let me know.

Also when I tried to upload the firedrake.json file github told me that the format type was unsupported so I changed the format to '.txt' but it is still the original file.

Thanks for your help

Mariana
[firedrake.txt](https://github.com/firedrakeproject/firedrake/files/3565844/firedrake.txt)

**Comment by wence-** [comment]
I'm not sure that firedrake-zenodo releases Thetis, or if one has to do it by hand, @tkarna?

**Comment by wence-** [comment]
@mc4117 That firedrake commit doesn't exist in the firedrake repository, so we can't release it.

**Comment by mc4117** [comment]
Ah I think that's because when I made the changes to firedrake-zenodo it made me commit the changes. Does this file work
[firedrake.txt](https://github.com/firedrakeproject/firedrake/files/3569593/firedrake.txt)
 @wence- ?

**Comment by wence-** [comment]
Tag is `Firedrake_20190903.0`, bibtex (from `firedrake-zenodo --bibtex Firedrake_20190903.0`):

```
@misc{zenodo/Firedrake-20190903.0,
 key   = {zenodo/Firedrake-20190903.0},
 title = {{Software used in 'Hydro-morphodynamics 2D modelling using a discontinuous Galerkin discretisation'}},
 year  = {2019},
 month = {sep},
 doi   = {10.5281/zenodo.3385061},
 url   = {https://doi.org/10.5281/zenodo.3385061},
}
```

This doesn't include the thetis release. I don't recall if they have been done manually in the past.

**Comment by mc4117** [comment]
Thanks Lawrence! I think I'll just put the commit number for the thetis release then

**Comment by wence-** [comment]
We can release it, it's just a manual process.

**Comment by wence-** [comment]
Can you open an issue in thetis for it?

**Comment by mc4117** [comment]
Ok I will add it as an issue now

**Comment by wence-** [comment]
I also meant open an issue to remind us to release Thetis for your paper! With the relevant commit hash.
