### ISSUE TITLE
FLOP estimation takes long time

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#1512]
Arising from thetisproject/thetis#168, the flop-counting via loopy takes 10s of seconds for some of the forms. Unfortunately, although we save the the TSFC-generated kernel, we ask for the flop count of the PyOP2 kernel at runtime (so don't save it).

Two options spring to mind:

1. Compute the flop count for a kernel directly for the loopy rep in tsfc (and then store that in the cache, amortising cost)
2. Compute the flop count directly from the GEM representation. I guess that the loopy version is slow because it's trying to count points in a polynomial set.

The first is an easier change, but does bump up the compilation time for kernels. The second is more invasive, and someone would need to write the code that computes the flops (and validate it was vaguely doing the right thing).

@inducer is this a problem you observe for "big" kernels? (the profile linked in the thetis suggests we spend 32s in `get_op_map`)

**Comment by wence-** [comment]
No, it's kind of only really useful for profiling (although note that if we try and do more automated profiling then it needs to go back in). So we could make it a configuration option.

**Comment by inducer** [comment]
I'm not sure that counting code has been made to go as fast as it can be, at least in terms of caching/not recomputing things. It also does extra work to verify it computed the right result in the absence of [barvinok](https://repo.or.cz/barvinok.git/refs) wrappers in islpy. Let me cc in James (@jdsteve2) who wrote the stats gathering code. He might have some ideas and/or might be able to help. (James, meet Lawrence and David from the [Firedrake](https://firedrakeproject.org/) crowd.)

Btw sorry for being slow on everything.

**Comment by wence-** [comment]
"Fixed" by turning it off by default.
