### ISSUE TITLE
Issue installing PETSc in Firedrake on OS Mojave

### ISSUE THREAD

**Issue by dwb26** [firedrakeproject/firedrake#1513]
Had issues installing Firedrake so I've removed Anaconda, reinstalled Homebrew and with this reinstalled Python 2.7 and Python 3.7. All to no avail. The Firedrake installer is happy until it begins installing PETSc (install log is attached below). When I run make alltest I get:

    Building extension modules
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
    Linting firedrake codebase
/usr/local/bin/firedrake/bin/python: No module named flake8
make: *** [lint] Error 1

The firedrake install log:
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/3698804/firedrake-install.log)

Thanks in advance.

**Comment by wence-** [comment]
OK, so the later issue (numpy not found) is kind of secondary, the first problem was that PETSc did not build (and so the installation aborted without succeeding).

I see two problems:

```
 ***** WARNING: You have an older version of Gnu make, it will work,
 but may not support all the parallel testing options. You can install the
 latest Gnu make with your package manager, such as brew or macports, or use
 the --download-make option to get the latest Gnu make warning message *****
```

This is somewhat strange, since homebrew normally installs a recent make. Can you show the output of:
```shell
$ which make
$ make --version
```

```
             UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
    -------------------------------------------------------------------------------
    Fortran error! mpif.h could not be located at: []
```

This one is the fatal error. For some reason the MPI compiler wrappers for fortran are not working.

What does the following show:
```shell
$ mpif90 -show
$ which mpi90
$ which gfortran
$ gfortran --version
```

**Comment by dwb26** [comment]
Hi wence, thanks so much for your response. I haven't responded sooner since I'm in the process of reinstalling Xcode, which is requiring me to update my OS software, which in turn is requiring me to reformat my SSD (!). Hence my delayed response. I will try the Firedrake installation once this is done and see where this gets me. I shall post the update on here either way.

**Comment by wence-** [comment]
Ah, ok! Good luck.

**Comment by dwb26** [comment]
Hi Wence, just to update this - upon rebooting and updating the Mac OS, installing Xcode, downloading Python 2 and 3 with Homebrew and a few extra linting programs, the installation was successful. The make alltest still raised a few errors, but the Firedrake library runs fine so I'm happy for now! Thanks for highlighting the gfortran aspect of the install log - given that I'd installed fortran before I suspect this was the problem.

**Comment by wence-** [comment]
Which tests error? Ideally we wouldn't have these at all!
