### ISSUE TITLE
updating to latest PETSc lead to poor performance

### ISSUE THREAD

**Issue by florian98765** [firedrakeproject/firedrake#1519]
Dear Firedrake-Users / Developers,

I am trying to make some small modifications to the PETSc Sundials time-integrators. In fact I would like to add the ```maxord``` parameter, which allows to set the maximal order of the used BDF method. I downloaded the latest PETSc version, added the required changes and compiled PETSC. Then I rerun firedrake installer using
```
PETSC_DIR=/petsc PETSC_ARCH=arch-linux2-c-debug python3 firedrake-install --honour-petsc-dir
```

Everything works fine, but the resulting performance is very bad. Even if I didn't apply my changes some of the equations systems are solved much slower and also the timeintegrator needs much more iterations. Since I am fairly sure that the CVode version didn't change for a long time the problem seems to be located in the PETSc linear system solvers.

I found out that firedrake still uses a petsc version of 2017. Unfortunately I didn't yet succeed to install that version manually. Maybe someone could give me a hint how this can be done? (I would like to have the original firedrake-petsc version then apply some small changes and recompile).

Furthermore I am wondering whether the problem with the poor performance already popped somewhere else. Could the problem result from some changed default settings which could be easily overwritten?

Finally this is an image of showing the diff of 2 runs - one with the original PETSc version and one with the latest master without any further modifications of the code:

![timings](https://user-images.githubusercontent.com/7449723/67088771-42daa000-f1a6-11e9-971f-4fbadd0ea485.png)

I would appreciate any advice or comment.
best wishes 
Florian

**Comment by dham** [comment]
This is interesting. Just before we start, it is not correct that Firedrake is using a 2017 version of PETSc. We follow PETSc master closely. We last updated from master about an hour ago, and the previous update was about 10 days ago.

My first guess is that there is a difference in the configure options. Can you please provide the full set of options you used to configure PETSc?

**Comment by florian98765** [comment]
I used ```firedrake-install --show-petsc-configure-options``` which results in the following options:
```
./configure --download-chaco --download-eigen=/firedrake/src/eigen-3.3.3.tgz --download-exodusii --download-hdf5 --download-hypre --download-metis --download-ml --download-mumps --download-netcdf  --download-pastix --download-pnetcdf --download-pragmatic --download-ptscotch --download-scalapack --download-suitesparse --download-sundials --download-superlu_dist --with-cxx-dialect=C++11 --with-fortran-bindings=0 --with-zlib
```

Maybe I didn't understand the firedrake install correctly. I found the following line
```
'petsc': '413f72f04f5cb0a010c85e03ed029573ff6d4c63'
```
And there is a corresponding petsc commit which dates back to 2017. But nevertheless it is good to hear that firedrake seems to use a fairly recent petsc version. Is there an easy method to apply the needed modifications, while using the firedrake installer?

thanks for the fast reply and best wishes
Florian

**Comment by wence-** [comment]
@florian98765 can you run your `./configure` line including `--with-debugging=0` (we should spit that out, but presently don't). I suspect that is the difference.

The reason it looks like we're not quite petsc master is we are presently carrying one patch that fixes something for us (until such time as we fix it in petsc itself, which turns out not to be completely trivial).

> Maybe I didn't understand the firedrake install correctly. I found the following line

> ```'petsc': '413f72f04f5cb0a010c85e03ed029573ff6d4c63'```

This part of firedrake-install is checking that it is possible to install a _particular_ version of firedrake as archived on Zenodo: we're just checking that the installer can correctly resolve the commits from a DOI.

**Comment by florian98765** [comment]
Dear Lawrence, Dear David,

I am now re-compiling PETSc without debugging. The timings of the individual calculations (e.g. exchange field) seems to be quite good. Unfortunately the number of iterations within the Sundials timeintegrator is still unchanged (factor 8 higher than with the original version.) Additionally I noticed that i now get 7 "error test failures" inside of the Sundial integrator (compared with 0 in the orignal version). 

I am wondering which patch you are applying to the original PETSc. When switching to the new PETSc version I had to deal with a locking problem of some petsc vectors which we are directly manipulating (when using ```x.getArray()``` we got an Error ```'Vec is already locked'```). May this be related?

I will next try to directly use the PETSc sources in ```/firedrake/src``` which are installed by the firedrake intstaller. After patching the PETSc sources and setting the ```PETSC_CONFIGURE_OPTIONS``` I would call 
```pip3 install --upgrade -vvv --ignore-installed petsc/```

I hope that this would solve the problem.

The following screenshot shows the latest timings (left:unoptimized, middle:optimized, right:original)

![comparison_new](https://user-images.githubusercontent.com/7449723/67202353-bbd93200-f408-11e9-98a3-f4b86319f740.png)

thanks for all your comments
best wishes
Florian

**Comment by florian98765** [comment]
Reusing the provided PETSc installation after patching worked fine. The main problem seem to be a workaround that I used to overcome the mentioned locking problem. Using the firedrake PETSc version works without workaround. The error test failures vanished and the overall performance is much better than expected :-) 

I am closing this issue. 
best wishes
Florian
