### ISSUE TITLE
Installation issue on macOS Mojave

### ISSUE THREAD

**Issue by anezkap** [firedrakeproject/firedrake#1526]
Hey!

I'm trying to install Firedrake on my macbook but without success. I always get to a point of 'Building PETSc', but get an error after couple of minutes.

Here is the install.log:
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/3779846/firedrake-install.log)

I see this problem: "Error running make; make install on PNETCDF", but I don't know how to fix it.

Thank you for your help!

**Comment by dham** [comment]
Sorry for taking a few days to get back to you. A few people have hit this issue. It looks like PNETCDF can't be built with the latest open-mpi. I think that a workaround might be to use mpich instead. Try:
```
brew unlink open-mpi
brew install mpich
rm -rf firedrake
python3 firedrake-install --no-package-manager
```

The option passed to the installer is to stop the installer from trying to reinstall open-mpi.

**Comment by anezkap** [comment]
I am so sorry for the late reply, but thank you very much for your help - it worked.
