### ISSUE TITLE
make test failed after install

### ISSUE THREAD

**Issue by tyszwh** [firedrakeproject/firedrake#1532]
I have met a problem with make test. I can not find the reason.
I have activated the env with "source firedrake/bin/activate"
The attached file is a log.

The error message
`    Building extension modules
    Running all regression tests
======================================= test session starts ========================================
platform linux -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/3_10/firedrake/src/firedrake, inifile: setup.cfg
plugins: forked-1.1.3, xdist-1.30.0
collected 5616 items                                                                               

tests/test_0init.py .Makefile:64: recipe for target 'test' failed
make: *** [test] Error 59
`

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/3811986/firedrake-install.log)

**Comment by wence-** [comment]
Hi, it looks like the install completed successfully, we just need to figure out what goes wrong with the tests.

Can you activate the virtual environment and run:

```shell
pytest tests/test_0init.py
```

And post the output?

Thanks!

**Comment by tyszwh** [comment]
Looks like I can not import the pyop2.
"
==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_0init.py _____________________
ImportError while importing test module '/home/3_10/firedrake/src/firedrake/tests/test_0init.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_0init.py:1: in <module>
    from firedrake import *
firedrake/__init__.py:43: in <module>
    from pyop2 import op2                        # noqa: F401
E   ModuleNotFoundError: No module named 'pyop2'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.87 seconds ============================

"

**Comment by tyszwh** [comment]
I just try to import pyop2 in a terminal environment, it seems to work fine.

**Comment by wence-** [comment]
Hmmm, can you show the output of:

```
which python
which pytest
```
In the activated venv? It seems somehow that the pytest you have can't see pyop2.

**Comment by tyszwh** [comment]
Ok,
which python 
/home/3_10/firedrake/bin/python
which pytest
/home/build_install/all/bin/pytest
This path inlcude the python 3.7 installed.

And I use the custom python path during install, like this
python3 firedrake-install --honour-pythonpath

**Comment by wence-** [comment]
OK, this looks to be the issue, you're getting a pytest that uses the "system" python, rather than the one in the virtual environment. Is there are particular reason you needed `--honour-pythonpath`? It is usually the wrong thing to do for a firedrake installation.

If you ensure that pytest is available in the venv (unset PYTHONPATH and run pip install pytest), things should work. But I would be a little leery of the install having some subtle issues due to other packages not being installed (because their dependencies were satisfied by packages you had lieing around).

**Comment by tyszwh** [comment]
Ok, got it. 
So, when I type the pip3 or pip. I got the error message:
`Traceback (most recent call last):
  File "/home/3_10/firedrake/bin/pip3", line 10, in <module>
    sys.exit(main())
TypeError: 'module' object is not callable
`
Should it be relative to my initial install setting?
And, could you tell me how to avoid using the "system" python. I always got a wrong message 
without  --honour-pythonpath option.
Should I uset all the pythonpath in bashrc?

**Comment by tyszwh** [comment]
Some $pythonpath is related to other codes. I may need it in bashrc for working. So, maybe I can unset it during reinstalling firedrake and reset it after then? I'm not sure whether it will cause a collision.

**Comment by wence-** [comment]
I would `unset PYTHONPATH` when both installing _and_ using Firedrake. That way you can guarantee it won't cause a collision.

**Comment by wence-** [comment]
To manage this stuff (modification of environment variables) in a clean way, I like to use [environment modules](https://modules.readthedocs.io/en/latest/) rather than setting everything in bashrc.

**Comment by tyszwh** [comment]
Ok, Thanks very much for your help. I will reinstall it and try using the environment modules to manage the environment variables.

**Comment by wence-** [comment]
OK, I'll close this issue for now. Please reopen if you continue to struggle! (And let us know how you get on either way).
