### ISSUE TITLE
ident_zeros() for matrices in Firedrake

### ISSUE THREAD

**Issue by c-abird** [firedrakeproject/firedrake#1534]
I would like to have the possibility to set zero-diagonal matrix entries to one (similar to the ```ident_zero``` method of the Matrix class in FEniCS). I assume this can be achieved with ```pyop2.par_loop```, but I can't figure out how. Any advise is appreciated.

**Comment by wence-** [comment]
Do you mean you want to set diagonal entries that are zero to one?

**Comment by c-abird** [comment]
exactly

**Comment by wence-** [comment]
Do you know where the zero diagonal entries are, or would you like us to find them for you?

**Comment by c-abird** [comment]
I kind of know where they are. I have a mesh with multiple domains and I assemble the matrix by integrating over a subset of the domains. Consequently all diagonal entries representing DOFs that are not part of the considered domains are zero. However, maybe it's easier to find the zeros?

**Comment by wence-** [comment]
How about this:

```python
from firedrake.petsc import PETSc
A = assemble(bilinear_form, ...)
diagonal = A.petscmat.getDiagonal()
vals = diagonal.array
vals[vals == 0] = 1
A.petscmat.setDiagonal(diagonal, PETSc.InsertMode.INSERT_VALUES)
```

**Comment by c-abird** [comment]
Ah, nice, I did not think of that. Thank you! Will this work with MPI?

**Comment by wence-** [comment]
Yes, it gets the global vector, updates the process-local part and sets it again. (So it's collective, but only does local work and neighbourhood communication at worst).

**Comment by c-abird** [comment]
Perfect, thanks a lot
