### ISSUE TITLE
Problem in 'make alltest'

### ISSUE THREAD

**Issue by felipeaugustogudes** [firedrakeproject/firedrake#1535]
Hi! When I try run 'make alltest' this error appears.  I don't find the c file that the run need.

running build_ext
skipping 'firedrake/cython/dmplex.c' Cython extension (up-to-date)
skipping 'firedrake/cython/extrusion_numbering.c' Cython extension (up-to-date)
skipping 'firedrake/cython/hdf5interface.c' Cython extension (up-to-date)
skipping 'firedrake/cython/mgimpl.c' Cython extension (up-to-date)
skipping 'firedrake/cython/patchimpl.c' Cython extension (up-to-date)
skipping 'firedrake/cython/spatialindex.c' Cython extension (up-to-date)
skipping 'firedrake/cython/supermeshimpl.c' Cython extension (up-to-date)
building 'firedrake.cython.hdf5interface' extension
mpicc -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/paopc/Documentos/firedrake/lib/python3.6/site-packages/numpy/core/include -I/home/paopc/Documentos/firedrake/lib/python3.6/site-packages/petsc4py/include -I/home/paopc/Documentos/firedrake/lib/python3.6/site-packages/petsc/include -I/home/paopc/Documentos/firedrake/include -I/usr/include/python3.6m -c firedrake/cython/hdf5interface.c -o build/temp.linux-x86_64-3.6/firedrake/cython/hdf5interface.o
firedrake/cython/hdf5interface.c:597:10: fatal error: hdf5.h: Arquivo ou diretório inexistente
 #include "hdf5.h"
          ^~~~~~~~
compilation terminated.
error: command 'mpicc' failed with exit status 1

**Comment by wence-** [comment]
can you show the contents of `/home/paopc/Documentos/firedrake/lib/python3.6/site-packages/petsc/include` ? I think it should contain `hdf5.h`

**Comment by wence-** [comment]
(Can you also post the firedrake-install.log that got you to this stage?)

**Comment by felipeaugustogudes** [comment]
I looked the contents of directories and I didn't find this file. Do I need to copy it from other directories to Firedrake directories?
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/3820217/firedrake-install.log)

**Comment by wence-** [comment]
Apologies, it looks like our setting of MPI compilers is not sufficient (and so, if we look at the bottom of that install log, despite you saying `--mpiexec mpiexec.mpich`, PETSc still found an openmpi mpiexec).

Can you try the firedrake-install script from here https://raw.githubusercontent.com/firedrakeproject/firedrake/wence/fix/mpiexec-install/scripts/firedrake-install

And re-run the install please.

Apologies that this has been so difficult so far.

**Comment by felipeaugustogudes** [comment]
Hi! The new error appears in the instalation log
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/3820407/firedrake-install.log)
.

**Comment by wence-** [comment]
Sorry, I made a mistake (please download from that same address again), but you also still need to provide the relevant mpiexec and so on to firedrake-install:

`firedrake-install --mpicc mpicc.mpich --mpicxx mpicxx.mpich --mpif90 mpif90.mpich --mpiexec mpiexec.mpich`

Thanks.

**Comment by felipeaugustogudes** [comment]
Hi! Now The errors were fix. I sent the instalation log! Thanks for all help!
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/3821077/firedrake-install.log)

**Comment by wence-** [comment]
Great, enjoy! I'll close the issue.
