### ISSUE TITLE
Order of convergence multigrid

### ISSUE THREAD

**Issue by funkiii** [firedrakeproject/firedrake#1540]
i try to use the multigrid method for solving the linear system of equations resulting out of a heat equation on the unit cube. I am using linear finite element method for the spatial discretization and the crank nicelson method for time-stepping. If i use a cg-method for solving, so
`parameters ={
"ksp_type": "cg",
 "ksp_atol": 1e-30,
 "ksp_rtol": 1e-9,
 "ksp_divtol": 1e4}`,
everthing is fine, and i get the expected estimated order of convergence 1.94 (~2).
But if I choose e.g.
`parameters={
"ksp_type": "preonly",
 "pc_type": "mg",
 "mg_levels_ksp_type":"richardson",
"mg_levels_pc_type":"jacobi",
"mg_levels_ksp_max_it": 2,
"ksp_atol": 1e-30,
"ksp_rtol": 1e-9,
"ksp_divtol": 1e4}`
as solver parameters, the order of convergence isn't even close to 2.
For both cg and multigrid i start with h = 1/4 and double it, and i start with 1 timestep and double it also.
So, everthing in my code is the same for both methods, just the solver parameters a different, and i construct a mesh hierarchy for mg with
`hierarchy = MeshHierarchy(mesh, int(num_refinements))`
 `mesh = hierarchy[-1]`

The order of convergence shouldn't depend drastically on the method used for solving the linear system of equations, and for the cg method it works, so there is an error for the multigrid method i use, but i don't know what is wrong. I tried many additional options for the mg method, but that didn't change much. Does anyone know where my error is?

**Comment by wence-** [comment]
With the latter, you're only doing one V-cycle (which has a contraction factor of around 0.1 for the constant coefficient Laplacian). If you want to use just multigrid rather than with a Krylov accelerator, you need to do `"ksp_type": "richardson"` (you may need to adapt the scaling for Richardson, not sure), or you could use Chebyshev acceleration. If you're constant coefficient, then you could also use a preonly application of a full multigrid cycle (`"ksp_type": "preonly", "pc_mg_type": "full"`) which (with appropriate smoothers [I think 2 pre- and post-smooths for Laplace is sufficient]) can obtain an algebraic error on the same order as the discretisation error.

**Comment by funkiii** [comment]
Thank you for the response.
Yes, i have constant coefficiants, and i already tried the version with the full multigrid cycle, but my order of convergence stays at 1. I used the parameters suggested in the example for the geometric multigrid method, so `parameters = {
   "ksp_type": "preonly",
   "pc_type": "mg",
   "pc_mg_type": "full",
   "mg_levels_ksp_type": "chebyshev",
   "mg_levels_ksp_max_it": 2,
   "mg_levels_pc_type": "jacobi"
}.`
There is a mark, that for those parameters the algebraic error is equal to the discretisation error for those parameters.
The other version you suggested results in quite good convergence(~1.9), but takes at least 10 times longer than the corresponding cg method.

**Comment by wence-** [comment]
Can you show the output of both adding `"ksp_monitor": None` and `"ksp_view": None`? I wouldn't expect adding richardson to take 10 times as many iterations.

**Comment by funkiii** [comment]
[fullmg.txt](https://github.com/firedrakeproject/firedrake/files/3836825/fullmg.txt)
[richardson.txt](https://github.com/firedrakeproject/firedrake/files/3836826/richardson.txt)

**Comment by funkiii** [comment]
Does someone have a code with linear finite elements that converges with order 2 in 3d? My example in 2d converges with order 2, but if I transfer the problem in 3d, there isn't. 
Thanks in advance
