### ISSUE TITLE
Firedrake zenodo release

### ISSUE THREAD

**Issue by tkarna** [firedrakeproject/firedrake#1541]
I'd need a zenodo release for the firedrake stack below. This is an update of `10.5281/zenodo.3269766`. I tried doing this myself but `firedrake-zenodo` failed.

[firedrake_thetis-turb-review1.txt](https://github.com/firedrakeproject/firedrake/files/3840565/firedrake_thetis-turb-review1.txt)

**Comment by tkarna** [comment]
It looks like I cannot make a release for PyOP2. The SHA is valid. Maybe I'm lacking permissions in the repo?
[firedrake-zenodo.log](https://github.com/firedrakeproject/firedrake/files/3845890/firedrake-zenodo.log)

**Comment by wence-** [comment]
That's almost certainly the case. I can do it for you today?

**Comment by tkarna** [comment]
Sure.

**Comment by wence-** [comment]
Tag is `Firedrake_20191114.0`

Bibtex:

```
@misc{zenodo/Firedrake-20191114.0,
 key   = {zenodo/Firedrake-20191114.0},
 title = {{Software used in 'Discontinuous Galerkin discretization for two-equation turbulence closure model'}},
 year  = {2019},
 month = {nov},
 doi   = {10.5281/zenodo.3541739},
 url   = {https://doi.org/10.5281/zenodo.3541739},
}
```

(A bit of a dance cos zenodo had been flaky).

**Comment by wence-** [comment]
A reminder (if you have a paper review and want the zenodo releases for the first and second round to be linked), you can run `firedrake-zenodo --new-version-of DOI-of-previous-release` and then we create a link in the new record (I did that for this case).
