### ISSUE TITLE
Unable to install firedrake on mac Catalina using either openmpi or mpich

### ISSUE THREAD

**Issue by cassie-ying** [firedrakeproject/firedrake#1542]
Hi. When i try to install firedrake with openmpi, I encounter "Fortran error! mpi_init() could not be located!" error.

When i try to install firedrake with mpich, I encounter "Error running make; make install on HDF5". And when i try to install petsc on my own using mpich with hdf5, the error is "Fatal Error: Cannot read module file ‘mpi.mod’ opened at (1), because it was created by a different version of GNU Fortran".

[firedrake-install-openmpi.log](https://github.com/firedrakeproject/firedrake/files/3844376/firedrake-install-openmpi.log)
[firedrake-install-mpich.log](https://github.com/firedrakeproject/firedrake/files/3844378/firedrake-install-mpich.log)

**Comment by danshapero** [comment]
These issues might have been improved with some recent changes to the install script, see #1554 . From the second problem you describe, you might have built HDF5 and then upgraded to a newer version of gfortran. I think `brew doctor` should fix this if you're using homebrew.
