### ISSUE TITLE
firedrake-update did not update submodule of loopy

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#1553]
A run of firedrake-update broke my installation which turned out to be because the loopy/target/c/compyte submodule in loopy was out of sync. I could unbreak this with
```
git submodule update loopy/target/c/compyte
```
I don't know much about submodules, but should the `git pull` in firedrake update be using `--recurse-submodules`?

**Comment by dham** [comment]
Good point. See: #1555

**Comment by dham** [comment]
Fix merged.
