### ISSUE TITLE
Initial guess for solve

### ISSUE THREAD

**Issue by funkiii** [firedrakeproject/firedrake#1557]
Hello,

is there a way to set an initial guess for the solve method, maybe via the solver_parameters? I know about the option ksp_initial_guess_nonzero, but what is the initial guess then? I would like to use the solution from the last timestep as an initial guess for solving the problem in the current timestep.

Kind regards

**Comment by dham** [comment]
The value of the solution variable passed into the solve call or the variational solver constructor will be used as the initial guess in the solver. Quite often this will mean that in time stepping algorithms the previous solution will naturally be used as the initial guess. If that isn't the case for you, you can assign a value to the solution variable before the solve call.
