### ISSUE TITLE
Slate tensor assembly fails for high order Nedelec elements

### ISSUE THREAD

**Issue by marybarker** [firedrakeproject/firedrake#1560]
Using slate's `Tensor(form)` functionality results in a compilation error for degree >4 N1curl elements. The error gets thrown during `assemble(Tensor(form))` but does not occur when using the usual `assemble(form)`. The output from the example below is attached. (Note: it runs perfectly for degree =1,2,3,4)

    def solve_curl_curl(mesh, f, degree, with_tensor=False):
        V_element = FiniteElement("N1curl", mesh.ufl_cell(), degree)
        V = FunctionSpace(mesh, V_element)
        u = TrialFunction(V)
        v = TestFunction(V)
    
        a = inner(curl(u), curl(v))*dx
        L = inner(f, v)*dx
    
        if with_tensor:
            A = Tensor(a)
            B = Tensor(L)
            w = A.inv * B
            u_h = assemble(w) # throws an error if degree > 4
        else:
            A = assemble(a)
            B = assemble(L)
            w = Function(V)
            solve(a == L, w, bcs=[DirichletBC(V, 0, "on_boundary")])
        print("FINISHED with degree %d"%degree)
    
    mesh = UnitTetrahedronMesh()
    solve_curl_curl(mesh, Constant((1,1,1)), 5)
    solve_curl_curl(mesh, Constant((1,1,1)), 5, True)
[output.txt](https://github.com/firedrakeproject/firedrake/files/3921585/output.txt)

**Comment by dham** [comment]
That's an interesting bug! When we get compiler errors like this, it's useful to see the compiler error log. The error message you posted tells us that this is: `/Users/marvin/firedrake/.cache/pyop2/b9/2e8ab04bb76df1a5a87f9223799e0e_p1228.err`

**Comment by marybarker** [comment]
Oh yes! Here it is. Looks like it's a problem with an Eigen macro maybe

[2e8ab04bb76df1a5a87f9223799e0e_p1228.err.txt](https://github.com/firedrakeproject/firedrake/files/3940569/2e8ab04bb76df1a5a87f9223799e0e_p1228.err.txt)

**Comment by wence-** [comment]
Sorry, fat-fingered the button. The issue here is that Eigen is complaining that we're asking to stack-allocate a tensor with 19600 entries, this is larger than the internal eigen variable `EIGEN_STACK_ALLOCATION_LIMIT`. I do not know how easy it is to change that. Since we know up front the size of the tensor, we could heap allocate ones that are too big (although I do not know exactly how to do this with Eigen).

**Comment by dham** [comment]
OK, so the local tensor is getting too big for Eigen. This is not a huge surprise as local tensor size in 3d is (p+1)**6 where p is polynomial, degree. Using any matrix-explicit algorithm on high order elements is very bad for this reason. @sv2518 is currently working on refactoring the insides of SLATE to remove the Eigen dependency and introduce a matrix-free capability for high order.

I should also note that the polynomial basis for all of our elements on tets becomes very badly conditioned at high order too.

**Comment by dham** [comment]
Perhaps you might like to start a conversation on slack about what you're trying to achieve and we can see if we can point you at a way to do that in Firedrake.

**Comment by marybarker** [comment]
Thanks! I was actually just trying to use Slate for the speed enhancement it gives my code, but I can go back to using a full assemble and solve with Firedrake.

**Comment by dham** [comment]
OK. You should be aware that the high cost in memory and operations of assembling matrices is a universal feature of high order discretisations. It's the reason that matrix-free approaches are often preferred at high order. Firedrake does have matrix-free capabilities so if that might be useful to you, get in contact and we'll try to help.

**Comment by rckirby** [comment]
One possibility for higher-order Nedelec would be to use a Schwarz-type
preconditioner.  We'd need to generalize the low-order PC (on the eventual
to-do anyway list if I ever find time...) but patchPC should be up to the
task of doing the low-order problems.  One could hit the low-order part of
the operator with LU or you could use the hypre AMS hookup that hasn't been
committed.

So there are options but...it's a bit complicated.

**Comment by marybarker** [comment]
Awesome! Thanks. At the moment I'm just working with some toy examples in high high order for convergence rates. I was trying to use Slate instead of the PETSc preconditioners, as it's so much quicker, but it looks like I'll have to take that hit.

**Comment by rckirby** [comment]
Yes, the built-in PETSc preconditioners all fail badly on H(curl) problems
-- they are designed for other kinds of problems.  Development will be
needed for trying out Schwarz-type preconditioners.

In my paper with Marie & Anders (10 years ago!), we just used direct
solvers on these matrices and waited.  Or at least Marie did -- she
conducted the experiments.

**Comment by wence-** [comment]
@marybarker If you only need to do single-element things, you can get the equivalent of the slate thing by asking for:
```python
solve(a == L, u, bcs=bcs, solver_parameters={"ksp_type": "preonly", "pc_type": "lu"})
```

If you want to do things on a bigger mesh and have a regular geometry (such that you can use a MeshHierarchy), then we can do Arnold-Falk-Winther HCurl multigrid out of the box with PCPatch.

**Comment by rckirby** [comment]
How does the high-order MG work vis-a-vis doing Schwarz and multilevel only
on the low-order subspace (besides taking considerably less code and
development)?  My knowledge of MG details is rather sketchy, but IIRC
Bank/Dupont discuss higher-order methods and show you need different
scaling in smoothers.   But that may just be parameter fiddling.

**Comment by wence-** [comment]
> How does the high-order MG work vis-a-vis doing Schwarz and multilevel only
on the low-order subspace (besides taking considerably less code and
development)?  My knowledge of MG details is rather sketchy, but IIRC
Bank/Dupont discuss higher-order methods and show you need different
scaling in smoothers.   But that may just be parameter fiddling.

Our experiments (we have not gone to very high order) suggest that the overlapping patch smoothers are h and k independent when used as smoothers. I think this aligns with the abstract theory.

**Comment by sv2518** [comment]
@marybarker Just to give you an update: I made a bit of progress in this. My Slate compiler is using loopy rather than Eigen now. I have tested your example and it is possible to assemble your forms also with higher order. This is still work in progress, however. I will let you know as soon as you can solve your problem matrixfree.

**Comment by wence-** [comment]
That work of @sv2518 is now merged, so at least the example provided now runs fine.
