### ISSUE TITLE
Zenodo release for "Goal-oriented error estimation and mesh adaptation for shallow water modelling"

### ISSUE THREAD

**Issue by jwallwork23** [firedrakeproject/firedrake#1561]
Hi,

Please could I have a Zenodo release? Here is the output of `firedrake-zenodo`:

```{"firedrake": "b065dcaa91b069deeb5b8754fb000473a9713f40", "PyOP2": "9a07a333c0665b12cdb9268d8b40a318cf3506f8", "tsfc": "8647dd51f0592a51798ccad2c7e3eb91211d0bb9", "COFFEE": "72a4464aa18fd408de5304ac467db18d7af2b670", "ufl": "0d56bd53823a1ccb92e92fc3604b8f9c4a6cc480", "FInAT": "685bc3cde320f59463eab10307bb2e57af21edc5", "fiat": "58658a66d0af7c607b10027ff8aca9c0a194fd57", "petsc4py": "85ab3b84f3715cf585431b8603797c9980402b5c", "loopy": "c9287a88822424706caaba921c9f2428f67db0ca", "metarelease_info_file": null, "title": "Goal-Oriented Error Estimation and Mesh Adaptation for Shallow Water Modelling"}```

I am using a custom PETSc with commit hash a614912a57eb64ab03e9e5d802a1bb520ab3db33.

Thanks very much,
Joe

**Comment by dham** [comment]
On it. Stand by.

**Comment by dham** [comment]
You're using a branch of Firedrake which does not exist in the Firedrake repo on GitHub. You need to push it or we can't archive it (our telepathic capabilities are limited).

**Comment by jwallwork23** [comment]
Apologies, I thought I was using public branches. Try using this commit: 30ad4595d2709456d398a656f078e34e9a859c89.
Thanks!

**Comment by jwallwork23** [comment]
Sorry, you might also need 7a0eec3b3eacbc4ed0984d07510170bbe171eb76 for petsc4py

**Comment by jwallwork23** [comment]
Ignore that; have pushed the appropriate branch and the latest commit is indeed 85ab3b84f3715cf585431b8603797c9980402b5c.

**Comment by dham** [comment]
The problem is the Firedrake branch. `b065dcaa91b069deeb5b8754fb000473a9713f40` is not a commit in the Firedrake repository.

**Comment by jwallwork23** [comment]
Apologies. How about this?
```{"firedrake": "30ad4595d2709456d398a656f078e34e9a859c89", "PyOP2": "9a07a333c0665b12cdb9268d8b40a318cf3506f8", "tsfc": "8647dd51f0592a51798ccad2c7e3eb91211d0bb9", "COFFEE": "72a4464aa18fd408de5304ac467db18d7af2b670", "ufl": "0d56bd53823a1ccb92e92fc3604b8f9c4a6cc480", "FInAT": "685bc3cde320f59463eab10307bb2e57af21edc5", "fiat": "58658a66d0af7c607b10027ff8aca9c0a194fd57", "petsc4py": "85ab3b84f3715cf585431b8603797c9980402b5c", "loopy": "c9287a88822424706caaba921c9f2428f67db0ca", "metarelease_info_file": null, "title": "Goal-Oriented Error Estimation and Mesh Adaptation for Shallow Water Modelling"}```

**Comment by dham** [comment]
Zenodo release here:

@software{firedrake_zenodo_2019_3568997,
  author       = {firedrake-zenodo},
  title        = {{Software used in 'Goal-Oriented Error Estimation 
                   and Mesh Adaptation for Shallow Water Modelling'}},
  month        = dec,
  year         = 2019,
  publisher    = {Zenodo},
  version      = {Firedrake_20191209.0},
  doi          = {10.5281/zenodo.3568997},
  url          = {https://doi.org/10.5281/zenodo.3568997}
}

Note that there is no PETSc in this archive. This is probably due to you using an external PETSc.

**Comment by jwallwork23** [comment]
Thanks very much David!
