### ISSUE TITLE
Memory in compute_gradient 

### ISSUE THREAD

**Issue by krober10nd** [firedrakeproject/firedrake#1576]
Hello, 

I have FireDrake installed on my MacBook OS Catalina and the same version also installed on Ubuntu 18.04 LTS. When I go to run the identical code, on Ubuntu it exceeds 20 gb of RAM causing the computer to literally shut off. On the MacBook Pro, I barely exceed 8 GB of RAM. The problem is small (only 24k DoF) and integrated for about 2,000 timesteps. 

The memory grows exponentially when it encounters the compute_gradient call. Any advice on how to deal with this? Has this been noted before? 

I can share code if you're interested by email

Thanks

**Comment by dham** [comment]
Hi Keith,

Code would be brilliant, it sounds like we have a memory leak. The most obvious relevant thing that might be different between the two platforms is the Python version, so it’s possible something is not getting garbage collected on one version that is on another (in particular, your Mac almost certainly has a newer Python than Ubuntu 18.04).

Regards,

David

--
Dr David Ham
Department of Mathematics
Imperial College London
https://www.imperial.ac.uk/people/david.ham

**Comment by krober10nd** [comment]
Hey David,

Here is the inputs and code called  Spyro (named after the Dragon). The code is run with the script called fwi.py and its serial. It should use the small 23k node mesh included in the zip. 

Anyway, it tries to invert a 2D P-wave velocity model using 3 acoustic waves injected at the top of the domain. On the Ubuntu machine, the memory goes way up to 15-20 gb but on my macbook, it's smooth sailing hovering around 4 gb. I'm not sure what python version I have on my machine in Brasil (I'm currently home in the US for holidays) but on my MacBook as you point 3.6.5. To increase the memory, change the number of sources or num_sources in the fwi.py script. With 5, it's literally impossible to run on the ubnuntu machine but still remains possible on my Mac. 

Thanks! Happy holidays.

[FWI.zip](https://github.com/firedrakeproject/firedrake/files/4014654/FWI.zip)

**Comment by JDBetteridge** [comment]
We have recently added some new garbage collection functionality that potentially fixes this issue. If you are still experiencing the memory leak in a recent install of Firedrake, please open a new issue.

**Comment by krober10nd** [comment]
Thanks for the update and exciting fix. @Olender maybe retry the 3D problem after updating Firedrake?
