### ISSUE TITLE
Installation fails on Arm Isambard

### ISSUE THREAD

**Issue by jaimesouza** [firedrakeproject/firedrake#1581]
I have successfully installed firedrake on Isambard cluster (arm thunderx2) about 2 months ago. But now I get error when I try to repeat the installation. Any idea of what could It be? The log file is bellow.
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4071724/firedrake-install.log)

**Comment by dham** [comment]
I'm not the expert on Isambard (that's @dacreman ), but I've just merged current master into the isambardBuild branch, so it might be worth trying again now.

**Comment by jaimesouza** [comment]
It's working now. Thanks!
