### ISSUE TITLE
Request for Zenodo release

### ISSUE THREAD

**Issue by j130792** [firedrakeproject/firedrake#1582]
Hi,

Can I have a Zenodo release for the following please?

`{"firedrake": "970d7f15c60db8407fc4180791c5f50f02cd0aa4", "PyOP2": "25ec8f44146e8454c0a28e9f40a8b0b134f30609", "tsfc": "70de05b881d042322991e3628359daa593ddb024", "COFFEE": "19e2c0d43a42cd30ddf11808551c7e6e7176abe3", "ufl": "d0bc23621d74131400b3336507e0ab1523a08cb0", "FInAT": "de6f2ab96464f81d984c7d77522db6464d780cf8", "fiat": "e618dfa5dbb3283b9fc03225338255debddc3d15", "petsc": "bf08679ea3a16b2203d34b0b2be4b3cd7e8a9b51", "petsc4py": "60406028eb2b84f1abc61a7fd8f3a56a62774266", "metarelease_info_file": null, "title": "Invariant preserving schemes for Hamiltonian problems"}`

Thanks,
James

**Comment by dham** [comment]
Release is at https://dx.doi.org/10.5281/zenodo.3624988
