### ISSUE TITLE
License and copyright headers

### ISSUE THREAD

**Issue by kynan** [firedrakeproject/firedrake#159]
As a Fluidity derivative, Firedrake is currently licensed under LGPL 2.1. Once we remove the remaining Fluidity code, would we be able to change the license to BSD for compatibility with PyOP2? Or would that not be possible since we still use some (although heavily modified) bits from the DOLFIN Python interface?

We should then also have consistent copyright headers. Currently we either have none or a modified DOLFIN copyright header.

**Comment by miklos1** [comment]
Is this question still valid after #703?

**Comment by wence-** [comment]
No, fixed by #703.
