### ISSUE TITLE
Issues installing and running firedrake on Centos7

### ISSUE THREAD

**Issue by jaredcworkman** [firedrakeproject/firedrake#1602]
I'm running into several issues installing and testing firedrake.

First I do
  yum -y install python35

then I run 
curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install

and 

python35 firedrake-install --no-package-manager

I am left with the following out put
#############################################################

Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "firedrake-install", line 1317, in <module>
    install("petsc/")
  File "firedrake-install", line 717, in install
    build_and_install_petsc()
  File "firedrake-install", line 825, in build_and_install_petsc
    check_call(["./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + list(petsc_options))
  File "firedrake-install", line 519, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib64/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./configure', 'PETSC_DIR=/program/firedrake/firedrake/src/petsc', 'PETSC_ARCH=default', '--with-fortran-bindings=0', '--download-exodusii', '--with-cxx-dialect=C++11', '--download-superlu_dist', '--download-eigen=/program/firedrake/firedrake/src/eigen-3.3.3.tgz ', '--with-debugging=0', '--download-hdf5', '--download-chaco', '--download-pastix', '--download-mumps', '--download-suitesparse', '--download-pnetcdf', '--with-zlib', '--download-scalapack', '--with-c2html=0', '--download-netcdf', '--download-hypre', '--download-ml', '--with-shared-libraries=1', '--download-mpich', '--download-ptscotch', '--download-metis']' returned non-zero exit status 1

#############################################################

The install log is attached
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4162885/firedrake-install.log)

Then I run . $PROGRAM_PATH/firedrake/bin/activate which sets up the env

After this I try to run make alltest.  The code does not seem to see many of the python dependencies so I run

yum -y install python35-devel.x86_64
  python -m pip install numpy
  python -m pip install pytest
  python -m pip install flake8
  python -m pip install petsc4py

I think this is wrong as 
make alltest returns an mpicc exited with code 1 error and fails to find pyadjoint (or several others that python -m pip installing fixes but no pyadjoint)

I think something is breaking in my install and I have my python paths set incorrectly. I see pyadjoint in the installdir.

Can you help?

**Comment by wence-** [comment]
The end of the install log says:

```
                      ===============================================================================
                            Trying to download git://https://github.com/gsjaardema/seacas.git for EXODUSII
                      ===============================================================================
                    
                      ===============================================================================
                            Configuring EXODUSII with cmake, this may take several minutes
                      ===============================================================================
                    
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
Error configuring EXODUSII with cmake
*******************************************************************************```

Which meant the installation failed. Can you show the contents of `/program/firedrake/firedrake/src/petsc/configure.log` ?

I anticipate that you have a version of cmake that is too old.

**Comment by jaredcworkman** [comment]
Thanks. I’m running the install on ec2 instances that terminate post install failure. I’ll update cmake, reattempt, and send you the logs. Should I be needing to install python packages or will they link and download with a completed install.

Cheers,
Jared. 

Dr. Jared Workman 
HPC Engineer 
Rescale

**Comment by wence-** [comment]
OK, we should catch petsc install failure and cat the log so it appears. The python packages are installed by a completed install. We install inside a virtual environment, so making system packages available doesn't actually help!

**Comment by jaredcworkman** [comment]
Thanks. One other quick question. Can I use the intel compiler suite and intel mpi?

Cheers,
Jared

Dr. Jared Workman 
HPC Engineer 
Rescale

**Comment by wence-** [comment]
You should be able to. If you say `--mpicc intelmpicc --mpiexec intelmpiexec --mpicxx intelmpicxx --mpif90 intelmpif90` then we try to arrange that everything that we compile is built with the intel compilers. This may not be flawless, and I don't think we've tried the intel compilers recently...

**Comment by jaredcworkman** [comment]
I have a script that sets all of those variables. I guess I was more curious about runtime intel mpi. We try to default to intel mpi libraries for code execution but I wasn’t sure if I needed mpich for runtime with firedrake and mpi4py.   

Thanks,
Jared

Dr. Jared Workman 
HPC Engineer 
Rescale

**Comment by dham** [comment]
If you specify your own mpi compilers then the installer shouldn't build mpich and should use whichever MPI those compilers point at. This is pretty much required behaviour on supercomputers so we have to support it.

I can't recall whether setting those variables will also set the compiler used for just in time compilation, but that should be independent of the mpi question.

**Comment by jaredcworkman** [comment]
OK, I've updated cmake and it looks like you were right, thanks.  All I needed to do was to remove y old cmake, install a new one and run 
yum  install -y  python36
yum  install -y python36-devel.x86_64 - for the headers
I'll run make alltest to completion over night.  Thanks for the help. 

Question - does make alltest run any mpi tests?  If not can you point me to a quick sample validation script I can use to check node/multinode on?

Cheers,
Jared

**Comment by rckirby** [comment]
One caveat to using intel compilers -- if you're in an HPC environment,
then you need the license available on compute nodes.  The cluster at my
institution has both gcc and intel compilers, but the latter only have
licenses on login nodes.  Since firedrake generates code during run-time on
compute nodes, YMMV with intel.

**Comment by jaredcworkman** [comment]
How do I check the errors in make alltest?  I get the following
tests/multigrid/test_embedded_transfer.py make: *** [test] Error 123

**Comment by jaredcworkman** [comment]
Also, I install this program onto a snapshot directory that I later boot up and attach to an ec2 instance I get the following error "Error: Firedrake venv not active." but it shows as (firedrake) in front of the command prompt.  Any suggestions?
