### ISSUE TITLE
firedrake-update fails

### ISSUE THREAD

**Issue by sentz2** [firedrakeproject/firedrake#1612]
firedrake-update currently fails on a machine running Debian Linux.  The error message I receive is 

Cleaning PyOP2
Installing PyOP2/
Traceback (most recent call last):
  File "../bin/firedrake-update", line 1485, in <module>
    install(p+"/")
  File "../bin/firedrake-update", line 725, in install
    run_pip_install(["-e", package])
  File "../bin/firedrake-update", line 682, in run_pip_install
    check_call(pipinstall + pipargs)
  File "../bin/firedrake-update", line 524, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/sentz2/firedrake/bin/python', '-m', 'pip', 'install', '--no-binary', 'mpi4py,randomgen,islpy', '--no-deps', '-vvv', '-e', 'PyOP2/']' returned non-zero exit status 1.

Update log saved in /home/sentz2/firedrake/firedrake-update.log

I have attached the update log:
[firedrake-update.log](https://github.com/firedrakeproject/firedrake/files/4221338/firedrake-update.log)

**Comment by JDBetteridge** [comment]
`/home/sentz2/firedrake/src/petsc/include/petscsys.h:14:10: fatal error: petscconf.h: No such file or directory`

Suggests PETSc hasn't built/built correctly.
Try `firedrake-update --rebuild` if you let firedrake build PETSc for you (the default)
