### ISSUE TITLE
Zenodo release request

### ISSUE THREAD

**Issue by swarder** [firedrakeproject/firedrake#1622]
Hi,

Please can I have a Zenodo release for the below?

{"fiat": "8ceb29a3b9b14668b9d387321a3f8f4126f9a159", "firedrake": "23ea4ce1fc6edee221536d820feba1b98393ddc1", "COFFEE": "8563a56884a68ef00710fc7ddff98318f5818104", "FInAT": "de6f2ab96464f81d984c7d77522db6464d780cf8", "ufl": "510da040e48ea0d10f7fbb9390946cdb059c8881", "metarelease_info_file": null, "petsc4py": "60406028eb2b84f1abc61a7fd8f3a56a62774266", "petsc": "bf08679ea3a16b2203d34b0b2be4b3cd7e8a9b51", "tsfc": "bd9f3e817cb3ec2a35b6fbab67c3e116c2f55d21", "title": "A comparison of Bayesian inference and gradient-based approaches for friction parameter estimation", "PyOP2": "8da04363db6a9de931d28f6437e59e3d6cb97024"}

Except for the title, this is identical to the one I requested a few weeks ago (#1587), in case that saves any effort.

Thanks!

**Comment by wence-** [comment]
HI Simon, sorry for the delay, let me do this later today.

**Comment by swarder** [comment]
No problem, I've submitted the paper without this and will add it at a later point, so there's no rush.

Thanks

**Comment by wence-** [comment]
Tag: `Firedrake_20200521.0`

Bibtex:

```
@misc{zenodo/Firedrake-20200521.0,
 key   = {zenodo/Firedrake-20200521.0},
 title = {{Software used in 'A comparison of Bayesian inference and gradient-based approaches for friction parameter estimation'}},
 year  = {2020},
 month = {may},
 doi   = {10.5281/zenodo.3837272},
 url   = {https://doi.org/10.5281/zenodo.3837272},
}
```
