### ISSUE TITLE
Installation fails while configuring PETSc

### ISSUE THREAD

**Issue by volpatto** [firedrakeproject/firedrake#1629]
Hi all,

Well, here is another "installation issue", sorry. Firstly, I noticed that Firedrake now installs MPI stuffs through PETSc, this is great. As a user, I would like to thank you for that.

Unfortunately, I'm still facing some problems in a Manjaro OS machine during Firedrake's installation. Below I provide my log files:

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4352186/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/4352187/configure.log)

The thing is: checking out cmake logging for EXODUSII installation, it looks like that mpif90 is not included in the MPI stuff that is now managed by PETSc. CMake found a mpif90 from my system, which is, unfortunately, not compatible with Firedrake requirements (mpich implementation of MPI).

So, what I could do to fix my installation?

P.S.: All system requirements specified [here](https://www.firedrakeproject.org/download.html) are installed.

Cheers!

**Comment by volpatto** [comment]
Okay, this is very strange. I had a look in `firedrake-install` script, and everything seems to be correct configured. I think I'm misunderstanding the problem...

**Comment by danshapero** [comment]
Can you try installing again with `--minimal-petsc`? That will leave off exodus and a few other packages. That could narrow down the problem.

**Comment by volpatto** [comment]
> Can you try installing again with `--minimal-petsc`? That will leave off exodus and a few other packages. That could narrow down the problem.

Thanks, @danshapero! I'll try your suggestion.

**Comment by volpatto** [comment]
For future reference in case any user find (him/her)self stuck in similar problem..:

* @danshapero's suggestion above probably works;

* I also find myself a solution. As before (see #1543), I had to install `mpich` in my own system, then I provided `mpich` runners through `firedrake-install` option. Furthermore, Manjaro (and I think Arch-based OS in general) is working with Python 3.8, and OS depends on this new version. Python downgrade is not recommended (see [here](https://forum.manjaro.org/t/downgrading-python/121654)), it will probably break the system. The solution is to install Python 3.7 separately with a proper command, so `python`, `python3`, etc will remain unchanged. To do so, just install `yay`, then install `python37` from AUR (see [this answer](https://forum.manjaro.org/t/downgrading-python/121654/3)). Now, you can use the command `python3.7` in your terminal. But why you need it? The answer is simple (rationale is not): When I tried to install Firedrake with Python 3.8, I got stuck in the `vtk` installation managed by `pip` (if I remember well). When I used Python 3.7, no problem was found, a compatible `vtk` version is available.

At the end of the day, what I did? The command below works for me (Manjaro 19.0.2):

```console
python3.7 firedrake-install --disable-ssh --no-package-manager --mpicc /opt/mpich/bin/mpicc --mpicxx /opt/mpich/bin/mpicxx --mpif90 /opt/mpich/bin/mpif90 --mpiexec /opt/mpich/bin/mpiexec
```

Since the problem is solved for me, I'll close this issue.

**Comment by danshapero** [comment]
@volpatto I think the MPICH package on Arch is installed in /opt so as not to clobber an existing OpenMPI installation.

Also, to work with multiple versions of Python on the same system, I've had great luck using [pyenv](https://github.com/pyenv/pyenv) and pyenv-virtualenv with Firedrake.

**Comment by volpatto** [comment]
> @volpatto I think the MPICH package on Arch is installed in /opt so as not to clobber an existing OpenMPI installation.

Yes, you are correct. For some reason, Arch depends on OpenMPI. I don't know why they prefer OpenMPI, but OK. (this is based on what I read [here](https://aur.archlinux.org/packages/mpich/)).

> Also, to work with multiple versions of Python on the same system, I've had great luck using [pyenv](https://github.com/pyenv/pyenv) and pyenv-virtualenv with Firedrake.

This is a nice tip, I will certainly give it a try. In general, I use conda to manage packages and achieve portability, provisioning and etc. But I don't like to mix it with `virtualenv` or `pip`, since it harms conda's purpose for compatibility management. I already heard good things about `pyenv`, and since you have been achieving success with it, I think that I'll try to change my Firedrake workbase to use it.

Thanks for the support, @danshapero!
