### ISSUE TITLE
#1611 has mysterious side effects

### ISSUE THREAD

**Issue by sv2518** [firedrakeproject/firedrake#1633]
The latest change to the install script in "Work around homebrew linker issues. #1611" gives me "Assertion failed: (!PyErr_Occurred()), function __Pyx_PyCFunction_FastCall, file src/petsc4py.PETSc.c, line 329746." whenever I run tests and hit an assertion. It seems to be caused by setting the cflags.

**Comment by narciuch** [comment]
Related issue: For Slate's local solves/inverses there is a function that replaces the respective callables in loopy with calls to the external functions `LAPACKgetrf_` and `LAPACKgetri_` . These external functions are coming from `petscblaslapack.h` . When compiling tests for these cases, the following error was encountered:
`OSError: firedrake/.cache/pyop2/de/394a0424203546819010c84f805436.so: undefined symbol: dgetri_ `

This was resolved by doing: `export PYOP2_LDFLAGS=-llapack`
and then running `scripts/firedrake-install --rebuild-script`

**Comment by wence-** [comment]
Was this fixed?

**Comment by sv2518** [comment]
Yes
