### ISSUE TITLE
For simple/basic built of firedrake

### ISSUE THREAD

**Issue by issabass** [firedrakeproject/firedrake#1642]
Hello Firedrake team.
Can I build the firedrake library without PETSc?
HOw can i build a simple and basic version of the library without incorporating any *non-necessary* external dependencies? I just wanna learn and explore the basic tools of firedrake library.
Thank you very much
zaq

**Comment by rckirby** [comment]
It would be very difficult to do without PETSc.  All of the algebraic solvers and the mesh internals depend directly on PETSc.  So you couldn’t actually build a mesh or solve anything without it.  We aren’t going to recreate lesser functionality by hand-rolling these things.

On the bright side, Firedrake is actually very good at building/installing PETSc and other dependencies on standard Mac or Ubuntu, but it does take a bit of time for the installer to run.  Unless you use OpenCascade (definitely a non-essential dependency), the vast majority of build time for Firedrake is PETSc — an absolutely essential dependency — so I just recommend running Firedrake install and reading through online demos or having lunch.

Please report any problems (or successes) and people who understand the build system (so likely not me) will do their best to help.

**Comment by danshapero** [comment]
It's also possible to pass the option `--minimal-petsc` to the install script. This will leave out a few dependencies that are not strictly necessary for getting Firedrake to work and will shave a bit of time off the installation.

As Rob said, Firedrake relies on PETSc data structures at such a fundamental level that it would be impossible to use without installing PETSc. For basic to intermediate uses, you'll rarely have to interact with PETSc other than waiting for it to install and occasionally passing some solver options, most of which you can copy from whichever example script is most similar to your problem.

I'm closing this issue for now, but if you encounter a specific problem when installing you should feel free to raise another issue and someone will try to help.
