### ISSUE TITLE
Adjoint annotation without importing firedrake_adjoint

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#1645]
The following sequence does not work as expected:
```
from firedrake import *
from pyadjoint import continue_annotation
<do-non-annotated-stuff>
continue_annotation()
<code-to-be-annotated>
```
The reason for this is that by skipping the import of `firedrake_adjoint`, which immediately starts annotation, we also skip `import numpy_adjoint`. That latter import is necessary because it registers (as a side effect) `numpy.float64` to be "overloaded" by AdjFloat. If that registration is not done, assemble of a 0-form in firedrake fails when the annotation is switched on, because it doesn't know how to "overload" the return value of assemble.

An alternative is of course:
```
from firedrake 
from firedrake_adjoint import *
stop_annotation()
<do-non-annotated-stuff>
continue_annotation()
<code-to-be-annotated>
```
which is perfectly fine, but it's not immediately obvious why the first shouldn't work. It's also a bit awkward for the package-built-on-top-of-firedrake use case (say Thetis). I could put these first three lines in `thetis/__init__.py` but now importing thetis has the side effect of *stopping* the tape, i.e. there would be a difference between:
```
from firedrake_adjoint import ReducedFunctional
import thetis
```
and
```
import thetis
from firedrake_adjoint import ReducedFunctional
```

Note that another side effect of importing `firedrake_adjoint` is that it sets a new working tape. However this also happens in `firedrake/adjoint/__init.py` which is always imported with firedrake. So would it be reasonable to add an `import numpy_adjoint` in `firedrake/adjoint/__init.py` as well?

**Comment by wence-** [comment]
I have to say, I don't really like these side-effectful imports. It's kind of only "luck" that the first example works for non-scalar assembly (in that all of the objects happen to inherit from pyadjoint `OverloadedType`).

To me, it doesn't seem too bad that importing pyadjoint and continuing annotation doesn't work. What do firedrake and pyadjoint have to do with one another (why would I expect it to work).

Would a better interface be that `firedrake_adjoint` just registers overloaded types on import and that one must explicit ask for the annotation to be switched on?

Now annotations always live in "user" code and your final problem with order of import doesn't occur.

**Comment by stephankramer** [comment]
> Would a better interface be that firedrake_adjoint just registers overloaded types on import and that one must explicit ask for the annotation to be switched on?

I agree, but that would be an interface change (that I would be happy with). Would there still be any need for a separate `firedrake_adjoint` then? Note that the registering of most overloaded objects already happens by importing firedrake, it's just the overloading of `numpy.float64` that only happens through importing firedrake_adjoint.

**Comment by dham** [comment]
Yes, importing firedrake_adjoint sets the pyadjoint backend and provides the adjoint API.

**Comment by stephankramer** [comment]
Ok, fair enough.I agree that importing things directly from pyadjoint isn't required to work. Also agree that the automatic start of the tape upon importing `firedrake_adjoint` isn't ideal, but it doesn't hinder me at the moment. For now, we'll just use the following in thetis setups with adjoint:

    from thetis import *
    from firedrake_adjoint import *
