### ISSUE TITLE
Enable interior boundary conditions

### ISSUE THREAD

**Issue by ScottMacLachlan** [firedrakeproject/firedrake#1661]
For many coupled (multiphysics) problems, we would like to be able to impose boundary conditions on interior faces of the mesh that correspond to material or physics boundaries.  We can construct meshes with interior boundary faces marked via gmesh, so it's "just" a matter of getting rid of the internal assumption by firedrake that we'll only ever want to apply BCs to the exterior boundary.

Attached is an example of a mesh generated by gmesh with an interior face marked, and an implementation of `InteriorBC` that implements such functionality (Thanks @wence- !).  I'm opening the issue to prompt discussion on how this could be adapted to work natively.

For convenience, here's the relevant code block:
```
import numpy
from pyop2.datatypes import IntType
from pyop2.utils import as_tuple
from firedrake.utils import cached_property
from firedrake.cython.dmplex import FACE_SETS_LABEL
class InteriorBC(DirichletBC):
    @cached_property
    def nodes(self):
        dm = self.function_space().mesh()._plex
        section = self.function_space().dm.getDefaultSection()
        nodes = []
        for sd in as_tuple(self.sub_domain):
            nfaces = dm.getStratumSize(FACE_SETS_LABEL, sd)
            faces = dm.getStratumIS(FACE_SETS_LABEL, sd)
            if nfaces == 0:
                continue
            for face in faces.indices:
                if dm.getLabelValue("interior_facets", face) < 0:
                    continue
                closure, _ = dm.getTransitiveClosure(face)
                for p in closure:
                    dof = section.getDof(p)
                    offset = section.getOffset(p)
                    nodes.extend((offset + d) for d in range(dof))
        return numpy.unique(numpy.asarray(nodes, dtype=IntType))
```

[interiorBCfiles.zip](https://github.com/firedrakeproject/firedrake/files/4517928/interiorBCfiles.zip)

**Comment by wence-** [comment]
Coming back to this, it would be trivial to do all of this if we removed the `method="geometric"` argument to `DirichletBC` (which applies bcs to dofs that have non-zero support on faces, rather than ones which are topologically associated with the faces). This is a dolfin-compatibility argument, but it makes very little mathematical sense. So I would really just like to remove it.

**Comment by tranner** [comment]
Hi, I was pointed to the issue from the mailing list and it does seem to be exactly what I wanted. 

I don't know enough to know whether this is something that should be in `DirichletBC` or a separate class but I found it counter-intuitive that `DirichletBC` doesn't give a warning if passed an internal face id but doesn't do anything.

I've tried to use this code but get an error - is there a version of firedrake I should try to use?

```
$ python -c 'import firedrake; print(firedrake._version.get_versions())'
{'version': '0.13.0+4371.g3df67d85', 'full-revisionid': '3df67d856c34b14be0784ba0e8f93cf9f99f4ddc', 'dirty': False, 'error': None}
$ python advection-diffusion.py
Traceback (most recent call last):
  File "advection-diffusion.py", line 5, in <module>
    from interiorbc import InteriorBC
  File "/localhome/scstr/Software/python-fem/firedrake-moving-interface/interiorbc.py", line 7, in <module>
    from firedrake.cython.dmplex import FACE_SETS_LABEL
ModuleNotFoundError: No module named 'firedrake.cython.dmplex'
```

**Comment by wence-** [comment]
We shuffled some internal modules around, if you `from firedrake.cython.dmcommon import FACE_SETS_LABEL` it should work

**Comment by wence-** [comment]
#2007 attempts to do this. Can those of you who have uses cases try it? I should incorporate the test from the first post.
