### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by andreasbock** [firedrakeproject/firedrake#1665]
Could you create a release for me please? Thanks.

`{"metarelease_info_file": null, "FInAT": "2f0e0bd61fd5800920ed66a2c3347d4d916c0045", "loopy": "a6ee11ec9c630fed4e855cd09be03e3853b595ae", "firedrake": "e4cefd12fa6195dec6a317735e61f15282f9b1d6", "PyOP2": "8e1c5720fe0a8f7b4e870a49c43608d97c66ad14", "COFFEE": "72a4464aa18fd408de5304ac467db18d7af2b670", "tsfc": "6a0c1b73d472829bd92cfe82f5e2a79d235daf4b", "fiat": "ae587ff3a32be0b23edae3222e88b0f62da9f3e4", "ufl": "4516a6d5023eb5dfe62ec2431865e125aa6daf97", "petsc": "0d9a514b7d7c5c0bcef72be50478634c8ea73815", "petsc4py": "9bcb404c3b9bb7ba5a4c5f522d0f6894e6e0d6bf", "title": "Space-time image metamorphosis"}`

**Comment by wence-** [comment]
Tag is `Firedrake_20200430.0`

```
@misc{zenodo/Firedrake-20200430.0,
 key   = {zenodo/Firedrake-20200430.0},
 title = {{Software used in 'Space-time image metamorphosis'}},
 year  = {2020},
 month = {apr},
 doi   = {10.5281/zenodo.3778236},
 url   = {https://doi.org/10.5281/zenodo.3778236},
}```
