### ISSUE TITLE
Plotting of 1D DG basis functions looks odd

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#1676]
Consider the following code:

```
from firedrake import *
from matplotlib import pyplot as plt

mesh = UnitIntervalMesh(1)

V = FunctionSpace(mesh, "Discontinuous Lagrange", 1)
u = Function(V)

u.dat.data[:] = 0
u.dat.data[0] = 1
plot(u)
plt.show()
```

I expected it to show a line from (0, 1) to (1, 0), or from (0, 0) to (1, 1). Instead it shows

![bug](https://user-images.githubusercontent.com/3494657/81154534-e5f4da80-8f7b-11ea-96e6-5fa5691b855e.png)

It does the right thing for CG1.

**Comment by wence-** [comment]
I bet those points are 0.22... and 0.78...

**Comment by danshapero** [comment]
Does #1678 fix this one too?

**Comment by pefarrell** [comment]
Yes, it does, and of course `variant="equispaced"` is also necessary for what I expect. Thanks!
