### ISSUE TITLE
Plotting 1D basis functions should set ylim automatically

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#1677]
I am trying to sketch the CG2 basis functions for some students. I tried

```
from firedrake import *
from matplotlib import pyplot as plt

mesh = UnitIntervalMesh(3)

V = FunctionSpace(mesh, "Lagrange", 2)
u = Function(V)

for i in range(len(u.dat.data)):
    u.dat.data[:] = 0
    u.dat.data[i] = 1
    plot(u)
plt.show()
```

This plots the correct basis functions, but the image is chopped off: the y-limit of the plot is set to [0, 1], even though the basis functions can be negative. This gives pictures like the one attached:

![cg2](https://user-images.githubusercontent.com/3494657/81157143-9663de00-8f7e-11ea-8fcd-0a1fe53fcc8d.png)

The plotting code should figure out the right y limit automatically.

**Comment by wence-** [comment]
Try this?
```patch
diff --git a/firedrake/plot.py b/firedrake/plot.py
index 7ad2dcd3..34441378 100644
--- a/firedrake/plot.py
+++ b/firedrake/plot.py
@@ -318,18 +318,20 @@ def plot(function, *args, bezier=False, num_sample_points=10, **kwargs):
         axes = figure.add_subplot(111)
 
     if function.ufl_element().degree() < 4:
-        return _bezier_plot(function, axes, **kwargs)
-
-    if bezier:
-        num_sample_points = max((num_sample_points // 3) * 3 + 1, 4)
-    points = calculate_one_dim_points(function, num_sample_points)
-
-    if bezier:
-        return _interp_bezier(points,
-                              function.function_space().mesh().num_cells(),
-                              axes, **kwargs)
-
-    return axes.plot(points[0], points[1], *args, **kwargs)
+        result = _bezier_plot(function, axes, **kwargs)
+    else:
+        if bezier:
+            num_sample_points = max((num_sample_points // 3) * 3 + 1, 4)
+        points = calculate_one_dim_points(function, num_sample_points)
+
+        if bezier:
+            result = _interp_bezier(points,
+                                    function.function_space().mesh().num_cells(),
+                                    axes, **kwargs)
+        else:
+            result = axes.plot(points[0], points[1], *args, **kwargs)
+    _autoscale_view(axes, None)
+    return result
 
 
 def _calculate_values(function, points, dimension, cell_mask=None):
```

**Comment by pefarrell** [comment]
Lawrence's patch shows all of the function. I would say the y-limit chosen is too large, but I think that's a matter of personal taste. I'm happy with the above patch.

**Comment by wence-** [comment]
That can be fiddled, probably by autoscaling with `tight=True`? Can you try that and see?

**Comment by wence-** [comment]
Make the last line `axes.autoscale_view(tight=True)` instead (I think).

**Comment by pefarrell** [comment]
I agree that from the matplotlib docs `axes.autoscale_view(tight=True)` should work, but it doesn't. I'm happy enough with the situation after your first patch that it's not worth digging in further.

**Comment by danshapero** [comment]
Ah this got brought up in slack the other day, I forgot to add in autoscaling the view when I rewrote that one -- I'll fix it now.
