### ISSUE TITLE
Installation script fails

### ISSUE THREAD

**Issue by konsim83** [firedrakeproject/firedrake#1679]
Hi,
I am experiencing an issue when installing Firedrake on Ubuntu 20.04. 
Cheers,
Konrad
This is the error message when running "python3 firedrake-install --minimal-petsc".
.......
.......
.......
Pip installing VTK for Python3.8
Traceback (most recent call last):
  File "firedrake-install", line 1294, in <module>
    run_pip_install("https://github.com/firedrakeproject/VTKPythonPackage/releases/download/firedrake_20200224/vtk-8.1.2-cp38-cp38-linux_x86_64.whl")
  File "firedrake-install", line 689, in run_pip_install
    pipargs = ["-vvv"] + pipargs
TypeError: can only concatenate list (not "str") to list

**Comment by djanekovic** [comment]
Hi Konrad,

I think this simple patch should fix your issue:
```
diff --git a/scripts/firedrake-install b/scripts/firedrake-install
index d5ef421c..50ed7de5 100755
--- a/scripts/firedrake-install
+++ b/scripts/firedrake-install
@@ -1289,9 +1289,9 @@ if mode == "install":
     if sys.version_info >= (3, 8):
         log.info("Pip installing VTK for Python3.8")
         if osname == "Darwin":
-            run_pip_install("https://github.com/firedrakeproject/VTKPythonPackage/releases/download/firedrake_20200224/vtk-8.1.2-cp38-cp38-macosx_10_14_x86_64.whl")
+            run_pip_install(["https://github.com/firedrakeproject/VTKPythonPackage/releases/download/firedrake_20200224/vtk-8.1.2-cp38-cp38-macosx_10_14_x86_64.whl"])
         elif osname == "Linux":
-            run_pip_install("https://github.com/firedrakeproject/VTKPythonPackage/releases/download/firedrake_20200224/vtk-8.1.2-cp38-cp38-linux_x86_64.whl")
+            run_pip_install(["https://github.com/firedrakeproject/VTKPythonPackage/releases/download/firedrake_20200224/vtk-8.1.2-cp38-cp38-linux_x86_64.whl"])
 
 
 petsc_dir, petsc_arch = get_petsc_dir()

```

I pushed the fix so that you can run installer like this:
```
curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/djanekovic/fix-python3.8-install/scripts/firedrake-install
python3 firedrake-install --minimal-petsc
```

Kind regards,
Darko

**Comment by konsim83** [comment]
Hi @djanekovic 

Thank you a lot, Darko. This fixed the first issue but there is another issue related to Python 3.8. Now I get further until:

.........
.........
.........
Installing petsc/
Downloading Eigen from 'https://github.com/eigenteam/eigen-git-mirror/archive/3.3.3.tar.gz' to 'eigen-3.3.3.tgz'
Checking Eigen tarball integrity
Eigen tarball hash valid
Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "firedrake-install", line 1374, in <module>
    install("petsc/")
  File "firedrake-install", line 730, in install
    build_and_install_petsc()
  File "firedrake-install", line 838, in build_and_install_petsc
    check_call(["./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + list(petsc_options))
  File "firedrake-install", line 532, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./configure', 'PETSC_DIR=/home/ksimon/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-eigen=/home/ksimon/firedrake/src/eigen-3.3.3.tgz ', '--download-chaco', '--download-hdf5=https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.bz2', '--download-scalapack', '--download-mumps', '--with-fortran-bindings=0', '--download-hypre', '--download-mpich', '--with-debugging=0', '--download-ptscotch', '--with-shared-libraries=1', '--with-cxx-dialect=C++11', '--with-c2html=0', '--download-superlu_dist']' returned non-zero exit status 127.


The log-file says:

2020-05-07 09:17:45,191 DEBUG  Running command './configure PETSC_DIR=/home/ksimon/firedrake/src/petsc PETSC_ARCH=default --download-superlu_dist --download-metis --with-c2html=0 --with-cxx-dialect=C++11 --download-mumps --download-eigen=/home/ksimon/firedrake/src/eigen-3.3.3.tgz  --download-pnetcdf --download-exodusii --download-scalapack --with-debugging=0 --download-ml --download-pastix --download-ptscotch --download-chaco --with-zlib --with-shared-libraries=1 --download-hdf5=https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.6/src/hdf5-1.10.6.tar.bz2 --download-mpich --download-hypre --with-fortran-bindings=0 --download-hwloc --download-suitesparse --download-netcdf'
2020-05-07 09:17:45,193 DEBUG  **/usr/bin/env: ‘python’: No such file or directory**

I found out that there is no sym-link python -> python3 installed by default (at least not on ubuntu 20.04). Installing it fixes the issue. Would it be better to point directly to python3 in this case?

Best,
Konrad

**Comment by wence-** [comment]
Given that we need python3 anyway, updating that command to run `python3 ./configure -...` is probably the right thing, yes. PETSc itself can configure with python2 or python3, so changing the `/usr/bin/env python` command there is wrong.

**Comment by konsim83** [comment]
OK, but many thanks for your help. I got it working.
