### ISSUE TITLE
Adjoint annotation wrapper obliterates `assemble` docstring

### ISSUE THREAD

**Issue by inducer** [firedrakeproject/firedrake#1680]
The [docstring for `assemble`](https://firedrakeproject.org/firedrake.html?highlight=assemble#firedrake.assemble.assemble) is no longer quite its [useful self](https://github.com/firedrakeproject/firedrake/blob/73013086471c9db5f56a6aaad834b756c813f0d9/firedrake/assemble.py#L30-L84).

**Comment by wence-** [comment]
Thanks. This is actually a more general problem with the adjoint annotation. The handcoded decorators always override the docstring of the underlying method. I think the right thing to do is for all of the decorators to use [`functools.wraps`](https://docs.python.org/dev/library/functools.html#functools.wraps)

**Comment by nbouziani** [comment]
I have used `functools.wraps` as suggested @wence-  (which conserves `__name__` and `__doc__`) for assemble, solve and more generally dor all the different adjoint wrappers. This was also causing some problems for `MeshGeometry._coordinates_function`.

See #1684

**Comment by dham** [comment]
Nacime's fix has now landed so this should be fixed.
