### ISSUE TITLE
Reorder mesh

### ISSUE THREAD

**Issue by klosedan** [firedrakeproject/firedrake#1683]
Hey guys,
I want to import a mesh without reordering the nodes. However, when I use the parameter reorder=False for the Mesh function, I observe that the nodes are reordered anyway. However, in a different order than with reorder=True. I implemented a simple example to illustrate the issue: 

```python
import numpy as np
import scipy.io as sio
from firedrake import *

filename='test.msh'
dimension=3
ndata=2131

# Read data manually
coords_man=np.zeros((ndata,dimension))
with open(filename) as fp:
    line = fp.readline()
    flag_read=0
    while line:
        if 'EndNodes' in line:
            flag_read=0
            line=fp.readline()
        if 'Nodes' in line:
            flag_read=1
            next(fp)
            line=fp.readline()
        if flag_read==1:
            row=np.fromstring(line,sep=' ')
            coords_man[int(row[0])-1,:]=row[1:dimension+1]
        line = fp.readline()

# Read data with firedrake
mesh=Mesh(filename,dim=dimension,reorder=True)
meshcoordinates=mesh.coordinates.vector().array()
n=int(meshcoordinates.shape[0]/dimension)
coords_fd=meshcoordinates.reshape(n,dimension)
sio.savemat('coords.mat',{"manual":coords_man,'firedrake':coords_fd})
```
Best regards
Daniel

[example.zip](https://github.com/firedrakeproject/firedrake/files/4602966/example.zip)

**Comment by wence-** [comment]
The reordering refers to whether we visit the cells in the order the mesh numbered them or not (with some caveats in parallel). Vertices will always be reordered due to constraints on the numbering requirements. 

Why do you need to match up with your external numbering?

**Comment by klosedan** [comment]
OK, I missunderstood that point. 
In my particular case I have a mesh which is deforming over time.  I have the information about the deformation of each node and want to map it to the firedrake mesh.

**Comment by klosedan** [comment]
I solved that issue with some post processing. 
I mapped the firedrake coordinates with the ones read manually from the .msh file.

**Comment by wence-** [comment]
Thanks, that's the normal way right now.
