### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by andreasbock** [firedrakeproject/firedrake#1692]
Hi,

Could you please create a Zenodo release for me?

{"PyOP2": "8e1c5720fe0a8f7b4e870a49c43608d97c66ad14", "fiat": "ae587ff3a32be0b23edae3222e88b0f62da9f3e4", "title": "Andreas Bock PhD thesis", "firedrake": "e4cefd12fa6195dec6a317735e61f15282f9b1d6", "petsc": "0d9a514b7d7c5c0bcef72be50478634c8ea73815", "metarelease_info_file": null, "ufl": "4516a6d5023eb5dfe62ec2431865e125aa6daf97", "COFFEE": "72a4464aa18fd408de5304ac467db18d7af2b670", "FInAT": "2f0e0bd61fd5800920ed66a2c3347d4d916c0045", "petsc4py": "9bcb404c3b9bb7ba5a4c5f522d0f6894e6e0d6bf", "tsfc": "6a0c1b73d472829bd92cfe82f5e2a79d235daf4b", "loopy": "a6ee11ec9c630fed4e855cd09be03e3853b595ae"}

Thanks,
Andreas

**Comment by wence-** [comment]
Tag `Firedrake_20200518.0`
Bibtex
```
@misc{zenodo/Firedrake-20200518.0,
 key   = {zenodo/Firedrake-20200518.0},
 title = {{Software used in 'Andreas Bock PhD thesis'}},
 year  = {2020},
 month = {may},
 doi   = {10.5281/zenodo.3832141},
 url   = {https://doi.org/10.5281/zenodo.3832141},
}```
