### ISSUE TITLE
Install failed during complie petsc

### ISSUE THREAD

**Issue by tyszwh** [firedrakeproject/firedrake#1695]
Hi, everybody.
Although there have some questions about the install failed during compile petsc, I have not find a solution for me.
I have installed it successfully last year. But now it stuck in compiling petsc.
I set PETSC_CONFIGURE_OPTIONS="--download-hdf5=/home/tysz/888/depedence/hdf5-1.10.6.tar.gz --download-netcdf=/home/tysz/888/depedence/netcdf-c-4.5.0.tar.gz --download-fblaslapack=1" and use python3 firedrake-install.
I have attached the firedrake-install.log and config.log from petsc.
Can anyone help me figure out the problem?

[configure.log](https://github.com/firedrakeproject/firedrake/files/4650032/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4650033/firedrake-install.log)

**Comment by dham** [comment]
From the configure.log, the failure is here:
```
cmake --version failed: Could not execute "['/home/tysz/build_install/seperate/cmake_3.16/bin/cmake --version']":
/home/tysz/build_install/seperate/cmake_3.16/bin/cmake: error while loading shared libraries: libmpi.so.40: cannot open shared object file: No such file or directory
```

Now `libmpi.so.40` is an openmpi library (you can tell from the version number). It looks like you have your own-build cmake in your path and that it's linked against openmpi. Because Firedrake now builds its own mpich by default (because openmpi has issues we can't live with), using your cmake in the Firedrake build fails. I suggest using the system cmake instead.

**Comment by tyszwh** [comment]
Thanks for your support. Now I have fixed the petsc problem.
 But a new error occurred related to libtool.
However, I have installed the libtool through (sudo apt-get install libtool)
`error: Libtool library used but 'LIBTOOL' is undefined.`
The log attached below.
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4656879/firedrake-install.log)
And if the firedrake install failed, is there a way to continue install, or I must delete the old firedrake.

**Comment by dham** [comment]
I haven't seen this one before but google mostly shows this issue coming up several years ago. What OS version is this, and what versions of autotools and libtool do you have?

It is sometimes possible to restart a firedrake install. The way to do this is to activate the firedrake venv and then run `firedrake-update`. Effectively, once you get a little way into the install you have enough of an installation that the update script will work. This can avoid the need to rebuild PETSc.

**Comment by tyszwh** [comment]
I have solved the problem by deleting related libtool and reinstalling it.
Now I install firedrake successfully except the make alltest failed.
My system is ubuntu 18.04.

`=================================== FAILURES ===================================
____________________ test_horiz_facet_interior_jump[False] _____________________

mesh = Mesh(VectorElement(TensorProductElement(FiniteElement('Lagrange', triangle, 1), FiniteElement('Lagrange', interval, 1), cell=TensorProductCell(triangle, interval)), dim=3), 42831)

    def test_horiz_facet_interior_jump(mesh):
        DG = VectorFunctionSpace(mesh, "DG", 1)
        n = FacetNormal(mesh)
        u = TestFunction(DG)
    
        x, y, z = SpatialCoordinate(mesh)
        f = project(as_vector([z, y, x]), DG)
        form = jump(f[2]*f[1]*u, n=n)*dS_h
    
        A = assemble(Tensor(form)).dat.data
        ref = assemble(form).dat.data
    
>       assert np.allclose(A, ref, rtol=1e-14)
E       assert False
E        +  where False = <function allclose at 0x7fa046a9c0e0>(array([[ 0.00000000e+00,  0.00000000e+00, -1.90638231e-04],\n       [ 0.00000000e+00,  0.00000000e+00,  7.11471564e-04]...      [ 2.40917094e-18,  0.00000000e+00, -4.33997654e-02],\n       [-6.45535408e-19,  0.00000000e+00,  1.16289321e-02]]), array([[ 0.00000000e+00,  0.00000000e+00,  1.90638231e-04],\n       [ 0.00000000e+00,  0.00000000e+00, -7.11471564e-04]...      [-2.40917094e-18,  0.00000000e+00, -4.33997654e-02],\n       [ 6.45535408e-19,  0.00000000e+00,  1.16289321e-02]]), rtol=1e-14)
E        +    where <function allclose at 0x7fa046a9c0e0> = np.allclose

tests/slate/test_facet_tensors_extr.py:24: AssertionError
=============================== warnings summary ===============================
tests/regression/test_line_smoother_periodic.py::test_line_smoother_periodic
tests/regression/test_line_smoother_periodic.py::test_line_smoother_periodic
  /home/tysz/888/Multiphysics/firedrake/lib/python3.7/site-packages/pymbolic/parser.py:284: DeprecationWarning: Usage of 'if' as an identifier is deprecated due to introduction of python style 'if-else' expressions.
    left_exp = self.parse_terminal(pstate)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=========================== short test summary info ============================
FAILED tests/slate/test_facet_tensors_extr.py::test_horiz_facet_interior_jump[False]
===== 1 failed, 5639 passed, 31 skipped, 2 warnings in 13954.68s (3:52:34) =====
Makefile:64: recipe for target 'test' failed
`

[make_alltest.txt](https://github.com/firedrakeproject/firedrake/files/4665885/make_alltest.txt)

**Comment by wence-** [comment]
Huh, nearly all working, except for a sign flip in one test. Weird.

Can you try the following:

```
PYOP2_DEBUG=1 pytest 'tests/slate/test_facet_tensors_extr.py::test_horiz_facet_interior_jump[False]'
```

In the activated venv?

**Comment by tyszwh** [comment]
Yes, It passed.
'''
PYOP2_DEBUG=1 pytest 'tests/slate/test_facet_tensors_extr.py::test_horiz_facet_interior_jump[False]'
============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/tysz/888/Multiphysics/firedrake/src/firedrake, inifile: setup.cfg
plugins: forked-1.1.3, xdist-1.32.0
collected 1 item                                                               

tests/slate/test_facet_tensors_extr.py .                                                     [100%]

======================================== 1 passed in 18.06s ========================================
'''

**Comment by wence-** [comment]
OK, and now let's check on its own without the debug. Run `firedrake-clean` and then do
```
unset PYOP2_DEBUG
pytest 'tests/slate/test_facet_tensors_extr.py::test_horiz_facet_interior_jump[False]'
```

Thanks!

**Comment by tyszwh** [comment]
Ok, now, the same error occurred.
```
pytest 'tests/slate/test_facet_tensors_extr.py::test_horiz_facet_interior_jump[False]'
======================================= test session starts ========================================
platform linux -- Python 3.7.6, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/tysz/888/Multiphysics/firedrake/src/firedrake, inifile: setup.cfg
plugins: forked-1.1.3, xdist-1.32.0
collected 1 item                                                                                   

tests/slate/test_facet_tensors_extr.py F                                                     [100%]

============================================= FAILURES =============================================
______________________________ test_horiz_facet_interior_jump[False] _______________________________

mesh = Mesh(VectorElement(TensorProductElement(FiniteElement('Lagrange', triangle, 1), FiniteElement('Lagrange', interval, 1), cell=TensorProductCell(triangle, interval)), dim=3), 4)

    def test_horiz_facet_interior_jump(mesh):
        DG = VectorFunctionSpace(mesh, "DG", 1)
        n = FacetNormal(mesh)
        u = TestFunction(DG)
    
        x, y, z = SpatialCoordinate(mesh)
        f = project(as_vector([z, y, x]), DG)
        form = jump(f[2]*f[1]*u, n=n)*dS_h
    
        A = assemble(Tensor(form)).dat.data
        ref = assemble(form).dat.data
    
>       assert np.allclose(A, ref, rtol=1e-14)
E       assert False
E        +  where False = <function allclose at 0x7f0ac325d3b0>(array([[ 0.00000000e+00,  0.00000000e+00, -1.90638231e-04],\n       [ 0.00000000e+00,  0.00000000e+00,  7.11471564e-04]...      [ 2.40917094e-18,  0.00000000e+00, -4.33997654e-02],\n       [-6.45535408e-19,  0.00000000e+00,  1.16289321e-02]]), array([[ 0.00000000e+00,  0.00000000e+00,  1.90638231e-04],\n       [ 0.00000000e+00,  0.00000000e+00, -7.11471564e-04]...      [-2.40917094e-18,  0.00000000e+00, -4.33997654e-02],\n       [ 6.45535408e-19,  0.00000000e+00,  1.16289321e-02]]), rtol=1e-14)
E        +    where <function allclose at 0x7f0ac325d3b0> = np.allclose

tests/slate/test_facet_tensors_extr.py:24: AssertionError
--------------------------------------- Captured stderr call ---------------------------------------
UFL:WARNING Discontinuous Lagrange element requested on triangle * interval, creating DQ element.
---------------------------------------- Captured log call -----------------------------------------
WARNING  UFL:log.py:141 Discontinuous Lagrange element requested on triangle * interval, creating DQ element.
===================================== short test summary info ======================================
FAILED tests/slate/test_facet_tensors_extr.py::test_horiz_facet_interior_jump[False] - assert False
======================================== 1 failed in 17.77s ========================================
```

**Comment by wence-** [comment]
OK, this looks like it might be a C compiler bug. Can you show `mpicxx --version`. Also the output of `cat /proc/cpuinfo` ?

**Comment by tyszwh** [comment]
```
mpicxx --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
and cat /proc/cpuinfo in the attached file
[log.txt](https://github.com/firedrakeproject/firedrake/files/4667661/log.txt)

**Comment by wence-** [comment]
I think this was fixed by some changes in PyOP2.
