### ISSUE TITLE
Requesting Zenodo release for upcoming paper "Augmented saddle point formulation of the steady-state Stefan--Maxwell diffusion equations"

### ISSUE THREAD

**Issue by AlexanderVB** [firedrakeproject/firedrake#1711]
The firedrake.json file is zipped in the file below (it wouldn't let me attach the .json file directly).

[firedrake.zip](https://github.com/firedrakeproject/firedrake/files/4689542/firedrake.zip)

**Comment by wence-** [comment]
I am doing this, but the zenodo API is _very_ slow to respond, so github webhook events timeout (with the result that we haven't managed to archive Firedrake and PyOP2 yet). I'll go again tomorrow.

**Comment by wence-** [comment]
It stopped crying.

Tag: `Firedrake_20200527.0`

Bibtex:

```
@misc{zenodo/Firedrake-20200527.0,
 key   = {zenodo/Firedrake-20200527.0},
 title = {{Software used in 'Augmented saddle point formulation of the steady-state Stefan--Maxwell diffusion equations'}},
 year  = {2020},
 month = {may},
 doi   = {10.5281/zenodo.3860438},
 url   = {https://doi.org/10.5281/zenodo.3860438},
}
```

**Comment by AlexanderVB** [comment]
Great thank you Lawrence! This is our our upcoming paper with Patrick
Farrell.
