### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by alexanderzimmerman** [firedrakeproject/firedrake#1713]
Per [Firedrake's Zenodo integration instructions](https://www.firedrakeproject.org/zenodo.html), could a Zenodo release please be created using the following JSON?

```json
{"firedrake": "5b5e2890cd1e20a037dda910ac44d2e76a235e39", "PyOP2": "8e1c5720fe0a8f7b4e870a49c43608d97c66ad14", "tsfc": "6a0c1b73d472829bd92cfe82f5e2a79d235daf4b", "COFFEE": "72a4464aa18fd408de5304ac467db18d7af2b670", "ufl": "4516a6d5023eb5dfe62ec2431865e125aa6daf97", "FInAT": "2f0e0bd61fd5800920ed66a2c3347d4d916c0045", "fiat": "ae587ff3a32be0b23edae3222e88b0f62da9f3e4", "petsc": "bbc3b47c2450b090879fad6292a3c84746e81201", "petsc4py": "9bcb404c3b9bb7ba5a4c5f522d0f6894e6e0d6bf", "loopy": "a6ee11ec9c630fed4e855cd09be03e3853b595ae", "metarelease_info_file": null, "title": "Mixed finite elements for convection-coupled phase-change in enthapy form: Open software verified and applied to 2D benchmarks"}
```

I hope to finish revising a journal article in the next week or two and to cite this.

Thanks!

**Comment by wence-** [comment]
Will do this, zenodo is being flaky today though.

**Comment by wence-** [comment]
Looks like zenodo/github integration fell over in the last week. c.f. zenodo/zenodo#2002.

**Comment by alexanderzimmerman** [comment]
@wence- , do you have any idea if there is someone who might prioritize fixing that?

If I manage to have this revision ready for submitting before that is done, do you have any suggestions for the next best practice for documenting my Firedrake build?

Thanks for your advice!

**Comment by wence-** [comment]
Effectively this looks like a zenodo breakage, but they are not listening AFAICT.

It looks like zenodo development is dead, no-one ever responds to any issues. And it seems like hook delivery is still not managing to create new releases.

It looks like no-one cares about it right now. I wonder if we should just manually manage talking to the web API rather than going through the github release "automation".

**Comment by wence-** [comment]
Update, it looks like, without mentioning it anywhere, they changed their processing to _only_ archive releases rather than also prereleases (which is what we were making). I've changed that, so I think we'll get an archive for you momentarily.

**Comment by wence-** [comment]
OK:

Tag: `Firedrake_20200611.3`

Bibtex,

```
@misc{zenodo/Firedrake-20200611.3,
 key   = {zenodo/Firedrake-20200611.3},
 title = {{Software used in 'Mixed finite elements for convection-coupled phase-change in enthapy form: Open software verified and applied to 2D benchmarks'}},
 year  = {2020},
 month = {jun},
 doi   = {10.5281/zenodo.3890252},
 url   = {https://doi.org/10.5281/zenodo.3890252},
}
```

**Comment by alexanderzimmerman** [comment]
Thanks!

**Comment by alexanderzimmerman** [comment]
Hey @wence- , I just realized that I wrote "enthapy" instead of "enthalpy" in the JSON that I gave you above. I copied and pasted the same typo in a release of my user code which also went to Zenodo. Thankfully, on Zenodo, I was able to edit the that to "enthalpy" without changing the DOI. 

Could you do also change "enthapy" to "enthalpy" at https://doi.org/10.5281/zenodo.3890252 without changing the DOI? So the whole title should be

    Software used in 'Mixed finite elements for convection-coupled phase-change in enthalpy form: Open software verified and applied to 2D benchmarks'

Sorry for the trouble.

**Comment by wence-** [comment]
Done.

**Comment by alexanderzimmerman** [comment]
Thanks!
