### ISSUE TITLE
ModuleNotFoundError: No module named 'Cython',/Users/zhangweilin/opt/anaconda3/bin/python: No module named flake8

### ISSUE THREAD

**Issue by acse-wz19** [firedrakeproject/firedrake#1721]
I have re-install it several  times, but always module not found error happened. I do not know why and  I attach the log file here
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4730429/firedrake-install.log)

**Comment by acse-wz19** [comment]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/56032987/83765017-3cedec80-a6ad-11ea-9f03-e11d4d0758dd.png">
this is the test error shown on my screen

**Comment by wence-** [comment]
The install went fine, but it looks like you haven't activated the firedrake virtual environment before running `make alltest`.

**Comment by acse-wz19** [comment]
Building extension modules
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from Cython.Distutils import build_ext
ModuleNotFoundError: No module named 'Cython'
    Linting firedrake codebase
/Users/zhangweilin/opt/anaconda3/bin/python: No module named flake8
make: *** [lint] Error 1

**Comment by acse-wz19** [comment]
I hope you can help me figure out this problem, thanks

**Comment by acse-wz19** [comment]
Yes I will try it now,thanks

**Comment by acse-wz19** [comment]
is this all_test takes a very long time?
and I can not use the function contained in this package.
<img width="912" alt="image" src="https://user-images.githubusercontent.com/56032987/83773998-c9051180-a6b7-11ea-9a53-8321ed515d42.png">

**Comment by wence-** [comment]
I am confused that you don't see `UnitSquareMesh` though, since I would have expected that if the import did not fail, then the function should be available.

**Comment by acse-wz19** [comment]
my test presently is .... rather than FFF

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Zhang, Weilin <weilin.zhang19@imperial.ac.uk>
发送时间: Thursday, June 4, 2020 11:30:17 PM
收件人: firedrakeproject/firedrake <reply@reply.github.com>; firedrakeproject/firedrake <firedrake@noreply.github.com>
抄送: Author <author@noreply.github.com>
主题: Re: [firedrakeproject/firedrake] ModuleNotFoundError: No module named 'Cython',/Users/zhangweilin/opt/anaconda3/bin/python: No module named flake8 (#1721)

but this problem happens on my notebook, and I can not import Thetis also. It is quite confusing me. Do you have any idea of this situation?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Lawrence Mitchell <notifications@github.com>
发送时间: Thursday, June 4, 2020 11:07:18 PM
收件人: firedrakeproject/firedrake <firedrake@noreply.github.com>
抄送: Zhang, Weilin <weilin.zhang19@imperial.ac.uk>; Author <author@noreply.github.com>
主题: Re: [firedrakeproject/firedrake] ModuleNotFoundError: No module named 'Cython',/Users/zhangweilin/opt/anaconda3/bin/python: No module named flake8 (#1721)


This email from notifications@github.com originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



I am confused that you don't see UnitSquareMesh though, since I would have expected that if the import did not fail, then the function should be available.

―

**Comment by acse-wz19** [comment]
it also contains ssss

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Zhang, Weilin <weilin.zhang19@imperial.ac.uk>
发送时间: Thursday, June 4, 2020 11:38:55 PM
收件人: firedrakeproject/firedrake <reply@reply.github.com>; firedrakeproject/firedrake <firedrake@noreply.github.com>
抄送: Author <author@noreply.github.com>
主题: Re: [firedrakeproject/firedrake] ModuleNotFoundError: No module named 'Cython',/Users/zhangweilin/opt/anaconda3/bin/python: No module named flake8 (#1721)

my test presently is .... rather than FFF

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Zhang, Weilin <weilin.zhang19@imperial.ac.uk>
发送时间: Thursday, June 4, 2020 11:30:17 PM
收件人: firedrakeproject/firedrake <reply@reply.github.com>; firedrakeproject/firedrake <firedrake@noreply.github.com>
抄送: Author <author@noreply.github.com>
主题: Re: [firedrakeproject/firedrake] ModuleNotFoundError: No module named 'Cython',/Users/zhangweilin/opt/anaconda3/bin/python: No module named flake8 (#1721)

but this problem happens on my notebook, and I can not import Thetis also. It is quite confusing me. Do you have any idea of this situation?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Lawrence Mitchell <notifications@github.com>
发送时间: Thursday, June 4, 2020 11:07:18 PM
收件人: firedrakeproject/firedrake <firedrake@noreply.github.com>
抄送: Zhang, Weilin <weilin.zhang19@imperial.ac.uk>; Author <author@noreply.github.com>
主题: Re: [firedrakeproject/firedrake] ModuleNotFoundError: No module named 'Cython',/Users/zhangweilin/opt/anaconda3/bin/python: No module named flake8 (#1721)


This email from notifications@github.com originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



I am confused that you don't see UnitSquareMesh though, since I would have expected that if the import did not fail, then the function should be available.

―

**Comment by danshapero** [comment]
The `....` indicates how many tests have run, which suggests that your installation worked. The `sssss` indicates that some tests are skipped because they're for special optional features that you might not have installed, so that's nothing to worry about.

To use Firedrake from a jupyter notebook, you have to install a jupyter kernel first. If you just want to make sure that Firedrake is working, can you try:

1. activate the Firedrake virtual environment
2. `pip3 install ipython` and run `ipython`
3. from the ipython interpreter, `from firedrake import *` and then `mesh = UnitSquareMesh(10, 10)`

Hopefully this will actually work. If it does, then you can do the following to install a jupyter kernel for Firedrake:

1. activate the virtual environment
2. `pip3 install ipykernel`
3. `python3 -m ipykernel install --user --name=firedrake`

When you want to use Firedrake in a new jupyter notebook, you might have to go into the "kernel" menu and selected "firedrake" for it to work properly.

**Comment by acse-wz19** [comment]
Thanks, this is very helpful.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Daniel Shapero <notifications@github.com>
发送时间: Thursday, June 4, 2020 11:47:14 PM
收件人: firedrakeproject/firedrake <firedrake@noreply.github.com>
抄送: Zhang, Weilin <weilin.zhang19@imperial.ac.uk>; Author <author@noreply.github.com>
主题: Re: [firedrakeproject/firedrake] ModuleNotFoundError: No module named 'Cython',/Users/zhangweilin/opt/anaconda3/bin/python: No module named flake8 (#1721)


This email from notifications@github.com originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



The .... indicates how many tests have run, which suggests that your installation worked. The sssss indicates that some tests are skipped because they're for special optional features that you might not have installed, so that's nothing to worry about.

To use Firedrake from a jupyter notebook, you have to install a jupyter kernel first. If you just want to make sure that Firedrake is working, can you try:

  1.  activate the Firedrake virtual environment
  2.  pip3 install ipython and run ipython
  3.  from the ipython interpreter, from firedrake import * and then mesh = UnitSquareMesh(10, 10)

Hopefully this will actually work. If it does, then you can do the following to install a jupyter kernel for Firedrake:

  1.  activate the virtual environment
  2.  pip3 install ipykernel
  3.  python3 -m ipykernel install --user --name=firedrake

When you want to use Firedrake in a new jupyter notebook, you might have to go into the "kernel" menu and selected "firedrake" for it to work properly.

―

**Comment by danshapero** [comment]
Happy to help! Let us know if everything worked so we can close the issue.

**Comment by danshapero** [comment]
I'm closing this issue, but if it's still a problem then feel free to re-open.
