### ISSUE TITLE
Build Error --Make alltest

### ISSUE THREAD

**Issue by rado9012** [firedrakeproject/firedrake#1727]
Hello, I am having some issues installing firedrake and I would really appreciate some help. I installed firedrake following the directions [here](https://www.firedrakeproject.org/download.html). Everything seems properly installed however when I test the build by using "make alltest", I get the following error:

Building extension modules
    Linting firedrake codebase
    Linting firedrake test suite
    Linting firedrake scripts
    Running all regression tests
ImportError while loading conftest '/Users/radoslavvuchkov/firedrake/src/firedrake/tests/conftest.py'.
tests/conftest.py:8: in <module>
    from mpi4py import MPI
E   ImportError: dlopen(/Users/radoslavvuchkov/firedrake/lib/python3.7/site-packages/mpi4py/MPI.cpython-37m-darwin.so, 2): Symbol not found: _ADIOI_Datarep_head
E     Referenced from: /Users/radoslavvuchkov/firedrake/src/petsc/default/lib/libpmpi.12.dylib
E     Expected in: flat namespace
E    in /Users/radoslavvuchkov/firedrake/src/petsc/default/lib/libpmpi.12.dylib
make: *** [test] Error 4

**Comment by wence-** [comment]
Can you show the output of `otool -L /Users/radoslavvuchkov/firedrake/lib/python3.7/site-packages/mpi4py/MPI.cpython-37m-darwin.so`

and also `otool -L /Users/radoslavvuchkov/firedrake/src/petsc/default/lib/libpmpi.12.dylib`

?

**Comment by rado9012** [comment]
The outputs are as follows:
/Users/radoslavvuchkov/firedrake/lib/python3.7/site-packages/mpi4py/MPI.cpython-37m-darwin.so:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	@rpath/libmpi.40.dylib (compatibility version 61.0.0, current version 61.1.0)
	/Users/radoslavvuchkov/firedrake/src/petsc/default/lib/libpmpi.12.dylib (compatibility version 14.0.0, current version 14.8.0)


/Users/radoslavvuchkov/firedrake/src/petsc/default/lib/libpmpi.12.dylib:
	/Users/radoslavvuchkov/firedrake/src/petsc/default/lib/libpmpi.12.dylib (compatibility version 14.0.0, current version 14.8.0)
	/System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/gcc/lib/gcc/9/libgfortran.5.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
	/usr/local/lib/gcc/9/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/gcc/lib/gcc/9/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)


I guess I have to downgrade libpmpi.12.dylib from 14.8.0 to 14.0.0? Also thanks for taking the time to help me with this, I appreciate it.

**Comment by wence-** [comment]
This part

```
/Users/radoslavvuchkov/firedrake/lib/python3.7/site-packages/mpi4py/MPI.cpython-37m-darwin.so:
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
@rpath/libmpi.40.dylib (compatibility version 61.0.0, current version 61.1.0)
^^^^
```

Looks suspicious to me. For example, on my system I just have:

```
$ otool -L ../../firedrake/lib/python3.7/site-packages/mpi4py/MPI.cpython-37m-darwin.so 
../../firedrake/lib/python3.7/site-packages/mpi4py/MPI.cpython-37m-darwin.so:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
        /usr/local/opt/mpich/lib/libmpi.12.dylib (compatibility version 14.0.0, current version 14.7.0)
        /usr/local/opt/mpich/lib/libpmpi.12.dylib (compatibility version 14.0.0, current version 14.7.0)
```

Notice the lack of `@rpath/libmpi.40.dylib`.

I suspect something went wrong while building mpi4py.

Can you activate the virtual environment and show the output of:
```
mpicc -show
mpiexec --version
```

I suspect it may be possible to fix this by doing:

```
pip uninstall mpi4py
pip install --no-binary mpi4py mpi4py
```

In the activated virtualenv.

**Comment by rado9012** [comment]
Here is the out put of the commands 

(firedrake) (base) Radoslavs-MacBook-Pro-2:firedrake radoslavvuchkov$ mpicc -show
gcc -fstack-protector -fno-stack-check -Qunused-arguments -g -O3 -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/Users/radoslavvuchkov/firedrake/src/petsc/default/include -L/Users/radoslavvuchkov/firedrake/src/petsc/default/lib -lmpi -lpmpi
(firedrake) (base) Radoslavs-MacBook-Pro-2:firedrake radoslavvuchkov$ mpiexec --version
HYDRA build details:
    Version:                                 3.3.2
    Release Date:                            Tue Nov 12 21:23:16 CST 2019
    CC:                              gcc  -fstack-protector -fno-stack-check -Qunused-arguments -g -O3  
    CXX:                             g++  -fstack-protector -fno-stack-check -g -O3 -std=c++11  
    F77:                             gfortran -ffree-line-length-0 -g -O  
    F90:                             gfortran -ffree-line-length-0 -g -O  
    Configure options:                       '--disable-option-checking' '--prefix=/Users/radoslavvuchkov/firedrake/src/petsc/default' 'MAKE=/usr/bin/make' '--libdir=/Users/radoslavvuchkov/firedrake/src/petsc/default/lib' 'CC=gcc' 'CFLAGS=-fstack-protector -fno-stack-check -Qunused-arguments -g -O3 -O2' 'AR=/usr/bin/ar' 'ARFLAGS=cr' 'CXX=g++' 'CXXFLAGS=-fstack-protector -fno-stack-check -g -O3 -std=c++11 ' 'FFLAGS=-ffree-line-length-0 -g -O ' 'FC=gfortran' 'F77=gfortran' 'FCFLAGS=-ffree-line-length-0 -g -O ' '--enable-shared' '--with-device=ch3:sock' '--with-pm=hydra' '--enable-g=meminit' '--cache-file=/dev/null' '--srcdir=.' 'LDFLAGS=' 'LIBS=' 'CPPFLAGS= -I/Users/radoslavvuchkov/firedrake/src/petsc/default/externalpackages/mpich-3.3.2/src/mpl/include -I/Users/radoslavvuchkov/firedrake/src/petsc/default/externalpackages/mpich-3.3.2/src/mpl/include -I/Users/radoslavvuchkov/firedrake/src/petsc/default/externalpackages/mpich-3.3.2/src/openpa/src -I/Users/radoslavvuchkov/firedrake/src/petsc/default/externalpackages/mpich-3.3.2/src/openpa/src -D_REENTRANT -I/Users/radoslavvuchkov/firedrake/src/petsc/default/externalpackages/mpich-3.3.2/src/mpi/romio/include' 'MPLLIBNAME=mpl'
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Checkpointing libraries available:       
    Demux engines available:                 poll select

**Comment by rado9012** [comment]
I ran the
 `pip uninstall mpi4py`
`pip install --no-binary mpi4py mpi4py`

and tested the make alltest in the firedrake env and got this output

ImportError while loading conftest '/Users/radoslavvuchkov/firedrake/src/firedrake/tests/conftest.py'.
tests/conftest.py:8: in <module>
    from mpi4py import MPI
E   ImportError: dlopen(/Users/radoslavvuchkov/firedrake/lib/python3.7/site-packages/mpi4py/MPI.cpython-37m-darwin.so, 2): Symbol not found: _ADIOI_Datarep_head
E     Referenced from: /Users/radoslavvuchkov/firedrake/src/petsc/default/lib/libpmpi.12.dylib
E     Expected in: flat namespace
E    in /Users/radoslavvuchkov/firedrake/src/petsc/default/lib/libpmpi.12.dylib

**Comment by rado9012** [comment]
I decided to install it on a clean computer. No issue there, my only guess is that there was some issue with the anaconda and firedrake together. 

Anyhow, thank you for the help!
