### ISSUE TITLE
Installation exception when building petsc

### ISSUE THREAD

**Issue by erizmr** [firedrakeproject/firedrake#1742]
Hi,
I was running ```python3 firedrake-install --install thetis``` on Ubuntu and constantly run into an installation exception when the program is building Petsc.
The firedrake error log and the Petsc configure log are listed below.
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/4791615/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/4791621/configure.log)

Would someone give any suggestions?
Thanks a lot.

**Comment by danshapero** [comment]
The end of the PETSc configure log says that the installation for Exodus.II requires CMake version 3.10.0 or greater, but it looks like you have 3.5.1. There are a few things you could do to remedy this:

1. Try to get a more recent CMake through the package manager: `sudo apt-get update && sudo apt-get upgrade`
2. If you're on an older version of Ubuntu you might not be able to get a CMake that's recent enough through the package manager. In that case, you can [install CMake from source](https://cmake.org/install/).
3. You can also opt out of installing Exodus.II by installing firedrake with the arguments `python3 firedrake-install --install-thetis --minimal-petsc`. Exodus.II is used for reading certain mesh file formats which you might not even need in the first place.

**Comment by erizmr** [comment]
The problem is sorted after updating the Cmake.
Thanks a lot!

**Comment by danshapero** [comment]
Happy to help! If anything else comes up feel free to ask on the Firedrake [slack clhannel](https://firedrakeproject.org/contact.html) or raise another issue.
