### ISSUE TITLE
Macos Catalina (10.15.5) when installing petsc, exodusII installation fails

### ISSUE THREAD

**Issue by sghelichkhani** [firedrakeproject/firedrake#1746]
I wonder if this is something Macos related or not, but when trying to have a fresh installation of firedrake, installation of petsc fails. 

Attached is [configure.log](https://github.com/firedrakeproject/firedrake/files/4811475/configure.log) in firedrake/src/petsc/default/lib/petsc/conf/configure.log. 

Any idea why this occurs only on Mac?

**Comment by dham** [comment]
Those missing symbols that are causing the configure fail are from open-mpi, so for some reason part of the build chain which is being used on exodus is finding your system open-mpi, and then trying to link agains the mpich that Firedrake builds. We should probably just drop exodus from the build. Essentially nobody actually uses it. As an immediate workaround you could try passing `--minimal-petsc` to `firedrake-install`. That cuts down the PETSc external dependencies and in particular won't include exodus.

**Comment by sghelichkhani** [comment]
Seems like the issue only occurs for exodus. I just commented out adding `--download-exodusii` as an option for petsc and it worked fine. Many thanks for the help!
