### ISSUE TITLE
On creating copies of the SNES and TS solvers.

### ISSUE THREAD

**Issue by salazardetroya** [firedrakeproject/firedrake#1757]
This issue comes from the PETSc issue tracker: https://gitlab.com/petsc/petsc/-/issues/663

I am working on adding the TSAdjoint capabilities as a pyadjoint block, using Ivan's TS interface (https://github.com/IvanYashchuk/firedrake-ts). My initial plan was to make a copy of the `DAESolver` in firedrake-ts within the pyadjoint block, but I ran into the problem described in the PETSc issue.

I tried cloning the `DM` as suggested by the PETSc developers, but it crashes:
```python
In [1]: from firedrake import *

In [2]: mesh = UnitSquareMesh(10, 10)

In [3]: V = FunctionSpace(mesh, 'CG', 1)

In [4]: V.dm
Out[4]: <petsc4py.PETSc.DMShell at 0x110248770>

In [5]: V.dm.clone()
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-5-4086e1d60e13> in <module>
----> 1 V.dm.clone()

PETSc/DM.pyx in petsc4py.PETSc.DM.clone()

Error: error code 63
[0] DMClone() line 128 in /Users/salazardetro1/scicomp_libraries/firedrake-debug/firedrake/src/petsc/src/dm/interface/dm.c
[0] DMSetDimension() line 5525 in /Users/salazardetro1/scicomp_libraries/firedrake-debug/firedrake/src/petsc/src/dm/interface/dm.c
[0] PetscDSSetCoordinateDimension() line 712 in /Users/salazardetro1/scicomp_libraries/firedrake-debug/firedrake/src/petsc/src/dm/dt/interface/dtds.c
[0] Argument out of range
[0] Coordinate dimension must be non-negative, not -1
```

 So far, this has not been an issue for the `NonlinearVariationalSolver` because `SNES` objects can share `DM` with no problems. It is not the case for `TS`. For instance, the following code using `NonlinearVariationalSolver` works with no problems:

```python
from firedrake import *

mesh = UnitIntervalMesh(10)
V = FunctionSpace(mesh, "P", 1)

u = Function(V)
u_t = Function(V)
v = TestFunction(V)
F = inner(grad(u), grad(v)) * dx - 1.0 * v * dx

bc = DirichletBC(V, 0.0, "on_boundary")

x = SpatialCoordinate(mesh)
bump = conditional(lt(abs(x[0] - 0.5), 0.1), 1.0, 0.0)
u.interpolate(bump)


problem = NonlinearVariationalProblem(F, u, bcs=bc)
solver = NonlinearVariationalSolver(problem)

V2 = FunctionSpace(mesh, "P", 1)
u2 = Function(V2)
u_t2 = Function(V2)
v = TestFunction(V2)
F2 = inner(u_t2, v) * dx + inner(grad(u2), grad(v)) * dx - 1.0 * v * dx
bc2 = DirichletBC(V2, 0.0, "on_boundary")

problem2 = NonlinearVariationalProblem(F2, u2, bcs=bc)
solver2 = NonlinearVariationalSolver(problem2)

solver.solve()
```
The equivalent code in firedrake-ts is in https://github.com/IvanYashchuk/firedrake-ts/issues/4 and returns the same error than in the PETSc issue.

**Comment by wence-** [comment]
So this is quite a deep-seated issue. We use DM objects to provide information to PETSc solvers. Because we have to go back and forth between DMs and functionspaces (and not lose information) presently the DM actually lives on the PyOP2 dataset (which is long-lived) as opposed to a functionspace object (which is lightweight).

Our workaround, I am not immediately sure why it doesn't work for TS is the following. A DM lives on multiple solvers, but is only ever _used_ by one solver at a time (approximately) using a stack management system for application contexts that are pushed and popped.

To rework this, one would need to cons a new DM for each solver and manage application context transfer in a different way. I think this needs some thinking through, but it is probably worthwhile since I have rewritten this petsc-firedrake interaction code twice and it is still not perfect.

**Comment by salazardetroya** [comment]
Thanks. From your description, it sounds that `firedrake_ts` might be forgetting to add some of its data to this sharing mechanism through the stack. I will take a look closer to it.

**Comment by salazardetroya** [comment]
I found what the problem is with the `TS` object. The `DM` has a `DMSNES` object which holds a reference to the implicit part of the residual function with `DMSNESSetFunction`. In the case of `TS` and for the `TSType` theta, this function is `SNESTSFormFunction_Theta`. This function has as last argument the `TS`, which the `SNES` sees as a `void * ctx`. 

Now, because the `DM` is shared, so is the `DMSNES`. When we create a second `TS` and assign the residual evaluation function, the `DMSNES` reference gets overwritten and now the `void * ctx` points to the new `TS`. When we call the first `solver.solve()`, the first `TS` is not in the `DMSNES` anymore.

This was more clear when I created a `DAESolver` (contains a TS) from `firedrake_ts` and then a `NonlinearVariationalSolver` (contains a SNES). The second one also shares the `DMSNES` with the `TS` and when we create it, it calls `DMSNESSetFunction` to add its own residual function, getting rid of the `TS`'s. This is not a problem when using different `NonlinearVariationalSolver` because they all shared the same residual evaluation function and only differ in the `appctx` which is pushed and popped accordingly by firedrake.

For now I have solved the problem by setting the residual evaluation when I call `solver.solve()`

By the way, I have found VSCode debugging tools very useful to debug python+C. You can run the python debugger, attach a lldb/gdb to it and debug line by line in the IDE. 100% recommended.

**Comment by wence-** [comment]
Thanks, this makes sense. I suspect it should still be the case that these DMs are created (and their children) for each new solver (to avoid this kind of cross-contamination). However, I have not thought through all the consequences.
