### ISSUE TITLE
Fingerprint issue

### ISSUE THREAD

**Issue by Mark-Pinto** [firedrakeproject/firedrake#1761]
Hello,

I am trying to install Firedrake on my laptop running Windows 10. I have installed WSL 1 and Ubuntu 20.04. I first updated Ubuntu using the commands you suggested. When I tried to install Firedrake the installation process paused at one stage with the following message:

The authenticity of host 'github.com (140.82.118.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])?

**Comment by dham** [comment]
That very much looks like your network had issues at that point.
