### ISSUE TITLE
firedrake-install should offer a "cleanup build artifacts" mode

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#1771]
The full-fat firedrake installation is large (multi GB). A significant portion of this is build artifacts in PETSc. We should provide an option to run an install that cleans these up after finishing. Would be useful for reducing the size of docker images, and also typical install modes on supercomputers.

The other reason is that the number of files is very large (which sometimes runs into inode/quota limits on shared systems).

**Comment by JDBetteridge** [comment]
This was fixed by #1786
