### ISSUE TITLE
VTK installation fails when using firedrake installation script.

### ISSUE THREAD

**Issue by jfregin** [firedrakeproject/firedrake#1799]
Hi,

I'm trying to get firedrake running with OSX 10.13.6. I followed the installation instructions here: [https://www.firedrakeproject.org/download.html](url)
However, during the installation process the script calls pip to install "vtk-8.1.2-cp38-cp38-macosx_10_14_x86_64.whl" which is not supported on my platform (apparently 10.14 is the minimum requirement). Is there a possibility to resolve my problem?

Any help is appreciated. Thank you very much,
Joscha

Installation Log: [firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/5016740/firedrake-install.log)

**Comment by dham** [comment]
@JDBetteridge I think this should work if @jfregin builds himself a vtk wheel for MacOS 10.13. Can you point him at the instructions to do so?

**Comment by JDBetteridge** [comment]
So building the wheel on Mac isn't straightforward as we ended up having to patch the source code to get it to work.

A short term workaround would be to use the following Firedrake branch:
https://github.com/firedrakeproject/firedrake/tree/remove-build-files

This is a better solution as we will soon be able to use the VTK9 wheels dropping our prebuild ones and it avoids the involved process of making your own wheel. I still need to double check that the newer VTK isn't breaking higher order output, but I can take a look for tomorrow.

**Comment by dham** [comment]
To do that you would grab that branch's version of the install script:
```
curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/remove-build-files/scripts/firedrake-install
```
... and also tell Firedrake to install that branch:
```
python3 firedrake-install --package-branch firedrake remove-build-files
```
Once that branch lands (which is imminent, quite possibly tomorrow) you can switch back to master:
```
cd firedrake/src/firedrake
git checkout master
firedrake-update
```

**Comment by jfregin** [comment]
Thank you for the helpful comments. I managed to install firedrake with the above instructions.

The firedrake project webpage suggests to run `make alltest` within firedrake/src/firedrake. This results in an error (error 147) which is already issued here: #1784

Thanks again,
Joscha
