### ISSUE TITLE
MPI Issues on macOS

### ISSUE THREAD

**Issue by edaub** [firedrakeproject/firedrake#1803]
I just did a fresh Firedrake install on macOS Catalina using the provided install script. My installation works fine on a single processor, but I am having issues running multiple processes where the scripts hang and never run to completion.

I have confirmed that the `mpi4py` installation is fine -- in the venv, I can run the following under multiple processes no problem:

```
from mpi4py.MPI import COMM_WORLD
print(COMM_WORLD.rank)
```

However, the Firedrake equivalent hangs with two or more processes:

```
from firedrake import COMM_WORLD
print(COMM_WORLD.rank)
```

Any idea what could be causing this? Log file from installation is attached.
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/5076556/firedrake-install.log)

**Comment by edaub** [comment]
**Update:** Seems to be a PETSc issue, as I can't run the equivalent with `PETSc.COMM_WORLD` on two processes. Investigating the PETSc build.

**Comment by wence-** [comment]
Our probable guess at the moment for these problems is that the numpy wheels ship with a version of libgfortran that is ABI-incompatible with the one you get in homebrew. @JDBetteridge is working on this. Perhaps he can describe if there is currently a workaround.
