### ISSUE TITLE
Firedrake creates wrong meshes when saving NCF functions to PVD in parallel

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#1807]
Consider the code

```
from firedrake import *
N = 4
base = RectangleMesh(N, N, 1, 1, quadrilateral=True)
basemh = MeshHierarchy(base, 0)
mh = ExtrudedMeshHierarchy(basemh, 1, base_layer=N)
mesh = mh[-1]

File("mesh.pvd").write(mesh)
V = FunctionSpace(mesh, "NCF", 2)
File("fun.pvd").write(Function(V))
```

This should make a regular mesh of a box, but when I run it in parallel (on two cores), it gives a warped mesh in paraview:

![ncf2](https://user-images.githubusercontent.com/3494657/90508324-73d18b80-e14f-11ea-8e5d-bf2d1e7cbbca.png)

The output looks correct in serial.

**Comment by wence-** [comment]
WFM, using paraview 5.8.0.

**Comment by pefarrell** [comment]
I just checked with paraview 5.8.1 and it still happens.

**Comment by pefarrell** [comment]
Here are the files it produces. Can you check what they look like for you?


[fun.tar.gz](https://github.com/firedrakeproject/firedrake/files/5094662/fun.tar.gz)

**Comment by wence-** [comment]
OK, that is bad like yours.

**Comment by wence-** [comment]
Ah, I had an older firedrake with vtk-8.1.2. With the updated vtk, things break. Which suggests to me that the paraview reordering is changed, broken, something. FWIW, I also get bad output in serial.

With vtk-9, permutation map is:
```
[0, 9, 12, 3, 1, 10, 13, 4, 18, 15, 21, 6, 19, 16, 22, 7, 2, 11, 14, 5, 8, 17, 20, 23, 24, 25, 26]
```
With vtk 8
```
[0, 9, 12, 3, 1, 10, 13, 4, 18, 15, 21, 6, 19, 16, 22, 7, 2, 11, 5, 14, 8, 17, 20, 23, 24, 25, 26]
```

Note that 14 and 5 are flipped.

**Comment by wence-** [comment]
Hexes changed ordering in https://github.com/Kitware/VTK/commit/7a0b92864c96680b1f42ee84920df556fc6ebaa3

There's some way of advertising this in the vtk file, but I do not understand it. Perhaps we should move to using the vtk Python interface for writing these files?

**Comment by pefarrell** [comment]
I looked at the release notes for 9.0.0 but couldn't find anything about it. And there's no blog post or release notes that I could find for 9.0.1. Strange that they changed this without making a song and dance about it.

Any ideas for a quick & ugly workaround until this is fixed?

**Comment by wraith1995** [comment]
Looking at the pull and the discussion here, maybe grab the function "NodeNumberingMappingFromVTK8To9" from the appropriate part of VTK, invert it in the paraview reordering file, and then apply that inverse in the generation of the vtk file? If I am reading this correctly, Paraview is using the VTK 8 ordering, but we are producing the VTK 9 ordering? If so, then applying the inverse of NodeNumberingMappingFromVTK8To9 might work.

**Comment by wraith1995** [comment]
On my machine in serial I have the same results as above. [Here is a fix](https://gist.github.com/wraith1995/6f5873f788d595e5dcfe5692357585f8) that works for me. Tell me if it works.

**Comment by pefarrell** [comment]
Hi @wraith1995 . That patch works for me. Could you please make a pull request? Thanks!

**Comment by wraith1995** [comment]
@pefarrell Done. See #1832. 

The need for this (and other issues we ran into when we introduced this feature) might indicate a need for something better. Maybe a [plugin](https://www.paraview.org/Wiki/ParaView/Plugin_HowTo) could be made? I am not sure that would be a better way, but it did occur to me once to look into it.
