### ISSUE TITLE
Installation Error on Mac Catalina

### ISSUE THREAD

**Issue by adiegel** [firedrakeproject/firedrake#1813]
I am attempting to install Firedrake on an iMac running Catalina Version 10.15.6. I was previously able to install Firedrake on a Mac laptop also running Catalina using the commands:

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
/usr/local/bin/python3 firedrake-install

These came from a previous help ticket #1703. However, when using the same strategy on the iMac, it fails. I am attaching the installation log here. Any help would be greatly appreciated!
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/5098766/firedrake-install.log)

**Comment by wence-** [comment]
I think this is because the relevant package in PETSc (Chaco) is written in pre-ansi C, and the C compiler on catalina has somehow become stricter. We will try and reproduce standalone and ship a bug report upstream.

**Comment by adiegel** [comment]
Thank you!

**Comment by OsKnoth** [comment]
Is this issue now solved?

**Comment by wence-** [comment]
I think not yet sorry.

**Comment by adiegel** [comment]
No. I'm still hoping someone else can reproduce this issue. I've tried a few other things to get Firedrake working on this machine, but to no avail.

**Comment by JDBetteridge** [comment]
I have managed to reproduce this error in my quest to fix the numpy bug, I will report back if I stumble across a fix

**Comment by JDBetteridge** [comment]
For anyone still experiencing the issue, could you try:
`export PETSC_CONFIGURE_OPTIONS="--COPTFLAGS='-g -O3 -Wno-implicit-function-declaration'"`
before running `firedrake-install` to see if this workaround allows you to install Firedrake (or at least get past the issue installing Chaco)

**Comment by wence-** [comment]
See also https://gitlab.com/petsc/petsc/-/merge_requests/3202 (when this merges I will update our petsc)

**Comment by adiegel** [comment]
Thanks everyone! This seems to have worked. The install says it was successful but I have yet to run any tests. Thanks again!
