### ISSUE TITLE
Initial conditions using mixed function spaces

### ISSUE THREAD

**Issue by jfregin** [firedrakeproject/firedrake#1819]
Hello,

I am trying to solve a simple coupled system of PDE's on a periodic domain involving two prognostic variables u(t,x) and p(t,x). The initial conditions are u(0,x) = 0 and p(0,x) = f(x). The documentation tells me to use [mixed function spaces](https://www.firedrakeproject.org/variational-problems.html#mixed-function-spaces). However, when trying to apply initial conditions to the following setup
<pre><code>mesh = PeriodicIntervalMesh(n,1) 
x = SpatialCoordinate(mesh)[0]  
Q = FunctionSpace(mesh,'Lagrange',2)
V = Q*Q
</code></pre>
I receive errors, depending on the way I set the initial conditions. My first approach was to do the following
<pre><code>u_n, p_n = Function(V)
p_init = f(x)
p_n.interpolate(p_init)
</code></pre>
This yields `'Indexed' object has no attribute 'interpolate'`. Note f(x) is just short for some longer expression.

So i tried to define a vector containing the initial conditions (2 versions) and then splitting the vector to access its components.  Version 1:
<pre><code>U_n = Function(V)
U_init = as_vector([0,f(x)])
U_n.interpolate(U_init)
</code></pre>
This raises the error `UFL expressions for mixed functions are not yet supported.`.
Similarly with Version 2:
<pre><code>class InitialConditions(Expression):
    def eval(self, values, x):
        values[0] = 0
        values[1] = f(x)
        
    def value_shape(self):
        return (2,)

U_init = InitialConditions()
U_n = Function(V)
U_n.interpolate(U_init)
</code></pre>
This raises the error `Python expressions for mixed functions are not yet supported.`. I notice that it says 'not yet supported' so I am aware that this is not a bug. However, is there a way to still apply initial conditions (to indexed objects)? 

Any help is appreciated. Thank you very much,
Joscha

**Comment by wence-** [comment]
Hi Joscha,

please use (for the purposes of setting the initial conditions)

```python
U_n = Function(V)
u_n, p_n = U_n.split()
p_n.interpolate(p_init)
# You can also just write:
U_n.sub(1).interpolate(p_init)
```

**WARNING**

If you want to use the separate expressions for `u_n` and `p_n` in a subsequent form, you should do:

```python
u_n, p_n = split(U_n) # Note free function, not method call.
```

This was done implicitly when you did

```python
u_n, p_n = Function(V)
```

**Comment by jfregin** [comment]
Thank you so much for the helpful response, works like a charm.
