### ISSUE TITLE
Install fails to clone libsupermesh

### ISSUE THREAD

**Issue by Ainlina** [firedrakeproject/firedrake#1827]
firedrake-install fails while trying to clone libsupermesh, when running with ssh disabled. May be an issue with the libsupermesh hosting rather than a Firedrake problem. Arises under Xubuntu 20.04.1.

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/5145242/firedrake-install.log)

**Comment by wence-** [comment]
Sorry for the delayed response. That certainly looks like a network issue. You got far enough into the installation that you could activate the venv and run `firedrake-update` to resume the installation (and hopefully build libsupermesh).
