### ISSUE TITLE
Install-script error while installing without package manager and prebuilt petsc

### ISSUE THREAD

**Issue by jfregin** [firedrakeproject/firedrake#1831]
Hi all,

I'm trying to get firedrake running with openSUSE. Since I can not rely on a package manager I tried to preinstall every necessary package as instructed on the firedrakeproject webpage ([here](https://www.firedrakeproject.org/download.html)). Running the install script with 

`python3 firedrake-install --no-package-manager --disable-ssh --honour-petsc-dir --mpicc MPICC --mpicxx MPICXX --mpif90 MPIF90 --mpiexec MPIEXEC`

yields the following output:
```
Creating firedrake venv in '/prog/firedrake'. 
Traceback (most recent call last):
  File "firedrake-install", line 1341, in <module>
    f.write('#!/bin/bash' + os.linesep + src + ' "$@"')
TypeError: must be str, not NoneType
```

Can anyone help with this error? If I'm not mistaken line 1328 of the install script `name=options[opt]` name is assigned to a NonType object.
Below is the log file if needed.
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/5162698/firedrake-install.log)

Any help is much appreciated. Kind regards,

Joscha

**Comment by wence-** [comment]
> `python3 firedrake-install --no-package-manager --disable-ssh --honour-petsc-dir --mpicc MPICC --mpicxx MPICXX --mpif90 MPIF90 --mpiexec MPIEXEC`

Generally these executables are spelt in lowercase (e.g. `mpicc`). What is happening is that we're attempting to locate the full path to the executable you provided (by running `which MPICC` say). But this is returning `None` which we should catch.

I think that if you do `--mpicc mpicc --mpicxx mpicxx` etc... then the install should work.

But we should also provide a clearer error message.

**Comment by jfregin** [comment]
Thank you, I was previously running the help command, which instructed me to use the upper case letters. Error is gone now :).

**Comment by wence-** [comment]
> Thank you, I was previously running the help command, which instructed me to use the upper case letters.

Are this is standard help output convention indicating that the flag takes an argument.

**Comment by jfregin** [comment]
Thanks again, I did not know about the help output convention.
