### ISSUE TITLE
Firedrake running problems

### ISSUE THREAD

**Issue by cammbyrne** [firedrakeproject/firedrake#1837]
I am a student in Software engineering running Firedrake for a research project. I am running it on a Dell windows laptop using Ubuntu 20.04 LTS. The instillation seemed to have worked fine but when i try to run the poisson demo, it says that it cannot find the Firedrake module. I am in the virtual environment and the code i am running is in the firedrake folder. If someone could please help me get this running. Im including my install log and screenshots of the errors appearing
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/5197916/firedrake-install.log)

![image](https://user-images.githubusercontent.com/71042713/92654229-2ad7a780-f2b5-11ea-8fbb-3736e3b47d03.png)

**Comment by wence-** [comment]
This installation looks like it did not succeed. The end of the log says:
```
TESTING: checkCCompiler from config.setCompilers(/home/cammbyrne/firedrake/src/petsc/config/BuildSystem/config/setCompilers.py:635)
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
Could not locate a functional C compiler
*******************************************************************************


2020-09-09 11:59:47,861 DEBUG  Popping path '/home/cammbyrne/firedrake/src/petsc'
2020-09-09 11:59:47,861 DEBUG  New path '/home/cammbyrne/firedrake/src'
2020-09-09 11:59:48,083 INFO   
```

Can you upload the file `/home/cammbyrne/firedrake/src/petsc/configure.log` ?

**Comment by cammbyrne** [comment]
[configure.log](https://github.com/firedrakeproject/firedrake/files/5197966/configure.log)
here you go!

**Comment by wence-** [comment]
Oh sorry, that somehow only uploaded the symlink, can you try `/home/cammbyrne/firedrake/src/petsc/default/lib/petsc/conf/configure.log` ?

**Comment by cammbyrne** [comment]
[configure.log](https://github.com/firedrakeproject/firedrake/files/5212947/configure.log)
Here you go!
sorry about the wait!

**Comment by wence-** [comment]
Ah, sorry, I should have read the original log more carefully.

It printed:

```
2020-09-09 11:50:02,624 INFO   Installing missing packages: build-essential, autoconf, automake, bison, flex, cmake, gfortran, libblas-dev, liblapack-dev, libtool, python3-dev, python3-pip, python3-tk, zlib1g-dev, libboost-dev.
2020-09-09 11:50:08,731 INFO   apt-get not found or disabled. Proceeding on the rash assumption that your compiled dependencies are in place.
2020-09-09 11:50:08,732 INFO   Please use the --show-dependencies for more information.
```

So we were unable to provide the relevant build dependencies, so the PETSc build failed because there was no C compiler.

Are you running Ubuntu in WSL? Do you have the permissions to install packages with `apt`?

**Comment by wence-** [comment]
Did you make any progress here, or give up?

**Comment by cammbyrne** [comment]
Apologies. Yes i gave up. We decided to do something different. Thank you so much
