### ISSUE TITLE
Installation failure during petsc

### ISSUE THREAD

**Issue by xiaodizhang29** [firedrakeproject/firedrake#1846]
Hello, I am trying to install Firedrake on Ubuntu. It failed while installing PETSC. It says,
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/5243648/firedrake-install.log)

===============================================================================
                              Running make on HDF5; this may take several minutes
                        ===============================================================================
                      
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
Error running make; make install on HDF5
*******************************************************************************
Could you help me to solve this problem?

[configure.log](https://github.com/firedrakeproject/firedrake/files/5243647/configure.log)

**Comment by stephankramer** [comment]
> H5Tconv.c:9317:1: fatal error: error writing to /tmp/ccfT2I79.s: No space left on device

It looks like your /tmp/ directory is full

**Comment by xiaodizhang29** [comment]
Tank you very much~

**Comment by xiaodizhang29** [comment]
> > H5Tconv.c:9317:1: fatal error: error writing to /tmp/ccfT2I79.s: No space left on device
> 
> It looks like your /tmp/ directory is full
