### ISSUE TITLE
AttributeError: 'Interpolator' object has no attribute 'frozen_assembled_interpolator'

### ISSUE THREAD

**Issue by xiaodizhang29** [firedrakeproject/firedrake#1848]
Hello! I am running Firedrake for a research project. The instillation seemed to have worked fine but when i try to run the helmholtz demo, it failed.
![image](https://user-images.githubusercontent.com/43510798/93660130-65440000-fa7e-11ea-9807-5c3050bf2e2a.png)

If someone could please help me get this running.

**Comment by wence-** [comment]
Can you show the rest of the backtrace?

**Comment by xiaodizhang29** [comment]
![image](https://user-images.githubusercontent.com/43510798/93766895-be13c400-fc49-11ea-92b0-fe9946a1dbd1.png)
Thank you for your help~

**Comment by xiaodizhang29** [comment]
Maybe I don't have the authorization?

**Comment by wence-** [comment]
Yes, it looks like it. Although if you installed firedrake yourself as the current user in that directory I do not immediately see how this might have occurred. Can you show permissions for `/mnt/firedrake/`? `ls -al /mnt/firedrake/`

And also the output of `whoami` and `groups`?

**Comment by xiaodizhang29** [comment]
![image](https://user-images.githubusercontent.com/43510798/93769769-e1407280-fc4d-11ea-90af-da80ca9cdbdf.png)
Yes, how shall I deal with this? Make me the root ?

**Comment by wence-** [comment]
Our general recommendation is that you install firedrake as a user (rather than centrally), since then you can update it easily. If you can't do that (as done here) then you can set the environment variables `FIREDRAKE_TSFC_KERNEL_CACHE_DIR` and `PYOP2_CACHE_DIR`.

For example

```
export PYOP2_CACHE_DIR=/tmp/pyop2-cache/
export FIREDRAKE_TSFC_KERNEL_CACHE_DIR=/tmp/firedrake-kernel-cache/
```

If other people use the system you should put a unique name in these directories (e.g. using your uid).

**Comment by xiaodizhang29** [comment]
Thanks a lot!

**Comment by wence-** [comment]
OK, I will close this issue. Please raise new ones if you have any further problems.
