### ISSUE TITLE
Translation of matrix-free solve gem node

### ISSUE THREAD

**Issue by sv2518** [firedrakeproject/firedrake#1865]
Hi, I am trying to set up local matrixfree infrastructure in Firedrake. The idea is to have a matfree solve node in Slate, then translate to a gem matfree solve node. Now I am wondering what the right way of translating the gem node is.

**Version A)**  I translate the gem node into a loopy call ala `x[:] = matfree_solve(A[:], b[:]))`.

Then I need to generate and attach a loopy kernel for the Call somewhere. I am thinking it could just go into slates loopy kernel generation here https://github.com/firedrakeproject/firedrake/blob/fecd3830a0e3ebfe78a7a6963eede9eab33e2d3e/firedrake/slate/slac/compiler.py#L162
And we would do something like the following there, where _generate_matfree_solve_kernel() would give back a kernel for the matrixfree solve written in loopy.
```
    # register loopy kernel for matrix-free solve call
    matfree_solve_loopy = _generate_matfree_solve_kernel()
    prg = register_callable_kernel(loopy_merged, matfree_solve_loopy)
    prg = inline_callable_kernel(loopy_merged,  matfree_solve_loopy.name)
```
The disadvantage of that is that I need to re-search for the instruction that contains the call in order to infer the iname domains. (Because I need to get some shape information from somewhere, maybe there is an alternative to my approach here.)

**Version B)** Another way would be a straight translation of the gem.solve node into the instructions for the matfree solve. The advantage there is that the shape is just available from the gem Solve node. But it would mean we would have a _generate_matfree_solve_kernel() in tsfc.tsfc.loopy and I am not sure if that really belongs in there. Maybe my concern about that is for no reason actually.

I thought I'd just ask for opinions.

**Comment by wence-** [comment]
Sorry for the delayed response.

I think that it makes sense to go for version B, since one may well wish to do some transforms in gem before going to loopy.
