### ISSUE TITLE
Running Firedrake through Docker

### ISSUE THREAD

**Issue by adiegel** [firedrakeproject/firedrake#1868]
I have a student using a machine running Windows 10. We were attempting to run Firedrake through the Docker image but we have been unsuccessful. I notice that the FEniCS project has the following instructions:

you can start a container with the following docker command:
docker run -ti -p 127.0.0.1:8000:8000 -v $(pwd):/home/fenics/shared -w /home/fenics/shared quay.io/fenicsproject/stable:current

Is there a similar command for firedrake?

Thanks.

**Comment by danshapero** [comment]
Can you say more about what part of running Firedrake through Docker was unsuccessful?

A similar command for Firedrake with fewer bells and whistles would be

    docker run --interactive --tty firedrakeproject/firedrake:latest

That'll fetch the Docker image, start up a container, and drop you into a terminal in that container. If that works, you can then do

    source firedrake/bin/activate

from inside the container. You should be able to, say, run `ipython3`, import Firedrake, and then play around with it in the interpreter.

That FEniCS command does two extra things: sync some directories between the container and the host system, and forward ports so that you can run a Jupyter notebook server. If you need help with those we can get to that, I just want to make sure the basic stuff works for you first.

**Comment by adiegel** [comment]
Thank you, @danshapero. I have asked my student to try your suggestion. I will let you know if this does not work or I will close the ticket if it does.

Thanks again!

**Comment by adiegel** [comment]
Hi @danshapero,

My student says that did not work for him. I am going to ask him to get on this help board and see if we can get this worked out. Thanks for your efforts.

**Comment by cammbyrne** [comment]
Hi @danshapero, I am the student that Dr. Diegel is refering to. I tried many things for Docker and all of them fail saying the Docker Daemon is not running. I have looked into it and tried ways to make it run but none seem to work

**Comment by danshapero** [comment]
Gotcha, so Docker has to start up a program called a daemon that runs in the background. It sounds like you have Docker installed but this daemon isn't running yet for whatever reason. What have you tried to make it run? I don't have a windows machine to test on but I found [a guide](https://success.mirantis.com/article/docker-for-windows-fails-with-a-daemon-not-running-message) and [a more detailed guide](https://www.thecodebuzz.com/docker-error-daemon-is-not-running/) with some proposed solutions.

**Comment by cammbyrne** [comment]
I tried the first guide awhile ago and again just now and that doesnt work. First i wanted to make sure im executing commands in the correct spot. Am i to do it in the Docker cli for the image or powershell or command terminal? Im still not 100% sure

**Comment by danshapero** [comment]
Ok I've managed to procure a windows machine! I installed Docker for Windows, then started up a program called "Docker Desktop". If you're able to run this program, that should start the Docker daemon.

After that, I ran this command in powershell:

    docker run --interactive --tty firedrakeproject/firedrake:latest

which downloaded the image and fired up a container running it. Let me know if these two steps work and we can go from there.

**Comment by cammbyrne** [comment]
Hey Daniel. Thank you so much for all the help. We have decided that since it is nearing the end of the semester we gave up on the computational side of the project. If we decide to continue it we will probably have more questions but for now we are okay. Thank you so much again

**Comment by adiegel** [comment]
Thanks for all the help.!
