### ISSUE TITLE
Alter Linear Form Vector

### ISSUE THREAD

**Issue by adiegel** [firedrakeproject/firedrake#1880]
Hi All, 

I would like to have the ability to alter specific entries to a right hand side linear form vector (say from a source term). I found a way to alter the diagonals of my mass matrix by following an example previously posted to this forum. The successful code is shown below:

Mass = assemble(inner(c,z)*dx)
diagonal = Mass.petscmat.getDiagonal()
vals = diagonal.array

DA_mark_array = []
for k in range(0, len(vals)-2):
    if k % 2:
        DA_mark_array.append(k)

vals[DA_mark_array] = (2/(eps**2))*vals[DA_mark_array]
Mass.petscmat.setDiagonal(diagonal, PETSc.InsertMode.INSERT_VALUES)

Going off this example, I thought that perhaps something like 
source = assemble(inner(f,z)*dx)
entries = source.petscvec.getValue()
...

would work. However, I keep running into the error

AttributeError: 'CoordinatelessFunction' object has no attribute 'petscvec'

Any help here would be greatly appreciated!

**Comment by wence-** [comment]
Hi, sorry for the delay.

You can directly access (in local numbering) the backing array for a `Function` using 
```
# For read-write access
source.dat.data[i] = some_value
# For read-only access
some_value = source.dat.data_ro[i]
```

If you want to deal with petsc objects

```
# also supports source.dat.vec (RW) and source.dat.vec_wo (write-only)
with source.dat.vec_ro as v:
   v.petscMethod
```

Is that what you need?

**Comment by adiegel** [comment]
Hi @wence- ,

Yes! I think the first option you suggested worked. Thanks so much!
