### ISSUE TITLE
The preconditioner "firedrake.HypreAMS"

### ISSUE THREAD

**Issue by xiaodizhang29** [firedrakeproject/firedrake#1881]
Dear Firedrake Developers,

I am currently using the firedrake.HypreAMS, which has been discussed in [Feature hypre ams #1854](https://github.com/firedrakeproject/firedrake/pull/1854) .

But when I run the code

----------------------------------------------------------------
```
import numpy
from firedrake import *
import hypre_ams

def test_homogeneous_field_linear():

    mesh = UnitCubeMesh(5, 5, 5)
    V = FunctionSpace(mesh, "N1curl", 1)
    V0 = VectorFunctionSpace(mesh, "DG", 0)

    u = TrialFunction(V)
    v = TestFunction(V)

    a = inner(curl(u), curl(v))*dx
    L = inner(Constant((0., 0., 0.)), v)*dx

    x, y, z = SpatialCoordinate(mesh)
    B0 = 1
    constant_field = as_vector([-0.5*B0*(y - 0.5), 0.5*B0*(x - 0.5), 0])

    bc = DirichletBC(V, constant_field, (1, 2, 3, 4))

    params = {'snes_type': 'ksponly',
              'ksp_type': 'cg',
              'ksp_itmax': '30',
              'ksp_rtol': '1e-15',
              'ksp_atol': '1e-15',
              'pc_type': 'python',
              'pc_python_type': 'firedrake.HypreAMS',
              'pc_hypre_ams_zero_beta_poisson': True,
              }

    A = Function(V)
    solve(a == L, A, bc, solver_parameters=params)
    B = project(curl(A), V0)
    assert numpy.allclose(B.dat.data_ro, numpy.array((0., 0., 1.)), atol=1e-6)

test_homogeneous_field_linear()
```
----------------------------------------------------------------

I get the following error

![image](https://user-images.githubusercontent.com/43510798/96361157-ecf05d80-1155-11eb-9d7c-363cc12859b4.png)

Any help would be greatly appreciated. Thank you.

best wishes

**Comment by wence-** [comment]
Can you please add

```
from firedrake.petsc import PETSc
PETSc.Sys.popErrorHandler()
```

to the top of your script and run again? This will hopefully give a more helpful error message.

BTW, you can copy text from the ubuntu terminal by selecting it with the mouse and using Control-Shift-C (rather than having to take a screenshot).

**Comment by xiaodizhang29** [comment]
Thank you for the answer and hints. The reason is that this pc module (firedrake.HypreAMS) has no import. Now it can run.

**Comment by xiaodizhang29** [comment]
I try to implementate the **ADS** solver according to the AMS solver. But it requires the "Coordinates". When I provieded coordinates rather than the "EdgeConstantVectors", the solver is performing very poorly. 

Replace the following code 
----------------------------------------------------------
        # Build constants basis for the Nedelec space
        cvecs = []
        for i in range(mesh.cell_dimension()):
            direction = [1.0 if i == j else 0.0 for j in range(mesh.cell_dimension())]
            c = project(Constant(direction), V)
            with c.vector().dat.vec_ro as cvec:
                cvecs.append(cvec)
        pc.setHYPRESetEdgeConstantVectors(*cvecs)
------------------------------------------------------------
with 
-----------------------------------------------------------
        pc.setCoordinates(np.reshape(mesh._topology_dm.getCoordinates().getArray(),(-1,mesh.geometric_dimension())))
-----------------------------------------------------------
The former gvies

------------------------------------------
Ndofs = 98, iterations = 4, converged reason = CONVERGED_ATOL
Ndofs = 604, iterations = 5, converged reason = CONVERGED_ATOL
Ndofs = 4184, iterations = 6, converged reason = CONVERGED_ATOL
Ndofs = 31024, iterations = 6, converged reason = CONVERGED_RTOL
------------------------------------------

After changing, the solver gets worse.

------------------------------------------
Ndofs = 98, iterations = 7, converged reason = CONVERGED_ATOL
Ndofs = 604, iterations = 13, converged reason = CONVERGED_ATOL
Ndofs = 4184, iterations = 25, converged reason = CONVERGED_ATOL
Ndofs = 31024, iterations = 49, converged reason = CONVERGED_ATOL
------------------------------------------

Any help would be greatly appreciated. Thank you.

**Comment by wence-** [comment]
Can you show your complete implementation of the ADS setup?

**Comment by xiaodizhang29** [comment]
I'm sorry I didn't make myself clear. This replace is still for AMS solver. And my purpose here is to test the "Coordinates" input.

**Comment by florian98765** [comment]
Dear xiaodizhang29,
I noticed that same behaviour. That's why I started using the `EdgeConstantVectors`. Another option would be to use `HYPRE_AMSSetInterpolations` directly. This would also allow higher order elements, but unfortunately the corresponding `petsc4py`wrapper is currently missing. 

If I understand correctly `Interpolator(P1, V)` should give the desired Interplation Pi.
best wishes
Florian

**Comment by florian98765** [comment]
@xiaodizhang29 could you provide the test code, that you used? I would try to write a small unit test in order to assure proper convergence. Is it the code shown above, or did you use something else?

**Comment by xiaodizhang29** [comment]
Thanks a lot! Here you are! The main code is

------------------------------------------------------------
import numpy
from firedrake import *
from hypre_ams import*
from firedrake.solving_utils import KSPReasons
from firedrake.petsc import PETSc
PETSc.Sys.popErrorHandler()

for n in [1,2,3,4]:
    mesh = UnitCubeMesh(2 ** n, 2 ** n, 2 ** n)
    V = FunctionSpace(mesh, "N1curl", 1)
    V0 = VectorFunctionSpace(mesh, "DG", 0)

    u = TrialFunction(V)
    v = TestFunction(V)

    a = inner(curl(u), curl(v))*dx
    L = inner(Constant((0., 0., 0.)), v)*dx

    x, y, z = SpatialCoordinate(mesh)
    B0 = 1
    constant_field = as_vector([-0.5*B0*(y - 0.5), 0.5*B0*(x - 0.5), 0])

    bc = DirichletBC(V, constant_field, (1, 2, 3, 4))

    alpha = 1.0
    beta = 0.0
    appctx = {"alpha": alpha, "beta": beta}
    params = {'ksp_type': 'cg',
              'ksp_itmax': '30',
              'ksp_rtol': '1e-8',
              'ksp_atol': '1e-8',
              #"ksp_monitor_true_residual": None,
              'pc_type': 'python',
              'pc_python_type': 'hypre_ams.HypreAMS',
              'pc_hypre_ams_zero_beta_poisson': True,
              #'ksp_monitor ': None,
              #'ksp_view ': None,
              }

    A = Function(V)
    problem = LinearVariationalProblem(a, L, A, bcs=bc)
    solver = LinearVariationalSolver(problem, solver_parameters=params,appctx=appctx)
    solver.solve()
    print("Ndofs = {}, iterations = {}, converged reason = {}".format(
        V.dim(), solver.snes.ksp.getIterationNumber(), 
        KSPReasons[solver.snes.ksp.getConvergedReason()]))
------------------------------------------------------------

And the subfunction is 

------------------------------------------------------------
from firedrake.preconditioners.base import PCBase
from firedrake.petsc import PETSc
from firedrake.functionspace import FunctionSpace
from firedrake.constant import Constant
from firedrake.ufl_expr import TestFunction
from firedrake.function import Function
from firedrake.interpolation import Interpolator
from firedrake.projection import project
from firedrake.dmhooks import get_function_space
from ufl import grad
import numpy as np


__all__ = ("HypreAMS",)


class HypreAMS(PCBase):
    def initialize(self, obj):
        A, P = obj.getOperators()
        prefix = obj.getOptionsPrefix()
        V = get_function_space(obj.getDM())
        mesh = V.mesh()

        family = str(V.ufl_element().family())
        degree = V.ufl_element().degree()
        if family != 'Nedelec 1st kind H(curl)' or degree != 1:
            raise ValueError("Hypre AMS requires lowest order Nedelec elements! (not %s of degree %d)" % (family, degree))

        P1 = FunctionSpace(mesh, "Lagrange", 1)
        G = Interpolator(grad(TestFunction(P1)), V).callable().handle

        pc = PETSc.PC().create(comm=obj.comm)
        pc.incrementTabLevel(1, parent=obj)
        pc.setOptionsPrefix(prefix + "hypre_ams_")
        pc.setOperators(A, P)

        pc.setType('hypre')
        pc.setHYPREType('ams')
        pc.setHYPREDiscreteGradient(G)
        zero_beta = PETSc.Options(prefix).getBool("pc_hypre_ams_zero_beta_poisson", default=False)
        if zero_beta:
            pc.setHYPRESetBetaPoissonMatrix(None)
        
        pc.setCoordinates(np.reshape(mesh._topology_dm.getCoordinates().getArray(),(-1,mesh.geometric_dimension())))
        
        '''
        # Build constants basis for the Nedelec space
        cvecs = []
        for i in range(mesh.cell_dimension()):
            direction = [1.0 if i == j else 0.0 for j in range(mesh.cell_dimension())]
            c = project(Constant(direction), V)
            with c.vector().dat.vec_ro as cvec:
                cvecs.append(cvec)
        pc.setHYPRESetEdgeConstantVectors(*cvecs)
        '''
        pc.setUp()
        self.pc = pc

    def apply(self, pc, x, y):
        self.pc.apply(x, y)

    def applyTranspose(self, pc, x, y):
        self.pc.applyTranspose(x, y)

    def view(self, pc, viewer=None):
        super(HypreAMS, self).view(pc, viewer)
        if hasattr(self, "pc"):
            viewer.printfASCII("PC to apply inverse\n")
            self.pc.view(viewer)

    def update(self, pc):
        self.pc.setUp()
------------------------------------------------------------

Hope we can solve it !

**Comment by florian98765** [comment]
I just tested the coordinate version, and it produces the same iteration count:
```
pc.setCoordinates(np.reshape(mesh.coordinates.dat.data_ro, (-1,mesh.geometric_dimension())))
```

**Comment by xiaodizhang29** [comment]
What a surprise！It seems to find the error! In the Hypre manual, it says the input should satisfies 

![image](https://user-images.githubusercontent.com/43510798/97299731-668ff600-1890-11eb-9fc3-03374b2a0b5c.png)

In my view, the coordinate should be given in the order of the  interpolation node of P1 space rather the mesh coordinate. Thus, we should replace it by **P1.tabulate_dof_coordinates()** in FEniCS/DOLFIN. I have test it , it is right. But for firedrake, I don't find the corresponding function. Any  ideas?

Best wishes!

Xiaodi

**Comment by florian98765** [comment]
I run some more tests comparing the `interpolate` and the `coordinate` version. 
Actually I cannot find any difference between the two methods any more.
Maybe `mesh.coordinates` is already ordered correctly? 

From this point of few, I would like to change the method to use `setCoordinates` because it makes the code simpler (and also slightly faster).

Could you verify that this version also works for you? (This would maybe require a very recent firedrake version)
```
pc.setCoordinates(np.reshape(mesh.coordinates.dat.data_ro, (-1,mesh.geometric_dimension())))
```
best wishes

**Comment by wence-** [comment]
> I run some more tests comparing the interpolate and the coordinate version.
Actually I cannot find any difference between the two methods any more.
Maybe mesh.coordinates is already ordered correctly?

Only if the mesh use a piecewise linear geometry (which it doesn't always).

The safe thing to do is `interpolate(SpatialCoordinate(mesh), VectorP1)`

**Comment by xiaodizhang29** [comment]
Yes! You are right! @florian98765  Thank you very much! We should use 

`pc.setCoordinates(np.reshape(mesh.coordinates.dat.data_ro, (-1,mesh.geometric_dimension())))
`
rather than 

`    pc.setCoordinates(np.reshape(mesh._topology_dm.getCoordinates().getArray(),(-1,mesh.geometric_dimension())))
`
Thank you again!

**Comment by xiaodizhang29** [comment]
But for FEniCS/DOLFIN，
