### ISSUE TITLE
strange AMS setup failure 

### ISSUE THREAD

**Issue by florian98765** [firedrakeproject/firedrake#1886]
After the new AMS preconditioner has been merged into firedrake, I rerun some of my older simulations, with the adapted code.
For some reason I now get the following error, during PC setup:
```
/firedrake/src/fiat/FIAT/check_format_variant.py:10: DeprecationWarning: Variant of Nedelec element will change from point evaluation to integral evaluation. You should project into variant="integral"
  ' You should project into variant="integral"', DeprecationWarning)
N: 50061
NE: 292629
dofs: 342955
  0 SNES Function norm 1.164177949606e-01
Traceback (most recent call last):
  File "libpetsc4py/libpetsc4py.pyx", line 1298, in libpetsc4py.PCSetUp_Python                                             
  File "/firedrake/src/firedrake/firedrake/preconditioners/base.py", line 45, in setUp                                     
    self.initialize(pc)
  File "/host/home/florian/work/2020/eddy_current/team13/linear/firedrake/medium/gtos/MyHypreAMS_preconditioner.py", line 156, in initialize
    c = project(Constant(direction), V)
  File "/firedrake/src/firedrake/firedrake/adjoint/projection.py", line 29, in wrapper                                     
    output = project(*args, **kwargs)
  File "/firedrake/src/firedrake/firedrake/projection.py", line 92, in project 
    use_slate_for_inverse=use_slate_for_inverse).project()                                                                 
  File "/firedrake/src/firedrake/firedrake/projection.py", line 170, in project                                            
    self.apply_massinv(self.target, self.rhs)
  File "/firedrake/src/firedrake/firedrake/linear_solver.py", line 160, in solve                                           
    raise ConvergenceError("LinearSolver failed to converge after %d iterations with reason: %s", self.ksp.getIterationNumber(), solving_utils.KSPReasons[r])
firedrake.exceptions.ConvergenceError: ('LinearSolver failed to converge after %d iterations with reason: %s', 0, 'DIVERGED_PCSETUP_FAILED')
```

Rerunning the original standalone code (but with a recent firedrake version) also leads to the same error. Furthermore the code still works for a coarse mesh, whereas medium and fine mesh fails. 

For now I have the following questions:
- are there any changes in Firedrake which could explain this problem
- is it possible to install an older version of Firedrake using the installer? how can I find out the working version?
- any advice how to debug this problems are welcome

Thanks in advance
Florian

**Comment by wence-** [comment]
Can you add `"ksp_converged_reason": None` to the solver parameters? The error is occuring on the `c = project(Constant(direction), V)` line which is just attempting to produce representations of the constant vectors. I do not know why that would fail.

**Comment by florian98765** [comment]
Ah, I see. The error is raised within the `project` call:
```
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    c = project(Constant(direction), V)
  File "/firedrake/src/firedrake/firedrake/adjoint/projection.py", line 29, in wrapper
    output = project(*args, **kwargs)
  File "/firedrake/src/firedrake/firedrake/projection.py", line 93, in project
    use_slate_for_inverse=use_slate_for_inverse).project()
  File "/firedrake/src/firedrake/firedrake/projection.py", line 172, in project
    self.apply_massinv(self.target, self.rhs)
  File "/firedrake/src/firedrake/firedrake/linear_solver.py", line 160, in solve
    raise ConvergenceError("LinearSolver failed to converge after %d iterations with reason: %s", self.ksp.getIterationNumber(), solving_utils.KSPReasons[r])
firedrake.exceptions.ConvergenceError: ('LinearSolver failed to converge after %d iterations with reason: %s', 0, 'DIVERGED_PCSETUP_FAILED')
```

Replacing the projection with an interpolation resolved this issue. It think interpolation on edge elements was not available, when I implemented the original code. This would make the code even faster. 

An alternative solution would be to use `setCoordinates` instead:
```pc.setCoordinates(np.reshape(mesh.coordinates.dat.data_ro, (-1,mesh.geometric_dimension())))```

For the current problem it converges similarily, but as reported in #1881, convergence seems to be significantly worse at least for some problems.

I will try to submit a small fix soon.
thanks for your fast reply.

best wishes 
Florian

**Comment by xiaodizhang29** [comment]
@florian98765 Hello! Do you mean this

-----------------------------------------------
        # Build constants basis for the Nedelec space
        cvecs = []
        for i in range(mesh.cell_dimension()):
            direction = [1.0 if i == j else 0.0 for j in range(mesh.cell_dimension())]
            # c = project(Constant(direction), V)
            c = Interpolator(Constant(direction), V).callable()
            with c.vector().dat.vec_ro as cvec:
                cvecs.append(cvec)
        pc.setHYPRESetEdgeConstantVectors(*cvecs)
-----------------------------------------------

**Comment by florian98765** [comment]
i use  `c = interpolate(Constant(direction), V)`, but this may be equivalent!?

**Comment by wence-** [comment]
> i use c = interpolate(Constant(direction), V), but this may be equivalent!?

Just to note that yes, they are!
