### ISSUE TITLE
Block diag/upper/lower preconditioner 

### ISSUE THREAD

**Issue by xiaodizhang29** [firedrakeproject/firedrake#1894]
I am using block diag/upper/lower preconditioners for mixed poisson euqation. For the saddle matrix,

>  A= [M, B^T; B, 0], 

where M <--> (\sigma, \tau), B <--> (\div u, \tau). I consider three preconditioners as follows.

-  block diag preconditioner
> P= [D, 0; 0, Q],

 where D <--> (\sigma, \tau)+ (\div\sigma, \div\tau), Q <--> (u, v). This can be done by setting  

>     "pc_type": "fieldsplit",
>     "pc_fieldsplit_type": "additive",

Its performance is good.

-  block lower preconditioner
> P= [D, 0; 2*B, -Q],

where D <--> (\sigma, \tau)+ (\div\sigma, \div\tau), Q <--> (u, v). This is inspired by the Augmented Lagrange preconditioner.
[A CHARGE-CONSERVATIVE FINITE ELEMENT METHOD FOR INDUCTIONLESS MHD EQUATIONS. PART II: A ROBUST SOLVER](http://lsec.cc.ac.cn/~zwy/publication.htm)
This can be done by setting  

>     "pc_type": "fieldsplit",
>     "pc_fieldsplit_type": "multiplicative",

-  block upper preconditioner

> P= [D, 2*B^T; 0, -Q],

This can be done by setting 

>     "pc_type": "fieldsplit",
>     "pc_fieldsplit_0_fileds": "1",
>     "pc_fieldsplit_1_fileds": "0",
>     "pc_fieldsplit_type": "multiplicative",

There are three questions:

1. In the block lower preconditioner P, the (1,1) block  is a negative positive definite matrix, can we use conjugate gradient methods to slove it? 
2. For  the block upper preconditioner P, the performance is very poor, the iteration number up to 44, whlie the block diag/lower preconditioner is 6. But when I repalce -Q with Q, the iteration number becomes 6.  What can we do to see the details of every preconditioning process?
3. Many papers focus on block upper preconditioners. But the interface to PETSC is not so friendly. Can we define a block preconditioner and give preconditioning process by ourselves? This is very important for multiple physical coupling problem. Are there some examples for reference?

Any help would be greatly appreciated. Thank you.

**Comment by wence-** [comment]
> In the block lower preconditioner P, the (1,1) block is a negative positive definite matrix, can we use conjugate gradient methods to slove it?

According to [this](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/KSP/KSPCG.html) I think it should work.

> For the block upper preconditioner P, the performance is very poor, the iteration number up to 44, whlie the block diag/upper preconditioner is 6. But when I repalce -Q with Q, the iteration number becomes 6. What can we do to see the details of every preconditioning process?

(I guess one of these "uppers" should be a "lower", the second one?). If you run with `"ksp_view": None` you'll see a print out of the structure of the preconditioner. You can further then monitor convergence of the individual bits by using `"fieldsplit_0_ksp_monitor": None` (etc...)

I guess when you do the fieldsplit_0_fields: 1, fieldsplit_1_fields: 0 you end up with needing to solve

`[0, B; B^T, M]` which you precondition with `[-Q, 0; 2B^T, D]` I don't think this permutation requires a sign-flip, but I always get lost here.

> Many papers focus on block upper preconditioners. But the interface to PETSC is not so friendly. Can we define a block preconditioner and give preconditioning process by ourselves? This is very important for multiple physical coupling problem. Are there some examples for reference?

You could if you wanted to do this by writing your own Python-based preconditioner that pulls things apart appropriately. We have all the information available to do this, but it's not super-trivial.

I think it would also be productive to open a dialogue with the PETSc team about what is lacking wrt block upper triangular PCs.

**Comment by xiaodizhang29** [comment]
Thanks for your answers. For the second question,

> For the block upper preconditioner P, the performance is very poor, the iteration number up to 44, whlie the block diag/upper preconditioner is 6. But when I repalce -Q with Q, the iteration number becomes 6. What can we do to see the details of every preconditioning process?

The [PETSC user](https://gitlab.com/petsc/petsc/-/issues/761) said that 
![image](https://user-images.githubusercontent.com/43510798/98070109-79f81e00-1e9b-11eb-978a-896a3cbbcd28.png)

I will try again to find the reasons of failure for the block upper preconditioner.

**Comment by xiaodizhang29** [comment]
I'm sorry. I was too careless and made a spelling mistake. Now the upper preconditioner gives the same result as the lower.
