### ISSUE TITLE
HDF5 build error in firedrake-install

### ISSUE THREAD

**Issue by angus-g** [firedrakeproject/firedrake#1895]
The recent change to the `firedrake-install` script (#1885) removed the pin to HDF5 1.10.6. We're seeing petsc fail to build because of this, see this snippet from the petsc `configure.log`:

```
H5VLff.F90:41:6:

   USE H5fortkit
      1
Warning: USE statement at (1) has no ONLY qualifier [-Wuse-without-only]
H5VLff.F90:41:6: Fatal Error: Can't open module file ‘h5fortkit.mod’ for reading at (1): No such file or directory
compilation terminated.
make[3]: *** [H5VLff.lo] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

This actually seems to be an oversight in HDF5 1.12.0 which didn't correctly modify the dependencies in the autotools configuration when `H5VLff.F90` was added (it's not present in previous HDF5). Anyway, I don't seem to be able to reproduce this if I build firedrakeproject/petsc standalone with the same flags, so it's something about the `firedrake-install` environment.

**Comment by wence-** [comment]
Huh, I don't know what might be going on inside `firedrake-install` (as you note, it just runs petsc configure/make with flags). The only thing I can perhaps think is that some old externalpackages bits were lying around? Did you do `firedrake-install` from scratch, or did you `firedrake-update`?

**Comment by angus-g** [comment]
This is an install from scratch, yes.

**Comment by jgwilliams17** [comment]
Did you resolve this? I think I'm having the same issue (firedrake-install.log and configure.log attached). 

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/5647702/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/5647703/configure.log)

**Comment by angus-g** [comment]
For the moment I've just reverted to a pinned version of HDF5, reinstating this commit: https://github.com/firedrakeproject/firedrake/commit/34fa00066041cbc3c186d94092714736f2929e1a
