### ISSUE TITLE
Subclassing NonlinearVariationalSolver for FEM/BEM Problems

### ISSUE THREAD

**Issue by florian98765** [firedrakeproject/firedrake#1912]
Dear Firedrake Developers,

I would like to implement a FEM-BEM method (Johnson-Nedelec-Coupling) on top of an existing FEM-only code for the solution of Maxwell's equations. The idea is that the additional BEM method can be switched on like a different boundary condition, without changing the original FEM code.

What I need to solve is a block system [ A(u), B; C, D] (u,phi) = [rhs_phi; phi_u]`, where `A` is a FEM stiffness matrix, `B` is the FEM Neumann term. `C` and `D` are the dense BEM Single-, and Double-Layer matrices.

The idea is that I just provide the nonlinear variational form `a`. Somewhere within the nonlinear solver an PETSc MatNest created which adds to additional constant blocks `B`, `C`, and `D` and passes the block system (and a proper preconditioner) to the PETSc solver. The nonlinear matrix `A` as well as the Jacobian should be assembled automatically. Maybe I would also like to use Fieldsplit Preconditioners for the Block Matrix.

Is there an easy way to overload the `NonlinearVariationalProblem` and `NonlinearVariationalSolver` to achieve this?
As far as I can see many things are handled within the `_SNESContext`. Overloading only the Problem / Solver object thus would be complicated, right?

best wishes
Florian

**Comment by rckirby** [comment]
There are a few things going on here:
1.) This is an instance of a multi-domain problem (the domain and the part of its boundary where you are applying the BEM operator), which is not currently supported in Firedrake.  So officially, you need different `FunctionSpace` objects for the domain and the boundary and then a `MixedFunctionSpace` coupling the two together.  This is actually orthogonal to the question of using BEM operators.
2.) If you are willing to do some legwork, you could write your own PETSc setup -- the Jacobian would probably be a mat nest with blocks variously being Firedrake-assembled AIJ matrices or dense (or HSS or matrix-free!) blocks for the BEM operators.  I doubt you could overload `NLVP` and `NLVS` for reasons listed above, but petsc4py isn't that bad...
3.) There is some work in progress with Andreas Klöckner (UIUC) to incorporate nonlocal operators in Firedrake.  We have code in place to convert functions between Firedrake and his layer/volume potential tools and a paper that does a hand-rolled integration of layer potentials with Firedrake FEM operators (special case of domain truncation BC for Helmholtz): https://arxiv.org/abs/2009.08493.  We are working on making the code prettier through the `ExternalOperator` interface so that you can have UFL expressions that include both local and nonlocal operations.  That's getting closer -- code runs on a branch but isn't correct yet and we haven't tried merging the external operator branches back with master now that complex arithmetic is a thing.
4.) Once multi-domains and nonlocal operators both land, one wouldn't need to extend `NLVP` and `NLVS` since it should hopefully "just work", but this may be a while.

**Comment by florian98765** [comment]
Cool, seems to be pretty similar to what we are using:
`C` and `D` above, are Double- and Singlelayer Potential for the Laplace operator. Right now we are using Collocation-BEM where analytical equations are available for the potential operators. We are then using H2lib for matrix compression and wrap the operator as a PETSc matshell. 

> We have code in place to convert functions between Firedrake and his layer/volume potential tools

You mean that one map `firedrake` functions to `pytential`, evaluate the Potential (maybe in parallel with FMM) and get the results back into firedrake? That would be exactly what we need for our code. 

If I understand correctly, despite the fact that we are solving Laplace problems, the main difference is that you are using the Dirichlet-to-Neumann map whereas we use direct FEM-BEM coupling. For the DtN-map you also need a hypersingular potential operator, right? But therefore you don't get this larger block-system as in our case.

Is there some code which you could share? This would be very interesting for us.

Best wishes
Florian

**Comment by rckirby** [comment]
Converters to and from Firedrake now live in `meshmode` (which supports `pytential` and `volumential`).  We haven't really migrated the code to this new support, but there are branches (of branches) of various Firedrake packages that we're using to put everything back together.   

The code we used for the paper was: https://github.com/benSepanski/fd2mm

We're doing something kind of like DtN, but note that the double integral in our variational form integrates over different boundaries (\Gamma and \Sigma) so we don't actually have to evaluate any singular integrals.

**Comment by florian98765** [comment]
Dear Robert,
after reading through some of the publications I have some additional questions:
- you don't have singular integrals since you integrate over the external domain where no sources exist. In case of maxwell's equations this would require to put a small airbox around the magnetic region Gamma, right?
- nevertheless, this small airbox complicates meshing and has some other drawbacks. Without the airbox, one needs to deal with singular integrals. Could those also be handled by `pytentials`?
- `pytentials` seems to be limited to DG elements. We currently use CG 1 elements for the the magnetic scalar potential? e.g I would like to calculate the single-/double-layer potentials for CG1 trial and test functions. Would this be possible?
- is the code/mapping already running in parallel? 

best wishes 
Florian

**Comment by inducer** [comment]
> Without the airbox, one needs to deal with singular integrals. Could those also be handled by pytentials?

This is not a restriction in pytential, it's merely how we chose to approach the problem in that article. Pytential evaluates layer potentials (including hypersingular ones) anywhere in space, including on the source surface.

> pytentials seems to be limited to DG elements. We currently use CG 1 elements for the the magnetic scalar potential?

Given that pytential views its job as "simply evaluate the layer potential", you can always interpolate your density space "up" to DG and then project back down to your chosen test space (especially in iterative solves), so in my view this is less of a restriction.

I think you'll find that a few more key distinctions are the following:
- pytential is focused on arbitrary high-order accurate discretization, including curvilinear geometry. (As far as I'm aware, the analytic expressions you mention are available for P0 (maybe P1) densities on P1-geometry elements. Of course, there's Sauter-Schwab, but that's partially numerical and expensive/cumbersome at high order.)
- Given the ability to "simply" evaluate the layer potential, it becomes possible to use Nyström discretizations and second-kind IEs, which provide straightforward, generic error estimates (Anselone's theorem) and are computationally efficient. It also frees you from having to carefully manage test and trial spaces for stability. (In fact, for Nyström methods, there is no need to enforce any continuity between neighboring elements.)

> is the code/mapping already running in parallel?

Distributed-memory operation in pytential is [in the works](https://gitlab.tiker.net/inducer/pytential/-/merge_requests/102), but it's not yet merged. (cc @gaohao95)

**Comment by florian98765** [comment]
Dear Andreas,

that sounds perfect. DG is not a problem (I originally thought that only DG0 is supported).
Could you give me some hint how to get the code running?

Our current code looks something like this:
```
boundary_mesh = BoundaryMesh(mesh)
V  = state.function_space()
VB = fd.FunctionSpace(boundary_mesh, "CG", 1)

rho = fd.Function(V)
u = fd.Function(V)

K = DLP(VB, VB)
T = TraceOperator(V)

with rho.vector().dat.vec_ro as rho_vec: 
    with u.vector().dat.vec_wo as u_vec:
        T.multTranspose(K * (T * rho), u)
```
The main parts are the Trace Matrix with maps dofs for the Function to the dofs on the boundary (in correct order), as well as the doublelayer operator DLP which calculates the (singular) potential on the whole domain boundary. I think these two parts need to be replace by some `pytentials` alternatives. 

How can this be done? I already had a short look at the `meshmode` examples, but maybe you could give me some further advice? As far as I understand `build_connection_from_firedrake`, and `build_connection_to_firedrake` would be the equivalent of our T and T.transpose() matrices. How can the DLP be applied?

Regarding parallelization: If the interface is working. Should (in theory) everything run in parallel if I switch to the parallel branch of `pytentials` or is the firedrake interface a different topic. I am wondering how mesh-partitioning of the boundary mesh (where the BEM operators are defined) would look like?

thank you very much for your help 
best wishes Florian

**Comment by inducer** [comment]
>  How can the DLP be applied?

Sure. Once you've got the density on the meshmode (surface) discretization, you can follow the relevant [pytential example](https://github.com/inducer/pytential/blob/10c2ea345e69367cfbba67ba5aa2954ebac467cf/examples/layerpot-3d.py#L60-L116). For on-surface evaluation, make sure to pass `qbx_forced_limit="avg"`. Example [here](https://github.com/inducer/pytential/blob/master/examples/laplace-dirichlet-3d.py#L104-L105).

**Comment by florian98765** [comment]
Dear All, 
I just finished the first version of the FEM-BEM solver. I decided to implement a new class JohnsonNedelecSolver() which is very similar to the NonlinearVariationalSolver, but I omitted all the callback stuff.

The new class inherts from OptionManager in order to be configurable via the usual petsc parameter interface. Here i needed to use the `with self.inserted_options()` context in order to use the provided options.

The system matrix `[ A(u), B; C, D]` is stored as a MatNest where `C`and `D` are double- and singlelayer potential stored as MatShell operators. I needed to provide a Jacobian function, which updates A(u) in each nonlinear iteration, whereas `B`, `C`, and `D` stay constant, since they are independent of `u`. 

The code runs, but it still contains some flaws / bugs. Maybe someone could give me some advice how to fix the remaining issues:
- inside the Jacobian function i currently use `assemble(self.Ju, tensor=self._Ju)`, whereas the original code seems to use `create_assembly_callable`. Whats advantage of using `create_assembly_callable`?
- I create a sparse approximation of the system matrix which is used for preconditioning. By default I am using a fieldsplit method, where only the diagonal blocks are used. For sake of simplicity the preconditioning matrix is also created as a MatNest. Unfortunately this setup prevents the user from using many preconditioning methods. For example one cannot use a dense solver for the total preconditioning problem (just for testing reasons). Is there a more general way to setup the blockmatrix containing 2x2 aij matrices which allows to set the `mattype` via some option?
- I still have troubles with a strange bug inside the residual function. A single linear solve seems to give correct results, but if I apply a nonlinear solver for a linear problem, the first iteration converges to 1e-10, but when the second nonlinear iteration starts it again starts from 1e1, which was the initial true residual norm. It seems that the value is not updated correctly, or maybe some internal arrays are not used correctly. As a workaround I found that adding a `print("F.array)` seems to solve the problem at least for some cases. Does anybody have some advice how to debug such problems? 
- regarding `pytentials` I will definitely give it a try. I will let you know if it runs successful.

Thanks again for any advice
best Wishes
Florian

**Comment by wence-** [comment]
> inside the Jacobian function i currently use assemble(self.Ju, tensor=self._Ju), whereas the original code seems to use create_assembly_callable. Whats advantage of using create_assembly_callable?

They avoid some of the symbolic overhead associated with turning the form into executable code for assembly: they're purely a performance optimisation that you'd only really notice in the small-dof-number limit, so we can ignore this for now.

> I create a sparse approximation of the system matrix which is used for preconditioning. By default I am using a fieldsplit method, where only the diagonal blocks are used. For sake of simplicity the preconditioning matrix is also created as a MatNest. Unfortunately this setup prevents the user from using many preconditioning methods. For example one cannot use a dense solver for the total preconditioning problem (just for testing reasons). Is there a more general way to setup the blockmatrix containing 2x2 aij matrices which allows to set the mattype via some option?

The petsc approach to this is to disentangle assembly from matrix type. You should make the matrix for your coupled system in one way (or another), and then assemble into the blocks (by using MatGetLocalSubMatrix). This is what happens inside PyOP2 to allow us to switch between matnest and aij matrices.

The very simple thing you could do is catch a matrix_type option and do `MatConvert` inside your jacobian assembly.

> I still have troubles with a strange bug inside the residual function. A single linear solve seems to give correct results, but if I apply a nonlinear solver for a linear problem, the first iteration converges to 1e-10, but when the second nonlinear iteration starts it again starts from 1e1, which was the initial true residual norm. It seems that the value is not updated correctly, or maybe some internal arrays are not used correctly. As a workaround I found that adding a print("F.array) seems to solve the problem at least for some cases. Does anybody have some advice how to debug such problems?

PETSc vectors do some caching of the norms, based on a state counter. Depending on exactly how you update the Firedrake function data, that state counter may not be modified (with the norm then being out of date). `F.array` updates the state counter, which is probably why this works.

**Comment by florian98765** [comment]
Dear Lawrence,
thank you for the fast reply.

Replacing the `print` with an `F.stateIncrease()` also works as a workaround. The vector is updated like this:
```
self._Mconst.mult(X, F)
fd.assemble(A, tensor=self._A)
F.getNestSubVecs()[0] += self._A.dat.vec_ro
```
where `_Mconst = [0, B; C D]`is the constant part of the Jacobian. Instead of the += I also tried getNestSubVecs() followed by a setNestSubVecs(), but this also didn't affect the state-counter. I can live with the work-around, but I am just wondering how I can prevent such problem next time? Shouldn't at least setNestSubVecs() update the state-counter?

Regarding the `mat_type` I understand that the setup should be done, without fixing the type of the matrix. I could then use `setValuesBlockedCSR` to set the values for the submatrix blocks. I think I would have to add shift the dofs according to the block-location, right? Then I choose a `mat_type` and assemble the matrix. This way the `mat_type` should be configurable also by commandline, right?

best wishes 
Florian

**Comment by florian98765** [comment]
UPDATE:
I am still confused about the printed SNES residual norms. 
The FEM-BEM code (including the workaround) shows some strange results for a simple linear problem.
I could reproduce the same behavior, with a simple pure FEM code:
```
SOLVE
  0 SNES Function norm 2.394737140355e-01 
    Residual norms for MagnetostaticScalarSolver_ solve.
    0 KSP preconditioned resid norm 9.583178446190e+00 true resid norm 2.394737140355e-01 ||r(i)||/||b|| 1.000000000000e+00
    1 KSP preconditioned resid norm 4.291773708047e-01 true resid norm 4.445169692068e-02 ||r(i)||/||b|| 1.856224475397e-01
    2 KSP preconditioned resid norm 2.428747814040e-02 true resid norm 1.916951925124e-03 ||r(i)||/||b|| 8.004853195871e-03
    3 KSP preconditioned resid norm 4.256661970847e-03 true resid norm 9.081307478978e-05 ||r(i)||/||b|| 3.792193859587e-04
    4 KSP preconditioned resid norm 3.112574303804e-04 true resid norm 1.376084033036e-05 ||r(i)||/||b|| 5.746284257454e-05
    5 KSP preconditioned resid norm 1.126435257008e-05 true resid norm 7.536095999833e-07 ||r(i)||/||b|| 3.146940794812e-06
    6 KSP preconditioned resid norm 7.410431827042e-07 true resid norm 5.286472502066e-08 ||r(i)||/||b|| 2.207537692961e-07
    7 KSP preconditioned resid norm 3.246901923918e-08 true resid norm 2.844861312156e-09 ||r(i)||/||b|| 1.187963916463e-08
    8 KSP preconditioned resid norm 1.749952261837e-09 true resid norm 1.697001901398e-10 ||r(i)||/||b|| 7.086380683714e-10
    9 KSP preconditioned resid norm 8.002403142498e-11 true resid norm 8.122230869095e-12 ||r(i)||/||b|| 3.391700380064e-11
  1 SNES Function norm 8.122236318903e-12 
SOLVE
  0 SNES Function norm 8.122236318903e-12 
    Residual norms for MagnetostaticScalarSolver_ solve.
    0 KSP preconditioned resid norm 8.002234399365e-11 true resid norm 8.122236318903e-12 ||r(i)||/||b|| 1.000000000000e+00
    1 KSP preconditioned resid norm 6.254845819585e-12 true resid norm 6.597285878831e-13 ||r(i)||/||b|| 8.122499296748e-02
    2 KSP preconditioned resid norm 3.670025339491e-13 true resid norm 3.081025717014e-14 ||r(i)||/||b|| 3.793321932586e-03
    3 KSP preconditioned resid norm 2.251150748501e-14 true resid norm 1.710235038553e-15 ||r(i)||/||b|| 2.105620880019e-04
    4 KSP preconditioned resid norm 1.421056734078e-15 true resid norm 1.064884089085e-16 ||r(i)||/||b|| 1.311072526426e-05
    5 KSP preconditioned resid norm 1.048460782633e-16 true resid norm 6.443037294239e-18 ||r(i)||/||b|| 7.932590288274e-07
    6 KSP preconditioned resid norm 1.865569462344e-17 true resid norm 4.193031203185e-19 ||r(i)||/||b|| 5.162409758291e-08
    7 KSP preconditioned resid norm 1.215087616836e-18 true resid norm 6.084901735364e-20 ||r(i)||/||b|| 7.491658080919e-09
    8 KSP preconditioned resid norm 2.868970310578e-20 true resid norm 3.060224122749e-21 ||r(i)||/||b|| 3.767711259062e-10
    9 KSP preconditioned resid norm 2.457261884156e-21 true resid norm 1.312674760258e-22 ||r(i)||/||b|| 1.616149430672e-11
  1 SNES Function norm 3.237982190132e-15 
SOLVE:
  0 SNES Function norm 3.237982190132e-15 
    Residual norms for MagnetostaticScalarSolver_ solve.
    0 KSP preconditioned resid norm 1.854542761999e-15 true resid norm 3.237982190132e-15 ||r(i)||/||b|| 1.000000000000e+00
    1 KSP preconditioned resid norm 1.676290084035e-16 true resid norm 3.223720555797e-17 ||r(i)||/||b|| 9.955955179809e-03
    2 KSP preconditioned resid norm 2.122511233112e-17 true resid norm 1.765347119338e-18 ||r(i)||/||b|| 5.451997619748e-04
    3 KSP preconditioned resid norm 2.980501234694e-18 true resid norm 1.357507620168e-19 ||r(i)||/||b|| 4.192449310886e-05
    4 KSP preconditioned resid norm 2.417925710308e-19 true resid norm 1.632238797955e-20 ||r(i)||/||b|| 5.040913451992e-06
    5 KSP preconditioned resid norm 1.101992592658e-20 true resid norm 1.245560698333e-21 ||r(i)||/||b|| 3.846718805709e-07
    6 KSP preconditioned resid norm 4.774388424513e-22 true resid norm 7.419034248860e-23 ||r(i)||/||b|| 2.291252333466e-08
    7 KSP preconditioned resid norm 2.022220071500e-23 true resid norm 3.760158272660e-24 ||r(i)||/||b|| 1.161265890875e-09
    8 KSP preconditioned resid norm 1.019095562056e-24 true resid norm 1.759221070423e-25 ||r(i)||/||b|| 5.433078278764e-11
    9 KSP preconditioned resid norm 5.819234048146e-26 true resid norm 8.909846922905e-27 ||r(i)||/||b|| 2.751666439074e-12
  1 SNES Function norm 2.398180014049e-15 
```
Notice the the SNES Function norm is not exactly the same as the last KSP true resid norm. And more important the SNES Function norm does not get below 1e-15, whereas the KSP norm gets down to 1e-27.

Is this expected behavior? Here is a short example which finally diverges: 
```
from firedrake import *

mesh = UnitCubeMesh(10,10,10)
V = FunctionSpace(mesh, "CG", 1)
u = interpolate(Constant(0), V)
v = TestFunction(V)

n = FacetNormal(mesh)
mu, Hext = Constant(2.), Constant((1.,0.,0.))
a = mu * inner(grad(u), grad(v)) * dx
a -= mu * inner(Hext, grad(v)) * dx
a += inner(Hext, n) * v * ds
bcs = [ DirichletBC(V, Constant(0.), "on_boundary") ]

problem = NonlinearVariationalProblem(a, u, bcs)
params = {'snes_monitor':None, 
          'ksp_rtol':1e-10,
          'ksp_type':'cg',
          'pc_type':'ilu',
          'ksp_monitor_true_residual':None}
solver = NonlinearVariationalSolver(problem, solver_parameters=params)
solver.solve()
```

**Comment by florian98765** [comment]
Dear all,
I think we can close this for now.

The question regarding the SNES residual is still open, but is independent from this issue.
I will try to get `pytentials` running as soon as i find some time, and I will let you know if it works.

thanks again for all the valuable input.
best wishes
Florian
