### ISSUE TITLE
`FunctionSpace` takes a very long time with spatial + ensemble parallelism 

### ISSUE THREAD

**Issue by krober10nd** [firedrakeproject/firedrake#1918]
The following snippet hangs on the call to `FunctionSpace` if run with ensemble + spatial parallelism (i.e., more than one core per ensemble member). 

It however works:

1) in serial
2) with only spatial parallelism
3) with only ensemble parallelism without spatial parallelism 

```
from firedrake import *

my_ensemble = Ensemble(COMM_WORLD, 2)

mesh = Mesh("EAGE_Salt_EXACT.msh", comm=my_ensemble.comm)
x, y, z = SpatialCoordinate(mesh)
V = FunctionSpace(mesh, "CG", 1) # hangs here 
u = Function(V)
```

The same problem however does not occur with a built in mesh. 

The mesh is here

[External_3d_triangular_mesh.tar.gz](https://github.com/firedrakeproject/firedrake/files/5548935/External_3d_triangular_mesh.tar.gz)

Firedrake version: 
```
>>> import firedrake
>>> firedrake.__version__       
'0.13.0+4280.g458f2cee'
>>> 
```

Platform: 
Linux 64-bit Centos

thanks

**Comment by wence-** [comment]
Does it hang if you just do `mesh = ...; mesh.init()` ?

**Comment by krober10nd** [comment]
> Does it hang if you just do mesh = ...; mesh.init() ?

Yes.

**Comment by wence-** [comment]
Either we, or petsc, is not using the communicator correctly when loading from file

**Comment by wence-** [comment]
Ok so it's in the mesh load or distribution. 

Can you take the ensemble thing out of the way and just comm split 4 processes into a subcommunicator with 2 spatial processes and check that?

**Comment by krober10nd** [comment]
Sure. I'll get to that.

**Comment by krober10nd** [comment]
yea, same behavior with the ensemble communicator...never finishes initialization but 'past here' prints. 

mpiexec -n 4 python hang.py

```
from mpi4py import MPI
from firedrake import *

comm = MPI.COMM_WORLD
size = comm.size
rank = comm.rank

spatial_com = comm.Split(color=(rank // 2), key=rank)

mesh = Mesh("EAGE_Salt_EXACT.msh", comm=spatial_com)
print('past here',flush=True)
mesh.init()
```

**Comment by wence-** [comment]
Huh, I can't reproduce in the latest firedrake docker container.

**Comment by krober10nd** [comment]
Then it must be our installation on our cluster then. Let me check with our IT personal

**Comment by krober10nd** [comment]
So we did some experiments and discovered that with the GNU build of Firedrake, things work while for the Intel build  of Firedrake the problem persists.  Could there be some incompatibility with Intel-MPI?

**Comment by krober10nd** [comment]
was the docker by chance a GNU build?

**Comment by wence-** [comment]
docker is built with gcc+mpich.

**Comment by krober10nd** [comment]
I see. Do you have any ability to replicate the alleged issue? Or could you suggest a method to debug `msh.init()` to see where it's locked?

**Comment by wence-** [comment]
I don't have access to an intel MPI easily. My normal recourse is to run in a parallel debugger of some kind and check where the hang is. You can do that in python with `mpiexec -n 4 xterm -e python -m pdb script.py`, or `mpiexec -n 4 xterm -e gdb --args python script.py` for C level debugging.

**Comment by krober10nd** [comment]
The code hangs @mesh.py:670

```
            def add_overlap():
                # Default is FEM (vertex star) adjacency.
                self._topology_dm.distributeOverlap(overlap)
                self._grown_halos = True
```

**Comment by krober10nd** [comment]
so I discovered by just doing something else that it eventually passes through `mesh.init()` although it takes 30-45 minutes for a several million cell problem when doing both ensemble and spatial parallelism at the same time. Not sure what the slow down is but then again I can't figure out what `mesh.init()` actually does.

**Comment by wence-** [comment]
It adds the overlap to a parallel distributed mesh. If you have CG elements and not facet integrals, you can configure the distribution to not add the overlap (you don't need it in this case). Check out the distribution_parameters argument to Mesh.

**Comment by krober10nd** [comment]
I see thanks for the info, interesting. I unfortunately have CG elements so I need the overlap but is it really that expensive to add overlap? 

Could it be calling SCOTCH or some slow domain decomposition approach? METIS was never this slow

**Comment by krober10nd** [comment]
inspecting the code, it seems like it's indeed calling SCOTCH. How would I change to ParMETIS?

**Comment by wence-** [comment]
If you have CG that's good, and you don't have to add overlap. 

If the mesh setup doesn't take this long with meshes built on COMM_WORLD, i am continuing to blame your vendor's mpi implementation.

**Comment by wence-** [comment]
You have to get parmetis from firedrake-update (see --help) and maybe rebuild so petsc does its thing. Then you can configure the partitioner somehow (i forget). 

But i would want to rule the partitioner out as the problem. By the time mesh.init is called, the mesh is already decomposed and distributed

**Comment by krober10nd** [comment]
ah okay, I'll test out the `distribution_parameters` thing and get back.

**Comment by krober10nd** [comment]
so changing the overlap type worked, it's light speed faster now. 

```
I now pass this to the mesh load op...distribution_parameters={"overlap_type": (DistributedMeshOverlapType.NONE,0)}
```

**Comment by wence-** [comment]
It would be good to understand what went wrong. Since the setup did not take ages with only spatial parallelism, I suspect bugs in the MPI implementation.

Can you run one of the "bad cases" of `mesh.init()` with `-log_view` on the commandline so we can see if PETSc reports useful timing breakdown?

**Comment by krober10nd** [comment]
Sure I can. But I'm not sure what's the syntax to trigger the log view? Is is when I call Python?

**Comment by wence-** [comment]
`python foo.py -log_view`

**Comment by krober10nd** [comment]
thanks.
