### ISSUE TITLE
Firedrake Zenodo release

### ISSUE THREAD

**Issue by jwallwork23** [firedrakeproject/firedrake#1925]
Hi, please could I have a release for the following? Thanks a lot!

`
{"firedrake": "5eb39dc80df20031275fd75f74d29de4781e9d05", "PyOP2": "9608d1850513b4a92ac0f3a3afe9206c55cbd387", "tsfc": "35241741db0720fcaefb6884e575b1fdd39710fe", "COFFEE": "70c1e66a4e4e39d3bf75274505a16901af110751", "ufl": "4c6189a0bdfbc27753325ea4bd5668888b16c0a5", "FInAT": "7058bfad1a157d4a8e83ffcb25a3b28306c03063", "fiat": "d085f35723a6c2992009f8f21b7d14485c338b8d", "petsc4py": "8b76066bd3b0bcbeb8a432574f89e1da27137756", "loopy": "4f2b39411ebbc687a98cc8804bed04400cd1b475", "metarelease_info_file": null, "title": "Goal-Oriented Error Estimation and Mesh Adaptation for Tracer Transport Modelling", "petsc": "e06f0ea172bdcebe219894c0ab7da8ce3d13e711"}
`

**Comment by wence-** [comment]
Will get to this tomorrow.

**Comment by wence-** [comment]
Tag: `Firedrake_20201127.0`
Bibtex

```
@misc{zenodo/Firedrake-20201127.0,
 key   = {zenodo/Firedrake-20201127.0},
 title = {{Software used in 'Goal-Oriented Error Estimation and Mesh Adaptation for Tracer Transport Modelling'}},
 year  = {2020},
 month = {nov},
 doi   = {10.5281/zenodo.4293614},
 url   = {https://doi.org/10.5281/zenodo.4293614},
}
```
Thanks!

**Comment by jwallwork23** [comment]
Thanks a lot, @wence- !
