### ISSUE TITLE
Permissions on a firedrake install

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#1935]
This is an issue that causes frequent, but intermittent failures in the Jenkins testing of Thetis: the testsuite is (sometimes?) run as user `jenkins` inside a firedrake vanilla docker container where firedrake has been built as user `firedrake`. As a workaround permissions can be changed afterwards, but changing permissions on a large number of files in Docker is slow (on Jenkins it takes about 12 mins to change permisisions on all executables in lib/ and bin/). It was suggested instead to enable other users to run the container, by building it with a more permissive umask.

Looking a little further into this. I believe there are two separate issues:

## Executable permissions
If you look into the executable permissions in lib/ and bin/ in the firedrake container (or in any other firedrake install that has been run with the standard umask 022) with `ls -l $(find lib/ bin/ -executable -type f)` then you can see that the only executables that do not have executable permission for all, are the mpicc, mpicxx, mpiexec and mpif90 scripts that firedrake-install installs itself:
```
for opt in ["mpicc", "mpicxx", "mpif90", "mpiexec"]:
    ...
    if should_link:
        with open(dest, "w") as f:
            f.write('#!/bin/bash' + os.linesep + src + ' "$@"')
        os.chmod(dest, os.stat(dest).st_mode | stat.S_IEXEC)
```
Note that having `umask 0000` would not help in this case: it would still create readable and writable for all, but then only set executable for the user. So I believe the fix here is to just be more permissive in that last line. Not sure what the correct way to install is, somewhere on stackexchange the following was suggested:
```
      perm = os.stat(dest).st_mode
      os.chmod(dest,  perm | ((perm & 0o444) >> 2))
```
which looks at the current read permissions (which will be set according to umask), and then gives executable permissions to those that have read permission by shifting that bit 2 to the right.
This would also make it possible for users to share a firedrake installation in other situations (outside docker).

## Write permissions
I believe this only affects the .cache folder. One option is to just have the docker user set a different cache directory by setting `FIREDRAKE_TSFC_KERNEL_CACHE_DIR` and `PYOP2_CACHE_DIR`
Setting umask with docker seems to be a bit cumbersome. I could do something like:
```
RUN bash -c "umask 0000 & python3 firedrake-install --no-package-manager --disable-ssh --remove-build-files"
```
but there doesn't seem to be a way to change umask persistently between RUN commands that I can find; lots of people seem to use `ENV UMASK` or `ENV UMASK_SET` but I think that only applies to a certain build stack where somewhere along the way that env. variable is picked up to set the umask..

So this would mean that any step afterwards (e.g. Docker containers that build on vanilla) could still mess up the permissions. Actually adding the umask to the firedrake-install doesn't really help, because it doesn't create firedrake/.cache
So I could just add
```
RUN mkdir /home/firedrake/firedrake/.cache && chmod a+rwx /home/firedrake/firedrake/.cache 
```
Of course that still wouldn't fix a situation where a container is logged in with different users subsequently.

Yet another suggestion is to change the cache dir of the installed firedrake to a place relative to the users homedir. I don't know if it's possible to do something like `firedrake-install --cache-dir="~/.cache"` or $(HOME) with the correct amount of quoting so that it is only substituted when the cache dir is used (or cleaned), and not at the time of the install?

**Comment by stephankramer** [comment]
I've come to the conclusion that it's basically impossible to set the umask for docker run commands. (also suggested a.o. https://github.com/moby/moby/issues/19189),  If I build a container with a "umask 000" added in all the usual places: /etc/profile /etc/bash.bashrc, /etc/login.defs (UMASK 000), ~/.bashrc etc. etc. and I run
```
docker run <image> bash -c "umask"
```
it still comes back with the default umask 022.

**Comment by JDBetteridge** [comment]
Thetis CI now runs on Github CI (with a user named `firedrake`). Please open a new issue if the above is still a problem.
