### ISSUE TITLE
Pytest Failures and Can't Access Files

### ISSUE THREAD

**Issue by drb546** [firedrakeproject/firedrake#1950]
I have been trying to run the pytests in my Ubuntu Linux subsystem on my Windows machine, and I cannot get them to run. Also, there was no make.log file in my Linux subsystem. I was able to find the other files needed, but I could not get them to transfer from my Ubuntu 20.04.1 Linux subsystem to Windows. These are the instructions I have been following:

https://github.com/firedrakeproject/firedrake/wiki/Installing-on-Windows-Subsystem-for-Linux

Could someone explain how I can access these files so I can upload them to this github?

**Comment by danshapero** [comment]
Duplicate of #1949
