### ISSUE TITLE
Firedrake in IDE

### ISSUE THREAD

**Issue by lecovee** [firedrakeproject/firedrake#1960]
Hi,

first I want to mention that I am not super familiar with programming, so please apologize these newbie questions.

I want to use Firedrake in Ecilpse on Ubuntu. Everything works when compiling from the console after using the activate script. In Eclipse I use either of the Firedrake Python versions as the interpreter. If I start Eclipse out of the Firedrake terminal (after activate script) I can compile and run my Script.

Now to the problem: It seems as that the activate script does not affect the editor, meaning it marks the Firedrake imports as not found, but strangely only some of them. So for example `from firedrake import UnitSquareMesh` gives `Unresolved import: UnitSquareMesh` but also `def UnitSquareMesh Found at: firedrake.utility_meshes ...` . On the other hand `from firedrake import VectorFunctionSpace` gets resolved just fine.

I think (I am not sure anymore) I used Firedrake in Eclipse before and I didn't have to use the Script before but rather defining Firedrake as external library, but I don't know how I did this, so I think the whole approach above is wrong. However I tried every possibility of including Firedrake as external Library in some form but it never worked.

So I guess it is just a configuration probelm. I would appreciate if somebody can tell how to configure it.

**Comment by ReubenHill** [comment]
It sounds like when Eclipse runs its python interpreter, the firedrake virtual environment (venv) is not activated, or at least is not activated properly. So I agree that this appears to be an Eclipse configuration issue.

 I'm not an Eclipse user, but perhaps see what happens if you run `from firedrake import *`?

**Comment by lecovee** [comment]
Thank you for the advice!

Actually `from firedrake import *` is what I am coming from with the same behaviour: The scripts runs fine but the editor marks for example UnitSquareMesh as not found but VectorFunctionSpace is found as expected.

(regarding the invalid label: I am sorry if this is the wrong place to ask such questions. I will look for more information in a more Eclipse directed place.)

**Comment by lecovee** [comment]
For people that encounter the same problem, I found a solution.
Select Project-> RightClick-> PyDev-> Remove PyDev Project Config
and then restart eclipse

Essentially it is this: https://stackoverflow.com/a/29351006

**Comment by ReubenHill** [comment]
Glad to see you got this sorted! If you think it would be useful to others please feel free to add a note on the wiki for this repository.

Regarding this not being the right place - it's true that this isn't really a firedrake issue per-se but I was glad to try and be helpful. If you haven't already, please do join our very active [slack](https://firedrakeproject.slack.com/) if you have these kinds of questions in the future.
