### ISSUE TITLE
API documentation on website has not been updated in months

### ISSUE THREAD

**Issue by connorjward** [firedrakeproject/firedrake#1961]
I just noticed that the [API documentation](https://firedrakeproject.org/firedrake.html) on the website is considerably out-of-date. 
Specifically I noticed that the `constant_jacobian`  default for the `LinearVariationalProblem` changed from `True` to `False` last September and the website has not been updated to reflect this.

**Comment by dham** [comment]
Website rebuilt.

**Comment by wence-** [comment]
We could automate this by having a github actions builder pull the latest docker image and build the docs on a push to master (that would mean we are at most one commit behind).

Said builder needs an SSH key to be able to push to godaddy, but that can be added as a secret in the repository

**Comment by dham** [comment]
Let's put that on the to do list behind moving CI to actions.
