### ISSUE TITLE
Install script does not set OPENBLAS_NUM_THREADS

### ISSUE THREAD

**Issue by FabianL1908** [firedrakeproject/firedrake#1968]
I have done a fresh firedrake install yesterday on my MacBook and a linux machine. I’ve seen that firedrake ran extremely slow on the linux machine. Htop told me that there were running threads on all cores at 100% even though I only started the computation on a single core. Running export OPENBLAS_NUM_THREADS=1  seems to fix that issue. OPENBLAS_NUM_THREADS  is not set on both machines, but it only seems to cause problems on the linux machine.

**Comment by danshapero** [comment]
@fastice and I ran into the same issue with a recent build on an Ubuntu server. @wence- in slack suggested that a fix to this would involve either building OpenBLAS single-threaded when installing via PETSc, or setting OPENBLAS_NUM_THREADS=1 in the venv activate script.

**Comment by wence-** [comment]
We decided that we should do this at runtime via ctypes:

c.f. https://stackoverflow.com/questions/29559338/set-max-number-of-threads-at-runtime-on-numpy-openblas

**Comment by JDBetteridge** [comment]
This will be tackled in PR #2047

**Comment by wence-** [comment]
And done.
