### ISSUE TITLE
Firedrake Zenodo release

### ISSUE THREAD

**Issue by jwallwork23** [firedrakeproject/firedrake#1986]
Hi, please could I have a release for the following? Thanks a lot!

{"firedrake": "f9b9b1fe693dc24c79da0350fa014ebb611e37a8", "PyOP2": "d0cc348d4af759e16e01dfda8948485436b16c40", "tsfc": "fe07cb5563c7b1ef38b5b4f01b52275e32ed3ee8", "COFFEE": "70c1e66a4e4e39d3bf75274505a16901af110751", "ufl": "057c5f6f06687c401dab7683c2406a0e91901c9c", "FInAT": "34b3da492ed86286e1518f481252a2afca81acfb", "fiat": "42ceef358d4c1273a8ef83dac8169d7a3a54f968", "petsc4py": "0385919767fc51d581d089b221bb12fefbfa39b6", "loopy": "cbbdc7ebb6298859e2238ea207474b49a3706f2e", "petsc": "d8022d2971ef9a10847ccb0074273217a9a90a92", "metarelease_info_file": null, "title": "Mesh Adaptation and Adjoint Methods for Finite Element Coastal Ocean Modelling"}

**Comment by wence-** [comment]
```
@misc{zenodo/Firedrake-20210225.0,
 key   = {zenodo/Firedrake-20210225.0},
 title = {{Software used in 'Mesh Adaptation and Adjoint Methods for Finite Element Coastal Ocean Modelling'}},
 year  = {2021},
 month = {feb},
 doi   = {10.5281/zenodo.4561836},
 url   = {https://doi.org/10.5281/zenodo.4561836},
}
```

Tag is `Firedrake_20210225.0`

Thanks!

**Comment by jwallwork23** [comment]
Thanks for the quick response, Lawrence!
