### ISSUE TITLE
install recent version of slepc 

### ISSUE THREAD

**Issue by florian98765** [firedrakeproject/firedrake#1987]
Dear All,

I am just lost with installing the recent master of slepc (including slepc4py).

I tried activating firedrake and then pulling the actual slepc master and recompiling. Unfortunately this slepc version does not work with the installed petsc version. 

I also noticed that petsc4py is not updated, since it is installed from a separete repository. It seems that the recent slepc4py version in now also included within the slepc repository (similar to the situation with PETSc, compare #1908).

What would be the easiest way to get the recent slepc version running with firedrake?
best wishes
Florian

**Comment by wence-** [comment]
Ah, good spot!

We need to update the slepc branch pointer and switch to the in tree slepc4py. I will try and have a go.

**Comment by wence-** [comment]
I just did that and pushed the updated pointers (and some changes in firedrake to match). Can you check that `firedrake-update` now works and pulls in latest slepc?

**Comment by florian98765** [comment]
Yes, seems to work. Thanks a lot.
best wishes 
Florian

**Comment by florian98765** [comment]
Dear Lawrence, 
i just re-built firedrake, because I forgot to set some PETSc options. For some reason slepc build now fails. I am not sure what is the difference to the last build. I only passed the PETSc option `--download-sundials2`, but I think this is not related to the error. Maybe some parts of the installation were cached somewhere? 

I definitely have a version where the new SLEPc version is running, but sundials is missing. Rebuilding everything from scratch now fails with:
```
In file included from src/SLEPc.c:3:0:
  src/slepc4py.SLEPc.c: In function ‘__pyx_pf_8slepc4py_5SLEPc_2DS_48truncate’:
  src/slepc4py.SLEPc.c:20373:47: error: too few arguments to function ‘DSTruncate’
```
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6120960/firedrake-install.log)

Did you do some further changes on PETSc / SLEPc?
best wishes
Florian

**Comment by wence-** [comment]
Hi Florian,

I didn't change anything I think. Looking in the log, I see

> `Running command 'git clone -q --recursive https://github.com/firedrakeproject/slepc4py.git'`

Which makes me suspect you have an older `firedrake-install` script. More up-to-date versions will get slepc4py from the slepc repo. Can you try grabbing a new `firedrake-install` and trying again?

**Comment by florian98765** [comment]
Dear Lawrence,
you are right. It was the other way around: the original version took the new install-script, but somehow the current version takes the installer from docker-cache. 
Sorry for the confusion and thanks for the fast reply.
best wishes
Florian

**Comment by florian98765** [comment]
Dear Lawrence, 
could you please update to the latest petsc main branch once more. Unfortunately the sundials bindings which we are using got broken. It should have been fixed by the following commit:
"TSSUNDIALS: update PETSC_HAVE_SUNDIALS to PETSC_HAVE_SUNDIALS2"

thanks a lot 
Florian
