### ISSUE TITLE
Installing Firedrake in Arch linux.

### ISSUE THREAD

**Issue by cdelv** [firedrakeproject/firedrake#1993]
Hi, I'm using an arch base OS. And I have 2 problems with the installation of the library suggested in these page
https://firedrakeproject.org/download.html
 the first problem is that arch don't use the apt-get package so the python script wont run

The second problem is that after installing, to run it you have to source a .csh file. The problem with this is that arch uses a fish terminal so I would need a .fish file.

 Does some one know how to solve these problems?

**Comment by dham** [comment]
If you're running on a platform other than MacOS or a .deb based Linux then you should pass `--no-package-manager` to the installer. Obviously you have to make sure that the dependencies listed on the install site are installed first.

Firedrake installs a plain old Python venv, which provides activation scripts for bash (and similar), csh, and fish. The fish activate script is `activate.fish`.
