### ISSUE TITLE
PETSc update for sundials2 

### ISSUE THREAD

**Issue by florian98765** [firedrakeproject/firedrake#2009]
Dear Lawrence,
could you please update to the latest petsc main branch once more. Unfortunately the sundials bindings which we are using got broken. It should have been fixed by the following commit:
"TSSUNDIALS: update PETSC_HAVE_SUNDIALS to PETSC_HAVE_SUNDIALS2"

thanks a lot
Florian

**Comment by wence-** [comment]
Done. @bourdin I think this should have the scalapack fix too.

**Comment by florian98765** [comment]
Thank you very much for the fast reply.
