### ISSUE TITLE
Zenodo Release

### ISSUE THREAD

**Issue by orpembery** [firedrakeproject/firedrake#2011]
Can I have a Zenodo release for the following JSON please?

{"firedrake": "3080efc4d6fcae7ce84d6dabb068d9fbe64ec843", "PyOP2": "df3f03a371654444b3bc7deade0759f8ee9314ce", "tsfc": "0d8251e1451a9f0148c10db5a1bd344e2e2d40d2", "COFFEE": "72a4464aa18fd408de5304ac467db18d7af2b670", "ufl": "9d11804abc2442619138d2f112a0e8a1e7e878b3", "FInAT": "de6f2ab96464f81d984c7d77522db6464d780cf8", "fiat": "daacf42c19a83843ffcde3dc18fc0d5922feebcb", "petsc": "d566698e4b0df05357f21e63354cc0745587193b", "petsc4py": "3619809e2f823ec1c6e1f718bec34bae5b332d18", "metarelease_info_file": null, "title": "Analysis of a Helmholtz preconditioning problem motivated by uncertainty quantification"}

Thanks!

**Comment by wence-** [comment]
Tag: `Firedrake_20210317.0`

Bibtex:

```
@misc{zenodo/Firedrake-20210317.0,
 key   = {zenodo/Firedrake-20210317.0},
 title = {{Software used in 'Analysis of a Helmholtz preconditioning problem motivated by uncertainty quantification'}},
 year  = {2021},
 month = {mar},
 doi   = {10.5281/zenodo.4611654},
 url   = {https://doi.org/10.5281/zenodo.4611654},
}
```

Thanks!

**Comment by orpembery** [comment]
Thanks Lawrence!
