### ISSUE TITLE
Installation failure on Mac OS

### ISSUE THREAD

**Issue by sv2518** [firedrakeproject/firedrake#2017]
Hi, I have tried to install firedrake on macOS Catalina 10.15.7 with Python 3.9.1 and Clang 11.0.0. I am running into an error that I have not had yet. I am wondering, if it occurs because I have recently upgraded to Catalina. I have attached the install log and the output of brew doctor.

In one line of the log file it says "Please check your Xcode installation", but I am not sure if this is actually causing the failure.

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6190299/firedrake-install.log)
[doctoroutput.txt](https://github.com/firedrakeproject/firedrake/files/6190318/doctoroutput.txt)

Does anyone have an idea what I have screwed up here?

**Comment by JDBetteridge** [comment]
You're right, it seems to be complaining about the Xcode version:
`Compiling with an SDK that doesn't seem to exist: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk`
Could you try updating Xcode the the latest version?

As for the cause, it seems PETSc got built with 10.14 somehow and now post PETSc install things are being installed with 10.15.
Perhaps the system was still updating

**Comment by sv2518** [comment]
Okay after getting the newest version of command line tools, this still does not work. I was able to run `/Users/sv2518/firedrakeinstalls/firedrake/bin/python -m pip install --no-build-isolation --no-binary mpi4py,randomgen,islpy,numpy,scipy -vvv mpi4py>=1.3.1` manually, but the firedrake update still fails with the following log.

[firedrake-update.log](https://github.com/firedrakeproject/firedrake/files/6191245/firedrake-update.log)

**Comment by wence-** [comment]
Can you show the output of:

```
/Users/sv2518/firedrakeinstalls/firedrake/bin/python -c "import sysconfig; print(sysconfig.get_config_var('PY_CORE_LD'))"
```

**Comment by connorjward** [comment]
I don't know if this would matter but isn't the compiler used in `firedrake-update` the `mpicc` from the already installed PETSc? Could it be that you're still using the old tools because you're using that compiler? In that case a fresh `firedrake-install` might fix it.

**Comment by sv2518** [comment]
> /Users/sv2518/firedrakeinstalls/firedrake/bin/python -c "import sysconfig; print(sysconfig.get_config_var('PY_CORE_LDFLAGS'))"

-L/usr/local/lib

> I don't know if this would matter but isn't the compiler used in `firedrake-update` the `mpicc` from the already installed PETSc? Could it be that you're still using the old tools because you're using that compiler? In that case a fresh `firedrake-install` might fix it.

Maybe.  I will give it another go over night, but I don't think that "just that" would help. From the very start the problem was, that something in the install was trying to pick up /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk even though I only have /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk. I don't think updating the command line tools has actually changed anything, they were probably already up to date.

Jack also had the following suggestions, but no luck. Given what Connor said, I might need to run firedrake-install for them to take full effect, so I will try that.
```
export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include
```
 or get the path from
```
xcrun --show-sdk-path
```
and
```
export MACOSX_DEPLOYMENT_TARGET=10.15
export SDKROOT=/that/path
```

**Comment by wence-** [comment]
> > /Users/sv2518/firedrakeinstalls/firedrake/bin/python -c "import sysconfig; print(sysconfig.get_config_var('PY_CORE_LDFLAGS'))"
> 
> -L/usr/local/lib

Hmmm. Mine says:

```
$ /usr/local/Cellar/python@3.9/3.9.2_1/bin/python3 -c "import sysconfig; print(sysconfig.get_config_var('PY_CORE_LDFLAGS'))"

-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -L/usr/local/lib -flto -Wl,-export_dynamic -g
```

I think when I updated to catalina I had to do a dance where I did `brew uninstall python` followed by `brew install python`.

**Comment by sv2518** [comment]
Okay, I will do that as well before I start the reinstall and report back tomorrow.

**Comment by sv2518** [comment]
> I think when I updated to catalina I had to do a dance where I did `brew uninstall python` followed by `brew install python`.

Okay, this seems to have fixed the previous issue. I have got a new issue now, that is `PETSc was configured with one MPICH mpi.h version but now appears to be compiling using a different MPICH mpi.h version`. I have brew uninstalled mpich, then brew installed mpich again and started yet another install. Please let me know, if anyone has had this issue already and already knows the fix for that, because that might save me another 2hrs or so waiting for the install go through and be borked again. 

Unfortunately me trying to fix my new firedrake installed resulted in me destroying my old firedrake install. If I try to import firedrake in the old venv, I get 
```
 ImportError: dlopen(/Users/sv2518/firedrakeinstalls/firedrake3/lib/python3.8/site-packages/petsc4py/lib/default/PETSc.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/gcc/lib/gcc/9/libgfortran.5.dylib
  Referenced from: /Users/sv2518/firedrakeinstalls/firedrake3/src/petsc/default/lib/libpetsc.3.013.dylib
  Reason: image not found
```

**Comment by wence-** [comment]
This looks like homebrew has removed gcc-9. If you `brew install gcc@9` does this problem disappear?

> PETSc was configured with one MPICH mpi.h version but now appears to be compiling using a different MPICH mpi.h version

I am not sure how you are building PETSc, but the PETSc configure keeps track of the MPI version it uses, and if that is upgraded (e.g. mpich 3.2 -> 3.3) it complains.

**Comment by sv2518** [comment]
> This looks like homebrew has removed gcc-9. If you brew install gcc@9 does this problem disappear?

Was this in response to my old firedrake being screwed or the mpi version issue?

> I am not sure how you are building PETSc, but the PETSc configure keeps track of the MPI version it uses, and if that is upgraded (e.g. mpich 3.2 -> 3.3) it complains.

I am doing nothing special, just the default PETSC installation as it comes with firedrake-install without any options. To fix what you said, do I just downgrade mpich?

I have double checked without the new venv activated mpicc -v gives `MPICH version 3.3.2` with the venv activated I get `MPICH version 3.4.1`. Here are firedrake install log and petsc configure log:

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6196692/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/6196696/configure.log)

**Comment by wence-** [comment]
> Was this in response to my old firedrake being screwed or the mpi version issue?

Sorry, old firedrake breakage.

**Comment by sv2518** [comment]
> Sorry, old firedrake breakage.

Okay, no then, that did not help.

**Comment by wence-** [comment]
> I am doing nothing special, just the default PETSC installation as it comes with firedrake-install without any options. To fix what you said, do I just downgrade mpich?

I don't think so.

This is the failure:

```
    /Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/bin/mpicc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/include -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -L/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/lib -I/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/include -Ipyop2 -I/Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages/numpy/core/include -I/Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages/petsc4py/include -I/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/include -I/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/include -I/Users/sv2518/firedrakeinstalls/firedrake/include -I/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c pyop2/sparsity.c -o build/temp.macosx-10.15-x86_64-3.9/pyop2/sparsity.o
 
...
    In file included from pyop2/sparsity.c:618:
    In file included from /Users/sv2518/firedrakeinstalls/firedrake/src/petsc/include/petsc.h:5:
    In file included from /Users/sv2518/firedrakeinstalls/firedrake/src/petsc/include/petscbag.h:4:
    /Users/sv2518/firedrakeinstalls/firedrake/src/petsc/include/petscsys.h:213:6: error: "PETSc was configured with one MPICH mpi.h version but now appears to be compiling using a different MPICH mpi.h version"
    #    error "PETSc was configured with one MPICH mpi.h version but now appears to be compiling using a different MPICH mpi.h version"
         ^
    1 warning and 1 error generated.
```

So what does `/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/bin/mpicc -show` say?

If you compile this file:

```
#include <mpi.h>
#include <petsc.h>
#include <stdio.h>
int main(void):
{
  printf("%d %d\n", MPICH_NUMVERSION,  PETSC_HAVE_MPICH_NUMVERSION);
  return 0;
}
```

with the mpicc in that (failed) firedrake venv with:

```
/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/bin/mpicc -I/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/include foo.c -o foo
```

What do you get?

**Comment by wence-** [comment]
> Okay, no then, that did not help.

OK, this is because the install of gcc@9 puts things in `/usr/local/opt/gcc@9` rather than `/usr/local/opt/gcc`. You could probably try rewriting the rpaths in those dylibs but that way madness lies.

**Comment by sv2518** [comment]
> So what does /Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/bin/mpicc -show say?

```
gcc -I/usr/local/opt/openblas/include -Wno-implicit-function-declaration -g -O3 -Wno-implicit-function-declaration -Wl,-rpath,/usr/local/opt/openblas/lib -L/usr/local/opt/openblas/lib -L/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/lib -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/include -L/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/lib -lmpi -lpmpi
```

> If you compile this file:

> #include <mpi.h>
> #include <petsc.h>
> #include <stdio.h>
> int main(void):
> {
  printf("%d %d\n", MPICH_NUMVERSION,  PETSC_HAVE_MPICH_NUMVERSION);
  return 0;
}
> with the mpicc in that (failed) firedrake venv with:

> /Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/bin/mpicc -I/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/include foo.c -o foo
What do you get?

If I remove the : after main the command runs with no issue and when I execute generated file, I get `30401300 30401300`

`OK, this is because the install of gcc@9 puts things in /usr/local/opt/gcc@9 rather than /usr/local/opt/gcc. You could probably try rewriting the rpaths in those dylibs but that way madness lies.`

Okay let's focus on getting the new install working.

**Comment by wence-** [comment]
I think we're far enough in that we should just be able to fix things up "by hand". Can you activate the venv and set:
```
PETSC_DIR=/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/
PETSC_ARCH=default
```
and then run `pip install -e PyOP2/` ?

**Comment by sv2518** [comment]
Okay that gives me
```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /Users/sv2518/firedrakeinstalls/firedrake/src/PyOP2/PyOP2
(firedrake) ma-sv2518:PyOP2 sv2518$ cd ..
(firedrake) ma-sv2518:src sv2518$ pip install -e PyOP2/ 
Obtaining file:///Users/sv2518/firedrakeinstalls/firedrake/src/PyOP2
Requirement already satisfied: decorator in /Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages (from PyOP2==0.13.0+554.gd0cc348d) (4.4.2)
Requirement already satisfied: mpi4py in /Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages (from PyOP2==0.13.0+554.gd0cc348d) (3.0.3)
Requirement already satisfied: numpy>=1.6 in /Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages (from PyOP2==0.13.0+554.gd0cc348d) (1.20.1)
Requirement already satisfied: COFFEE in ./COFFEE (from PyOP2==0.13.0+554.gd0cc348d) (0.1.0)
Requirement already satisfied: networkx in /Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages (from COFFEE->PyOP2==0.13.0+554.gd0cc348d) (2.5)
Installing collected packages: PyOP2
  Running setup.py develop for PyOP2
    ERROR: Command errored out with exit status 1:
     command: /Users/sv2518/firedrakeinstalls/firedrake/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/sv2518/firedrakeinstalls/firedrake/src/PyOP2/setup.py'"'"'; __file__='"'"'/Users/sv2518/firedrakeinstalls/firedrake/src/PyOP2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/sv2518/firedrakeinstalls/firedrake/src/PyOP2/
    Complete output (30 lines):
    /usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py:274: UserWarning: Unknown distribution option: 'test_requires'
      warnings.warn(msg)
    running develop
    running egg_info
    writing PyOP2.egg-info/PKG-INFO
    writing dependency_links to PyOP2.egg-info/dependency_links.txt
    writing requirements to PyOP2.egg-info/requires.txt
    writing top-level names to PyOP2.egg-info/top_level.txt
    reading manifest file 'PyOP2.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'PyOP2.egg-info/SOURCES.txt'
    running build_ext
    skipping 'pyop2/sparsity.c' Cython extension (up-to-date)
    building 'pyop2.sparsity' extension
    mpicc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/include -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -Ipyop2 -I/Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages/numpy/core/include -I/Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages/petsc4py/include -I/Users/sv2518/firedrakeinstalls/firedrake/src/petsc//include -I/Users/sv2518/firedrakeinstalls/firedrake/src/petsc//default/include -I/Users/sv2518/firedrakeinstalls/firedrake/include -I/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c pyop2/sparsity.c -o build/temp.macosx-10.15-x86_64-3.9/pyop2/sparsity.o
    In file included from pyop2/sparsity.c:610:
    In file included from /Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
    In file included from /Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1944:
    /Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it with " \
     ^
    In file included from pyop2/sparsity.c:618:
    In file included from /Users/sv2518/firedrakeinstalls/firedrake/src/petsc//include/petsc.h:5:
    In file included from /Users/sv2518/firedrakeinstalls/firedrake/src/petsc//include/petscbag.h:4:
    /Users/sv2518/firedrakeinstalls/firedrake/src/petsc//include/petscsys.h:213:6: error: "PETSc was configured with one MPICH mpi.h version but now appears to be compiling using a different MPICH mpi.h version"
    #    error "PETSc was configured with one MPICH mpi.h version but now appears to be compiling using a different MPICH mpi.h version"
         ^
    1 warning and 1 error generated.
    error: command '/Users/sv2518/firedrakeinstalls/firedrake/bin/mpicc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/sv2518/firedrakeinstalls/firedrake/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/sv2518/firedrakeinstalls/firedrake/src/PyOP2/setup.py'"'"'; __file__='"'"'/Users/sv2518/firedrakeinstalls/firedrake/src/PyOP2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

If I change the command in which this fails with the following two options removed
`-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include` I don't get the petsc error.

**Comment by sv2518** [comment]
So the last command I ran was
```
/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/bin/mpicc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall  -L/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/lib -I/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/include -Ipyop2 -I/Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages/numpy/core/include -I/Users/sv2518/firedrakeinstalls/firedrake/lib/python3.9/site-packages/petsc4py/include -I/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/include -I/Users/sv2518/firedrakeinstalls/firedrake/src/petsc/default/include -I/Users/sv2518/firedrakeinstalls/firedrake/include -I/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c pyop2/sparsity.c -o build/temp.macosx-10.15-x86_64-3.9/pyop2/sparsity.o
```

**Comment by wence-** [comment]
I suspect that this bit `-I/usr/local/include` is the problem.

**Comment by wence-** [comment]
if you `brew unlink mpich` do things work?

**Comment by sv2518** [comment]
Ja! firedrake-update finished successfully now. If I import firedrake I get a warning. Do I need to worry about that? 
```
/Users/sv2518/firedrakeinstalls/firedrake/src/firedrake/firedrake/randomfunctiongen.py:282: UserWarning: Unknown attribute: Firedrake needs to wrap numpy.random.Generator.permuted.
  warnings.warn("Unknown attribute: Firedrake needs to wrap numpy.random.Generator.%s." % class_attr)
```

I ran some Slate tests, those seemed to be working.

**Comment by wence-** [comment]
I think that warning is not problematic. It's just telling us that numpy's randomgen has some new property we're not wrapping up.

**Comment by sv2518** [comment]
Okay, cool! Thanks to everyone who put some thoughts into my problems here, it was a difficult birth of the Firedrake ;)
