### ISSUE TITLE
Firedrake Zenodo Release

### ISSUE THREAD

**Issue by Justincrum** [firedrakeproject/firedrake#2020]
Looking to get a firedrake zenodo release for the trimmed serendipity work that some of us have been doing recently.  Attaching the firedrake.json file by copy/pasting it here.  I tried attaching the firedrake.json file how git asks me to, and it says "We don't support that file type."

{"firedrake": "306e7c92ac67c11518c8a801abbafe43859f82ec", "PyOP2": "d0cc348d4af759e16e01dfda8948485436b16c40", "tsfc": "125c157831fb0e5295eea6939af25cecfe7fecf8", "COFFEE": "70c1e66a4e4e39d3bf75274505a16901af110751", "ufl": "0449576c984a06052ec4b00034b3f16072029005", "FInAT": "bcf11baffc4762c74237957a779bd76b3a9be0a2", "fiat": "26feeed26906464c0a04b572c89795a71c7fdbcb", "petsc": "a033d6a5187357ab3a4359400592d1a6798cbcf5", "loopy": "7665f16acfd34cde6cb420425f2b4089af1b528c", "slepc": "51b1ff1e2b48520e83092882af9baf7722992751", "metarelease_info_file": ["TrimmedSerendipityTestCodes.tar.gz", "H4sIAMaTY2AAA+w9a3Mit7L7mar9Dzr4bhU4w5iHvU62wqmwMI45sYEATu5WaoMHRsDY8zqjGWwn\nlfvbb7fmPQzYjtfYSUYnZw1Sq7vVklrqltQsTZ0euPWvD65mtqsfzFWbKrZ8TQ/O706Czz+b9vXB\n2FZ1nSojalNDUS3VuRtT5rRNhbKD0VK2qTzV6ATzJl7mmzBVIR0fHb2p1hpH7xuH/PtRvcH/+ulN\n7bDaqB7Xaoe16ptqo3Z03HhDjt7sILnMkW1C3vD2b4FjjqtQw9kFS7tM4oF48N2ZaSzOVOP6mWgE\nfbzhb7V29D4xFqo1yDl+Q86eiZ9ECvrfNs2tnXtf+V80LZ9t/p+rt1SZDEyVMdOYNBTRunvpxuZp\nLe2i/3FSvz88jOn/46N67TCY88fvDxsp/d+ogkog1V0I4KH6/8pky13ws+O0V9ibqxr9QEjGfC3s\nya6zNG0o/Q/ISTVIG4RU2FNkB2o0DmrfHNRrhb1CsVgstE3rzlYXS4fUq/VaAr4woLYOaFXTICoj\nSxhC0zuysGXDoYpA5jalxJyTGYyiBRWIYxLZuCMWtYERYk4dWTVUY0EKMpkBEQR1loCHmXPnBgYe\nQCtEBq5nKvClEMWcuTos1bKDBLF1jJScJSXFkV+jWBYKQEWhskaASSwLisiNCi12HWLDSLbVGeIQ\nAGimuQoyERRrqq76FApYnzedIe8ugzYgowLRTUWd41/KG2a5U01lS4EoKuKeug5kMsycUQNrFaAl\nB6ZNGNU0RKEC57y1EX8Cby2QsVCmji8lTvgG5nKyLQWQ0ty1DSBKeSXFBKlxmld05mAOws9NTTNv\nsHUzE+Y2Nop9KBTGUCRPzRXlrfH61jAdYNbjAfvAinrWL2JLGZifUl9mQBckXJBjDbKRPsw6w1FB\n/pZpc4LphorAwKlERv2T8c+toUS6IzIY9n/qdqQOKbZG8L0okJ+749P+xZgAxLDVG38i/RPS6n0i\nP3R7HRCn9L+DoTQakf6QdM8HZ10JMru99tlFp9v7nnyEir3+mJx1z7tjwDruE6To4+pKI1IAdOfS\nsH0K31sfu2fd8SeBnHTHPUR6AlhbZNAajrvti7PWkAwuhoP+SAIGOoC31+2dDIGMdC71xiIpdHuQ\nSaSf4BsZnbbOzjix1gU0YMg5bPcHn4bd70/H5LR/1pEg86MEvLU+nkkeLWhX+6zVPYeGdVrnre8l\nXq0PaIYczufv51OJZwHBFvzXHnf7PZRLu98bD+GrAA0djrFqgdf9uTuSBNIadkcolJNhHwigTKFK\nn2OBij3JQ4PyJoluQTSYcTGSIm46UusMkI2wdhwa+pTrirkNIzVcaoiq4yAg+wX/A6gBS7YZTcGJ\nFnXYLIAeSOPRrFDggDZphpXElr3g03/AS0oFkk6wOM1s1cJR14ShhGMfpgkMS9WwYGbDODRtBXDi\nINcpW4IqmKsGRZxisexTFGVFmcg+qVKx0ofRWKxU+lgTPjp3Fm2qhgN9tUZ/STWrWexyYjjiPWr+\n8LdM7c4wdZgZbDOxnkesDWpCurVMA3IfSZP61Xi7DVefehzMACPDCcvbXd/f75Hb+B9kCfhgIG+f\nM/4HeWOlcqHAsWF90O0LWsJskYtEINFn8hWplT9wHhH+KgUfb5VfLZ7l1w6buLe3d47MMuoQ1xLD\nfBRkhy5wbWkSI8z22tqft3lLm9iqq7BQBzxNcmGozui/LuggRFxK1BBI6ivAKbaqwcJjy1pzbLu0\nHKGjHJ9069ioCDk2HfW/Jt+B2m6mUK33WizxKpMlRS3crB0kuSqXE/I4cQ2+bhFmyaiRU5LZQ8U+\nT8LMUEHjwgxa2tUUXMTISFcNl3XUFSktFXVVBsl3Bm1SOvu1HrVxD3qw15ZiID96EBG9JaAYcSpN\nErDGv5dQQDCSQ0IwiKNui2ho9a3VgalERVKBERJ1Am5rgvoRK/sB1hBQMec4ICJ4UVH1UlKyA9uE\nXa6+JlKmLnRZIC7Uh32yrAV8slKELmLJkV2BrBAW9hjZoCHsrUBgA/EbAEMJLphtE/SFasCA4+2P\nsLr0FqCYapQsdf+2vO9/ugs//VZO8svhYRemlKBqVDaH3Ap0ZiksirEjQ2FJMZ2S32JoCnY6guPH\nfdf/wovL+6vyvnIb9SNinu+v4nk3sV7NlgCIfWRqK9AboGtkncJMY1w3M8jFTQtXm17HxKY/wmJ/\n/l5kBmUTVI7FD6Ro0BvHNDRWFDKmmweqgbJnVLZny7DWVGbqbEsV3QSdYdoA2gMltRkO9lcr3Asq\nE7CXYN+2rYIuOyF9Wb3aRl2+nagOwNWqW1olLyZX8sycqjKSrdS3g1o2DTeD1N5c4ZpZIZdQB0R7\nl80pAj6m+Qjvi3UC+pNCFaYqrqxtq2TNQmY0d4vEbMdEPDVaqW2RgxxC1bMFC+Tm8gw5xM5ifJSG\nDOiubm0YZgjNiyfqzHC0Se0QK9Sr1QeC1zh48Y8QmG+GxDNzIU7pAmZ7NJvRXokVSyu+g+ATqugv\nwkHi/JdghjeJJpAbgfgNiqZd05tVMU2m6qhWN+EXF9QB22/eNeZmqfxLEcGLn0mW2rwRmaWpTkrf\ndmQHjT5No95ihdPesmGPA/M+muvUtn+SUbkYpq0zEb6aNn5E5QXYE2pP2gTrq0TBYyqqowLvAP5L\ntL6s7QFqB/et5Li2CD6fQsSGwAX4OdWNozsmDrCRJaRdLjyr/Z/7f3P/7w78vyLTXHubey1PL5Ne\ngf/3sFY9WvP/Anju/91BgkWWjHBuEs8pgj5BVdNAKjaYGGRp3vD9Nd+ZE38yB7ttciMzb5OgiAVE\n5HmSMyY+L832JUOB504O/cmYF3mTv/0ktYb/Jt+m3WP/5nBfxrP8JR3LZJNjGdl9vHP5i/mWH+Fa\nRk4f4l5+kncZaHxBB/Of8i8jC090MT/Vw3y/g5mP8gc6mb+kj/nRLmZkNNPN/GW8zI9yMu/962Cq\nGgdgti8Le6OPrXH7lFQqV+a0YoAp0+y1T8KDLu59rcegYH6za9b85jCWp1O9eXhcXUxjebh1b77/\nUK3Cf7FsMJEcPsibOAQV2VZihfJsZrqG02y12/2L3njSa51LcdK4cDZr8Qq2Ld+RRqURywMNYbkO\nb0QjOrDjrtV6pfdOrry7EgGmUAAV4WqUaKYMVtMdqBbjoCF+HWSzG9kipkUN3VIbBP6ZLbELmena\nMMv+L7YViD6hUMHgVVe4NnBPIkxRg1KFawiYk0Ehemd0CquHQKAT4Ks5n5M7QE0sGQxSAN6AtVDY\nTDn8VplpVDagm7tz1ArEdg3D8wSh9o6vZvwEAae9AnXRUr8L9IADKtiHEjDDQPUFC4ECekTXUf/g\naiIWQDCAnlQMi9QPfTE2sg5LSaVP6qQyIv/z++jsYng+wVn+aTJujX6YdDt//J0RvfQmJk9/Or0O\n+7+xbv8f5vb/LtLz2X+SuqDGStZcmhv/rzftov/vs/8bR+v2//Fxbv/vIqH9zVL2/0JdoQVG6K2s\nWxq3oAM/AA079R4nQHr25x6A3AOQewByD8Ar8QBE6mnSr/e+fq3mv2/qexdkJhHTjHP9FEP/EWb+\nHmro8SnMDZC2RHqS1BnhQIaBM7zokY+tEQzs/skJ+dS/gOHZwq7rb7LvObbHGPkxI/XryEaVb29A\njU3a8go2IoGRyrwLE3gHZkVth1SoxSYOKn6HNMSq992gK1I7IpX1M3hSr1Yz8huk5mMyNbwLcJyz\n9Fdl6aU3W68w5fZ/bv8/j/03sM0r79rOpJ4//nqtaRf9f4/9f3RUraft/1q9ntv/u0jh+6/0dN3+\n9it//JU//soff+WPv57x8ddj3nbFn3Q904uu6M5z+MzquR5yPYDUY99vvc6HWyPq4E1u4lreJTNg\n+mkPuPC5VY0cJIHS77Ee9b5r66MssvX5V7yl7aVpsrVXVzgeZ0s6u+bN7/RPGOEOIjFeuS2DlKml\nYQXPEdR2bc272B++nBLIcNyW+L8nAhkJqGjP5AXvnQS2EygYccJBsYBrL/wNFgQ2kzXYEVGNzw90\n8/v7AoIPY2L9o86uWw9414XcbnjY5T+5ijD5T66yJMifFGS/9cE3Uk95IPWgZ1He04fm7+vvctbH\nSOJVzGyRCRJ7qjL13uVkgsFqOYmBqvisZQPB2KOW6h/JHk/2KYu9BaQ2KtjUkwm/z/0vYe/ECO+l\nOdj4ViSSYJpU+OIiIBdlZJF8OEWvzSt+3yejzTPXBhvG4W9Ltj/swN1a8HLDe6XBH5+UYhie+XnG\ns6fns/+GUqtzLom6khH/KXn+W6+l7b964zC3/3aS/G4FqyPs1/Dcd4b9+LbwtrC/3+K2IPuwv08I\n5sQsPNg+GopNb8j3qqbBgg7T6D8gK3JGV7BewJJkTskPqj298zBJuqxqiAe/cqF/RzFLlG31N9OQ\nRaq4sHtY+Mi+A3W7TJRBLUCfVQnWBWo7k2sk9t1UvtNMGwuQ0NsCv6romyVgPsZaiEYbN5DQXQ0a\ngILlB7YJbLHgE9cdeCUQlAu/YgjGmmm/LYDOUlyworgxlCXDQO0Q0gUojZkRcZnMQVw+C/xC3duC\nt39l8eN3FUzU8Ozd4w6pwV6A06Zopbqaw/d7MjkdtPFZMn8Z50l6YAM//3VVpjoUe45LwcOTNPz4\nVUjPQ+/fAgCVd2e6/GYnkl7KwNFJtGU3YM5A9yjQh54xSMnlun64JFPYYMyW3hYH74DC5lVNEw8u\nZoJ1+AE5rJDLOZjyl/zTSddojb2P7lzzPjhsPrv0WnjimfeBrAGz7JAZiA4sUN6pHjUddi7M8b7i\nGmFAHlNZ2ZdJZc33QUjJ20h5m6popxTbb0WbG/hcTmFp+Fh6iKT3KByqLmup25ekFKvNwbLuaHrk\n+BDp/Bgj4+UM2l7FrPMXrCjFuVmn4V3iwOz0xQ6vJzq8F7nvIDHQ0JcTGESJAUb26e2MWs4+NyUu\ns/i69AahLt8hqrfc0xLczb30sU0g+RdU90ilBxvFS3LD4xggtG8YyXPYHpDLPhSBVoFBq+B+AVrr\nQa2ZbsHWF4eQ73JZQ9bzkKVxJeyywKZBvEz9jZL6r9weg3+hNPrC/xVRsfZMh3qjeGrC9r7PifcI\nW/KgDFO0KmE2o36AbQhdwKZH9PQxiDvYxcPYpvGn8jDoN4kX9I8MwFRRPasyUEPcb0ZUh1Ft7ikw\n9PaYjKmwxnMXnQKz2Qh7Aw2DOEluSUCVtwVUsAIXhr+osMiDB4ZdejARX2qjM2kwg543XFkDBrzB\nhCNAZVxnh544euvY8iY+BOxqMxwrmULwdeXQU6WhRhgvg8XhMq0cLnmnXKZnO4wHHHbBWjKDDRHv\nS/q2EFfUc3XhAthhOCtkWGXENZIJLVD3u+syOe3D7CylcQnrpMdohq7I5jXGJR99HquMHHE87xNM\nbhhS/DJYWgS4MSSNYB5liuMYkL/0TuifmV7H+e/x2vnvcTU//91Fes7zv3Wt9NKtzVM67aL/7zn/\nPa6vxX9uVBt5/M+dpCj+Z9Z8zQ+B80Pg/BA4PwT+e0QAzU+J/yZRPvMgn/cH+WxHcTwTh8HRWXlt\n++Ft8syWpA9t/erpIJlrITBLPmAksXTkywjiIaE2Hx4Q8+YBATETUS83s5yMiXmzHhMTQ2J6Z8Zl\nwTs8XpXXYl+qhgHqaCXMeUlYNJ3VoLCjwl5jqVHnYzugL5CqWIWugN3Y1HTxMcldsRyr5myv5phW\nAny6HXxqOo6px2rcZIpka1xOIQjKKSRC9QUenzw8Zx6e8y8bnrMGpuqzh9yczljzF1AIAsxu+P/0\n87NF4bw/euYNXsW4eVQkzGScyxcPbpmne1Pu/839v88U/zHjgOilW5undNpF/2/3/9ZqtYzff6pX\nc//vLlL4608Zs/XB3l/4HxmHZ/OKiXecjHisEL6HAWMUbYFwWOVO49xpnDuNc6fxg53GG73GPJ/7\nhg9hoifcw7yIadSKF/HrRYGvGUwYKJEZMaxCob9CF58W3Us6gzmHRs/ngorePxxzbXyi4eVxV2jM\nCRn6OOsCaZQ/xE29LE9oQyCHPtT9P2jUQ0cm2d8naVfmEOYkoNM8T2ZPIPCfYYmWGv55iv+yJyTd\nkhzlQalXLpNsf+Ro848OJRyNW35ziD9w8X5YKOavxNynvTfJcE6GSLf5JzOA0tZssWOecGUUYxPU\n0Yfi5ioRpOdEfZj/k/8Cj+dJnEF97nDkH1blpMdRZyz0OeLvDSUKp7O0MzBkRiCP8jnG6z3M7bhW\nI/Q8xtvPp6Dn+1gfTCP/p39a6OHVZH2qyOQ8al0LT4MYozpIsCSHXpWYUyXbDW/ysyGG3rW5etss\nwl62WBbPxSUsXFr0S1HncfQg5i9OQELvNuooURqMSmXRu0lXwmuOTf5IDj9FMpZEEFDfQvVk2qzU\nEsh5qtAfTOM7i5ZCxGIsV/z+VBrEO4B06Fzmt/Si6CtHiXAqtVoiTkutuhbHJcnD2NQo3genrAQY\nmhxDis0OXrdn/MewgF6zdpQodziWqAmjschZhwXoJ2k4TuEac7ZKDbGaKjiBFaHv9UMpVXRhpX5/\nxruH6u1eQ4c2v8cOM33Nqf1nXYLJwQKccK9gVHv8JP8eVzZh9VD9JMsBWaypiOEDeTcvkneceDkF\nnP5e3N+ailnw/h1faIPLlw3/Bi5fImOrwKbqjyEXc2E6qBMllFg3WM573IW53qZeeF4arvzhblOn\nsJ1XQEQKigiwxkkktglfwT7hlxJCfI65XC3vxCPghQ/qNQZC0YTUGFILKkfwMFdgqZ/BP7qlBDhj\nc2lL0/CBCOVvIyJrjQXtArwxJ7OpAX75VnVCrqMJvc47rAJWwjT4gBia78TDhY+m6REpRYhjbwUN\nPIsICLWDc4ltLQkPL7yWWLJqs6AdWLb1h6Wi3pv7pP9NqklX/coWyA1eM2ghSz/RWbzVHAA2Wjfq\nFoBr5m0a43n8+kG0IfQ4TRLmVQNRSEHbSkANWVqp5XVoJsqWRQ2ldC3CyqGtQ6iGgszAXg5P3mEX\nXLqOD+GEEOJia4e32sNL3N4zS/aFZcXbGe290yK7EjypUf5cC9dGbNGTBcfPPngNfPAFdraEGaUM\nSBCRJ1vyrffgdp00JpCiA6qMZtdXdXlB/tXEXVB2dX+Qk3ffzN999c0cTId3tfqCzxqPuuBjETzW\nyxlN0hi9B3mtPvdy1pBvQpppJQVj7pdE7c/5Ec+rTq/j/CeP//ZSaSfx3/Kzn1ebXkP8t8PaWvz3\nWv0oP//ZRcqK/5Zf/c9PcfJTnPwU54Xjv+UX+/8ZF/tjUeCePQLcA+7+Z3vuM4m/zpcBPNYcCjQZ\nbS7zbQAP/MGjlKQDlPhRSaJgJZ1BeyfB3zYMDT/qW3AfdvOlcyXp2vszLwc2RoqLvRwIYLNixm29\nI8+Z9DlOX4j/64WXi18j3k10t7DKU+K4cZGvxXJ76c34C6TX4f/J7/++VNpZ/If8NwBeZXoF8R/e\nv39/uHb/96iR+392kTbGf8h/BCB3AuVOoNwJlMd/+Oe4iV6nf+iLBX74E+H/s/w7mbeeN0RhQA2a\nCvrPrz1jkNpdxWYICncSmuEpcRn+ytEY8mAJebCEPFjCywRLeAVBElJSia5SvvaYCa/D//d+/f7X\nce7/20V6xvff68GqX7qxeVpLu+j/e/x/x43Dtftf1aP8/tdOUuT/y5iv291/ufcv9/7l3r/c+5d7\n/3Lv3068f0+7GfYS7r92KrAB/hxTaamoqzK0tDNok9LZr/UyDIqoCv7wVAzmRw8k5hoEHA+4eAVQ\nG+5dafWt1YGrREVSIbFn2jpuEoL6ESv7Ada0JzKCz7jdtcmPyG8KCev+SlaK0MUMexmjG6Qcl0nQ\nx3oon/ZLoUn3pLvuniyhf9Jv5P8P6HpQPIOUg5hapVAOWFpTqwxj2FI3TasMWQxl4BGrpwktQsN+\nqerooCO6r0YHHRE+HJSDjkYGBkQqNwQrp/kAJY1GJRWwlZTlesUFOZklGnj3uaNMNCDyOs7RTfAF\nwKUoxZ4rLrXw9Z2QoouUIVBDfUJroVEHSeHOIG68dHQH8igYBaNgFIyCUYAKAHzeGd4AyAAA\n"], "title": "Bringing Trimmed Serendipity Methods to Computational Practice in Firedrake"}

**Comment by dham** [comment]
The ufl hash above is does not appear to be in the repository. Are you sure this has been pushed to GitHub?

**Comment by Justincrum** [comment]
As far as I know, yes.  What I've done is `git push origin trimmedSerendipity` on fiat, FInAT, ufl, and tsfc.  Those should be the only 4 branches that I've changed.  I went through each of those 4 branches just now and made sure, and I got the `Everything up-to-date` message from git. 

Is there something else I should go through and do?

**Comment by Justincrum** [comment]
Hi David, here's the link for the UFL hash, it is in the trimmedSerendipity branch for the ufl repo.

https://github.com/firedrakeproject/ufl/commit/0449576c984a06052ec4b00034b3f16072029005

**Comment by dham** [comment]
Sorry, my bad I must have failed to update. However now I seem to have an issue with COFFEE. You have commit 8fc9795c342210d08fb1a52517009bebe1282094 but I can't find that locally or by searching the repo on GitHub.

**Comment by Justincrum** [comment]
When you have time, try it again and let me know if I fixed it?  I had something wrong with a couple of directories.

I did get a warning when I ran firedrake-zenodo though that said:

`Failed to retrieve git hash for optional component 'petsc4py', continuing without it
Failed to retrieve git hash for optional component 'slepc4py', continuing without it
`

I'm not sure if that's an issue or not, but I do make use of slepc/petsc in some of the test codes.

**Comment by wence-** [comment]
> Failed to retrieve git hash for optional component 'petsc4py', continuing without it
> Failed to retrieve git hash for optional component 'slepc4py', continuing without it

These warnings are fine, petsc4py and slepc4py are now in slepc/petsc respectively.

**Comment by wence-** [comment]
Tag: `Firedrake_20210419.2`
Bibtex:

```
@misc{zenodo/Firedrake-20210419.2,
 key   = {zenodo/Firedrake-20210419.2},
 title = {{Software used in 'Bringing Trimmed Serendipity Methods to Computational Practice in Firedrake'}},
 year  = {2021},
 month = {apr},
 doi   = {10.5281/zenodo.4701708},
 url   = {https://doi.org/10.5281/zenodo.4701708},
}
```

Thanks.
