### ISSUE TITLE
Problems while installing firedrake on Ubuntu

### ISSUE THREAD

**Issue by sharma-kk** [firedrakeproject/firedrake#2022]
Hi, 
[firedrake-install.log.txt](https://github.com/firedrakeproject/firedrake/files/6242659/firedrake-install.log.txt)

I am a new user of Ubuntu. I tried installing firedrake by following the instructions from their website. But after running the install script, i am not able to move on to the next installation steps. 
I have attached the log.

Kindly help,
Kamal

**Comment by dham** [comment]
That log file appears to be from a Firedrake install that was run in 2017 using Python 2.7. It's definitely not the log file from a recent install. The log file for your current installation will be in the folder from which you ran firedrake-install.

**Comment by sharma-kk** [comment]
Thanks David for the reply. 

Here is what i did:
1. I first ran curl -0 https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install on my terminal.
2. Then when i entered python3 firedrake-install, 
    It shows python3: can't open file 'firedrake-install': [Errno 2] No such file or directory.

Am i doing something wrong ?

**Comment by dham** [comment]
I'm afraid you haven't provided enough information to tell what is wrong here. Please show the output of the `curl` command, and run `ls` to verify that `firedrake-install` is present in the current directory.

**Comment by sharma-kk** [comment]
I have attached the output. After running the curl command, i don't see firedrake-install in my directory. 
[curl command output.txt](https://github.com/firedrakeproject/firedrake/files/6245223/curl.command.output.txt)

**Comment by sharma-kk** [comment]
Hey David, 
I think it's working now. I was making some silly mistakes. Thank again.
