### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by salazardetroya** [firedrakeproject/firedrake#2025]
Hello, I'd like to have a zenodo release for

{"firedrake": "306e7c92ac67c11518c8a801abbafe43859f82ec", "PyOP2": "d0cc348d4af759e16e01dfda8948485436b16c40", "tsfc": "fe07cb5563c7b1ef38b5b4f01b52275e32ed3ee8", "COFFEE": "70c1e66a4e4e39d3bf75274505a16901af110751", "ufl": "057c5f6f06687c401dab7683c2406a0e91901c9c", "FInAT": "2dabc83d321e6cd2fded033f0002325afe58b66a", "fiat": "0439689f364347a0cec4e8129abf88570380e4ed", "petsc": "a033d6a5187357ab3a4359400592d1a6798cbcf5", "loopy": "7665f16acfd34cde6cb420425f2b4089af1b528c", "metarelease_info_file": null, "title": "Another source of mesh dependence in topology optimization"}

Thanks
Miguel

**Comment by wence-** [comment]
Tag: `Firedrake_20210411.0`

Bibtex:
```
@misc{zenodo/Firedrake-20210411.0,
 key   = {zenodo/Firedrake-20210411.0},
 title = {{Software used in 'Another source of mesh dependence in topology optimization'}},
 year  = {2021},
 month = {apr},
 doi   = {10.5281/zenodo.4679405},
 url   = {https://doi.org/10.5281/zenodo.4679405},
}
```

Thanks!
