### ISSUE TITLE
Zenodo please

### ISSUE THREAD

**Issue by JDBetteridge** [firedrakeproject/firedrake#2027]
For our paper "Code generation for productive portable scalable finite element simulation in Firedrake"
@dham
```json
{"firedrake": "33ec106cf7a50aead0efcccbcf993617bb498c2d", "PyOP2": "2c568ea11a36f81a9603d278bbb1f1906bd7dd71", "tsfc": "b693a096f3f294fdd66fe844514e6794883da704", "COFFEE": "70c1e66a4e4e39d3bf75274505a16901af110751", "ufl": "057c5f6f06687c401dab7683c2406a0e91901c9c", "FInAT": "34b3da492ed86286e1518f481252a2afca81acfb", "fiat": "42ceef358d4c1273a8ef83dac8169d7a3a54f968", "petsc": "e85aaad7c1287e684d6072a4b7567aca31c0daee", "loopy": "cbbdc7ebb6298859e2238ea207474b49a3706f2e", "metarelease_info_file": ["simulations_doi.txt", "UG9pc3NvbiBzaW11bGF0aW9uIHNjcmlwdHM6IFshW0RPSV0oaHR0cHM6Ly96ZW5vZG8ub3JnL2Jh\nZGdlLzM1NzY0MTcyOS5zdmcpXShodHRwczovL3plbm9kby5vcmcvYmFkZ2UvbGF0ZXN0ZG9pLzM1\nNzY0MTcyOSkKCkxEQyBzaW11bGF0aW9uIHNjcmlwdHM6IFshW0RPSV0oaHR0cHM6Ly96ZW5vZG8u\nb3JnL2JhZGdlLzM1NzY0MjI5Mi5zdmcpXShodHRwczovL3plbm9kby5vcmcvYmFkZ2UvbGF0ZXN0\nZG9pLzM1NzY0MjI5MikK\n"], "title": "Code generation for productive portable scalable finite element simulation in Firedrake"}
```

**Comment by wence-** [comment]
github3.exceptions.UnprocessableEntity: 422 No commit found for SHA: 2c568ea11a36f81a9603d278bbb1f1906bd7dd71

**Comment by wence-** [comment]
Have you pushed the pyop2 stuff anywhere?

**Comment by JDBetteridge** [comment]
I thought I'd switched back to upstream master, I had been using a fork to try some things out, I'll try again

**Comment by wence-** [comment]
You should archive the version you used to run the simulations...

**Comment by JDBetteridge** [comment]
Second attempt: I'm using [this](https://github.com/JDBetteridge/PyOP2/commit/f1aa96d191f650e41e4e3c3d57bc0e938b4cbb60) commit from my fork of PyOP2, is there a specific way I should tag this for release, or should I add the PyOP2 DOI to the supplementary file?

```json
{"firedrake": "33ec106cf7a50aead0efcccbcf993617bb498c2d", "PyOP2": "f1aa96d191f650e41e4e3c3d57bc0e938b4cbb60", "tsfc": "b693a096f3f294fdd66fe844514e6794883da704", "COFFEE": "70c1e66a4e4e39d3bf75274505a16901af110751", "ufl": "057c5f6f06687c401dab7683c2406a0e91901c9c", "FInAT": "34b3da492ed86286e1518f481252a2afca81acfb", "fiat": "42ceef358d4c1273a8ef83dac8169d7a3a54f968", "petsc": "e85aaad7c1287e684d6072a4b7567aca31c0daee", "loopy": "cbbdc7ebb6298859e2238ea207474b49a3706f2e", "metarelease_info_file": ["simulations_doi.txt", "UG9pc3NvbiBzaW11bGF0aW9uIHNjcmlwdHM6IFshW0RPSV0oaHR0cHM6Ly96ZW5vZG8ub3JnL2Jh\nZGdlLzM1NzY0MTcyOS5zdmcpXShodHRwczovL3plbm9kby5vcmcvYmFkZ2UvbGF0ZXN0ZG9pLzM1\nNzY0MTcyOSkKCkxEQyBzaW11bGF0aW9uIHNjcmlwdHM6IFshW0RPSV0oaHR0cHM6Ly96ZW5vZG8u\nb3JnL2JhZGdlLzM1NzY0MjI5Mi5zdmcpXShodHRwczovL3plbm9kby5vcmcvYmFkZ2UvbGF0ZXN0\nZG9pLzM1NzY0MjI5MikK\n"], "title": "Code generation for productive portable scalable finite element simulation in Firedrake"}
```

**Comment by JDBetteridge** [comment]
[![DOI](https://zenodo.org/badge/257616993.svg)](https://zenodo.org/badge/latestdoi/257616993)

**Comment by dham** [comment]
Don't do it that way. Push your branch to the firedrake repository and let firedrake-zenodo pick it up.

**Comment by JDBetteridge** [comment]
Okay, commit `f1aa96d191f650e41e4e3c3d57bc0e938b4cbb60` now exists in a branch of the official PyOP2 repository (rather than my fork)

**Comment by wence-** [comment]
That's great, but it's not the commit you asked us to archive.

**Comment by wence-** [comment]
(At least for the first json file you provided). So which code did you use to run the experiments?

**Comment by wence-** [comment]
> I'm using this commit from my fork of PyOP2

I don't believe this statement, because that commit was made one hour ago, and all of the results in the paper existed at least yesterday.

**Comment by JDBetteridge** [comment]
That branch has been force updated to `2c568ea11a36f81a9603d278bbb1f1906bd7dd71`:

Merge: d0cc348d fa3a6880
Author: JDBetteridge <J.Betteridge@imperial.ac.uk>
Date:   Tue Feb 9 23:04:09 2021 +0000

**Comment by JDBetteridge** [comment]
That's the commit I originally posted

**Comment by wence-** [comment]
Thanks!

Tag: `Firedrake_20210415.0`

Bibtex:

```
@misc{zenodo/Firedrake-20210415.0,
 key   = {zenodo/Firedrake-20210415.0},
 title = {{Software used in 'Code generation for productive portable scalable finite element simulation in Firedrake'}},
 year  = {2021},
 month = {apr},
 doi   = {10.5281/zenodo.4694370},
 url   = {https://doi.org/10.5281/zenodo.4694370},
}
```
