### ISSUE TITLE
Installing on Apple silicon MacBook Pro

### ISSUE THREAD

**Issue by klaatujk** [firedrakeproject/firedrake#2029]
I am now trying to install firedrake for Thetis on Apple silicon Macbook pro.

But after I got the message "Pip installing VTK for Python 3.9 to venv",
installing is terminated.

Attached is the log file.

Does anybody have any suggestions?

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6329588/firedrake-install.log)

**Comment by JDBetteridge** [comment]
This was an error in the install script and was fixed in [#2048](https://github.com/firedrakeproject/firedrake/pull/2042).

Please download the latest version of the install script and try again.

**Comment by klaatujk** [comment]
Thanks a lot.
But I have paused compiling on Mac because compiling is stopped around mpich.

**Comment by JDBetteridge** [comment]
If you post the new firedrake-install.log and PETSc's configure.log, we can try and find the issue

**Comment by klaatujk** [comment]
I uploaded the firedrake-install.log and have no idea how I can solve errors.

I used the command of " python3 firedrake-install --no-package-manager.

I am really happy with your help and comment on it.




[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6422200/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/6422202/configure.log)

**Comment by JDBetteridge** [comment]
Your issue seems related to this issue:
https://github.com/Homebrew/homebrew-core/issues/73949
You could try updating gcc/gfortran through homebrew to see if this has been fixed upstream.

**Comment by klaatujk** [comment]
Again, I gave up installing Firedrake on M1 Macbook.
Thanks, guys for guiding me.

**Comment by wence-** [comment]
Thanks. Presently none of the developers has an M1 system, so we're reliant on bug reports like this (thanks for your input!). We certainly intend to support M1 (and related) in the future.

**Comment by klaatujk** [comment]
Based on my googling, I realized installing is "impossible" at the moment because an M1 system is not supported by other developers as well.
So I quitted it.

Hopley, support M1 in the near future.
