### ISSUE TITLE
firedrake install fail to prompt petsc

### ISSUE THREAD

**Issue by valentinelun** [firedrakeproject/firedrake#2039]
Hello,
  I had some problem with firedrake installation. It seems like the script failed to prompt the petsc installer to move forward the installation. I check the install.log and the program stopped at the status 
"DEBUG  Running command 'git clone -q --recursive https://github.com/firedrakeproject/petsc.git'"
then no further information.

I also check the /src/petsc in the root of my ubutuntu, it only has one folder called ".git", hope you guys can help me with some answers, thank you very much!

<img width="663" alt="Capture" src="https://user-images.githubusercontent.com/83060267/115835115-39269e00-a416-11eb-8b62-09879cc172a1.PNG">
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6363523/firedrake-install.log)

**Comment by danshapero** [comment]
This is a little silly, but is it possible your internet connection went out while cloning PETSc? If you delete the `firedrake` folder and try again do you get the same result?

**Comment by ReubenHill** [comment]
Just to back up Dan's suggestion, I have definitely had problems with my internet connection causing an install failure!

**Comment by valentinelun** [comment]
Hi guys,
  Thank you for the suggestion, but I've been trying for 2 days and the same problem remained before I asked for help in this forum. 
  I did remove firedrake folder and reinstall many times, same. so I doubted it's because of the internet connection. Is that any way that I could monitor the process of the prompting? Thank you guys.

**Comment by valentinelun** [comment]
It's solved, the problem was on WSL 1, I recommend WSL 2 if next time anyone comes with the same problem of cloning but it's not a very good news for windows 10 home users for getting WSL 2.
