### ISSUE TITLE
Firedrake install problem

### ISSUE THREAD

**Issue by sv2518** [firedrakeproject/firedrake#2045]
Hi. I have tried to install firedrake complex with clang version 12.0.0 and Python version 3.9.4. I'm on macOS Catalina 10.15.7. I have brew updated to 3.1.4, brew uninstalled and installed python3, brew unlinked mpich, brew unlinked open-mpi. 

Here is the install log 
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6390216/firedrake-install.log)
 And the petsc log
[configure.log](https://github.com/firedrakeproject/firedrake/files/6390220/configure.log)

It looks like it fails on make install on MPICH. Does anyone have an idea how I can get this to work?

**Comment by JDBetteridge** [comment]
Does the issue go away if you 
```bash
export PETSC_CONFIGURE_OPTIONS="--with-x=0"
```
before installing?

**Comment by sv2518** [comment]
Ok done, still failing, but with a new error

[configure.log](https://github.com/firedrakeproject/firedrake/files/6391672/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6391673/firedrake-install.log)

**Comment by dham** [comment]
I think I don't understand that configure error

**Comment by wence-** [comment]
Can we strip this back to just getting `./configure --download-mpich` to fail inside the petsc source tree? Then we could upstream the bug :)

**Comment by dham** [comment]
It transpires that @sv2518 ran out of space. For me, @JDBetteridge's fix looks like it might have worked. I'm not sure if that makes it an upstream bug or not.

**Comment by JDBetteridge** [comment]
I think this is working as intended, if PETSc configure finds an X11 it will try to use it and passes it to all external packages that want it. I don't really understand enough about X11 on a Mac to know what should happen in this case.

Perhaps we should add `--with-x=0` to the PETSc config options if we're on a Mac if this is going to become a common issue?

**Comment by dham** [comment]
Do we need x from PETSc? If not we should switch it off for all platforms.

**Comment by wence-** [comment]
Jack's comment suggests that petsc does find X but doesn't pass it correctly to mpich?

Having X available in PETSc is kind of nice because you can draw matrices with it (I like it, that might be niche).

**Comment by dham** [comment]
OK. Let's just switch it off for Mac.

**Comment by sv2518** [comment]
Ja, Jack's fix worked for me as well. Thanks!
