### ISSUE TITLE
Error in implementing DG method for elliptic problem

### ISSUE THREAD

**Issue by dbojanjac** [firedrakeproject/firedrake#2064]
While implementing SIP-DG from Quarteroni's book (Numerical models for Differential problems, page 270, eq. 11.6)
<img width="1102" alt="Screenshot 2021-05-10 at 21 38 57" src="https://user-images.githubusercontent.com/30177723/117715235-498d9580-b1d8-11eb-933f-00e34c5e81d8.png">

```
W = FunctionSpace(mesh, "DG", 1)
n = FacetNormal(mesh)
h = CellSize(V.mesh());    h_avg = avg(h)
u_DG = TrialFunction(W);  v_DG = TestFunction(W)

a_vol = dot(grad(u_DG),grad(v_DG))*dx

a_in = - dot(jump(v_DG,n),avg(grad(u_DG)))*dS \
        - dot(jump(u_DG,n),avg(grad(v_DG)))*dS \
        + (gamma/h_avg) * (dot(jump(u_DG,n),jump(v_DG,n)))*dS

a_out = - v_DG*dot(grad(u_DG),n)*ds \
        - u_DG*dot(grad(v_DG),n)*ds \
        + (gamma/h_avg)*u_DG * v_DG*ds

a_DG = a_vol + a_in + a_out
```

with bold part i obtain
<img width="1267" alt="Screenshot 2021-05-10 at 21 42 50" src="https://user-images.githubusercontent.com/30177723/117715564-ba34b200-b1d8-11eb-98d3-4e1c9de97f80.png">

If i remove + (gamma/h_avg)*u_DG * v_DG*ds everything works fine. But this part is directly from the method quoted above. Where do I make a mistake using + (gamma/h_avg)*u_DG * v_DG*ds in the definition of weak formulation?

**Comment by wence-** [comment]
> If you include the line `PETSc.Sys.popErrorHandler()` at the beginning of your script,

To get this available you'll need to `from firedrake.petsc import PETSc`

**Comment by wence-** [comment]
The snippet you posted seems incomplete, since it does not define `gamma`, and uses `CellSize(V.mesh())`, but your function space is `W`. Can you provide a complete failing example?

**Comment by dbojanjac** [comment]
Comment about h_avg solve everything. Thnx.
