### ISSUE TITLE
Determinant in Firedrake

### ISSUE THREAD

**Issue by valentinelun** [firedrakeproject/firedrake#2067]
Hi guys,
  May I ask a question about how to take the determinant of a tensor in Firedrake?
  
  For example, I define a vector space V and a function u in this vector space using V = VectorFunctionSpace(mesh,"CG", 1) and u= Function(V). 

  Afterward after I interpolate some expression into the function u and take gradient operation of it, grad(u), then how can I calculate the determinant of this tensor grad(u)?

  Hope you can help me with an answer, thanks a lot!

**Comment by danshapero** [comment]
@valentinelun I'm closing this issue since it's a month old now, feel free to reopen if David's suggestion isn't what you needed.
