### ISSUE TITLE
Equivalent to FEniCS XDMFFile function? 

### ISSUE THREAD

**Issue by mwelland** [firedrakeproject/firedrake#2073]
Hi, wondering if there is an equivalent in Firedrake to the FEniCS XDMFFile function? (Writes visualization data to an xdmf + h5 file)? 

I see work extending the checkpointing dump but I not sure if this will provide the same tools e.g.: reusing the mesh between timesteps and variables. 

Thanks - I dislike the multitude of vtu files created with a pvd (1 vtu / time / core) with larger files.

**Comment by wence-** [comment]
The goal is to get to the XDMFFile idea. W'ere trying to get the checkpoint to work properly (this will reuse mesh topology etc...)

**Comment by mwelland** [comment]
Great thanks, I'll keep my eyes open for it.
