### ISSUE TITLE
Is there some documents on the implementation of isoparametric finite elements in Firedrake

### ISSUE THREAD

**Issue by lrtfm** [firedrakeproject/firedrake#2098]
### Questions
Can someone tell me whether the isoparametric finite element in Firedrake is optimal?

1. If it is optimal, is this identical to the optimal isoparametric finite elements developed by M. Lenior[1]? 
2. If it's not, are there any documents on the implementation?

### Reference 
[1] M. Lenior, Optimal Isoparametric Finite Elements and Error Estimates For Domains Involving Curved Boundaries. SIAM. J. Numer. Anal. 23(3). 1986. pp 562--580.

**Comment by wence-** [comment]
I'm not sure exactly what optimal is in this context, but I can describe what the Firedrake implementation does.

The coordinate mapping is represented as a normal finite element field. Normally this will be piecewise polynomial (though sometimes it is discontinuous). "Standard" is that this field is piecewise linear. However, it can be some higher order approximation to the geometry. Everything else then proceeds as normal, except that geometric terms are computed at each quadrature point (rather than once per triangle [say]).

Does that help to explain things?

**Comment by wraith1995** [comment]
I've actually read this paper a while back as part of an REU project; IIRC optimal here means that as you refine your curved mesh you don't reduce (or eliminate) the order of the convergence due to your curved mesh being a poor approximation of the domain or due to your curved mesh breaking some quasi-uniformity condition. In other words, the order of convergence should be the same as it would be on a nice polygonal domain.

There are two questions here:
 1. Does Firedrake support the use of curve elements so that you could implement that paper? Yes. See above.
 2. Does Firedrake implement a (good) method for building and refining those curved elements given some representation of the geometry? There is [this merged pull](https://github.com/firedrakeproject/firedrake/pull/1448), which includes functionality to build a curved mesh given an OpenCascade geometry. However, I don't know what algorithm it uses or the relation between that algorithm and the paper. You can look at the code and maybe @pefarrell can comment.

**Comment by lrtfm** [comment]
@wence- The meaning of `optimal` is what @wraith1995 has explained above. 

### Idea on implement the paper of Lenior

1. Combining your answers, I think I can handle the curve boundary manually through coordinate mapping like this.
Is this what you mean `Yes` for the first question? @wraith1995 

```python
order = 2
mesh = Mesh('mymesh.msh')   #  `mymesh.msh` is first order triangulation of the domain.

V = VectorFunctionSpace(mesh, 'CG', order)
coords_new = Function(V)

coords_new.interpolate(mesh.coordinates)                       # 
coords_new = apply_Lenior_procedure(coords_new)                # Modify some coordinates of the boundary points
mesh_new = mesh(coords_new)                                    #
```

Here, the routine `apply_Lenior_procedure` will implement the procedure that Lenior introduced, i.e. construct the map for reference element to physical element by the exact boundary information, and modify the coordinates filed by this map.


2. I will read the code in `https://github.com/firedrakeproject/firedrake/pull/1448` to see some details. Thanks for the advice.

### Other question on Firedrake
By the way, I have another two questions on Firedrake, @wence-. Thanks in advance.
1. I am wondering in which case the coordinating mapping will be discontinuous?
2. Can we load a high-order mesh file of `gmsh` now? I notice that the issue [how to import a 2nd order mesh?](https://github.com/firedrakeproject/firedrake/issues/982) is still open. It seems that `PETSc` has supported exporting high order `gmsh` file. In Firedrake, when I load a high-order `gmsh` file, it goes well before I checked the coordinates of the mesh.
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-0dccd61f8d28> in <module>
----> 1 mesh.coordinates

~/firedrake/src/firedrake/firedrake/mesh.py in __getattr__(self, name)
   1569 
   1570     def __getattr__(self, name):
-> 1571         val = getattr(self._topology, name)
   1572         setattr(self, name, val)
   1573         return val

AttributeError: 'MeshTopology' object has no attribute 'coordinates'
```
My mesh file is here:
[dumball-0.1-new.msh.zip](https://github.com/firedrakeproject/firedrake/files/6581470/dumball-0.1-new.msh.zip)

**Comment by wence-** [comment]
> I am wondering in which case the coordinating mapping will be discontinuous?

The way we implement periodic domains is to have a periodic topology with a coordinate field with a jump in it.

> Can we load a high-order mesh file of gmsh now? I notice that the issue how to import a 2nd order mesh? is still open. It seems that PETSc has supported exporting high order gmsh file. In Firedrake, when I load a high-order gmsh file, it goes well before I checked the coordinates of the mesh.

Not yet sorry! I think the major issue is converting the coordinate field from the order that petsc reads it in to the order that firedrake needs. @ksagiyam is actually working on this exact problem for the purposes of checkpointing, so it's possible that his work will enable this.

**Comment by wence-** [comment]
> I've actually read this paper a while back as part of an REU project; IIRC optimal here means that as you refine your curved mesh you don't reduce (or eliminate) the order of the convergence due to your curved mesh being a poor approximation of the domain or due to your curved mesh breaking some quasi-uniformity condition. In other words, the order of convergence should be the same as it would be on a nice polygonal domain.
> 
> There are two questions here:
> 
> 1. Does Firedrake support the use of curve elements so that you could implement that paper? Yes. See above.
> 2. Does Firedrake implement a (good) method for building and refining those curved elements given some representation of the geometry? There is [this merged pull](https://github.com/firedrakeproject/firedrake/pull/1448), which includes functionality to build a curved mesh given an OpenCascade geometry. However, I don't know what algorithm it uses or the relation between that algorithm and the paper. You can look at the code and maybe @pefarrell can comment.

I think this just projects any point on the surface of the mesh to the nearest point that is on the CAD.

**Comment by wence-** [comment]
> Here, the routine `apply_Lenior_procedure` will implement the procedure that Lenior introduced, i.e. construct the map for reference element to physical element by the exact boundary information, and modify the coordinates filed by this map.

Your sketch code here looks correct, just `new_mesh = Mesh(new_coords)` (not `mesh`).

**Comment by lrtfm** [comment]
> Your sketch code here looks correct, just `new_mesh = Mesh(new_coords)` (not `mesh`).

Thanks for pointing out that.

**Comment by wraith1995** [comment]
@lrtfm Yes, you understood me correctly. I think an annoying part here will be accessing and using the accurate representation of the boundary. Hopefully the pull I linked can help there even if the algorithm is rather far from the paper.

**Comment by lrtfm** [comment]
> I think this just projects any point on the surface of the mesh to the nearest point that is on the CAD.

I have a look at the code. Yes, it just projects the point to the nearest point.

**Comment by lrtfm** [comment]
Is there an easy way to get the barycentric coordinate of the local `dofs` in `CG` space?

I can only find the local `dofs` by the following code
```
order = 3
V_coords = VectorFunctionSpace(mesh, 'CG', order)
V_coords.finat_element.entity_dofs()
```

**Comment by wence-** [comment]
To obtain the locations of the nodes in reference element cartesian coordinates, you can do:

```python
element = V_coords.finat_element.fiat_equivalent
locations = []
# The order here is the numbering in entity_dofs
for dual in element.dual_basis():
    loc, = dual.get_point_dict().keys()
    locations.append(loc)

locations = numpy.asarray(locations)

# Now we can convert to barycentric coordinates.
cell = element.ref_el
vertices = numpy.asarray(cell.get_vertices())
bary2cart = numpy.vstack([vertices.T, numpy.ones(len(vertices))])
cart2bary = numpy.linalg.inv(bary2cart)

bary_locs = numpy.hstack([locations, numpy.ones((len(locations), 1))]).dot(cart2bary.T)
```

**Comment by lrtfm** [comment]
Thanks @wence-
