### ISSUE TITLE
Pytest fail on CentOS

### ISSUE THREAD

**Issue by Ub3rJosh** [firedrakeproject/firedrake#2102]
The installation seemed to work fine, but when running the regressions test, I get the error "bash: pytest: command not found". As a workaround I tried to use "make alltest" and that gave me "make: *** No rule to make target `alltest'.  Stop.". Any help is greatly appreciated!

**Comment by wence-** [comment]
Assuming the install was successful, did you activate the virtual environment before running pytest? Suppose that you are in directory `foo` and you successfully ran `firedrake-install`, before you can use things, you'll need to do `source firedrake/bin/activate` (you need to do this every time you get a new shell).

Then to run the test suite you need to be in the correct directory:

```
$ cd firedrake/src/firedrake
$ pytest tests
```

**Comment by Ub3rJosh** [comment]
No errors while installing firedrake, and I am in the virtual environment but it is still not recognizing pytest and gives the same error as above.

**Comment by wence-** [comment]
Can you upload `firedrake-install.log` so we can check? In addition, in the activated virtual environment, can you please show the output of `which python`, `python --version`, `python -c "import sys; print(sys.path)"`, and `python -c "import firedrake"`?

**Comment by Ub3rJosh** [comment]
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6600104/firedrake-install.log)

When running "which python" I get:
(firedrake) Predator[100] jmm2014$ which python
python is /home/jmm2014/firedrake/bin/python

and for "python --version" I get:
(firedrake) Predator[101] jmm2014$ python --version
Python 3.7.5

for "python -c "import sys; print(sys.path)"" I get:
(firedrake) Predator[102] jmm2014$ python -c "import sys; print(sys.path)"
['', '/apps/python-3.7.5/lib/python37.zip', '/apps/python-3.7.5/lib/python3.7', '/apps/python-3.7.5/lib/python3.7/lib-dynload', '/home/jmm2014/firedrake/lib/python3.7/site-packages']

and for "python -c "import firedrake"" I get:
(firedrake) Predator[103] jmm2014$ python -c "import firedrake"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jmm2014/firedrake/src/firedrake/firedrake/__init__.py", line 19, in <module>
    import firedrake.petsc as petsc
  File "/home/jmm2014/firedrake/src/firedrake/firedrake/petsc.py", line 3, in <module>
    import petsc4py
ModuleNotFoundError: No module named 'petsc4py'

**Comment by wence-** [comment]
Thanks, it looks like from your install log that this didn't run successfully, although somehow we didn't complain which has misled you. The final lines from the log are:

```
2021-06-04 10:11:12,382 DEBUG  


2021-06-04 10:11:12,383 DEBUG  Running command 'apt-get --version'
2021-06-04 10:11:12,398 INFO   

Install log saved in /home/jmm2014/firedrake-install.log

```

I note that you're on CentOS, so I would expect `apt-get` to fail. We don't have a fully automated pathway on rpm-based systems but it will work. You'll need to _at least_ run `firedrake-install --no-package-manager`. You'll also need a number of OS-provided packages (see the list here https://www.firedrakeproject.org/download.html#system-requirements).

Thanks

**Comment by Ub3rJosh** [comment]
We had attempted to install those already, is there a way to tell if they are hooked up correctly?

**Comment by wence-** [comment]
Sorry for the delayed response. I think if you run `firedrake-install --no-package-manager` we will complain if we don't have all the necessary build prerequisites

**Comment by snowbird294** [comment]
Anyone ever come to a github to ask a question and find the person you're helping is asking in the same vein?

Anyway, I'm a sys-admin helping Josh, but we are in a tightly managed environment.

Installation was successful with this:
`env -u PYTHONPATH -u CC -u CXX python3 firedrake-install --disable-ssh --no-package-manager`

Where we explicitly set some environment variables that are relevant to the installation.

Hope that helps some folks who live in the redhat realm.

Now an extension: How do we set the firedrake/.cache directory? Our environment is intentionally configured such that software is run from a read-only filesystem. If I try pytests /path/to/tests/regression/ -k "stokes_mini" or the others, it tries to write back to the software installation directory, which is not a favorable behavior in a multi-user shared-software environment (cluster computing).

**Comment by wence-** [comment]
> Now an extension: How do we set the firedrake/.cache directory?

Set the two environment variables:

```
PYOP2_CACHE_DIR
FIREDRAKE_TSFC_KERNEL_CACHE_DIR
```

Aside: there should be a single thing that controls this.

**Comment by connorjward** [comment]
> > Now an extension: How do we set the firedrake/.cache directory?
> 
> 
> 
> Set the two environment variables:
> 
> 
> 
> ```
> 
> PYOP2_CACHE_DIR
> 
> FIREDRAKE_TSFC_KERNEL_CACHE_DIR
> 
> ```
> 
> 
> 
> Aside: there should be a single thing that controls this.

I think we already do this. `firedrake-install` accepts a `--cache-dir` option.

**Comment by wence-** [comment]
> I think we already do this. `firedrake-install` accepts a `--cache-dir` option.

Doesn't work for the multi-user case I think (which is what we have here).

**Comment by snowbird294** [comment]
Wence, that worked like a charm, thanks much. Aside from the Aside, this issue can be marked resolved

**Comment by wence-** [comment]
Cool, I'll close.
