### ISSUE TITLE
Using Docker to Install Firedrake

### ISSUE THREAD

**Issue by Ub3rJosh** [firedrakeproject/firedrake#2103]
I was trying to install firedrake on my windows machine using Docker and was running into some errors. I was trying to follow Running Firedrake through Docker #1868 but was having trouble when running "docker run --interactive --tty firedrakeproject/firedrake:latest" and getting that I needed to run the command as an administrator. 

Basically, the question is, on Windows 10, how do you access firedrake through Docker.

**Comment by danshapero** [comment]
Unfortunately, running Docker effectively requires admin privileges. There's an explanation for why in [this SO question](https://stackoverflow.com/questions/51218233/docker-why-do-i-need-to-sudo-in-ubuntu). Note that you would have the same issue in Ubuntu or another Linux distro, it's not just Windows. So this is a Docker issue first and a Windows issue second.

On Linux, you have to make your user account a member of the `docker` group. On Windows, I think that you can make your user a member of the `docker-users` group, as detailed in [this other SO question](https://stackoverflow.com/questions/58663920/can-i-run-docker-desktop-on-windows-without-admin-privileges). It's likely that adding your account to that group will also require admin privileges, but after doing so you'll never have to be bothered about it again.

**Comment by danshapero** [comment]
@Ub3rJosh were you able to make this work?

**Comment by Ub3rJosh** [comment]
@danshapero I actually ended up using ubuntu and getting rid of docker. The firedrake install process went much more smoothly on the ubuntu subsystem.

**Comment by danshapero** [comment]
Ok, you can close the issue if you've resolved the problem. If this does pop up again later you can always reopen it.
