### ISSUE TITLE
Zenodo Release 

### ISSUE THREAD

**Issue by indiamai** [firedrakeproject/firedrake#2106]
Hi,

Could a Zenodo release please be created for this set of versions? 

[firedrake.txt](https://github.com/firedrakeproject/firedrake/files/6629844/firedrake.txt)

**Comment by wence-** [comment]
I've kicked this off. Zenodo is being quite slow processing some of the archives.

**Comment by wence-** [comment]
Looks like the zenodo processing might be borked (https://github.com/zenodo/zenodo/issues/2181)

**Comment by wence-** [comment]
Zenodo finally unwedged, so here we are.

Tag is `Firedrake_20210610.0`

DOI is `10.5281/zenodo.4986160`

Zenodo URL is https://zenodo.org/record/4986160

BibTeX
```
@misc{zenodo/Firedrake-20210610.0,
 key   = {zenodo/Firedrake-20210610.0},
 title = {{Software used in `Symbolic and Numerical Representation of Dual Spaces in the Unified Form Language and Firedrake'}},
 year  = {2021},
 month = {jun},
 doi   = {10.5281/zenodo.4986160},
 url   = {https://doi.org/10.5281/zenodo.4986160},
}
```
