### ISSUE TITLE
'Segmentation fault'  when assembling linear form with complex UFL expression for high order mesh

### ISSUE THREAD

**Issue by lrtfm** [firedrakeproject/firedrake#2107]
The following complex UFL expression (`source_term1` and `source_term2`) will result in 'Segmentation fault'.
For linear mesh and space, everything is ok. As I set the `order` to 2, the fault raise. See the code below.
Why this happened? The mesh file is attached below.

```python
from firedrake import *

def omega(t):              # \omega(t) = \exp^{-t/10}
    return exp(-t/10)

def phi(x, y, z):
    return (y**2+z**2)/(0.7*x**2 + 0.3)**2 + x**2

def g(x, y, z, t):
    return omega(t)*phi(x, y, z) - 1

def source_term0(x, y, z, t):
    return g(x, y, z, t)*div(grad(phi(x, y, z)))


def source_term1(x, y, z, t):
    return \
      - (                                               \
            6*omega(t)**2*dot(grad(phi(x, y, z)), grad(phi(x, y, z)))   \
          + 3*g(x, y, z, t)*omega(t)*div(grad(phi(x, y, z)))     \
        )

def source_term2(x, y, z, t):
    return \
      - g(x, y, z, t)*(                                               \
            6*omega(t)**2*dot(grad(phi(x, y, z)), grad(phi(x, y, z)))   \
          + 3*g(x, y, z, t)*omega(t)*div(grad(phi(x, y, z)))     \
        )


def test_ufl_expression(order=2):
    mesh = Mesh('dumball-maxh0.125-new.msh')

    V_coords = VectorFunctionSpace(mesh, 'CG', order)

    coords = Function(V_coords)
    coords.interpolate(mesh.coordinates)

    # test = map_to_surface_2(coords, thre=0.9375)
    # coords_backup = coords.copy(deepcopy=True)
    mesh_new = Mesh(coords)

    V = FunctionSpace(mesh_new, 'CG', order)

    x, y, z = SpatialCoordinate(mesh_new)
    t = Constant(0)

    v = TestFunction(V)

    s_terms = [source_term0, source_term1, source_term2]

    fs = [st(x, y, z, t) for st in s_terms]

    Ls = [f*v*dx for f in fs]

    bs = []
    for i, L in enumerate(Ls):
        print('Begin Assemble L%d'%i)
        bs.append(assemble(L))
        print('End Assemble L%d'%i)
    

test_ufl_expression(order=2)
```

The output is something like this
```text
firedrake:WARNING OMP_NUM_THREADS is not set or is set to a value greater than 1, we suggest setting OMP_NUM_THREADS=1 to improve performance
tsfc:WARNING Estimated quadrature degree 57 more than tenfold greater than any argument/coefficient degree (max 2)
Begin Assemble L0
End Assemble L0
Begin Assemble L1
Segmentation fault
```

[dumball-maxh0.125-new.msh.zip](https://github.com/firedrakeproject/firedrake/files/6643256/dumball-maxh0.125-new.msh.zip)

**Comment by wence-** [comment]
My guess is that the kernels that are being generated have very large temporary arrays (because the quadrature estimation is so far off). On some systems you might be running into an operating system imposed stack limit.

To confirm, can you show the output of:

```
ulimit -s -S
ulimit -s -H
```
?

UFL generally does a bad job at estimate quadrature for the kind of forcing terms you provide with complicated non-polynomial expressions. So I would recommend manually selecting the integration degree:

```
Ls = [f*v*dx(degree=order*2) for f in fs]
```

(or some other appropriate quadrature degree).

Hopefully that will work. FWIW, I was able to run your test case without modification.

**Comment by lrtfm** [comment]
Thanks for your clarification. 
The outputs of `ulimit` are listed below, the `soft` value is too low. After I set it to unlimited. The test case run without error. 

```
$ ulimit -s -H
unlimited
$ ulimit -s -S
8192
```

> UFL generally does a bad job at estimate quadrature for the kind of forcing terms you provide with complicated non-polynomial expressions. So I would recommend manually selecting the integration degree:
> 
> ```
> Ls = [f*v*dx(degree=order*2) for f in fs]
> ```

This works well, Thanks.
