### ISSUE TITLE
Update loopy

### ISSUE THREAD

**Issue by sv2518** [firedrakeproject/firedrake#2113]
Since loopy has merged their loopy sprint branch, we want to run on a version of their master. We talked about this in one of our meetings, there are minutes which say what we decided on.

> DH: We don't actually want to run on their master branch. We want a nominal fork that automatically updates to master when we have confirmed that CI passes using it. SV: They are happy to take some of our tests to make sure that they don't break compatibility with Firedrake. DH: But they're not going to want to build PETSc in their CI. If they ran the tests on our Docker container they would have to switch out the Loopy which is slightly involved. Also there is still the risk of breaking Firedrake for our users.
> 
> DH: We want to hard update our fork to master but this would break firedrake-update.
> 
> Process decided upon: Check if current branch is firedrake and if so then switch to main and then pull. This won't affect other branches.

I am tracking here what I am doing because I don't feel confident I will get this right on my own.

1. I fetched loopy main and pushed it to our fork also named as main.
2. I have updated the install script so it resets the loopy remote to branch main if working on branch firedrake.
-> The casing is in `git_update` and I added loopy@main to `requirements-ext.git`. Note that I am not confident that this is working yet. The branch is here https://github.com/firedrakeproject/firedrake/tree/sv/update-loopy-fork
3. I guess we need to do this for the install as well. Will the change in `requirements-ext.git` be sufficient for that?
4. I am not really sure how I can test what I am doing is right. I guess for 3. I can just do a fresh install with the script from my branch to double-check and for 2. I can install firedrake with our current script on master and then try updating with the new script. Since this "testing" will take ages, I'd be happy if anyone more familiar with the install script can already see issues with the changes I have made on the update-loopy-fork branch.
5. Remember to reset the default branch on our fork.

Note that there is a parallel issue in our loopy fork here https://github.com/firedrakeproject/loopy/issues/16 where there was a discussion about having a small subset of tests run in the loopy CI.

Note that we also need merge the PyOP2 branch which adapts to new loopy changes.

The tests on the current loopy master are green, see https://github.com/firedrakeproject/firedrake/pull/2105.

**Comment by connorjward** [comment]
I've left some comments on your [commit](https://github.com/firedrakeproject/firedrake/commit/647b4abba9d1d0d79b98439858aaba5c5c3181d9). Testing does NOT sound fun, if you want someone else to check that your changes actually work I'm happy to do that.

**Comment by sv2518** [comment]
Ok, I finally got around to look at this again. I changed the install script according to what you commented. I have also moved the change of requirements from firedrake to PyOP2 see https://github.com/OP2/PyOP2/pull/628. I tested the update locally and it worked. I just realised maybe I should actually move https://github.com/OP2/PyOP2/pull/628 into https://github.com/OP2/PyOP2/pull/627, so we can merge them together.

**Comment by connorjward** [comment]
Your changes look good. Minor point. Could you get `current_branch` to be `"firedrake"` instead of `"firedrake\n"`? Just add `.strip()` to the `check_output` call.

Also this would be good to make into a PR rather than an issue.

**Comment by sv2518** [comment]
Ok. PR is here already https://github.com/firedrakeproject/firedrake/pull/2130
