### ISSUE TITLE
Docker container supporting complex numbers

### ISSUE THREAD

**Issue by MiroK** [firedrakeproject/firedrake#2119]
Hi, is there a container available in which firedrake complex could be tested? I found [this](https://hub.docker.com/r/firedrakeproject/firedrake-complex/tags?page=1&ordering=last_updated) one which however gives me

```
$ docker pull firedrakeproject/firedrake-complex
Using default tag: latest
Error response from daemon: manifest for firedrakeproject/firedrake-complex:latest not found: manifest unknown: manifest unknown
```

Isn't the container updated in [testing](https://github.com/firedrakeproject/firedrake/blob/master/Jenkinsfile#L127)

**Comment by dham** [comment]
Hi @MiroK. basically we ran out of time when we were merging Complex to master last year and never got the container building. Now that term is just about over here, I am picking up the task of fixing up our build system by moving it to GitHub Actions. I plan to fix the docker file on the way.

**Comment by QingguoHong** [comment]
@dham, I am using firedrake to do complex computing. Could I have your favor to fix that issue soon?

**Comment by dham** [comment]
OK there is now a complex Firedrake docker container up at: https://hub.docker.com/repository/docker/firedrakeproject/firedrake-complex

I would be most grateful if people would give it a try and see if it works.

**Comment by MiroK** [comment]
Thanks @dham. I ran a simple Helmholtz problem with complex coefs inside the container - everything worked fine.

**Comment by dham** [comment]
Thanks!
