### ISSUE TITLE
cannot run any f.interpolate

### ISSUE THREAD

**Issue by WenhuiHAN7** [firedrakeproject/firedrake#2128]
https://www.firedrakeproject.org/demos/helmholtz.py
I tried to run the code of the above link, there would be an error. I don't know how to fix it. 

from firedrake import *
mesh = UnitSquareMesh(10, 10)

V = FunctionSpace(mesh, "CG", 1)
u = TrialFunction(V)
v = TestFunction(V)

f = Function(V)
x, y = SpatialCoordinate(mesh)
f.interpolate((1+8*pi*pi)*cos(x*pi*2)*cos(y*pi*2))

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-80977890e4b3> in <module>
     67 # value of our right hand side function::
     68 
---> 69 f = Function(V).interpolate((1+8*pi*pi)*cos(x*pi*2)*cos(y*pi*2))
     70 x, y = SpatialCoordinate(mesh)
     71 # f.interpolate((1+8*pi*pi)*cos(x*pi*2)*cos(y*pi*2))

/usr/lib/petsc/lib/python3/dist-packages/dolfin/function/function.py in interpolate(self, u)
    381             self._cpp_object.interpolate(u._cpp_object)
    382         else:
--> 383             self._cpp_object.interpolate(u)
    384 
    385     def compute_vertex_values(self, mesh=None):

AttributeError: 'Product' object has no attribute '_cpp_object'

**Comment by connorjward** [comment]
> `/usr/lib/petsc/lib/python3/dist-packages/dolfin/function/function.py in interpolate(self, u)`

This looks like you are somehow using dolfin instead of firedrake. Are you using a recent Firedrake install and have you activated the virtual environment?
