### ISSUE TITLE
Installation error about petsc

### ISSUE THREAD

**Issue by cherrymilk** [firedrakeproject/firedrake#2137]
After running the installation command: 

> python3 firedrake-install

I finally get the error below

[error.txt](https://github.com/firedrakeproject/firedrake/files/6746642/error.txt)

It seems that something maybe be wrong when installing the petsc. 

And here is the log file

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6746649/firedrake-install.log)

**Comment by connorjward** [comment]
The install log says `Could not locate a functional C compiler`. What is your default compiler and what version is it?

**Comment by cherrymilk** [comment]
My default compiler is gcc version 7.5.0

**Comment by connorjward** [comment]
We use the `--download-mpich` flag when running `configure`. Could you add that and see what happens? We also add a bunch of other flags but I doubt that those will be causing you any issues.

**Comment by cherrymilk** [comment]
I know the reason now.   Because of the network reason, I use the proxy to run the command

`proxychains4 ./configure  --download-mpich` 

Under this situation, it will say 

`Could not locate a functional C compiler`

Maybe I should use other methods for network proxying.
