### ISSUE TITLE
Issue with norm calculation?

### ISSUE THREAD

**Issue by mwelland** [firedrakeproject/firedrake#2140]
Is there not a problem with the implementation of firedrake/norms.py? As implemented, viz l:
norm(x) = integral x.x dx 
depends on the mesh size / resolution. Different from norm = sum(x.x). 
I think you could modify with information element size, but why not do numpy norm on the vector data directly which may be faster?

**Comment by dham** [comment]
I think you have that backwards. The integral norms, which are the natural norms on the finite element spaces and are the norms in which the convergence behaviour of well-posed finite element problems is proven. 

The integral norms are robust to mesh resolution, in the sense that they converge to the value for the underlying continuous function space as the mesh size goes to zero. The l_2 norm (`sum(x.x)`) doesn't converge as resolution goes to zero, and is more generally an issue. Scaling these by element size is a poor substitute for doing the integrals properly.

**Comment by mwelland** [comment]
Okay thanks for the background.
