### ISSUE TITLE
Should we set mat_mumps_icntl_14 even if pc_type is set by user?

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#2142]
Currently `"mat_mumps_icntl_14": 200` is part of the default solver parameters (along with preonly/lu+mumps).  However when the user sets `"pc_type"` themselves, the `pc_factor_mat_solver_type` and `mat_mumps_icntl` defaults are skipped. In the case of `pc_factor_mat_solver_type` I can see the logic for that: if the user sets `"pc_type": "lu"` they might reasonably expect the default (petsc) direct solver, so they have to explicitly ask for `"pc_factor_mat_solver_type": "mumps"` as well if they want mumps. However if they do so, they still do not get `"mat_mumps_icntl_14": 200` and this seems to frequently lead to issues - it does for me at least, random hangs in solvers that are not obvious to debug but are presumably just memory issues. I think the user explicitly asking for lu + mumps, despite it already being the default, happens relatively often, either because the user is just being explicit in a configuration, say in code with multiple alternative solver configurations, or because the setup was written before mumps was the default. As an example: https://www.firedrakeproject.org/demos/navier_stokes.py.html. I think it would be more helpful if we just always set `"mat_mumps_icntl_14": 200` (except when the user sets `"mat_mumps_icntl_14"` themselves of course).

**Comment by wence-** [comment]
I think that is a reasonable thing to do, do you want to have a go?
