### ISSUE TITLE
Transfer of 2D simulation outputs to subsequent 3D simulation

### ISSUE THREAD

**Issue by amakarowsky** [firedrakeproject/firedrake#2148]
Hi all,

I have been using Firedrake to study electrochemical cells. I am aiming for a two-stage simulation process:

1. An cell electrochemical simulation which takes place on a 2D rectangular mesh. This simulation produces heat source terms q(x, y, t) which vary across two spatial dimensions and time. 

2. A thermal simulation of many stacked electrochemical cells, performed on a 3D rectangular prism mesh. The x-y footprint of the 3D mesh is the same as in the cell electrochemical simulation. 

For the moment, I am considering decoupled thermal/electrochemical models (the electrochemical model produces heat source terms which affect the thermal simulation, the thermal simulation does not affect the electrochemical simulation).

I would like to feed in the q(x, y, t) outputs of the first simulation into the second 3D simulation i.e. q(x, y, t) -> q(x, y, z, t) with no variance across z. 

I would appreciate some advice on whether this is possible within Firedrake as I have not had success to date. If it is indeed possible, a rough outline of the process would be greatly appreciated. 

Thank you for your efforts on a great package. AM

**Comment by pefarrell** [comment]
Hi Alexander,

Here's a snippet that transfers a function from a 2D base mesh to its 3D extrusion.

It could probably be faster; writing the loop in Python won't be efficient. Hopefully someone from the firedrake team will chime in with a better way.

```
from firedrake import *
  
mesh = UnitTriangleMesh()

V = FunctionSpace(mesh, "CG", 1)
(x, _) = SpatialCoordinate(mesh)
u = interpolate(x, V)

mesh3 = ExtrudedMesh(mesh, layers=2, layer_height=0.5)
V3 = FunctionSpace(mesh3, "CG", 1)
X = interpolate(SpatialCoordinate(mesh3), VectorFunctionSpace(mesh3, "CG", 1))
u3 = Function(V3)

for i in range(X.dat.data_ro.shape[0]):
    (x, y, _) = X.dat.data_ro[i, :]
    u3.dat.data[i] = u.at((x, y))

File("output.pvd").write(u3)
```

**Comment by amakarowsky** [comment]
Hi Patrick,

Thank you very much for this code snippet, I think this will do the job for now. 

If anyone has other ideas for performing this task feel free to share also. AM
