### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by mc4117** [firedrakeproject/firedrake#2150]
Please could I have a firedrake zenodo release using the attached file (sorry I had to convert from json to txt to upload it). Thanks!
[firedrake.txt](https://github.com/firedrakeproject/firedrake/files/6821781/firedrake.txt)

**Comment by wence-** [comment]
I think this matches up with a thetis release? Can you re-run `firedrake-zenodo` with the `--additional-dois` flags passing the DOI for the thetis release. That way you'll only need to cite one zenodo archive in your paper.

**Comment by mc4117** [comment]
Thanks for the advice! This is the new file with the additional doi 
[firedrake.txt](https://github.com/firedrakeproject/firedrake/files/6821892/firedrake.txt)

**Comment by wence-** [comment]
Tag is `Firedrake_20210715.0`
DOI is 10.5281/zenodo.5105703
Zenodo URL is https://zenodo.org/record/5105703
BibTeX

```
@misc{zenodo/Firedrake-20210715.0,
 key   = {zenodo/Firedrake-20210715.0},
 title = {{Software used in `Calibration, inversion and sensitivity analysis for hydro-morphodynamic models through the application of adjoint methods'}},
 year  = {2021},
 month = {jul},
 doi   = {10.5281/zenodo.5105703},
 url   = {https://doi.org/10.5281/zenodo.5105703},
}
```

Thanks!
