### ISSUE TITLE
Create a Zenodo release

### ISSUE THREAD

**Issue by rfausas** [firedrakeproject/firedrake#2162]
{"firedrake": "442f257b0b2ff11604a193c2239f949106335aeb", "PyOP2": "b18cb61d648f16a34991a675e860581599fc7cba", "tsfc": "6a0c1b73d472829bd92cfe82f5e2a79d235daf4b", "COFFEE": "72a4464aa18fd408de5304ac467db18d7af2b670", "ufl": "4516a6d5023eb5dfe62ec2431865e125aa6daf97", "FInAT": "2f0e0bd61fd5800920ed66a2c3347d4d916c0045", "fiat": "ae587ff3a32be0b23edae3222e88b0f62da9f3e4", "petsc": "bbc3b47c2450b090879fad6292a3c84746e81201", "petsc4py": "9bcb404c3b9bb7ba5a4c5f522d0f6894e6e0d6bf", "loopy": "5f5bf994c6aa6fca1b749adbb3d5b3d4c7432074", "metarelease_info_file": ["README.md", "IyBtaWNyb3N3aW1tZXJzCgotIEZpcmVkcmFrZSBzY3JpcHQgZm9yIHRoZSBzaW11bGF0aW9uIG9m\nIGFjdGl2ZSBtaWNyb3N3aW1tZXJzIGFzIHByZXNlbnRlZCBpbjoKCiAgKioiQSBmaW5pdGUgZWxl\nbWVudCBtZXRob2QgZm9yIHNpbXVsYXRpbmcgc29mdCBhY3RpdmUgbm9uLXNoZWFyYWJsZSByb2Rz\nIGltbWVyc2VkIGluIGdlbmVyYWxpemVkIE5ld3RvbmlhbiBmbHVpZHMiKioKCiAgICpieSBSb2Jl\ncnRvIEYuIEF1c2FzLCBDcmlzdGlhbiBHLiBHZWJoYXJkdCBhbmQgR3VzdGF2byBDLiBCdXNjYWds\naWEqCgogICBodHRwOi8vYXJ4aXYub3JnL2Ficy8yMTA3LjEyODQxCgogICBRdWVzdGlvbnMgdG86\nIHJmYXVzYXNAaWNtYy51c3AuYnIKICAgICAgICAgICAgICAgICBodHRwOi8vd3d3LmxtYWNjLmlj\nbWMudXNwLmJyL35hdXNhcy8KCi0gRmlyZWRyYWtlIGluc3RhbGxhdGlvbjoKCiAgU2VlIGRldGFp\nbGVkIGluc3RydWN0aW9ucyBpbiBodHRwczovL3d3dy5maXJlZHJha2Vwcm9qZWN0Lm9yZy8KCiAg\nKFRoZSBleGFjdCB2ZXJzaW9uIG9mIGZpcmVkcmFrZSBhbmQgaXRzIGRlcGVuZGVuY2llcyBpcyB3\ncml0dGVuIGluIHRoZSBmaXJlZHJha2UuanNvbiBmaWxlKQogIAotIFJ1bm5pbmcgdGhlIHNjcmlw\ndCBpbiBhIHRlcm1pbmFsOgoKICAxLiBEb3dubG9hZCB0aGUgc2NyaXB0IGZyb206IAoKICAgICBo\ndHRwczovL2dpdGxhYi5jb20vcmZhdXNhcy9taWNyb3N3aW1tZXJzLmdpdAoKICAyLiBBY3RpdmF0\nZSB0aGUgZmlyZWRyYWtlIGVudmlyb25tZW50OgoKICAgICAuIC9ob21lL3VzZXIvcGF0aF90b195\nb3VyX2ZpcmVkcmFrZV9pbnN0YWxsYXRpb24vZmlyZWRyYWtlL2Jpbi9hY3RpdmF0ZQoKICAzLiBF\neGVjdXRlIGludG8geW91ciBmaXJlZHJha2UgZW52aXJvbm1lbnQ6CgogICAgIChmaXJlZHJha2Up\nIHVzZXJAbWFjaGluZTpwYXRoX3RvX3lvdXJfZmlsZXMkIHB5dGhvbjMgc3dpbW1lci5weSAKCgog\nICBDb21tZW50OiBOb3RpY2UgdGhhdCB0aGUgZmlyc3QgdGltZSB5b3UgcnVuIHRoZSBzY3JpcHQg\nZm9yIGEgZ2l2ZW4gcm9kIGRpc2NyZXRpemF0aW9uLCB0aGUgbGlicmFyeSBleHBlbmRzCiAgICAg\nICAgICAgIHNvbWUgdGltZSBkdXJpbmcgdGhlIGNvZGUgZ2VuZXJhdGlvbiBwaGFzZS4KCgo=\n"], "title": "A finite element method for simulating soft active non-shearable rods immersed in generalized Newtonian fluids, http://arxiv.org/abs/2107.12841"}

**Comment by dham** [comment]
Here you go:

```
@misc{zenodo/Firedrake-20210729.1,
 key   = {zenodo/Firedrake-20210729.1},
 title = {{Software used in 'A finite element method for simulating soft active non-shearable rods immersed in generalized Newtonian fluids, http://arxiv.org/abs/2107.12841'}},
 year  = {2021},
 month = {jul},
 doi   = {10.5281/zenodo.5145878},
 url   = {https://doi.org/10.5281/zenodo.5145878},
}
```

**Comment by rfausas** [comment]
Thanks!
