### ISSUE TITLE
Zenodo release for a paper

### ISSUE THREAD

**Issue by NBoulle** [firedrakeproject/firedrake#2180]
Hi, could you create a Zenodo release of Firedrake with the following file ?
[firedrake.txt](https://github.com/firedrakeproject/firedrake/files/6999024/firedrake.txt)

Thanks

**Comment by wence-** [comment]
Tag is `Firedrake_20210818.0`
DOI is 10.5281/zenodo.5217566
Zenodo URL is https://zenodo.org/record/5217566
BibTeX
```
@misc{zenodo/Firedrake-20210818.0,
 key   = {zenodo/Firedrake-20210818.0},
 title = {{Software used in `Control of bifurcation structures using shape optimization'}},
 year  = {2021},
 month = {aug},
 doi   = {10.5281/zenodo.5217566},
 url   = {https://doi.org/10.5281/zenodo.5217566},
}
```

Thanks!
