### ISSUE TITLE
Platform dependent VertexOnlyMesh creation failure

### ISSUE THREAD

**Issue by ReubenHill** [firedrakeproject/firedrake#2186]
On my laptop, I don't have any problem with `VertexOnlyMesh`. Take a look at the test:

```python
from firedrake import *
import numpy as np
mesh = RectangleMesh(100, 200, 1.0, 2.0)
num_rec = 10
δs = np.linspace(0.4, 0.9, num_rec)
X, Y = np.meshgrid(δs*0.999,0.5*0.999)
print(X,Y)
xs = np.vstack((X.flatten(), Y.flatten())).T

point_cloud = VertexOnlyMesh(mesh, xs)
```

However, I had a problem running the same test at the equal Firedrake version on another computer. The error was: 

```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    point_cloud = VertexOnlyMesh(mesh, xs)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/dolci/run_firedrake/firedrake/src/firedrake/firedrake/mesh.py", line 2006, in VertexOnlyMesh
    dmcommon.label_pic_parent_cell_info(swarm, mesh)
  File "firedrake/cython/dmcommon.pyx", line 2711, in firedrake.cython.dmcommon.label_pic_parent_cell_info
TypeError: an integer is required
```

I ran a print at the `mesh.py`, inside the function ```locate_cell_and_reference_coordinate```. I printed ```print(X.ctypes.data_as(ctypes.POINTER(ctypes.c_double))._arr)```. I observed that on the case where an error occurs, the print ```print(X.ctypes.data_as(ctypes.POINTER(ctypes.c_double))._arr)``` is [0,0] and then the run break due the error. On my laptop, the print is

```
[0.04 0.91]
[0.49 0.46]
[0.94 0.01]
[0.39 0.56]
[0.84 0.11]
[0.29 0.66]
[0.74 0.21]
[0.19 0.76]
[0.64 0.31]
[0.09 0.86]
```

and everything works. So, my question is why this error does not appears on my laptop? Maybe some relation with a library installation?

_Originally posted by @Ig-dolci in https://github.com/firedrakeproject/firedrake/issues/2178#issuecomment-900426004_

**Comment by ReubenHill** [comment]
> I ran a print at the `mesh.py`, inside the function `locate_cell_and_reference_coordinate`. I printed `print(X.ctypes.data_as(ctypes.POINTER(ctypes.c_double))._arr)`. I observed that on the case where an error occurs, the print `print(X.ctypes.data_as(ctypes.POINTER(ctypes.c_double))._arr)` is [0,0] and then the run break due the error.

If the C representation of the array doesn't match what you're seeing in python then that would perhaps explain the issue. This would presumably point to some kind of numpy issue though? What's the platform where it isn't working (python and numpy version for example vs where it does work) and what is printed?

**Comment by ReubenHill** [comment]
I wonder if my suggestion in #2185 

> We could switch to filtering points using locate_cell_and_reference_coordinate before rank locating them relative to the DMPlex

might help catch cases like this earlier

**Comment by Ig-dolci** [comment]
Case in which the `VertxOnlyMesh`does not work: numpy version is 1.21.1,  python version is 3.8.5.
Case in which the `VertxOnlyMesh` works: numpy version is 1.20.3, python3 version 3.85.

As you see only the numpy version is different.

**Comment by ReubenHill** [comment]
Does the problem go away if you downgrade numpy?

**Comment by Ig-dolci** [comment]
No. The error remains.

**Comment by ReubenHill** [comment]
Can you please add a print out of the ctypes equivalent for both `X` and `Y` alongside the current `print(X,Y)` and post what you get in both the passing and failing case?

**Comment by Ig-dolci** [comment]
- **Failing case:**

When I ran `print(X.ctypes,Y.ctypes)`:
```
<numpy.core._internal._ctypes object at 0x7f96af6bae80> <numpy.core._internal._ctypes object at 0x7f95d3d79bb0>
```
When I ran `print(X.ctypes.__dict__,Y.ctypes.__dict__)`:
 ```
{'_arr': array([[0.4       , 0.45555556, 0.51111111, 0.56666667, 0.62222222,
        0.67777778, 0.73333333, 0.78888889, 0.84444444, 0.9       ]]), '_ctypes': <module 'ctypes' from '/home/dolci/anaconda3/lib/python3.8/ctypes/__init__.py'>, '_data': c_void_p(94776915396960), '_zerod': False} {'_arr': array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]]), '_ctypes': <module 'ctypes' from '/home/dolci/anaconda3/lib/python3.8/ctypes/__init__.py'>, '_data': c_void_p(94776913483600), '_zerod': False}
```

**- Passing Case**

When I ran `print(X.ctypes,Y.ctypes)`:
```
<numpy.core._internal._ctypes object at 0x7f707a5545b0> <numpy.core._internal._ctypes object at 0x7f703fadf340>
```

When I ran `print(X.ctypes.__dict__,Y.ctypes.__dict__)`:
```
{'_arr': array([[0.4       , 0.45555556, 0.51111111, 0.56666667, 0.62222222,
        0.67777778, 0.73333333, 0.78888889, 0.84444444, 0.9       ]]), '_ctypes': <module 'ctypes' from '/usr/lib/python3.8/ctypes/__init__.py'>, '_data': c_void_p(48697456), '_zerod': False} {'_arr': array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]]), '_ctypes': <module 'ctypes' from '/usr/lib/python3.8/ctypes/__init__.py'>, '_data': c_void_p(46078320), '_zerod': False}
```

**Comment by Ig-dolci** [comment]
I see
**Failing case**:
Inside of the function `locate_cell_and_reference_coordinate` I ran `print(x.ctypes, X.ctypes)` and it was printed:

```
x.ctypes: <numpy.core._internal._ctypes object at 0x7fac99744100> 
X.ctypes: <numpy.core._internal._ctypes object at 0x7fad64753640>
```
I also ran `print(x.ctypes.__dict__, X.ctypes.__dict__)`, and it was printed:
```
x.ctypes.__dict__: {'_arr': array([0.3996, 0.4995]), '_ctypes': <module 'ctypes' from '/home/dolci/anaconda3/lib/python3.8/ctypes/__init__.py'>, '_data': c_void_p(94169453654784), '_zerod': False} 
X.ctypes.__dict__: {'_arr': array([0., 0.]), '_ctypes': <module 'ctypes' from '/home/dolci/anaconda3/lib/python3.8/ctypes/__init__.py'>, '_data': c_void_p(94169441782480), '_zerod': False}
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    point_cloud = firedrake.VertexOnlyMesh(mesh, xs)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/dolci/run_firedrake/firedrake/src/firedrake/firedrake/mesh.py", line 2010, in VertexOnlyMesh
    dmcommon.label_pic_parent_cell_info(swarm, mesh)
  File "firedrake/cython/dmcommon.pyx", line 2713, in firedrake.cython.dmcommon.label_pic_parent_cell_info
TypeError: an integer is required
```
**Passing case**

Inside of the function `locate_cell_and_reference_coordinate` I ran `print(x.ctypes, X.ctypes)` and it was printed:

```
x.ctypes: <numpy.core._internal._ctypes object at 0x7fb783f8b1f0>     
X.ctypes: <numpy.core._internal._ctypes object at 0x7fb71a15ba60>
```

I also ran `print(x.ctypes.__dict__, X.ctypes.__dict__)`, and it was printed:
```
x.ctype.__dict__: {'_arr': array([0.3996, 0.4995]), '_ctypes': <module 'ctypes' from '/usr/lib/python3.8/ctypes/__init__.py'>, '_data': c_void_p(55670768),  x.ctype.__dict__: '_zerod': False} 

X.ctype.__dict__: {'_arr': array([0.04, 0.91]),  '_ctypes': <module 'ctypes' from '/usr/lib/python3.8/ctypes/__init__.py'>, '_data': c_void_p(58233888), '_zerod': False}
```

**Comment by ReubenHill** [comment]
That `X.ctypes.__dict__: {'_arr': array([0., 0.]), '_ctypes': <module 'ctypes' from '/home/dolci/anaconda3/lib/python3.8/ctypes/__init__.py'>, '_data': c_void_p(94169441782480), '_zerod': False}` is rather mysterious. 

So going back to what I originally asked for, does it match up to the entries in `X` at all in the failing case?
I.e. do you see 0.0 as one of the values of `X` or is it only in the c representation (which I'm assuming is what cython looks at).

Note I am not a cython expert at all!

Also just to be on the safe side, try running `make` in `src/firedrake` with the venv activated and see if the problem goes away. This will recompile your cython files.

**Comment by wence-** [comment]
It may be easier to debug by just removing the type annotations from `label_pic_parent_cell_info` and putting it in one of the python files (it uses no Cython-specific features).

**Comment by wence-** [comment]
I imagine that the problem is that the cell is not located (so `locate_cell_and_reference_coordinate` returns `None, None`. But `parent_cell_num` and `reference_coord` are type-annotated as `int` and `np.ndarray` respectively. So cython complains at runtime that there's a type mismatch.

**Comment by ReubenHill** [comment]
> I imagine that the problem is that the cell is not located (so `locate_cell_and_reference_coordinate` returns `None, None`. But `parent_cell_num` and `reference_coord` are type-annotated as `int` and `np.ndarray` respectively. So cython complains at runtime that there's a type mismatch.

This is indeed the reason for the error message but I don't understand why it would be raised based on the script given. At this point any out-of-mesh points should already have been removed

**Comment by Ig-dolci** [comment]
> So going back to what I originally asked for, does it match up to the entries in `X` at all in the failing case?

Actually, I am trying to understand the things here. So `X` and `Y`are:
```
X: [[0.3996 0.4551 0.5106 0.5661 0.6216 0.6771 0.7326 0.7881 0.8436 0.8991]]
Y: [[0.4995 0.4995 0.4995 0.4995 0.4995 0.4995 0.4995 0.4995 0.4995 0.4995]]
```

At the `locate_cell_and_reference_coordinate` is get the `cell` according to the points given by `X`and `Y`, right?
The cell is got by:
```
cell = self._c_locator(tolerance=tolerance)(self.coordinates._ctypes,
                                                    x.ctypes.data_as(ctypes.POINTER(ctypes.c_double)),
                                                    X.ctypes.data_as(ctypes.POINTER(ctypes.c_double)))
```
In the current case (according to the`X`and `Y` points coordinates), we have `x.ctypes.data_as(ctypes.POINTER(ctypes.c_double)` given by:

```
[0.4551 0.4995]
[0.5106 0.4995]
[0.5661 0.4995]
[0.6216 0.4995]
[0.6771 0.4995]
[0.7326 0.4995]
[0.7881 0.4995]
[0.8436 0.4995]
[0.8991 0.4995]
```
So, I understood that `x` inside of the function `locate_cell_and_reference_coordinate` is the vector with the points defined by `X` and `Y`. I did not understand what is `X` inside of the function `locate_cell_and_reference_coordinate`.

**Comment by Ig-dolci** [comment]
The problem is in finding the cell and updating the X inside of function `locate_cell_and_reference_coordinate`.

**Comment by ReubenHill** [comment]
Right but I'm trying to understand where `[0.0]` has come from. If we can track that down that will probably give us a clue to further debugging

**Comment by Ig-dolci** [comment]
I got access to another computer. I will install Firedrake and verify if this error remains. I will notify you about the result.

**Comment by Ig-dolci** [comment]
@ReubenHill I installed Firedrake on another computer and `VertexOnlyMesh` is working. Like on my laptop, I do not have errors. It is weird the `VertexOnlyMesh` does not work for that other computer, I guess that some library it is not working adequately. Anyway, for now, I am using this newer computer for larger simulations.

**Comment by ReubenHill** [comment]
Are you planning to do any more debugging of the issue on the other computer? If not please close for now and reopen if the problem reoccurs

**Comment by Ig-dolci** [comment]
No. We can close.
