### ISSUE TITLE
Zenodo request for upcoming paper "Consolidated theory of fluid thermodiffusion"

### ISSUE THREAD

**Issue by AlexanderVB** [firedrakeproject/firedrake#2189]
[Consolidated-theory-of-fluid-thermodiffusion-json-and-readme.zip](https://github.com/firedrakeproject/firedrake/files/7020574/Consolidated-theory-of-fluid-thermodiffusion-json-and-readme.zip)

**Comment by AlexanderVB** [comment]
Sorry, please use this JSON file instead contained in the following zip.

[Consolidated-theory-of-fluid-thermodiffusion-json.zip](https://github.com/firedrakeproject/firedrake/files/7045150/Consolidated-theory-of-fluid-thermodiffusion-json.zip)

**Comment by wence-** [comment]
Hi @AlexanderVB sorry we dropped the ball here. I see the paper is now on the arxiv, do you still want this release?

**Comment by AlexanderVB** [comment]
Thank you yes that would be much appreciated, we are just about to submit
the revisions.

**Comment by wence-** [comment]
Great. I'll get to that in the next few days. Is your json from the second post still correct?

**Comment by AlexanderVB** [comment]
Yes it is. Thank you!

**Comment by wence-** [comment]
Tag is `Firedrake_20211106.0`
DOI is 10.5281/zenodo.5651136
Zenodo URL is https://zenodo.org/record/5651136
BibTeX

```bibtex
@misc{zenodo/Firedrake-20211106.0,
 key   = {zenodo/Firedrake-20211106.0},
 title = {{Software used in `Consolidated theory of fluid thermodiffusion'}},
 year  = {2021},
 month = {nov},
 doi   = {10.5281/zenodo.5651136},
 url   = {https://doi.org/10.5281/zenodo.5651136},
}

```

Thanks!
