### ISSUE TITLE
Request for Zenodo release (before changes)

### ISSUE THREAD

**Issue by Melina97** [firedrakeproject/firedrake#2203]
{"firedrake": "9bb29486c7a6c5cf932507815f52162688b6333d", "PyOP2": "edf5b3a51e5d3268cb5d67c5e8a6c9e981e3b01b", "tsfc": "231e30103df52be8bfa1e58ec38c794706f2e04a", "COFFEE": "70c1e66a4e4e39d3bf75274505a16901af110751", "ufl": "cf8d177c539ef89d9fa832e9f5062536f37d4c77", "FInAT": "1219f013a5cf57dd99f2b0e11be5a9602bf19c6a", "fiat": "7d418fa0a372ac6f5e103533ab77ad6a9fac764c", "petsc": "0ca58fa61fc0b1fa35e5eff0174befb041c0e4b7", "loopy": "120244304c8fdc7b0ca4ea46dba0308fb6702742", "metarelease_info_file": null, "title": "Automated Differentiation for Inverse Problems"}

**Comment by wence-** [comment]
Tag is Firedrake_20210902.0
DOI is 10.5281/zenodo.5396847
Zenodo URL is https://zenodo.org/record/5396847
BibTeX

```
@misc{zenodo/Firedrake-20210902.0,
 key   = {zenodo/Firedrake-20210902.0},
 title = {{Software used in `Automated Differentiation for Inverse Problems'}},
 year  = {2021},
 month = {sep},
 doi   = {10.5281/zenodo.5396847},
 url   = {https://doi.org/10.5281/zenodo.5396847},
}
```

Thanks!
