### ISSUE TITLE
Request for Zenodo release (after changes)

### ISSUE THREAD

**Issue by Melina97** [firedrakeproject/firedrake#2204]
{"firedrake": "b88a5ecfdbea85604a81f28a6ee8922b5f06d67a", "PyOP2": "315d5f52a7b3da3f507c145c61c8eb07487eb8df", "tsfc": "231e30103df52be8bfa1e58ec38c794706f2e04a", "COFFEE": "70c1e66a4e4e39d3bf75274505a16901af110751", "ufl": "cf8d177c539ef89d9fa832e9f5062536f37d4c77", "FInAT": "1219f013a5cf57dd99f2b0e11be5a9602bf19c6a", "fiat": "7d418fa0a372ac6f5e103533ab77ad6a9fac764c", "petsc": "0ca58fa61fc0b1fa35e5eff0174befb041c0e4b7", "loopy": "120244304c8fdc7b0ca4ea46dba0308fb6702742", "metarelease_info_file": null, "title": "Automated Differentiation for Inverse Problems"}

**Comment by wence-** [comment]
Tag is `Firedrake_20210902.1`
DOI is 10.5281/zenodo.5396879
Zenodo URL is https://zenodo.org/record/5396879
BibTeX

```bibtex
@misc{zenodo/Firedrake-20210902.1,
 key   = {zenodo/Firedrake-20210902.1},
 title = {{Software used in `Automated Differentiation for Inverse Problems'}},
 year  = {2021},
 month = {sep},
 doi   = {10.5281/zenodo.5396879},
 url   = {https://doi.org/10.5281/zenodo.5396879},
}

```

Thanks!

**Comment by Melina97** [comment]
Thank you Lawrence!
