### ISSUE TITLE
Zenodo release "Goal-Oriented Metric-Based Mesh Adaptive Tidal Farm Modelling"

### ISSUE THREAD

**Issue by jwallwork23** [firedrakeproject/firedrake#2210]
Hi, please can I have a release for this json? Thanks!

`{"firedrake": "05d4e5472a700c8eb143e50fdc7475ffa54d150b", "PyOP2": "d5f82d3813e8f83bda00cd1f015fc70a1240bbc8", "tsfc": "3fe9dcf785c86a7dd8c5c5d58134b8b309784c03", "COFFEE": "70c1e66a4e4e39d3bf75274505a16901a    f110751", "ufl": "bcae96560f0a2c7b59b57397b155046d5846f116", "FInAT": "aa47ad58d3ad61dd8c5ed2dc2225999e61e919b4", "fiat": "7d418fa0a372ac6f5e103533ab77ad6a9fac764c", "petsc": "f77756e566a509e2539eb26e111f57c    b98596bcc", "loopy": "e232bb1361479f2e6fd3bd7efd7f4ecce270947f", "metarelease_info_file": null, "title": "Goal-Oriented Metric-Based Mesh Adaptive Tidal Farm Modelling"}`

**Comment by wence-** [comment]
Tag is `Firedrake_20210909.0`
DOI is 10.5281/zenodo.5497899
Zenodo URL is https://zenodo.org/record/5497899
BibTeX

```bibtex
@misc{zenodo/Firedrake-20210909.0,
 key   = {zenodo/Firedrake-20210909.0},
 title = {{Software used in `Goal-Oriented Metric-Based Mesh Adaptive Tidal Farm Modelling'}},
 year  = {2021},
 month = {sep},
 doi   = {10.5281/zenodo.5497899},
 url   = {https://doi.org/10.5281/zenodo.5497899},
}

```

**Comment by jwallwork23** [comment]
Thanks very much!
