### ISSUE TITLE
Downloading Firedrake

### ISSUE THREAD

**Issue by Cametron99** [firedrakeproject/firedrake#2213]
If I go onto Ubuntu: it says I have installed Firedrake but when I try and run a Fire drake code on python it says there is no module named python
According to the Firedrake site I need to activate the venv
How do I do that: do I need to go on virtual studio code?

**Comment by ReubenHill** [comment]
Hi @Cametron99 .

Assuming you ran `firedrake-install` without any arguments then the venv can be activated by 
 1. navigating to the location to which you cloned and ran the `firedrake-install` script then
 2. running `source firedrake/bin/activate`

For more information on venvs (virtual environments) see [this section of the python documentation](https://docs.python.org/3/tutorial/venv.html).

Hopefully that works for you - closing for now.
