### ISSUE TITLE
MPI hangs with data_with_halos

### ISSUE THREAD

**Issue by tranner** [firedrakeproject/firedrake#2225]
I am trying to manually update some function values using a cell-wise operation in parallel. I tried to do something using `par_loops` before without success due to #2030 . I'm now trying a pure python version.

The code iterates over the function space `cell_node_list` and updates data with function `.dat.data_with_halos`.

Following advice from <https://www.firedrakeproject.org/parallelism.html#id6> , I have turned off garbage collection but still the code just hangs when the number of cells is not balanced across cores.

Am I missing some nice way to do these manual updates in python? Is there something obviously wrong with the mpi set up? Any other help/comments welcome too.

Thanks,
Tom

Minimal working example:
```python
import sys

from firedrake import COMM_WORLD, Function, FunctionSpace, UnitCubeMesh
from firedrake import _version as version

if COMM_WORLD.rank == 0:
    print("python:")
    print(sys.version)
    print("firedrake:")
    print(version.get_versions())
    print("my rank is", COMM_WORLD.rank, "of", COMM_WORLD.size)

sys.stdout.flush()
COMM_WORLD.barrier()

# don't garbage collect in parallel
# see https://www.firedrakeproject.org/parallelism.html#id6

import gc

gc.disable()


N = 1
mesh = UnitCubeMesh(N, N, N)

V = FunctionSpace(mesh, "Lagrange", 1)
f = Function(V)

print(f"rank {COMM_WORLD.rank} has {len(V.cell_node_list)} cells")
sys.stdout.flush()
COMM_WORLD.barrier()

for id, cell in enumerate(V.cell_node_list):
    for i in cell:
        f.dat.data_with_halos[i] = i

    print(f"rank {COMM_WORLD.rank} cell {id} of {len(V.cell_node_list)} - done")
    if id == len(V.cell_node_list) - 1:
        print(f"rank {COMM_WORLD.rank} complete")
    sys.stdout.flush()
```
Output with `-np 2` (all good):
```
python:
3.9.6 (default, Jul 16 2021, 00:00:00) 
[GCC 10.3.1 20210422 (Red Hat 10.3.1-1)]
firedrake:
{'version': '0.13.0+4754.gea23f014', 'full-revisionid': 'ea23f01446a1412733caf348b566b95791cb6a2d', 'dirty': False, 'error': None}
my rank is 0 of 2
rank 1 has 5 cells
rank 0 has 5 cells
rank 1 cell 0 of 5 - done
rank 0 cell 0 of 5 - done
rank 1 cell 1 of 5 - done
rank 0 cell 1 of 5 - done
rank 1 cell 2 of 5 - done
rank 0 cell 2 of 5 - done
rank 1 cell 3 of 5 - done
rank 0 cell 3 of 5 - done
rank 1 cell 4 of 5 - done
rank 1 complete
rank 0 cell 4 of 5 - done
rank 0 complete
```

Output before the hang with `-np 4` (not good):
```
python:
3.9.6 (default, Jul 16 2021, 00:00:00) 
[GCC 10.3.1 20210422 (Red Hat 10.3.1-1)]
firedrake:
{'version': '0.13.0+4754.gea23f014', 'full-revisionid': 'ea23f01446a1412733caf348b566b95791cb6a2d', 'dirty': False, 'error': None}
my rank is 0 of 4
rank 1 has 4 cells
rank 2 has 3 cells
rank 3 has 4 cells
rank 0 has 3 cells
rank 0 cell 0 of 3 - done
rank 1 cell 0 of 4 - done
rank 2 cell 0 of 3 - done
rank 3 cell 0 of 4 - done
rank 0 cell 1 of 3 - done
rank 1 cell 1 of 4 - done
rank 2 cell 1 of 3 - done
rank 3 cell 1 of 4 - done
rank 0 cell 2 of 3 - done
rank 0 complete
rank 1 cell 2 of 4 - done
rank 2 cell 2 of 3 - done
rank 2 complete
rank 3 cell 2 of 4 - done
```

**Comment by wence-** [comment]
> ```python
> for id, cell in enumerate(V.cell_node_list):
>     for i in cell:
>         f.dat.data_with_halos[i] = i
> 
>     print(f"rank {COMM_WORLD.rank} cell {id} of {len(V.cell_node_list)} - done")
>     if id == len(V.cell_node_list) - 1:
>         print(f"rank {COMM_WORLD.rank} complete")
>     sys.stdout.flush()
> ```

Your problem lies here. The call to `f.dat.data_with_halos` is a collective one (that is, it kicks off MPI communication). But when you run on more than one rank, there may not be the same number of cells on each process, so rank 0 may call the communication routines three times, and rank 2 only once.

To avoid this, get access to the array outside the loop:
```
data_pointer = f.dat.data_with_halos
for id, cell in enumerate(...):
    for i in cell:
        data_pointer[i] = i
```

**Comment by tranner** [comment]
Thank you so much - that now works great :)
