### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by nbouziani** [firedrakeproject/firedrake#2229]
Hi,

I would like to get the zenodo release for the json file whose content is:

> {"firedrake": "1e0f9ed8ed9e6ea1a627471730dda0bddb7fd1fa", "PyOP2": "7d3d4bec07d6ca48787e75eb24e1d25c398c8a13", "tsfc": "55dc96cbbd43273c99c9eea3f8160c21971d5712", "COFFEE": "70c1e66a4e4e39d3bf75274505a16901af110751", "ufl": "72cddd9a011510e23bb0e75b9cbde16425948b24", "FInAT": "aa47ad58d3ad61dd8c5ed2dc2225999e61e919b4", "fiat": "7d418fa0a372ac6f5e103533ab77ad6a9fac764c", "petsc": "70a4eb5794b0eb30a077b74a20497d039985a498", "loopy": "e232bb1361479f2e6fd3bd7efd7f4ecce270947f", "metarelease_info_file": null, "title": "Escaping the abstraction: a foreign function interface for the Unified Form Language [UFL]"}
~                                                         

PS: Sorry, it seems I cannot upload the json file directly.

**Comment by dham** [comment]
```bibtex
@misc{zenodo/Firedrake-20210924.0,
 key   = {zenodo/Firedrake-20210924.0},
 title = {{Software used in `Escaping the abstraction: a foreign function interface for the Unified Form Language [UFL]'}},
 year  = {2021},
 month = {sep},
 doi   = {10.5281/zenodo.5526458},
 url   = {https://doi.org/10.5281/zenodo.5526458},
}

```
