### ISSUE TITLE
Installing Icepack

### ISSUE THREAD

**Issue by simondriscoll** [firedrakeproject/firedrake#2230]
Hi I'm installing icepack off the instructions given here: https://icepack.github.io/install/ 

curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install

Seems to work fine. I get an error on the second step. This is my output (and I have attached the .log file). 

% python3.8 firedrake-install --install icepack
Running firedrake-install --install icepack
Installing command line tools...
Checking brew doctor...
Installing required packages via homebrew...
Required package 'gcc' is already installed via Homebrew.
Required package 'autoconf' is already installed via Homebrew.
Required package 'make' is already installed via Homebrew.
Required package 'automake' is already installed via Homebrew.
Required package 'cmake' is already installed via Homebrew.
Required package 'libtool' is already installed via Homebrew.
Required package 'boost' is already installed via Homebrew.
Required package 'openblas' is already installed via Homebrew.
Creating firedrake venv in '/Users/simondriscoll/firedrake'.
Configuration saved to /Users/simondriscoll/firedrake/.configuration.json
Cloning firedrake

Failed to clone firedrake using ssh, falling back to https.
Successfully cloned repository firedrake.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Creating firedrake-update script.
Cloning the dependencies of firedrake
Cloning ufl

Failed to clone ufl using ssh, falling back to https.
Successfully cloned repository ufl.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning fiat

Failed to clone fiat using ssh, falling back to https.
Successfully cloned repository fiat.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning FInAT

Failed to clone FInAT using ssh, falling back to https.
Successfully cloned repository FInAT.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning tsfc

Failed to clone tsfc using ssh, falling back to https.
Successfully cloned repository tsfc.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning PyOP2

Failed to clone PyOP2 using ssh, falling back to https.
Successfully cloned repository PyOP2.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning pyadjoint

Failed to clone pyadjoint using ssh, falling back to https.
Successfully cloned repository pyadjoint.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning petsc

Failed to clone petsc using ssh, falling back to https.
Successfully cloned repository petsc.
Checking out branch firedrake
Successfully checked out branch firedrake
Updating submodules.
Successfully updated submodules.
Cloning the dependencies of PyOP2
Cloning COFFEE

Failed to clone COFFEE using ssh, falling back to https.
Successfully cloned repository COFFEE.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning loopy

Failed to clone loopy using ssh, falling back to https.
Successfully cloned repository loopy.
Checking out branch main
Successfully checked out branch main
Updating submodules.
Successfully updated submodules.
Cloning icepack

Failed to clone icepack using ssh, falling back to https.
Successfully cloned repository icepack.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning the dependencies of icepack
Installing petsc/
Downloading Eigen from 'https://github.com/eigenteam/eigen-git-mirror/archive/3.3.3.tar.gz' to 'eigen-3.3.3.tgz'
Checking Eigen tarball integrity
Eigen tarball hash valid
Depending on your platform, PETSc may take an hour or more to build!
Installing pip dependencies for COFFEE
Installing pip dependencies for loopy
Installing pip dependencies for petsc4py
No dependencies found. Skipping.
Installing pip dependencies for ufl
No dependencies found. Skipping.
Installing pip dependencies for fiat
No dependencies found. Skipping.
Installing pip dependencies for FInAT
Installing pip dependencies for tsfc
Installing pip dependencies for PyOP2
Installing pip dependencies for pyadjoint
No dependencies found. Skipping.
Installing pip dependencies for firedrake
Traceback (most recent call last):
  File "firedrake-install", line 1627, in <module>
    pip_requirements(p, compiler_env)
  File "firedrake-install", line 832, in pip_requirements
    run_pip_install_wrap(reqs, parallel_compiler_env)
  File "firedrake-install", line 825, in run_pip_install_wrap
    run_pip_install([req])
  File "firedrake-install", line 806, in run_pip_install
    check_call(pipinstall + pipargs)
  File "firedrake-install", line 520, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/opt/homebrew/Cellar/python@3.8/3.8.12/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.8/3.8.12/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/simondriscoll/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy,scipy', '-vvv', 'vtk==9.0.1']' returned non-zero exit status 1.

Install log saved in /Users/simondriscoll/firedrake-install.log
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/7225802/firedrake-install.log)

It takes over an hour on my Mac to run/see if it has installed, and is time consuming to retry etc. without guidance (or much more useful with some expert eyes!), so I hope it's ok to ask for guided tips as to installing icepack this way. Can anyone give me any suggestions as to what I might try? I think the key error is "No matching distribution found for vtk==9.0.1". But I'm not sure if others could be tried. Thanks!

**Comment by connorjward** [comment]
```
ERROR: Could not find a version that satisfies the requirement vtk==9.0.1 (from versions: none)
ERROR: No matching distribution found for vtk==9.0.1
```
I think you are right. @JDBetteridge has a fair bit of experience with VTK + Firedrake. Jack?

**Comment by JDBetteridge** [comment]
You stated you were on a Mac, is it an ARM based (M1) Mac by any chance? We should make that more obvious in the install log, but I think you may well be.

Unfortunately, we don't currently have a wheel for Python 3.8 for M1 Macs. Is there a reason you have Python 3.8 rather than 3.9? If you want you can try building a VTK wheel yourself and contribute it back to our repo, but the simpler solution would be to update your Python and try reinstalling.

**Comment by danshapero** [comment]
I'm going to close this for lack of activity, @simondriscoll please feel free to reopen if you need more assistance with the installation. Since this issue came up there have been some further problems installing on M1 but these should be fixed by now.
