### ISSUE TITLE
We don't have a working R space

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#226]
This has been raised as an issue a few times. However I think we may now have an idea how to do this efficiently in parallel.  Please see the documentation at http://www.firedrakeproject.org/r-space.html

Comments on this are solicited before we try to actually do it.

**Comment by wence-** [comment]
I think I also know how to provide an efficient solve for this.  Eliminate the real variable using a schur complement, so you end up with the operator for the rest of the system + a rank one update coming from the outer product of the row and column "vectors" that couple into the rest of the system.  Now you can use sherman-morrison to compute a good preconditioner.  It "just" remains to think how to hook this up transparently.

**Comment by wence-** [comment]
We sort of do now.
