### ISSUE TITLE
The problem about load the unstructure grid with .exo file format

### ISSUE THREAD

**Issue by tu1620808124** [firedrakeproject/firedrake#2264]
Hello, when I use the mesh with .exo file format with Mesh("***.exo"), the error appeared:

DMPlexCreateExodusFromFile() at /home/jltu/jltu/firedrake/src/petsc/src/dm/impls/plex/plexexodusii.c:1356
[0] No support for this operation for this object type
[0] This method requires ExodusII support. Reconfigure using --download-exodusii

so, I try to do :
cd /home/jltu/jltu/firedrake/src/petsc
./configure --download-exodusii

but this problem still exit,  and how I should to do configure ExodusII in firedrake?

**Comment by wence-** [comment]
You will need to rebuild the PETSc that `firedrake-install` produces for you (there are some instructions here: https://github.com/firedrakeproject/firedrake/wiki/Modifying-and-Rebuilding-PETSc-and-petsc4py-in-Firedrake).

In your case the process will be:

1. activate venv
2. Run `PETSC_CONFIGURE_OPTIONS=--download-exodusii firedrake-update --rebuild`
3. Wait a while...

**Comment by tu1620808124** [comment]
thank you very much!
