### ISSUE TITLE
Installation Problem within the PETSc install

### ISSUE THREAD

**Issue by andreichalapco** [firedrakeproject/firedrake#2276]
I get a `subprocess.CalledProcessError` when trying to install PETSc.

When looking in the logs the following appears:

Error during download/extract/detection of HWLOC : 
Error changing permissions for hwloc-2.5.0 obtained from /home/xxx/Desktop/firedrake setup/firedrake/src/petsc/default/externalpackages/_d_hwloc-2.5.0.tar.gz : Could not execute "['cd /home/xxx/Desktop/firedrake setup/firedrake/src/petsc/default/externalpackages; chmod -R a+r hwloc-2.5.0;find  hwloc-2.5.0 -type d -name "*" -exec chmod a+rx {} \\;']":

**Comment by wence-** [comment]
Something is odd here, you should have permissions in those directories (or certainly if you didn't the installer would have failed earlier).
Can you the contents of `/home/xxx/Desktop/firedrake/src/petsc/configure.log` ?

**Comment by andreichalapco** [comment]
Hi,

I've changed the machine I was working one (using the same ubuntu version as before), but now the installation works. So the issue can be closed  now.

I think the problem was very specific to the machine I used before ... (or I've mistakenly changed some download configurations).
