### ISSUE TITLE
the problem about DirichletBC for the DG method

### ISSUE THREAD

**Issue by tu1620808124** [firedrakeproject/firedrake#2287]
hi, I want to use the DG with DirichletBC, but it's seems the boundary nodes can't get from the functionspace, just like I try to test like this:
```
from  firedrake import*
mesh = UnitSquareMesh(20,20)
V = FunctionSpace(mesh,"DG", 0) 
print(V.boundary_nodes(1))
```
```
[]
```
but if i change the DG(0) to CG(1)
```
from  firedrake import*
mesh = UnitSquareMesh(20,20)
V = FunctionSpace(mesh,"CG", 1) 
print(V.boundary_nodes(1))
```
```
[  0   1   5   9  14  20  27  35  44  54  65  77  90 104 119 135 152 170 189 209 230]
```
it  return the suitable boundary nodes. 
so, if there have any other method to use the  DirichletBC to the DG method?

**Comment by wence-** [comment]
We recommend enforcing dirichlet conditions on DG spaces weakly by penalising the jump (as you would for interior face terms).

Rationale/details:

The reason we don't advertise any nodes on the boundary for a DG space is because they aren't actually on the boundary (the topological association is all with the cell).

While for some choices of basis, the nodes might be _geometrically_ associated with the boundary, this is mathematically dubious: the usual definition would be to ask which nodes have non-zero support on the boundary facets, and for a DG space the answer depends on the choice of dual basis. Another way of thinking about this is that the trace of an L2 function is not well-defined, so it kind of doesn't make sense to split the functionspace as is required for strong boundary conditions.

**Comment by tu1620808124** [comment]
I probably get it. "DirichletBC()" don't work in DG. how to get the different bounds in unstructure grid(just like  dS can identify interior face terms) , Are there simple example to refer to?

**Comment by wence-** [comment]
You can use `ds` to integrate over exterior faces. Any faces that you had marked with particular tags can be selected with `ds(1)` (say). We have an example that walks through the formulation for a DG advection problem (which imposes an inflow condition weakly in this manner) here https://firedrakeproject.org/demos/DG_advection.py.html

**Comment by tu1620808124** [comment]
For example when I consider a poisson equation like this
<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{aligned}&space;&-\nabla^{2}&space;u=f&space;\;&space;\text{&space;in&space;}&space;\Omega&space;\\&space;&u=0&space;\;&space;\text{&space;on&space;}&space;\Gamma_{D}&space;\quad&space;\nabla&space;u&space;\cdot&space;\mathbf{n}=g&space;\;&space;\text{&space;on&space;}&space;\Gamma_{N}&space;\end{aligned}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{aligned}&space;&-\nabla^{2}&space;u=f&space;\;&space;\text{&space;in&space;}&space;\Omega&space;\\&space;&u=0&space;\;&space;\text{&space;on&space;}&space;\Gamma_{D}&space;\quad&space;\nabla&space;u&space;\cdot&space;\mathbf{n}=g&space;\;&space;\text{&space;on&space;}&space;\Gamma_{N}&space;\end{aligned}" title="\begin{aligned} &-\nabla^{2} u=f \; \text{ in } \Omega \\ &u=0 \; \text{ on } \Gamma_{D} \quad \nabla u \cdot \mathbf{n}=g \; \text{ on } \Gamma_{N} \end{aligned}" /></a>
and the weak form is :
<a href="https://www.codecogs.com/eqnedit.php?latex=\int_{\Omega}&space;\nabla&space;u&space;\cdot&space;\nabla&space;v&space;\mathrm{~d}&space;x-\int_{\partial&space;\Omega}&space;v&space;\nabla&space;u&space;\cdot&space;\mathbf{n}&space;\mathrm{d}&space;s=\int_{\Omega}&space;f&space;v&space;\mathrm{~d}&space;x\;\text{for&space;all}&space;\;v" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\int_{\Omega}&space;\nabla&space;u&space;\cdot&space;\nabla&space;v&space;\mathrm{~d}&space;x-\int_{\partial&space;\Omega}&space;v&space;\nabla&space;u&space;\cdot&space;\mathbf{n}&space;\mathrm{d}&space;s=\int_{\Omega}&space;f&space;v&space;\mathrm{~d}&space;x\;\text{for&space;all}&space;\;v" title="\int_{\Omega} \nabla u \cdot \nabla v \mathrm{~d} x-\int_{\partial \Omega} v \nabla u \cdot \mathbf{n} \mathrm{d} s=\int_{\Omega} f v \mathrm{~d} x\;\text{for all} \;v" /></a>
if choose the DG(0) space maybe :

<a href="https://www.codecogs.com/eqnedit.php?latex=\int_{\Gamma_{\text&space;{int&space;}}}\left(v^{&plus;}-v^{-}\right)&space;\frac{u^{&plus;}-u^{-}}{\left\|h^{&plus;}-h^{-}\right\|}&space;\mathrm{d}&space;S-\int_{\Gamma_{D}}&space;v&space;\frac{f-u}{d_{\Gamma_{D}}(h)}&space;\mathrm{d}&space;s-\int_{\Gamma_{N}}&space;v&space;g&space;\mathrm{~d}&space;s=\int_{\Omega}&space;f&space;v&space;\mathrm{~d}&space;x\;\text{for&space;all}&space;\;v" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\int_{\Gamma_{\text&space;{int&space;}}}\left(v^{&plus;}-v^{-}\right)&space;\frac{u^{&plus;}-u^{-}}{\left\|h^{&plus;}-h^{-}\right\|}&space;\mathrm{d}&space;S-\int_{\Gamma_{D}}&space;v&space;\frac{f-u}{d_{\Gamma_{D}}(h)}&space;\mathrm{d}&space;s-\int_{\Gamma_{N}}&space;v&space;g&space;\mathrm{~d}&space;s=\int_{\Omega}&space;f&space;v&space;\mathrm{~d}&space;x\;\text{for&space;all}&space;\;v" title="\int_{\Gamma_{\text {int }}}\left(v^{+}-v^{-}\right) \frac{u^{+}-u^{-}}{\left\|h^{+}-h^{-}\right\|} \mathrm{d} S-\int_{\Gamma_{D}} v \frac{f-u}{d_{\Gamma_{D}}(h)} \mathrm{d} s-\int_{\Gamma_{N}} v g \mathrm{~d} s=\int_{\Omega} f v \mathrm{~d} x\;\text{for all} \;v" /></a>

but I don`t kown how to deal with the <a href="https://www.codecogs.com/eqnedit.php?latex={d_{\Gamma_{D}}(h)}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?{d_{\Gamma_{D}}(h)}" title="{d_{\Gamma_{D}}(h)}" /></a>

**Comment by wence-** [comment]
I think you want FacetArea(mesh)
