### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by Abdalaziz00** [firedrakeproject/firedrake#2291]
Could you please create a Zenodo release?

Thanks,
Abdalaziz
[firedrake.txt](https://github.com/firedrakeproject/firedrake/files/7636976/firedrake.txt)

**Comment by wence-** [comment]
Tag is `Firedrake_20211206.1`
DOI is 10.5281/zenodo.5762546
Zenodo URL is https://zenodo.org/record/5762546
BibTeX

```bibtex
@misc{zenodo/Firedrake-20211206.1,
 key   = {zenodo/Firedrake-20211206.1},
 title = {{Software used in `A new mixed finite-element method for H^2 elliptic problems'}},
 year  = {2021},
 month = {dec},
 doi   = {10.5281/zenodo.5762546},
 url   = {https://doi.org/10.5281/zenodo.5762546},
}

```

Thanks! And sorry for the delay.
