### ISSUE TITLE
Zenodo request

### ISSUE THREAD

**Issue by NBoulle** [firedrakeproject/firedrake#2293]
Hi,

Can someone create a Zenodo release of the following file ?
[firedrake.txt](https://github.com/firedrakeproject/firedrake/files/7650430/firedrake.txt)

Thanks!

**Comment by wence-** [comment]
Tag is `Firedrake_20211206.0`
DOI is 10.5281/zenodo.5762538
Zenodo URL is https://zenodo.org/record/5762538
BibTeX

```bibtex
@misc{zenodo/Firedrake-20211206.0,
 key   = {zenodo/Firedrake-20211206.0},
 title = {{Software used in `Optimal control of Hopf bifurcations'}},
 year  = {2021},
 month = {dec},
 doi   = {10.5281/zenodo.5762538},
 url   = {https://doi.org/10.5281/zenodo.5762538},
}

```

Thanks!
