### ISSUE TITLE
scipy link errors

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#2312]
This appears to be the same issue that is occurring in master (and probably coming from upstream). I will investigate further!

```
>   import scipy.linalg._interpolative as _id
E   ImportError: /__w/firedrake/build/lib/python3.8/site-packages/scipy/linalg/_interpolative.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZGVbN2v_cos
```

_Originally posted by @JDBetteridge in https://github.com/firedrakeproject/firedrake/issues/2307#issuecomment-1005870934_

**Comment by wence-** [comment]
Can't reproduce in `docker run -ti ubuntu:20.04`. @JDBetteridge what are precise reproduction steps?

**Comment by JDBetteridge** [comment]
On Arch Linux (with Python 3.10.1, gcc 11.1.0, glibc 2.33) in a fresh virtual environment:
```
pip install -U setuptools
pip install -U pip
pip install -U wheel
pip install Cython
pip install pybind11
pip install --no-build-isolation --no-binary numpy numpy
pip install pythran
pip install -v --no-build-isolation --no-binary numpy,scipy scipy
```

I haven't tried reproducing the issue in Docker yet

**Comment by JDBetteridge** [comment]
Additionally, I'm also hitting:
```python -c "import scipy.stats._stats as _st"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jack/Documents/firedrake/scipy_issue/lib/python3.10/site-packages/scipy/stats/__init__.py", line 441, in <module>
    from .stats import *
  File "/home/jack/Documents/firedrake/scipy_issue/lib/python3.10/site-packages/scipy/stats/stats.py", line 43, in <module>
    from . import distributions
  File "/home/jack/Documents/firedrake/scipy_issue/lib/python3.10/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "/home/jack/Documents/firedrake/scipy_issue/lib/python3.10/site-packages/scipy/stats/_continuous_distns.py", line 22, in <module>
    from . import _stats
  File "_stats.pyx", line 1, in init scipy.stats._stats
ImportError: /home/jack/Documents/firedrake/scipy_issue/lib/python3.10/site-packages/scipy/special/cython_special.cpython-310-x86_64-linux-gnu.so: undefined symbol: _gfortran_stop_numeric
```
Although we're unlikely to see this one in CI

**Comment by wence-** [comment]
Scipy issue is scipy/scipy#15414 (and for the latter problem scipy/scipy#8325).

Are we convinced we need to hand-build scipy? AFAICT on macos I can use the wheel and the issues in #1800 don't occur.

**Comment by JDBetteridge** [comment]
I'm not at all convinced scipy needs to be built by hand. I believe originally this was a precaution against seeing the same BLAS/LAPACK linking issues and FORTRAN ABI incompatibility that we saw in numpy. Reading the docs and through observation this doesn't seem to be the case.

I don't see the issue using the scipy wheel on Arch and the CI doesn't see the issue on Ubuntu 20.04 either. We could make PR #2313 a permanent change if desired.

**Comment by JDBetteridge** [comment]
Fixed in
- https://github.com/scipy/scipy/issues/15414
- https://github.com/firedrakeproject/firedrake/pull/2313
