### ISSUE TITLE
Installation failure on MacOS

### ISSUE THREAD

**Issue by sv2518** [firedrakeproject/firedrake#2315]
Hi. I broke my Firedrake install from last week and tried to install a new one today but there is an issue with the install (with mpich I think). Unfortunately I deleted the venv from last week already and can't recall what the error message was. What happened between last and this week is (I think) is that I somehow broke my old Firedrake version when I was reinstalling docker and virtual box. I might have run a `brew upgrade` in the process.

To fix my install I have tried to run the install once with a `brew link mpich` before, which failed, and `brew unlink mpich`, which failed too. No venv was active.
 These are all not really helpful information, here are the ones that I can give you:
 
  My System Version is: macOS 10.15.7

`gcc --version` says
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

`brew doctor` says
[doctoroutput.txt](https://github.com/firedrakeproject/firedrake/files/7904729/doctoroutput.txt)

install log is:
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/7904733/firedrake-install.log)

petsc configure log is
[configure.log](https://github.com/firedrakeproject/firedrake/files/7904961/configure.log)

`echo $PATH` says
`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin`

Can someone help me figure out what I need to do to get the install running again?

**Comment by sv2518** [comment]
I will try to follow the suggestions in https://github.com/firedrakeproject/firedrake/issues/2017 and keep track of it here

**Comment by sv2518** [comment]
The output of `/Users/sv2518/firedrakeinstalls/fresh/firedrake/bin/python -c "import sysconfig; print(sysconfig.get_config_var('PY_CORE_LDFLAGS'))"` is
`-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -L/usr/local/lib -Wl,-rpath,/usr/local/lib -flto -Wl,-export_dynamic -g` which is what we want according to @wence- comment in the other issue.


The output of `mpicc -v` with the new venv activated says
```
mpicc for MPICH version 3.4.2
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
clang: warning: argument unused during compilation: '-I /usr/local/opt/openblas/include' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-Wno-implicit-function-declaration' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-fPIC' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-g' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-O3' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-Wno-implicit-function-declaration' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-I /Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/default/include' [-Wunused-command-line-argument]
```


The output of `/Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/default/bin/mpicc -show` says
```
gcc -I/usr/local/opt/openblas/include -Wno-implicit-function-declaration -fPIC -g -O3 -Wno-implicit-function-declaration -Wl,-rpath,/usr/local/opt/openblas/lib -L/usr/local/opt/openblas/lib -L/Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/default/lib -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/default/include -L/Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/default/lib -lmpi -lpmpi
```


And then I tried to run the following code in a foo file
```
#include <mpi.h>
#include <petsc.h>
#include <stdio.h>
int main(void):
{
  printf("%d %d\n", MPICH_NUMVERSION,  PETSC_HAVE_MPICH_NUMVERSION);
  return 0;
}
```
with` /Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/default/bin/mpicc -I/Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/include foo.c -o foo`
and it errors with
```
In file included from /Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/include/petsc.h:5:
In file included from /Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/include/petscbag.h:4:
/Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/include/petscsys.h:15:10: fatal error: 
      'petscconf.h' file not found
#include <petscconf.h>
         ^~~~~~~~~~~~~
1 error generated.
```

Is there anyone who can deduce anything useful from all this?

**Comment by wence-** [comment]
What is the contents of the petsc configure.log from the failed install?

**Comment by sv2518** [comment]
Its in the decription of the issue, I edited this later.

**Comment by wence-** [comment]
Hmm, this looks bad:
```ignoring file /Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/default/lib/libpmpi.dylib, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 )```

and

```
make[1]: Leaving directory '/Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/default/externalpackages/mpich-3.4.2'/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/default/lib/libpmpi.a(lib_libpmpi_la-mpir_netloc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/default/lib/libpmpi.a(mpl_dbg.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/default/lib/libpmpi.a(mpl_thread.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: /Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/default/lib/libmpifort.a(mpi_base.o) has no symbols
********End of Output of running make on MPICH *******
```

Does this directory exist? `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk`

**Comment by wence-** [comment]
I think we can ignore the firedrake-install part of this for now and purely focus on the PETSc part.

What does `gfortran --version` say?

Can you run:
```
./configure --download-mpich=1
```
successfully in the PETSc checkout?

**Comment by sv2518** [comment]
In `/Library/Developer/CommandLineTools/SDKs/MacOS*` there is `MacOSX.sdk/      MacOSX10.15.sdk/ MacOSX11.1.sdk/  `

`gfortran --version` says
```
GNU Fortran (Homebrew GCC 11.2.0_3) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by sv2518** [comment]
No I could not run the configure successfully in the petsc dir. It fails with `Error with downloaded MPICH: Cannot compile/link C with /Users/sv2518/firedrakeinstalls/fresh/firedrake/src/petsc/arch-darwin-c-debug/bin/mpicc.`

**Comment by sv2518** [comment]
I noticed that I am running explicitly with `/usr/local/bin/python3` but the configure log says `Installer running with: /usr/local/opt/python@3.9/bin/python3.9`, that might be an issue?

**Comment by wence-** [comment]
I _think_ that petsc-maint did their magic and this was fixed, is that right?

**Comment by sv2518** [comment]
Sorry yes this was resolved. I just wanted to update this issue with a) the procedure to track down what is going on and b) what was the issue, but forgot.

PETSc folk advised to try a simpler install first with
`PATH=/usr/bin:/bin:/usr/sbin:/sbin ./configure --download-mpich --with-cc=/usr/bin/clang --with-fc=0 --with-cxx=0 PETSC_ARCH=arch-test `
 If that works try with my own path
`./configure --download-mpich --with-cc=/usr/bin/clang --with-fc=0 --with-cxx=0 PETSC_ARCH=arch-test2`
and then to enable fortran/c++ with
`./configure --download-mpich --with-cc=/usr/bin/clang --with-fc=/usr/local/bin/gfortran --with-cxx=/usr/bin/clang++ PETSC_ARCH=arch-test3`

The problem was that I had `ginstall` installed as part of `coreutils`. So I brew uninstalled coreutils and kicked of another PETSc configure run with my PATH changed back to what it was. This was successful and the Firedrake install after that too.
