### ISSUE TITLE
petsc4py installation failure

### ISSUE THREAD

**Issue by tjung1234** [firedrakeproject/firedrake#2316]
Hi! 

I am trying to install firedrake on mac (big sur) but the installation fails at petsc4py stage.
firedrake-install.log gives me this error:
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
Cannot use PaStiX without Fortran, make sure you do NOT have --with-fc=0
*******************************************************************************
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/7930393/firedrake-install.log)

I am not at all familiar with working in terminal and the whole installation process has been quite a challenge.
Any help would be really appreciated. Thanks!

Here is configure.log:
[configure.log](https://github.com/firedrakeproject/firedrake/files/7930392/configure.log)

which python3 gives me:
/Users/taehojung/firedrake/bin/python3

which gfortran gives me:
/usr/local/bin/gfortran

Brew doctor says:
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/taehojung/firedrake/bin/pybind11-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3-config

**Comment by danshapero** [comment]
Did you ever find a solution for this and if so can you post what it was?
