### ISSUE TITLE
Documentation on the firedrake-install script

### ISSUE THREAD

**Issue by andreichalapco** [firedrakeproject/firedrake#2318]
Hi,

As discussed with one of the developers of Firedrake, I've come to the conclusion that the Firedrake install script needs a documentation on the internal mechanism. One reason for this is the fact that many people patch this script, but only fix their issue and not the underlying issue. So, a documentation would, I hope, bring more clarity to the script and help developers fix issues or refactor the code for future releases.

I hope it is alright with you if I would start working on it. If you have any tips I would gladly appreciate if you would leave it here.

**Comment by dham** [comment]
I am never ever going to say no to offers of documentation! Shout as soon as you have any questions.

**Comment by andreichalapco** [comment]
So I will make a fork of the original repository and create a pull request. Will this issue be assigned to me or?
