### ISSUE TITLE
Compilation issues (and possible solutions) for MacOS Monterey (12.1)

### ISSUE THREAD

**Issue by omarjamil** [firedrakeproject/firedrake#2320]
Upgrading to latest MacOS seems to break firedrake install. The main error that comes up is `ld: file not found: @rpath/libgcc_s.1.1.dylib for architecture arm64` This could be due to homebrew moving the library to a different location, but I have not been able to compare to pre-upgrade location. Doing `export LDFLAGS="-L/opt/homebrew/opt/gcc/lib/gcc/11"` before running `firedrake-install` solves the issue for firedrake installation. 

The above, however, is not enough to pass the tests. The test failures are due to pyop2 compilation failures (mpicc) and again not finding `libgcc_s.1.1.dylib`. This can be fixed by adding to `ldargs` in `parloop.py` line 409. Something like: ` ["%s" % os.environ['LDFLAGS']]`. Not sure that is the best way to get pyop2 to pick up this additional flag.

**Comment by wence-** [comment]
What library in particular is not being linked correctly? I don't think that one should need to do magic for a different homebrew location.

Is `brew doctor` free of complaints?

**Comment by omarjamil** [comment]
It could not find that library during petsc4py compilation. There is one warning from brew doctor: find replacement for `tbb@2020`

**Comment by wence-** [comment]
OK, if the problem is linking petsc4py, can we first check that PETSc is linked correctly?

In the failed install directory go to: `src/petsc` and do:
```
$ export PETSC_DIR=`pwd`
$ export PETSC_ARCH=default
$ make check
```

I _think_ that what is going on is that brew has updated gcc/gfortran, but not python (which somehow knows about the old versions?)

**Comment by omarjamil** [comment]
Doing above gives warnings, but no errors. The `ld` warning warnings are:
```
libmpifort.dylib) was built for newer macOS version (12.1) than being linked (12.0)
libcmumps.a(cana_aux.o)) was built for newer macOS version (12.1) than being linked (12.0)
....
```
I have seen these warnings before on macOS 11, but did not lead to build errors.

**Comment by bourdin** [comment]
I am having the same issue (see thread on slack).
Adding LDFLAGS to Compiler._ldargs (src/PyOP2/pyop2/compilation.py:188) seems to solve the issue. In my case, PETSc is properly compiled (after setting LDFLAGS) and passes make check.
This is not a satisfying fix, though. It would be better to understand why `libgcc_s` is not found (on my system, it is in `/opt/homebrew/opt/gcc/lib/gcc/11`

**Comment by dham** [comment]
I can confirm that I can see this on a completely clean and new M1 and that the workarounds suggested work. I will give some thought to what the proper fix is.

**Comment by adofarsi** [comment]
Hi @omarjamil, I was able to install Firedrake on my MacBook Air (M1, 2020) by doing `export LDFLAGS="-L/opt/homebrew/opt/gcc/lib/gcc/11" `before running the firedrake-install script. Firedrake still fails as pointed out in your post, as I get an error as soon as I run the `solve` function in my python code. I have tried to modify `parloop.py` but I couldn't understand where to add ` ["%s" % os.environ['LDFLAGS']]` in line 409 in the `parloop.py` source code. When I open `parloop.py`,  line 409 is the end of a docstring (see figure below):

<img width="677" alt="image" src="https://user-images.githubusercontent.com/18035301/156035126-572872a4-1fdc-499b-a872-07bfedba640b.png">

How should I implement the workaround to fix this?

Thank you for your time!

> Upgrading to latest MacOS seems to break firedrake install. The main error that comes up is `ld: file not found: @rpath/libgcc_s.1.1.dylib for architecture arm64` This could be due to homebrew moving the library to a different location, but I have not been able to compare to pre-upgrade location. Doing `export LDFLAGS="-L/opt/homebrew/opt/gcc/lib/gcc/11"` before running `firedrake-install` solves the issue for firedrake installation.
> 
> The above, however, is not enough to pass the tests. The test failures are due to pyop2 compilation failures (mpicc) and again not finding `libgcc_s.1.1.dylib`. This can be fixed by adding to `ldargs` in `parloop.py` line 409. Something like: ` ["%s" % os.environ['LDFLAGS']]`. Not sure that is the best way to get pyop2 to pick up this additional flag.

**Comment by dham** [comment]
It's now line 390 of `compilation.py`. I've also created a PyOP2 branch with this on it. Check out the `pass_ld_flags` branch.

If it's a fresh Firedrake install then pass `--package-branch PyOP2 pass_ld_flags` to cause this branch to be chosen.

**Comment by adofarsi** [comment]
Thanks @dham ! I can confirm that after reinstalling a fresh Firedrake with `python3 firedrake-install --package-branch PyOP2 pass_ld_flags` it works fine!

**Comment by adofarsi** [comment]
Apologies if it's off topic, but I believe that this is related to a similar problem as above. The python gmsh API works fine on my conda virtual enviroment, but on the Firedrake venv I get the following error when I `import gmsh`:
```
>>> import gmsh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adofarsi/firedrake/lib/python3.9/site-packages/gmsh-4.8.4-MacOSX-sdk/lib/gmsh.py", line 40, in <module>
    lib = CDLL(libpath)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/adofarsi/firedrake/lib/python3.9/site-packages/gmsh-4.8.4-MacOSX-sdk/lib/libgmsh.dylib, 0x0006): tried: '/Users/adofarsi/firedrake/lib/python3.9/site-packages/gmsh-4.8.4-MacOSX-sdk/lib/libgmsh.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libgmsh.dylib' (no such file), '/usr/lib/libgmsh.dylib' (no such file)
```
Do you have any workaround to fix this? Thank you!

**Comment by dham** [comment]
@adofarsi that looks like a different issue. It appears to be the case that the gmsh python package you have installed is compiled for Intel not for M1.

**Comment by adofarsi** [comment]
@dham Thanks for the hint! For some reason when `pip install gmsh` from conda environment it was installing the correct arm64 wheels, but it was installing the x86 wheels from the Firedrake virtual environment.
I have solved this issue by installing gmsh in the Firedrake virtual environment with `pip install git+https://github.com/lukeolson/gmsh-python-homebrew`.
See [https://github.com/lukeolson/gmsh-python-homebrew](url) for more info.

**Comment by dham** [comment]
We claim #2408 fixes installation on M1 Please open a new issue if there are M1 installation problems past this point.
