### ISSUE TITLE
Zenodo release for a paper

### ISSUE THREAD

**Issue by marazzaf** [firedrakeproject/firedrake#2322]
[firedrake.zip](https://github.com/firedrakeproject/firedrake/files/7944556/firedrake.zip)

Hello,
I would like to create a Zenodo version to cite a repository with code a paper.

Thank you for your kind help.
Best,
Dr. Frederic Marazzato.

**Comment by wence-** [comment]
Just FYI it looks like the `README.txt` you included with the `--info-file` argument was empty. Was that deliberate?

**Comment by marazzaf** [comment]
Hello,
My bad. I did not pay enough attention to that. Do you need some more description?
I was thinking about creating a REDAME.txt later.

**Comment by wence-** [comment]
No we don't need it at all. But the way this archiving works, is that it incorporates the "info-file" in the final zenodo release (which has a DOI attached), so you can't modify that file later (without making a new release).

The "info-file" is entirely optional, so I can just make a release without it if you like.

**Comment by marazzaf** [comment]
Hello again,

I understand. I'm sorry for disturbing you then.

I'll make another request later with a README file.

Thank you for your help.

Best.
--

Dr. Frédéric Marazzato

phone: +1 (225) 441-7013

email : ***@***.***

**Comment by marazzaf** [comment]
Thank you so much.
