### ISSUE TITLE
CentOS installation

### ISSUE THREAD

**Issue by VictorEijkhout** [firedrakeproject/firedrake#2323]
I'm trying to just let firedrake do its thing.

```
FileNotFoundError: [Errno 2] No such file or directory: 'apt-get': 'apt-get'
```

Is FD an ubuntu-only package? I think my package manager is yum. How do I specify that?

**Comment by danshapero** [comment]
Hi Victor! The install script is only set up to work with apt on Linux or homebrew on Mac, but not with yum, pacman, or the other package managers for different Linux distros. We could probably stand to have better error messages about this.

The solution is to first make sure that the dependencies listed [here](https://firedrakeproject.org/download.html#system-requirements) or from the output of `python3 firedrake-install --show-dependencies` are already installed via yum. I'm guessing you already have all of this stuff installed anyway -- it's things like flex, bison, cmake, etc. Then run the Firedrake install script with `--no-package-manager`. @JDBetteridge and I both use Firedrake on arch linux and this has worked fine for the both of us, so hopefully it should work on CentOS too.
