### ISSUE TITLE
Where does it say that Eigen is required?

### ISSUE THREAD

**Issue by VictorEijkhout** [firedrakeproject/firedrake#2325]
```
    raise ValueError("""Could not find Eigen configuration in %s. Did you build PETSc with Eigen?""" % PETSC_ARCH or PETSC_DIR)
ValueError: Could not find Eigen configuration in /work/00434/eijkhout/petsc/petsc-3.16.3/clx-intel-firedrake. Did you build PETSc with Eigen?
```

I don't think I'm asking for Eigen. Shouldn't the install process somewhere tell me that it is required?

**Comment by connorjward** [comment]
You are informed that you need Eigen if you execute `python3 firedrake-install --show-petsc-configure-options`. For example on my machine I see:
```
Running firedrake-install --show-petsc-configure-options
*********************************************
Would build PETSc with the following options:
*********************************************

--download-mpich
--download-hypre
--with-fortran-bindings=0
--download-scalapack
--download-hdf5
--download-netcdf
--download-pastix
--download-mumps
--download-hwloc
--download-suitesparse
--with-debugging=0
--download-eigen=/home/connor/Downloads/firedrake/src/eigen-3.3.3.tgz
--download-pnetcdf
--download-ml
--with-c2html=0
--with-cxx-dialect=C++11
--download-chaco
--download-ptscotch
--download-superlu_dist
--download-metis
--with-zlib
--with-shared-libraries=1

Eigen will be downloaded from https://github.com/eigenteam/eigen-git-mirror/archive/3.3.3.tar.gz


Install log saved in /home/connor/Downloads/firedrake-install.log
```

**Comment by danshapero** [comment]
As Connor points out, the install script asks PETSc to build Eigen -- you don't need to have it installed yourself. For that reason, I suspect that the real error message might be further up the stack, somewhere in the PETSc config or make logs. Can you check those to see if there's something else that failed?

**Comment by wence-** [comment]
@VictorEijkhout has built PETSc out of band (rather than asking `firedrake-install` to build it), and didn't explicitly know about the set of options to pass, I think.

**Comment by VictorEijkhout** [comment]
On , 2022Feb1, at 08:46, Lawrence Mitchell ***@***.******@***.***>> wrote:

built PETSc out of band (rather than asking firedrake-install to build it), and didn't explicitly know about the set of options to pass, I think.

Right. Yesterday I went through 1. Build firedrake 2. Run example, 3. Find out what’s missing in petsc 4. Rebuild petsc 5. Rebuild firedrake, ….  And repeat this several times.

It would have been nice if the firedrake install would have tested for components of petsc being present or not.

Victor.

**Comment by wence-** [comment]
> It would have been nice if the firedrake install would have tested for components of petsc being present or not.

This is a good idea. @JDBetteridge, petsc is actually quite good about this (we're already in some sense using a similar facility in `firedrake.petsc.get_petsc_variables`). Basically we need to look for `PETSC_HAVE_FOO` being defined in `$PETSC_DIR/$PETSC_ARCH/include/petscconf.h` for all of the required `FOO` packages.

**Comment by JDBetteridge** [comment]
We now test for and log installed PETSc components at install time, see #2345
