### ISSUE TITLE
firedrake-install installs conflicting versions of petsc4py and slepc4py

### ISSUE THREAD

**Issue by francesco-ballarin** [firedrakeproject/firedrake#2336]
I am in a clean `firedrakeproject/firedrake` docker container.

Running
```
pip3 list | grep c4py
```
returns
```
petsc4py                      3.15.4
slepc4py                      3.14.0
```

slepc4py seems to be pinned to 3.14 due to https://github.com/firedrakeproject/firedrake/blob/master/scripts/firedrake-install#L1233
and should be upgraded to >=3.15

Minimal failing example: create a new package with the following `setup.cfg` file
```
[metadata]
name = mytest 

[options]
install_requires =
   petsc4py
   slepc4py
```
try to install with pip and you will get the following output
```
Requirement already satisfied: slepc4py in /home/firedrake/firedrake/lib/python3.8/site-packages (from mytest==0.0.0) (3.14.0)
Requirement already satisfied: petsc4py in /home/firedrake/firedrake/lib/python3.8/site-packages (from mytest==0.0.0) (3.15.4)
Requirement already satisfied: numpy in /home/firedrake/firedrake/lib/python3.8/site-packages (from petsc4py->mytest==0.0.0) (1.22.0)
Collecting petsc4py
  Using cached petsc4py-3.14.1.tar.gz (2.1 MB)
  [.... tries to downgrade petsc4py, and actually fails ....]
```

**Comment by wence-** [comment]
Thanks. What should be happening is that you get the slepc4py that is packaged with the slepc source tree (see the following lines from the one you linked). So I wonder what went wrong (perhaps the slepc branch pointer needs updated).
