### ISSUE TITLE
BLASLAPACK_LIB not defined in complex mode

### ISSUE THREAD

**Issue by pbrubeck** [firedrakeproject/firedrake#2343]
Is there any particular reason why `BLASLAPACK_LIB` and `BLASLAPACK_INCLUDE` are undefined if `complex_mode == True` other than SLATE not being implemented in complex mode yet?

https://github.com/firedrakeproject/firedrake/blob/85dd96dfcb6fefb745bf7a79829ac92489758297/firedrake/slate/slac/compiler.py#L64

**Comment by JDBetteridge** [comment]
Closing since PR is merged
