### ISSUE TITLE
Firedrake wiki should document policies and procedures

### ISSUE THREAD

**Issue by connorjward** [firedrakeproject/firedrake#2355]
I think it would be very valuable to have our policies and procedures documented somewhere, and the wiki seems like the right place to do it. The type of content that we should record should be things like:

**Policies**
- When do we decide to stop supporting a particular version of Python
- How should we deal with stale issues

**Procedures**
- How to do a Zenodo release
- How to update one of our mirrored repositories (e.g. loopy, PETSc)
- How to rebuild the website

**Comment by ReubenHill** [comment]
Think this would be best moved to the discussions section?

**Comment by ReubenHill** [comment]
Okay

**Comment by JDBetteridge** [comment]
I have made a start, feel free to add more pages under the policy drop down on the wiki
https://github.com/firedrakeproject/firedrake/wiki/Closing-Installation-Issues
