### ISSUE TITLE
Error configuring ML with cmake

### ISSUE THREAD

**Issue by vabhi6** [firedrakeproject/firedrake#2377]
I am trying to install firedrake on my user directory of our HPC system. I have miniconda based Python 3.8 distribution. 
```
module load gnu/8.2.0 boost/1.68.0_gnu8.2 cmake/3.20.4 lapack/3.8.0
curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
python3 firedrake-install --with-blas="download" --no-package-manager --disable-ssh --mpicc mpicc --mpicxx mpicxx --mpif90 mpif90 --mpiexec mpiexec --honour-pythonpath
```
I have tried different options with firedrake-install and I keep hitting configuring ML with cmake error
[configure.log](https://github.com/firedrakeproject/firedrake/files/8200875/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/8200876/firedrake-install.log)

**Comment by danshapero** [comment]
@vabhi6 I'm hitting the same error and I can only work around it by installing with `--minimal-petsc`. Did you find a solution for this?

**Comment by vabhi6** [comment]
@danshapero I was not able to find a solution myself. However, the IT support staff at our lab was able to install firedrake without --minimal-petsc. He did mention that the ```firedrake-install``` makes assumptions about the location of some libraries. For example, this error for me was due to the fact that it could not find ```libblas.so```. He solved it by manually compiling the libraries. I can get you more info from him if needed.
