### ISSUE TITLE
Mixed Function Space Problem 

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2389]
​I try to solve the heat equation 

<img src="https://latex.codecogs.com/svg.image?\left\{\begin{matrix}&space;u_t&space;-&space;\Delta&space;u&space;=&space;0,&space;\quad&space;\Omega&space;=&space;[0,2\pi]\times[0,2\pi]&space;\\u(x,y,0)&space;=&space;\sin(x)\sin(y)&space;\&space;\end{matrix}\right." title="https://latex.codecogs.com/svg.image?\left\{\begin{matrix} u_t - \Delta u = 0, \quad \Omega = [0,2\pi]\times[0,2\pi] \\u(x,y,0) = \sin(x)\sin(y) \ \end{matrix}\right." />

with periodic boundary conditions . The exact solution is  <img src="https://latex.codecogs.com/svg.image?u(x,y,t)&space;=&space;e^{-2t}&space;\sin(x)\sin(y)&space;" title="https://latex.codecogs.com/svg.image?u(x,y,t) = e^{-2t} \sin(x)\sin(y) " />

​	Local Discontinuous Galerkin(LDG)  method is used for spatial discretization, we first introduce an auxiliary vector-valued variable  <img src="https://latex.codecogs.com/svg.image?\boldsymbol{p}" title="https://latex.codecogs.com/svg.image?\boldsymbol{p}" />

then find <img src="https://latex.codecogs.com/svg.image?u&space;\in&space;V,&space;\boldsymbol{p}&space;\in&space;\Sigma,&space;\forall&space;v&space;\in&space;V,&space;\boldsymbol{w}&space;\in&space;\Sigma" title="https://latex.codecogs.com/svg.image?u \in V, \boldsymbol{p} \in \Sigma, \forall v \in V, \boldsymbol{w} \in \Sigma" />, s.t.

<img src="https://latex.codecogs.com/svg.image?\begin{cases}\int_{\Omega}u_t&space;v&space;dx&space;&=&space;-\int_{\Omega}\boldsymbol{p}&space;\cdot&space;\nabla&space;v&space;dx&space;&plus;&space;\int_{\Gamma_{int}}&space;\hat{\boldsymbol{p}}&space;\cdot&space;[[v]]_{\boldsymbol{n}}&space;dS,\\&space;&space;\int_{\Omega}&space;{\boldsymbol{p}}&space;\cdot\boldsymbol{w}&space;dx&space;&=&space;-\int_{\Omega}&space;u&space;\nabla&space;\cdot&space;\boldsymbol{w}&space;dx&space;&plus;\int_{\Gamma_{int}}&space;\hat{u}&space;[[\boldsymbol{w}]]_{\boldsymbol{n}}&space;&space;dS&space;.\end{cases}" title="https://latex.codecogs.com/svg.image?\begin{cases}\int_{\Omega}u_t v dx &= -\int_{\Omega}\boldsymbol{p} \cdot \nabla v dx + \int_{\Gamma_{int}} \hat{\boldsymbol{p}} \cdot [[v]]_{\boldsymbol{n}} dS,\\ \int_{\Omega} {\boldsymbol{p}} \cdot\boldsymbol{w} dx &= -\int_{\Omega} u \nabla \cdot \boldsymbol{w} dx +\int_{\Gamma_{int}} \hat{u} [[\boldsymbol{w}]]_{\boldsymbol{n}} dS , \end{cases}" />

where the flux is 
<img src="https://latex.codecogs.com/svg.image?\hat{\boldsymbol{p}}&space;=&space;\boldsymbol{p}^{&plus;},&space;\hat{u}&space;=&space;u^{-}." title="https://latex.codecogs.com/svg.image?\hat{\boldsymbol{p}} = \boldsymbol{p}^{+}, \hat{u} = u^{-}." />

​	Two-stage, second-order  DIRK method is  used for time  discretization, to discretise  <img src="https://latex.codecogs.com/svg.image?u_t&space;=&space;L(u)," title="https://latex.codecogs.com/svg.image?u_t = L(u)," />
we set
<img src="https://latex.codecogs.com/svg.image?\begin{align*}&space;u^{(1)}&space;&=&space;u^{n}&space;&plus;&space;\Delta&space;t&space;a_{11}&space;L(u^{(1)}),&space;&space;\nonumber&space;\\u^{(2)}&space;&=&space;u^{n}&space;&plus;&space;\Delta&space;t&space;\left(&space;a_{21}&space;L(u^{(1)})&space;&plus;&space;a_{22}&space;L(u^{(2)})&space;&space;\right)&space;,&space;\\u^{n&plus;1}&space;&=&space;u^{n}&space;&plus;&space;\Delta&space;t&space;\left(&space;b_1&space;L(u^{(1)})&space;&plus;&space;b_{2}&space;L(u^{(2)})&space;&space;\nonumber&space;\right),\end{align*}" title="https://latex.codecogs.com/svg.image?\begin{align*} u^{(1)} &= u^{n} + \Delta t a_{11} L(u^{(1)}), \nonumber \\u^{(2)} &= u^{n} + \Delta t \left( a_{21} L(u^{(1)}) + a_{22} L(u^{(2)}) \right) , \\u^{n+1} &= u^{n} + \Delta t \left( b_1 L(u^{(1)}) + b_{2} L(u^{(2)}) \nonumber \right),\end{align*}" />
where <img src="https://latex.codecogs.com/svg.image?a_{11}&space;=&space;a_{22}&space;=&space;&space;\alpha,&space;&space;a_{12}&space;=&space;1-&space;\alpha,&space;b_{1}&space;=&space;1-\alpha,&space;b_{2}&space;=&space;\alpha,&space;\alpha&space;=&space;1-\frac{\sqrt{2}}{2}&space;" title="https://latex.codecogs.com/svg.image?a_{11} = a_{22} = \alpha, a_{12} = 1- \alpha, b_{1} = 1-\alpha, b_{2} = \alpha, \alpha = 1-\frac{\sqrt{2}}{2} " />

I follow the example of [Mixed formulation for the Poisson ](https://github.com/firedrakeproject/firedrake/blob/ac22e4c55d6fad32ddc9e936cd3674fb8a75f1da/demos/poisson/poisson_mixed.py.rst), but  there are some problems.
Here is my code:

```python
from firedrake import *
import math

Nx = 10; Ny = 10; 
Pk = 1
CFL = 0.1

Lx = 2*math.pi; Ly = 2*math.pi
Hx = Lx/Nx
mesh = PeriodicRectangleMesh(Nx, Ny, Lx, Ly, direction='both',quadrilateral=False, reorder=None, diagonal="right")
x, y = SpatialCoordinate(mesh)
n = FacetNormal(mesh)


V = FunctionSpace(mesh, "DG", Pk)
Simga = VectorFunctionSpace(mesh, "DG", Pk)
W = V * Simga


T = 0.001
dt = CFL * Hx
dtc = Constant(dt)


u_init = Function(V).interpolate(sin(x) * sin(y))
u = Function(W.sub(0))
u.assign(u_init)


# coefficients of SDIRK 
alpha = 1.0 - math.sqrt(2.0)/2.0
RK_a = Constant(alpha); RK_a21 = Constant(1.0 - alpha)
RK_b1 = Constant(1.0 - alpha); RK_b2 = Constant(alpha)


u_trial, p_trial = TrialFunctions(W)
v, w = TestFunctions(W)

LHS = u_trial * v *dx \
    - dtc*RK_a * ( -dot(p_trial,grad(v))*dx +  dot(p_trial('+'),jump( v,n))*dS ) \
    + dot(p_trial,w)*dx \
    - (-u_trial*div(w)*dx + u_trial('-')*jump(w,n)*dS)  
A = assemble(LHS)                                                                           
M = assemble( u_trial*v *dx)



p1 = Function(W.sub(1))
p2 = Function(W.sub(1))

L1 = u*v *dx
L2 =  u*v *dx + dtc * RK_a21 *(-dot(p1,grad(v))*dx +  dot( p1('+'),jump(v,n) )*dS)          
L = dtc * (RK_b1 * (-dot(p1,grad(v))*dx +  dot( p1('+'), jump(v,n) )*dS) \
        + RK_b2 * (-dot(p2,grad(v))*dx +  dot( p2('+'), jump(v,n) )*dS) )                  


w_solution = Function(W)


b = assemble(L1)
solve(A, w_solution, b)
p1.assign(w_solution.sub(1))


b = assemble(L2)
solve(A, w_solution, b)
p2.assign(w_solution.sub(1))

b = assemble(L)
solve(M, w_solution, b)
u.assign(u + w_solution.sub(0))



u_exact = pow(e, -2*T) * sin(x) * sin(y)
L2_error = norms.errornorm( u_exact, u, norm_type = "L2")

print("Nx = ",Nx ,", L2_error = ", L2_error)
```
Error:
```shell
Traceback (most recent call last):
  File "/home/mycode/Code/firedrake_code/Heat_LDG.py", line 71, in <module>
    solve(M, w_solution, b)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/mycode/firedrake/src/firedrake/firedrake/adjoint/solving.py", line 53, in wrapper
    output = solve(*args, **kwargs)
  File "/home/mycode/firedrake/src/firedrake/firedrake/solving.py", line 133, in solve
    return _la_solve(*args, **kwargs)
  File "/home/mycode/firedrake/src/firedrake/firedrake/solving.py", line 244, in _la_solve
    solver.solve(x, b)
  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/mycode/firedrake/src/firedrake/firedrake/linear_solver.py", line 162, in solve
    raise ConvergenceError("LinearSolver failed to converge after %d iterations with reason: %s", self.ksp.getIterationNumber(), solving_utils.KSPReasons[r])
firedrake.exceptions.ConvergenceError: ('LinearSolver failed to converge after %d iterations with reason: %s', 0, 'DIVERGED_PCSETUP_FAILED')
```

**Comment by zhyxue0** [comment]
I probably know why,  the last term 
<img src="https://latex.codecogs.com/svg.image?u^{n&plus;1}&space;=&space;u^{n}&space;&plus;&space;\Delta&space;&space;t&space;\left(&space;b_1&space;L(u^{(1)})&space;&plus;&space;b_{2}&space;L(u^{(2)}\right)" title="https://latex.codecogs.com/svg.image?u^{n+1} = u^{n} + \Delta t \left( b_1 L(u^{(1)}) + b_{2} L(u^{(2)}\right)" />
written in matrix form is 
<img src="https://latex.codecogs.com/svg.image?M_{u}&space;U^{n&plus;1}&space;=&space;M_{u}U^{n}&space;&plus;&space;L_{p}P^{(1)}&plus;&space;L_{p}P^{(2)}&space;" title="https://latex.codecogs.com/svg.image?M_{u} U^{n+1} = M_{u}U^{n} + L_{p}P^{(1)}+ L_{p}P^{(2)} ." />.

But when written as a mixed function space, we get
<img src="https://latex.codecogs.com/svg.image?\begin{pmatrix}M_u&space;&&space;O&space;\\O&space;&&space;&space;O\\\end{pmatrix}\begin{pmatrix}U^{n&plus;1}&space;\\P&space;&space;&space;\end{pmatrix}=&space;\begin{pmatrix}L&space;\\O&space;&space;&space;\end{pmatrix}" title="https://latex.codecogs.com/svg.image?\begin{pmatrix}M_u & O \\O & O\\\end{pmatrix}\begin{pmatrix}U^{n+1} \\P \end{pmatrix}= \begin{pmatrix}L \\O \end{pmatrix}" />
the matrix is singular.

**Comment by wence-** [comment]
I think you figured out a solution, do you mind mentioning it so that anyone hitting the same kind of problem can benefit from the result?

**Comment by zhyxue0** [comment]
> I think you figured out a solution, do you mind mentioning it so that anyone hitting the same kind of problem can benefit from the result?

OK,   inspired by ksagiyam in issue #2399 ,  define a new trial function `u_trial_V`  and test function `v_V`  

```python
u_trial_V = TrialFunction(V)
v_V = TestFunctions(V)


M_V = assemble( u_trial_V  * v_V *dx)
L = dtc * (RK_b1 * (-dot(p1,grad(v_V))*dx +  dot( p1('+'), jump(v_V,n) )*dS) \
        + RK_b2 * (-dot(p2,grad(v_V))*dx +  dot( p2('+'), jump(v_V,n) )*dS) )  
        
u_solution = Function(V)        
b = assemble(L)
solve(M_V, u_solution, b)
u.assign(u + u_solution)
```
