### ISSUE TITLE
testing downstream packages

### ISSUE THREAD

**Issue by danshapero** [firedrakeproject/firedrake#2390]
The Firedrake test suite checks whether it can import downstream packages like Icepack, Thetis, Gusto, etc. This means that people like me can inadvertently break the Firedrake build by, for example, goofing up setup.py in our own projects (see #2386).

**Has testing import of downstream packages caught many potential bugs in development branches?** I have a hunch that it hasn't. If not, I don't think it's worth continuing to do this. I've broken the build a bunch of times and that inconveniences several people, so I'd rather take care of any problems that get introduced from upstream on my end.

Just want to also check with @tkarna, @colinjcotter, @jshipton since Thetis and Gusto are included in the list of downstream packages that get tested. If I'm way off base and other people would prefer to keep these tests, then I'll be more careful or change some of the testing of Icepack.

If github actions had an [allow failure](https://github.com/actions/toolkit/issues/399) option then that would be a nicer solution, but they don't seem to have implemented it yet.

**Comment by jshipton** [comment]
@danshapero what does this import actually test? I like the idea of catching issues in Gusto (e.g. when Firedrake gets stricter about something we've been sloppy about in Gusto - see recent boundary condition issues!) but I don't think that this does that. I can't recall this alerting us to issues.

**Comment by connorjward** [comment]
I think that the idea behind this test is to check that `firedrake-install --install gusto/thetis/...` will work as intended. I agree with @danshapero that these should probably go but we would also need to expunge these options from the install script.
