### ISSUE TITLE
Problem Transformation from MixedFunctionSpace to Subspace 

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2399]
```python
V0 = FunctionSpace(mesh, "DG", 1)		        # FunctionSpace V0
V1 = VectorFunctionSpace(mesh, "DG", 1)		        # FunctionSpace V1
W = MixedFunctionSpace([V0,V1])                         # MixedFunctionsSpace W

u_V0 = Function(V0)
u_W0 = Function(W.sub(0))
```

In firedrake, `u_V0` and `u_W0` are not in the same function space，but mathematically they are the same.  How to change `u_V0` into the space `W.sub(0)`  and `u_W0` into the space `V0` ? 

**Background of the problem**

An iterative algorithm is as follows, u^{n} is known, but p^{n} is unknown

<img src="https://latex.codecogs.com/svg.image?\begin{cases}&space;&&space;M_u(u^{n&plus;1})&space;=&space;M_u(u^{n})&space;&plus;&space;\Delta&space;t&space;\left(&space;\frac{1}{2}&space;L_{p}(p^{n})&space;&plus;&space;\frac{1}{2}&space;L_{p}(p^{n&plus;1})&space;\right)\\&space;&&space;M_{p}(p^{n})&space;=&space;P_{u}(u^{n})&space;\\&space;&&space;M_{p}(p^{n&plus;1})&space;=&space;P_{u}(u^{n&plus;1})\end{cases}" title="https://latex.codecogs.com/svg.image?\begin{cases} & M_u(u^{n+1}) = M_u(u^{n}) + \Delta t \left( \frac{1}{2} L_{p}(p^{n}) + \frac{1}{2} L_{p}(p^{n+1}) \right)\\ & M_{p}(p^{n}) = P_{u}(u^{n}) \\ & M_{p}(p^{n+1}) = P_{u}(u^{n+1})\end{cases}" />

***Method 1***
In order to be able to solve in firdrake, I define a mixed space `W = V0 * V1` , and the iterative algorithm is as follows 
<img src="https://latex.codecogs.com/svg.image?\begin{cases}&space;&&space;\text{Step&space;1.}&space;&space;\quad&space;&space;M_{p}(p^{n})&space;=&space;P_{u}(u^{n})&space;\\&space;&&space;\text{Step&space;2.}&space;\quad&space;\left(&space;M_u(u^{n&plus;1})&space;-&space;\Delta&space;t&space;\frac{1}{2}L_{p}(p^{n&plus;1})\right)&space;&plus;&space;&space;\left(&space;M_{p}(p^{n&plus;1})&space;-&space;P_{u}(u^{n&plus;1})&space;\right)&space;=&space;M_u(u^{n})&space;&plus;&space;\Delta&space;t&space;\left(&space;\frac{1}{2}&space;L_{p}(p^{n})&space;\right)\end{cases}" title="https://latex.codecogs.com/svg.image?\begin{cases} & \text{Step 1.} \quad M_{p}(p^{n}) = P_{u}(u^{n}) \\ & \text{Step 2.} \quad \left( M_u(u^{n+1}) - \Delta t \frac{1}{2}L_{p}(p^{n+1})\right) + \left( M_{p}(p^{n+1}) - P_{u}(u^{n+1}) \right) = M_u(u^{n}) + \Delta t \left( \frac{1}{2} L_{p}(p^{n}) \right)\end{cases}" />

But  there is an error  when solving Step 1
```shell
firedrake.exceptions.ConvergenceError: ('LinearSolver failed to converge after %d iterations with reason: %s', 0, 'DIVERGED_PCSETUP_FAILED')
```
And print the matrix 

```shell
[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.20561676 0.         0.10280838]
 [0.         0.         0.         ... 0.         0.20561676 0.        ]
 [0.         0.         0.         ... 0.10280838 0.         0.20561676]]
```
As I asked in #2389,  since it is a mixed function space, But LHS has only variables of subspace `V1`  in step 1, the matrix is singular.

***Method  2***
I modified the function space like this `W = V0 * V1 * V1`, and the iterative algorithm is as follows 

<img src="https://latex.codecogs.com/svg.image?\left(&space;M_u(u^{n&plus;1})&space;-&space;\Delta&space;t&space;\frac{1}{2}L_{p}(p^{n&plus;1})\right)&space;&plus;&space;&space;\left(&space;M_{p}(p^{n&plus;1})&space;-&space;P_{u}(u^{n&plus;1})&space;\right)&plus;&space;&space;\left(&space;M_{p}(p^{n})&space;-&space;\Delta&space;t&space;\frac{1}{2}L_{p}(p^{n})\right)&space;&space;\\=&space;M_u(u^{n})&space;&plus;&space;P_{u}(u^{n})&space;" title="https://latex.codecogs.com/svg.image?\left( M_u(u^{n+1}) - \Delta t \frac{1}{2}L_{p}(p^{n+1})\right) + \left( M_{p}(p^{n+1}) - P_{u}(u^{n+1}) \right)+ \left( M_{p}(p^{n}) - \Delta t \frac{1}{2}L_{p}(p^{n})\right) \\= M_u(u^{n}) + P_{u}(u^{n}) " />

It worked, but I think the matrix is too large.  If method 1 were to work, the matrix would be much smaller.  How to extract from MixedFunctionsSpace  `W` to subspace `V1` and integrate the variables of function space `V0` and `V1` into MixedFunctionsSpace `W` ?

**Comment by ksagiyam** [comment]
`W.sub(1) == V1` actually returns `True` in Firedrake, and `assign()` works from `V1` to `W.sub(1)`, and vice versa:
```
from firedrake import *
  

mesh = UnitSquareMesh(1, 1)
V0 = FunctionSpace(mesh, "DG", 1)
V1 = VectorFunctionSpace(mesh, "DG", 1)
W = MixedFunctionSpace([V0, V1])
f = Function(V1)
g = Function(W)

g.sub(0).assign(1)
g.sub(1).assign(as_vector([2., 3.]))
print("g:\n", g.dat.data)
f.assign(g.sub(1))
print("f:\n", f.dat.data)
f.assign(as_vector([4., 5.]))
g.sub(1).assign(f)
print("g:\n", g.dat.data)

print("W.sub(1) == V1:", W.sub(1) == V1)
```
prints:
```
g:
 (array([1., 1., 1., 1., 1., 1.]), array([[2., 3.],
       [2., 3.],
       [2., 3.],
       [2., 3.],
       [2., 3.],
       [2., 3.]]))
f:
 [[2. 3.]
 [2. 3.]
 [2. 3.]
 [2. 3.]
 [2. 3.]
 [2. 3.]]
g:
 (array([1., 1., 1., 1., 1., 1.]), array([[4., 5.],
       [4., 5.],
       [4., 5.],
       [4., 5.],
       [4., 5.],
       [4., 5.]]))
W.sub(1) == V1: True
```

**Comment by zhyxue0** [comment]
> MixedFunctionSpace([V0, V1])

thanks

**Comment by zhyxue0** [comment]
> from firedrake import *
>   
> 
> mesh = UnitSquareMesh(1, 1)
> V0 = FunctionSpace(mesh, "DG", 1)
> V1 = VectorFunctionSpace(mesh, "DG", 1)
> W = MixedFunctionSpace([V0, V1])
> f = Function(V1)
> g = Function(W)
> 
> g.sub(0).assign(1)
> g.sub(1).assign(as_vector([2., 3.]))
> print("g:\n", g.dat.data)
> f.assign(g.sub(1))
> print("f:\n", f.dat.data)
> f.assign(as_vector([4., 5.]))
> g.sub(1).assign(f)
> print("g:\n", g.dat.data)
> 
> print("W.sub(1) == V1:", W.sub(1) == V1)
> ```
> 
> prints:
> 
> ```
> g:
>  (array([1., 1., 1., 1., 1., 1.]), array([[2., 3.],
>        [2., 3.],
>        [2., 3.],
>        [2., 3.],
>        [2., 3.],
>        [2., 3.]]))
> f:
>  [[2. 3.]
>  [2. 3.]
>  [2. 3.]
>  [2. 3.]
>  [2. 3.]
>  [2. 3.]]
> g:
>  (array([1., 1., 1., 1., 1., 1.]), array([[4., 5.],
>        [4., 5.],
>        [4., 5.],
>        [4., 5.],
>        [4., 5.],
>        [4., 5.]]))
> W.sub(1) == V1: True
> ```
