### ISSUE TITLE
Request for Zenodo release

### ISSUE THREAD

**Issue by jwallwork23** [firedrakeproject/firedrake#2411]
Hi, please could I have a Zenodo release for the following? Thanks!

`{"firedrake": "158225ce3478425e1301601e0df0b09d4af74647", "PyOP2": "5fb85598771f0aef20174ae4b699cc069559dafe", "tsfc": "73ad5d177a81953b1d18d1296b557178acc80644", "COFFEE": "70c1e66a4e4e39d3bf75274505a16901af110751", "ufl": "645814befcbe475e876ee8cb978c1c4be54b7762", "FInAT": "8b08fe073cc32c48d2f12c4d1d6265503851707f", "fiat": "5384bebb545dd5564344fa3f7473277425ff90a8", "petsc": "693005e3cae822be8bbd88a24a71fa554e42a118", "loopy": "3988272b385fd770a3427b539e8b27e367f9db33", "metarelease_info_file": null, "title": "Tidal Array Modelling using Goal-Oriented Mesh Adaptation"}`

**Comment by wence-** [comment]
Tag is `Firedrake_20220411.0`
DOI is 10.5281/zenodo.6444350
Zenodo URL is https://zenodo.org/record/6444350
BibTeX

```bibtex
@misc{zenodo/Firedrake-20220411.0,
 key   = {zenodo/Firedrake-20220411.0},
 title = {{Software used in `Tidal Array Modelling using Goal-Oriented Mesh Adaptation'}},
 year  = {2022},
 month = {apr},
 doi   = {10.5281/zenodo.6444350},
 url   = {https://doi.org/10.5281/zenodo.6444350},
}

```

Thanks!

**Comment by jwallwork23** [comment]
Perfect, thanks Lawrence!
