### ISSUE TITLE
Docker file for building firedrake on Mac M1

### ISSUE THREAD

**Issue by yyimingucl** [firedrakeproject/firedrake#2416]
Hello everyone! 
I am new to MacOS. I am trying to build firedrake by docker file. 
For reproducing the issue, the bullet points below are my implementation steps. 

-   Pulling the image: `docker pull firedrakeproject/firedrake`
-   Building the container: `docker run -i -p 8888:8888 -p 6060:22 --platform linux/amd64 --ipc=host --name='firedrake' -v /Users/account_name/Documents:/data` 
-   Activate venv source /home/firedrake/firedrake/bin/activate
-   The error appears (shown in the attached screenshot) when I run `from firedrake import * `
<img width="908" alt="Reported Error" src="https://user-images.githubusercontent.com/57998874/163884697-d004c938-1321-4712-8b51-287bdceaee59.png">

Any solutions or suggestions?

Many thanks.

**Comment by tkoskela** [comment]
Hi, is anyone able to help with this issue?

**Comment by dham** [comment]
Well there's not a lot to go on in the error message. I can imagine that there are all sorts of possible failure modes running intel docker containers on ARM hardware but I'm not an expert in that problem. 

I would recommend just running Firedrake natively on the Mac. We believe we have dealt with the known issues which people had and several users are happily using Firedrake on M1, including me.

**Comment by yyimingucl** [comment]
Download it after degrading python3.9 to 3.8

**Comment by dham** [comment]
As a side point, we recommend Homebrew over Anaconda as users usually have far fewer issues with Homebrew. However, if it works for you then I'm happy.
