### ISSUE TITLE
Problem DG operators in 1D

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2417]
### Background of the problem

To solve the heat equation u_t = u_xx with Dirichlet bundary in the interval I = [a,b] by LDG method
we first introduce an auxiliary  variable q, 

<img src="https://latex.codecogs.com/svg.image?\begin{align}u_{t}&space;&=&space;q_{x}&space;\nonumber&space;\\q&space;&=&space;u_{x}&space;\nonumber\end{align}" title="https://latex.codecogs.com/svg.image?\begin{align}u_{t} &= q_{x} \nonumber \\q &= u_{x} \nonumber\end{align}" />
The interval I is divided into <img src="https://latex.codecogs.com/svg.image?a&space;=&space;x_{\frac{1}{2}}&space;<&space;x_{\frac{3}{2}}&space;<&space;\cdots<&space;x_{N&plus;\frac{1}{2}}&space;=&space;b" title="https://latex.codecogs.com/svg.image?a = x_{\frac{1}{2}} < x_{\frac{3}{2}} < \cdots< x_{N+\frac{1}{2}} = b" />

Integrate by parts on each cell
<img src="https://latex.codecogs.com/svg.image?\int_{I_{j}}&space;u_{t}&space;v&space;dx&space;=&space;\int_{I_{j}}&space;q_{x}&space;v&space;dx&space;=&space;&space;-\int_{I_{j}}&space;q&space;v_{x}&space;dx&space;&space;&plus;&space;\hat{q}(x_{j&plus;\frac{1}{2}})&space;v^{-}(x_{j&plus;\frac{1}{2}})&space;-&space;\hat{q}(x_{j-\frac{1}{2}})&space;v^{&plus;}(x_{j-\frac{1}{2}})&space;\\\int_{I_{j}}&space;q&space;w&space;dx&space;=&space;\int_{I_{j}}&space;u_{x}&space;w&space;dx&space;=&space;&space;-\int_{I_{j}}&space;u&space;w_{x}&space;dx&space;&space;&plus;&space;\hat{u}(x_{j&plus;\frac{1}{2}})&space;w^{-}(x_{j&plus;\frac{1}{2}})&space;-&space;\hat{u}(x_{j-\frac{1}{2}})&space;w^{&plus;}(x_{j-\frac{1}{2}})&space;\\" title="https://latex.codecogs.com/svg.image?\int_{I_{j}} u_{t} v dx = \int_{I_{j}} q_{x} v dx = -\int_{I_{j}} q v_{x} dx + \hat{q}(x_{j+\frac{1}{2}}) v^{-}(x_{j+\frac{1}{2}}) - \hat{q}(x_{j-\frac{1}{2}}) v^{+}(x_{j-\frac{1}{2}}) \\\int_{I_{j}} q w dx = \int_{I_{j}} u_{x} w dx = -\int_{I_{j}} u w_{x} dx + \hat{u}(x_{j+\frac{1}{2}}) w^{-}(x_{j+\frac{1}{2}}) - \hat{u}(x_{j-\frac{1}{2}}) w^{+}(x_{j-\frac{1}{2}}) \\" />

where  the flux is  alternating flux <img src="https://latex.codecogs.com/svg.image?\hat{q}&space;=&space;q^{&plus;},&space;\hat{u}&space;=&space;u^{-}&space;" title="https://latex.codecogs.com/svg.image?\hat{q} = q^{+}, \hat{u} = u^{-} " /> or     <img src="https://latex.codecogs.com/svg.image?\hat{q}&space;=&space;q^{-},&space;\hat{u}&space;=&space;u^{&plus;}&space;" title="https://latex.codecogs.com/svg.image?\hat{q} = q^{-}, \hat{u} = u^{+} " />

Summing over the I_j
<img src="https://latex.codecogs.com/svg.image?\sum_{j&space;=1&space;}&space;^{N}&space;\left(&space;-\int_{I_{j}}&space;q&space;v_{x}&space;dx&space;&plus;&space;\hat{q}(x_{j&plus;\frac{1}{2}})&space;v^{-}(x_{j&plus;\frac{1}{2}})&space;-&space;\hat{q}(x_{j-\frac{1}{2}})&space;v^{&plus;}(x_{j-\frac{1}{2}})&space;\right)&space;\\=&space;-\int_{I}&space;q&space;v_{x}&space;dx&space;&plus;&space;\sum_{j=1}^{N-1}\left(&space;\hat{q}(x_{j&plus;\frac{1}{2}})&space;\left(v^{-}(x_{j&plus;\frac{1}{2}})&space;-&space;v^{&plus;}(x_{j&plus;\frac{1}{2}})&space;\right)&space;\right)&plus;&space;\hat{q}(x_{N&plus;\frac{1}{2}})v^{-}(x_{N&plus;\frac{1}{2}})&space;-&space;&space;\hat{q}(x_{\frac{1}{2}})v^{&plus;}(x_{\frac{1}{2}}))&space;\\=&space;-\int_{I}&space;q&space;v_{x}&space;dx&space;&plus;&space;&space;\hat{q}&space;\left(&space;v^{-}&space;-&space;v^{&plus;}&space;\right)&space;dS&space;&plus;&space;qv&space;ds(2)&space;-&space;qvds(1)" title="https://latex.codecogs.com/svg.image?\sum_{j =1 } ^{N} \left( -\int_{I_{j}} q v_{x} dx + \hat{q}(x_{j+\frac{1}{2}}) v^{-}(x_{j+\frac{1}{2}}) - \hat{q}(x_{j-\frac{1}{2}}) v^{+}(x_{j-\frac{1}{2}}) \right) \\= -\int_{I} q v_{x} dx + \sum_{j=1}^{N-1}\left( \hat{q}(x_{j+\frac{1}{2}}) \left(v^{-}(x_{j+\frac{1}{2}}) - v^{+}(x_{j+\frac{1}{2}}) \right) \right)+ \hat{q}(x_{N+\frac{1}{2}})v^{-}(x_{N+\frac{1}{2}}) - \hat{q}(x_{\frac{1}{2}})v^{+}(x_{\frac{1}{2}})) \\= -\int_{I} q v_{x} dx + \hat{q} \left( v^{-} - v^{+} \right) dS + qv ds(2) - qvds(1)" />

Backward Euler method is used for time discretization

The full discrete scheme is as follows
<img src="https://latex.codecogs.com/svg.image?\int_{I}&space;\frac{u^{n&plus;1}&space;-&space;u^{n}}{\Delta&space;t}vdx&space;=&space;-\int_{I}&space;q^{n&plus;1}&space;v_{x}&space;dx&space;&plus;&space;&space;\hat{q}^{n&plus;1}&space;\left(&space;v^{-}&space;-&space;v^{&plus;}&space;\right)&space;dS&space;&plus;&space;q^{n&plus;1}v&space;ds(2)&space;-&space;q^{n&plus;1}vds(1)&space;\\\int_{I}&space;q^{n&plus;1}&space;w_{x}&space;dx&space;=&space;-\int_{I}&space;u^{n&plus;1}&space;w_{x}&space;dx&space;&plus;&space;&space;\hat{u}^{n&plus;1}&space;\left(&space;w^{-}&space;-&space;w^{&plus;}&space;\right)&space;dS&space;&plus;&space;u_{bd}w&space;ds(2)&space;-&space;u_{bd}&space;wds(1)&space;" title="https://latex.codecogs.com/svg.image?\int_{I} \frac{u^{n+1} - u^{n}}{\Delta t}vdx = -\int_{I} q^{n+1} v_{x} dx + \hat{q}^{n+1} \left( v^{-} - v^{+} \right) dS + q^{n+1}v ds(2) - q^{n+1}vds(1) \\\int_{I} q^{n+1} w_{x} dx = -\int_{I} u^{n+1} w_{x} dx + \hat{u}^{n+1} \left( w^{-} - w^{+} \right) dS + u_{bd}w ds(2) - u_{bd} wds(1) " />

### **Code**
```python
from firedrake import *
import math

Nx = 40
Pk = 0
CFL = 0.01
T = 0.2
Lx = 2*math.pi
Hx = Lx/Nx

mesh = IntervalMesh(Nx, Lx)

V = FunctionSpace(mesh, "DG", Pk)
MixedSpace = V * V
u_trial, q_trial = TrialFunctions(MixedSpace)
v, w = TestFunctions(MixedSpace)

x, = SpatialCoordinate(mesh)

# dt 
dt = CFL * Hx
N_step = math.ceil(T/dt)
dt = T / N_step
dtc = Constant(dt)

t = 0.0
tc = Constant(t)

# Initial value 
u = Function(V)
u = project(sin(x),MixedSpace.sub(0))

# Boundary term
u_bd = Function(V)
u_bd =  project(exp(-tc)*sin(x),MixedSpace.sub(0))


Lap = ( -q_trial*v.dx(0) *dx + q_trial("+")*(v("-") - v("+") )*dS + q_trial*v*ds(2) - q_trial*v*ds(1) )
Qu = ( -u_trial*w.dx(0) *dx + u_trial("-")*(w("-") - w("+") )*dS )


a = u_trial*v*dx - dtc* Lap + q_trial*w*dx - Qu
L = u*v*dx + u_bd*w*ds(2) - u_bd*w*ds(1)


solver_parameters={"ksp_type": "preonly", "pc_type": "lu"}
w_solution = Function(MixedSpace)
problem = LinearVariationalProblem(a,L, w_solution)
solver= LinearVariationalSolver(problem, solver_parameters = solver_parameters)

Step = 0
for Step in range(N_step):

    tc.assign(t+dt)

    solver.solve()
    u.assign(w_solution.sub(0))    

    t += dt
    print("t = ", t)


tc.assign(t)
u_exact = project(exp(-tc)*sin(x), MixedSpace.sub(0))
L2_error = norms.errornorm(  u_exact, u, norm_type = "L2")
print("L2 error:", L2_error)
```

### Question
But the result looks wrong,  maybe I  misunderstood the meaning of Interior facets `dS` and the flux term  `u("-")`  `q("+")`  .
Is  formula
<img src="https://latex.codecogs.com/svg.image?\sum_{j=1}^{N-1}\left(&space;q^{&plus;}(x_{j&plus;\frac{1}{2}})&space;\left(v^{-}(x_{j&plus;\frac{1}{2}})&space;-&space;v^{&plus;}(x_{j&plus;\frac{1}{2}})&space;\right)&space;\right)" title="https://latex.codecogs.com/svg.image?\sum_{j=1}^{N-1}\left( q^{+}(x_{j+\frac{1}{2}}) \left(v^{-}(x_{j+\frac{1}{2}}) - v^{+}(x_{j+\frac{1}{2}}) \right) \right)" />
 equivalent to  
` q_trial("+")*(v("-") - v("+") )*dS `   in 1D ?

**Comment by dham** [comment]
"+" and "-" are fixed but arbitrary sides of each facet. In 1d, at one cell boundary "+" might be on the right, but at another cell boundary "+" might be on the left.

 This means that it is essentially always wrong to use forms which are not invariant under swapping those two symbols. `Lap` contains a `q_trial("+")` but not a `q_trial("-")` while Qu contains a `u_trial("+")` but not a `u_trial("-")`. I note your comment about alternating flux, but I don't think that makes sense here due to the arbitrary nature of the signs.

**Comment by zhyxue0** [comment]
> "+" and "-" are fixed but arbitrary sides of each facet. In 1d, at one cell boundary "+" might be on the right, but at another cell boundary "+" might be on the left.
> 
> This means that it is essentially always wrong to use forms which are not invariant under swapping those two symbols. `Lap` contains a `q_trial("+")` but not a `q_trial("-")` while Qu contains a `u_trial("+")` but not a `u_trial("-")`. I note your comment about alternating flux, but I don't think that makes sense here due to the arbitrary nature of the signs.

Thanks, I found that when I call `IntervalMesh`, `q("+")` represents q^{-}  mathematically. For the LDG method,  alternating flux is a better choice, but I switched to  choose central flux and it can work correctly.

**Comment by dham** [comment]
> > "+" and "-" are fixed but arbitrary sides of each facet. In 1d, at one cell boundary "+" might be on the right, but at another cell boundary "+" might be on the left.
> > This means that it is essentially always wrong to use forms which are not invariant under swapping those two symbols. `Lap` contains a `q_trial("+")` but not a `q_trial("-")` while Qu contains a `u_trial("+")` but not a `u_trial("-")`. I note your comment about alternating flux, but I don't think that makes sense here due to the arbitrary nature of the signs.
> 
> Thanks, I found that when I call `IntervalMesh`, `q("+")` represents q^{-} mathematically. For the LDG method, alternating flux is a better choice, but I switched to choose central flux and it can work correctly.

I think this still mistakes the issue. You can upwind the flux and this is demonstrated in the DG demo. Alternating flux amounts to upwinding/downwinding with respect to the coordinate field, and you can do that too. What is not safe is assuming that there is any fixed relationship between the `"+"` and `"-"` restrictions and any mathematical convention you may be following.

**Comment by zhyxue0** [comment]
> > > "+" and "-" are fixed but arbitrary sides of each facet. In 1d, at one cell boundary "+" might be on the right, but at another cell boundary "+" might be on the left.
> > > This means that it is essentially always wrong to use forms which are not invariant under swapping those two symbols. `Lap` contains a `q_trial("+")` but not a `q_trial("-")` while Qu contains a `u_trial("+")` but not a `u_trial("-")`. I note your comment about alternating flux, but I don't think that makes sense here due to the arbitrary nature of the signs.
> > 
> > 
> > Thanks, I found that when I call `IntervalMesh`, `q("+")` represents q^{-} mathematically. For the LDG method, alternating flux is a better choice, but I switched to choose central flux and it can work correctly.
> 
> I think this still mistakes the issue. You can upwind the flux and this is demonstrated in the DG demo. Alternating flux amounts to upwinding/downwinding with respect to the coordinate field, and you can do that too. What is not safe is assuming that there is any fixed relationship between the `"+"` and `"-"` restrictions and any mathematical convention you may be following.

You're right, if I call `PeriodicIntervalMesh` the result is wrong, but I can't think of any other way to make the LDG method work correctly in the framework of firedrake.

**Comment by zhyxue0** [comment]
> > > "+" and "-" are fixed but arbitrary sides of each facet. In 1d, at one cell boundary "+" might be on the right, but at another cell boundary "+" might be on the left.
> > > This means that it is essentially always wrong to use forms which are not invariant under swapping those two symbols. `Lap` contains a `q_trial("+")` but not a `q_trial("-")` while Qu contains a `u_trial("+")` but not a `u_trial("-")`. I note your comment about alternating flux, but I don't think that makes sense here due to the arbitrary nature of the signs.
> > 
> > 
> > Thanks, I found that when I call `IntervalMesh`, `q("+")` represents q^{-} mathematically. For the LDG method, alternating flux is a better choice, but I switched to choose central flux and it can work correctly.
> 
> I think this still mistakes the issue. You can upwind the flux and this is demonstrated in the DG demo. Alternating flux amounts to upwinding/downwinding with respect to the coordinate field, and you can do that too. What is not safe is assuming that there is any fixed relationship between the `"+"` and `"-"` restrictions and any mathematical convention you may be following.

Thanks a lot, I see , Alternating flux can be implemented in this way, but it can only guarantee that the two variables choose different facet.
```python
u_vec = Function(FunctionSpace(mesh, "DG", 1))
u_vec.assign(1.0)
un = dot(u_vec,n)
q_flux = conditional(un('+') > 0, q_trial("-"),q_trial('+'))
u_flux = conditional(un('+') > 0, u_trial("+"),u_trial('-'))
```
