### ISSUE TITLE
Firedrake release

### ISSUE THREAD

**Issue by tkarna** [firedrakeproject/firedrake#2418]
I'd need a Zenodo release, the json file is attached.
[firedrake.json.zip](https://github.com/firedrakeproject/firedrake/files/8530149/firedrake.json.zip)

**Comment by wence-** [comment]
Tag is `Firedrake_20220421.0`
DOI is 10.5281/zenodo.6475963
Zenodo URL is https://zenodo.org/record/6475963
BibTeX

```bibtex
@misc{zenodo/Firedrake-20220421.0,
 key   = {zenodo/Firedrake-20220421.0},
 title = {{Software used in `Adjoint-based optimization of a regional water elevation model'}},
 year  = {2022},
 month = {apr},
 doi   = {10.5281/zenodo.6475963},
 url   = {https://doi.org/10.5281/zenodo.6475963},
}

```

Thanks!
