### ISSUE TITLE
Constant cannot be updated in function project

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2420]
My boundary conditions are time dependent, but it seems cannot be updated in function project, is this a bug?
Or is there any other trick to solve it?
Here is my code:
```python
from firedrake import *
import math

Nx = 4
Pk = 1

Lx = 2*math.pi
Hx = Lx/Nx

mesh = IntervalMesh(Nx, Lx)
V = FunctionSpace(mesh, "CG", Pk)
x, = SpatialCoordinate(mesh)
v = TestFunction(V)

t = 0.0
N_step = 10
dt = 2*math.pi / N_step

# boundary term 
tc = Constant(t)
u_bd =  project(sin(x-tc),V)

L = u_bd*v*ds


b = None
Step = 0
for Step in range(N_step):

    tc.assign(t+dt)

    b = assemble(L)
    print("t = ", t, ", u_bd at x=0 is ", u_bd.at(0))
    print("b =", b.vector().array(),"\n")

    t += dt

```
Output:
```shell
t =  0.0 , u_bd at x=0 is  0.11489360186051263
b = [ 0.15694758 -0.04205398  0.          0.          0.          0.
  0.04205398 -0.15694758] 

t =  0.6283185307179586 , u_bd at x=0 is  0.11489360186051263
b = [ 0.15694758 -0.04205398  0.          0.          0.          0.
  0.04205398 -0.15694758] 

t =  1.2566370614359172 , u_bd at x=0 is  0.11489360186051263
b = [ 0.15694758 -0.04205398  0.          0.          0.          0.
  0.04205398 -0.15694758] 

t =  1.8849555921538759 , u_bd at x=0 is  0.11489360186051263
b = [ 0.15694758 -0.04205398  0.          0.          0.          0.
  0.04205398 -0.15694758] 

t =  2.5132741228718345 , u_bd at x=0 is  0.11489360186051263
b = [ 0.15694758 -0.04205398  0.          0.          0.          0.
  0.04205398 -0.15694758] 

t =  3.141592653589793 , u_bd at x=0 is  0.11489360186051263
b = [ 0.15694758 -0.04205398  0.          0.          0.          0.
  0.04205398 -0.15694758] 

t =  3.7699111843077517 , u_bd at x=0 is  0.11489360186051263
b = [ 0.15694758 -0.04205398  0.          0.          0.          0.
  0.04205398 -0.15694758] 

t =  4.39822971502571 , u_bd at x=0 is  0.11489360186051263
b = [ 0.15694758 -0.04205398  0.          0.          0.          0.
  0.04205398 -0.15694758] 

t =  5.026548245743669 , u_bd at x=0 is  0.11489360186051263
b = [ 0.15694758 -0.04205398  0.          0.          0.          0.
  0.04205398 -0.15694758] 

t =  5.654866776461628 , u_bd at x=0 is  0.11489360186051263
b = [ 0.15694758 -0.04205398  0.          0.          0.          0.
  0.04205398 -0.15694758] 
```

**Comment by jwallwork23** [comment]
`project` takes a UFL expression and gives you a `Function`, in this case `u_bd`. If the UFL expression is updated, you will need to re-project, i.e. call `u_bd.project(sin(x-tc))` inside the time loop.

**Comment by zhyxue0** [comment]
Thanks for replying so quickly,  but  I found that the cost time is about twice as long as before.  Is it because the re-project needs to re-assemble the `L`?  I don't think each re-project will take so much time. 

Here is my code:
```python
from firedrake import *
import math
import time 


CFL = 0.1
Pk = 1

T = math.pi
Nx = 20; Ny = Nx
Lx = 2*math.pi; Ly = Lx
Hx = Lx/Nx
mesh = RectangleMesh(Nx, Nx, Lx, Ly)

V = FunctionSpace(mesh, "DG", Pk)
W = VectorFunctionSpace(mesh, "CG", 1)

x, y = SpatialCoordinate(mesh)

velocity = as_vector((1, 1))
u = Function(W).interpolate(velocity)

q = Function(V)
q.project(sin(x+y))
q_init = Function(V).assign(q)



# Time step
dt = CFL*Hx
N_step = math.ceil(T/dt)
dt = T / N_step
dtc = Constant(dt)


dq_trial = TrialFunction(V)
phi = TestFunction(V)
a = phi*dq_trial*dx
n = FacetNormal(mesh)
un = 0.5*(dot(u, n) + abs(dot(u, n)))

t = 0.0
tc = Constant(t)
tc1 = Constant(t)
tc2 = Constant(t)
q_in = project(sin(x+y-2*tc),V)
q_in_1 = project(sin(x+y-2*tc1),V)
q_in_2 = project(sin(x+y-2*tc2),V)


L1 = dtc*(q*div(phi*u)*dx
    - conditional(dot(u, n) < 0, phi*dot(u, n)*q_in, 0.0)*ds
    - conditional(dot(u, n) > 0, phi*dot(u, n)*q, 0.0)*ds
    - (phi('+') - phi('-'))*(un('+')*q('+') - un('-')*q('-'))*dS)

q1 = Function(V); q2 = Function(V)
L2 = replace(L1, {q: q1, q_in: q_in_1 })
L3 = replace(L1, {q: q2, q_in: q_in_2 })

dq = Function(V)
params = {'ksp_type': 'preonly', 'pc_type': 'bjacobi', 'sub_pc_type': 'ilu'}
prob1 = LinearVariationalProblem(a, L1, dq)
solv1 = LinearVariationalSolver(prob1, solver_parameters=params)
prob2 = LinearVariationalProblem(a, L2, dq)
solv2 = LinearVariationalSolver(prob2, solver_parameters=params)
prob3 = LinearVariationalProblem(a, L3, dq)
solv3 = LinearVariationalSolver(prob3, solver_parameters=params)

Step = 0
time_start = time.time()

for Step in range(N_step):

    tc.assign(t)
    tc1.assign(t+dt)
    tc2.assign(t+0.5*dt)

    q_in.project(sin(x+y-2*tc))
    q_in_1.project(sin(x+y-2*tc1))
    q_in_2.project(sin(x+y-2*tc2))


    solv1.solve()
    q1.assign(q + dq)

    solv2.solve()
    q2.assign(0.75*q + 0.25*(q1 + dq))

    solv3.solve()
    q.assign((1.0/3.0)*q + (2.0/3.0)*(q2 + dq)) 

    t += dt
    print(t)
time_end = time.time()     

L2_err = sqrt(assemble((q - q_init)*(q - q_init)*dx))
L2_init = sqrt(assemble(q_init*q_init*dx))
print(L2_err/L2_init)
print('Time costs: ', str(time_end - time_start))
```

**Comment by zhyxue0** [comment]
> Thanks for replying so quickly, but I found that the cost time is about twice as long as before. Is it because the re-project needs to re-assemble the `L`? I don't think each re-project will take so much time.
> 
> Here is my code:
> 
> ```python
> from firedrake import *
> import math
> import time 
> 
> 
> CFL = 0.1
> Pk = 1
> 
> T = math.pi
> Nx = 20; Ny = Nx
> Lx = 2*math.pi; Ly = Lx
> Hx = Lx/Nx
> mesh = RectangleMesh(Nx, Nx, Lx, Ly)
> 
> V = FunctionSpace(mesh, "DG", Pk)
> W = VectorFunctionSpace(mesh, "CG", 1)
> 
> x, y = SpatialCoordinate(mesh)
> 
> velocity = as_vector((1, 1))
> u = Function(W).interpolate(velocity)
> 
> q = Function(V)
> q.project(sin(x+y))
> q_init = Function(V).assign(q)
> 
> 
> 
> # Time step
> dt = CFL*Hx
> N_step = math.ceil(T/dt)
> dt = T / N_step
> dtc = Constant(dt)
> 
> 
> dq_trial = TrialFunction(V)
> phi = TestFunction(V)
> a = phi*dq_trial*dx
> n = FacetNormal(mesh)
> un = 0.5*(dot(u, n) + abs(dot(u, n)))
> 
> t = 0.0
> tc = Constant(t)
> tc1 = Constant(t)
> tc2 = Constant(t)
> q_in = project(sin(x+y-2*tc),V)
> q_in_1 = project(sin(x+y-2*tc1),V)
> q_in_2 = project(sin(x+y-2*tc2),V)
> 
> 
> L1 = dtc*(q*div(phi*u)*dx
>     - conditional(dot(u, n) < 0, phi*dot(u, n)*q_in, 0.0)*ds
>     - conditional(dot(u, n) > 0, phi*dot(u, n)*q, 0.0)*ds
>     - (phi('+') - phi('-'))*(un('+')*q('+') - un('-')*q('-'))*dS)
> 
> q1 = Function(V); q2 = Function(V)
> L2 = replace(L1, {q: q1, q_in: q_in_1 })
> L3 = replace(L1, {q: q2, q_in: q_in_2 })
> 
> dq = Function(V)
> params = {'ksp_type': 'preonly', 'pc_type': 'bjacobi', 'sub_pc_type': 'ilu'}
> prob1 = LinearVariationalProblem(a, L1, dq)
> solv1 = LinearVariationalSolver(prob1, solver_parameters=params)
> prob2 = LinearVariationalProblem(a, L2, dq)
> solv2 = LinearVariationalSolver(prob2, solver_parameters=params)
> prob3 = LinearVariationalProblem(a, L3, dq)
> solv3 = LinearVariationalSolver(prob3, solver_parameters=params)
> 
> Step = 0
> time_start = time.time()
> 
> for Step in range(N_step):
> 
>     tc.assign(t)
>     tc1.assign(t+dt)
>     tc2.assign(t+0.5*dt)
> 
>     q_in.project(sin(x+y-2*tc))
>     q_in_1.project(sin(x+y-2*tc1))
>     q_in_2.project(sin(x+y-2*tc2))
> 
> 
>     solv1.solve()
>     q1.assign(q + dq)
> 
>     solv2.solve()
>     q2.assign(0.75*q + 0.25*(q1 + dq))
> 
>     solv3.solve()
>     q.assign((1.0/3.0)*q + (2.0/3.0)*(q2 + dq)) 
> 
>     t += dt
>     print(t)
> time_end = time.time()     
> 
> L2_err = sqrt(assemble((q - q_init)*(q - q_init)*dx))
> L2_init = sqrt(assemble(q_init*q_init*dx))
> print(L2_err/L2_init)
> print('Time costs: ', str(time_end - time_start))
> ```



> `project` takes a UFL expression and gives you a `Function`, in this case `u_bd`. If the UFL expression is updated, you will need to re-project, i.e. call `u_bd.project(sin(x-tc))` inside the time loop.

**Comment by zhyxue0** [comment]
> `project` takes a UFL expression and gives you a `Function`, in this case `u_bd`. If the UFL expression is updated, you will need to re-project, i.e. call `u_bd.project(sin(x-tc))` inside the time loop.


Thank you for the quick reply!   But it took about twice as long as before, I don't think `project` takes so much time, is it because of  `project`  that it needs to re-assemble  `L`  at each step in the time loop? Is there any trick to speed up?
This is adapted from the tutorial DG advection equation with upwinding[¶](https://firedrakeproject.org/demos/DG_advection.py.html#dg-advection-equation-with-upwinding):
```python
from firedrake import *
import math
import time 


CFL = 0.1
Pk = 1

T = math.pi
Nx = 20; Ny = Nx
Lx = 2*math.pi; Ly = Lx
Hx = Lx/Nx
mesh = RectangleMesh(Nx, Nx, Lx, Ly)

V = FunctionSpace(mesh, "DG", Pk)
W = VectorFunctionSpace(mesh, "CG", 1)

x, y = SpatialCoordinate(mesh)

velocity = as_vector((1, 1))
u = Function(W).interpolate(velocity)

q = Function(V)
q.project(sin(x+y))
q_init = Function(V).assign(q)



# Time step
dt = CFL*Hx
N_step = math.ceil(T/dt)
dt = T / N_step
dtc = Constant(dt)


dq_trial = TrialFunction(V)
phi = TestFunction(V)
a = phi*dq_trial*dx
n = FacetNormal(mesh)
un = 0.5*(dot(u, n) + abs(dot(u, n)))

t = 0.0
tc = Constant(t)
tc1 = Constant(t)
tc2 = Constant(t)
q_in = project(sin(x+y-2*tc),V)
q_in_1 = project(sin(x+y-2*tc1),V)
q_in_2 = project(sin(x+y-2*tc2),V)


L1 = dtc*(q*div(phi*u)*dx
    - conditional(dot(u, n) < 0, phi*dot(u, n)*q_in, 0.0)*ds
    - conditional(dot(u, n) > 0, phi*dot(u, n)*q, 0.0)*ds
    - (phi('+') - phi('-'))*(un('+')*q('+') - un('-')*q('-'))*dS)

q1 = Function(V); q2 = Function(V)
L2 = replace(L1, {q: q1, q_in: q_in_1 })
L3 = replace(L1, {q: q2, q_in: q_in_2 })

dq = Function(V)
params = {'ksp_type': 'preonly', 'pc_type': 'bjacobi', 'sub_pc_type': 'ilu'}
prob1 = LinearVariationalProblem(a, L1, dq)
solv1 = LinearVariationalSolver(prob1, solver_parameters=params)
prob2 = LinearVariationalProblem(a, L2, dq)
solv2 = LinearVariationalSolver(prob2, solver_parameters=params)
prob3 = LinearVariationalProblem(a, L3, dq)
solv3 = LinearVariationalSolver(prob3, solver_parameters=params)

Step = 0
time_start = time.time()

for Step in range(N_step):

    tc.assign(t)
    tc1.assign(t+dt)
    tc2.assign(t+0.5*dt)

    q_in.project(sin(x+y-2*tc))
    q_in_1.project(sin(x+y-2*tc1))
    q_in_2.project(sin(x+y-2*tc2))


    solv1.solve()
    q1.assign(q + dq)

    solv2.solve()
    q2.assign(0.75*q + 0.25*(q1 + dq))

    solv3.solve()
    q.assign((1.0/3.0)*q + (2.0/3.0)*(q2 + dq)) 

    t += dt
    print(t)
time_end = time.time()     

L2_err = sqrt(assemble((q - q_init)*(q - q_init)*dx))
L2_init = sqrt(assemble(q_init*q_init*dx))
print(L2_err/L2_init)
print('Time costs: ', str(time_end - time_start))
```

**Comment by rckirby** [comment]
Your linear system is just solving a mass matrix at each time step.
 `project` does L2 projection -- which solves a mass matrix.   Doubling
run-time for your case is expected.  But for a more complicated problem you
wouldn't observe doubling.

Note that you can interpolate rather than project your boundary condition
function into the space for standard finite elements, and this is usually
much faster.

Also, as a shameless self-promotion, you might consider using Irksome (
https://github.com/firedrakeproject/Irksome) for time-dependent problems.
It lets you write the PDE in semi-discrete form (using a `Dt` symbol) and
then generates UFL for a Runge-Kutta method.  Lots of methods are supported.

**Comment by wence-** [comment]
> > `project` takes a UFL expression and gives you a `Function`, in this case `u_bd`. If the UFL expression is updated, you will need to re-project, i.e. call `u_bd.project(sin(x-tc))` inside the time loop.
> 
> Thank you for the quick reply! But it took about twice as long as before, I don't think `project` takes so much time, is it because of `project` that it needs to re-assemble `L` at each step in the time loop? Is there any trick to speed up? This is adapted from the tutorial DG advection equation with upwinding[¶](https://firedrakeproject.org/demos/DG_advection.py.html#dg-advection-equation-with-upwinding):
> 
> ```python
> [...]
> t = ...
> tc = Constant(t)
> tc1 = Constant(t)
> tc2 = Constant(t)
> q_in = project(sin(x+y-2*tc),V)
> q_in_1 = project(sin(x+y-2*tc1),V)
> q_in_2 = project(sin(x+y-2*tc2),V)
> 
> 
> L1 = dtc*(q*div(phi*u)*dx
>     - conditional(dot(u, n) < 0, phi*dot(u, n)*q_in, 0.0)*ds
>     - conditional(dot(u, n) > 0, phi*dot(u, n)*q, 0.0)*ds
>     - (phi('+') - phi('-'))*(un('+')*q('+') - un('-')*q('-'))*dS)
> [...] 
> Step = 0
> time_start = time.time()
> 
> for Step in range(N_step):
> 
>     tc.assign(t)
>     tc1.assign(t+dt)
>     tc2.assign(t+0.5*dt)
> 
>     q_in.project(sin(x+y-2*tc))
>     q_in_1.project(sin(x+y-2*tc1))
>     q_in_2.project(sin(x+y-2*tc2))
> 
> 
>     solv1.solve()
>     q1.assign(q + dq)
> 
>     solv2.solve()
>     q2.assign(0.75*q + 0.25*(q1 + dq))
> 
>     solv3.solve()
>     q.assign((1.0/3.0)*q + (2.0/3.0)*(q2 + dq)) 
> 
>     t += dt
>     print(t)
> time_end = time.time()     
> 
> L2_err = sqrt(assemble((q - q_init)*(q - q_init)*dx))
> L2_init = sqrt(assemble(q_init*q_init*dx))
> print(L2_err/L2_init)
> print('Time costs: ', str(time_end - time_start))
> ```

Since you're just using `q_in`, `q_in_1`, and `q_in_2` in forms there's no need to separately project them to a function first. The symbolic expression can be used directly and will be evaluated at the quadrature points.

So try with:
```python
...
t = ...
tc = Constant(t)
tc1 = Constant(t)
tc2 = Constant(t)
q_in = sin(x+y-2*tc)
q_in_1 = sin(x+y-2*tc1)
q_in_2 = sin(x+y-2*tc2)

...
while ...:
    tc.assign(t)
    tc1.assign(...)
    tc2.assign(...)
    # your solve calls here
```

**Comment by zhyxue0** [comment]
> 

Thanks, this does save time, but does it affect accuracy if I want to test the order? I would like to know what quadrature rules and quadrature points are used in firedrake?

**Comment by zhyxue0** [comment]
> > > `project` takes a UFL expression and gives you a `Function`, in this case `u_bd`. If the UFL expression is updated, you will need to re-project, i.e. call `u_bd.project(sin(x-tc))` inside the time loop.
> > 
> > 
> > Thank you for the quick reply! But it took about twice as long as before, I don't think `project` takes so much time, is it because of `project` that it needs to re-assemble `L` at each step in the time loop? Is there any trick to speed up? This is adapted from the tutorial DG advection equation with upwinding[¶](https://firedrakeproject.org/demos/DG_advection.py.html#dg-advection-equation-with-upwinding):
> > ```python
> > [...]
> > t = ...
> > tc = Constant(t)
> > tc1 = Constant(t)
> > tc2 = Constant(t)
> > q_in = project(sin(x+y-2*tc),V)
> > q_in_1 = project(sin(x+y-2*tc1),V)
> > q_in_2 = project(sin(x+y-2*tc2),V)
> > 
> > 
> > L1 = dtc*(q*div(phi*u)*dx
> >     - conditional(dot(u, n) < 0, phi*dot(u, n)*q_in, 0.0)*ds
> >     - conditional(dot(u, n) > 0, phi*dot(u, n)*q, 0.0)*ds
> >     - (phi('+') - phi('-'))*(un('+')*q('+') - un('-')*q('-'))*dS)
> > [...] 
> > Step = 0
> > time_start = time.time()
> > 
> > for Step in range(N_step):
> > 
> >     tc.assign(t)
> >     tc1.assign(t+dt)
> >     tc2.assign(t+0.5*dt)
> > 
> >     q_in.project(sin(x+y-2*tc))
> >     q_in_1.project(sin(x+y-2*tc1))
> >     q_in_2.project(sin(x+y-2*tc2))
> > 
> > 
> >     solv1.solve()
> >     q1.assign(q + dq)
> > 
> >     solv2.solve()
> >     q2.assign(0.75*q + 0.25*(q1 + dq))
> > 
> >     solv3.solve()
> >     q.assign((1.0/3.0)*q + (2.0/3.0)*(q2 + dq)) 
> > 
> >     t += dt
> >     print(t)
> > time_end = time.time()     
> > 
> > L2_err = sqrt(assemble((q - q_init)*(q - q_init)*dx))
> > L2_init = sqrt(assemble(q_init*q_init*dx))
> > print(L2_err/L2_init)
> > print('Time costs: ', str(time_end - time_start))
> > ```
> 
> Since you're just using `q_in`, `q_in_1`, and `q_in_2` in forms there's no need to separately project them to a function first. The symbolic expression can be used directly and will be evaluated at the quadrature points.
> 
> So try with:
> 
> ```python
> ...
> t = ...
> tc = Constant(t)
> tc1 = Constant(t)
> tc2 = Constant(t)
> q_in = sin(x+y-2*tc)
> q_in_1 = sin(x+y-2*tc1)
> q_in_2 = sin(x+y-2*tc2)
> 
> ...
> while ...:
>     tc.assign(t)
>     tc1.assign(...)
>     tc2.assign(...)
>     # your solve calls here
> ```

Thanks, this does save time, but does it affect accuracy if I want to test the order? I would like to know what quadrature rules and quadrature points are used in firedrake?

**Comment by wence-** [comment]
> Thanks, this does save time, but does it affect accuracy if I want to test the order? I would like to know what quadrature rules and quadrature points are used in firedrake?

For polynomial integrands, UFL picks a quadrature rule that integrates exactly. Obviously for non-polynomial expressions this is not possible so it estimates something that is conservative.

You can select the degree of polynomials you want to integrate directly by specifying it in the measure (e.g. `integrand*dx(degree=5)` would pick a rule that integrates degree 5 polynomials exactly. On triangles at moderate degree, the quadrature rules are hand-coded (see https://github.com/firedrakeproject/fiat/blob/master/FIAT/quadrature_schemes.py#L328). At high degree it uses the collapsed tensor product schemes of Karniadakis and Sherwin (see https://github.com/firedrakeproject/fiat/blob/master/FIAT/quadrature.py)

**Comment by zhyxue0** [comment]
> > Thanks, this does save time, but does it affect accuracy if I want to test the order? I would like to know what quadrature rules and quadrature points are used in firedrake?
> 
> For polynomial integrands, UFL picks a quadrature rule that integrates exactly. Obviously for non-polynomial expressions this is not possible so it estimates something that is conservative.
> 
> You can select the degree of polynomials you want to integrate directly by specifying it in the measure (e.g. `integrand*dx(degree=5)` would pick a rule that integrates degree 5 polynomials exactly. On triangles at moderate degree, the quadrature rules are hand-coded (see https://github.com/firedrakeproject/fiat/blob/master/FIAT/quadrature_schemes.py#L328). At high degree it uses the collapsed tensor product schemes of Karniadakis and Sherwin (see https://github.com/firedrakeproject/fiat/blob/master/FIAT/quadrature.py)



> > Thanks, this does save time, but does it affect accuracy if I want to test the order? I would like to know what quadrature rules and quadrature points are used in firedrake?
> 
> For polynomial integrands, UFL picks a quadrature rule that integrates exactly. Obviously for non-polynomial expressions this is not possible so it estimates something that is conservative.
> 
> You can select the degree of polynomials you want to integrate directly by specifying it in the measure (e.g. `integrand*dx(degree=5)` would pick a rule that integrates degree 5 polynomials exactly. On triangles at moderate degree, the quadrature rules are hand-coded (see https://github.com/firedrakeproject/fiat/blob/master/FIAT/quadrature_schemes.py#L328). At high degree it uses the collapsed tensor product schemes of Karniadakis and Sherwin (see https://github.com/firedrakeproject/fiat/blob/master/FIAT/quadrature.py)

Thanks for your detailed answer.
