### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by sv2518** [firedrakeproject/firedrake#2439]
I think firedrake build is currently failing, see the CI on one of my branches here https://github.com/firedrakeproject/firedrake/runs/6397133289?check_suite_focus=true but I assume it's the same on master. It's failing because `setuptools` and `wheel` are not installed at the right version (there seems to be some incompatibility). I had this issue locally too yesterday and just pinned the version to `setuptools==59.2.0` and `wheel==0.37.0`. Should we do the same in the firedrake install?

**Comment by ksagiyam** [comment]
More recent PRs do not seem to have any issues, though: https://github.com/firedrakeproject/firedrake/actions

**Comment by sv2518** [comment]
Ah, ok let me just try to rerun the tests then.

**Comment by sv2518** [comment]
Ah, actually those PRs are not more recent. The last rerun of the tests on my branch was 10 hours ago, the last rerun on your branch e.g. was 18 hours ago. We are retriggering our runs so they are not at the top of the list that you linked.

**Comment by ksagiyam** [comment]
You are right. I was able to reproduce: https://github.com/firedrakeproject/firedrake/runs/6403097841?check_suite_focus=true

Can you make a PR with your fix?

**Comment by dham** [comment]
Fixed in #2441
