### ISSUE TITLE
Installing on Apple M1 issues

### ISSUE THREAD

**Issue by noforiopoku** [firedrakeproject/firedrake#2445]
I'm having some problems installing firedrake on my new MacBook with the M1 chip. The petsc build and installation appear to be successful, however, the python installation fails. It seems to be an architecture issue, but I'm unsure. Any help would be appreciated.

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/8703510/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/8703512/configure.log)

**Comment by dham** [comment]
We've seen this a couple of times in the last few days. For some reason, when pip is installing the dependencies of numpy it fails to install packaging. The workaround is as follows:
```
. </path/to/firedrake venv>/bin/activate
pip install packaging==20.5
firedrake-update
```
Hopefully this will continue your firedrake installl where it left off and it will run to finish.

**Comment by noforiopoku** [comment]
Thanks @dham !!! That did it. I did run into hiccups of not having automake or libtool installed, but that was simple enough to address. Thanks again!
