### ISSUE TITLE
Extra MPI routines on the Ensemble class

### ISSUE THREAD

**Issue by JHopeCollins** [firedrakeproject/firedrake#2447]
The Ensemble class currently has methods which wrap the allreduce, (i)send, and (i)recv operations for Functions.
Reduce and broadcast are also commonly used MPI routines, so it would be useful if the Ensemble class handled these too.

Looking at the source code for the existing methods, it doesn't look like this should be too tricky. I needed to broadcast over an ensemble so I've already got code for what would be the body of the bcast method.

I'm happy to pick this up and submit a pull request, but I'd be interested to hear if there are any potential sticking points to be aware.

**Comment by JHopeCollins** [comment]
Having thought about this a bit more, I have a couple more questions:
- The nonblocking ```isend```/```irecv``` methods of ```Ensemble``` access the ```Function``` data directly from ```f.dat[<int>].data``` instead of using a PETSc ```Vec``` from the context manager. This means that for a mixed function space, a seperate communication round is needed for each element of ```f.dat```, but it ensures correctness because a context-managed PETSc ```Vec``` may go out of scope before the communication finishes (see [this commit](https://github.com/firedrakeproject/firedrake/commit/cac67c027b4c2585757f266950048f9db41165b0)). For non-blocking operations, seperate communication rounds is not really a performance issue.
However, in that commit the blocking ```send```/```recv``` methods were also changed to no longer use the PETSc ```Vec``` context manager. For a ```Function``` from a  ```MixedFunctionSpace``` I believe that this may be a performance regression because it results in multiple blocking communication rounds, whereas using the PETSc ```Vec``` needs only a single communication round. The ```Vec``` scoping shouldn't be an issue here, precisely because the operations are blocking.
Is this correct, or is there something I've missed? If it is correct, is it worth reverting back to using the PETSc ```Vec``` for the blocking communications? The ```Ensemble.allreduce``` method already uses the context manager to access the underlying data of the ```Function``` being reduced. For the new methods I'd like to add to ```Ensemble```, the blocking ```bcast``` and ```reduce``` would use the context manager, and the non-blocking ```ibcast``` would access the ```f.dat.data``` directly.

- Secondly, the ```Ensemble.allreduce``` method checks that the ```Functions``` being reduced from/into are the same size using the ```Vec.getSizes``` method. Doesn't this mean that you could reduce a ```Function``` from one ```FunctionSpace``` into a ```Function``` from a different ```FunctionSpace``` as long as they both happened to have the same number of DoF? In terms of memory / MPI correctness this is fine, but it feels like it doesn't respect the intended semantics of the method. Is this supposed to be supported? Should this be changed to check whether the two functions are members of the same ```FunctionSpace``` instead? If, for some reason, someone did want to reduce between different function spaces, they could still do it manually by accessing the ```Vec``` themselves.

**Comment by wence-** [comment]
I think when I made that change (to handle nonblocking correctly) I just did it for the blocking versions as well, I think that could probably be changed back to the previous approach.

If you wanted to do the non-blocking thing in one go, you could do:
```
with f.dat.vec_ro as v:
   # send
   req1 = comm.Isend(v.array_r, ...)

req = comm.Irecv(g.dat._vec, ...)

# some time later
MPI.Request.Waitall([req1, req2])

with g.dat.vec_wo as v:
    pass
```

But that does feel a bit like magic, so one could expose the `._vec` property along with the `scatter_forward` (dat->vec) and `scatter_reverse` (vec->dat) routines.

**Comment by wence-** [comment]
I think that probably to point 2, yes, all the data exchanges on `Ensemble` should probably check for functionspace matching.

**Comment by JHopeCollins** [comment]
Hi Lawrence, thanks for taking at look at this. I'll put those changes into the PR when I get around to adding the new `Ensemble` methods (probably in a couple of weeks).

That non-blocking trick does look pretty magic! I was going to do some benchmarks for this to see how much of a difference it actually makes doing the communication in one shot. I'll do one for this trick too. Although I think that adding an extra requirement onto the non-blocking comms (on top of the usual MPI Waitall) could be pretty error-prone.
Could you point me to the scatter_forward/reverse definitions or documentation? I haven't been able to find them in Firedrake or PyOP2.

**Comment by wence-** [comment]
> That non-blocking trick does look pretty magic! I was going to do some benchmarks for this to see how much of a difference it actually makes doing the communication in one shot. I'll do one for this trick too.

It's probably better to construct models, since it's remarkably difficult to make MPI do asynchronous progress (at least last time I tried).

> Could you point me to the scatter_forward/reverse definitions or documentation? I haven't been able to find them in Firedrake or PyOP2.

The mixeddat case is here https://github.com/OP2/PyOP2/blob/master/pyop2/types/dat.py#L992-L1026 and the non-mixed case https://github.com/OP2/PyOP2/blob/master/pyop2/types/dat.py#L684-L695

**Comment by JHopeCollins** [comment]
Thanks, I'll take a look at those
