### ISSUE TITLE
Difficult to obtain the order of CG(1) convergence

### ISSUE THREAD

**Issue by tu1620808124** [firedrakeproject/firedrake#2448]
The heat equation is described as follows:
<img src="https://latex.codecogs.com/svg.image?\begin{array}{lllll}\displaystyle{\frac{\partial&space;u}{\partial&space;t}}&space;-&space;\Delta&space;u&space;=&space;0,\text{&space;in&space;}&space;\Omega&space;\times&space;(0,T)\\u(x,y,0)&space;=&space;\sin(x)\sin(y).\end{array}" title="https://latex.codecogs.com/svg.image?\begin{array}{lllll}\displaystyle{\frac{\partial u}{\partial t}} - \Delta u = 0,\text{ in } \Omega \times (0,T)\\u(x,y,0) = \sin(x)\sin(y).\end{array}" />

<img src="https://latex.codecogs.com/svg.image?\Omega&space;=&space;(0,&space;\pi)" title="https://latex.codecogs.com/svg.image?\Omega = (0, \pi)" /> and analytic solution is :
<img src="https://latex.codecogs.com/svg.image?u(x,y,t)&space;=&space;e^{-2t}\sin(x)\sin(y)." title="https://latex.codecogs.com/svg.image?u(x,y,t) = e^{-2t}\sin(x)\sin(y)." />
and  I referred to the example https://www.firedrakeproject.org/demos/burgers.py.html 
this is my code:
```
from firedrake import *
import sys
import os
N = int(sys.argv[1])
mesh = RectangleMesh(N, N, pi, pi, quadrilateral = True)
V = FunctionSpace(mesh, "CG", 1)
bc = DirichletBC(V, Constant(0), [1,2,3,4])
x,y = SpatialCoordinate(mesh)
ic  = project(sin(x)*sin(y),V)
u = Function(V, name = "Velocitynext")
u_ = Function(V,name = "Velocity")
u.assign(ic)
u_.assign(ic)
t = 0.0
t_end = 0.01
dt = 0.001
v = TestFunction(V)
a_temp = inner(grad(u),grad(v))*dx
a_time = inner((u - u_)/dt,v)*dx 
F = a_temp +a_time
while t <= t_end:
    solve(F == 0, u, bc)
    u_.assign(u)
    t += dt
u_true = interpolate(exp(-2*t_end)*sin(x)*sin(y), V)
l2 = errornorm(u_true,u,norm_type = "L2")/norm(u_true,norm_type = "L2")
l1 = errornorm(u_true,u,norm_type = "L1")/norm(u_true,norm_type = "L1")
print(l1)
print(l2)
```
but ,the results look bad:
![1652928414(1)](https://user-images.githubusercontent.com/49664375/169193504-009bd34b-ee34-407a-9be7-3124e4a66dec.png)
when the mesh element number is small ,it seems good ,but when the number increasing，the error decrease is not significant.

**Comment by dham** [comment]
You're using backward Euler in time which is only first order, and you're not increasing the number of timesteps as you refine the mesh. I therefore suspect that your timestepping error is dominating your spatial error.

I suggest you start by solving a steady heat equation (i.e. positive defininite Helmholtz) and convincing yourself that the spatial error converges at the right rate. Then do time stepping but use a second order timestepper and keep reducing the timestep until the error stops decreasing (so that you're confident that the spatial error is dominant).

**Comment by tu1620808124** [comment]
Thank you, with your help, my confusion has been resolved ！
