### ISSUE TITLE
BDM elements error

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2467]
When I run the tutorial  [A mixed formulation of the Poisson equation](https://firedrakeproject.org/demos/poisson_mixed.py.html), I get the error feedback:

```shell
/home/firedrake/src/fiat/FIAT/check_format_variant.py:9: DeprecationWarning: Variant of BDM element will change from point evaluation to integral evaluation.  You should project into variant="integral"
  warnings.warn('Variant of ' + element + ' element will change from point evaluation to integral evaluation.'

```

How to solve it?

**Comment by zhyxue0** [comment]
> I think you might be using an older version of Firedrake / FIAT; I don't run into this warning and the [current version](https://github.com/firedrakeproject/fiat/blob/master/FIAT/check_format_variant.py) of that file from FIAT no longer has it. Can you try the following code:
> 
> ```python
> from firedrake import *
> mesh = UnitSquareMesh(32, 32)
> 
> element = FiniteElement("BDM", "triangle", 1, variant="integral")
> BDM = FunctionSpace(mesh, element)
> DG = FunctionSpace(mesh, "DG", 0)
> W = BDM * DG
> 
> sigma, u = TrialFunctions(W)
> tau, v = TestFunctions(W)
> 
> x, y = SpatialCoordinate(mesh)
> f = Function(DG).interpolate(10*exp(-(pow(x - 0.5, 2) + pow(y - 0.5, 2)) / 0.02))
> 
> a = (dot(sigma, tau) + div(tau)*u + div(sigma)*v)*dx
> L = - f*v*dx
> 
> bc0 = DirichletBC(W.sub(0), as_vector([0.0, -sin(5*x)]), 3)
> bc1 = DirichletBC(W.sub(0), as_vector([0.0, sin(5*x)]), 4)
> 
> w = Function(W)
> 
> solve(a == L, w, bcs=[bc0, bc1])
> sigma, u = w.split()
> ```
> 
> to see if it works? If you're able to update your Firedrake installation, that should fix it.

Thanks, this code can work. But why do we need this step?
```
element = FiniteElement("BDM", "triangle", 1, variant="integral")
``` 
I don't quite understand why. 

And are there any other parameters for `variant`?

**Comment by danshapero** [comment]
@rckirby would be the best person to answer this, the distinction between the different variants is a little above my pay grade. If you look at the FIAT source code for BDM elements, it looks like the variant can only be "integral" or "point".

**Comment by rckirby** [comment]
`FunctionSpace` is a wrapper around creating a finite element, and it doesn't have a mechanism to pass keyword arguments like `variant` down into FIAT.  The variants in this case are whether facet degrees of freedom are defined as integral moments of the normal component or the normal component evaluated at particular points.  The latter was original in the code, and then it was discovered that it gave suboptimal nodal interpolation, so we included the former as an option but wanted to maintain backward compatibility.  But the switch was made to make moments the default not too long ago (I forget when).

And BTW, the feedback you were getting from Firedrake is a warning, not an error, that the default value was going to change.  Which it did.
