### ISSUE TITLE
How to get the value of the divergence?

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2479]
I want to check the divergence value of u
```python
from firedrake import *
import math as math
Nx = 10
Ny = Nx
Lx = 2*math.pi
Ly = Lx
mesh = RectangleMesh(Nx, Ny, Lx, Ly)
x, y = SpatialCoordinate(mesh)

element = FiniteElement("BDM", "triangle", 2, variant="integral")
BDM = FunctionSpace(mesh, element)
u_exact =  as_vector((-cos(x)*sin(y), sin(x)*cos(y)))
u = Function(BDM).interpolate(u_exact)

print("div u L1:", norm(div(u),norm_type='L1'))
print("div u L2:", norm(div(u),norm_type='L2'))
print("div u at [1,1]", div(u).at([1,1]))
```
but getting error message as follows
```shell
Traceback (most recent call last):
  File "test_8.py", line 17, in <module>
    print("div u at [1,1]", div(u).at([1,1]))
AttributeError: 'Div' object has no attribute 'at'
```

**Comment by wence-** [comment]
To evaluate at a point in space you need to first interpolate the expression into a space. You can either do this by picking a `FunctionSpace` that spans `div BDM` in your case `FunctionSpace(mesh, "P", 1)` would work and then interpolating there before calling `.at` on that function.

Or you can make a `VertexOnlyMesh` of the points you want to evaluate at:

```
vmesh = VertexOnlyMesh(mesh, [[1, 1]])

Vv = FunctionSpace(vmesh, "DG", 0)

divu_at_p = interpolate(div(u), Vv)
print(divu_at_p.dat.data_ro)
```

**Comment by zhyxue0** [comment]
> To evaluate at a point in space you need to first interpolate the expression into a space. You can either do this by picking a `FunctionSpace` that spans `div BDM` in your case `FunctionSpace(mesh, "P", 1)` would work and then interpolating there before calling `.at` on that function.
> 
> Or you can make a `VertexOnlyMesh` of the points you want to evaluate at:
> 
> ```
> vmesh = VertexOnlyMesh(mesh, [[1, 1]])
> 
> Vv = FunctionSpace(vmesh, "DG", 0)
> 
> divu_at_p = interpolate(div(u), Vv)
> print(divu_at_p.dat.data_ro)
> ```

Thanks, but DG P0 `Vv = FunctionSpace(vmesh, "DG", 0)`  seems to affect the accuracy. Because `u` is  approximated by a  polynomial of degree 2, so `div(u)` should  be a polynomial of degree 1.  However here is approximated by a  polynomial of degree 0.

If  I change the DG P0 to DG P1,  get the following  error  feedback:
``` shell 
ValueError: Only degree zero polynomials supported on point elements.
```
