### ISSUE TITLE
How to define the Tensor FunctionSpace ?

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2491]
I try to solve the incompressible Navier–Stokes equations, to handle the $\Delta \vec{u}$ term,  rewrite as

$\Delta \vec{u} = \nabla \cdot \boldsymbol{Q} $
$\boldsymbol{Q} = \nabla \vec{u} $

then the weak formulation can be derived.

Here $\boldsymbol{Q}$ is the TrialFunction, but it  is also  a **tensor,** how to define the FunctionSpace? (As far as I know there are only two options `FunctionSpace` and `VectorFunctionSpace`)

**Comment by ksagiyam** [comment]
`TensorFunctionSpace` exists: https://www.firedrakeproject.org/firedrake.html#firedrake.functionspace.TensorFunctionSpace
