### ISSUE TITLE
Block associated with LinearVariationalProblem diverges when evaluating adjoint. 

### ISSUE THREAD

**Issue by sghelichkhani** [firedrakeproject/firedrake#2513]
For applying the boundary condition on my controls, I am using a simple solve with the specific boundary conditions in the form of:

`solve(TestFunction(Q)*TrialFunction(Q)*dx == TestFunction(Q)*ControlField*dx, ControlField, bcs=BCs)`
with Q being the FunctionSpace for ControlField, BCs the specific boundary conditions. 

To avoid constructing a new solver for every iteration, I replace this solve with an equivalent LinearVariationalProblem:

` bc_prob = LinearVariationalProblem(Y*TrialFunction(Q)*dx, Y*Tfield*dx, Tfield, bcs=[bc_base, bc_top])`
`bc_solver = LinearVariationalSolver(bc_prob)`
`bc_solver.solve()`

However  the adjoint evaluation related to the LVP block (`NonlinearVariationalSolveBlock.evaluate_adj()`) now fails with :

> ConvergenceError: ('LinearSolver failed to converge after %d iterations with reason: %s', 0, 'DIVERGED_PCSETUP_FAILED')

Here is a minimal [reproducer](https://gist.github.com/sghelichkhani/edf7acc2d600165fe741bc3d8e1bd30f).

**Comment by dham** [comment]
Your `LinearVariationalProblem` has the same `Function` on the left and right sides. When the linear problem is internally converted to a nonlinear problem, this results in a spurious cancellation. We should possibly raise an exception in this case, but in any event it's not a valid problem to set up.
