### ISSUE TITLE
gmsh read error: DMPlex object has no attribute 'distributeSetDefault'

### ISSUE THREAD

**Issue by MaihgrUmosch** [firedrakeproject/firedrake#2540]
`dungeness_thetis.py` 
`Traceback (most recent call last):`
   `  File "/home/~/dungeness_thetis.py", line 47, in <module>`
`    mesh = Mesh('dungeness_v2.msh', dim=2)`
`  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func`
`  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func`
`  File "/home/~/firedrake/src/firedrake/firedrake/mesh.py", line 2041, in Mesh`
`    topology = MeshTopology(plex, name=plex.getName(), reorder=reorder,`
`  File "PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func`
`  File "PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func`
`  File "/home/~/firedrake/src/firedrake/firedrake/mesh.py", line 803, in __init__`
`    plex.distributeSetDefault(False)`
`AttributeError: 'petsc4py.PETSc.DMPlex' object has no attribute 'distributeSetDefault'`

Code recently produces this bug, after previous successful runs. Is there something wrong with the .msh file being read here? https://github.com/MaihgrUmosch/tidal_simulator

**Comment by connorjward** [comment]
I think this error is occurring because your PETSc installation is out-of-date. Does the issue persist after running `firedrake-update`?

**Comment by MaihgrUmosch** [comment]
Yes. The version is 3.18.0dev.

**Comment by MaihgrUmosch** [comment]
firedrake-update was last run on the 29th and the PETSc repo was up to date

**Comment by MaihgrUmosch** [comment]
This is happening during the firedrake-update: 

`Updating the git repository for petsc`
`Removing existing petsc installations`

**Comment by connorjward** [comment]
That's a very misleading message. Your PETSc installation won't have been removed. Has this resolved your issue?

**Comment by MaihgrUmosch** [comment]
Unfortunately not, but I'm not convinced that PETSc has updated either. How
can I check?

**Comment by connorjward** [comment]
The most straightforward thing to do is run `firedrake-update -—rebuild` to force a rebuild of PETSc and petsc4py.

**Comment by MaihgrUmosch** [comment]
Fixed, thank you.
