### ISSUE TITLE
Problem on installation

### ISSUE THREAD

**Issue by cjunho** [firedrakeproject/firedrake#2541]
I tried to install Firedrake on my server machine, but I failed to install.

The OS is
CentOS Linux release 7.9.2009 (Core)

The log files are as follows
[9firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/9448552/9firedrake-install.log)
[firedrake-update.log](https://github.com/firedrakeproject/firedrake/files/9448553/firedrake-update.log)

What caused the problem and how can I fix it?

**Comment by dham** [comment]
The first error in the firedrake install, which is probably the key issue, seems to indicate that you have two versions of libtool installed, 2.4.2 and 2.4.6, and that somehow different stages of the libspatialindex install process are finding different ones. You have quite a complex environment, with long paths containing a lot of installed tools. Possibly the culprit is in there somewhere.

**Comment by cjunho** [comment]
Thank dham for your advice.
After I asked the server manager, I fixed the different paths of the libtools 2.4.2 and 2.4.6.  The server manager said libtools 2.4.2 came from the default path "/usr/lib64" on the install script, but libtools 2.4.6 came from "/apps/applications/PYTHON/3.7/lib" which is a path when I loaded another Python module. So I fixed the path by "export PATH=/usr/bin:$PATH" as the default path and installed Firedrake. Unfortunately, something new error occurred. How should I fix the error?
[13firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/9472860/13firedrake-install.log)  
Moreover, the manager said I need to manually correct the Firedrake install script to avoid the conflict between the default path of the script and the path when I loaded modules such as gcc and cmake. So is there anything I need to correct in the script?

In addition, the manager advised about using Singularity as "github.com/firedrakeproject/firedrake/wiki/singularity". Following the instruction in the web page, and building the image and converting the sandboxed image, I have "firedrake-vanilla" folder. As usual, I access /home/firedrake/firedrake/bin, and then type source activate. But a firedrake code does not work as "ImportError: No module named firedrake". The install log file is
[14firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/9472993/14firedrake-install.log). The installation seems to succeed as the log file said, but what do you think the problem is?

Thank you.

**Comment by JDBetteridge** [comment]
If you're using Singularity you won't need to activate an environment. The singularity container can be used to run your scripts by executing:
```mpiexec -n 4 singularity run firedrake-vanilla.sif my_firedrake_script.py```

Where both the singularity container (`firedrake-vanilla.sif`) and your firedrake script (`my_firedrake_script.py`) both reside in the same directory. The example on the wiki is much more complicated, but is primarily aimed at users running Singularity on ARCHER2. If you are new to Singularity/Apptainer there is a [software carpentry tutorial](https://carpentries-incubator.github.io/singularity-introduction/about/index.html) with more information on how to run you code and how Singularity works.
