### ISSUE TITLE
`assign` should only be used for weighted sums

### ISSUE THREAD

**Issue by connorjward** [firedrakeproject/firedrake#2556]
This was discussed in the [Firedrake meeting 14/09/22](https://github.com/firedrakeproject/firedrake/wiki/Firedrake-meeting-2022-09-14#cw-assign-performance-issues-worth-fixing).

According to @dham, `assign` and `interpolate` are really the same thing except `assign` is less mathematically valid and has somewhat undefined behaviour in the adjoint. The only acceptable use case of `assign` should be for doing weighted sums (useful in RK timesteppers for example).

Someone should at some point do the following:
- Restrict `assign` to only work for weighted sums.
- Use the numpy interface to `Dats` for this. Code generation is overkill and produces substantial overhead.

**Comment by wence-** [comment]
for linear combinations you may want vecmaxpy (which avoids multiple temporarys)

**Comment by connorjward** [comment]
This has now be done.
