### ISSUE TITLE
Running out of comms

### ISSUE THREAD

**Issue by JDBetteridge** [firedrakeproject/firedrake#2566]
It is quite easy to run out of communicators if some outer loop is using Firedrake

Here is an MFE that demonstrates the issue (thanks to @connorjward ):

```python
from firedrake import *
from mpi4py import MPI

for _ in range(1000):
    comm = MPI.COMM_WORLD.Dup()
    UnitSquareMesh(1, 1, comm=comm)
    comm.Free()
```

I think we just need to be a bit more careful in Firedrake and PyOP2 where we are holding references to MPI communicators. When PyOP2's `dup_comm()` is called we should ensure a corresponding `free_comm()` is called. The `@atexit.register` function `free_comms()` should only be used as a last resort.

**Comment by wence-** [comment]
`dup_comm` is _meant_ to stash the dupped communicator as an attribute on the user communicator.

So:

```
comm1 = dup_comm(MPI.COMM_WORLD)
comm2 = dup_comm(MPI.COMM_WORLD)
comm1 == comm2
```

I guess that the problem is that you need a `__del__` on the object that holds onto the comm to call `free_comm` ?

**Comment by JDBetteridge** [comment]
Yes, exactly! Any Firedrake object that holds a _new_ reference to a comm (which is returned by `dup_comm()` should free it. Mesh is the most obvious example.

**Comment by wence-** [comment]
> Yes, exactly! Any Firedrake object that holds a _new_ reference to a comm (which is returned by `dup_comm()` should free it. Mesh is the most obvious example.

You don't have to worry about _new_ reference or not, the inner communicator is ref-counted, so just make sure that any firedrake object that called `dup_comm` calls `free_comm` when it is released.

**Comment by JDBetteridge** [comment]
Fixed by https://github.com/OP2/PyOP2/pull/676
