### ISSUE TITLE
Linux update broke PETSc

### ISSUE THREAD

**Issue by adiegel** [firedrakeproject/firedrake#2571]
I just updated my linux machine and am now getting the error: 

NameError: name 'PETSc' is not defined

when I try to run my code. So, I attempted to run an update for "Firedrake with firedrake-update --rebuild". However, when I try to run this command, I get the error:

Finding dependencies of firedrake

Traceback (most recent call last):
  File "/home/mathstudent/firedrake/src/../bin/firedrake-update", line 1854, in <module>
    name = split_requirements_url(p)[0]
  File "/home/mathstudent/firedrake/src/../bin/firedrake-update", line 783, in split_requirements_url
    spliturl = url.split("://")[1].split("#")[0].split("@")
IndexError: list index out of range

Can anyone help me fix my broken connection with PETSc or do I need to uninstall and reinstall Firedrake?

Thanks!

**Comment by dham** [comment]
We're not amazingly robust against the operating system updating libraries under the feet of the Firedrake install. In theses circumstances a clean install is the simplest and safest way forward.
