### ISSUE TITLE
HDG Tutorial

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2583]
Hello, developers. 

I start to learn HDG by firedrake. Although I read `Slate: Extending Firedrake's Domain-Specific Abstraction to Hybridized Solvers for Geoscience and Beyond`, I still have a lot of confusion. Can you provide a complete HDG tutorial(for any equation) like [A time-dependent DG advection equation using upwinding.](http://www.firedrakeproject.org/demos/DG_advection.py.html)?  

Thank you very much!

**Comment by JDBetteridge** [comment]
Have you looked at the Hybridisation notebook?

https://nbviewer.org/github/firedrakeproject/firedrake/blob/master/docs/notebooks/09-hybridisation.ipynb

This is using a mixed conforming problem, not DG, but the ideas are very similar.

There are also a few examples lurking in the test suite if they are useful to you https://github.com/firedrakeproject/firedrake/blob/master/tests/slate/test_hdg_poisson.py

**Comment by zhyxue0** [comment]
> Have you looked at the Hybridisation notebook?
> 
> https://nbviewer.org/github/firedrakeproject/firedrake/blob/master/docs/notebooks/09-hybridisation.ipynb
> 
> This is using a mixed conforming problem, not DG, but the ideas are very similar.
> 
> There are also a few examples lurking in the test suite if they are useful to you https://github.com/firedrakeproject/firedrake/blob/master/tests/slate/test_hdg_poisson.py

Thanks a lot,  I am glad we implemented the code from the same paper.
I mentioned in  #2603， I have two question:
1. Handling of integrals on interior faces ：
To calculate this  term $\langle\hat{q} \cdot n, w\rangle_K$ 
```python
# My code
inner(qhat('+'),n('+'))*w('+')*dS + inner(qhat('-'),n('-'))*w('-')*dS
# Slate code
inner(jump(qhat, n=n), w('+'))*dS
```
My code get wrong results, but should not it be alternate for `w`?  `w` is discontinuous in two cells, why only choose `w('+')`?

2. To handle DirichletBC, shouldn't it be Weakly imposed BC ?
``` python
# My code 
# (1.3c)  Dirichlet BC condition
a += uhat*mu*ds
L+= g_Dirichlet * mu *ds

# Slate Code
bc_multiplier = DirichletBC(W.sub(2), p_exact, "on_boundary")

```

**Comment by JDBetteridge** [comment]
I believe this was referenced in a different discussion. Feel free to open a new issue if this is not the case.
