### ISSUE TITLE
Loo.py caching grows indefinitely

### ISSUE THREAD

**Issue by JDBetteridge** [firedrakeproject/firedrake#2610]
On my workstation I see
```
13G	/home/jbetteri/.cache/pytools/pdict-v4-loopy-schedule-cache-v4-2022.1-islpy2022.2.1-cgen2020.1-3988272b385fd770a3427b539e8b27e367f9db33-v1-py3.9.7.final.0
```
As one of many very large caches (The workstation supports multiple Python versions and Firedrake builds)

Perhaps we should be clearing the `loo.py` cache when we run `firedrake-update` or `firedrake-clean`.

**Comment by dham** [comment]
Yes. Should be cleared on `firedrake-clean`.
