### ISSUE TITLE
Intermittent failure (SEGFAULT) of various tests on CI

### ISSUE THREAD

**Issue by JDBetteridge** [firedrakeproject/firedrake#2617]
Several instances of 

`tests/regression/test_periodic_rectangle_advection.py::test_periodic_rectangle_advection[DG0-x-quad]`

Causing CI tests to fail. [Example](https://github.com/firedrakeproject/firedrake/actions/runs/3384500410/jobs/5621529369)

        > Just to note, trunk failed yesterday with what looked like a segfault in one of the tests (periodic dg advection).

Looks like an intermittent failure, I couldn't reproduce locally or on the build hardware, but I'll keep an eye on it

_Originally posted by @JDBetteridge in https://github.com/firedrakeproject/firedrake/issues/2613#issuecomment-1302198800_

**Comment by JDBetteridge** [comment]
Immediately fails when run with `PYOP2_CFLAGS="-fsanitize=address"`

**Comment by wence-** [comment]
That might be a problem with libasan not being dynloaded (can you get any firedrake program to run when linked compiled with `-fsanitize=address`?) You might need some LD_PRELOAD magic.

**Comment by JHopeCollins** [comment]
This also happened with `tests/multigrid/test_poisson_gtmg.py::test_scpc_mixed_poisson_gtmg` when running the CI for PR #2639

**Comment by JDBetteridge** [comment]
This issue appears to have gone away
