### ISSUE TITLE
How to change the value of Function u

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2622]
I try to solve a time dependent problem. 
To prevent program crashes. I write the  `Function` `u` for each time step into a `pvd` file or a` txt` file.

Then run the program again at time `t`.
First, read `u_load` from `pvd` file or `txt` file.
Second, assign value `u`( `u = Function(V_h)` ) with a  numpy array `u_load`

How can I achieve this?

**Comment by danshapero** [comment]
PVD files are good for reading into VTK but not so much for reading back in and resuming a simulation. Instead, you could try the `CheckpointFile` class, which writes to HDF5; it's described [here](https://firedrakeproject.org/checkpointing.html). Going to close this but feel free to reopen if need be!
