### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by gazcaorozco** [firedrakeproject/firedrake#2641]
[firedrake.json.zip](https://github.com/firedrakeproject/firedrake/files/10043466/firedrake.json.zip)

Hello, could you please help with a zenodo release?

Thanks!
Alexei

**Comment by ksagiyam** [comment]
Created Zenodo meta-release.
Tag is `Firedrake_20221121.0`
DOI is 10.5281/zenodo.7342357
Zenodo URL is https://zenodo.org/record/7342357
BibTeX

```bibtex
@misc{zenodo/Firedrake-20221121.0,
 key   = {zenodo/Firedrake-20221121.0},
 title = {{Software used in `Numerical approximation of rate-type perfect plasticity via implicit constitutive relations'}},
 year  = {2022},
 month = {nov},
 doi   = {10.5281/zenodo.7342357},
 url   = {https://doi.org/10.5281/zenodo.7342357},
}

```
Thanks!

**Comment by gazcaorozco** [comment]
Thanks!
