### ISSUE TITLE
Parallel deadlock after assignment

### ISSUE THREAD

**Issue by jrmaddison** [firedrakeproject/firedrake#2668]
The following example deadlocks on 4 processes after the assignment. `A` and `B` are displayed, but `C` is not displayed.

The code does not deadlock if the assignment is removed, and I have not been able to trigger the deadlock without the assignment.

```
from firedrake import *

import sys

mesh = UnitSquareMesh(10, 10)
space = FunctionSpace(mesh, "Lagrange", 1)
test, trial = TestFunction(space), TrialFunction(space)
u = Function(space)
v = Function(space)

sys.stdout.write("A\n")
sys.stdout.flush()

v.assign(2 * u)

sys.stdout.write("B\n")
sys.stdout.flush()

solve(inner(trial, test) * dx == inner(Constant(1.0), test) * dx,
      u)
sys.stdout.write("C\n")
sys.stdout.flush()
```

**Comment by connorjward** [comment]
I'm not able to reproduce this locally. @JDBetteridge what about you?

**Comment by wence-** [comment]
@jrmaddison can you attach to the processes and provide a C-level backtrace?

**Comment by ReubenHill** [comment]
This might prove useful for doing what @wence- suggests https://github.com/firedrakeproject/firedrake/wiki/Parallel-MPI-Debugging-with-tmux-mpi-(python-and-c!)

**Comment by jrmaddison** [comment]
With complex Firedrake, as that is my most recent build (yesterday).

[0.log](https://github.com/firedrakeproject/firedrake/files/10165417/0.log)
[1.log](https://github.com/firedrakeproject/firedrake/files/10165416/1.log)
[2.log](https://github.com/firedrakeproject/firedrake/files/10165415/2.log)
[3.log](https://github.com/firedrakeproject/firedrake/files/10165413/3.log)

**Comment by wence-** [comment]
Rank 1 is in `Comm_dup`, everyone else is in `VecCreate`. @JDBetteridge I think you have made bugs.

**Comment by jrmaddison** [comment]
A simpler example

```
from firedrake import *

import gc
import mpi4py.MPI as MPI
import sys

l = []
l.append(l)
l.append(Constant(0.0))
del l

sys.stdout.write("A\n")
sys.stdout.flush()

if MPI.COMM_WORLD.rank == 0:
    gc.collect()

Constant(0.0).assign(Constant(1.0))

sys.stdout.write("B\n")
sys.stdout.flush()
```

I believe the error is caused by communicators not being freed collectively, in this example via `Constant.__del__`.

**Comment by wence-** [comment]
That sounds right.

**Comment by JDBetteridge** [comment]
@jrmaddison I see the deadlock with your second failing example. This is related to `Constant`s not having an associated mesh, in the near future we will be changing Firedrake's behaviour so constants _must_ have associated mesh.

If you add something like:
```python
m = UnitIntervalMesh(10)
Constant(0.0, domain=m)
```

Does the deadlock go away?

**Comment by jrmaddison** [comment]
@JDBetteridge Yes, but the following deadlocks on two processes.

```
from firedrake import *

import gc
import mpi4py.MPI as MPI
import sys

mesh = UnitIntervalMesh(10)

l = []
l.append(l)
l.append(Constant(0.0, domain=mesh))
l.append(mesh)
del mesh, l

sys.stdout.write("A\n")
sys.stdout.flush()

if MPI.COMM_WORLD.rank == 0:
    gc.collect()

mesh = UnitIntervalMesh(10)
Constant(0.0, domain=mesh).assign(Constant(1.0, domain=mesh))

sys.stdout.write("B\n")
sys.stdout.flush()
```

Here the garbage collection on rank zero leads to a call to `pyop2.mpi.free_comm` on rank zero only, and not on rank one.

`__del__` methods call `pyop2.mpi.decref`, but the call of the `__del__` methods need not be collective.

**Comment by JDBetteridge** [comment]
Yes, I see the issue. I the fix is more tricky than I anticipated, if you have code that needs an immediate fix I have this hacky workaround:
```python
from pyop2.mpi import internal_comm
delete_me_at_end = internal_comm(MPI.COMM_WORLD)
```

Essentially this just holds onto a ref for the internally duplicated COMM_WORLD (or whichever comm you wish to use) so that it doesn't drop to zero, even if the generational garbage collector is cleaning up meshes.

To fix this properly I need to add a bit more machinery to PyOP2. I'll update here when it goes in.
