### ISSUE TITLE
yaksa: leaked handle pool objects

### ISSUE THREAD

**Issue by tu1620808124** [firedrakeproject/firedrake#2672]
Hi,

when I use ```mpirun -np 2 python *.py```,  it seems mpirun any code,warning will appear```yaksa: 1 leaked handle pool objects```,for example the *.py is  
```
from firedrake import *
mesh = UnitSquareMesh(64, 64)
V = FunctionSpace(mesh, "CG", 1)
bc = DirichletBC(V, Constant(0), [1, 2])
x,y = mesh.coordinates
f = interpolate(10*exp(-((x - 0.5)**2 \
    + (y - 0.5)**2) / 0.02), V)
g = interpolate(sin(5*x), V)

u = TrialFunction(V)
v = TestFunction(V)
a = inner(grad(u), grad(v))*dx
L = f*v*dx + g*v*ds
u = Function(V)
solve(a == L, u, bc)
outfile = File("u_poissonCG.pvd")
outfile.write(u)
```
it's seems a problem about my mpi, and how i can deal with it?

**Comment by wence-** [comment]
I suspect this is related to the recent MPI communicator changes from @JDBetteridge

**Comment by JDBetteridge** [comment]
@tu1620808124 I have been seeing this issue for a very long time running MPICH on Arch Linux. (Well before I refactored communicators in PyOP2)

The full message is:
```
[WARNING] yaksa: 2 leaked handle pool objects
```

I believe it is coming from MPICH itself. I see the same warning running other Python scripts and PETSc executables.
Note that this is a warning and not an error and I have been safely ignoring it.

If the above warning is causing some other issues, specifically with Firedrake, feel free to elaborate below.

**Comment by tu1620808124** [comment]
When I am dealing with a time-related problem, I use implicit time discretization, the space is the DG method, and the degree of freedom is obviously lower than 100,000. After a certain number of timesteps under multi-core, the memory will be insufficient, but no problem with single-core. I'm not sure if it's related.

**Comment by tu1620808124** [comment]
> 
> ```
> [WARNING] yaksa: 2 leaked handle pool objects
> ```
> 
> I believe it is coming from MPICH itself. I see the same warning running other Python scripts and PETSc executables. Note that this is a warning and not an error and I have been safely ignoring it.
> 
> If the above warning is causing some other issues, specifically with Firedrake, feel free to elaborate below.

**Comment by tu1620808124** [comment]
When I am dealing with a time-related problem, I use implicit time discretization, the space is the DG method, and the degree of freedom is obviously lower than 100,000. After a certain number of timesteps under multi-core, the memory will be insufficient, but no problem with single-core. I'm not sure if it's related.

**Comment by JDBetteridge** [comment]
Could you run your code under a memory profiler and share the results? Memory profiler is the suggestion from the [Firedrake website](https://firedrakeproject.org/optimising.html#memory-profiler).

Check you aren't keeping every timestep in memory, which would cause the memory use to grow continually. If you are still seeing issues try to create a minimal failing example to post here.

I'm still not sure it's related to the leaked handle pool objects.

**Comment by JDBetteridge** [comment]
@tu1620808124 I have taken your example and run it on my workstation and am seeing very similar numbers, so I don't think there is an issue with your installation.

A few points to help you track down your performance issues:
1. memory profiler is a great tool for tracking your memory usage, when you're using it with MPI you can use it as you have done to see total memory us. Or, if you suspect that one rank is consuming more memory than others you can run `mprof run --multiprocess python script.py` and the plot will show the memory consumption of each rank individually.
2. I'd take the time to read all the information on the [optimising performance page](https://firedrakeproject.org/optimising.html#optimising-firedrake-performance). There are quite a few tools there that will help you profile your code, the flamegraph may be particularly useful.
3. You currently call solve repeatedly in a loop, which can lead to [poor performance](https://firedrakeproject.org/optimising.html#calling-solve-repeatedly). You can change your code as follows to get better performance and reduce your memory footprint at the same time:
```diff
$ diff -u sipg_heat.py sipg_heat2.py 
--- sipg_heat.py        2022-12-12 10:14:27.315673505 +0000
+++ sipg_heat2.py       2022-12-12 10:34:33.005629677 +0000
@@ -5,7 +5,6 @@
 #define mesh
 mesh = RectangleMesh(256, 256,1.0,1.0)
 V = FunctionSpace(mesh, "DG", 1)
-bc = []
 x,y = SpatialCoordinate(mesh)
 n = FacetNormal(mesh)
 
@@ -33,9 +32,12 @@
 f = (1+8*pi**2)*sin(2*pi*x)*sin(2*pi*y)*exp(tc)
 F = a_temp + a_time - f*v*dx
 
+nlvp = NonlinearVariationalProblem(F, u)
+solver = NonlinearVariationalSolver(nlvp)
+
 while abs(t - t_end) > 0.1*dt:
     tc.assign(t + dt)
-    solve(F == 0, u, bc)
+    solver.solve()
     u_.assign(u)
     t += dt
```

Before:
![4_rank](https://user-images.githubusercontent.com/43041811/207028360-a1021453-a8d4-4d67-a951-edcfa610f54f.png)
After:
![ver2_4_rank](https://user-images.githubusercontent.com/43041811/207028390-c4e12587-737a-483e-9166-5ddeb533fd61.png)

If you have any more questions I propose we convert this to a github discussion and others can chime in with suggestions.
