### ISSUE TITLE
Installation failure on mac 

### ISSUE THREAD

**Issue by sghelichkhani** [firedrakeproject/firedrake#2689]
I was wondering if anyone else has had this issue on (M1) macs:

ptscotch installation of petsc fails. It seems like `libptscotchparmetisv3` is installed, but clang cannot find it: 

```
ld: library not found for -lptscotchparmetis
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Linker output before filtering:
```
macOs 13.1
Clang version:
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

firedrake log:
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10233367/firedrake-install.log)

petsc log:
[configure.log](https://github.com/firedrakeproject/firedrake/files/10233361/configure.log)

**Comment by ksagiyam** [comment]
I found:
```
ld: warning: object file (/Users/sghelichkhani/firedrake/src/petsc/default/lib/libptscotchparmetisv3.a(parmetis_dgraph_part_f_v3.o)) was built for newer macOS version (11.0) than being linked (10.15)
```
The first thing I would try is to change MACOSX_DEPLOYMENT_TARGET from 10.15 to 11.0 here in the install script:
https://github.com/firedrakeproject/firedrake/blob/660d46b5f380ed23ec3074efdf9301033fc1e3fa/scripts/firedrake-install#L1158

Related discussion: https://github.com/firedrakeproject/firedrake/discussions/2598

**Comment by hsharsh** [comment]
Hi, I am having a similar issue while installing on M1 pro (macOS 13.0.1). Mine seems to be around blaslapack-dir. I have changed the MACOSX_DEPLOYMENT_TARGET from 10.15 to 11.0 but that doesn't seem to help either.

firedrake log: [firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10241910/firedrake-install.log)
petsc configure log: [configure.log](https://github.com/firedrakeproject/firedrake/files/10241911/configure.log)

**Comment by sghelichkhani** [comment]
Thanks @ksagiyam. It resolved my issue. 
@hsharsh Seems like clang is trying to use macOS-x86_64 architecture. Could you try setting MACOSX_DEPLOYMENT_TARGET to 11.0 instead of 13.0? I assume Xcode deployment target is different from macOS version.

**Comment by hsharsh** [comment]
I did try both 11.0 and 13.0 but it doesn't seem to work for me.

**Comment by ksagiyam** [comment]
Your install log says that you are using `/opt/anaconda3/bin/python3`. I would try installing with homebrew python.

Please see:

https://firedrakeproject.org/download.html#system-requirements (also see `System anti-requirements`subsection)

https://github.com/firedrakeproject/firedrake/discussions/2591

**Comment by hsharsh** [comment]
Thanks for that! My bad for not noticing that. Using the correct python installation did fix the problem.
