### ISSUE TITLE
Question about compiler optimization

### ISSUE THREAD

**Issue by zhyxue0** [firedrakeproject/firedrake#2694]
Hi everyone! I found some code from a long time ago. 
such as from dolfin https://www.repository.cam.ac.uk/bitstream/handle/1810/236975/heat_treatment_solver.py?sequence=1
``` python
# Some FFC parameters
parameters["form_compiler"]["log_level"]    = INFO
parameters["form_compiler"]["cpp_optimize"] = True
parameters["form_compiler"]["cpp_optimize_flags"] = "-O3"
parameters["form_compiler"]["optimize"]     = True
```

And some more from firedrake https://github.com/firedrakeproject/firedrake-bench/blob/master/poisson/firedrake_poisson.py
``` python
parameters["assembly_cache"]["enabled"] = False
parameters["coffee"]["licm"] = True
parameters["coffee"]["ap"] = True
```

I have two questions.
1. What is the meaning of these parameters?  Is there some corresponding documentation? And can I set more parameters?
2. In https://github.com/firedrakeproject/firedrake-bench/blob/master/poisson/firedrake_poisson.py,  it mentions `removing calls to ffc in firedrake version`.  Are there automatically set compiler optimization parameters in firedrake?

**Comment by JDBetteridge** [comment]
COFFEE has now largely been replaced by loopy. You can change some of the compilation flags by tweaking PYOP2 [environment variables](https://github.com/OP2/PyOP2/blob/master/pyop2/configuration.py#L81) (not really documented, but you can probably understand from the code what they do) or making your own [compiler object](https://github.com/OP2/PyOP2/blob/master/pyop2/compilation.py#L496).

It might be easier to answer this question if you made it clearer what you are trying to achieve by changing these options? For general performance tuning, [here](https://firedrakeproject.org/optimising.html) is a good place to start.

**Comment by JDBetteridge** [comment]
Closing. Please consider opening a discussion if more information is required
