### ISSUE TITLE
Ubuntu: firebrake installation error

### ISSUE THREAD

**Issue by chamabdoul-cell** [firedrakeproject/firedrake#2717]
Hi Dear,

I am having trouble installing firebrake on ubuntu. Below is the output after I try to install:

Installing pip dependencies for pyadjoint
No dependencies found. Skipping.
Installing pip dependencies for firedrake
Traceback (most recent call last):
  File "/home/chama/firedrake-install", line 1865, in <module>
    pip_requirements(p, compiler_env)
  File "/home/chama/firedrake-install", line 991, in pip_requirements
    run_pip_install_wrap(reqs, parallel_compiler_env)
  File "/home/chama/firedrake-install", line 984, in run_pip_install_wrap
    run_pip_install([req])
  File "/home/chama/firedrake-install", line 965, in run_pip_install
    check_call(pipinstall + pipargs)
  File "/home/chama/firedrake-install", line 653, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/chama/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy', '-vvv', 'vtk>=9.0.1']' returned non-zero exit status 2.

Install log saved in /home/chama/firedrake-install.log

**Comment by connorjward** [comment]
You failed with the message:
```
  Error during download/extract/detection of PTSCOTCH:
  Unable to clone ptscotch
  Could not execute "['git clone  https://gitlab.inria.fr/scotch/scotch.git
  /home/chama/firedrake/src/petsc/default/externalpackages/git.ptscotch']":
  Cloning into '/home/chama/firedrake/src/petsc/default/externalpackages/git.ptscotch'...
  fatal: unable to access 'https://gitlab.inria.fr/scotch/scotch.git/': Failed to connect
  to gitlab.inria.fr port 443 after 130919 ms: Connection timed out
```

Can you please try the installation again, perhaps somewhere with a better network connection? You should delete the existing `firedrake` venv first.

**Comment by chamabdoul-cell** [comment]
Network is a big issue, which I have little choice. I removed everything and tried to install again, but I am getting similar issue. see the attached log file.
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10455912/firedrake-install.log)

**Comment by connorjward** [comment]
Unfortunately `firedrake-install` is not smart enough to handle poor network connections. There are some tricks you can pull to make PETSc use local packages instead of cloning them during install but the latest installation broke cloning the Firedrake repo so those tricks won't help.

**Comment by chamabdoul-cell** [comment]
Hi Connor,

Thank you very much for your help. The installation is fine. I am testing it now.
I really appreciate.

My Regards,
