### ISSUE TITLE
Faild while installing PETSc

### ISSUE THREAD

**Issue by Komiller** [firedrakeproject/firedrake#2736]
[configure.log](https://github.com/firedrakeproject/firedrake/files/10498151/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10498158/firedrake-install.log)
This in console.log:
Possible ERROR while running linker: exit code 1
stderr:
/usr/bin/ld: cannot find -lpetsc-ufod4vtr9mqHvKIQiVAm: No such file or directory
collect2: error: ld returned 1 exit status

**Comment by connorjward** [comment]
The first thing I notice about this which seems off is that you are running the installer as root. Firedrake assumes a non-root install. I don't know if that is causing your error but it may be informative to try as a regular user.

**Comment by Komiller** [comment]
Repeated:
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10502676/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/10502694/configure.log)

**Comment by connorjward** [comment]
It looks like your are using WSL and trying to install under `/mnt/c`. This is known to cause issues ([source](https://github.com/firedrakeproject/firedrake/wiki/Installing-on-Windows-Subsystem-for-Linux)). Could you try again but try to install to `~/firedrake` or similar?
