### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by nbouziani** [firedrakeproject/firedrake#2762]
Can someone make a zenodo release for that file: [firedrake.zip](https://github.com/firedrakeproject/firedrake/files/10689756/firedrake.zip) ?

**Comment by wence-** [comment]
Tag is `Firedrake_20230208.0`
DOI is 10.5281/zenodo.7623009
Zenodo URL is https://zenodo.org/record/7623009
BibTeX

```bibtex
@misc{zenodo/Firedrake-20230208.0,
 key   = {zenodo/Firedrake-20230208.0},
 title = {{Software used in `Physics-driven machine learning models coupling PyTorch and Firedrake'}},
 year  = {2023},
 month = {feb},
 doi   = {10.5281/zenodo.7623009},
 url   = {https://doi.org/10.5281/zenodo.7623009},
}

```

Thanks!

**Comment by nbouziani** [comment]
Thank you!
