### ISSUE TITLE
How to access the values of a function efficiently?

### ISSUE THREAD

**Issue by stwerner97** [firedrakeproject/firedrake#2766]
Hi, I just started learning about ``firedrake``! I want to access the velocity and pressure of a fluid flow at the coordinates of a grid mesh and store their values in a ``numpy.ndarray``. What is the most efficient manner to do so? 

So far, I have tried using point evaluations (as follows), but found that the evaluation takes too long to complete if done repeatedly.
```python
# create meshgrid
x = np.linspace(0.0, Lx, num=128)
y = np.linspace(0.0, Ly, num=256)
x, y = np.meshgrid(x, y)

# use point evaluations to access velocity and pressure values (here, q is of type firedrake.function.Function)
coordinates = np.dstack((x, y)).reshape(-1, 2)
values = q.at(coordinates)
velocity, pressure = zip(*values)
``` 
What other options do I have to access the velocity and pressure more efficiently? Could I define a ``RectangleMesh`` and somehow project or interpolate the values from the original mesh on which the function ``q`` is defined? I also though about mapping values based on what coordinate is closest in the original mesh.

**Comment by ReubenHill** [comment]
You can try creating a `VertexOnlyMesh` which you can interpolate on to:
```python
# create meshgrid
x = np.linspace(0.0, Lx, num=128)
y = np.linspace(0.0, Ly, num=256)
x, y = np.meshgrid(x, y)

# use point evaluations to access velocity and pressure values (here, q is of type firedrake.function.Function)
coordinates = np.dstack((x, y)).reshape(-1, 2)
vm = VertexOnlyMesh(mesh_q_is_on, coordinates)  # mesh of vertices at your coordinates - creating this takes a similar amount of time as each q.at(coordinates) but you can pull it outside of any loop
W = FunctionSpace(vm, "DG", 0)  # The only valid function space on a VertexOnlyMesh - you can pull this out of the loop too
point_cloud = Function(W)  # this can also be pulled out

for i in range(lots)
    q_at_coords = point_cloud.interpolate(q)  # Point evaluation
    values = q_at_coords.dat.data_ro   # the velocity and pressure at each coordinate in the order you specified coordinates when constructing your VertexOnlyMesh
```

**Comment by stwerner97** [comment]
Thanks so much for your reply! Accessing the values in this way is much faster than before.
