### ISSUE TITLE
Having trouble installing firedrake on my macos

### ISSUE THREAD

**Issue by chamabdoul-cell** [firedrakeproject/firedrake#2777]
Hi Dear

Could anyone help me install firedrake on my macos ventura 13.1?
I have followed the instructions
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10768200/firedrake-install.log)
 given in the documentation, but I keep getting error.

Attache is the log file.

**Comment by ksagiyam** [comment]
Could you give this a try?

https://stackoverflow.com/questions/62971964/mac-brew-doctor-show-warning-homebrews-sbin-was-not-found-in-your-path-but-you

**Comment by chamabdoul-cell** [comment]
I followed the links but get different error. Attached is the corresponding 
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10801209/firedrake-install.log)
log file.

**Comment by chamabdoul-cell** [comment]
Hi Ksagiyam,
The above code did not work. bellow is the output of the error.

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**Comment by ksagiyam** [comment]
Does this diagram help? https://www.firedrakeproject.org/download.html#debugging-install-problems

**Comment by chamabdoul-cell** [comment]
I am still getting the error for the installation. And I have followed the link. The error is now different than the preview. I have attached the new .
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10818993/firedrake-install.log)
log file

**Comment by ksagiyam** [comment]
```
2023-02-23 22:05:59,083 WARNING Failed to clone COFFEE using ssh, falling back to https.
2023-02-23 22:05:59,083 DEBUG  Running command 'git clone -q --recursive https://github.com/coneoproject/COFFEE.git'
2023-02-23 22:17:00,115 DEBUG  error: 2583 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```
seems to indicate that you have the Internet connectivity issue. I would first follow this link https://github.com/desktop/desktop/issues/13642, say, and try to fix this. There seems to be other potentially useful pages if I search the error message on the Internet. You can run `git clone -q --recursive https://github.com/coneoproject/COFFEE.git` to check if the problem has been fixed.

**Comment by chamabdoul-cell** [comment]
Ok I will check that. maybe my internet is slow. 

Thanks.

**Comment by connorjward** [comment]
Has this been resolved?

**Comment by chamabdoul-cell** [comment]
Hi Connor,
The issue was not resolved. See attached the *.log file, from my latest attempt.

**Comment by connorjward** [comment]
You're now failing to build libspatialindex with the error message:
```
ld: symbol(s) not found for architecture x86_64
```
A quick search online provides lots of different reasons why this might be happening so I'm not totally sure what to do. 

Could you try a couple of things:
- `brew doctor` is throwing a number of warnings. Could you try and resolve them? In particular I am concerned by the line:
  ```
  Warning: Some installed formulae are deprecated or disabled.
  You should find replacements for the following formulae:
    brew-pip
  ```
- Try installing libspatialindex independently using [these instructions](https://libspatialindex.org/en/latest/install.html)? Does that work?
- Perhaps try unsetting `LDFLAGS` and `CPPFLAGS` from your environment. They look to be set to some openssl paths. I don't know if that is interfering with any build processes.

**Comment by adofarsi** [comment]
Hi! I am having issues installing on a MacBook Air M1 with Ventura 13.2.1.

I had a working version of Firedrake that I installed exactly a year ago, but I need to upgrade to access new checkpointing features.

Attached to this email you can find the logs for the installation. It fails when trying to install PETSc, but with a different error from #2793 

[configure.log](https://github.com/firedrakeproject/firedrake/files/10968695/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10968700/firedrake-install.log)

**Comment by connorjward** [comment]
> Hi! I am having issues installing on a MacBook Air M1 with Ventura 13.2.1.
> 
> I had a working version of Firedrake that I installed exactly a year ago, but I need to upgrade to access new checkpointing features.
> 
> Attached to this email you can find the logs for the installation. It fails when trying to install PETSc, but with a different error from #2793
> 
> [configure.log](https://github.com/firedrakeproject/firedrake/files/10968695/configure.log) [firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10968700/firedrake-install.log)

This is a distinct issue so moved to https://github.com/firedrakeproject/firedrake/issues/2820.
