### ISSUE TITLE
 How to set up a product interlation operator in the linear form?

### ISSUE THREAD

**Issue by baigm11** [firedrakeproject/firedrake#2788]
Dear all,

I'm trying to use the following expression in my linear form

$$\int \nabla f\cdot \nabla I_h(g\phi_h)dx$$

, but I didn't find a suitable way to do it because the interpolation operator can not directly applied to the test function in firedrake. Do you have any idea? Thank you!

**Comment by ReubenHill** [comment]
This was answered on slack by @nbouziani .

> The UFL/Firedrake interp branches are named interp_dual. 
Genming Bai
 in those branches your `I_h` term I think writes:
`Interp(g \phi_h, V)`
where `V` is the space you are interpolating into.
