### ISSUE TITLE
Firedrake installation error due to petsc/slepc compilation error using gmake 4.4.1

### ISSUE THREAD

**Issue by boutsitron** [firedrakeproject/firedrake#2793]
The error comes from a bug of gmake 4.4.1 that is now posted [here](
https://lists.gnu.org/archive/html/bug-make/2023-02/msg00144.html).

The problem with this version of gmake is that it replaces $(MAKEFLAGS) with 'w' in firedrake/src/petsc/lib/petsc/conf/rules for petsc and firedrake/src/slepc/lib/slepc/conf/slepc_rules for slepc, and the compiler finds no target for 'w'.

Could firedrake installation use gmake 4.4.0? (at the beginning of the installation make is installed via homebrew, which installs it as gmake 4.4.1).

**Comment by dham** [comment]
Yuck. I agree we'll have to do something like this until PETSc or gmake sort this out. It's not actually obvious to me how to get homebrew to install gmake 4.4.0. Do you know how we do this?

**Comment by boutsitron** [comment]
Me neither, brew install make@4.4 or make@4.4.0 does not work, and other than that, I don't know how to go about this.

**Comment by wence-** [comment]
> It's not actually obvious to me how to get homebrew to install gmake 4.4.0. Do you know how we do this?

It's _horrible_: https://cmichel.io/how-to-install-an-old-package-version-with-brew/

```
brew tap-new wence/local-make
brew extract --version=4.3 make wence/local-make
brew install make@4.3 # This _builds_ the version, because it can't find the pre-built binaries
...
```

Not fully tested, obvs.

**Comment by miguelcoolchips** [comment]
Is it possible to use this approach to pin the version of the libraries installed by homebrew?

**Comment by marcomoschetta** [comment]
> ```
> brew tap-new $USER/local-make
> brew extract --version=4.4 make $USER/local-make
> brew install make@4.4
> brew unlink make
> brew link make@4.4
> ```

I have installed firedrake following @wence- and @dham advice. It passed the test and I am using it and it works. Do I need to re-install after you updated your fork?

**Comment by boutsitron** [comment]
I don't know where we stand on this bug, but I still get it while trying to install firedrake on my MacBook M2 Max with MacOS Ventura 13.3.1 (a), even with the up-to-date firedrake-install file. 

So I incorporated a fix, by adding the following function in firedrake-install

```
def fix_rules(rules_path):
    with open(rules_path, "r") as file:
        file_data = file.read()
    # Replace the target string
    file_data = file_data.replace("$(MAKEFLAGS)", "")
    with open(rules_path, "w") as file:
        file.write(file_data)
    print(f"modified the {rules_path} file")
```

That one can call inside the build_and_install_petsc() function as

```
def build_and_install_petsc():
    log.info("Depending on your platform, PETSc may take an hour or more to build!")
    assert (
        not args.honour_petsc_dir
    )  # Belt and braces security before we start clobbering things.
    with directory("petsc"):
        petsc_dir, petsc_arch = get_petsc_dir()
        petsc_options = get_petsc_options()

        # Find and replace '$(MAKEFLAGS)' with empty string '' in the rules file
        # Creating firedrake/src/petsc/lib/petsc/conf/rules
        rules_path = os.path.join(petsc_dir, "lib", "petsc", "conf", "rules")
        fix_rules(rules_path)

	# /////  REST OF THE CODE /////
```

**Comment by connorjward** [comment]
> PETSc have [fixed](https://gitlab.com/petsc/petsc/-/issues/1336) this issue. Now we just need to update our fork which I will do ASAP.

Closing as this has been done.
