### ISSUE TITLE
Installation failure on Linux Mint 21

### ISSUE THREAD

**Issue by Yuri-Albuquerque** [firedrakeproject/firedrake#2794]
Hi. I tried to install Firedrake, but it reported an error:
```Successfully updated submodules.
Installing petsc/
Downloading Eigen from 'https://github.com/eigenteam/eigen-git-mirror/archive/3.3.3.tar.gz' to 'eigen-3.3.3.tgz'
Checking Eigen tarball integrity
Eigen tarball hash valid
Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "/home/user/project/firedrake-install", line 1856, in <module>
    install("petsc/")
  File "/home/user/project/firedrake-install", line 1022, in install
    build_and_install_petsc()
  File "/home/user/project/firedrake-install", line 1162, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "/home/user/project/firedrake-install", line 655, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/user/project/firedrake/bin/python', './configure', 'PETSC_DIR=/home/user/project/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-mpich', '--download-pastix', '--download-ptscotch', '--download-cmake', '--download-suitesparse', '--download-chaco', '--download-metis', '--download-netcdf', '--download-hwloc', '--download-ml', '--with-fortran-bindings=0', '--download-hdf5', '--with-c2html=0', '--download-eigen=/home/user/project/firedrake/src/eigen-3.3.3.tgz ', '--download-mumps', '--with-shared-libraries=1', '--download-superlu_dist', '--download-hypre', '--download-scalapack', '--with-zlib', '--download-bison', '--with-debugging
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10874251/firedrake-install.log)
=0', '--download-pnetcdf']' returned non-zero exit status 1.
```

And here is the [firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10874260/firedrake-install.log)

**Comment by danshapero** [comment]
It looks like it's failing in configuring NetCDF; can you attach the configure.log file from PETSc? Just from looking at the paths in your installation log, this should be at `/home/yuri/project/firedrake/src/petsc/configure.log`. If I got that wrong, you can do `find ~ -name "configure.log"` to search for it.

**Comment by Yuri-Albuquerque** [comment]
yeah sure, here is the [configure.log](https://github.com/firedrakeproject/firedrake/files/10874746/configure.log) and thank you for the quick response above @danshapero!

**Comment by ksagiyam** [comment]
`fatal error: curl/curl.h: No such file or directory`

so you probably need to get `libcurl`; see e.g. https://stackoverflow.com/questions/11471690/curl-h-no-such-file-or-directory.

**Comment by connorjward** [comment]
This looks to be the same as https://github.com/firedrakeproject/firedrake/issues/2803. Installing libcurl4-openssl-dev and libxml2-dev should hopefully resolve the issue. We are also fixing the installation script.

**Comment by ReubenHill** [comment]
@Yuri-Albuquerque can you retry installing with the (now updated) install script and let us know if the issue is resolved?

**Comment by Yuri-Albuquerque** [comment]
Yes, it solved. Thank you!  ![Captura de tela de 2023-03-12 13-41-51](https://user-images.githubusercontent.com/15900924/224559045-d9228cce-f95f-4aba-9cb7-ced8ac382de4.png)

Sorry for the late response guys. I was handling some personal issues here, now I'm back to work.
