### ISSUE TITLE
Option to generate random numbers into an existing Function

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#2806]
It would be nice if we could have an optional argument to the Generator methods for a Function to put the random numbers into, instead of allocating a new one. I'd do it myself but this wrapper is too clever for me!

**Comment by dham** [comment]
Random number generation is relatively expensive. Are we sure this would be worth the effort as opposed to just using `.assign`.

**Comment by colinjcotter** [comment]
Well, we do it for form assembly, which is also relatively expensive.

**Comment by dham** [comment]
That's mostly because of 2-form assembly where the construction of the tensor is properly expensive. If we only ever assembled 1-forms we might well not bother.

**Comment by colinjcotter** [comment]
ok fair enough
