### ISSUE TITLE
`CheckpointFile` can hang (likely cause of CI failures)

### ISSUE THREAD

**Issue by connorjward** [firedrakeproject/firedrake#2809]
To make repeated loads of the same mesh fast, `CheckpointFile` current has two class-level `WeakValueDictionary` objects for stashing the meshes ([source](https://github.com/firedrakeproject/firedrake/blob/master/firedrake/checkpointing.py#L521)). A weak-referencing dictionary has been used to avoid storing a global dictionary of previously loaded mesh objects (obviously a memory leak). However, this causes issues in parallel because meshes are non-deterministically cleaned up by the cyclic garbage collector so the cache can hit on one rank and miss on another.

I've managed to produce the following MFE which hangs reliably for me:
```py
import gc

from firedrake import *


# create and save a mesh
mesh_name = "mymesh"
mesh = UnitSquareMesh(100, 100, comm=COMM_WORLD, name=mesh_name)
fname = "test.h5"
with CheckpointFile(fname, "w", comm=COMM_WORLD) as meshfile:
    meshfile.save_mesh(mesh)

# load the mesh once - this populates the caches
print(f"{COMM_WORLD.rank}: loading mesh", flush=True)
with CheckpointFile(fname, "r", comm=COMM_WORLD) as meshfile:
    meshfile.load_mesh(name=mesh_name)
print(f"{COMM_WORLD.rank}: mesh loaded", flush=True)

# clear the mesh from rank 0
if COMM_WORLD.rank == 0:
    gc.collect()

# what do the caches look like?
print(f"{COMM_WORLD.rank} cache size: {len(CheckpointFile._tmesh_cache)}", flush=True)

# load the mesh again
# this will result in a cache hit on one rank and a miss on the other
print(f"{COMM_WORLD.rank}: loading mesh", flush=True)
with CheckpointFile(fname, "r", comm=COMM_WORLD) as meshfile:
    meshfile.load_mesh(name=mesh_name)
print(f"{COMM_WORLD.rank}: mesh loaded", flush=True)
```

This outputs:

```
0: loading mesh
1: loading mesh
0: mesh loaded
1: mesh loaded
1 cache size: 1
1: loading mesh
0 cache size: 0
0: loading mesh

*hangs*
```

**Comment by ksagiyam** [comment]
I think option 2 is fine. If we load the same mesh multiple times, we will end up having multiple instances of the same mesh, but I think we should load the mesh just once and pass around that mesh. We need to load mesh first and pass that mesh to load functions, so loading many functions will not end up making many instances of the same mesh.

**Comment by wence-** [comment]
Definitely cull the cache! It sounds like a solution to a performance problem that can be avoided by writing code "appropriately". 

(Arguably many of the caches in firedrake/pyop2 exist for this reason and could be culled)
