### ISSUE TITLE
Exterior facet integral over part and whole of facet gives surprising result

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#281]
Consider the following

```python
from firedrake import *
m = UnitSquareMesh(1, 1)

print assemble(Constant(1, cell=m.ufl_cell())*(ds(1) + ds)))
```

I expect to see 5, but I get 6.  As if the ds term is also being included in the ds(1) integral.

I note in dolfin this is sort of unsupported, in that if I have produced a marked subdomain then I can't use a bare `ds` but must always select a subdomain to integral over.  So maybe this is unsupported and expected.

**Comment by miklos1** [comment]
In ufl/algorithms/domain_analysis.py, in function `build_integral_data`:
```
            # Group integrals by subdomain id, after splitting e.g.
            #   f*dx((1,2)) + g*dx((2,3)) -> f*dx(1) + (f+g)*dx(2) + g*dx(3)
            # (note: before this call, 'everywhere' is a valid subdomain_id,
            # and after this call, 'otherwise' is a valid subdomain_id)
            single_subdomain_integrals = \
                rearrange_integrals_by_single_subdomains(ddt_integrals)
```
In `rearrange_integrals_by_single_subdomains`:
```
    # Add everywhere integrals to each single subdomain id integral list
    otherwise_integrals = []
    for ev_itg in everywhere_integrals:
        # Restrict everywhere integral to 'otherwise'
        otherwise_integrals.append(
            ev_itg.reconstruct(subdomain_id="otherwise"))

        # Restrict everywhere integral to each subdomain
        # and append to each integral list
        for subdomain_id in sorted(single_subdomain_integrals.keys()):
            single_subdomain_integrals[subdomain_id].append(
                ev_itg.reconstruct(subdomain_id=subdomain_id))

    if otherwise_integrals:
        single_subdomain_integrals["otherwise"] = otherwise_integrals
```
I guess the cause of this bug is that we treat "everywhere" and "otherwise" the same way, while "otherwise" means everywhere outside the explicitly specified subdomains.

**Comment by wence-** [comment]
Having looked at this again, this is notabug, since UFL is merging the integrals correctly. `f*ds + f*ds(1)` is interpreted as `f*ds(not 1) + f*ds(1) + f*ds(1)`.

**Comment by miklos1** [comment]
Well, the bug is that we're treating 'otherwise' as 'everywhere'.

**Comment by wence-** [comment]
Oh, I see, yes.
