### ISSUE TITLE
Trouble with vertex only mesh interpolation and adjoint

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#2811]
The following script can use either split(), .split(), or .subfunctions to split by uncommenting appropriately.
Two of these produce an error message, whilst .split() provokes the deprecation warning.

```
from firedrake import *
from firedrake_adjoint import *
import numpy as np

mesh = UnitSquareMesh(3,3)

V = FunctionSpace(mesh, "CG", 1)
W = V * V

w = Function(W)

u, v = w.subfunctions

u.assign(3.)
v.assign(3.)

coords = np.array([[0.5, 0.6],
                   [0.3, 0.4]])
VOM = VertexOnlyMesh(mesh, coords)
VVOM = FunctionSpace(VOM, "DG", 0)
vv = Function(VVOM)

#u, v = w.subfunctions
#u, v = w.split()
u, v = split(w)
vv.interpolate(u)

J = assemble(vv**2*dx)

Jhat = ReducedFunctional(J, Control(w))
Jhat.derivative()
```

**Comment by ksagiyam** [comment]
It seems that you are getting different results for `.split()` and `.subfunctions` as `.subfunctions` is not annotated.

**Comment by dham** [comment]
Um WTF. That's a severe bug.

**Comment by connorjward** [comment]
I think it's here: https://github.com/firedrakeproject/firedrake/pull/2725/files#diff-8ffe589c32bb5a40a5ddab9215a820970ff50db2e14792a93ecdb0486fb870c9R314

The decorator wasn't transferred across.
