### ISSUE TITLE
Issues installing on a MacBook Air M1 with Ventura 13.2.1.

### ISSUE THREAD

**Issue by connorjward** [firedrakeproject/firedrake#2820]
Hi! I am having issues installing on a MacBook Air M1 with Ventura 13.2.1.

I had a working version of Firedrake that I installed exactly a year ago, but I need to upgrade to access new checkpointing features.

Attached to this email you can find the logs for the installation. It fails when trying to install PETSc, but with a different error from #2793 

[configure.log](https://github.com/firedrakeproject/firedrake/files/10968695/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10968700/firedrake-install.log)

_Originally posted by @adofarsi in https://github.com/firedrakeproject/firedrake/issues/2777#issuecomment-1468047708_

**Comment by adofarsi** [comment]
Hi, I have tried setting `MACOSX_DEPLOYMENT_TARGET=11.0` and still getting the same warnings and errors. Logs below:
[configure.log](https://github.com/firedrakeproject/firedrake/files/10970595/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10970607/firedrake-install.log)

**Comment by connorjward** [comment]
Inside `configure.log` I am seeing:
```
MACOSX_DEPLOYMENT_TARGET=10.15
```
so clearly the environment variable is not being respected. How long ago did you download `firedrake-install`? A couple of weeks ago I modified the installation script to get this working. Beforehand you would have to modify the source of `firedrake-install` directly.

**Comment by adofarsi** [comment]
Hi! I downloaded it today. I have tried again with a freshly downloaded installer:
```
adofarsi@Ados-MacBook-Air ~ % MACOSX_DEPLOYMENT_TARGET=11.0              
adofarsi@Ados-MacBook-Air ~ % echo $MACOSX_DEPLOYMENT_TARGET
11.0
adofarsi@Ados-MacBook-Air ~ % curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 91918  100 91918    0     0   182k      0 --:--:-- --:--:-- --:--:--  184k
adofarsi@Ados-MacBook-Air ~ % python3 firedrake-install       
Running firedrake-install
```
But the inside `configure.log` file I am still seeing `MACOSX_DEPLOYMENT_TARGET=10.15`.

**Comment by adofarsi** [comment]
Hi! Apologies, now I can see the `MACOSX_DEVELOPMENT_TARGET=11.0` in the `configure.log`, but still showing the same warnings and then fails like before (see logs attached).
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10972992/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/10972993/configure.log)

**Comment by connorjward** [comment]
The `configure.log` includes the lines:
```
MACOSX_DEVELOPMENT_TARGET=11.0
_=/opt/homebrew/bin/python3
__CF_USER_TEXT_ENCODING=0x1F5:0:2
VIRTUAL_ENV=/Users/adofarsi/firedrake
MACOSX_DEPLOYMENT_TARGET=10.15
```
so it appears that the environment variable is still not right. Note that `MACOSX_DEPLOYMENT_TARGET` is the right variable. `MACOSX_DEVELOPMENT_TARGET` was just an error by me.

**Comment by adofarsi** [comment]
Hi and apologise for the confusion, the installation with the `MACOSX_DEPLOYMENT_TARGET=11.0` variable was actually successful! But still getting warnings, this time like `ld: warning: dylib (/opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/libgfortran.dylib) was built for newer macOS version (13.0) than being linked (11.0)`
Should I reinstall it with `MACOSX_DEPLOYMENT_TARGET=13.0` ?
[configure.log](https://github.com/firedrakeproject/firedrake/files/10983280/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/10983282/firedrake-install.log)

**Comment by connorjward** [comment]
This looks similar to https://github.com/firedrakeproject/firedrake/discussions/2735. I do notice that `brew doctor` is spewing a lot of warnings. I expect that if you do the following:
1. Resolve `brew doctor` warnings
2. Reinstall Firedrake, likely with `MACOSX_DEPLOYMENT_TARGET=13.0`

Then these warnings may go away.

**Comment by connorjward** [comment]
Has this issue been resolved?

**Comment by adofarsi** [comment]
Hi @connorjward I haven't tried MACOSX_DEPLOYMENT_TARGET=13.0 yet, but I can confirm that the installation with `MACOSX_DEPLOYMENT_TARGET=11.0` works. Thanks!

**Comment by connorjward** [comment]
Good to hear! I would stick to using `11.0` for now. If it ain’t broke…
