### ISSUE TITLE
Interpolate CellNormal of CircleManifoldMesh "ValueError: The argument dtypes do not match those for the local kernel"

### ISSUE THREAD

**Issue by lrtfm** [firedrakeproject/firedrake#2823]
The following code raises ValueError exception: The argument dtypes do not match those for the local kernel. Is the interpolation of CellNormal not supported for 1D manifold?

```python
from firedrake import *


def set_cell_orientations(mesh):
    from ufl.classes import ReferenceGrad
    V0 = FunctionSpace(mesh, 'DG', 0)
    X = SpatialCoordinate(mesh)
    flag = Function(V0)
    flag.interpolate(dot(X, as_vector((-ReferenceGrad(X)[1, 0], ReferenceGrad(X)[0, 0]))))
    cell_orientations = Function(V0)
    cell_orientations.dat.data[:] = (flag.dat.data_ro < 0)
    mesh.topology._cell_orientations = cell_orientations


mesh= CircleManifoldMesh(10)
set_cell_orientations(mesh)

degree= 1
V = VectorFunctionSpace(mesh, 'CG', degree=degree)
n = CellNormal(mesh)
n_h = Function(V, name='n_h')
n_h.interpolate(n)
```

**Comment by ksagiyam** [comment]
It looks you need:
```
    cell_orientations = Function(V0, dtype=np.int32)
```

**Comment by wence-** [comment]
Indeed. It feels like the `mesh.init_cell_orientations` code could be augmented to handle this, but I'm not sure what subtleties lie there.

**Comment by lrtfm** [comment]
Sure, I can make a PR for this.

**Comment by lrtfm** [comment]
@ksagiyam Should the `dtype` be `IntType` or just `np.int32`?

**Comment by ksagiyam** [comment]
I think it should be `np.int32` as it is hard-coded in tsfc: https://github.com/firedrakeproject/tsfc/blob/e68bd286486216bf13f7a7157b2a222565633c44/tsfc/kernel_interface/firedrake_loopy.py#L361.

**Comment by lrtfm** [comment]
The PR has been created, see https://github.com/firedrakeproject/firedrake/pull/2829.
