### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by ReubenHill** [firedrakeproject/firedrake#2846]
Please can someone do the zenodo thing for this json
```json
{"firedrake": "18c3c282831b4775ee74e7f9239c948bacf079c2", "PyOP2": "37481155878bb2deb2aa6c7a914c553d7401781e", "tsfc": "b6da9e096f284f653549edaa324098a647b2ed9f", "COFFEE": "70c1e66a4e4e39d3bf75274505a16901af110751", "ufl": "13435fbf9ba22487d534de7d24ee21a0be17e41a", "FInAT": "cd1d528dc6b3fdcadc7548e7ac0a1f467c349742", "fiat": "9fca26188a4533ff86e006a8fe61b8edbb73ed8b", "petsc": "94188b0279cbe4647d502b63c2212330e11c228f", "loopy": "3988272b385fd770a3427b539e8b27e367f9db33", "slepc": "3ef5a0699975fbf8418b3a969196fe73958e7253", "metarelease_info_file": null, "title": "Consistent Point Data Assimilation in Firedrake and Icepack: Groundwater Hydrology and Ice Shelf Demonstrations"}
```

**Comment by ksagiyam** [comment]
Is this a new version of previous one? If so, please pass `--new-version-of doi_of_prev_release`.

**Comment by ReubenHill** [comment]
No, it's a different version of Firedrake which needs to go into the same paper. But good to know!

**Comment by wence-** [comment]
That is what `--new-version-of` is for. A new "release" of firedrake for the same paper

**Comment by wence-** [comment]
Or do you mean you need to cite two different versions of firedrake in the same paper?

**Comment by ReubenHill** [comment]
No I mean that, in the paper, there are two different firedrake version used for two different experiments. They each need their own reference.

**Comment by ReubenHill** [comment]
> Or do you mean you need to cite two different versions of firedrake in the same paper?

Yes, exactly.

**Comment by wence-** [comment]
Apologies for the spam...

**Comment by ksagiyam** [comment]
I see. I understand. Will do.

**Comment by ksagiyam** [comment]
Created Zenodo meta-release.
Tag is `Firedrake_20230405.1`
DOI is 10.5281/zenodo.7801478
Zenodo URL is https://zenodo.org/record/7801478
BibTeX

```bibtex
@misc{zenodo/Firedrake-20230405.1,
 key = {zenodo/Firedrake-20230405.1},
 title = {{Software used in `Consistent Point Data Assimilation in Firedrake and Icepack: Groundwater Hydrology and Ice Shelf Demonstrations'}},
 year = {2023},
 month = {apr},
 doi = {10.5281/zenodo.7801478},
 url = {https://doi.org/10.5281/zenodo.7801478},
}

```

**Comment by ReubenHill** [comment]
Thanks Koki!
