### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by gninr** [firedrakeproject/firedrake#2861]
Can someone please create a Zenodo release for the following? Thanks!

[firedrake.txt](https://github.com/firedrakeproject/firedrake/files/11151039/firedrake.txt)

**Comment by ksagiyam** [comment]
Thanks!

Created Zenodo meta-release.
Tag is `Firedrake_20230405.0`
DOI is 10.5281/zenodo.7800089
Zenodo URL is https://zenodo.org/record/7800089
BibTeX

```bibtex
@misc{zenodo/Firedrake-20230405.0,
 key   = {zenodo/Firedrake-20230405.0},
 title = {{Software used in `Sensitivity-guided shape reconstruction'}},
 year  = {2023},
 month = {apr},
 doi   = {10.5281/zenodo.7800089},
 url   = {https://doi.org/10.5281/zenodo.7800089},
}

```
