### ISSUE TITLE
INSTALL: Error installing PETSc on M1 mac. 

### ISSUE THREAD

**Issue by megr090** [firedrakeproject/firedrake#2869]
Hello,

I receive an error when trying to install PETSc on my M1 mac (when trying to install Firedrake for the model IcePack "python firedrake-install --install icepack"). I will attach the log files below, and I'm including the error message below as well. Any advice would be very appreciated! Thank you so much!

> Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "/Users/meghanaranganathan/Documents/GeorgiaTech/Research/IceDamage/firedrake-install", line 1860, in <module>
    install("petsc/")
  File "/Users/meghanaranganathan/Documents/GeorgiaTech/Research/IceDamage/firedrake-install", line 1022, in install
    build_and_install_petsc()
  File "/Users/meghanaranganathan/Documents/GeorgiaTech/Research/IceDamage/firedrake-install", line 1161, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "/Users/meghanaranganathan/Documents/GeorgiaTech/Research/IceDamage/firedrake-install", line 655, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/meghanaranganathan/Documents/GeorgiaTech/Research/IceDamage/firedrake/bin/python', './configure', 'PETSC_DIR=/Users/meghanaranganathan/Documents/GeorgiaTech/Research/IceDamage/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-chaco', '--with-zlib', '--with-debugging=0', '--download-hwloc', '--download-metis', '--download-suitesparse', '--download-eigen=/Users/meghanaranganathan/Documents/GeorgiaTech/Research/IceDamage/firedrake/src/eigen-3.3.3.tgz ', '--LDFLAGS=-Wl,-rpath,/usr/local/opt/openblas/lib -L/usr/local/opt/openblas/lib', '--download-pnetcdf', '--download-mumps', '--CFLAGS=-I/usr/local/opt/openblas/include -Wno-implicit-function-declaration', '--download-mpich', '--download-bison', '--download-netcdf', '--with-x=0', '--download-ptscotch', '--with-fortran-bindings=0', '--with-shared-libraries=1', '--download-ml', '--download-hdf5', '--download-superlu_dist', '--download-scalapack', '--with-64-bit-blas-indices=0', '--with-blaslapack-dir=/usr/local/opt/openblas', '--with-64-bit-indices=0', '--download-hypre', '--download-pastix', '--download-hwloc-configure-arguments=--disable-opencl', '--download-mpich-configure-arguments=--disable-opencl', '--with-c2html=0']' returned non-zero exit status 1.

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/11202817/firedrake-install.log)

[configure.log](https://github.com/firedrakeproject/firedrake/files/11202821/configure.log)

**Comment by megr090** [comment]
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/11202802/firedrake-install.log)

**Comment by connorjward** [comment]
Can you try running with `-—with-blas=download`? Your installation seems to be picking up on a brew-installed BLAS which has 64-bit indices which ML doesn’t like. Alternatively passing `-—minimal-petsc` may fix things as then ML won’t be installed.

**Comment by megr090** [comment]
> Can you try running with `-—with-blas=download`? Your installation seems to be picking up on a brew-installed BLAS which has 64-bit indices which ML doesn’t like. Alternatively passing `-—minimal-petsc` may fix things as then ML won’t be installed.

When I try to run with either --with-blas=download or --minimal-petsc, I get an error saying that those are unrecognized arguments:

> Running firedrake-install --install icepack -—with-blas=download
usage: firedrake-install [-h] [--slepc] [--opencascade] [--tinyasm] [--disable-ssh] [--no-package-manager]
                         [--minimal-petsc | --with-parmetis] [--honour-petsc-dir] [--petsc-int-type {int32,int64}] [--honour-pythonpath]
                         [--rebuild-script] [--doi DOI] [--package-branch PACKAGE BRANCH] [--verbose] [--mpicc MPICC] [--mpicxx MPICXX]
                         [--mpif90 MPIF90] [--mpiexec MPIEXEC] [--show-petsc-configure-options] [--show-dependencies]
                         [--venv-name VENV_NAME] [--install PACKAGES] [--pip-install PIP_PACKAGES] [--install-help]
                         [--cache-dir CACHE_DIR] [--complex] [--documentation-dependencies] [--remove-build-files]
                         [--with-blas WITH_BLAS]
firedrake-install: error: unrecognized arguments: -—with-blas=download

**Comment by connorjward** [comment]
My prior suggestion was made using my phone and it looks like the options I specified contain a different type of dash by accident so copying and pasting them won't work. You want `--with-blas=download` instead of `-—with-blas=download` and `--minimal-petsc` instead of `-—minimal-petsc`.

**Comment by wence-** [comment]
> my phone and it looks like the options I specified contain a different type of dash

Assuming iphone, `Settings -> Keyboards -> turn off "Smart Punctuation"`

**Comment by megr090** [comment]
That worked great, thank you so much!

**Comment by connorjward** [comment]
Can this issue be closed then?
