### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by ScottMacLachlan** [firedrakeproject/firedrake#2926]
Could someone please do the zenodo magic for the attached?  Many thanks!
[firedrake.txt](https://github.com/firedrakeproject/firedrake/files/11441364/firedrake.txt)

**Comment by ksagiyam** [comment]
Created Zenodo meta-release.
Tag is `Firedrake_20230510.0`
DOI is 10.5281/zenodo.7920255
Zenodo URL is https://zenodo.org/record/7920255
BibTeX

```bibtex
@misc{zenodo/Firedrake-20230510.0,
 key   = {zenodo/Firedrake-20230510.0},
 title = {{Software used in `Multigrid preconditioning of singularly perturbed convection-diffusion equations'}},
 year  = {2023},
 month = {may},
 doi   = {10.5281/zenodo.7920255},
 url   = {https://doi.org/10.5281/zenodo.7920255},
}

```
Thanks!

**Comment by ScottMacLachlan** [comment]
Many thanks!
