### ISSUE TITLE
BUG: Pytorch not installed correctly

### ISSUE THREAD

**Issue by JDBetteridge** [firedrakeproject/firedrake#2942]
**Describe the bug**
Installing pytorch with `firedrake-install`/`firedrake-update` doesn't install all dependencies.

**Steps to Reproduce**
1. `firedrake-update --torch`

**Expected behavior**
`python -c "import torch"` should run just fine.

**Error message**
```
$ python -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scratch/jbetteri/firedrake_py311_opt/lib/python3.11/site-packages/torch/__init__.py", line 1122, in <module>
    from .serialization import save, load
  File "/scratch/jbetteri/firedrake_py311_opt/lib/python3.11/site-packages/torch/serialization.py", line 17, in <module>
    from typing_extensions import TypeAlias  # Python 3.10+
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'typing_extensions'
```

**Environment:**
 - OS: (Arch) Linux
 - Python version: 3.11.2
 - Output of `firedrake-status`
 ```
$ firedrake-status
Firedrake Configuration:
    package_manager: False
    minimal_petsc: False
    mpicc: /opt/mpich/bin/mpicc
    mpicxx: /opt/mpich/bin/mpicxx
    mpif90: /opt/mpich/bin/mpif90
    mpiexec: /opt/mpich/bin/mpiexec
    disable_ssh: False
    honour_petsc_dir: True
    with_parmetis: False
    slepc: False
    packages: []
    honour_pythonpath: False
    opencascade: False
    tinyasm: False
    petsc_int_type: int32
    cache_dir: /scratch/jbetteri/firedrake_py311_opt/.cache
    complex: False
    remove_build_files: False
    with_blas: None
    torch: cpu
    netgen: False
Additions:
    None
Environment:
    PYTHONPATH: None
    PETSC_ARCH: full-opt
    PETSC_DIR: /opt/petsc/firedrake
Unable to retrieve git information from .pytest_cache.
Status of components:
---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|COFFEE              |master                        |70c1e66   |False     |
|FInAT               |master                        |47f6c37   |False     |
|PyOP2               |JDBetteridge/global_literal   |c1e5a460  |True      |
|fiat                |master                        |8c66270   |False     |
|firedrake           |JDBetteridge/constant_rethink |41467edcc |True      |
|h5py                |firedrake                     |6cc4c912  |False     |
|libspatialindex     |master                        |4768bf3   |True      |
|libsupermesh        |master                        |69012e5   |False     |
|loopy               |main                          |cd388f74  |False     |
|pyadjoint           |connorjward/constants-away    |c0470bc   |False     |
|pytest-mpi          |main                          |a478bc8   |False     |
|tsfc                |JDBetteridge/constant_update  |c97e8a7   |False     |
|ufl                 |master                        |772485d7  |False     |
---------------------------------------------------------------------------
```
^^My branches are rebased on master/main

**Additional Info**
N/A

**Comment by JDBetteridge** [comment]
Okay, one argument is that `pytorch` isn't supported by Python 3.11 and we should prevent users installing in this situation. (Although I have installed it and it is sufficient to get the tests to run, after fixing the dependency, so I'd argue not a great solution)

However, the error message suggests that the dependency is also required for Python 3.10 also:
```
    from typing_extensions import TypeAlias  # Python 3.10+
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I really hope `pytorch` supports 3.10 by now!

**Comment by nbouziani** [comment]
Since I can't reproduce this locally, could you try to pip install torch and see if you still get that error? That is, via:

`pip3 install torch --index-url https://download.pytorch.org/whl/cpu`

We are installing PyTorch in the exact same way users are supposed to do it (pip install with backend-specific wheels), so I would assume it also fails in that case. If yes, then that's a bug on their side and I think we could just add `typing_extensions` to our dependency, see https://github.com/pytorch/pytorch/issues/48454.

**Comment by JDBetteridge** [comment]
In a fresh Python 3.11 venv, after running the command you gave me, I can run `python -c "import torch"` without issue. It appears to be an issue in the Firedrake install script.

It might be worth printing out exactly the command that is being used, for me (from my `firedrake-update.log`) I see:
```
/scratch/jbetteri/firedrake_py311_opt/bin/python -m pip install --no-build-isolation --no-binary mpi4py,randomgen,islpy,numpy --no-deps -vvv torch --extra-index-url https://download.pytorch.org/whl/cpu
```

Which is passing `--no-deps` and therefore not installing the dependencies of `pytorch`.
