### ISSUE TITLE
successful installation but code is not working

### ISSUE THREAD

**Issue by ruizbaier** [firedrakeproject/firedrake#2944]
I've installed Firedrake in Ubuntu 22.04 with Python 3.10.6. The installation runs smoothly with no issues. 

I activate the venv and then try to run any python script, for example the mixed_poisson demo. The issue is 

`Traceback (most recent call last):
  File "/home/ruizbaier/Firedrake/mixed_poisson.py", line 22, in <module>
    from firedrake import *
  File "/home/ruizbaier/code/firedrake/src/firedrake/firedrake/__init__.py", line 69, in <module>
    from pyop2 import op2                        # noqa: F401
  File "/home/ruizbaier/code/firedrake/src/PyOP2/pyop2/__init__.py", line 4, in <module>
    from pyop2.op2 import *  # noqa
  File "/home/ruizbaier/code/firedrake/src/PyOP2/pyop2/op2.py", line 40, in <module>
    from pyop2.mpi import MPI, COMM_WORLD, collective
  File "/home/ruizbaier/code/firedrake/src/PyOP2/pyop2/mpi.py", line 38, in <module>
    from mpi4py import MPI  # noqa
ImportError: /home/ruizbaier/code/firedrake/lib/python3.10/site-packages/mpi4py/MPI.cpython-310-x86_64-linux-gnu.so: undefined symbol: MPI_UNWEIGHTED`

I've also run `firedrake-update` and the update is marked as successful. However when trying to run any script I get the same error message. I've seen older issues where it is suggested to `install libcurl4-openssl-dev` and `libxml2-dev`. I've done that and have done a fresh reinstallation of Firedrake, but the result is the same. 

`firedrake-status` gives me 

> Firedrake Configuration:
    package_manager: True
    minimal_petsc: False
    mpicc: None
    mpicxx: None
    mpif90: None
    mpiexec: None
    disable_ssh: True
    honour_petsc_dir: False
    with_parmetis: False
    slepc: False
    packages: []
    honour_pythonpath: False
    opencascade: False
    tinyasm: False
    torch: False
    petsc_int_type: int32
    cache_dir: /home/ruizbaier/code/firedrake/.cache
    complex: False
    remove_build_files: False
    with_blas: None
    netgen: False
Additions:
    None
Environment:
    PYTHONPATH: None
    PETSC_ARCH: None
    PETSC_DIR: None

> Status of components:
>---------------------------------------------------------------------------
>Package             |Branch                        |Revision  |Modified  |
>---------------------------------------------------------------------------
>FInAT               |master                        |47f6c37   |False     |
>PyOP2               |master                        |edae2884  |False     |
>fiat                |master                        |8c66270   |False     |
>firedrake           |master                        |397ddfa0a |False     |
>h5py                |firedrake                     |6cc4c912  |False     |
>libspatialindex     |master                        |4768bf3   |True      |
>libsupermesh        |master                        |69012e5   |False     |
>loopy               |main                          |cd388f74  |False     |
>petsc               |firedrake                     |9364cb008b|False     |
>pyadjoint           |master                        |9e1725a   |False     |
>pytest-mpi          |main                          |a478bc8   |False     |
>tsfc                |master                        |ef39f72   |False     |
>ufl                 |master                        |772485d7  |False     |
>---------------------------------------------------------------------------

Any help would be very much appreciated. Thanks

**Comment by ruizbaier** [comment]
And here is the install log: [firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/11561248/firedrake-install.log)

**Comment by connorjward** [comment]
This looks to be the same as the issue described [here](https://github.com/firedrakeproject/firedrake/discussions/2941). In particular please use [this command](https://github.com/firedrakeproject/firedrake/discussions/2941#discussioncomment-5968696).

We are aware of wider issues with Ubuntu linking to MPI and PETSc libraries and hopefully a fix will be rolled out relatively soon.

**Comment by ruizbaier** [comment]
Oh sorry, now it seems that there is still an issue. I can run just an import firedrake command, but when I try to run an actual finite element code I run into troubles with petsc and cython maybe? 

`File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/ruizbaier/code/firedrake/src/firedrake/firedrake/utility_meshes.py", line 838, in UnitSquareMesh
    return SquareMesh(
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/ruizbaier/code/firedrake/src/firedrake/firedrake/utility_meshes.py", line 785, in SquareMesh
    return RectangleMesh(
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/ruizbaier/code/firedrake/src/firedrake/firedrake/utility_meshes.py", line 609, in RectangleMesh
    return TensorRectangleMesh(
  File "/home/ruizbaier/code/firedrake/src/firedrake/firedrake/utility_meshes.py", line 734, in TensorRectangleMesh
    m = mesh.Mesh(
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/ruizbaier/code/firedrake/src/firedrake/firedrake/mesh.py", line 2451, in Mesh
    topology = MeshTopology(plex, name=plex.getName(), reorder=reorder,
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/ruizbaier/code/firedrake/src/firedrake/firedrake/mesh.py", line 936, in __init__
    dmcommon.validate_mesh(plex)
  File "firedrake/cython/dmcommon.pyx", line 1964, in firedrake.cython.dmcommon.validate_mesh
ValueError: Provided mesh has some entities not reachable by traversing cells (maybe rogue vertices?)`

**Comment by connorjward** [comment]
I think that this is a related linking issue. The workaround for this one seems to be uninstalling `libpetsc-real3.18-dev` (using `apt` I believe) and then rebuilding some files in `$VIRTUALENV/src/firedrake` and `$VIRTUALENV/src/PyOP2`. You need to run the command `python setup.py build_ext --inplace` in both directories.

Again, sorry about the faff.

**Comment by ruizbaier** [comment]
I wasn't able to install it that way. If a fix for Ubuntu 22 is going to be available soon I can simply wait... thanks!

**Comment by ruizbaier** [comment]
I don't know if it is relevant, but the output of `ldd $VIRTUAL_ENV/lib/python*/site-packages/mpi4py/MPI*.so` is 
`	linux-vdso.so.1 (0x00007ffdcbaca000)
	libmpi.so.12 => /home/ruizbaier/code/firedrake/src/petsc/default/lib/libmpi.so.12 (0x00007f7886baa000)
	libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007f7886982000)
	libhwloc.so.15 => /home/ruizbaier/code/firedrake/src/petsc/default/lib/libhwloc.so.15 (0x00007f7886927000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f78871dc000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7886821000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f78867f7000)
	libpciaccess.so.0 => /lib/x86_64-linux-gnu/libpciaccess.so.0 (0x00007f78867ea000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f78867ce000)
`

**Comment by connorjward** [comment]
I'm currently trying to reproduce this issue. To get yours working could you please try running
```
export LDFLAGS="-Wl,-rpath,$VIRTUAL_ENV/src/petsc/default/lib -L$VIRTUAL_ENV/src/petsc/default/lib"
cd $VIRTUAL_ENV/src/firedrake
make
```

**Comment by connorjward** [comment]
I have attempted a fix. Could you try running this modified `firedrake-install`: https://raw.githubusercontent.com/firedrakeproject/firedrake/48fc14aaa0c51d8aa25827764cc4ecf9d6b7879d/scripts/firedrake-install

**Comment by ruizbaier** [comment]
this works, thanks so much! Note that I also had to `pip3 uninstall -y mpi4py` and then use your previous suggestion 
`env LDFLAGS="-Wl,-rpath,$VIRTUAL_ENV/src/petsc/default/lib -L$VIRTUAL_ENV/src/petsc/default/lib" MPICC=$VIRTUAL_ENV/src/petsc/default/bin/mpicc MPICXX=$VIRTUAL_ENV/src/petsc/default/bin/mpicxx MPIF90=$VIRTUAL_ENV/src/petsc/default/bin/mpif90 pip install --no-cache-dir --no-binary mpi4py mpi4py`

**Comment by connorjward** [comment]
Thanks for letting us know about mpi4py. Clearly my fix isn't quite sufficient. I'm glad you got things working.

**Comment by ruizbaier** [comment]
Awesome, thanks Connor!
