### ISSUE TITLE
IDEA: Proxy block for adjoint

### ISSUE THREAD

**Issue by connorjward** [firedrakeproject/firedrake#2979]
One of the key performance problems with the adjoint is the cost of setting up fresh solvers as the tape is traversed. Assuming that the adjoint problem involves a time loop, many of these solvers are repeating work done by other blocks ([example](https://github.com/dolfin-adjoint/pyadjoint/blob/master/dolfin_adjoint_common/blocks/solving.py#L144)). I think that this problem stems from the fact that we unroll time loops on the tape and information is lost about the equivalence of solve blocks.

My suggestion is as follows:
1. Add a `ProxyBlock` class to pyadjoint that points to some original block.
2. Add a new adjoint kwarg to decorated functions so the functions can know if they are repeated operations or not, and hence whether or not to store themselves as proxy blocks. Something like:
    ```py
    while t < T:
        solve(..., ad_block_id="mysolve")
    ```

**Comment by colinjcotter** [comment]
I like this idea of leaving it up to the coder to decide

**Comment by connorjward** [comment]
A related pipe dream of mine is for us to employ enough smart caching that we could get near to equivalent performance calling the `solve` function compared with creating and reusing solvers.

This would all be interesting to discuss in this week's meeting.

**Comment by connorjward** [comment]
The conclusion from this week's meeting is that having a proxy block like this is practically equivalent to creating and reusing a solver object as reusing the solver naturally connects solve blocks.

I still want to find ways to optimise solver instantiation such that these strategies aren't required, but this specific `ProxyBlock` idea isn't the answer.
