### ISSUE TITLE
BUG: Fresh install on MacBook M1 returns error when importing firedrake

### ISSUE THREAD

**Issue by adofarsi** [firedrakeproject/firedrake#3028]
**Describe the bug**
Fresh install on MacBook M1 returns error when importing firedrake

**Steps to Reproduce**
```
curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
python3 firedrake-install
source firedrake/bin/activate
python3
>>> import firedrake
```

**Expected behavior**
Importing firedrake with no errors

**Error message**
```
[-1]PETSC ERROR: --------------------- Error Message --------------------------------------------------------------
[-1]PETSC ERROR: MPI library at runtime is not compatible with MPI used at compile time
[-1]PETSC ERROR: Application was linked against both OpenMPI and MPICH based MPI libraries and will not run correctly
zsh: segmentation fault  python3
```

**Environment:**
 - MacOS
 - Python version: 3.9.10

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/12071694/firedrake-install.log)

**Comment by adofarsi** [comment]
Hi @JDBetteridge thanks for the prompt reply.

You can find the output of each query below:

```
adofarsi@Ados-MacBook-Air ~ % source firedrake/bin/activate
(firedrake) adofarsi@Ados-MacBook-Air ~ % otool -L $VIRTUAL_ENV/lib/python*/site-packages/mpi4py/MPI.cpython*.so
/Users/adofarsi/firedrake/lib/python3.9/site-packages/mpi4py/MPI.cpython-39-darwin.so:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
	/opt/homebrew/opt/open-mpi/lib/libmpi.40.dylib (compatibility version 71.0.0, current version 71.5.0)
	/Users/adofarsi/firedrake/src/petsc/default/lib/libpmpi.12.dylib (compatibility version 16.0.0, current version 16.0.0)
```
```
(firedrake) adofarsi@Ados-MacBook-Air ~ % otool -L $VIRTUAL_ENV/lib/python*/site-packages/petsc4py/ib/default/PETSc.cpython*.so
zsh: no matches found: /Users/adofarsi/firedrake/lib/python*/site-packages/petsc4py/ib/default/PETSc.cpython*.so
```
```
(firedrake) adofarsi@Ados-MacBook-Air ~ % otool -L $VIRTUAL_ENV/src/petsc/default/lib/libpetsc.so                              
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic: can't open file: /Users/adofarsi/firedrake/src/petsc/default/lib/libpetsc.so (No such file or directory)
```

**Comment by JDBetteridge** [comment]
Ah sorry, typo in the second line `ib` should be `lib`. Not sure why the third command failed, just check that PETSc is installed properly. (should be in `src/petsc/default`, but maybe different file layout on Mac)

But you can already see that `mpi4py` is linked against the wrong MPI: `/opt/homebrew/opt/open-mpi/lib/libmpi.40.dylib`

You can reinstall mpi4py by running:
```bash
pip uninstall -y mpi4py
env LDFLAGS="-Wl,-rpath,/Users/adofarsi/firedrake/src/petsc/default/lib -L/Users/adofarsi/firedrake/src/petsc/default/lib" \
    MPICC=/Users/adofarsi/firedrake/src/petsc/default/bin/mpicc \
    MPICXX=/Users/adofarsi/firedrake/src/petsc/default/bin/mpicxx \
    MPIF90=/Users/adofarsi/firedrake/src/petsc/default/bin/mpif90 \
    pip install --no-build-isolation --no-cache-dir --no-binary mpi4py mpi4py
```

You can do a similar trick with petsc4py:
```bash
pip uninstall -y petsc4py
env PETSC_DIR=/Users/adofarsi/firedrake/src/petsc \
    PETSC_ARCH=default \
    LDFLAGS="-Wl,-rpath,/Users/adofarsi/firedrake/src/petsc/default/lib -L/Users/adofarsi/firedrake/src/petsc/default/lib" \
    MPICC=/Users/adofarsi/firedrake/src/petsc/default/bin/mpicc \
    MPICXX=/Users/adofarsi/firedrake/src/petsc/default/bin/mpicxx \
    MPIF90=/Users/adofarsi/firedrake/src/petsc/default/bin/mpif90 \
    pip install --no-build-isolation --no-cache-dir /Users/adofarsi/firedrake/src/petsc/src/binding/petsc4py
```

Please double check all of those paths they are largely copy-pasted from your install log file and manually edited.
Let us know if that fixes things in your venv.

**Comment by adofarsi** [comment]
Hi @JDBetteridge. Thank you a lot for your help. I have solved this problem by reinstalling firedrake using /opt/homebrew/bin/python3 instead of using /Users/adofarsi/.pyenv/shims/python3 (also installed with Homebrew). The problem with this solution is that when Homebrew updates and installs a newer version of python3 breaks the python3 of the firedrake virtual environment (firedrake/bin/python3) and I have to reinstall firedrake every time this happens.

**Comment by JDBetteridge** [comment]
Glad to hear your issue is fixed. I believe that this is currently what we recommend for Mac Users (I am not a Mac User), if you are following the Python update cycle that means reinstalling once a year as things will only break on a major release (AFAIK), so I don't think this is too bad.

If you really don't want to rebuild Firedrake, you can try building your own Python at a fixed release tag, which is what I do on my workstation.

Mac users may also weigh in with their solutions if they have better suggestions.
