### ISSUE TITLE
BUG: jupyter-nbextension not found

### ISSUE THREAD

**Issue by Ig-dolci** [firedrakeproject/firedrake#3042]
**Describe the bug**
`jupyter-nbextension` not found.

**Steps to Reproduce**
docker build -t fire_jupyter:tag -f Dockerfile.jupyter .

**Expected behavior**
Build image

**Error message**
Jupyter command `jupyter-nbextension` not found.

**Environment:**
 - OS: MacOS
 - Python version: 3.10

**Additional Info**
This error is apparently related to the latest notebook version.

**Comment by JDBetteridge** [comment]
Fixed in https://github.com/firedrakeproject/firedrake/pull/3086
