### ISSUE TITLE
BUG: assigning to a vector function space of R space produces error

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#3046]
**Describe the bug**
Making a VectorFunctionSpace over R and assigning from one Function to another causes error.

**Steps to Reproduce**

from firedrake import *
mesh = UnitIntervalMesh(20)

V = VectorFunctionSpace(mesh, "R", dim=4)

a = Function(V).assign(1.0)
b = Function(V).assign(2.0)

a.assign(b)

**Error message**

TypeError: Indexed.__float__ returned non-float (type NotImplementedType)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cjc1/repositories/sketchpad/nudging_tests/test_R.py", line 9, in <module>
    a.assign(b)
  File "petsc4py/PETSc/Log.pyx", line 115, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 116, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/cjc1/firedrake/src/firedrake/firedrake/adjoint/function.py", line 135, in wrapper
    ret = assign(self, other, *args, **kwargs)
  File "/home/cjc1/firedrake/src/firedrake/firedrake/function.py", line 419, in assign
    self.dat.data_wo[...] = expr
ValueError: setting an array element with a sequence.

**Environment:**
 - OS: MacOS
 - Python version: 3.10.6
 - Output of `firedrake-status`

Firedrake Configuration:
    package_manager: True
    minimal_petsc: False
    mpicc: None
    mpicxx: None
    mpif90: None
    mpiexec: None
    disable_ssh: False
    honour_petsc_dir: False
    with_parmetis: False
    slepc: False
    packages: []
    honour_pythonpath: False
    opencascade: False
    tinyasm: False
    torch: False
    petsc_int_type: int32
    cache_dir: /home/cjc1/firedrake/.cache
    complex: False
    remove_build_files: False
    with_blas: None
    netgen: False
Additions:
    None
Environment:
    PYTHONPATH: None
    PETSC_ARCH: None
    PETSC_DIR: None
Status of components:
---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|FInAT               |master                        |47f6c37   |False     |
|PyOP2               |master                        |d230953b  |False     |
|fiat                |master                        |8c66270   |False     |
|firedrake           |cospace                       |1e380c45a |False     |
|h5py                |firedrake                     |6cc4c912  |False     |
|libspatialindex     |master                        |4768bf3   |True      |
|libsupermesh        |master                        |69012e5   |False     |
|loopy               |main                          |8158afdb  |False     |
|petsc               |firedrake                     |9364cb008b|False     |
|pyadjoint           |master                        |0378c81   |False     |
|pytest-mpi          |main                          |a478bc8   |False     |
|tsfc                |master                        |6f72c9c   |False     |
|ufl                 |master                        |3c62318c  |False     |
---------------------------------------------------------------------------

**Comment by connorjward** [comment]
This is because we do not currently support vector function spaces in the real space ([old issue](https://github.com/firedrakeproject/firedrake/issues/1456)). Getting that to work would require non-trivial changes to PyOP2 and TSFC since the [dense row/column in assembled matrices](https://www.firedrakeproject.org/r-space.html#representing-matrices-involving-r) would need to be changed to having `dim`-many dense rows/columns.

**Comment by pbrubeck** [comment]
Right now `Function(VectorFunctionSpace(mesh, "R", 0, dim=2)).dat.data` has lenght 1 and does not raise an error. But `Constant([1, 1], domain=mesh).dat.data` gives the expected result (while raising a warning)

**Comment by pbrubeck** [comment]
The right fix could involve raising the error when creating a Test/TrialFunction on an R VectorSpace, and fixing the dat shape.

**Comment by connorjward** [comment]
I think it's possible that this could be quite simple for the non-argument case as you say.
