### ISSUE TITLE
INSTALL: 

### ISSUE THREAD

**Issue by adominious** [firedrakeproject/firedrake#3058]
**Describe the error**
A short description of what the installation error is.
ERROR: Could not build wheels for islpy, which is required to install pyproject.toml-based projects

**Steps to Reproduce**
python3 firedrake-install --install gusto

ie: The exact command used for installation/update  '...'
python3 firedrake-install --install gusto

**Expected behavior**
Describe what you expected to happen.
Firedrake to install along with gusto

**Error message**
Add error message with full backtrace.
Please add these as text using three backticks (`) for highlighting.
Please do not add screenshots.
```
Traceback (most recent call last):
  File "/home/adamh/firedrake-install", line 1917, in <module>
    install("loopy/")
  File "/home/adamh/firedrake-install", line 1058, in install
    run_pip_install(["-e", package])
  File "/home/adamh/firedrake-install", line 979, in run_pip_install
    check_call(pipinstall + pipargs)
  File "/home/adamh/firedrake-install", line 666, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/adamh/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy', '-vvv', '-e', 'loopy/']' returned non-zero exit status 1.
```

Please also include either `firedrake-install.log` which is found in
the directory `firedrake-install` was run or `firedrake-update.log`
found in the virtualenv directory.

Additionally please include the PETSc configure log located 
[configure.log](https://github.com/firedrakeproject/firedrake/files/12302921/configure.log)
in `$VIRTUAL_ENV/src/petsc/configure.log`.

**Environment:**
 - OS: [eg: Linux, MacOS, WSL (Windows Subsystem for Linux)] add this as an issue label too! Please be specific: state the Linux distribution or MacOS version you are attempting to install on.

Linux Ubuntu 22.04.2

 - Python version: 3.10
 - Any relevant environment variables or modifications [eg: PETSC_CONFIGURE_OPTIONS=...] Trying to install gusto alongside this

**Additional context**

**Comment by connorjward** [comment]
Please share the `firedrake-install.log` file.

**Comment by connorjward** [comment]
Is this still an issue?

**Comment by JDBetteridge** [comment]
@adominious is this issue superceded by #3185?

**Comment by JDBetteridge** [comment]
https://github.com/firedrakeproject/firedrake/wiki/Closing-Installation-Issues
