### ISSUE TITLE
Memory growth with repeated minimize calls 

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#3069]
**Describe the bug**
Repeated calls to minimize() leads to memory use growth.

**Steps to Reproduce**
```
from firedrake import *
from firedrake_adjoint import *
pyadjoint.tape.pause_annotation()

mesh = UnitSquareMesh(50, 50)
V = FunctionSpace(mesh, "CG", 1)

u = Function(V)
f = Function(V)

x, y = SpatialCoordinate(mesh)

f.interpolate(cos(2*pi*x)*sin(2*pi*y))
v = TestFunction(V)
q = Function(V)
L = inner(grad(v), grad(u - q))*dx - f*v*dx

prob = NonlinearVariationalProblem(L, u)
solver = NonlinearVariationalSolver(prob, solver_parameters=
                                    {'ksp_type':'preonly',
                                     'pc_type':'lu'})

pyadjoint.tape.continue_annotation()
solver.solve()
J = assemble(u*u*dx)
Jhat = ReducedFunctional(J, [Control(q), Control(f)], derivative_components=[0])
pyadjoint.tape.pause_annotation()

for i in range(1000):
    f.assign(f*1.1)
    Jhat([q, f])
    Xopt= minimize(Jhat)
```
run the above code as a script.

**Expected behavior**

I expected memory use to be roughly stationary with iterations.

**Environment:**
 - OS: Linux
 - Python version: [eg: 3.9.7] Python 3.9.17
 - Output of `firedrake-status`

---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|FInAT               |master                        |47f6c37   |False     |
|PyOP2               |master                        |d230953b  |False     |
|fiat                |master                        |8c66270   |False     |
|firedrake           |master                        |0ec02b2d8 |False     |
|h5py                |firedrake                     |6cc4c912  |False     |
|libspatialindex     |master                        |4768bf3   |True      |
|libsupermesh        |master                        |69012e5   |False     |
|loopy               |main                          |8158afdb  |False     |
|petsc               |firedrake                     |9364cb008b|False     |
|pyadjoint           |master                        |0378c81   |False     |
|pytest-mpi          |main                          |a478bc8   |False     |
|tsfc                |master                        |6f72c9c   |False     |
|ufl                 |master                        |3c62318c  |False     |
---------------------------------------------------------------------------

**Comment by connorjward** [comment]
I believe that this is a known issue. We only clean up the memory when `solve` is called.

I think that your issue will be resolved if you add the line `PETSc.garbage_cleanup(mesh._comm)` inside your loop.

**Comment by colinjcotter** [comment]
Does solve not get called when playing the tape then? Or does it directly build ksps?

On 18 Aug 2023, at 17:55, Connor Ward ***@***.***> wrote:

﻿

I believe that this is a known issue. We only clean up the memory when solve is called.

I think that your issue will be resolved if you add the line PETSc.garbage_cleanup(mesh._comm) inside your loop.

**Comment by connorjward** [comment]
When we evaluate the adjoint we use `LinearSolver`s instead of `LinearVariationalSolver`s (since we can't have RHSs that are `Cofunction`s). I think it makes sense that we're not hitting the code path where we call `garbage_cleanup`.

**Comment by colinjcotter** [comment]
Thanks for explaining!

On 18 Aug 2023, at 18:31, Connor Ward ***@***.***> wrote:

﻿

When we evaluate the adjoint we use LinearSolvers instead of LinearVariationalSolvers (since we can't have RHSs that are Cofunctions). I think it makes sense that we're not hitting the code path where we call garbage_cleanup.

**Comment by maneeshkrsingh** [comment]
When executing this script, memory usage initiates at approximately 200MB and gradually escalates to 2GB within the first 200 steps. Upon reaching the 1000th step, the total memory consumption peaks at around 7GB.

**Comment by colinjcotter** [comment]
Yes, I also observe that `garbage_cleanup` does not help.

**Comment by colinjcotter** [comment]
[mprofile_20230821135302.dat.gz](https://github.com/firedrakeproject/firedrake/files/12396197/mprofile_20230821135302.dat.gz)

**Comment by colinjcotter** [comment]
I think that it is specific to minimize(), because if I just call Jhat.derivative() then the memory usage asymptotes to a constant value.

**Comment by colinjcotter** [comment]
... actually it is still creeping upwards, just waiting for a longer run

**Comment by connorjward** [comment]
I think I've observed that `Jhat(...)` is also increasing memory usage. I'll continue to investigate.

**Comment by dham** [comment]
Can we get an approximate quantification of the leakage in units of Functions per timestep? I think that might help us understand what's going on (e.g. are we leaking functions or solvers).

**Comment by dham** [comment]
You can approximate a Function as number of DoFs x 8 bytes.

**Comment by dham** [comment]
Also, can you try a different optimiser?

**Comment by colinjcotter** [comment]
@dham I'm using mprof which just gives a time series from snapshots. I suppose I can just divide the final number by the number of for loop iterations.

@connorjward I am getting what seems to be an increase when using Jhat(). What made you think it wasn't happening?

**Comment by dham** [comment]
I'm a bit confused because you seem to have said something a bit different an hour ago. In any event, if it's in our code that's easier to deal with. So what we need to know is what we're leaking in units of Functions per step.

**Comment by connorjward** [comment]
> @dham I'm using mprof which just gives a time series from snapshots. I suppose I can just divide the final number by the number of for loop iterations.
> 
> @connorjward I am getting what seems to be an increase when using Jhat(). What made you think it wasn't happening?

Just double checked. The memory usage stays constant if you have the lines
```py
gc.collect()
PETSc.garbage_cleanup(mesh._comm)
```
inside the loop. Otherwise it does increase over time. This is not going to be the solution here since we're still leaking with these calls when we use `minimize`.

**Comment by colinjcotter** [comment]
Thanks for nailing it down a bit more, @connorjward !

**Comment by colinjcotter** [comment]
@dham the second is not sufficient.

Summary: if the loop just calls jhat and/or jhat.derivative(), gc.collect() and garbage_cleanup(...) are necessary and sufficient.
If the loop calls minimize(), we are leaking.

**Comment by dham** [comment]
> > > > @dham I'm using mprof which just gives a time series from snapshots. I suppose I can just divide the final number by the number of for loop iterations.
> > > > @connorjward I am getting what seems to be an increase when using Jhat(). What made you think it wasn't happening?
> > > 
> > > 
> > > Just double checked. The memory usage stays constant if you have the lines
> > > ```python
> > > gc.collect()
> > > PETSc.garbage_cleanup(mesh._comm)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > inside the loop. Otherwise it does increase over time. This is not going to be the solution here since we're still leaking with these calls when we use `minimize`.
> > 
> > 
> > Are both necessary or is the second sufficient?
> > This is a bit weird, because NLVS.solve should be being called when re-evaluating the functional, and that should call the garbage cleanup.
> 
> Actually only the first (`gc.collect()`) is required. This must be because we're otherwise only rarely cleaning up cyclically-referenced objects so the memory appears to grow at first. Ultimately it would get cleared when Python decides to do its own cleanup.

OK so it sounds like we need to add `gc.collect()` in front of the PETSc collection operation when we call it.

**Comment by connorjward** [comment]
To be clear though, this does not fix the memory leak being experienced. Adding `gc.collect()` and `garbage_cleanup` calls does not stop the memory from leaking from the example given above.

**Comment by colinjcotter** [comment]
Here's the output of the above from mprof (so x-axis is sample times). It is 1000 calls to minimize.
![Figure_1](https://github.com/firedrakeproject/firedrake/assets/6105842/a5a50d5f-737b-4f4e-94cb-97abafb0eba0)

**Comment by colinjcotter** [comment]
That's about 5250Mb leaking total, which is about 26.25Mb per minimize() call.

**Comment by colinjcotter** [comment]
I am interested to try other optimisers, but there is not even any API documentation for minimize(), so I don't know how to.

**Comment by connorjward** [comment]
I've figured it out. We are leaking PETSc objects that are stored on `COMM_SELF`. Adding the line `PETSc.garbage_cleanup(PETSc.COMM_SELF)` inside the loop makes the leak go away. You can see the number of objects increasing if you call `PETSc.garbage_view(PETSc.COMM_SELF)`.

The proper fix for this is probably to add some code to PETSc/petsc4py so `COMM_SELF` is always cleared when `garbage_cleanup` is called. Or one could actually eagerly delete these objects since there are no deadlock concerns.

**Comment by maneeshkrsingh** [comment]
Yes, it works. Significantly reduces memory use.

**Comment by wence-** [comment]
> The proper fix for this is probably to add some code to PETSc/petsc4py so `COMM_SELF` is always cleared when `garbage_cleanup` is called. Or one could actually eagerly delete these objects since there are no deadlock concerns.

Yeah, if `comm.size == 1` in petsc then you never need to defer collection

**Comment by connorjward** [comment]
> > The proper fix for this is probably to add some code to PETSc/petsc4py so `COMM_SELF` is always cleared when `garbage_cleanup` is called. Or one could actually eagerly delete these objects since there are no deadlock concerns.
> 
> Yeah, if `comm.size == 1` in petsc then you never need to defer collection

That's exactly what I've done [here](https://gitlab.com/petsc/petsc/-/merge_requests/6835). I will close this issue when that gets merged and our PETSc fork is updated.

**Comment by colinjcotter** [comment]
Thanks for clearing this up!

Once the fix is in, we would still need to call garbage_cleanup in this case - is that right?

What kind of objects are on COMM_SELF?

**Comment by connorjward** [comment]
> Thanks for clearing this up!
> 
> Once the fix is in, we would still need to call garbage_cleanup in this case - is that right?

No you shouldn't need to call `garbage_cleanup`. It gets called automatically by the `LinearSolver` during the adjoint calculation. Also, if you're only running this in serial, then things should always be eagerly collected anyway.

> What kind of objects are on COMM_SELF?

I think there were a lot of `PetscSF`s and the like.

**Comment by connorjward** [comment]
> > > The proper fix for this is probably to add some code to PETSc/petsc4py so `COMM_SELF` is always cleared when `garbage_cleanup` is called. Or one could actually eagerly delete these objects since there are no deadlock concerns.
> > 
> > 
> > Yeah, if `comm.size == 1` in petsc then you never need to defer collection
> 
> That's exactly what I've done [here](https://gitlab.com/petsc/petsc/-/merge_requests/6835). I will close this issue when that gets merged and our PETSc fork is updated.

Closing as this has happened.
