### ISSUE TITLE
INSTALL: 

### ISSUE THREAD

**Issue by AlcaeusX** [firedrakeproject/firedrake#3078]
**Describe the error**
"firedrake module not found" after installing in WSL win10.

**Steps to Reproduce**
installed the dependencies first (not my first install so I had written them down) and then followed the steps on firedrake's site.

**Environment:**
WSL windows 10  (ubuntu)
 - Python version: [eg: 3.10.12]

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/12445841/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/12445843/configure.log)

**Comment by Ig-dolci** [comment]
I saw the error `Failed to build islpy`. Perhaps this error is solved by running `pip install islpy`.

**Comment by AlcaeusX** [comment]
I saw the islpy error and tried installing it but i had the same error.

Regarging-->

> /home/alkaios/firedrake/bin/python -m pip install --no-build-isolation --no-binary mpi4py,randomgen,islpy,numpy -vvv islpy
> ```

(firedrake) alkaios@Legion-Alcaeus:~$ /home/alkaios/firedrake/bin/python -m pip install --no-build-isolation --no-binary mpi4py,randomgen,islpy,numpy -vvv islpy
Using pip 23.2.1 from /home/alkaios/firedrake/lib/python3.10/site-packages/pip (python 3.10)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-build-tracker-ul9zji09
Initialized build tracking at /tmp/pip-build-tracker-ul9zji09
Created build tracker: /tmp/pip-build-tracker-ul9zji09
Entered build tracker: /tmp/pip-build-tracker-ul9zji09
Created temporary directory: /tmp/pip-install-dwzr38ah
Created temporary directory: /tmp/pip-ephem-wheel-cache-r1bdf5qp
Requirement already satisfied: islpy in ./firedrake/lib/python3.10/site-packages (2023.1.2)
Created temporary directory: /tmp/pip-unpack-pzkq3h5r
Remote version of pip: 23.2.1
Local version of pip:  23.2.1
Was pip installed by pip? True
Removed build tracker: '/tmp/pip-build-tracker-ul9zji09'

**Comment by connorjward** [comment]
Perhaps you could make sure that your system is up to date with `sudo apt update && sudo apt upgrade`? Also, since you are failing to build the ISL shipped with islpy you could try running `sudo apt install libisl-dev`.

**Comment by AlcaeusX** [comment]
> Perhaps you could make sure that your system is up to date with `sudo apt update && sudo apt upgrade`? Also, since you are failing to build the ISL shipped with islpy you could try running `sudo apt install libisl-dev`.

I did run both commands but the problem persists. Should I delete everything and run these before installing again or send you the new logs?

**Comment by connorjward** [comment]
> > Perhaps you could make sure that your system is up to date with `sudo apt update && sudo apt upgrade`? Also, since you are failing to build the ISL shipped with islpy you could try running `sudo apt install libisl-dev`.
> 
> I did run both commands but the problem persists. Should I delete everything and run these before installing again or send you the new logs?

Yes please do.

**Comment by AlcaeusX** [comment]
[configure.log](https://github.com/firedrakeproject/firedrake/files/12522286/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/12522295/firedrake-install.log)

**Comment by connorjward** [comment]
I think you are running out of memory during compilation of ISL. Can you try increasing the memory available to WSL? It is described [here](https://fizzylogic.nl/2023/01/05/how-to-configure-memory-limits-in-wsl2) for example.

**Comment by JDBetteridge** [comment]
We have removed the part of the install script that builds islpy from source. Can you try downloading the latest version of the install script and trying again?

**Comment by JDBetteridge** [comment]
https://github.com/firedrakeproject/firedrake/wiki/Closing-Installation-Issues
