### ISSUE TITLE
INSTALL: CENTOS 9

### ISSUE THREAD

**Issue by NischalKMapakshi** [firedrakeproject/firedrake#3112]
**Describe the error**
Traceback (most recent call last):
  File "/home/karthik/firedrake-install", line 1873, in <module>
    install("petsc/")
  File "/home/karthik/firedrake-install", line 1043, in install
    build_and_install_petsc()
  File "/home/karthik/firedrake-install", line 1155, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "/home/karthik/firedrake-install", line 666, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/karthik/firedrake/bin/python', './configure', 'PETSC_DIR=/home/karthik/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-bison', '--with-c2html=0', '--download-hwloc', '--download-netcdf', '--with-debugging=0', '--download-mumps', '--download-chaco', '--with-zlib', '--with-shared-libraries=1', '--download-ml', '--download-mpich', '--download-cmake', '--download-hdf5', '--download-superlu_dist', '--download-pnetcdf', '--download-metis', '--download-suitesparse', '--with-fortran-bindings=0', '--download-scalapack', '--download-ptscotch', '--download-pastix', '--download-hypre']' returned non-zero exit status 1.

 - OS: CENTOS 9
 - Python version: 3.9.17

**Additional context**
Hello, I've been trying to install Firedrake on CENTOS 9, I've gone through previous discussions and installed all the dependencies/requirements using yum. I'm getting the above error message. I'm uploading firedrake-install.log and configure.log of Petc. Please have a look. Thanks.  
[configure.log](https://github.com/firedrakeproject/firedrake/files/12670643/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/12670649/firedrake-install.log)

**Comment by connorjward** [comment]
You are having issues with your BLAS. Does running `firedrake-install` with `--with-blas=download` help?

**Comment by NischalKMapakshi** [comment]
Hey Connor,
Could you please have a look?

**Comment by connorjward** [comment]
The error you are encountering now was recently fixed. Please can you redownload the install script and try again?

**Comment by NischalKMapakshi** [comment]
Hello Connor,

It's working, I even tested the installation. 
Thanks a lot!

**Comment by NischalKMapakshi** [comment]
Hello Connor,

It's working, I even tested the installation.
Thanks a lot!
