### ISSUE TITLE
INSTALL: 

### ISSUE THREAD

**Issue by fred-valentin** [firedrakeproject/firedrake#3134]
**Describe the error**
Not able to install Firedrake properly. It stopped at the PETSc installation stage.

**Steps to Reproduce**
curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
python3 firedrake-install --package-branch petsc ksagiyam/merge_upstream --with-blas=download

**Expected behavior**
Install FireDrake

**Error message**
Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "firedrake-install", line 1887, in <module>
    install("petsc/")
  File "firedrake-install", line 1043, in install
    build_and_install_petsc()
  File "firedrake-install", line 1155, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "firedrake-install", line 666, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/valentin/soft-orig/original/firedrake/bin/python', './configure', 'PETSC_DIR=/Users/valentin/soft-orig/original/firedrake/src/petsc', 'PETSC_ARCH=default', "--download-openblas-make-options='USE_THREAD=0 USE_LOCKING=1 USE_OPENMP=0'", '--with-fortran-bindings=0', '--download-mpich', '--download-scalapack', '--download-netcdf', '--download-mumps', '--with-shared-libraries=1', '--with-c2html=0', '--download-hdf5', '--with-zlib', '--CFLAGS=-Wno-implicit-function-declaration', '--with-x=0', '--download-hwloc', '--download-hwloc-configure-arguments=--disable-opencl', '--download-hypre', '--download-superlu_dist', '--download-bison', '--download-ml', '--download-suitesparse', '--download-metis', '--download-pnetcdf', '--download-openblas', '--download-ptscotch', '--download-mpich-configure-arguments=--disable-opencl', '--download-chaco', '--with-debugging=0', '--download-pastix']' returned non-zero exit status 1.
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/12768948/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/12768951/configure.log)

**Environment:**
Python 3.8 (/Library/Frameworks/Python.framework/Versions/3.8/bin/python3)
MacOS BigSur 11.7.9

**Additional context**

**Comment by dham** [comment]
I can see from your installation log that you appear to be using the MacOS system Python, and that you have anaconda in your path. Both of these are known sources of trouble when installing Firedrake. See here: https://www.firedrakeproject.org/download.html#system-requirements and particularly the anti-requirement on anaconda.

**Comment by JDBetteridge** [comment]
https://github.com/firedrakeproject/firedrake/wiki/Closing-Installation-Issues
