### ISSUE TITLE
INSTALL: PETSc on MacOS (previous resolutions no longer working)

### ISSUE THREAD

**Issue by megr090** [firedrakeproject/firedrake#3142]
Hello,

I am trying to install firedrake on a new machine (M1 Mac) and am running into install issues. I had install issues previously on an M1 Mac and adding "--with-blas=download" after the install command worked well. For some reason, the same command is no longer working, and I'm not sure what has caused the error. Below I include the error message, the install log and configure file, and the information about the environment.

Steps to reproduce:

> curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
> python firedrake-install --install icepack --with-blas=download

Error message:

> Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "/Users/meghanaranganathan/Documents/GeorgiaTech/Research/IceDamage/icepack_source/firedrake-install", line 1899, in <module>
    install("petsc/")
  File "/Users/meghanaranganathan/Documents/GeorgiaTech/Research/IceDamage/icepack_source/firedrake-install", line 1043, in install
    build_and_install_petsc()
  File "/Users/meghanaranganathan/Documents/GeorgiaTech/Research/IceDamage/icepack_source/firedrake-install", line 1155, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "/Users/meghanaranganathan/Documents/GeorgiaTech/Research/IceDamage/icepack_source/firedrake-install", line 666, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
  File "/Users/meghanaranganathan/anaconda3/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/meghanaranganathan/anaconda3/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/meghanaranganathan/Documents/GeorgiaTech/Research/IceDamage/icepack_source/firedrake/bin/python', './configure', 'PETSC_DIR=/Users/meghanaranganathan/Documents/GeorgiaTech/Research/IceDamage/icepack_source/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-chaco', '--with-c2html=0', '--download-hwloc-configure-arguments=--disable-opencl', '--download-metis', '--download-hdf5', '--download-pastix', '--download-mpich-configure-arguments=--disable-opencl', '--with-fortran-bindings=0', '--download-bison', '--download-suitesparse', '--with-shared-libraries=1', '--with-zlib', '--download-mpich', '--download-scalapack', '--download-superlu_dist', "--download-openblas-make-options='USE_THREAD=0 USE_LOCKING=1 USE_OPENMP=0'", '--with-debugging=0', '--download-pnetcdf', '--CFLAGS=-Wno-implicit-function-declaration', '--download-openblas', '--download-ptscotch', '--download-hypre', '--download-mumps', '--download-netcdf', '--download-ml', '--with-x=0', '--download-hwloc']' returned non-zero exit status 1.

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/12834423/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/12834425/configure.log)

Environment:
-MacOS, Ventura 13.2.1
-Python version 3.10.9

**Comment by connorjward** [comment]
You are using an anaconda python to run `firedrake-install`. This is known to cause issues. Can you try again with a homebrew installed (and up to date) python? Please note that `firedrake-install` is currently facing lots of issues on macOS so this might not fix everything. We are working on fixing things ASAP but if you really need a usable Firedrake then we recommend using one of our Docker images.

**Comment by megr090** [comment]
Great, thank you so much! That worked, and I'll look into using a Docker image in the future.
