### ISSUE TITLE
New DOFs for DG on simplices

### ISSUE THREAD

**Issue by pbrubeck** [firedrakeproject/firedrake#3154]
**Describe the current issue**
Currently we get undesired behaivior when interpolating discontinuous ufl expressions onto DG_k (k > 0) spaces on simplices (d > 1) if the discontinuity is located at an element interface. Typically, this will be due to the fact that `ufl.conditional` is singled  valued, and the DOFs for DG_k that we use concide with those of CG_k. Some of the DOFs are located exactly at the interfaces, in spite the fact that these DOFs do not have a topological association to the facets. Projecting such an expression gives expected behaivior.

```
from firedrake import *
import numpy

nx = 2
mesh = UnitSquareMesh(nx,nx)
V = FunctionSpace(mesh, "DG", degree=1)

x = SpatialCoordinate(mesh)
expr = conditional(gt(x[0], 0.5), 1, 0)

u_int = Function(V, name="interpolate").interpolate(expr)
u_proj = Function(V, name="project").project(expr)
File("output/jump.pvd").write(u_int, u_proj)
assert numpy.allclose(u_int.dat.data_ro, u_proj.dat.data_ro, atol=1E-10)
```

**Describe the solution you'd like**
We should use a different set of DOFs for DG_k, similar to what we do for DQ_k using GL points. Perhaps we could simply choose the interior points of the equispaced lattice used for CG_{k+2}?

**Comment by dham** [comment]
This is really a FIAT issue. Feel free to contribute Lagrange and or Discontinuous Lagrange elements to FIAT with better locations.

If you're going to the effort of doing it, the interior equispaced lattice is still not a great choice. Presumably the right choice is some sort of triangular GL set.

**Comment by wence-** [comment]
You might consider Toby's recursively-defined simplex nodes that are symmetric and not equispaced. Especially for the tet they have excellent Lebesgue constants compared to the alternatives: https://epubs.siam.org/doi/pdf/10.1137/20M1321802

**Comment by pbrubeck** [comment]
Is this also the reason why DG injection uses projection as opposed to simply interpolating?
