### ISSUE TITLE
Zenodo release: 2023-10

### ISSUE THREAD

**Issue by blechta** [firedrakeproject/firedrake#3158]
Can you please create a Zenodo release for my upcoming publication:

### Quasi-optimal Discontinuous Galerkin discretisations of the $p$-Dirichlet equation

[firedrake.json](https://github.com/firedrakeproject/firedrake/files/12883935/firedrake.json)

Note that hashes of petsc4py and slepc4py are just copies of PETSc and SLEPc as they have common repos now.

Consider that this request would be redundant if Docker tag 2023-10 was released, cf. #3157

**Comment by wence-** [comment]
Hashes of petsc4py and slepc4py can be dropped if they're in petsc (they're "optional").

**Comment by blechta** [comment]
I guess that the script should drop them?

**Comment by ksagiyam** [comment]
The script does not drop them automatically as, for someone using a very old Firedrake,  `petsc4py` is indeed a separate package, so I manually deleted the redundant entries.

Created Zenodo meta-release.
Tag is `Firedrake_20231101.0`
DOI is 10.5281/zenodo.10061067
Zenodo URL is https://zenodo.org/record/10061067
BibTeX

```bibtex
@misc{zenodo/Firedrake-20231101.0,
 key   = {zenodo/Firedrake-20231101.0},
 title = {{Software used in `Quasi-optimal Discontinuous Galerkin discretisations of the $p$-Dirichlet equation'}},
 year  = {2023},
 month = {nov},
 doi   = {10.5281/zenodo.10061067},
 url   = {https://doi.org/10.5281/zenodo.10061067},
}

```

**Comment by blechta** [comment]
@ksagiyam Awesome, thanks!
