### ISSUE TITLE
Merge current upstream PETSc

### ISSUE THREAD

**Issue by angus-g** [firedrakeproject/firedrake#3160]
**Describe the current issue**
There are a few notable fixes that have landed in upstream PETSc since the latest merge https://github.com/firedrakeproject/petsc/commit/37b8d529764055f1df8a2eca90493d6b9b86a026:
- https://gitlab.com/petsc/petsc/-/merge_requests/6918 (GAMG low memory filter)
- https://gitlab.com/petsc/petsc/-/merge_requests/6923 (GAMG square graph)
- https://gitlab.com/petsc/petsc/-/merge_requests/6905 (CHOLMOD empty matrix behaviour)

**Describe the solution you'd like**
It'd be great if the firedrakeproject/petsc fork could be updated again to bring in these latest changes.

**Describe alternatives you've considered**
It's possible to build upstream PETSc locally, but we consume the official Docker images in many places. It would be easiest for this to be updated at the source.

Thanks!

**Comment by dham** [comment]
The mechanism for getting the PETSc fork updated is:

1. Push a branch to firedrake's PETSc fork with upstream master merged in.
2. Push a branch to firedrake with build.yaml modified to use the PETSc branch above.
3. Open a draft PR on the firedrake branch so that the CI runs.

If the CI runs successfully, we can update.

**Comment by connorjward** [comment]
We have written down the procedure in more detail [here](https://github.com/firedrakeproject/firedrake/wiki/Updating-forked-dependencies).

**Comment by angus-g** [comment]
Thanks both, I guess the only issue here is the assumption that one has commit access to the firedrakeproject versions of this repository. I could submit a PR that modifies `requirements-git.txt` to point to my fork, although I guess the workflows would also need to be approved to run here anyway?

**Comment by dham** [comment]
That's a shocking oversight on my part which I have just remedied. You should now have an invite giving you push access to the various Firedrake repos.

**Comment by angus-g** [comment]
Thanks @dham! All seems to be underway now.
