### ISSUE TITLE
fredrake-install broken on macOS for clang15

### ISSUE THREAD

**Issue by Ig-dolci** [firedrakeproject/firedrake#3163]
**Describe the error**
In Xcode 15, there is a new linker that can potentially cause compatibility issues with certain projects, including OpenMPI. To work around this problem for the Petsc install, we need to set LDFLAGS='-Wl,-ld_classic' which instructs Petsc to use the classic linker. 

**Environment:**
MacOS

**Obs**
I tried the clang from the Xcode beta 15.1 and I had the same issue.

**Comment by JDBetteridge** [comment]
Can this issue be closed no #3171 has gone in?

**Comment by Ig-dolci** [comment]
Yes. The latest `firedrake-install` script worked!
