### ISSUE TITLE
Zenodo release: 

### ISSUE THREAD

**Issue by sghelichkhani** [firedrakeproject/firedrake#3188]
Hi FD team, can you please create a Zenodo release for:

### Software used in G-ADOPT v2.1.0

```{"firedrake": "23fd903aa5ceb0c149f56c0bbe098f90fa89ff55", "PyOP2": "d017d594e0bda694a71c4180fbfeae1cba473e93", "tsfc": "47c132456a76fc42ba8dc750e8cc7ac6d42c66da", "ufl": "cf66c4b371604e53854459dd8bcd7c3b5f8ee5cf", "FInAT": "f493084b14e6a1b68be3bec0c60af4a85931d896", "fiat": "e440a0695ce75886cb2d09d4e3da44abe3803d8b", "petsc": "98a99952882472a64d49cfa93b3213cb01e00456", "loopy": "8158afdb18f100fb21b6cd86c6178e3c5cd19058", "metarelease_info_file": null, "title": "Software for g-adopt v2.1.0"}```

**Comment by ksagiyam** [comment]
Created Zenodo meta-release.
Tag is `Firedrake_20231027.0`
DOI is 10.5281/zenodo.10047031
Zenodo URL is https://zenodo.org/record/10047031
BibTeX

```bibtex
@misc{zenodo/Firedrake-20231027.0,
 key   = {zenodo/Firedrake-20231027.0},
 title = {{Software used in `Software for g-adopt v2.1.0'}},
 year  = {2023},
 month = {oct},
 doi   = {10.5281/zenodo.10047031},
 url   = {https://doi.org/10.5281/zenodo.10047031},
}

```
Thanks!
