### ISSUE TITLE
Zenodo release for new publication

### ISSUE THREAD

**Issue by a-brugnoli** [firedrakeproject/firedrake#3190]
Can you please create a Zenodo release for my upcoming publication:

* Brugnoli, Rashad, Zhang, Stramigioli [Finite element hybridization of port-Hamiltonian systems](https://arxiv.org/abs/2302.06239).

[firedrake.json](https://github.com/firedrakeproject/firedrake/files/13187698/firedrake.json)

**Comment by ksagiyam** [comment]
Created Zenodo meta-release.
Tag is `Firedrake_20231027.1`
DOI is 10.5281/zenodo.10047121
Zenodo URL is https://zenodo.org/record/10047121
BibTeX

```bibtex
@misc{zenodo/Firedrake-20231027.1,
 key   = {zenodo/Firedrake-20231027.1},
 title = {{Software used in `Finite Element Hybridization of port-Hamiltonian systems'}},
 year  = {2023},
 month = {oct},
 doi   = {10.5281/zenodo.10047121},
 url   = {https://doi.org/10.5281/zenodo.10047121},
}

```
Thanks!
