### ISSUE TITLE
Zonodo release for preprint

### ISSUE THREAD

**Issue by cparker4** [firedrakeproject/firedrake#3200]
Can you please create a Zenodo release for my upcoming preprint:

Computing H2-conforming finite element approximations without having to implement C1-elements

I have attached `firedrake.json`.

Thank you!

Best,
Charlie Parker

[firedrake.json](https://github.com/firedrakeproject/firedrake/files/13243059/firedrake.json)

**Comment by UZerbinati** [comment]
Looking forward to read the preprint !

**Comment by ksagiyam** [comment]
Created Zenodo meta-release.
Tag is `Firedrake_20231103.0`
DOI is 10.5281/zenodo.10070565
Zenodo URL is https://zenodo.org/record/10070565
BibTeX

```bibtex
@misc{zenodo/Firedrake-20231103.0,
 key   = {zenodo/Firedrake-20231103.0},
 title = {{Software used in `Computing H2-conforming finite element approximations without having to implement C1-elements'}},
 year  = {2023},
 month = {nov},
 doi   = {10.5281/zenodo.10070565},
 url   = {https://doi.org/10.5281/zenodo.10070565},
}

```
Thanks!
