### ISSUE TITLE
DOCS: Example in documentation does not run, it is missing the variable definition of 1`line`.

### ISSUE THREAD

**Issue by p479h** [firedrakeproject/firedrake#3294]
I was reading the [documentation](https://www.firedrakeproject.org/interpolation.html#interpolating-onto-sub-domain-meshes) and found that the example in the link is missing the definition of `line`. 

This is the line of code where the undefined line object is used:

`V_line = FunctionSpace(line, "CG", 2)`

I hope this is the right place to raise this issue.

**Comment by connorjward** [comment]
Thank you for raising this. Someone will get around to fixing this at some point.
