### ISSUE TITLE
BUG: UFLInequalityConstraint from firedrake.adjoint is not working

### ISSUE THREAD

**Issue by diego-hayashi** [firedrakeproject/firedrake#3325]
**Describe the bug**
`UFLInequalityConstraint` from `firedrake.adjoint` is not working.

**Steps to Reproduce**
In order to make it simpler to reproduce, I took the code from the notebook [06-pde-constrained-optimisation.ipynb](https://github.com/firedrakeproject/firedrake/blob/master/docs/notebooks/06-pde-constrained-optimisation.ipynb) from the Firedrake docs, made it shorter, and included an arbitrary constraint in the last two lines. Run the following code with `python minimum_example.py` and the error will happen in the `a_constraint` line. Note that the code does not throw any error if the `a_constraint` is not used. 

```python
from firedrake import *
from firedrake.adjoint import *

continue_annotation()

mesh = Mesh("stokes-control.msh") # Get the file from https://github.com/firedrakeproject/firedrake/blob/master/docs/notebooks/stokes-control.msh

V = VectorFunctionSpace(mesh, "Lagrange", 2)
Q = FunctionSpace(mesh, "Lagrange", 1)
W = V*Q

nu = Constant(1)
alpha = Constant(10)
g_lim = Constant(1.0)

g = Function(V, name = "Control")
x, y = SpatialCoordinate(mesh)
u_inflow = as_vector([y*(10-y)/25.0, 0])
bcs = [
	DirichletBC(W.sub(0), (0, 0), (3, 5)), 
	DirichletBC(W.sub(0), interpolate(u_inflow, V), 1), 
	DirichletBC(W.sub(0), g, 4)
]

w = Function(W)
u, p = TrialFunctions(W)
v, q = TestFunctions(W)
a = nu*inner(grad(u), grad(v))*dx - inner(p, div(v))*dx - inner(q, div(u))*dx
L = Constant(0)*q*dx
solve(a == L, w, bcs = bcs)

u, p = split(w)
J = assemble(1./2*inner(grad(u), grad(u))*dx + alpha/2*inner(g, g)*ds(4))
m = Control(g)
Jhat = ReducedFunctional(J, m)

a_constraint = UFLInequalityConstraint((-inner(g,g) + g_lim)*ds(4), m)
g_opt = minimize(Jhat, method = 'SLSQP', constraints = a_constraint, options = {'disp' : True, 'iprint' : 2, 'maxiter' : 2})
```

**Expected behavior**
Not to throw the error message that was seen.

**Error message**
The traceback is the following:

```
Traceback (most recent call last):
  File "minimum_example.py", line 44, in <module>
    a_constraint = UFLInequalityConstraint((-inner(g,g) + g_lim)*ds(4), m)
  File "/opt/firedrake/src/firedrake/firedrake/adjoint/ufl_constraints.py", line 29, in __init__
    if not isinstance(control.control, backend.Function):
AttributeError: module 'firedrake.adjoint_utils.blocks.backend' has no attribute 'Function'
```

**Environment**

**Additional Info**
The error seems to be something related to [`ufl_constraints.py`](https://github.com/firedrakeproject/firedrake/blob/master/firedrake/adjoint/ufl_constraints.py), and the call of `backend` that comes from [backend.py](https://github.com/firedrakeproject/firedrake/blob/master/firedrake/adjoint_utils/blocks/backend.py).

**Comment by connorjward** [comment]
I've added this to the [agenda for today's meeting](https://github.com/firedrakeproject/firedrake/wiki/Firedrake-meeting-2024-01-17).

**Comment by connorjward** [comment]
@diego-hayashi I have done a quick fix for this. Can you try checking out the branch `connorjward/less-backend` and seeing if it works for you? There still appear to be issues with your MFE - it crashes - but the backend error has gone away.

**Comment by connorjward** [comment]
This appears to be an issue with `Argument` numbering. Changing [the line](https://github.com/firedrakeproject/firedrake/blob/master/firedrake/adjoint/ufl_constraints.py#L44)
```py
        self.trial = firedrake.TrialFunction(self.V)
```
to
```py
        self.trial = firedrake.TestFunction(self.V)  # now a dreadful variable name
```
and using my branch is sufficient to get the MFE passing. Unfortunately I don't really have enough experience with the adjoint to understand why this is the right thing to do/understand why this previously used to work. @nbouziani do you have any ideas? Is it sufficient to just swap `self.trial` and `self.test` in this class and have things work?

**Comment by dham** [comment]
I'm not surprised that that needs to be a testfunciton, but I am a little surprised that the second derivative a few lines down doesn't need to then be a trialfunction.

**Comment by nbouziani** [comment]
Yes, I think both should be swapped. The derivative of a 0-form should have a zero-numbered argument. Has this ever been working ?
