### ISSUE TITLE
Successful installation on HPC but code is not working

### ISSUE THREAD

**Issue by Dochu1** [firedrakeproject/firedrake#3329]
I installed firedrake on Imperial College London HPC as a batch job using the following job script

`
#!/bin/bash
#PBS -N fd_install
#PBS -l walltime=07:00:00
#PBS -l select=1:ncpus=16:mem=32gb
#PBS -o fd_install.out
#PBS -e fd_install.err
echo Working Directory is $PBS_O_WORKDIR
cd $PBS_O_WORKDIR
module purge
module load gcc/11.2.0
module load mpi
module load git
module load tools/prod
module load Python/3.11.2-GCCcore-12.2.0-bare
export MPICC_CC=gcc
export MPICXX_CXX=g++
export MPIF08_F08='gfortran -I/apps/intel/2019.4/compilers_and_libraries_2019.4.2.43/linux/mpi/intel64/include/ilp64/gfortran/8.2.0'
export MPIF90_F90="$MPIF08_F08"
export PETSC_CONFIGURE_OPTIONS=--download-fblaslapack
export PATH=$HOME/.local/bin:$PATH
python3.11 firedrake-install --no-package-manager --honour-pythonpath --disable-ssh
`

The installation was successful. However, when I tried to import firedrake with 
`from firedrake import *` , I get the error message

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/rds/general/user/rh2015/home/firedrake/src/firedrake/firedrake/__init__.py", line 19, in <module>
    import firedrake.petsc as petsc
  File "/rds/general/user/rh2015/home/firedrake/src/firedrake/firedrake/petsc.py", line 19, in <module>
    petsc4py.init(sys.argv)
  File "/rds/general/user/rh2015/home/firedrake/lib64/python3.11/site-packages/petsc4py/__init__.py", line 41, in init
    PETSc = petsc4py.lib.ImportPETSc(arch)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/rh2015/home/firedrake/lib64/python3.11/site-packages/petsc4py/lib/__init__.py", line 29, in ImportPETSc
    return Import('petsc4py', 'PETSc', path, arch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/rh2015/home/firedrake/lib64/python3.11/site-packages/petsc4py/lib/__init__.py", line 95, in Import
    module = import_module(pkg, name, path, arch)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rds/general/user/rh2015/home/firedrake/lib64/python3.11/site-packages/petsc4py/lib/__init__.py", line 71, in import_module
    module = importlib.util.module_from_spec(spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /rds/general/user/rh2015/home/firedrake/src/petsc/default/lib/libpetsc.so.3.020: undefined symbol: MPI_Neighbor_alltoallv_init
`

Any help would be appreciated!

The firedrake-install.log is here 
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/13940984/firedrake-install.log).

**Comment by connorjward** [comment]
It looks like you are trying to use a system MPI. For `firedrake-install` to not install its own MPI (MPICH) and link against the system one you need to pass the flags `--mpiexec path/to/mpiexec`, `--mpicc ...`, `--mpicxx ...` and `--mpif90 ...`. This is documented if you run `firedrake-install --help`.

To verify this I expect that running `ldd /rds/general/user/rh2015/home/firedrake/src/petsc/default/lib/libpetsc.so.3.020` will show you that PETSc is not linked against the expected `libmpi`.

Tagging @JDBetteridge as the resident HPC expert.

**Comment by Dochu1** [comment]
Running the command `ldd /rds/general/user/rh2015/home/firedrake/src/petsc/default/lib/libpetsc.so.3.020` gave me

`
linux-vdso.so.1 (0x00007fff54d48000)
	libHYPRE-2.30.0.so => /rds/general/user/rh2015/home/firedrake/src/petsc/default/lib/libHYPRE-2.30.0.so (0x000014723bf98000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x000014723bd78000)
	libscalapack.so.2.2 => /rds/general/user/rh2015/home/firedrake/src/petsc/default/lib/libscalapack.so.2.2 (0x000014723b731000)
	libsuperlu_dist.so.8 => /rds/general/user/rh2015/home/firedrake/src/petsc/default/lib/libsuperlu_dist.so.8 (0x000014723ddd9000)
	libhdf5_hl.so.310 => /rds/general/user/rh2015/home/firedrake/src/petsc/default/lib/libhdf5_hl.so.310 (0x000014723ddb2000)
	libhdf5.so.310 => /rds/general/user/rh2015/home/firedrake/src/petsc/default/lib/libhdf5.so.310 (0x000014723b299000)
	libm.so.6 => /lib64/libm.so.6 (0x000014723af17000)
	libX11.so.6 => /lib64/libX11.so.6 (0x000014723abd3000)
	libdl.so.2 => /lib64/libdl.so.2 (0x000014723a9cf000)
	libmpifort.so.12 => /apps/mpi/intel/2019.6.166/lib/libmpifort.so.12 (0x000014723a611000)
	libmpi.so.12 => /apps/mpi/intel/2019.6.166/lib/release/libmpi.so.12 (0x0000147239577000)
	libgfortran.so.5 => /rds/easybuild/zen2/apps/software/GCCcore/12.2.0/lib64/libgfortran.so.5 (0x00001472392a9000)
	libgcc_s.so.1 => /rds/easybuild/zen2/apps/software/GCCcore/12.2.0/lib64/libgcc_s.so.1 (0x000014723dd8d000)
	libquadmath.so.0 => /rds/easybuild/zen2/apps/software/GCCcore/12.2.0/lib64/libquadmath.so.0 (0x000014723dd46000)
	libstdc++.so.6 => /rds/easybuild/zen2/apps/software/GCCcore/12.2.0/lib64/libstdc++.so.6 (0x0000147239082000)
	librt.so.1 => /lib64/librt.so.1 (0x0000147238e7a000)
	libc.so.6 => /lib64/libc.so.6 (0x0000147238ab5000)
	/lib64/ld-linux-x86-64.so.2 (0x000014723dcff000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x000014723888c000)
	libfabric.so.1 => /apps/mpi/intel/2019.6.166//libfabric/lib/libfabric.so.1 (0x0000147238647000)
	libXau.so.6 => /lib64/libXau.so.6 (0x0000147238443000)
`

which I am unsure if the linked libmpi `libmpi.so.12 => /apps/mpi/intel/2019.6.166/lib/release/libmpi.so.12 (0x0000147239577000)` is expected or not.

**Comment by JDBetteridge** [comment]
It is incorrect, you may have to unload the Intel  MPI module, you may have to set some environment variables to get it to link correctly. I have some examples of how to fix this sort of error here: https://hackmd.io/zRpTBjJTTQ631f1mYLKpgw#BLASMPI-Linking-issues . Be sure to read and understand the paths carefully, you will not be able to just copy and paste.

**Comment by Dochu1** [comment]
Reinstalling firedrake without loading in any MPI module from HPC and using downloaded MPICH has solved the issue.

**Comment by ReHoss** [comment]
> Reinstalling firedrake without loading in any MPI module from HPC and using downloaded MPICH has solved the issue.

does this requires `sudo` ?

**Comment by connorjward** [comment]
> > Reinstalling firedrake without loading in any MPI module from HPC and using downloaded MPICH has solved the issue.
> 
> does this requires `sudo` ?

It shouldn't do.
