### ISSUE TITLE
BUG: cannot import from firedrake.pyplot

### ISSUE THREAD

**Issue by adominious** [firedrakeproject/firedrake#3331]
**Describe the bug**
No module named 'firedrake.pyplot'

**Steps to Reproduce**
from firedrake.pyplot import tripcolor, tricontour

**Expected behavior**
No error to occur and respective modules to be imported

**Error message**
```
Traceback (most recent call last):
  File "/home/adamh/firedrake-introduction/simple_Helmholtz_equation.py", line 69, in <module>
    from firedrake.pyplot import tripcolor, tricontour
ModuleNotFoundError: No module named 'firedrake.pyplot'
```

**Environment:**
 - OS: Linux (EndeavourOS)
 - Python version: 3.11.6

**Comment by connorjward** [comment]
Strange. @JDBetteridge moved around some of the plotting functions recently. Have you recently run `firedrake-update`?

If this is a fresh install does `pip install matplotlib` make the error go away?

**Comment by JDBetteridge** [comment]
This error may also occur if you update and then switch to a branch with an older base commit (`firedrake.pyplot` is created when you update master, but then disappears when you switch to your branch). You can fix such errors by rebasing on master, or merging master into your branch.
