### ISSUE TITLE
BUG: bug in assembly or vertex-only mesh

### ISSUE THREAD

**Issue by danshapero** [firedrakeproject/firedrake#3340]
**Describe the bug**
A test case that I've been running is giving different answers with different versions of Firedrake. Specifically, solving a PDE-constrained optimization problem is converging to a wrong answer on the most recent available Docker image (as of 19 Jan) and a correct answer on the Docker image from December.

**Steps to Reproduce**
The entire code is available in [this repo](https://github.com/icepack/kangerdlugssuaq-test). The test suite for this repo runs the same code on the images from Sept, Oct, Nov, Dec, and latest. I'll try to bisect to find the exact commit.

This test case uses observational data that is available through NASA EarthData. Access to the data is free but requires an EarthData account. If you clone it and run it on your machine, the data fetching routines from icepack will prompt you for a username/password. I'm trying to produce a more minimal working example with just synthetic data but this is what I've got for now.

**Expected behavior**
The solver for the PDE-constrained optimization problem was taking an objective functional with initial values on the order of 1e+6 to 9e+3 in what I consider to be the working versions but is only achieving a final value of 4e+5 in the newest version of Firedrake.

**Error message**
Here is a snippet of the convergence log in what I consider to be one of the good runs, using the firedrake-vanilla:2023-12 image:
```
Truncated CG Trust-Region Solver
  iter  value          gnorm          snorm          delta          #fval     #grad     tr_flag   iterCG    flagCG    
  0     5.114858e+05   1.709185e+02                  3.673390e+03   
  1     1.372025e+05   4.912532e+01   3.673390e+03   9.183476e+03   3         2         0         1         3         
  2     4.204794e+04   1.353114e+01   9.183476e+03   9.183476e+03   4         3         0         2         3         
  3     2.950196e+04   7.238300e+00   9.183476e+03   9.183476e+03   5         4         0         3         2         
  4     2.793487e+04   9.827319e+00   9.183476e+03   9.183476e+03   6         5         0         5         3         
  5     2.793487e+04   9.827319e+00   9.183476e+03   5.739673e+02   7         5         2         3         2         
  6     2.339058e+04   6.265322e+00   5.739673e+02   1.434918e+03   8         6         0         1         3         
  7     1.863370e+04   2.740199e+00   1.434918e+03   3.587295e+03   9         7         0         2         3         
  8     1.456112e+04   1.019066e+00   3.587295e+03   8.968238e+03   10        8         0         4         3         
  9     1.384099e+04   3.190127e+00   8.968238e+03   8.968238e+03   11        9         0         5         3         
  10    1.384099e+04   3.190127e+00   8.968238e+03   5.605149e+02   12        9         2         3         3         
  ...
  45    9.276844e+03   2.482932e-01   3.111483e+02   3.111483e+02   47        38        0         4         3         
  46    9.257746e+03   1.085634e-01   3.111483e+02   7.778707e+02   48        39        0         5         3         
  47    9.234619e+03   2.478338e-01   7.778707e+02   7.778707e+02   49        40        0         5         3         
  48    9.221438e+03   2.183751e-01   7.778707e+02   7.778707e+02   50        41        0         6         3         
  49    9.179874e+03   1.994006e-01   7.778707e+02   1.944677e+03   51        42        0         6         3         
  50    9.179874e+03   1.994006e-01   1.944677e+03   1.215423e+02   52        42        2         4         2         
Optimization Terminated with Status: Iteration Limit Exceeded
```

and here is a snippet of one of the bad runs:

```
Truncated CG Trust-Region Solver
  iter  value          gnorm          snorm          delta          #fval     #grad     tr_flag   iterCG    flagCG    
  0     1.010102e+06   1.397665e+02                  5.140773e+03   
  1     5.889067e+05   4.626753e+01   5.140773e+03   1.285193e+04   3         2         0         2         3         
  2     4.637360e+05   1.123335e+01   1.285193e+04   1.285193e+04   4         3         0         2         2         
  3     4.505305e+05   1.346318e+01   1.285193e+04   1.285193e+04   5         4         0         2         3         
  4     4.389086e+05   6.958346e+00   1.285193e+04   1.285193e+04   6         5         0         2         2         
  5     4.389086e+05   6.958346e+00   1.285193e+04   8.032458e+02   7         5         2         3         2         
...    
  45    3.671430e+05   7.435655e-01   1.740974e+03   1.740974e+03   47        40        0         3         3         
  46    3.671430e+05   7.435655e-01   1.740974e+03   4.352434e+02   48        41        0         3         3         
  47    3.669776e+05   6.523151e-01   4.352434e+02   1.088109e+03   49        42        0         1         3         
  48    3.667413e+05   3.559979e-01   1.088109e+03   2.720271e+03   50        43        0         3         3         
  49    3.660396e+05   7.562733e-01   2.720271e+03   6.800679e+03   51        44        0         3         2         
  50    3.652938e+05   3.144753e+00   6.800679e+03   6.800679e+03   52        45        0         2         2         
Optimization Terminated with Status: Iteration Limit Exceeded
```

**Environment:**
Using the firedrake-vanilla images 2023-09, 2023-10, 2023-11, 2023-12, and latest, the last of which is from 19 Jan.

**Additional Info**
The attached images show the bad and good results. Briefly, the problem is to compute the basal friction -- a coefficient in the momentum balance equation -- between a glacier and the bed that it flows over. This field is not directly observable so it has to be estimated from observations of the surface velocity. The good version shows that the model computes very low bed friction along the main trunk of the glacier as it flows to the ocean (flow is from top left to bottom right). This agrees with previous results I've obtained using other models. The bad version doesn't make a whole lot of sense. I've used a substantial amount of regularization so I doubt we're running up against ill-posedness of inverse problems.

[kangerdlugssuaq-bad.pdf](https://github.com/firedrakeproject/firedrake/files/13998876/kangerdlugssuaq-bad.pdf)
[kangerdlugssuaq-good.pdf](https://github.com/firedrakeproject/firedrake/files/13998877/kangerdlugssuaq-good.pdf)

**Comment by ksagiyam** [comment]
Vertex-only mesh now reorder vertices (cells) so that those in the neighbourhood will carry similar local numbers. So pointwise assignments must be amended. In `kangerdlugssuaq-test/initialize.py`, if you change:
```
u_o.dat.data[:] = velocity_data["vx"][indices[:, 1], indices[:, 0]]
v_o.dat.data[:] = velocity_data["vy"][indices[:, 1], indices[:, 0]]
σ_x.dat.data[:] = velocity_data["ex"][indices[:, 1], indices[:, 0]]
σ_y.dat.data[:] = velocity_data["ey"][indices[:, 1], indices[:, 0]]
```
to:
```
perm = point_set.topology._dm_renumbering.indices[:point_set.cell_set.size]
u_o.dat.data[:] = velocity_data["vx"][indices[:, 1], indices[:, 0]][perm]
v_o.dat.data[:] = velocity_data["vy"][indices[:, 1], indices[:, 0]][perm]
σ_x.dat.data[:] = velocity_data["ex"][indices[:, 1], indices[:, 0]][perm]
σ_y.dat.data[:] = velocity_data["ey"][indices[:, 1], indices[:, 0]][perm]
```
does it fix your problem?

**Comment by danshapero** [comment]
Yes that fixed it, thanks so much Koki! I notice that this has to use the `_dm_renumbering` attribute, is there another way to do the same thing that only uses the public API?

**Comment by ksagiyam** [comment]
The following should work and is probably better as it works in parallel. I think we could add this as a method of `Function` just for functions on VOMs.
```
from mpi4py.util.dtlib import from_numpy_dtype
from pyop2.mpi import MPI


def assign_point_data(self, point_data):
    dof_array = self.dat.data
    assert len(point_data.shape) == 1 and len(dof_array.shape) == 1
    assert dof_array.dtype == point_data.dtype
    unit = from_numpy_dtype(dof_array.dtype)
    sf = self.function_space().mesh().topology.input_ordering_sf
    sf.bcastBegin(unit, point_data, dof_array, MPI.REPLACE)
    sf.bcastEnd(unit, point_data, dof_array, MPI.REPLACE)


assign_point_data(u_o, velocity_data["vx"][indices[:, 1], indices[:, 0]])
assign_point_data(v_o, velocity_data["vy"][indices[:, 1], indices[:, 0]])
assign_point_data(σ_x, velocity_data["ex"][indices[:, 1], indices[:, 0]])
assign_point_data(σ_y, velocity_data["ey"][indices[:, 1], indices[:, 0]])
```

**Comment by dham** [comment]
I'm confused. Isn't this what the input ordering VOM is for? Why do we need a second way of doing this?

**Comment by ksagiyam** [comment]
That is right.
```
mesh_input = mesh.input_ordering
V_input = FunctionSpace(mesh_input, "DG", 0)
u_o_input = Function(V_input)
u_o_input.dat.data[:] = velocity_data["vx"][indices[:, 1], indices[:, 0]]
u_o.interpolate(u_o_input)
...
```
will do.

**Comment by danshapero** [comment]
Ok, the last solution makes sense -- thanks for clearing this up.
