### ISSUE TITLE
Function assigning a Cofunction

### ISSUE THREAD

**Issue by Ig-dolci** [firedrakeproject/firedrake#3345]
### Description:
In the context of a UFL constraint problem, specifically in the example from `pyadjoint` (located [here](https://github.com/dolfin-adjoint/pyadjoint/blob/master/examples/stokes-topology/stokes-topology-rol-firedrake.py)), there is an issue related to the computation of the Jacobian adjoint action. This error arises when executing the `Function.assign` on a `Cofunction`, as seen at [this line](https://github.com/firedrakeproject/firedrake/blob/master/firedrake/adjoint/ufl_constraints.py#L100).

### Error:
The assignment operation (`Function.assign`) results in the following error:

```
 File "/home/firedrake/firedrake/src/firedrake/firedrake/assign.py", line 255, in _weighted_coefficients
    return map_expr_dag(self._coefficient_collector, self._expression)
  File "/home/firedrake/firedrake/src/ufl/ufl/corealg/map_dag.py", line 34, in map_expr_dag
    result, = map_expr_dags(function, [expression], compress=compress,
  File "/home/firedrake/firedrake/src/ufl/ufl/corealg/map_dag.py", line 100, in map_expr_dags
    r = handlers[v._ufl_typecode_](v, *[vcache[u] for u in v.ufl_operands])
  File "/home/firedrake/firedrake/src/ufl/ufl/corealg/multifunction.py", line 99, in undefined
    raise ValueError(f"No handler defined for {o._ufl_class_.__name__}.")
AttributeError: 'Cofunction' object has no attribute '_ufl_class_'
```

### Steps to Reproduce:
1. Execute the [stokes-topology-rol-firedrake.py](https://github.com/dolfin-adjoint/pyadjoint/blob/master/examples/stokes-topology/stokes-topology-rol-firedrake.py) example from `pyadjoint`.
2. Observe the error mentioned above during the computation of the Jacobian adjoint action.

**Comment by nbouziani** [comment]
> It looks to me like result ([here](https://github.com/firedrakeproject/firedrake/blob/master/firedrake/adjoint/ufl_constraints.py#L85)) should be a Cofunction instead of a Function.

Yes exactly, you cannot assign a `Cofunction` to a `Function`.
