### ISSUE TITLE
BUG: Errors checkpointing extruded mesh

### ISSUE THREAD

**Issue by JDBetteridge** [firedrakeproject/firedrake#3375]
**Describe the bug**
Errors are raised when changing distribution parameters of the mesh. Behaviour WRT these parameters is odd.

```python
from firedrake import *

distribution_parameters = None
# 1 distribution_parameters = {}
# 3 distribution_parameters = {"partitioner_type": "ptscotch"}
mesh = UnitIntervalMesh(2, name="Simon", distribution_parameters=distribution_parameters)
emesh = ExtrudedMesh(mesh, layers=2, name="Tim")
V = FunctionSpace(emesh, "Lagrange", 1)
f = Function(V, name="Betty").assign(3.14)

with CheckpointFile("uim.h5", "w") as cf:
    cf.save_function(f)
    
# 2 distribution_parameters = {"partitioner_type": "ptscotch"}
with CheckpointFile("uim.h5", "r") as cf:
    restored_mesh = cf.load_mesh("Tim", distribution_parameters=distribution_parameters)
    restored_function = cf.load_function(restored_mesh, "Betty")
 
with CheckpointFile("uim.h5", "w") as cf:
    cf.save_function(restored_function)
    
with CheckpointFile("uim.h5", "r") as cf:
    another_restored_mesh = cf.load_mesh("Tim", distribution_parameters=distribution_parameters)
    
print("DONE")
```

**Steps to Reproduce**
1. Run code snipped above in serial, everything runs fine/
2. Uncomment `# 1` and run:
```
RuntimeError: Can only save one permutation: found firedrake_default_False in file, but trying to save firedrake_default_True
```
3. Comment `# 1` and uncomment `# 2` and run on 2 MPI ranks:
```
RuntimeError: Can only save one distribution: found firedrake_default_2_True_chaco_(FACET,1) in file, but trying to save firedrake_default_2_True_ptscotch_(FACET,1)
RuntimeError: Can only save one distribution: found firedrake_default_2_True_chaco_(FACET,1) in file, but trying to save firedrake_default_2_True_ptscotch_(FACET,1)
```
4. Uncomment `# 2` and `# 3` and run on 2 MPI ranks:
```
RuntimeError: Can only save one distribution: found ptscotch in file, but trying to save firedrake_default_2_True_ptscotch_(FACET,1)
RuntimeError: Can only save one distribution: found ptscotch in file, but trying to save firedrake_default_2_True_ptscotch_(FACET,1)
```

**Expected behavior**
I'm not sure what should and shouldn't work here! If saving on `n` and loading on `m` processors is implemented, why is the checkpoint dependent on the partitioner?

**Error message**
See above

**Environment:**
Arch Linux, Python 3.11, latest Firedrake.

**Additional Info**
I'm confused as to how this should work and since this is used in tests (which are failing on my other branches) I would really like a fix! See https://github.com/firedrakeproject/firedrake/blob/master/tests/output/test_io_function.py#L572 for example

**Comment by ksagiyam** [comment]
Given that our current implementation of saving/loading meshes and functions strongly relies on global entity numbers, saving the loaded mesh back to the same file is not supported (unless we rename the mesh) as entities of the loaded mesh in general carry different global entity numbers from those of the saved mesh. This will be fixed once we make changes in DMPlex so that global entity numbers are preserved upon save-load (and, more generally, upon distribution/overlap-addition/migration).

See also https://github.com/firedrakeproject/firedrake/issues/2524.

**Comment by JDBetteridge** [comment]
Should we maybe stop doing this in our tests, if that is the case?

**Comment by JDBetteridge** [comment]
I think https://github.com/firedrakeproject/firedrake/pull/3378 fixed this specific bug anyway, closing.
