### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by volpatto** [firedrakeproject/firedrake#3380]
Can you please create a Zenodo release for my upcoming publication:

### Supporting Material: Hybrid and Discontinuous Finite Element Methods for porous media flow problems

[firedrake.json](https://github.com/firedrakeproject/firedrake/files/14123453/firedrake.json)

**Comment by ksagiyam** [comment]
Created Zenodo meta-release.
Tag is `Firedrake_20240201.0`
DOI is 10.5281/zenodo.10605321
Zenodo URL is https://zenodo.org/record/10605321
BibTeX

```bibtex
@misc{zenodo/Firedrake-20240201.0,
 key   = {zenodo/Firedrake-20240201.0},
 title = {{Software used in `Supporting Material: Hybrid and Discontinuous Finite Element
Methods for porous media flow problems'}},
 year  = {2024},
 month = {feb},
 doi   = {10.5281/zenodo.10605321},
 url   = {https://doi.org/10.5281/zenodo.10605321},
}

```
Thanks!
