### ISSUE TITLE
BUG: Assembling a `Cofunction` returns the `Cofunction` rather than a supplied `tensor`

### ISSUE THREAD

**Issue by jrmaddison** [firedrakeproject/firedrake#3407]
**Describe the bug**
The usage `assemble(b, tensor=tensor)` with `b` and `tensor` `Cofunction`s returns `b` rather than `tensor`.

**Steps to Reproduce**
```
from firedrake import *
import ufl

mesh = UnitIntervalMesh(1)
space = FunctionSpace(mesh, "Discontinuous Lagrange", 0)
test = TestFunction(space)

form = ufl.conj(test) * dx
tensor = Cofunction(space.dual())

b0 = assemble(form)
b1 = assemble(b0, tensor=tensor)

assert b0 is b1  # Passes
assert b1 is tensor  # Fails
```

**Expected behavior**
The return value should be `tensor`.

**Additional Info**
Can lead to subtle bugs if the return value is modified.

**Comment by connorjward** [comment]
@nbouziani can you tackle this?

**Comment by ksagiyam** [comment]
Opened a PR https://github.com/firedrakeproject/firedrake/pull/3408.

**Comment by nbouziani** [comment]
Thanks for spotting this. Note that passing `tensor` to `assemble` specifically means putting the result of the assembly into the tensor, so in practice you can just write:

```
assemble(b0, tensor=tensor)
```
