### ISSUE TITLE
INSTALL:  Can't install on Linux server without apt-get

### ISSUE THREAD

**Issue by mmorier-etu** [firedrakeproject/firedrake#3445]
Hi, I need to install firedrake on my server. I succeeded on my personal computer but not on the server.
On the server, I can't use sudo, or have apt-get. 
So I specified it when running, but then I have an error when it install numpy==1.24, wich I don't understand why because it can be install manually.

To reproduce: 
curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
python3 firedrake-install --no-package-manager

It then create a venv "firedrake", clone the git with https, and then tries to install numpy==1.24 but failed :

```(base) [mmorier@nef-devel2 Firedrake]$ python3 firedrake-install --no-package-manager
/home/mmorier/code/Firedrake/firedrake-install:20: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources.extern.packaging.version import Version, InvalidVersion
Running firedrake-install --no-package-manager
apt-get not found or disabled. Proceeding on the rash assumption that your compiled dependencies are in place.
Please use the --show-dependencies for more information.
Creating firedrake venv in '/home/mmorier/code/Firedrake/firedrake'.
BLAS config is {}
Configuration saved to /home/mmorier/code/Firedrake/firedrake/.configuration.json
Cloning firedrake

Failed to clone firedrake using ssh, falling back to https.
Successfully cloned repository firedrake.
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Creating firedrake-update script.
Installing numpy using setuptools==59.2.0 and wheel==0.37.0 and Cython==0.29.36
Installing numpy==1.24 due to performance regression
Traceback (most recent call last):
  File "/home/mmorier/code/Firedrake/firedrake-install", line 1835, in <module>
    run_pip_install(["numpy==1.24"])
  File "/home/mmorier/code/Firedrake/firedrake-install", line 997, in run_pip_install
    check_call(pipinstall + pipargs)
  File "/home/mmorier/code/Firedrake/firedrake-install", line 674, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmorier/miniconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmorier/miniconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/mmorier/code/Firedrake/firedrake/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,numpy', '-vvv', 'numpy==1.24']' returned non-zero exit status 1.

Environment:
- Linux nef-devel2 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - Python 3.11.5

I can add the firedrake-install.log if needed but it is really heavy.

Thanks for the help

**Comment by connorjward** [comment]
The `firedrake-install.log` is always helpful, but here it looks like you are using a miniconda python, which [we do not support](https://www.firedrakeproject.org/download.html#system-anti-requirements). Can you attempt another install with a different Python?

**Comment by mmorier-etu** [comment]
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/14558758/firedrake-install.log)

Here is the log file. Yes I am, but I am unable do otherwise because I am on a shared server that uses python2.7, and I only can create virtual environments with python3.6, which is not supported by firedrake.

**Comment by dham** [comment]
That logfile seems to only have 1 line in it. Something must have gone wrong very early. Python 3.6 is not only not supported by Firedrake, it's not supported by Python. It reached end of life a couple of years ago. It sounds like this server is full of very out of date software. I suspect you're going to hit a lot of issues using this machine.

**Comment by Ig-dolci** [comment]
@mmorier-etu Did you sort out this issue?
