### ISSUE TITLE
DOCS: Imports in introductory tutorials not up to date (imports deprecated `VTKFile`)

### ISSUE THREAD

**Issue by p479h** [firedrakeproject/firedrake#3451]
These examples:
- [ear wave equation with optional mass lumping.](https://www.firedrakeproject.org/demos/linear_wave_equation.py.html)
- [A basic Helmholtz equation.](https://www.firedrakeproject.org/demos/helmholtz.py.html)
- [The Burgers equation, a non-linear, unsteady example.](https://www.firedrakeproject.org/demos/burgers.py.html)
- [A mixed formulation of the Poisson equation.](https://www.firedrakeproject.org/demos/poisson_mixed.py.html)

Have this line:
`from firedrake.output import VTKFile`
which does not work since I last updated the library (2 weeks ago).

I believe the solution is to simply remove this line and replace instances of `VTKFile` with `File`.

**Comment by connorjward** [comment]
We changed `File` to `VTKFile` [last week](https://github.com/firedrakeproject/firedrake/pull/3324). You should update your Firedrake and then hopefully things should work for you.
