### ISSUE TITLE
INSTALL:  Install firedrake on an HPC with Centos 7.8 Machines. Using Singularity please help.

### ISSUE THREAD

**Issue by robertosussex** [firedrakeproject/firedrake#3467]
Hi guys,

We need to install Firedrake on our Azure HPC (typycally with Centos OS)
I have been told that the Spack option is not maintained. The firedrake-install also does not work properly.

I have been suggested that we should use Singularity and containers.

Can you give me some help on how we can do that?

Kind regards
Roberto Scipioni
University of Bath Research Computing

**Comment by robertosussex** [comment]
https://github.com/firedrakeproject/firedrake/wiki/singularity

Thank you!
It is a convoluted process that would require using a non HPC machine as we do not have (nor we would want to have ) Docker installed on the HPC.

Thank you for the information
Kind regards

**Comment by JHopeCollins** [comment]
Depending what MPI you have installed on the HPC machine you may be able to just use the Docker containers built by the Firedrake CI. In this case you would only need Singularity, not Docker.

**Comment by connorjward** [comment]
Closing as this appears to have been answered.
