### ISSUE TITLE
Passing block information into ASMStarPC and friends

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#3474]
I would like to try a Schur complement solver in my patches, something like

```
    my_params = {                                                                                                                 
        'snes_converged_reason': None,                                          
        'pc_type': "python",                                                    
        'pc_python_type': 'firedrake.ASMStarPC',                                
        'pc_star_construct_codim': 0,                   
        'pc_star_sub_sub' : {                                                   
            "pc_type": "fieldsplit",                                            
            "pc_fieldsplit_type":"schur",                                       
            "pc_fieldsplit_schur_fact_type":"full",                             
            "fieldsplit_detect_saddle_point": None,                             
            "pc_fieldsplit_schur_precondition":"selfp",                         
            "fieldsplit_Pressure_mat_schur_complement_ainv_type":"full",        
            "fieldsplit_Pressure_ksp_type":'preonly',                           
            "fieldsplit_Pressure_pc_type":"lu",                                 
            "fieldsplit_Vv_ksp_type":"preonly",                                 
            "fieldsplit_Vv_pc_type":"lu",                                       
            "pc_factor_mat_solver_type": "mumps",                               
            }                                                                   
    } 
```

However, this provokes the message

```
[0] Petsc has generated inconsistent data
[0] Unhandled case, must have at least two fields, not 1
```

What would be required to pass the fieldsplit down into the ASMStarPC level?

**Comment by pbrubeck** [comment]
Is the new default ordering introduced by https://github.com/firedrakeproject/firedrake/pull/3429 still giving issues for saddle point patch submatrices? How is this different from a direct solve? Why do you need to construct such sophisticated solver on each patch?

**Comment by colinjcotter** [comment]
My patches are full column patches - we use ASMStarPC as a mixed system line smoother on extruded meshes. So I would like to reduce the system to see if it can speed up the solve.

**Comment by pbrubeck** [comment]
I think the options you have are not entirely right, you should use `-pc_fieldsplit_detect_saddle_point` https://petsc.org/main/manualpages/PC/PCFieldSplitSetDetectSaddlePoint/

**Comment by pbrubeck** [comment]
Elimination of one field via static condensation is equivalent to LU/Cholesky in the (u,p) ordering (which we now ensure)

**Comment by colinjcotter** [comment]
Right! That’s true. I wasn’t up to date with this ordering.

**Comment by pbrubeck** [comment]
Maybe try with cholmod/umfpack I think those should be the most performant for a medium-sized sequential matrix. `-pc_type cholesky  -pc_factor_mat_solver_type cholmod` should use half of the memory/flops compared to LU and works for indefinite symmetric problems by doing LDLT.

**Comment by pbrubeck** [comment]
Also, for ASMStarPC one should specify `pc_star_construct_dim`, not `codim` that's only for Vanka and Linesmooth
