### ISSUE TITLE
INSTALL: Installing firedrake on MacOS fails (petsc's compilation of chaco fails) 

### ISSUE THREAD

**Issue by sghelichkhani** [firedrakeproject/firedrake#3485]
I was wondering if anyone has seen this issue, only happening on MacOS. 
Installing firedrake on a MacOS, petsc fails to install.  Config files are: 

[configure.log](https://github.com/firedrakeproject/firedrake/files/14831678/configure.log)
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/14831801/firedrake-install.log)

The main issue seems to occur when executing: 
`/Users/sghelichkhani/Workplace/firedrake-2024-04-02/src/petsc/default/bin/mpicc -c -Imain -Wno-implicit-function-declaration -g -O3 -std=c99 -Wno-implicit-function-declaration -fno-common -o input/check_input.o input/check_input.c` which generates: 
```
input/check_input.c:472:66: error: parameter 'local_method' was not declared, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
static int check_assignment(assignment, nvtxs, nsets_tot, ndims, local_method)
                                                                 ^
input/check_input.c:472:59: error: parameter 'ndims' was not declared, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
static int check_assignment(assignment, nvtxs, nsets_tot, ndims, local_method)
```
Obviously changing`-std=c99` to `-std=c89` would fix the issue. But I that seems to be overwritten with C99 during confugration!

**Compiler**:
```
@Sias-MacBook-Pro.local:  /Users/sghelichkhani/Workplace/firedrake-2024-04-02/src/petsc/default/bin/mpicc --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
``` 
```
@Sias-MacBook-Pro.local: python3 --version
Python 3.11.7
```

**Comment by connorjward** [comment]
Other users [have encountered this](https://github.com/firedrakeproject/firedrake/discussions/3465). Currently we think our best workaround until PETSc fix this upstream is to make a couple of modifications to the `firedrake-install` script (described [here](https://github.com/firedrakeproject/firedrake/discussions/3465#discussioncomment-8971299)).

**Comment by JDBetteridge** [comment]
We no longer install Chaco by default. Could you retry the install and open a fresh issue if you still encounter problems installing?
