### ISSUE TITLE
INSTALL: CalledProcessError on Apple M2 Pro chip

### ISSUE THREAD

**Issue by baigm11** [firedrakeproject/firedrake#3501]
**Describe the error**
Hi. I'm installing Firedrake with Homebrew Python3.11 and get a CalledProcessError when it's installing petsc.

**Steps to Reproduce**
I used `python3.11 firedrake-install --with-blas=download` for the installation.

**Error message**
/Users/baigm/firedrake-install:20: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources.extern.packaging.version import Version, InvalidVersion
Running firedrake-install --with-blas=download
Installing command line tools...
Checking brew doctor...
Installing required packages via homebrew...
Required package 'gcc' is already installed via Homebrew.
Required package 'autoconf' is already installed via Homebrew.
Required package 'make' is already installed via Homebrew.
Required package 'automake' is already installed via Homebrew.
Required package 'cmake' is already installed via Homebrew.
Required package 'libtool' is already installed via Homebrew.
Required package 'boost' is already installed via Homebrew.
Creating firedrake venv in '/Users/baigm/firedrake'.
BLAS config is {'BLAS': '/Users/baigm/firedrake/src/petsc/default', 'OPENBLAS': '/Users/baigm/firedrake/src/petsc/default', 'LDFLAGS': '-L/opt/homebrew/opt/gcc/lib/gcc/13'}
Configuration saved to /Users/baigm/firedrake/.configuration.json
Cloning firedrake

Successfully cloned repository firedrake
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Creating firedrake-update script.
Installing numpy using setuptools==59.2.0 and wheel==0.37.0 and Cython==0.29.36
Installing numpy==1.24 due to performance regression
Updating setuptools and wheel to latest versions
Pip installing VTK to venv
Cloning the dependencies of firedrake
Cloning ufl

Successfully cloned repository ufl
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning fiat

Successfully cloned repository fiat
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning FInAT

Successfully cloned repository FInAT
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning tsfc

Successfully cloned repository tsfc
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning PyOP2

Successfully cloned repository PyOP2
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning pyadjoint

Successfully cloned repository pyadjoint
Checking out branch master
Successfully checked out branch master
Updating submodules.
Successfully updated submodules.
Cloning petsc

Successfully cloned repository petsc
Checking out branch firedrake
Successfully checked out branch firedrake
Updating submodules.
Successfully updated submodules.
Cloning pytest-mpi

Successfully cloned repository pytest-mpi
Checking out branch main
Successfully checked out branch main
Updating submodules.
Successfully updated submodules.
Cloning the dependencies of PyOP2
Cloning loopy

Successfully cloned repository loopy
Checking out branch main
Successfully checked out branch main
Updating submodules.
Successfully updated submodules.
Installing petsc/
Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "/Users/baigm/firedrake-install", line 1866, in <module>
    install("petsc/")
  File "/Users/baigm/firedrake-install", line 1061, in install
    build_and_install_petsc()
  File "/Users/baigm/firedrake-install", line 1173, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "/Users/baigm/firedrake-install", line 674, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/baigm/firedrake/bin/python', './configure', 'PETSC_DIR=/Users/baigm/firedrake/src/petsc', 'PETSC_ARCH=default', '--with-fortran-bindings=0', '--download-openblas', '--download-hwloc-configure-arguments=--disable-opencl', '--download-bison', '--download-hdf5', '--download-hwloc', '--download-ptscotch', '--download-suitesparse', '--with-zlib', '--download-pnetcdf', '--CFLAGS=-Wno-implicit-function-declaration', '--download-mpich-configure-arguments=--disable-opencl', '--with-c2html=0', '--download-metis', '--download-scalapack', '--download-superlu_dist', '--download-mpich', "--download-openblas-make-options='USE_THREAD=0 USE_LOCKING=1 USE_OPENMP=0'", '--download-hypre', '--download-mumps', '--with-shared-libraries=1', '--download-netcdf', '--download-pastix', '--with-debugging=0', '--with-x=0', '--download-chaco']' returned non-zero exit status 1.

Install log saved in /Users/baigm/firedrake-install.log

Here is the [firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/14965314/firedrake-install.log)

**Environment:**
 - OS: MacOS 14.1, Apple M2 Pro chip.
 - Python version: 3.11.
 - Any relevant environment variables or modifications: no.

**Comment by connorjward** [comment]
What happens if you omit the `--with-blas` flag? Also you might want to update your command line tools to 15.2 (15.3 currently has build issues but 15.2 seems to work well for most users).

**Comment by baigm11** [comment]
I got Firedrake well installed on MacOS 14.4.1 and XCode 3.15 after I reset my Mac and used the useful script by  @lrtfm to avoid chaco error. Besides, I'd like to report that I got a pragmatic.git error which was fixed by using `brew unlink open-mpi`. XCode 3.15 required me to install "m4" as well.
