### ISSUE TITLE
INSTALL: trouble installing firedrake on mac

### ISSUE THREAD

**Issue by maglaser** [firedrakeproject/firedrake#3541]
UNABLE to CONFIGURE with GIVEN OPTIONS, first with MPICH then with CHACO

I spent some hours today trying to install firedrake on my macbook pro running macOS 14.4.1. I installed python 3.11 using homebrew and then ran the command:

python3.11 firedrake-install

This failed when it got to MPICH, with the following message:

 ``` Trying to download
  https://web.cels.anl.gov/projects/petsc/download/externalpackages/mpich-4.2.0-p1.tar.gz
  for MPICH
=============================================================================================
=============================================================================================
                  Running configure on MPICH; this may take several minutes
=============================================================================================
=============================================================================================
                     Running make on MPICH; this may take several minutes
=============================================================================================
=============================================================================================
                 Running make install on MPICH; this may take several minutes
=============================================================================================

*********************************************************************************************
           UNABLE to CONFIGURE with GIVEN OPTIONS (see configure.log for details):
---------------------------------------------------------------------------------------------
   Exhausted all shared linker guesses. Could not determine how to create a shared library!
*********************************************************************************************


2024-04-29 19:24:04,858 DEBUG  Popping path '/Users/glaser/src/Firedrake/firedrake/src/petsc'
2024-04-29 19:24:04,858 DEBUG  New path '/Users/glaser/src/Firedrake/firedrake/src'
2024-04-29 19:24:04,864 INFO   

Install log saved in /Users/glaser/src/Firedrake/firedrake-install.log```

Here is the log file:

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/15156648/firedrake-install.log)

and configure.log from /Users/glaser/src/Firedrake/firedrake/src/petsc:

[configure.log](https://github.com/firedrakeproject/firedrake/files/15156656/configure.log)

Following some advice I found on the firedrake install pages, I then tried to use the mac OS mpi installation:

python3.11 firedrake-install --mpiexec=mpiexec --mpicc=mpicc --mpicxx=mpicxx --mpif90=mpif90

This seemed to get me further, but now I encounter a new error message about CHACO:

```            Trying to download https://bitbucket.org/petsc/pkg-chaco.git for CHACO
=============================================================================================
=============================================================================================
                Compiling and installing chaco; this may take several minutes
=============================================================================================

*********************************************************************************************
           UNABLE to CONFIGURE with GIVEN OPTIONS (see configure.log for details):
---------------------------------------------------------------------------------------------
  Error running make on CHACO: Could not execute "['make clean', 'make', '/usr/bin/ar cr
  libchaco.a `ls */*.o |grep -v main/main.o`', '/usr/bin/ranlib -c libchaco.a', 'mkdir -p
  /Users/glaser/src/Firedrake/firedrake/src/petsc/default/lib', 'cp libchaco.a
  /Users/glaser/src/Firedrake/firedrake/src/petsc/default/lib']":
  rm -f */*.o ../exec/core
  mpicc -c -Imain -Wno-implicit-function-declaration -fPIC -g -O3
  -Wno-implicit-function-declaration -fno-common -o main/user_params.o main/user_params.c
  mpicc -c -Imain -Wno-implicit-function-declaration -fPIC -g -O3 -Wno-implicit-f
  .... more output .....
  PIC -g -O3 -Wno-implicit-function-declaration -fno-common -o input/input_assign.o
  input/input_assign.c
  mpicc -c -Imain -Wno-implicit-function-declaration -fPIC -g -O3
  -Wno-implicit-function-declaration -fno-common -o input/check_input.o
  input/check_input.cmain/interface.c:80:13: warning: passing arguments to 'read_params'
  without a prototype is deprecated in all versions of C and is not supported in C2x
  [-Wdeprecated-non-prototype]
  read_params(params_file);
  ^
  main/interface.c:108:
  .... more error .....
  a zero-parameter prototype in C2x, conflicting with a subsequent definition
  [-Wdeprecated-non-prototype]
  static int check_params(), check_assignment();
  ^
  8 warnings and 2 errors generated.
  make: *** [input/check_input.o] Error 1
*********************************************************************************************


2024-04-29 19:48:37,509 DEBUG  Popping path '/Users/glaser/src/Firedrake/firedrake/src/petsc'
2024-04-29 19:48:37,509 DEBUG  New path '/Users/glaser/src/Firedrake/firedrake/src'
2024-04-29 19:48:37,512 INFO   

Install log saved in /Users/glaser/src/Firedrake/firedrake-install.log```

Here are the log files:

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/15156873/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/15156880/configure.log)

I don't know what to do next, so any advice would be most appreciated.

**Comment by maglaser** [comment]
Thanks so much, that got me further! But I now encounter the UNABLE to CONFIGURE with GIVEN OPTIONS error message when the install tries to make PaStiX. Here are the log files:

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/15166442/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/15166452/configure.log)

Thanks again for your help.

**Comment by Ig-dolci** [comment]
Can you please try to install firedrake using `MPICH` built by PETSc? Just run `python3 firedrake-install`.

**Comment by maglaser** [comment]
Thanks, that helped, and now petsc appears to have installed successfully. However, the installation of h5py fails, with a "Failed building wheel for h5py" error. Here is the logfile:

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/15177627/firedrake-install.log)

As far as I can tell from the logfile, this may have to do with the Numpy installation, but I think everything has been installed using homebrew.

**Comment by Ig-dolci** [comment]
It looks like you've encountered several `homebrew` warnings. To address them, let's take a few steps:

1. Begin by running `brew update` and `brew upgrade`.

2. Make sure you are using Python installed via Homebrew. For example, you can typically find Homebrew's Python installation at `/opt/homebrew/bin/python3.11`.

**Comment by maglaser** [comment]
I updated and upgraded brew, but that made no difference (pretty sure brew was already up to date).

$(brew --prefix) is set to /usr/local, so the brew python installation is at /usr/local/bin/python3.11.

Just to be sure which python I was using, I tried installing using /usr/local/bin/python3.11 firedrake-install, but the result was the same, with "Failed building wheel for h5py" error.

I'll keep looking into those homebrew warnings.

**Comment by maglaser** [comment]
I dealt with some of the homebrew warnings, but was unable to resolve the h5py issue. Here is the logfile:

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/15204823/firedrake-install.log)

I'm not quite sure what to try next. Maybe install h5py manually somehow?

**Comment by Ig-dolci** [comment]
In your recent firedrake-install.log, I noticed you have set a local `HDF5_DIR=/usr/local` in the terminal. Can you please unset it or try installing Firedrake in a fresh terminal session? Additionally, there are still several warnings from Homebrew.

**Comment by maglaser** [comment]
I've unset HDF5_DIR and have taken measure to eliminate the Homebrew warnings, but the installation still fails. Here is the logfile:

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/15303595/firedrake-install.log)

The installer now throws an error that seems to relate to not finding /usr/local/lib/libmkl_rt.dylib. Probably not coincidentally, this is one of the dynamic libraries that I removed to get rid of the Homebrew warnings. So it seems that I may have to re-install the mkl libraries, is that correct? If so, what is the recommended procedure?

**Comment by Ig-dolci** [comment]
@connorjward any idea to fix this hdf5 error?

**Comment by connorjward** [comment]
I have an idea as to what might be going wrong. Looking through the logs to the point when numpy is installed I see the following:
```
Using cached wheel link: file:///Users/glaser/Library/Caches/pip/wheels/77/4f/28/1e1a45b8f7da14957b84ca35e7dee9398f27d2758f84c29808/numpy-1.24.0-cp311-cp311-macosx_14_0_x86_64.whl
Collecting numpy==1.24
  Using cached numpy-1.24.0-cp311-cp311-macosx_14_0_x86_64.whl
Created temporary directory: /private/var/folders/5l/bvg54gxx201dv_4syf5b_5jw0000gn/T/pip-unpack-ohdmy_jn
Installing collected packages: numpy
```
We then subsequently have linking issues where the numpy wheel is looking for MKL that no longer exists:
```
  Original error was: dlopen(/Users/glaser/src/Firedrake/firedrake/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libmkl_rt.dylib
    Referenced from: <12916B46-63FA-37F8-93D6-161D16D15D0A> /Users/glaser/src/Firedrake/firedrake/lib/python3.11/site-packages/numpy/core/_multiarray_umath.cpython-311-darwin.so
    Reason: tried: '/usr/local/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libmkl_rt.dylib' (no such file), '/usr/local/lib/libmkl_rt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libmkl_rt.dylib' (no such file)
```

My suspicion is that this is an artefact from an earlier failed build. Please can you delete the entries inside `/Users/glaser/Library/Caches/pip` and try again?

**Comment by maglaser** [comment]
Thanks so much for the suggestion... Firedrake now builds successfully!

Unfortunately, running the test suite with the command 

> pytest tests/regression/ -k "poisson_strong or stokes_mini or dg_advection"

 fails. I've included the output in this log file:
[test.log](https://github.com/firedrakeproject/firedrake/files/15315204/test.log)
I also get a "Python quit unexpectedly" popup window when I run this command.

Per the instructions on the Firedrake site, I added the following lines to /etc/hosts:

127.0.0.1       Matts-MBP-3.local
127.0.0.1       Matts-MBP-3

but this didn't change the behavior. Could the failure have something to do with MPI?

**Comment by connorjward** [comment]
> Thanks so much for the suggestion... Firedrake now builds successfully!
> 
> Unfortunately, running the test suite with the command
> 
> > pytest tests/regression/ -k "poisson_strong or stokes_mini or dg_advection"
> 
> fails. I've included the output in this log file: [test.log](https://github.com/firedrakeproject/firedrake/files/15315204/test.log) I also get a "Python quit unexpectedly" popup window when I run this command.
> 
> Per the instructions on the Firedrake site, I added the following lines to /etc/hosts:
> 
> 127.0.0.1 Matts-MBP-3.local 127.0.0.1 Matts-MBP-3
> 
> but this didn't change the behavior. Could the failure have something to do with MPI?

So Firedrake in serial seems to be correctly installed. I suspect that you're right and something is probably wrong with MPI. What do you get with (with the virtual environment activated) `which mpiexec` and `mpiexec -np 2 echo "testing"`?

**Comment by Ig-dolci** [comment]
We have a [PETSC issue](https://gitlab.com/petsc/petsc/-/issues/1569) causing errors in executing a Firedrake code on a Mac in parallel.

**Comment by maglaser** [comment]
I get the following, which seems normal?


(firedrake) Matts-MBP-3:firedrake glaser$ which mpiexec

/Users/glaser/src/Firedrake/firedrake/bin/mpiexec

(firedrake) Matts-MBP-3:firedrake glaser$ mpiexec -np 2 echo "testing"

testing

testing


From: Connor Ward ***@***.***>
Date: Wednesday, May 15, 2024 at 7:50 AM
To: firedrakeproject/firedrake ***@***.***>
Cc: Matthew A Glaser ***@***.***>, Author ***@***.***>
Subject: Re: [firedrakeproject/firedrake] INSTALL: trouble installing firedrake on mac (Issue #3541)
[External email - use caution]


Thanks so much for the suggestion... Firedrake now builds successfully!

Unfortunately, running the test suite with the command

pytest tests/regression/ -k "poisson_strong or stokes_mini or dg_advection"

fails. I've included the output in this log file: test.log<https://github.com/firedrakeproject/firedrake/files/15315204/test.log> I also get a "Python quit unexpectedly" popup window when I run this command.

Per the instructions on the Firedrake site, I added the following lines to /etc/hosts:

127.0.0.1 Matts-MBP-3.local 127.0.0.1 Matts-MBP-3

but this didn't change the behavior. Could the failure have something to do with MPI?

So Firedrake in serial seems to be correctly installed. I suspect that you're right and something is probably wrong with MPI. What do you get with (with the virtual environment activated) which mpiexec and mpiexec -np 2 echo "testing"?

**Comment by connorjward** [comment]
OK. Those are correct. I think @Ig-dolci may well be correct that you're hitting a known PETSc issue with MUMPS. It seems like possible solutions are:
- Use SuperLU_DIST instead of MUMPS for direct solves in parallel. If you don't mind much what direct solver you use or don't want to run Firedrake in parallel then this is definitely the easiest option.
- Downgrade your Xcode to 15.1 and reinstall

Eventually I expect this issue will go away with upgrades to either PETSc or Xcode.

**Comment by maglaser** [comment]
Okay, I tried Xcode 15.1 for the install but got the same behavior. I guess for now I'll just do code development in serial mode and worry about MPI later when I'm ready to do large-scale production runs.

Thanks so much for all of your help and patience!
