### ISSUE TITLE
BUG: AD computed derivative with respect to a `Function` is a `Function`

### ISSUE THREAD

**Issue by jrmaddison** [firedrakeproject/firedrake#3551]
**Describe the bug**
The derivative of a functional with respect to a `Function` control is returned as a `Function`.

**Steps to Reproduce**
```
from firedrake import *
from firedrake.adjoint import *

mesh = UnitIntervalMesh(1)
X = SpatialCoordinate(mesh)
space = FunctionSpace(mesh, "Lagrange", 1)
test = TestFunction(space)
u = Function(space).interpolate(X[0])

continue_annotation()
J = assemble((u ** 2) * dx)
pause_annotation()

rf = ReducedFunctional(J, Control(u))
dJ = rf.derivative()
dJ_ref = assemble(2 * u * test * dx)
print(f"{abs(dJ.dat.data_ro - dJ_ref.dat.data_ro).max()=}")
print(f"{type(dJ)=}")
```
which displays
```
abs(dJ.dat.data_ro - dJ_ref.dat.data_ro).max()=0.0
type(dJ)=<class 'firedrake.function.Function'>
```

**Expected behavior**
The result should be a `Cofunction`.

**Additional Info**
Encountered while attempting to use `TAO.setGradientNorm` for optimization using TAO.

**Comment by dham** [comment]
I think we're doing what the pyadjoint API tells us to do. You can plausibly claim that the pyadjoint API is not well throught through, because having `ReducedFunctional.derivative` return a gradient, which is what it requires, is dumb. I have a lot of sympathy with that. However that API has actual users, so any change requires serious work.

**Comment by jrmaddison** [comment]
It seems to be standard for the gradient to be defined in the primal space (although gradient covectors are used in differential geometry). However for the derivative it should definitely be in the dual space. The workaround is easy, by accessing the `adj_vector` attribute after running the adjoint.

Since this isn't exactly a bug, it can be closed?

**Comment by Ig-dolci** [comment]
I believe we can close this issue. Executing `ReducedFunctional.derivative(options={"riesz_representation": self.inner_product})` results in a `Cofunction`. Feel free to reopen the issue if anyone has valid arguments against its closure.

**Comment by dham** [comment]
> I believe we can close this issue. Executing `ReducedFunctional.derivative(options={"riesz_representation": self.inner_product})` results in a `Cofunction`. Feel free to reopen the issue if anyone has valid arguments against its closure.

Don't you mean: `ReducedFunctional.derivative(options={"riesz_representation": None})`
