### ISSUE TITLE
Network Inpainting via Optimal Transport

### ISSUE THREAD

**Issue by enricofacca** [firedrakeproject/firedrake#3582]
Can you please create a Zenodo release for my upcoming publication:

### Network Inpainting via Optimal Transport

Attached the `firedrake.json` created by running
`firedrake-zenodo -t "Network Inpainting via Optimal Transport"`
[firedrake.json](https://github.com/firedrakeproject/firedrake/files/15400230/firedrake.json)

**Comment by ksagiyam** [comment]
Created Zenodo meta-release.
Tag is `Firedrake_20240522.0`
DOI is 10.5281/zenodo.11242360
Zenodo URL is https://zenodo.org/record/11242360
BibTeX

```bibtex
@misc{zenodo/Firedrake-20240522.0,
 key   = {zenodo/Firedrake-20240522.0},
 title = {{Software used in `Network Inpainting via Optimal Transport'}},
 year  = {2024},
 month = {may},
 doi   = {10.5281/zenodo.11242360},
 url   = {https://doi.org/10.5281/zenodo.11242360},
}

```
Thanks!
