### ISSUE TITLE
Install: Problems when installing Firedrake on Mac

### ISSUE THREAD

**Issue by qk11853** [firedrakeproject/firedrake#3613]
The following problem occurs when installing Firedrake on my Mac computer. How can I solve it?

<img width="690" alt="截屏2024-06-06 11 35 56" src="https://github.com/firedrakeproject/firedrake/assets/115483517/6bbc9395-646b-4953-bdec-ee1b71711446">

**Comment by colinjcotter** [comment]
Please can you attach the log file?

And please don’t such screenshots, they are hard to read and impossible to search or paste from.
