### ISSUE TITLE
INSTALL:Can't install Firedrake on Mac

### ISSUE THREAD

**Issue by qk11853** [firedrakeproject/firedrake#3614]
When I install Firedrake on a Mac, the following error occurs

Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "/Users/zhangqk/firedrake-install", line 1870, in <module>
    install("petsc/")
  File "/Users/zhangqk/firedrake-install", line 1064, in install
    build_and_install_petsc()
  File "/Users/zhangqk/firedrake-install", line 1176, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "/Users/zhangqk/firedrake-install", line 680, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/zhangqk/firedrake/bin/python', './configure', 'PETSC_DIR=/Users/zhangqk/firedrake/src/petsc', 'PETSC_ARCH=default', '--download-mpich', '--download-suitesparse', '--with-shared-libraries=1', '--with-fortran-bindings=0', '--download-pnetcdf', '--download-scalapack', '--with-x=0', '--download-hwloc-configure-arguments=--disable-opencl', '--CFLAGS=-Wno-implicit-function-declaration', '--download-openblas', '--LDFLAGS=-Wl,-ld_classic', '--with-c2html=0', '--download-ptscotch', '--download-mumps', '--download-hypre', '--download-netcdf', "--download-openblas-make-options='USE_THREAD=0 USE_LOCKING=1 USE_OPENMP=0'", '--download-mpich-configure-arguments=--disable-opencl', '--download-metis', '--download-bison', '--download-hdf5', '--download-superlu_dist', '--with-zlib', '--download-pastix', '--download-hwloc', '--with-debugging=0']' returned non-zero exit status 1.

Install log saved in /Users/zhangqk/firedrake-install.log

**Comment by colinjcotter** [comment]
please can you attach the log file

**Comment by qk11853** [comment]
Log files
[firedrake-install.log](https://github.com/user-attachments/files/15604551/firedrake-install.log)

**Comment by Ig-dolci** [comment]
You are using `/opt/anaconda3/bin/python3`, leading to failure in the firedrake installation. Can you please follow the instructions available [here](https://www.firedrakeproject.org/download.html) in the section **System Requirements**?

**Comment by qk11853** [comment]
> You are using `/opt/anaconda3/bin/python3`, leading to failure in the firedrake installation. Can you please follow the instructions available [here](https://www.firedrakeproject.org/download.html) in the section **System Requirements**?

I hadn't installed anaconda before, and this error occurred at that time

**Comment by Ig-dolci** [comment]
> > You are using `/opt/anaconda3/bin/python3`, leading to failure in the firedrake installation. Can you please follow the instructions available [here](https://www.firedrakeproject.org/download.html) in the section **System Requirements**?
> 
> I hadn't installed anaconda before, and this error occurred at that time

Sorry. I just updated my message. It is **System anti-requirements**.

**Comment by qk11853** [comment]
> > > You are using `/opt/anaconda3/bin/python3`, leading to failure in the firedrake installation. Can you please follow the instructions available [here](https://www.firedrakeproject.org/download.html) in the section **System Requirements**?
> > 
> > 
> > I hadn't installed anaconda before, and this error occurred at that time
> 
> Sorry. I just updated my message. It is **System anti-requirements**.
Do I need to remove anaconda?

**Comment by Ig-dolci** [comment]
You have the option 2:

_Modify your PATH environment variable to remove any traces of Anaconda, then install Firedrake. If you need Anaconda later, you can re-enable it with a shell script that will add those directories back onto your path._

I think you run the command `/opt/homebrew/bin/python3 firedrake-install` will work to install firedrake via homebrew python.
