### ISSUE TITLE
superconvergence

### ISSUE THREAD

**Issue by qk11853** [firedrakeproject/firedrake#3622]
from firedrake import *

nx = 4
mesh = UnitSquareMesh(nx, nx, diagonal="right")
Uspace = FunctionSpace(mesh, "CG", 2)
u = TrialFunction(Uspace)
v = TestFunction(Uspace)
n = FacetNormal(mesh)
x, y = SpatialCoordinate(mesh)

bcs = DirichletBC(Uspace, cos(pi * x) * sin(pi * y), (1, 2, 3, 4))

u_ex = Function(Uspace).interpolate(cos(pi * x) * sin(pi * y))
f = Function(Uspace).interpolate(2 * pi ** 2 * cos(pi * x) * sin(pi * y))

a = inner(grad(u), grad(v)) * dx
l = f * v * dx

uu = Function(Uspace)

solve(a == l, uu, bcs)

Why do I get superconvergent results when calculating poisson problems?

**Comment by colinjcotter** [comment]
Probably symmetric cancellations on the structured grid (perhaps combined with symmetric solution). Try breaking some of the symmetries.

**Comment by qk11853** [comment]
> Probably symmetric cancellations on the structured grid (perhaps combined with symmetric solution). Try breaking some of the symmetries.

I'm not quite sure what you mean. How can I solve it?
Thank you very much for your reply!

**Comment by colinjcotter** [comment]
There is nothing to solve? Error analysis provides an upper bound in the general case. Sometimes we are lucky.

**Comment by qk11853** [comment]
> There is nothing to solve? Error analysis provides an upper bound in the general case. Sometimes we are lucky.
For the finite element, P1 polynomial space, we get second-order convergence in the L2 sense and first-order convergence in the H1 sense.
Now what I get with firedrake is second order and second order, how do I fix it?

**Comment by colinjcotter** [comment]
This is not inconsistent with the theory

**Comment by qk11853** [comment]
> This is not inconsistent with the theory

But this superconvergent result, how can I get a result that's not superconvergent?

**Comment by colinjcotter** [comment]
Try a less symmetric case

On 9 Jun 2024, at 10:58, qk11853 ***@***.***> wrote:

﻿

This is not inconsistent with the theory

But this superconvergent result, how can I get a result that's not superconvergent?
