### ISSUE TITLE
Spatial Convergence Order of Unsteady Problems

### ISSUE THREAD

**Issue by qk11853** [firedrakeproject/firedrake#3625]
N = N * 2
    mesh = UnitSquareMesh(N, N, diagonal="crossed")

    # ====================Time===================
    dt = 1e-5
    num_steps = 10
    T = dt * num_steps

I get an error when using finite element method to find the spatial convergence order. I give a very small time step and reduce the spatial step by half each time. Why can't I get the correct convergence order?

**Comment by connorjward** [comment]
Please share a complete (minimal) script that reproduces the error, as well as the error message. The information you have provided isn't enough for us to help you.
