### ISSUE TITLE
Compute norm of assembled derivative

### ISSUE THREAD

**Issue by LeeLizuoLiu** [firedrakeproject/firedrake#3651]
I may want to know, whether there is a way to compute the norm of the assembled derivative?
I tried `norm(assemble(derivative(inner(grad(v), grad(v))*dx, w))`, it doesn't work. 

             > OK here's a significantly more minimal case. This extracts the failing operation from the adjoint, so we're now down to a failing assemble with no adjoint aspect.
> 
> ```
> from firedrake import *
> 
> n = 4
> mesh = UnitSquareMesh(n,n)
> V = VectorFunctionSpace(mesh, 'CG', 1)
> R = FunctionSpace(mesh, 'R', 0)
> # R = FunctionSpace(mesh, 'CG', 1)  - works if you use a "normal" function space
> W = V*R
> w = Function(W)
> v, lamb0 = split(w)
> assemble(derivative(inner(grad(v), grad(v))*dx, w))
> ```

_Originally posted by @LeeLizuoLiu in https://github.com/firedrakeproject/firedrake/issues/2830#issuecomment-2187540974_

**Comment by connorjward** [comment]
My suspicion is that it is something to do with the fact that the input to `norm(...)` here is a `Cofunction` instead of a `Function` and hence there may be mathematical reasons why this doesn't work.

@colinjcotter @pbrubeck do either of you know?

**Comment by colinjcotter** [comment]
Yes, the derivative is a cofunction not a function. Cofunctions have norms, obtained by Riesz map to function and then taking norm of the corresponding function.
________________________________

**Comment by LeeLizuoLiu** [comment]
Thanks, do I need to derive the Riesz map manually?

**Comment by colinjcotter** [comment]
No, it is a method of Cofunction

On 26 Jun 2024, at 17:04, Lizuo Liu ***@***.***> wrote:

﻿

Thanks, do I need to derive the Riesz map manually?

**Comment by LeeLizuoLiu** [comment]
Great, thanks! I successfully implemented it.
