### ISSUE TITLE
BUG: firedrake-install is now failing with --petsc-int-type=int64

### ISSUE THREAD

**Issue by diego-hayashi** [firedrakeproject/firedrake#3659]
**Describe the bug**
The `firedrake-install` command is now failing with `--petsc-int-type=int64`.

**Error message**
The part of the error message that causes the installation to fail is:

```
tinyasm/matinvert.cpp:7:46: error: cannot convert ‘PetscInt*’ {aka ‘long int*’} to ‘const PetscBLASInt*’ {aka ‘const int*’}
```

**Comment by JDBetteridge** [comment]
Could you try checking out #3665 to see if you can install that branch? You should be able to do this in the existing virtualenv from the previous install.

If this fails please post the entire traceback and information about your system.

**Comment by diego-hayashi** [comment]
I have just installed with this branch, and it worked fine.

**Comment by JDBetteridge** [comment]
Okay, we will get that branch merged in ASAP
