### ISSUE TITLE
Flake8 for demos

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#3661]
Is pep8 checked for demos? I suspect not because qh is an unused variable in the single layer QG demo.

**Comment by dham** [comment]
We don't check for pep8 in demos because pylit doesn't emit pep8-compliant code.

**Comment by colinjcotter** [comment]
OK I will just PR for the unused variable

On 1 Jul 2024, at 09:15, David A. Ham ***@***.***> wrote:

﻿

We don't check for pep8 in demos because pylit doesn't emit pep8-compliant code.
