### ISSUE TITLE
Zenodo release please.

### ISSUE THREAD

**Issue by pbrubeck** [firedrakeproject/firedrake#3697]
Can you please create a Zenodo release for my upcoming publication:

FIAT: improving performance and accuracy for high-order finite elements

[firedrake.json](https://github.com/user-attachments/files/16285777/firedrake.json)

**Comment by ksagiyam** [comment]
Created Zenodo meta-release.
Tag is `Firedrake_20240718.0`
DOI is 10.5281/zenodo.12783131
Zenodo URL is https://zenodo.org/record/12783131
BibTeX

```bibtex
@misc{zenodo/Firedrake-20240718.0,
 key   = {zenodo/Firedrake-20240718.0},
 title = {{Software used in `FIAT: improving performance and accuracy for high-order finite elements'}},
 year  = {2024},
 month = {jul},
 doi   = {10.5281/zenodo.12783131},
 url   = {https://doi.org/10.5281/zenodo.12783131},
}

```
Thanks!
