### ISSUE TITLE
INSTALL: test case does not work

### ISSUE THREAD

**Issue by giupep** [firedrakeproject/firedrake#3785]
Hi, I've installed Firedrake as the guide instructed, but when i run the test case I have an error message, in fact there is no folder in src.
I've installed firedrake on wsl with ubuntu 24.04

**Error message**
ERROR: file or directory not found: tests/regression/

this is the installation.log
[firedrake-install.log](https://github.com/user-attachments/files/17241357/firedrake-install.log)

**Comment by dham** [comment]
As the install log shows, your installation failed with the following error:
```console
2024-10-03 09:45:18,267 DEBUG  Running command 'git clone -q --recursive https://github.com/firedrakeproject/firedrake.git'
2024-10-03 09:46:02,431 DEBUG  error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 7184 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

2024-10-03 09:46:02,431 ERROR  Failed to clone firedrake branch master.
2024-10-03 09:46:02,479 INFO  
```

Essentially, you had a network error connecting to Github. This might have been a transient error, in which case `rm -rf firedrake` and running the install again might fix it. If you get the same issue again then it probably indicates a network issue in your system (maybe some WSL issue). In that case you should see if you can run `git clone -q --recursive https://github.com/firedrakeproject/firedrake.git' outside the install script, and then debug based on any error you see there.

**Comment by giupep** [comment]
Thanks now it works.
