### ISSUE TITLE
INSTALL: PETSCs building issues on MacBook (macOS 15.0.1)

### ISSUE THREAD

**Issue by ACSE-yl4222** [firedrakeproject/firedrake#3790]
**Describe the error**
I install firedrake via following the steps:
curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
python3 firedrake-install

However, there is the issue in terminal:
Installing petsc/
Depending on your platform, PETSc may take an hour or more to build!
Traceback (most recent call last):
  File "/Users/liyezhang/firedrake-install", line 1836, in <module>
    install("petsc/")
  File "/Users/liyezhang/firedrake-install", line 1056, in install
    build_and_install_petsc()
  File "/Users/liyezhang/firedrake-install", line 1168, in build_and_install_petsc
    check_call([python, "./configure", "PETSC_DIR={}".format(petsc_dir), "PETSC_ARCH={}".format(petsc_arch)] + petsc_options)
  File "/Users/liyezhang/firedrake-install", line 676, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=os.environ).decode())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/liyezhang/firedrake/bin/python', './configure', 'PETSC_DIR=/Users/liyezhang/firedrake/src/petsc', 'PETSC_ARCH=default', "--download-openblas-make-options='USE_THREAD=0 USE_LOCKING=1 USE_OPENMP=0'", '--download-metis', '--download-hdf5', '--download-pastix', '--download-mpich-configure-arguments=--disable-opencl', '--download-hwloc', '--CFLAGS=-Wno-implicit-function-declaration', '--with-zlib', '--download-hypre', '--download-mpich', '--download-pnetcdf', '--download-bison', '--with-debugging=0', '--with-c2html=0', '--download-openblas', '--with-x=0', '--download-suitesparse', '--download-ptscotch', '--download-scalapack', '--download-superlu_dist', '--download-hwloc-configure-arguments=--disable-opencl', '--LDFLAGS=-Wl,-ld_classic,-dead_strip_dylibs', '--download-netcdf', '--with-fortran-bindings=0', '--with-shared-libraries=1', '--download-mumps']' returned non-zero exit status 1.

The relevant `firedrake-install.log` and `$VIRTUAL_ENV/src/petsc/configure.log` files are attached below:
[firedrake-install.log](https://github.com/user-attachments/files/17269951/firedrake-install.log)
[configure.log](https://github.com/user-attachments/files/17269954/configure.log)

**Environment:**
 - OS: macOS 15.0.1
 - Python version: Python 3.12.7
 - Xcode: Version 16.0

I'd appreciate it if you could help to solve it.

**Comment by Ig-dolci** [comment]
Can you please try to install it again with `python3 firedrake-install --package-branch petsc JDBetteridge/merge_upstream`?

**Comment by leo-collins** [comment]
Hi, I'm getting the same error, with and without using `--package-branch petsc JDBetteridge/merge_upstream`. I'm on macOS 15.0.1 and python 3.12.6 (pyenv). Logs:

[configure.log](https://github.com/user-attachments/files/17279920/configure.log), 
[firedrake-install.log](https://github.com/user-attachments/files/17279930/firedrake-install.log)

Thanks for any help!

**Comment by connorjward** [comment]
The logs posted above have different error messages but both seem to stem from problems with Fortran compilers. This is maybe not surprising since Xcode 16 is brand new: https://xcodereleases.com/. We maybe need to report these to PETSc to get them fixed.

**Comment by Ig-dolci** [comment]
I just installed firedrake with Xcode 16, python3.12.7, and Mac Sequoia 15.0.1 without errors with `--package-branch petsc JDBetteridge/merge_upstream`. I am not sure if is an issue related to Xcode 16.

**Comment by Ig-dolci** [comment]
@leo-collins, just to clarify—are you installing Firedrake with

```
python3 (from homebrew) firedrake-install --package-branch petsc JDBetteridge/merge_upstream
```

Or are you setting up a Python virtual environment first and then running:

```
python3 firedrake-install --package-branch petsc JDBetteridge/merge_upstream
```

inside the virtual environment?

**Comment by Ig-dolci** [comment]
@ACSE-yl4222, I noticed that you have `CONDA_PYTHON_EXE=/opt/anaconda3/bin/python`. Could you please check if you are using Python installed via Homebrew? Also, make sure to deactivate any Conda environment in the terminal where you are running the `firedrake-install` script.

**Comment by leo-collins** [comment]
@Ig-dolci I am using python installed with pyenv, following the [instructions here](https://github.com/firedrakeproject/firedrake/wiki/Installing-pyenv), and running

`python firedrake-install --venv-name=$(pyenv root)/versions/firedrake --petsc JDBetteridge/merge_upstream`

I'll try again using python from homebrew

**Comment by leo-collins** [comment]
I'm still getting the same error. I'm running `python3 firedrake-install --package-branch petsc JDBetteridge/merge_upstream` where `python3` is the brew installed python. I'm not doing this in a virtual environment. The new logs are here

[firedrake-install.log](https://github.com/user-attachments/files/17281881/firedrake-install.log)
[configure.log](https://github.com/user-attachments/files/17281888/configure.log)

**Comment by Ig-dolci** [comment]
It looks like there is an issue with `autoreconf` (see the error at line 73066: `autoreconf test error: Could not execute "[['/opt/homebrew/bin/autoreconf']]"`). Try running `brew reinstall autoconf`. After that, check if `autoreconf --version` works.

**Comment by leo-collins** [comment]
@Ig-dolci Reinstalling `autoconf` fixed solved my issue, thank you very much for your help! :)

**Comment by ACSE-yl4222** [comment]
> @ACSE-yl4222, I noticed that you have `CONDA_PYTHON_EXE=/opt/anaconda3/bin/python`. Could you please check if you are using Python installed via Homebrew? Also, make sure to deactivate any Conda environment in the terminal where you are running the `firedrake-install` script.

Hi @Ig-dolci, I just check my python version after that. Yes, I used Python installed via Homebrew and installed firedrake after deactivating the conda environment in the terminal. I'll try it again with ''--package-branch petsc JDBetteridge/merge_upstream'' again.

**Comment by ACSE-yl4222** [comment]
> @ACSE-yl4222 does this work for you? Sorry this issue thread got a bit distracted.

Hi @connorjward, I'm trying to figure out if there is some issues from setup in my machine, I've tried to install firedrake on Ubuntu system and it works. I'll try it in my MacBook later. Thanks so much!

**Comment by connorjward** [comment]
OK. I will close this issue. Please open a new one if you try again and encounter issues.
