### ISSUE TITLE
INSTALL: MacBook Pro installation fail

### ISSUE THREAD

**Issue by Frej-D** [firedrakeproject/firedrake#3797]
I'm trying to install firedrake on my MacBook Pro with MacOS Ventura 13.7. I've installed python through homebrew and am running the command '/usr/local/bin/python3 firedrake-install' as when I use 'python3 firedrake-install' it defaults to MacOS system python.

I've included the install log. I'm not very tech-savvy so any help would be greatly appreciated.

Thanks.

[firedrake-install.log](https://github.com/user-attachments/files/17363064/firedrake-install.log)

**Comment by connorjward** [comment]
The log shows
```
2024-10-14 11:56:41,888 DEBUG  Using pip 24.2 from /Users/frejdunn/firedrake/lib/python3.13/site-packages/pip (python 3.13)
ERROR: Could not find a version that satisfies the requirement vtk>=9.0.1 (from versions: none)
```
so clearly VTK do not have a Mac wheel for Python 3.13 yet.

@JDBetteridge what is the recommended solution for this?

**Comment by JDBetteridge** [comment]
This was posted on slack, but I will summarise options here for reference:
1. Install firedrake passing the `--no-vtk` flag (if you aren't planning on using VTK output in the near future).
2. Downgrade your Python version to 3.12, but you will have to completely reinstall Firedrake when you update back to 3.13
3. (More involved) Build your own VTK package using [our guide and repo](https://github.com/firedrakeproject/VTKPythonPackage).

**Comment by connorjward** [comment]
@Frej-D can this issue be closed?

**Comment by Frej-D** [comment]
Yep, thank you! The second option worked for me.
