### ISSUE TITLE
INSTALL: Failure to download mpich breaks firedrake install on Mac

### ISSUE THREAD

**Issue by ericwhester** [firedrakeproject/firedrake#3845]
Running the firedrake install script fails on a new MacBook Pro with M2 Pro chip.

Running `python3 firedrake-install` with the system python downloads everything, but then fails when installing petsc, specifically when trying to download the tar files for mpich. See attached log: [firedrake-install.log](https://github.com/user-attachments/files/17568495/firedrake-install.log)

There was advice about using the brew installed version of python. However, that fails at the first step, because that version (python 3.13) doesn't have modules "pkg_resources" or "packaging". The error message is

```Traceback (most recent call last):
  File "/Users/ericwilliamhester/firedrake-install", line 20, in <module>
    from pkg_resources.extern.packaging.version import Version, InvalidVersion
ModuleNotFoundError: No module named 'pkg_resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ericwilliamhester/firedrake-install", line 22, in <module>
    from packaging.version import Version, InvalidVersion
ModuleNotFoundError: No module named 'packaging'
```

So I tried installing older versions of python through brew which do have pkg_resources. Python 3.9 worked. So using _that_ version of python gave the same mpich download error as the first attempt. See the [firedrake-install.log](https://github.com/user-attachments/files/17568657/firedrake-install.log) and 
[configure.log](https://github.com/user-attachments/files/17568682/configure.log)

**Environment:**
 - OS: macOS Sonoma 14.6
 - Python version: python 3.13.0 and python 3.9.20

Thanks for any help,
Eric

**Comment by connorjward** [comment]
I think that there are two issues:
* At present we don't have *full* support for Python 3.13. In particular VTK have not yet released wheels for Python 3.13 so you would need to pass `--no-vtk` to `firedrake-install` (and not have paraview output) ([issue](https://github.com/firedrakeproject/firedrake/issues/3797#issuecomment-2411282294)). We recommend using Python 3.12 for the time being.
* You are having bizarre network issues when installing MPICH through PETSc. Do you either have a bad internet connection or some sort of firewall? Does
```
$  wget https://github.com/pmodels/mpich/releases/download/v4.2.3rc1/mpich-4.2.3rc1.tar.gz
```
run in your terminal?

**Comment by ericwhester** [comment]
Yep. So my install attempt with earlier python still didn't work. 3.12 also gave that pkg_resources error. 

The mpich download worked perfectly fine on my other laptop (also a MacBook, but with intel chips on MacOS 12.7.6). But the install script suffers the same failure to download building petsc. For completeness, I'll attach those install logs too. It looks like the same type of error on a different MacBook.

[firedrake-install.log](https://github.com/user-attachments/files/17579175/firedrake-install.log)

[configure.log](https://github.com/user-attachments/files/17579179/configure.log)

Now, the firewall is active on my other laptop. But I'm not sure if that's what's causing the issue, and what I should try changing to diagnose that.

Thanks for any help,
Eric

**Comment by connorjward** [comment]
> Based on the logs, it looks like that you are installing Firedrake using Python from Miniconda, which conflicts with Firedrake's [installation requirements](https://www.firedrakeproject.org/download.html). Please deactivate Conda in your terminal and try reinstalling Firedrake using Python from Homebrew instead.

As well as doing this you will also likely need to address the firewall issue that is preventing PETSc from downloading external packages. A previous user encountered a [similar issue](https://github.com/firedrakeproject/firedrake/issues/3644) which may be useful to refer to. Otherwise you may need to resort to a more involved installation procedure: https://petsc.org/release/install/install/#external-packages.

**Comment by ericwhester** [comment]
I will close this issue, since I was able to fix things by updating my old macbook to OS Ventura and then installing. However there is a new bug that I will open.
