### ISSUE TITLE
Zenodo release request

### ISSUE THREAD

**Issue by kaushikcfd** [firedrakeproject/firedrake#3850]
Can you please create a Zenodo release for our upcoming publication: "UFL to GPU: Near the roofline".

[firedrake.json](https://github.com/user-attachments/files/17601870/firedrake.json)

/cc @inducer

Thanks!

**Comment by ksagiyam** [comment]
`github3.exceptions.UnprocessableEntity: 422 No commit found for SHA: 421ee2a09b95124fb40c545ef24d6ad86a67262f`

You probably need to push your loopy branch to firedrakeproject/loopy so that we can find it.

**Comment by kaushikcfd** [comment]
Whoops, just pushed to a branch. Could you please retry.

**Comment by ksagiyam** [comment]
I do not see your Firedrake branch either. Please make sure that all branches are in Firedrakeproject.

**Comment by kaushikcfd** [comment]
Sorry, just regenerated and verified with a rebuild for the following hashes.

```json
{"firedrake": "57d05beb5fe19539e8fcfd882a7b212a8a5bd920", "PyOP2": "9783858bf7c5e04d0044098e570bec7777e83c20", "tsfc": "741412c7349d8247b31b5b158b24ea0a5f9a94f1", "ufl": "c1a8afb10bbde3c345d61a78b7f249f039dc6690", "FInAT": "56cf0267fb732872d5d9fae4348093ade76e62e3", "fiat": "ae368208aa000843e656b957295d0739727e448c", "petsc": "1c1d65e4821014ef0061175a45910161916374c3", "loopy": "421ee2a09b95124fb40c545ef24d6ad86a67262f", "metarelease_info_file": null, "title": "UFL to GPU: Near the Roofline"}
```

**Comment by ksagiyam** [comment]
Created Zenodo meta-release.
Tag is `Firedrake_20241102.1`
DOI is 10.5281/zenodo.14029412
Zenodo URL is https://zenodo.org/record/14029412
BibTeX

```bibtex
@misc{zenodo/Firedrake-20241102.1,
 key   = {zenodo/Firedrake-20241102.1},
 title = {{Software used in `UFL to GPU: Near the Roofline'}},
 year  = {2024},
 month = {nov},
 doi   = {10.5281/zenodo.14029412},
 url   = {https://doi.org/10.5281/zenodo.14029412},
}

```
Thanks!
