### ISSUE TITLE
CellSize gives NaNs with an extruded mesh

### ISSUE THREAD

**Issue by ctjacobs** [firedrakeproject/firedrake#387]
I'm trying to use `CellSize` for SU stabilisation purposes, but it gives NaNs when used with an extruded mesh.

```
from firedrake import *

unitmesh = UnitSquareMesh(10, 10)
mesh = ExtrudedMesh(unitmesh, layers=2)

c = CellSize(mesh)

print assemble(c*dx)
```

**Comment by miklos1** [comment]
There is a branch in FFC (`eliminate-silent-failures`) which prevents silently picking the wrong code snippet based on geometric and topological dimension.

**Comment by wence-** [comment]
Track this problem in firedrakeproject/tsfc#1

**Comment by wence-** [comment]
Fixed now if one uses `CellVolume`.
