### ISSUE TITLE
DOCS: Confusing in testing instructions

### ISSUE THREAD

**Issue by kakila** [firedrakeproject/firedrake#3893]
**Describe the issue**
The instructions to test a new firedrake installation are confusing.
- In the current online version of the docs the folder is wrong
-  in the github version of the docs the test ends with warnings.

If one follows the instructions in [github/download.rst](https://github.com/firedrakeproject/firedrake/blob/master/docs/source/download.rst) one gets:

```
============================================================== 27 passed, 2 skipped, 3602 deselected, 19 warnings in 10.58s ==============================================================
WARNING! There are options you set that were not used!
WARNING! could be spelling mistake, etc!
There is one unused database option. It is:
Option left: name:-k value: poisson_strong or stokes_mini or dg_advection source: command line

```

**Where to find**
- https://github.com/firedrakeproject/firedrake/blob/master/docs/source/download.rst
- https://www.firedrakeproject.org/download.html 

**Additional info**
I tested the command

`pytest tests/firedrake -k "poisson_strong or stokes_mini or dg_advection"
`

Seems to do more than the previous one and ends with 

```
======================================================= 36 passed, 3 skipped, 8057 deselected, 24850 warnings in 99.56s (0:01:39) ========================================================
WARNING! There are options you set that were not used!
WARNING! could be spelling mistake, etc!
There is one unused database option. It is:
Option left: name:-k value: poisson_strong or stokes_mini or dg_advection source: command line
(gully-thermal) juanpi@lorien:~/.virtual_envs/gully-thermal/src/firedrake$ pytest tests/firedrake/regression/ -k "poisson_strong or stokes_mini or dg_advection"

```

**Comment by connorjward** [comment]
Thank you for identifying a bug with our docs. It looks like we have two download pages:
* https://www.firedrakeproject.org/firedrake/download.html (new, correct)
* https://www.firedrakeproject.org/download.html (old, wrong)

Unfortunately these warnings are thrown by PETSc and are fairly hard to disable, especially through pytest. They are completely normal.

**Comment by connorjward** [comment]
Actually this is only because we merged the changes yesterday and the website hasn't yet been rebuilt. It should be within the next 30 minutes.

Can this issue be closed? You mention a couple of problems here and it is unclear whether or not they have all been answered.

**Comment by dham** [comment]
The options warning is still real. Not sure how fixable that is.

**Comment by kakila** [comment]
The way i see it the main issue with the docs seems to be solved. I guess the part of the warnings could be made a standalone issue.

**Comment by connorjward** [comment]
Please feel free to open a new issue discussing that specifically. I will close this one.
