### ISSUE TITLE
Assemble block inverse (for DG)

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#399]
This is related but hopefully less tricky than #108. I would like to have an `assemble_inverse()` that assembles a local element matrix from a bilinear form, inverts it, and assembles it into the global matrix. This would allow (via some PETSc operations) hybridised solvers for mixed FEM, which would speed up our code a lot and allow us to include Coriolis in the semi-implicit solve (required for Hiroe's stuff to work efficiently).

Wonder if this could be done by some post-processing hackery on a compiled FFC kernel made using `assemble()`?

**Comment by miklos1** [comment]
@colinjcotter: What is the state of this? Is it implemented already?

**Comment by colinjcotter** [comment]
That's already in, yes.
