### ISSUE TITLE
Cubed sphere mesh generator

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#406]
Something like `UnitCubedSphereMesh`

It's the topology that I need more than the geometry, which I can hack around with, so actually a mesh of the surface of a cube is fine. I could then supply various options: gnonomic, spring dynamics, conformal, etc.

**Comment by miklos1** [comment]
So, now that #418 is merged, is there any reason keep this issue open?

**Comment by wence-** [comment]
Nope.
