### ISSUE TITLE
The difference between w.split() and split(w) is irritating

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#407]
I'm not sure this can be fixed but we definitely need to document it very, very clearly.

**Comment by tkarna** [comment]
Would it make sense to rename one of those functions to avoid confusion? As they have the same name it is intuitive to assume they do the same thing, like with numpy.max(a) and a.max().

**Comment by dham** [comment]
Unfortunately the wierd behaviour of split is something we inherit from FEniCS so we would gratuitously break compatibility if we changed the names.

**Comment by wence-** [comment]
Fixed by #1035.
