### ISSUE TITLE
Travis should test pip install of firedrake

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#417]
We should dogfood our installation instructions in the travis builder and install firedrake via pip and clone the repo purely to get access to the tests.

**Comment by miklos1** [comment]
I think this issue is:
a) partially irrelevant, since pip install is not longer the recommend way of installation;
b) partially complete, since the installation instructions are mostly dogfooded by now (ignoring bugs);
thus I suggest closing this.
