### ISSUE TITLE
Cannot subtract a Form from an int

### ISSUE THREAD

**Issue by ctjacobs** [firedrakeproject/firedrake#427]
The `+=` operator works fine here:

```
from firedrake import *

mesh = UnitSquareMesh(10, 10)
fs = FunctionSpace(mesh, "CG", 1)
v = TestFunction(fs)
u = TrialFunction(fs)

F = 0
F += inner(v, u)*dx
```

but using the `-=` operator fails and gives the following error message:

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    F -= inner(v, u)*dx
TypeError: unsupported operand type(s) for -=: 'int' and 'Form'
```

**Comment by wence-** [comment]
This is because UFL defines `__radd__` on `Form`s but not `__rsub__`.  Workaround (since this is all UFL does anyway):

```
F += -inner(v, u)*dx
```

**Comment by miklos1** [comment]
Related: https://bitbucket.org/fenics-project/ufl/pull-requests/33

**Comment by wence-** [comment]
Fixed by recent UFL updates.
