### ISSUE TITLE
Separation of concerns between Mesh and FunctionSpace

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#429]
Problems:

1. Mesh* creates closure ordering using a FunctionSpace-dependent global section. This does not lead to bugs, since FunctionSpace-dependent section always fulfils the requirements of the closure ordering algorithm. However, it introduces an artificial dependence on FunctionSpace, when closure ordering could be self-contained.
2. The above dependence is _hidden_ via the default section of the DMPlex object.**

--

*Currently, simplex meshes only, however quadrilateral meshes will soon use the same thing. Extruded meshes have no own cell closure, they use the cell closure of the base mesh.

**This was, in fact, my fault, due to partial understanding of the situation at the time, when I removed another artificial dependence, that the number of topological mesh entities per cell were calculated from the FunctionSpace dependent FIAT element.

**Comment by miklos1** [comment]
Added branch `soc-fs-mesh`.

**Comment by wence-** [comment]
So from a PETSc point of view, the right thing to do is the following:

o Mesh contains the DMPlex object which we use to query topology-like information
o Every time we build a new function space we do:

```
fs._plex = mesh._plex.clone()
section = fs._plex.createSection(...)
fs._plex.setDefaultSection(section)
```

Cloning the DM just creates a new object that references the original one for all the internal (DAG/Plex) data.  This way, functionspace construction will never pollute the data in the original plex living with the mesh.

**Comment by mlange05** [comment]
I think we should use the IS returned from `DMPlexGetVertexNumbering` instead of this section to create the closure ordering. The IS gets created from the vertex-specific global section and is then cached on the DMPlex itself, without setting any default section.

**Comment by wence-** [comment]
That doesn't work because it pays no attention to the section permutation we use.

**Comment by mlange05** [comment]
Oh yes, sorry, I forgot this works at section level. In that case we probably want to wrap `PetscSectionCreateGlobalSection` to be able to create the according global section directly from `mesh._vertex_numbering` without (ab)using the DMPlexDefaults API.

**Comment by miklos1** [comment]
#437 merged.
