### ISSUE TITLE
More coffee optimiser failures

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#436]
Here's a stripped down version of the problem in #425.  The error is in the assembly of the diagonal A00 block.  With coffee switched on, the SVD of the operator is completely different.

```python
from firedrake import *
mesh = UnitSquareMesh(2, 2)

U = VectorFunctionSpace(mesh, "CG", 2)

u = Function(U)
w = TestFunction(U)

dt = 0.5
u_old = Function(U)
F = 0
M_momentum = (1.0/dt)*(inner(w, u) - inner(w, u_old))*dx
F += M_momentum

A_momentum = inner(dot(grad(u), u), w)*dx
F += A_momentum

# viscosity = Constant(0.7)
# K_momentum = -viscosity*inner(grad(u) + grad(u).T, grad(w))*dx
# F -= K_momentum

parameters["coffee"]["O2"] = False
a = derivative(F, u)
A = assemble(a)

import numpy as np

u, s, v = np.linalg.svd(A.M.values)

print s[:8]
```

Note this also fails with VFS degree 1, but this is closer to the original problem.

**Comment by FabioLuporini** [comment]
Branch fix-issue-436-firedrake in COFFEE should fix the issue. Please, let me know if you agree with this. All tests seem to pass; so if reasonable to you, @wence-, I'll merge

**Comment by wence-** [comment]
So while that branch fixes this particular issue, Christian's problem in firedrakeproject/firedrake#425 remains.  And the following does not work:

```python
from firedrake import *
mesh = UnitSquareMesh(2, 2)

U = VectorFunctionSpace(mesh, "CG", 2)

u = Function(U)
w = TestFunction(U)

dt = 0.5
u_old = Function(U)
F = 0
M_momentum = (1.0/dt)*(inner(w, u) - inner(w, u_old))*dx
F += M_momentum

A_momentum = inner(dot(grad(u), u), w)*dx
F += A_momentum

viscosity = Constant(0.7)
K_momentum = -viscosity*inner(grad(u) + grad(u).T, grad(w))*dx
F -= K_momentum

parameters["coffee"]["O2"] = True
a = derivative(F, u)
A = assemble(a)

import numpy as np

u, s, v = np.linalg.svd(A.M.values)

print s[:8]
```

This is as before but I've added back in the viscosity term.  In this case the SVD changes between optimised and non-optimised.

**Comment by FabioLuporini** [comment]
Fetch and have a go now

**Comment by wence-** [comment]
Thanks.  That appears to work for both this test and Christian's example.

**Comment by miklos1** [comment]
We can close this now, right?
