### ISSUE TITLE
IntervalMesh has inconsistent API for no good reason

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#440]
I want to create a mesh on [-1, 1]. Dolfin lets me do this with

    mesh = IntervalMesh(100, -1, 1)

but firedrake has an inconsistent API for no (obvious) good reason. Instead it's only possible to create meshes on [0, L]:

    mesh = IntervalMesh(ncells=100, L=2)

Can this be made consistent?

**Comment by wence-** [comment]
Does the branch in #441 do the right thing for you?

**Comment by pefarrell** [comment]
I haven't tried the branch, but from the tests it looks like it hits the nail squarely on the head.

**Comment by wence-** [comment]
Merged in #441.
