### ISSUE TITLE
The way of defining finite elements and function spaces on quadrilaterals in inconvenient

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#447]
Creating CG or DG elements / function spaces is OK, but for H(div) or H(curl) elements one has to do the following:
```
C_elt = FiniteElement("CG", "interval", degree)
D_elt = FiniteElement("DG", "interval", degree - 1)
V_elt = HDiv(OuterProductElement(C_elt, D_elt)) + HDiv(OuterProductElement(D_elt, C_elt))
V = FunctionSpace(mesh, V_elt)
```
... or:
```
C_elt = FiniteElement("CG", "interval", degree)
D_elt = FiniteElement("DG", "interval", degree - 1)
V_elt = HCurl(OuterProductElement(C_elt, D_elt)) + HCurl(OuterProductElement(D_elt, C_elt))
V = FunctionSpace(mesh, V_elt)
```
instead of something sensible such as
```
V = FunctionSpace(mesh, "RTCF", degree)
```
... or:
```
V = FunctionSpace(mesh, "RTCE", degree)
```

Even worse, the manual assembly of OuterProductElements allows creating elements where edges have different number of nodes. (Which will fail anyway later.)

**Comment by dham** [comment]
I assume you know this, but we should follow the periodic table when using names for elements: http://femtable.org/

**Comment by dorugeber** [comment]
These names are accepted in UFL already.  This is another justification for using the existing UFL elements on quadrilaterals.

I see two reasonable options.  The first is that when FFC encounters these elements, it builds the appropriate FIAT element out of products.

Another option is to modify FIAT to expose a representation of quadrilateral elements (presumably FIAT would internally build them out of products).

**Comment by miklos1** [comment]
Today we have decided with @dorugeber and @wence- to ditch support for user-defined outer product finite elements on quadrilaterals. That will break the currently existing syntax for H(div) and H(curl) elements. Users will be encouraged (forced) to use RTCF, RTCE, or anything we provide function spaces.

**Comment by miklos1** [comment]
#448 shall fix the issue both for quadrilaterals and for extruded intervals.

**Comment by miklos1** [comment]
#448 merged, closing.
