### ISSUE TITLE
Halo construction disgustingly memory heavy

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#451]
We were wondering why doru seems unable to run "big" jobs in parallel (where the data volume is around 3GB) but running on 12 processes blows memory usage up to almost 60GB.

It turns out the way we build halos is horrifically poorly performing as far as memory usage goes.  I think there must be a better way.  Effectively what we're doing is deriving two-sided communication data from the one-sided data that the petsc SF we have gives us.  I.e. we have the receives part of a halo but we want the sends.  Ideas?

**Comment by wence-** [comment]
I think, with a bit of reworking, we can use PETSc's SFs directly, rather than converting them to our own halo format.  Which should remove this problem.

**Comment by dham** [comment]
That is brilliant. Any time we can avoid having our own solution is
wonderful.

On 7 February 2015 at 11:15, Lawrence Mitchell <notifications@github.com>
wrote:

>  I think, with a bit of reworking, we can use PETSc's SFs directly,
> rather than converting them to our own halo format. Which should remove
> this problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/451#issuecomment-73360168>
> .
>



-- 
Dr David Ham
Departments of Mathematics and Computing
Imperial College London

http://www.imperial.ac.uk/people/david.ham

**Comment by miklos1** [comment]
Can we close this? A fix (#457), which was working for @doru1004, has already been merged.

**Comment by wence-** [comment]
Yes.
