### ISSUE TITLE
CUDA Mats cause crash in assembly_cache

### ISSUE THREAD

**Issue by chromy** [firedrakeproject/firedrake#461]
Running this example:
```python
#!/usr/bin/env python
from firedrake import *

degree = 1
mesh = UnitSquareMesh(10, 10)

def p():
    V = FunctionSpace(mesh, "CG", degree)
    u = TrialFunction(V)
    v = TestFunction(V)
    a = u * v * dx
    A = assemble(a)
    A.M

# This works.
p()

# This works with PYOP2_BACKEND=sequential but fails with PYOP2_BACKEND=cuda
p()
```

Produces this error:
```
Traceback (most recent call last):
  File "./cuda_twice_bug.py", line 20, in <module>
    p()
  File "./cuda_twice_bug.py", line 17, in p
    A.M
  File "/homes/hjd11/proj/Firedrake/firedrake/firedrake/matrix.py", line 143, in M
    self.assemble()
  File "/homes/hjd11/proj/Firedrake/firedrake/firedrake/matrix.py", line 72, in assemble
    self._assembly_callback(self.bcs)
  File "/homes/hjd11/proj/Firedrake/firedrake/firedrake/assembly_cache.py", line 338, in inner
    if obj.handle is not result._M.handle:
AttributeError: 'Mat' object has no attribute 'handle'
```
The assembly_cache seems to assume that the Mat will inherit from pyop2.petsc_base.Mat. I'm not sure what the equivalent field is for a CUDA Mat, maybe __lma_data?

[pyop2.cuda.Mat](https://github.com/OP2/PyOP2/blob/master/pyop2/cuda.py#L219)
[pyop2.petsc_base.handle](https://github.com/OP2/PyOP2/blob/e526c43dca451bc20b3cf728b71307950616d8c8/pyop2/petsc_base.py#L435)
[pyop2.petsc_base._handle](  https://github.com/OP2/PyOP2/blob/e526c43dca451bc20b3cf728b71307950616d8c8/pyop2/petsc_base.py#L239)

**Comment by dham** [comment]
I strongly suspect assembly caching won't work in your case. I'd start out by disabling it.

**Comment by chromy** [comment]
That works, for anybody else looking to do the same thing the magic command was:
`firedrake.parameters["assembly_cache"]["enabled"] = False`

**Comment by wence-** [comment]
I'm going to close this.  Firedrake basically doesn't support non-CPU pyop2 backends.
