### ISSUE TITLE
Infinite loop occurs when casting a Constant to a float

### ISSUE THREAD

**Issue by ctjacobs** [firedrakeproject/firedrake#464]
In DOLFIN the following code prints `0.5` as I would like, but in Firedrake I get an infinite loop of `Couldn't map 'w_0' to a float, returning ufl object without evaluation.` statements.

```
from firedrake import *
timestep = Constant(0.5)
print float(timestep)
```

**Comment by wence-** [comment]
Fixed in #466 I think.

**Comment by ctjacobs** [comment]
Fixed indeed - thank you.

**Comment by wence-** [comment]
Merged.
