### ISSUE TITLE
Extruding mesh with external data

### ISSUE THREAD

**Issue by tkarna** [firedrakeproject/firedrake#470]
Custom kernels in ExtrudedMesh allow user-defined mesh extrusion, but the kernel signature doesn't allow using any user-provided data.

I'd like to extrude a 2D mesh based on a function on the parent mesh (bathymetry). Would it be possible to add an argument to ExtrudedMesh (and make_extruded_coords) that, if provided, gets passed to the custom kernel (if one is given)?

**Comment by dham** [comment]
You are correct. We really should replace that specified interface with a more flexible one, and the more recent Firedrake kernel interface gives us a way to do it.

As a short term fix, one thing you can do is uniform extrusion and then access the mesh coordinate field and rewrite the z coordinate to take your bathymetry into account.

**Comment by tkarna** [comment]
OK, rewriting mesh coordinates seems to work fine.

**Comment by danshapero** [comment]
The fix seems to be to modify the coordinate field of the 3D mesh rather than use a custom kernel when extruding it, so I'm going to close this rather old issue. Please reopen if I was mistaken here and there actually is a good reason to do this during extrusion.
