### ISSUE TITLE
Quad plotting goes down wrong (well, inefficient) codepaths

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#480]
In io.py, we make a decision on whether to output a CG or a DG field.  Quote: "If both the coordinates and the output field are in H1, project to CG1.  Otherwise project to DG1." (from e25ac3f)

This is done by checking the element family against 'Lagrange'.  While we handle OPEs correctly (by checking each subelement against 'Lagrange'), the CG1 element on proper quadrilaterals has family 'Q', so wrongly fails this check.

Proposed fix incoming, of course.

**Comment by wence-** [comment]
Fixed in #737 by inspecting the fiat element.
