### ISSUE TITLE
VectorFunctionSpace.sub(0) not implemented

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#491]
I'd like to create a boundary condition on one component of a `VectorFunctionSpace`. In dolfin I would do `DirichletBC(V.sub(0), 0, ...)`, but I can't do this in firedrake:

    from firedrake import *

    mesh = RectangleMesh(10, 1, 10, 0.1)
    V = VectorFunctionSpace(mesh, "CG", 1)
    bc = DirichletBC(V.sub(0), 0., 1)

yields

    AttributeError: 'VectorFunctionSpace' object has no attribute 'sub'

**Comment by wence-** [comment]
So it looks like you can use such subscripted functions anywhere in dolfin: if you don't copy the data then they effectively just point at the vector-function's data.  I think this is possible to do cleanly, but it requires some work in PyOP2: effectively being able to define "Views" into existing data.  This requires some thought to get right.

**Comment by wence-** [comment]
I think recent changes have done this right.

**Comment by pefarrell** [comment]
Great, thanks!

**Comment by wence-** [comment]
Note you can't use a `f.sub(0)` in a form because I haven't implemented that.  But if you only need things for bc application, it's fine.
