### ISSUE TITLE
assemble(linear_form) returns a Function

### ISSUE THREAD

**Issue by jrmaddison** [firedrakeproject/firedrake#497]
Passing a linear form to assemble(...) yields a Function object. This is incompatible with DOLFIN, where a Vector object is returned, which leads to incompatibilities in simple assembly tests (e.g. attempting to compute a norm of the assembled form). It's also misleading, as a linear form is an element of the dual space.

**Comment by jrmaddison** [comment]
Note that this syntax potentially makes constructing some adjoint equations confusing.

**Comment by wence-** [comment]
So I think we decided to be deliberately incompatible here.  Yes, you should arguably get a CoFunction rather than a Function.  However, I'm not convinced that a euclidean vector is the right thing to get.

**Comment by jrmaddison** [comment]
There's potential for some issues with this syntax, as:

```python
F = Function(space)
G = Function(space)
G.assign(F + assemble(inner(test, F) * dx))
```

should be invalid, whereas it might be useful for:

```python
Gs = assemble(inner(test, G) * dx)
inner(test, F) * dx + Gs
```

to be valid. At the moment Firedrake gives the opposite behaviour. I agree that returning a Vector is also not obviously the right thing to do.

**Comment by wence-** [comment]
OK, I see.  So the latter probably fails because UFL doesn't know how to add Coefficients to Forms, right?

```assemble(inner(test, F)*dx) + Gs```

would work in this situation.

I agree that the former is a type error which appears in dolfin but not firedrake.  Here's a sketch of a possible solution:

```
# This inheritance is just to pick up the methods
class CoFunction(Function):
      pass
```

assemble(linear_form) => CoFunction

And then we can raise errors when trying to use CoFunctions where Functions are expected (and vice versa).  e.g. in solve(A, x, b), b should be a cofunction and x a function: the matrix A should really expose that is a linear operator between two function spaces.

I think this then also gives us the ability to DTRT with your second example.

**Comment by dham** [comment]
I agree that CoFunction would be a Good Thing (indeed we have previously
discussed it).

I am not convinced that

Gs = assemble(inner(test, G) * dx)
inner(test, F) * dx + Gs

should work. I understand that it has a mathematical meaning, but we do
differentiate between assembled and unassembled objects in some sense.

For example what type should Form + CoFunction have? I guess one answer
would be that a CoFunction is also a Form but that requires more legwork...



On 1 April 2015 at 12:18, Lawrence Mitchell <notifications@github.com>
wrote:

>  OK, I see. So the latter probably fails because UFL doesn't know how to
> add Coefficients to Forms, right?
>
> assemble(inner(test, F)*dx) + Gs
>
> would work in this situation.
>
> I agree that the former is a type error which appears in dolfin but not
> firedrake. Here's a sketch of a possible solution:
>
> # This inheritance is just to pick up the methods
> class CoFunction(Function):
>       pass
>
> assemble(linear_form) => CoFunction
>
> And then we can raise errors when trying to use CoFunctions where
> Functions are expected (and vice versa). e.g. in solve(A, x, b), b should
> be a cofunction and x a function: the matrix A should really expose that is
> a linear operator between two function spaces.
>
> I think this then also gives us the ability to DTRT with your second
> example.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/497#issuecomment-88444541>
> .
>



-- 
Dr David Ham
Departments of Mathematics and Computing
Imperial College London

http://www.imperial.ac.uk/people/david.ham

**Comment by jrmaddison** [comment]
The analogy is Coefficient versus Function. Coefficient + Function makes sense (Function is a Coefficient) but only the latter need carry data.

**Comment by jrmaddison** [comment]
As an aside, to see how inconvenient this can be take a look at the branching in timestepping.pre_assembled_adjoint.PAAdjointSolvers.solve.

**Comment by danshapero** [comment]
This is discussed further in #1159 and #1084 . I think the conclusion is that CoFunction is a good thing and somebody should implement it.
