### ISSUE TITLE
Install documentation is not upgrade friendy

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#503]
Installation instructions work fine for first time install, but later repeating the given pip install instructions won't upgrade the packages, as they are already installed. It would be nice to use a set of flags which work both for first time install and for later upgrades.

Applies to both Firedrake and PyOP2.

**Comment by dham** [comment]
Would it work to just add --upgrade --no-deps to the usual pip instructions?

**Comment by miklos1** [comment]
I'm slightly wary that adding `--no-deps` might spoil the initial install case.

**Comment by kynan** [comment]
It might be worth adding dedicated update instructions, since that is not an infrequent case.

**Comment by miklos1** [comment]
I consider this complaint superseded by #571.
