### ISSUE TITLE
Nonlinear solver fails for linear problem

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#511]
The following code has the same problem first solved as a linear problem, then a nonlinear problem.
https://gist.github.com/colinjcotter/dadb8b1056f1d712a9b1

As a linear problem, lu decomposition works and solves fine. As a nonlinear problem, the Newton solver has not converged after 30 iterations.

**Comment by wence-** [comment]
If I run with 

```
"ksp_type": "gmres",
 "snes_monitor": True,
 "ksp_monitor_true_residual": True,
```

I see that although the krylov solver converges, the residual is not reduced at all (even in the linear case).  The linear case just turns off the convergence test for the outer snes.

```
  0 SNES Function norm 2.186262064328e+00 
    Residual norms for firedrake_snes_1_ solve.
    0 KSP preconditioned resid norm 7.587551882527e+01 true resid norm 2.186262064328e+00 ||r(i)||/||b|| 1.000000000000e+00
    1 KSP preconditioned resid norm 2.271516615050e-13 true resid norm 2.816285135209e-15 ||r(i)||/||b|| 1.288173628020e-15
  1 SNES Function norm 4.065567396075e+01 
```

If I run with 'snes_type': 'test', I can see that a jacobian computed by finite differencing the residual and the analytic jacobian are massively different.  I don't know what's going on there.

**Comment by tkarna** [comment]
I am seeing the same issue.

**Comment by wence-** [comment]
This looks like a kernel optimisation bug, it goes away when I drop down to `parameters["coffee"]["O2"] = False`.  Here's a more minimal example:

```python
from firedrake import *
from numpy import array
parameters["coffee"]["O2"] = True
parameters["assembly_cache"]["enabled"] = False
mesh = UnitTriangleMesh()
V = VectorFunctionSpace(mesh, "CG", 1)

u = TrialFunction(V)
v = TestFunction(V)

c = Constant(2)
a = (c*inner(v,u))*dx + inner(v,u)*dx
A = assemble(a)
print A.M.values
```

I expect to see 3 times a mass matrix, but instead see just a mass matrix.

**Comment by wence-** [comment]
This is now working again with the recent merges in coffee and ffc, hence closing.
