### ISSUE TITLE
Interpolating custom Expressions to Extruded Meshes not implemented?

### ISSUE THREAD

**Issue by anriseth** [firedrakeproject/firedrake#514]
Hi all,

I'm using Firedrake to run a Finite Volume method an a regular 3D mesh, using `ExtrudedMesh` and DG0 elements.

I need to interpolate a cellwise constant permeability field from a numpy array to my `FunctionSpace`.
This works on a `RectangularMesh(quadrilateral=True)`, but raises a `NotImplementedError` on the `ExtrudedMesh`. (See the code below).

Are there other ways to create a DG0 function on my 3D mesh from a numpy array?

``` python
from firedrake import *
import numpy as np 

Dx = 20; Dy = 10; Dz = 2
Nx = 10; Ny = 10; Nz = 10
Lx = Nx*Dx; Ly = Ny*Dy; Lz = Nz*Dz

meshbase = RectangleMesh(Nx, Ny, Lx, Ly, quadrilateral=True)
mesh = ExtrudedMesh(meshbase, Nz, Dz)

horiz_elt = FiniteElement("DG", quadrilateral, 0)
vert_elt = FiniteElement("DG", interval, 0)
elt = OuterProductElement(horiz_elt, vert_elt)

V = FunctionSpace(mesh, elt)
f = Function(V)

V2d = FunctionSpace(meshbase, horiz_elt)
f2d = Function(V2d)

perm_array = np.random.randn(Nx, Ny, Nz)

class Permeability(Expression):
    def eval(self, value, x):
        # Convert coordinate to ECLIPSE ordering (starting from zero)
        i = np.floor(x[0] / float(Dx))
        j = np.floor(x[1] / float(Dy))
        k = np.floor(x[2] / float(Dz))
        value[0] = perm_array[i, j, k]

class Perm2d(Expression):
    def eval(self, value, x):
        i = np.floor(x[0] / float(Dx))
        j = np.floor(x[1] / float(Dy))
        value[0] = perm_array[i, j, 0]

# This works
f2d.interpolate(Perm2d())
f2d.dat.data

# This does not (Throws NotImplementedError)
f.interpolate(Permeability())
f.dat.data
```

**Comment by wence-** [comment]
So the problem here is this interpolation of a python class goes through pyop2, and this functionality is not implemented: (see https://github.com/OP2/PyOP2/blob/master/pyop2/pyparloop.py#L107).

There are some hacky workarounds, but they're pretty ugly (and sort of rely on knowing what the dof-numbering will be (easy for DG0).

The python-level iteration over the mesh in the extruded case is somewhat more involved than the code already implemented in pyop2.  If you wanted to have a go, we can provide some guidance.

**Comment by anriseth** [comment]
Thanks for the help. A workaround using mesh.coordinates sorted out the issue:
```python
Vvec = VectorFunctionSpace(mesh, "DG", 0)
dg0coords = project(mesh.coordinates, Vvec)

@np.vectorize
def coordtoijk(x, y, z):
    i = np.floor(x / float(Dx))
    j = np.floor(y / float(Dy))
    k = np.floor(z / float(Dz))
    return perm_array[i, j, k]

f = Function(V)
f.dat.data[...] = coordtoijk(dg0coords.dat.data[:,0], dg0coords.dat.data[:,1], dg0coords.dat.data[:,2])
```

**Comment by wence-** [comment]
Thanks, I'll keep this open though.  Since the general case is not really treated by this workaround, to ensure we don't forget about it.

**Comment by wence-** [comment]
Will close again.
