### ISSUE TITLE
Point in cell queries

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#524]
This comes up from time to time.  It's half of "evaluation at arbitrary points", but is also necessary for things like delta function point sources.

This requires: 

- geometry querying routines.  Is a given point in a given cell?  In the presence of bendy, this presumably means pulling back to reference space and checking everything there.  Corollary, does one care about arbitrary precision accuracy?

- k-d tree partitioning to get to a "small" number of cells to query linearly fast.

Anything else?

**Comment by dham** [comment]
I believe libspatialindex is our friend with respect to providing the tree search.

**Comment by mlange05** [comment]
I just pushed a simple interface to rtree/libspatialindex that should be able to do a basic tree search. @dham, can you elaborate on the query routines, please?

**Comment by miklos1** [comment]
Implemented as part of #612, closing.
