### ISSUE TITLE
Nonlinear term causes Newton to fail even when multiplied by zero

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#527]
The following code:

https://gist.github.com/colinjcotter/149b19c763bff54d4758

causes Newton to fail. If you comment out line 29, then it converges. This is odd, because C2=0., so commenting should make no difference.

**Comment by wence-** [comment]
Your initial guess is zero, and the guilty term, `C2*Hinv*inner(v,u)*(inner(u,u)**0.5)` generates a linearisation which has a term:

`C2*(...)/inner(u, u)**0.5`  Which evaluates to `0.0/0.0` which generates NaNs in your jacobian.  Can you try with a non-zero initial guess (or, indeed, a non-zero C2?).

**Comment by wence-** [comment]
non-zero C2 won't fix, you'll just get `inf` rather than NaN in the jacobian.

**Comment by colinjcotter** [comment]
Ah yes! Thanks.

all the best
--cjc
