### ISSUE TITLE
An Expression is not a ufl.Coefficient

### ISSUE THREAD

**Issue by kynan** [firedrakeproject/firedrake#53]
Firedrake `Expression`s are somewhat defunct at the moment: They derived from `ufl.Coefficient` but they really are not coefficients i.e. `ufl.Coefficient.__init__` is never called and therefore a `firedrake.Expression` cannot be used as a `ufl.Coefficient`.

The reason is that information required to initialise a `Coefficient` (i.e. the element) is not available at the time the `Expression` is constructed.

**Comment by miklos1** [comment]
Currently the only case when we have to use `Expression`s is when calling `MeshGeometry.init_cell_orientations`. Given that `Expression`s are mostly superseded by UFL now as of #715, and they will potentially become deprecated in the future, I think this issue isn't relevant any more.
