### ISSUE TITLE
 Situation with wrong jacobian even when COFFEE is disabled. 

### ISSUE THREAD

**Issue by anriseth** [firedrakeproject/firedrake#530]
**EDIT**: I assumed the issue was conditionals. I can replicate the error without conditionals as well. Just use 
```python
F =  avg(u)*flow*jump(v)*dS
````

**Original**:
snes_type test shows large discrepancies between FD and Firedrake-supplied jacobian when I'm running a upwind scheme with conditionals. A simplified code, with parts of the output is shown below. The problem only appears if there are two adjacent cells where the unknown function is zero.

COFFEE is disabled.

```python
from firedrake import *
parameters["coffee"]["O2"] = False
sp = {
    'snes_type': 'test', 
    'snes_test_display': True,
}

mesh = UnitIntervalMesh(3)
V = FunctionSpace(mesh, "DG", 0)

xfun = Function(V).interpolate(Expression('x[0]'))
deltax = jump(xfun)
dist = abs(jump(xfun))

u = Function(V)
v = TestFunction(V)
u.dat.data[-1] = 1
# Uncommenting this gives the correct jacobian
# u.dat.data[0] = 1

EPS = 1e-12
rho_facet = avg(u) / (avg(u) + EPS) 

flow = rho_facet * deltax / dist
cond = conditional(lt(flow, 0.0), u('-'), u('+'))
F =  cond*flow*jump(v)*dS

solve(F == 0, u, solver_parameters=sp)
```

Output for the user-supplied state is shown below. SNESTEST works when evaluation happens at 1.0 and -1.0.

```
Finite difference Jacobian (user-defined state)
Mat Object: 1 MPI processes
  type: seqaij
row 0: (0, 0)  (1, -0.999905) 
row 1: (1, 0.999905)  (2, -1) 
row 2: (2, 1) 
Hand-coded Jacobian (user-defined state)
Mat Object: 1 MPI processes
  type: seqaij
row 0: (0, 0)  (1, 0) 
row 1: (0, 0)  (1, -1.99996e-12)  (2, -1) 
row 2: (1, 1.99996e-12)  (2, 1) 
Hand-coded minus finite difference Jacobian (user-defined state)
Mat Object: 1 MPI processes
  type: seqaij
row 0: (0, 0)  (1, 0.999905) 
row 1: (0, 0)  (1, -0.999905)  (2, 3.95915e-09) 
row 2: (1, 1.99996e-12)  (2, -3.95915e-09) 
Norm of matrix ratio 0.999905 difference 1.41408 (user-defined state)
```

**Comment by anriseth** [comment]
The issue seems to be the rho_facet part. 
To make it more clear why I need such a weird facet function: In my application, I do something like
```python
rho_facet = avg(u*f) / (avg(u) + EPS)
```
where f is some function.

**Comment by anriseth** [comment]
Sorry, the issue is my calculus. The function I'm trying to use is not continuous, let alone differentiable, at 0.

It is supposed to be a "saturation weighted" density,
```tex
\rho_{facet} = \frac{u('+')\rho('+') + u('-')\rho('-'))}{u('+') + u('-')}.
```
Need to rethink this ...

**Comment by wence-** [comment]
I guess you could try mollifying the discontinuity (maybe even just in the jacobian)

**Comment by anriseth** [comment]
It seems deciding on a limit point for rho_facet, and adding a conditional, gives a sufficiently good answer in my actual application. If things break later on, I'll test the mollification idea.

Like
```python
rho_expr = (u('-')*f('-') + u('+')*f('+')) / (u('-') + u('+') + EPS)
rho_facet = conditional(eq(u('-')+u('+'), 0.0), avg(f), rho_expr)
```
