### ISSUE TITLE
Potential caching bug

### ISSUE THREAD

**Issue by FabioLuporini** [firedrakeproject/firedrake#531]
Two tests in the regression test suite:
- test_assemble.py -> test_assemble_with_tensor
- test_assembly_cache.py -> test_assemble_rhs_with_without_constant
fail, for the same reason, on my machine (master everywhere), which is that assemble(v*dx) (.dat.data) is 0 instead of soemthing else

I can reproduce the bug only if I run the whole test suite (including /extrusion and /multigrid) -- with/without coffee doesn't make any difference -- If I run the individual tests with py.test -k, or even py.test regression/.. they work smoothly. So I suspect it's something to do with caching.

**Comment by wence-** [comment]
Similar to #386 and/or #319?

**Comment by FabioLuporini** [comment]
Yes, apparently disabling the assembly cache this disappears

**Comment by wence-** [comment]
Turns out if both of those are fixed this /still/ occurs.  Reduced test reproduction:

```
py.test tests/multigrid/test_restriction.py tests/regression/test_assemble.py -k 'not parallel' -v --ipdb
```

I don't really know what's going on still.

**Comment by wence-** [comment]
I wonder if the thing going on here is that the execution trace is "full", and when the copy par_loop that is part of the assembly caching copy-on-write setup for Dats is enqueued it is immediately executed and somehow things are out of whack and the wrong value is read.

In any case, I /really/ don't understand the dat versioning implementation, so my preferred option is to either kill the assembly cache + dat versioning, or lazy evaluation.

**Comment by FabioLuporini** [comment]
I'm against killing lazy for reasons I already mentioned. We could keep it disabled by default, though. 
Or we could kill the assembly cache + dat versioning.

**Comment by wence-** [comment]
I don't think I managed to fix this one.

**Comment by kynan** [comment]
These are the very same tests also failing in a container (see #561).
