### ISSUE TITLE
Nullspace causes memory error if 4 components in mixed Function space

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#535]
The following code causes crash:
https://gist.github.com/colinjcotter/6b136f056f702601b566

It doesn't crash if I remove the nullspace option.

**Comment by wence-** [comment]
WFM.

**Comment by colinjcotter** [comment]
I'll try to update my firedrake....

**Comment by colinjcotter** [comment]
I still get this with trunk everything.

**Comment by colinjcotter** [comment]
Here's what I get:
*** Error in `python': free(): invalid next size (fast): 0x0000000002e6cdd0 ***
[ma-gauss:07220] *** Process received signal ***
[ma-gauss:07220] Signal: Aborted (6)
[ma-gauss:07220] Signal code:  (-6)
[ma-gauss:07220] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f67c7faa340]
[ma-gauss:07220] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x39) [0x7f67c7c0bcc9]
[ma-gauss:07220] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7f67c7c0f0d8]
[ma-gauss:07220] [ 3] /lib/x86_64-linux-gnu/libc.so.6(+0x73394) [0x7f67c7c48394]
[ma-gauss:07220] [ 4] /lib/x86_64-linux-gnu/libc.so.6(+0x7f66e) [0x7f67c7c5466e]
[ma-gauss:07220] [ 5] /usr/local/lib/python2.7/dist-packages/petsc/lib/libpetsc.so.3.05(PetscFreeAlign+0x9) [0x7f67c593b665]
[ma-gauss:07220] [ 6] /usr/local/lib/python2.7/dist-packages/petsc/lib/libpetsc.so.3.05(+0x719c49) [0x7f67c5f67c49]
[ma-gauss:07220] [ 7] /usr/local/lib/python2.7/dist-packages/petsc/lib/libpetsc.so.3.05(PCSetUp+0x4ab) [0x7f67c5e9c893]
[ma-gauss:07220] [ 8] /usr/local/lib/python2.7/dist-packages/petsc/lib/libpetsc.so.3.05(KSPSetUp+0xbd5) [0x7f67c5f83048]
[ma-gauss:07220] [ 9] /usr/local/lib/python2.7/dist-packages/petsc/lib/libpetsc.so.3.05(KSPSolve+0x44f) [0x7f67c5f83645]
[ma-gauss:07220] [10] /usr/local/lib/python2.7/dist-packages/petsc/lib/libpetsc.so.3.05(+0x7ca523) [0x7f67c6018523]
[ma-gauss:07220] [11] /usr/local/lib/python2.7/dist-packages/petsc/lib/libpetsc.so.3.05(SNESSolve+0x6b8) [0x7f67c6051015]
[ma-gauss:07220] [12] /usr/local/lib/python2.7/dist-packages/petsc4py/lib/PETSc.so(+0xe1d5e) [0x7f67c683dd5e]
[ma-gauss:07220] [13] python(PyEval_EvalFrameEx+0x425) [0x52c6d5]
[ma-gauss:07220] [14] python() [0x56d0aa]
[ma-gauss:07220] [15] python(PyEval_EvalFrameEx+0x1f36) [0x52e1e6]
[ma-gauss:07220] [16] python(PyEval_EvalCodeEx+0x2a4) [0x55c594]
[ma-gauss:07220] [17] python(PyEval_EvalFrameEx+0x7dd) [0x52ca8d]
[ma-gauss:07220] [18] python(PyEval_EvalFrameEx+0xc82) [0x52cf32]
[ma-gauss:07220] [19] python(PyEval_EvalCodeEx+0x2a4) [0x55c594]
[ma-gauss:07220] [20] python(PyEval_EvalCode+0x32) [0x5b7392]
[ma-gauss:07220] [21] python() [0x469663]
[ma-gauss:07220] [22] python(PyRun_FileExFlags+0x92) [0x4699e3]
[ma-gauss:07220] [23] python(PyRun_SimpleFileExFlags+0x2ee) [0x469f1c]
[ma-gauss:07220] [24] python(Py_Main+0xb5e) [0x46ab81]
[ma-gauss:07220] [25] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f67c7bf6ec5]
[ma-gauss:07220] [26] python() [0x57497e]
[ma-gauss:07220] *** End

**Comment by wence-** [comment]
Crystal ball: please try with the fix-dmshell-malloc branch of petsc4py.

**Comment by wence-** [comment]
I think this is now fixed with recent change to petsc4py: please update petsc4py and retry

**Comment by colinjcotter** [comment]
confirmed, working, thanks
