### ISSUE TITLE
Facet support DoFs on extruded meshes

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#543]
This is primarily for @tkarna, but Firedrake developers may be interested, too.

Related: #536, #540, https://bitbucket.org/tkarna/fiat/branch/tensorelem_facetdofs

I have made an attempt to generalise and clean up the above FIAT branch, including:
- Supporting all extruded cell types: interval x interval, triangle x interval, quadrilateral x interval
- Support all function spaces: continuous, discontinuous, H(div) and H(curl) conforming
- Refactoring

These changes are in the `extruded-facet-support-dofs` branches of FIAT and FFC. A major design difference with respect to tkarna's branch is that there is no unified facet numbering for horizontal and vertical facets, but there are separate APIs for them, i.e. `horiz_facet_support_dofs` (0 = bottom, 1 = top) and `vert_facet_support_dofs` (same facet numbering as for the base cell) methods on the FIAT element.
Also these changes don't break any of the Firedrake tests.

Some further work (e.g. new test cases) is required before those changes can be merged, but I'd like to ask @tkarna for his feedback first, if it works for him.

**Comment by tkarna** [comment]
Thanks for implementing this, looks good to me. All my tests run fine with the appropriate change to firedrake functionspace.

**Comment by miklos1** [comment]
So I have written a few tests, and finally filed the corresponding pull requests:
 * #552 
 * https://bitbucket.org/mapdes/fiat/pull-request/33
 * https://bitbucket.org/mapdes/ffc/pull-request/82

I'm not sure what change if any to do on the Firedrake side. #540 unconditionally uses facet support dofs for the top and bottom mask, which - I think - works for @tkarna, but I'm not sure if we want to do this in general. As far as I understand ...
 * Geometrical and topological BCs do the same thing for CG elements
 * Topological has no effect on DG, but geometric does "the right thing" on DG
 * They do different things on H(div) conforming spaces, both of them might be meaningful. Topological sets a free slip boundary, while geometric a no slip boundary, although it does that by aggressively setting all dofs to zero which might contribute to the slip part.

The question is what would be a meaningful thing to do (if anything) at the Firedrake side.

**Comment by tkarna** [comment]
Generic firedrake implementation of this is in progress in branch [extruded_geometric_bcs](/firedrakeproject/firedrake/tree/extruded_geometric_bcs)

**Comment by miklos1** [comment]
Closing, since firedrakeproject/firedrake#600 and OP2/PyOP2#466 are now merged.
