### ISSUE TITLE
Rework solver parameter setting

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#550]
Right now, we generate a unique prefix for every solver and allow a user to specify an options_prefix by hand.  The petsc default is to have the same (NULL) prefix for everything unless set.  Due to how we then set options for solvers, things get messy really fast.  Furthermore, to kill various things from the petsc options database, we have custom __del__ methods that occasionally result in unfriendly error messages.

**Comment by stephankramer** [comment]
Can I flag this up again? My main bugbear is that when you use the same options_prefix twice, your solver options for the second solve may be totally ignored if they were already set in the first solve:

    from firedrake import *    
    mesh=UnitSquareMesh(10,10)    
    V = FunctionSpace(mesh, "CG", 1)
    v = TestFunction(V)
    u = Function(V)    
    F = v*u*dx-v*Constant(1.0)*dx==0

    solve(F, u, solver_parameters={'ksp_type': 'preonly', 'pc_type': 'lu'}, options_prefix='foo_')
    # should fail with unknown pc_type, but gets ignored:
    solve(F, u, solver_parameters={'ksp_type': 'preonly', 'pc_type': 'bork'}, options_prefix='foo_')

The reason for this is that in the first call the prefixed options ('foo_ksp_type', etc.) are inserted in the global PETSc.Options dictionary and never removed again. In the second solve, it then overrides the provided solver_parameters with those already present in PETSc.Options (on the erronous assumption that they were command-line arguments).

One could argue of course that people shouldn't be using the same prefix for two different solves, but just as an example where this goes wrong: in Thetis we prefix the solves with the name of the time integrator. Now if I setup a problem in two separate tests that happen to use the same time integration scheme, and I run them in the same py.test session (as on Travis) the second test still picks up solver options from the first test (and those of the first test always win).

Not entirely sure how to fix this properly. In particular, if you also want to support two solvers with the same options_prefix to exist concurrently it is very unclear when which options should be set in PETSc.Options(). If you at least assume the first solver is deleted before the second one, you could try to fix PETSc.Options() - but you'd have to be careful not to overwrite options that were actually set on the command line. A completely different approach would be to always use an auto_prefix and only use the provided options_prefix to pull command-line options from PETSc.Options() and stick these back in with options_prefix replaced by the auto_prefix.

**Comment by wence-** [comment]
Of these options, I like the last one of always using a generated prefix but allowing the options_prefix thing to decide where to pull things out.

**Comment by wence-** [comment]
Done as part of #882.
