### ISSUE TITLE
Trace evaluation triggered by Constant assignment

### ISSUE THREAD

**Issue by FabioLuporini** [firedrakeproject/firedrake#567]
So I didn't know what was the right place to file this issue. Also, I don't even know whether this actually is an issue... it is for me (fusion), but don't know in general. So, here we go:

in `constants.py`, when we assign to a Constant, we do 

    self.dat.data = value

now this triggers the evaluation of the trace up to that point (I mean, the loops touching that dat, as far as I can understand) since in PyOP2, in class Dat, we have that accessing the (modifiable) property "data" triggers `trace.evaluate()`

I don't know if there's a work around to this

**Comment by wence-** [comment]
I don't know how you can "work around" this.  Assigning to that value /has/ to force evaluation of the trace of par_loops that read that constant.

**Comment by FabioLuporini** [comment]
so if I have (an example extracted from firedrake-bench/wave): 
bcval.assign(sin(2*t))
if "t" is the timestepping loop iteration variable, then we have that the bc changes in time, but its actual value is independent of any parloop execution. So it's the same dat that changes, but conceptually you could think of having N different (known) boundary conditions. Unless I'm missing something?

Anyway, you're saying that there's not much we can do here and I understand that.

**Comment by FabioLuporini** [comment]
by the way: it changes, so it's not a "real constant" indeed. I mean, it's a constant in the time loop iteration...isn't it?

**Comment by wence-** [comment]
It's "spatially constant".  You have to treat this exactly like you would treat a sequence of par_loops where the user accesses (and messes with) the value of a Dat.  I don't understand how you can not force evaluation at this point.

**Comment by FabioLuporini** [comment]
As I said, I understand your point that there's no easy of way of doing that. However, *theoretically*, you could somehow not force the evaluation, in the sense that this is not a global synchronisation point for which there's no getaway. 

Here we have:
parloop_1 (...d...) 
parloop_2 (...d...)
d = ...
parloop_1 (...d...) 
parloop_2 (...d...)
d = ...
...
so we're saying: ok, d is about to be modified, you guys that need it, just use it. Now.

But *theoretically* (I'm not saying I wanna do this), as far as I can understand, one could think of implementing something that behaves as follows:
parloop_1 (...d...) 
parloop_2 (...d...)
d' = ...
parloop_1 (...d'...) 
parloop_2 (...d'...)
d'' = ...
...

I just wanted to emphasise the fact that we are forcing the evaluation not because we have to, but because it's just way simpler.

Unless I'm missing something. Which could well be

**Comment by wence-** [comment]
OK, I see.  You can make that assignment into a lazy operation that sits in the queue if you like.  But you'll have to think about how to do this right.

**Comment by wence-** [comment]
I'm going to close this, it's not really a bug.  Changing this would require redesigning how the user interacts with pyop2 data objects.
