### ISSUE TITLE
firedrake-install script, package installation

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#575]
I prefer to let PETSc download and build hdf5 (mostly because I don't trust ubuntu packagers), because I'm also using it to build an MPI library and they have to be compatible.  It should be possible to skip package installation.

**Comment by wence-** [comment]
In particular, the installation process assumes I have sudo access on the machine I'm installing.  Which is not true on my system (at the very least).

**Comment by dham** [comment]
I claim this is now fixed.
