### ISSUE TITLE
firedrake-install should pass through unknown options to python interpreter

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#576]
It should be possible to pass "unrecognised" options through to the python interpreter (so that one can, for example, drop into the debugger in case of error).  Normal practice is something like:

```python firedrake-install --developer -- --unknown-option```

**Comment by dham** [comment]
I don't understand. Mistyped or non-existent options should be an error. You can pass options to the python interpreter with:

python --myoption firedrake-install ...

**Comment by wence-** [comment]
Oh, I see, fine.
