### ISSUE TITLE
For dev branches built on Travis, install script does not do what I expect it to do

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#579]
https://travis-ci.org/firedrakeproject/firedrake/jobs/77323727 has passed, while it clearly should be a failure, due to requiring special and extra dependencies (libspatialindex, ffc@compile-element, fiat@symbolic-tabulate).

According to the log, the added test (`tests/regression/test_compile_element.py` and `tests/regression/test_visualise.py`) are not even run.

Oddly, lines 560-561 say:
```
$ git checkout $BRANCH
Your branch is up-to-date with 'origin/master'.
```
Seems like it's testing master instead of my branch.

**Comment by dham** [comment]
Crap. 

The message is consistent with $BRANCH not being set.

**Comment by wence-** [comment]
You don't care that you're on a branch.  Do:

```sh
COMMIT=$(git rev-parse HEAD)
...
git checkout $COMMIT
```

no?

**Comment by dham** [comment]
Why would that work when the branch doesn't? Surely the issue is that the variable is not set when you get to the checkout line.

**Comment by wence-** [comment]
```
git checkout HEAD~
X=$(git symbolic-ref --short -q HEAD)
echo $X
```

As opposed to:
```
git checkout HEAD~
X=$(git rev-parse HEAD)
echo $X
```

**Comment by miklos1** [comment]
It is better now, however I'd still like to post this snippet from the Travis output:
```
$ if git fetch origin pull/$TRAVIS_PULL_REQUEST/merge; then git checkout FETCH_HEAD; else git checkout $TRAVIS_COMMIT; fi

fatal: Couldn't find remote ref pull/false/merge

Unexpected end of command stream

Note: checking out '76876a4b5b27b20b5212278061e9fc5802b7b8ed'.

You are in 'detached HEAD' state. You can look around, make experimental

changes and commit them, and you can discard any commits you make in this

state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may

do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 76876a4... test cases for quadrilaterals
```
source: https://travis-ci.org/firedrakeproject/firedrake/builds/77671685

Otherwise the test results look reasonable on that branch.

**Comment by miklos1** [comment]
https://travis-ci.org/firedrakeproject/firedrake/builds/77672276 fails consistently for not having libspatialindex. That's correct.

**Comment by wence-** [comment]
`TRAVIS_PULL_REQUEST` is either a number (if you're testing a pull request) or else `false` (when testing a pushed branch).  So this line should handle that case and fetch the pull request if it is one, but otherwise do something else.  I note the following variables may be of use (from the travis docs):


> `TRAVIS_BRANCH`: For builds not triggered by a pull request this is the name of the branch currently 
> being built; whereas for builds triggered by a pull request this is the name of the branch targeted by the
> pull request (in many cases this will be `master`).
> `TRAVIS_COMMIT`: The commit that the current build is testing.
> `TRAVIS_PULL_REQUEST`: The pull request number if the current job is a pull request, `"false"` if it’s not a pull request.
