### ISSUE TITLE
matnest=False + LU gives NaNs?

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#584]
Standard mixed-Poisson problem, assuming I haven't done anything stupid....

Dirichlet BC: scalar variable = 0 on all sides.  This is enforced weakly by dropping the surface integral when integrating by parts.

```
from firedrake import *

#parameters["matnest"] = False

mesh = UnitSquareMesh(3, 3)

V1 = FunctionSpace(mesh, "RT", 1)
V2 = FunctionSpace(mesh, "DG", 0)
W = V1*V2

sigma, u = TrialFunctions(W)
tau, v = TestFunctions(W)

f = Constant(1.0)

a = (dot(tau, sigma) + v*div(sigma) - u*div(tau))*dx
L = v*f*dx

out = Function(W)
solve(a == L, out)#, solver_parameters={'ksp_type': 'preonly', 'pc_type': 'lu'})

print out.dat.data[0]
print out.dat.data[1]
```

As written, this appears to work.  However, switching to LU, and disabling matnest, gives nans in out.dat.data.

**Comment by wence-** [comment]
Petsc LU I believe does no pivoting by default. Can you either try with (say) mumps: pc_factor_mat_solver_package: mumps or turn on pivoting pc_factor_mat_shift_type: nonzero

**Comment by dorugeber** [comment]
Ah, I can believe that.  Indeed, adding a u*v term to my LHS got rid of the nans with those solver options.

I don't have mumps installed; the latter option still gave nans, but using `'pc_factor_nonzeros_along_diagonal': True` instead worked.  Closing.
