### ISSUE TITLE
Is this a matnest+VFS issue, or just a PEBKAC?

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#585]
The following code segfaults on my machine.  On a 3x3 mesh, I get a numerical answer.  On a 4x4 mesh, I get nans.  Commenting out the matnest-disable line and not using any special solver parameters, I get a numerical answer on 8x8 but `Inner linear solve failed to converge after 10000 iterations with reason: DIVERGED_MAX_IT` on 16x16.

The matrix doesn't appear to be singular.

Edit: yes, I'm deliberately doing a 2D mixed-Poisson with a bad combination of spaces.

```
from firedrake import *

parameters["matnest"] = False

mesh = UnitSquareMesh(16, 16)

V1 = VectorFunctionSpace(mesh, "CG", 1)
V2 = FunctionSpace(mesh, "DG", 0)
W = V1*V2

sigma, u = TrialFunctions(W)
tau, v = TestFunctions(W)

f = Constant(1.0)

a = (dot(tau, sigma) + v*div(sigma) - u*div(tau))*dx
L = v*f*dx

out = Function(W)
solve(a == L, out, solver_parameters={'ksp_type': 'preonly', 'pc_factor_nonzeros_along_diagonal': True, 'pc_type': 'lu'})
#solve(a == L, out)

print out.dat.data[0]
```

**Comment by wence-** [comment]
Coming back to this, I think this is pebkac.  You need to tell PETSc's LU to do some pivoting: `-pc_factor_shift_type nonzero`.

**Comment by wence-** [comment]
Is the closeable?  As mentioned, I think you just needed to provide appropriate extra options.

**Comment by dorugeber** [comment]
Yes.
