### ISSUE TITLE
User specifying different forms on different processors produces unhelpful error message.

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#591]
The good Dr Cotter, in attempting to solve a PDE with stochastic forcing, managed to create a situation in which the form includes a different random value on each processor. This causes different code to be generated with a different hash, so processors other than the principal processor fail to find the .so they need.

It would be better if different processes having different hashes was actually caught and a useful error raised.

**Comment by wence-** [comment]
parameters["pyop2_options"]["check_src_hashes"] = True

This does an allgather so is not scalable, hence not on by default.

**Comment by dham** [comment]
How about defaulting it on if nprocs < n for some suitable n?

**Comment by colinjcotter** [comment]
This was definitely my favourite bug I have caused in Firedrake to date...

--cjc

On 4 September 2015 at 14:59, David Ham <notifications@github.com> wrote:

> The good Dr Cotter, in attempting to solve a PDE with stochastic forcing,
> managed to create a situation in which the form includes a different random
> value on each processor. This causes different code to be generated with a
> different hash, so processors other than the principle processor fail to
> find the .so they need.
>
> It would be better if different processes having different hashes was
> actually caught and a useful error raised.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/591>.
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by miklos1** [comment]
I think instead of `MPI_Gather`, we should apply `MPI_Reduce` (or `MPI_Allreduce`) to the source hashes with a custom reduction operator, defined as:
op(x, x) = x
op(x, y) = ⊥, if x != y
op(x, ⊥) = ⊥
op(⊥, x) = ⊥

**Comment by wence-** [comment]
Fixed by PyOP2 change.
