### ISSUE TITLE
Interior facet kernels have lines in nondeterministic order.

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#599]
The tensor insertion lines for interior facet kernels appear to happen in nondeterministic order. This causes intermittent failures in parallel due to different ranks generating different code. See: https://gist.github.com/dham/1fbeb0e56484cfc19073

The following fails intermittently:
```
firedrake-clean
mpirun -n 2 ipython nondeterministic.py
```

**Comment by wence-** [comment]
Does https://bitbucket.org/mapdes/ffc/pull-requests/79/sort-entry-ir-to-ensure-deterministic/diff help?

It's a disgusting hack, but maybe we should just merge

**Comment by tkarna** [comment]
@wence- Thanks, that seems to fix it, I haven't been able to reproduce the error anymore. Also more complex forms compile in parallel now.
