### ISSUE TITLE
Strong bcs broken with petsc with debugging enabled

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#607]
With a petsc build with debugging enabled all problems that have strong dirichlet bcs associated with them seem to be broken. When inspecting the values of the assembled jacobian matrix it appears that all rows associated with non-boundary nodes are zeroed, e.g. in the following:

    from firedrake import *
    mesh=UnitSquareMesh(2,2)
    V=FunctionSpace(mesh, "CG", 1)
    u=Function(V)
    v=TestFunction(V)
    bcs=(DirichletBC(V, 0, 1), )
    print assemble(derivative(v*u*dx-v*dx, u), bcs=bcs).M.values

I think this is because of the way that the bcs are inserted in the matrix. This mixes up the INSERT_VALUES and ADD_VALUES mode in calls to MatSetValues, which is not allowed. It first *inserts* the diagonal pivots associated with the boundary nodes (firedrake/assemble.py:433) and then later on *adds* in the finite element integrals. Petsc with debugging enabled, errors out (src/mat/interface.c:2000 in petsc), whereas without debugging it happily continues and "does the right thing".

It probably just needs a MatAssemblyBegin/End(mat, MAT_FLUSH_ASSEMBLY) inbetween the two stages.

**Comment by wence-** [comment]
Thanks, yes, I agree, will see how best to put that flush in.

**Comment by wence-** [comment]
This turns out to be sort of complicated, because the insertion of values is done "lazily" but the diagonal setting is not.  So it will be a slightly bigger fix.  I think the thing to do is to turn the diagonal setting into a lazy operation too, then everything will work.

**Comment by wence-** [comment]
I think I have fixed this in OP2/PyOP2#474.  To test this in firedrake, I think we need to switch travis to building PETSc with debugging enabled.  I will try this in a branch to see if it doesn't blow the testing time out of the water.

**Comment by wence-** [comment]
That change is now in PyOP2, so I claim this is fixed.  at least the provided test case is fine.
