### ISSUE TITLE
wrong cell size 

### ISSUE THREAD

**Issue by FabioLuporini** [firedrakeproject/firedrake#608]
This code:

from firedrake import *
Lx=300.0; Ly=150.0; h=2.5
mesh = RectangleMesh(int(Lx/h), int(Ly/h), Lx, Ly)
print assemble(CellSize(mesh)*dx)

returns 159099.025767 instead of ~2.5. What am I doing wrong? Thanks

**Comment by dorugeber** [comment]
Why would you expect this to return 2.5?  It returns the circumdiameter of each cell (2.5*sqrt(2)) multiplied by the area of the mesh, 300*150.

http://www.wolframalpha.com/input/?i=2.5*sqrt%282%29*300*150

**Comment by FabioLuporini** [comment]
ah, I was just reporting an observation from @ctjacobs , not even thought for a second about that, honestly. Maybe he has other concerns that I misunderstood ?

**Comment by ctjacobs** [comment]
No, this makes sense now. Thanks.
