### ISSUE TITLE
Getting solution as array.

### ISSUE THREAD

**Issue by silkbottle** [firedrakeproject/firedrake#615]
Hello,

Is there a way to get an actual solution as array on the grid pointwise or it only can be viewed in paraview? I found only one way to open it in paraview and convert to csv.

**Comment by dham** [comment]
Hello,

If by "actual solution" you mean the degree of freedom values, then this is easy. If `f` is a `Function` then `f.dat.data` is a numpy array containing the DoF values. You can also obtain the DoF values of the coordinate field (which for the usual case means the coordinates of the mesh vertices). If `m` is a `Mesh` then `m.coordinates.dat.data` is the numpy array of the coordinate values. 

Note that the DoF values of a field only correspond 1:1 with the Function DoF values if the Function is in the FunctionSpace CG1.
