### ISSUE TITLE
Installation issue mac os x (maverick)

### ISSUE THREAD

**Issue by earendilllock** [firedrakeproject/firedrake#618]
Dear all,
I have successfully installed all the dependencies due to http://www.firedrakeproject.org/download.html (Manual installation, cause script doesn't work for me). 

after the command :
pip install git+https://github.com/firedrakeproject/firedrake.git

I've obtained such a message:

 Cloning https://github.com/firedrakeproject/firedrake.git to /var/folders/8d/3ktv2nyd1sx0v5ylgblqy1j00000gn/T/pip-9SXC7w-build
Installing collected packages: firedrake
  Running setup.py install for firedrake
    Complete output from command /Users/earendilllock/anaconda/bin/python -c "import setuptools, tokenize;__file__='/var/folders/8d/3ktv2nyd1sx0v5ylgblqy1j00000gn/T/pip-9SXC7w-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/8d/3ktv2nyd1sx0v5ylgblqy1j00000gn/T/pip-W8Tmph-record/install-record.txt --single-version-externally-managed --compile:
    /Users/earendilllock/anaconda/lib/python2.7/site-packages/setuptools/dist.py:294: UserWarning: The version specified ('0.11.0-775-g1eae5ba') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    running install
    running build
    got version from git {'version': '0.11.0-775-g1eae5ba', 'full': '1eae5ba864914dccfc3e35e029cce43183ec3eeb'}
    running build_py
    creating build
    creating build/lib.macosx-10.5-x86_64-2.7
    creating build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/_version.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/assemble.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/assemble_expressions.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/assembly_cache.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/bcs.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/constant.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/expression.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/extrusion_utils.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/ffc_interface.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/fiat_utils.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/function.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/functionspace.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/halo.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/io.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/linear_solver.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/matrix.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/mesh.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/norms.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/nullspace.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/optimizer.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/parameters.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/parloops.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/petsc.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/projection.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/solving.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/solving_utils.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/ufl_expr.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/utility_meshes.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/utils.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/variational_solver.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/vector.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    copying firedrake/version.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    creating build/lib.macosx-10.5-x86_64-2.7/evtk
    copying evtk/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/evtk
    copying evtk/hl.py -> build/lib.macosx-10.5-x86_64-2.7/evtk
    copying evtk/vtk.py -> build/lib.macosx-10.5-x86_64-2.7/evtk
    copying evtk/xml.py -> build/lib.macosx-10.5-x86_64-2.7/evtk
    creating build/lib.macosx-10.5-x86_64-2.7/firedrake/mg
    copying firedrake/mg/__init__.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake/mg
    copying firedrake/mg/function.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake/mg
    copying firedrake/mg/functionspace.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake/mg
    copying firedrake/mg/interface.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake/mg
    copying firedrake/mg/mesh.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake/mg
    copying firedrake/mg/solver_hierarchy.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake/mg
    copying firedrake/mg/ufl_utils.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake/mg
    copying firedrake/mg/utils.py -> build/lib.macosx-10.5-x86_64-2.7/firedrake/mg
    copying firedrake/firedrake_geometry.h -> build/lib.macosx-10.5-x86_64-2.7/firedrake
    running build_ext
    cythoning firedrake/dmplex.pyx to firedrake/dmplex.c
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    import numpy as np
    cimport numpy as np
    import cython
    cimport petsc4py.PETSc as PETSc
    
    cimport mpi4py.MPI as MPI
           ^
    ------------------------------------------------------------
    
    firedrake/dmplex.pyx:9:8: 'mpi4py/MPI.pxd' not found
    warning: firedrake/dmplex.pyx:1079:4: Buffer unpacking not optimized away.
    warning: firedrake/dmplex.pyx:1079:4: Buffer unpacking not optimized away.
    warning: firedrake/dmplex.pyx:1471:4: Buffer unpacking not optimized away.
    warning: firedrake/dmplex.pyx:1471:4: Buffer unpacking not optimized away.
    warning: firedrake/dmplex.pyx:1472:4: Buffer unpacking not optimized away.
    warning: firedrake/dmplex.pyx:1472:4: Buffer unpacking not optimized away.
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
                               new_ilocal, PETSC_OWN_POINTER,
                               new_iremote, PETSC_OWN_POINTER))
        return pruned_sf
    
    
    def halo_begin(PETSc.SF sf, dat, MPI.Datatype dtype, reverse):
                                    ^
    ------------------------------------------------------------
    
    firedrake/dmplex.pyx:1859:33: 'Datatype' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            CHKERR(PetscSFBcastBegin(sf.sf, dtype.ob_mpi,
                                     <const void *>buf.data,
                                     <void *>buf.data))
    
    
    def halo_end(PETSc.SF sf, dat, MPI.Datatype dtype, reverse):
                                  ^
    ------------------------------------------------------------
    
    firedrake/dmplex.pyx:1894:31: 'Datatype' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        cdef:
            PETSc.SF sf
            PetscInt nroots, nleaves
            PetscInt *ilocal
            PetscSFNode *iremote
            MPI.Datatype dtype = MPI.INT
           ^
    ------------------------------------------------------------
    
    firedrake/dmplex.pyx:1767:8: 'Datatype' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        Forward exchanges are implemented using :data:`PetscSFBcastBegin`,
        reverse exchanges with :data:`PetscSFReduceBegin`.
        """
        cdef:
            MPI.Op op = MPI.SUM
           ^
    ------------------------------------------------------------
    
    firedrake/dmplex.pyx:1872:8: 'Op' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
        Forward exchanges are implemented using :data:`PetscSFBcastEnd`,
        reverse exchanges with :data:`PetscSFReduceEnd`.
        """
        cdef:
            MPI.Op op = MPI.SUM
           ^
    ------------------------------------------------------------
    
    firedrake/dmplex.pyx:1907:8: 'Op' is not a type identifier
    building 'firedrake.dmplex' extension
    creating build/temp.macosx-10.5-x86_64-2.7
    creating build/temp.macosx-10.5-x86_64-2.7/firedrake
    mpicc -fno-strict-aliasing -I/Users/earendilllock/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/earendilllock/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/earendilllock/anaconda/lib/python2.7/site-packages/petsc4py/include -I/Users/earendilllock/anaconda/lib/python2.7/site-packages/petsc/include -I/Users/earendilllock/anaconda/include/python2.7 -c firedrake/dmplex.c -o build/temp.macosx-10.5-x86_64-2.7/firedrake/dmplex.o
    firedrake/dmplex.c:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
    #error Do not use this file, it is the result of a failed Cython compilation.
     ^
    1 error generated.
    error: command 'mpicc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/earendilllock/anaconda/bin/python -c "import setuptools, tokenize;__file__='/var/folders/8d/3ktv2nyd1sx0v5ylgblqy1j00000gn/T/pip-9SXC7w-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/8d/3ktv2nyd1sx0v5ylgblqy1j00000gn/T/pip-W8Tmph-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /var/folders/8d/3ktv2nyd1sx0v5ylgblqy1j00000gn/T/pip-9SXC7w-build

Could you please help me to obtain firedrake (the ideal solution would be anaconda package for os x), but I would very pleased of any help.

**Comment by miklos1** [comment]
firedrake/dmplex.pyx:9:8: 'mpi4py/MPI.pxd' not found
Apparently the Firedrake installation does not find mpi4py.

Can you tell what the problem is when you try it with the install script?

**Comment by dham** [comment]
I think the following is your principal issue:

```
cimport mpi4py.MPI as MPI
       ^
------------------------------------------------------------

firedrake/dmplex.pyx:9:8: 'mpi4py/MPI.pxd' not found
```

So it appears Cython is not correctly finding your mpi4py installation. Could you try the following:

Run python and import mpi4py. Then try importing mpi4py.MPI. If that fails then there is a direct issue with how you've installed mpi4py.

**Comment by earendilllock** [comment]
Here's the message after I've runned the script 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0python firedrake-install
100 19358  100 19358    0     0  18907      0  0:00:01  0:00:01 --:--:-- 18922
MacBook-Air-Maksim:firedrake earendilllock$ python firedrake-install
Xcode 6.3.2
Build version 6D2105
0.9.5 (git revision daf9a; last commit 2015-10-22)
Installing required packages via homebrew. You can safely ignore warnings that packages are already installed
/usr/local/Cellar/open-mpi/1.10.0/bin/mpic++
/usr/local/Cellar/open-mpi/1.10.0/bin/mpic++-vt
/usr/local/Cellar/open-mpi/1.10.0/bin/mpicc
/usr/local/Cellar/open-mpi/1.10.0/bin/mpicc-vt
/usr/local/Cellar/open-mpi/1.10.0/bin/mpicxx
/usr/local/Cellar/open-mpi/1.10.0/bin/mpicxx-vt
/usr/local/Cellar/open-mpi/1.10.0/bin/mpiexec
/usr/local/Cellar/open-mpi/1.10.0/bin/mpif77
/usr/local/Cellar/open-mpi/1.10.0/bin/mpif77-vt
/usr/local/Cellar/open-mpi/1.10.0/bin/mpif90
/usr/local/Cellar/open-mpi/1.10.0/bin/mpif90-vt
/usr/local/Cellar/open-mpi/1.10.0/bin/mpifort
/usr/local/Cellar/open-mpi/1.10.0/bin/mpifort-vt
/usr/local/Cellar/open-mpi/1.10.0/bin/mpirun
/usr/local/Cellar/open-mpi/1.10.0/bin/ompi-clean
/usr/local/Cellar/open-mpi/1.10.0/bin/ompi-ps
/usr/local/Cellar/open-mpi/1.10.0/bin/ompi-server
/usr/local/Cellar/open-mpi/1.10.0/bin/ompi-top
/usr/local/Cellar/open-mpi/1.10.0/bin/ompi_info
/usr/local/Cellar/open-mpi/1.10.0/bin/opal_wrapper
/usr/local/Cellar/open-mpi/1.10.0/bin/orte-clean
/usr/local/Cellar/open-mpi/1.10.0/bin/orte-dvm
/usr/local/Cellar/open-mpi/1.10.0/bin/orte-info
/usr/local/Cellar/open-mpi/1.10.0/bin/orte-ps
/usr/local/Cellar/open-mpi/1.10.0/bin/orte-server
/usr/local/Cellar/open-mpi/1.10.0/bin/orte-submit
/usr/local/Cellar/open-mpi/1.10.0/bin/orte-top
/usr/local/Cellar/open-mpi/1.10.0/bin/ortecc
/usr/local/Cellar/open-mpi/1.10.0/bin/orted
/usr/local/Cellar/open-mpi/1.10.0/bin/orterun
/usr/local/Cellar/open-mpi/1.10.0/bin/otfaux
/usr/local/Cellar/open-mpi/1.10.0/bin/otfcompress
/usr/local/Cellar/open-mpi/1.10.0/bin/otfconfig
/usr/local/Cellar/open-mpi/1.10.0/bin/otfdecompress
/usr/local/Cellar/open-mpi/1.10.0/bin/otfinfo
/usr/local/Cellar/open-mpi/1.10.0/bin/otfmerge
/usr/local/Cellar/open-mpi/1.10.0/bin/otfmerge-mpi
/usr/local/Cellar/open-mpi/1.10.0/bin/otfprint
/usr/local/Cellar/open-mpi/1.10.0/bin/otfprofile
/usr/local/Cellar/open-mpi/1.10.0/bin/otfprofile-mpi
/usr/local/Cellar/open-mpi/1.10.0/bin/otfshrink
/usr/local/Cellar/open-mpi/1.10.0/bin/vtc++
/usr/local/Cellar/open-mpi/1.10.0/bin/vtcc
/usr/local/Cellar/open-mpi/1.10.0/bin/vtcxx
/usr/local/Cellar/open-mpi/1.10.0/bin/vtf77
/usr/local/Cellar/open-mpi/1.10.0/bin/vtf90
/usr/local/Cellar/open-mpi/1.10.0/bin/vtfilter
/usr/local/Cellar/open-mpi/1.10.0/bin/vtfilter-mpi
/usr/local/Cellar/open-mpi/1.10.0/bin/vtfiltergen
/usr/local/Cellar/open-mpi/1.10.0/bin/vtfiltergen-mpi
/usr/local/Cellar/open-mpi/1.10.0/bin/vtfort
/usr/local/Cellar/open-mpi/1.10.0/bin/vtjava
/usr/local/Cellar/open-mpi/1.10.0/bin/vtrun
/usr/local/Cellar/open-mpi/1.10.0/bin/vtsetup
/usr/local/Cellar/open-mpi/1.10.0/bin/vtunify
/usr/local/Cellar/open-mpi/1.10.0/bin/vtunify-mpi
/usr/local/Cellar/open-mpi/1.10.0/bin/vtwrapper
/usr/local/Cellar/open-mpi/1.10.0/etc/ (6 files)
/usr/local/Cellar/open-mpi/1.10.0/include/mpp/ (2 files)
/usr/local/Cellar/open-mpi/1.10.0/include/openmpi/ (31 files)
/usr/local/Cellar/open-mpi/1.10.0/include/vampirtrace/ (42 files)
/usr/local/Cellar/open-mpi/1.10.0/include/ (25 files)
/usr/local/Cellar/open-mpi/1.10.0/lib/libmca_common_sm.4.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libmpi.12.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libmpi_cxx.1.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libmpi_mpifh.12.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libmpi_usempif08.11.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libompitrace.0.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libopen-pal.13.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libopen-rte.12.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libopen-trace-format.1.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libotfaux.0.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libvt-hyb.0.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libvt-java.0.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libvt-mpi-unify.0.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libvt-mpi.0.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libvt-mt.0.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/libvt.0.dylib
/usr/local/Cellar/open-mpi/1.10.0/lib/openmpi/ (102 files)
/usr/local/Cellar/open-mpi/1.10.0/lib/pkgconfig/ (7 files)
/usr/local/Cellar/open-mpi/1.10.0/lib/ (25 other files)
/usr/local/Cellar/open-mpi/1.10.0/libexec/vtsetup.jar
/usr/local/Cellar/open-mpi/1.10.0/share/man/ (402 files)
/usr/local/Cellar/open-mpi/1.10.0/share/openmpi/ (93 files)
/usr/local/Cellar/open-mpi/1.10.0/share/vampirtrace/ (27 files)
/usr/local/Cellar/python/2.7.10_2/bin/2to3
/usr/local/Cellar/python/2.7.10_2/bin/2to3-2
/usr/local/Cellar/python/2.7.10_2/bin/2to3-2.7
/usr/local/Cellar/python/2.7.10_2/bin/easy_install
/usr/local/Cellar/python/2.7.10_2/bin/easy_install-2.7
/usr/local/Cellar/python/2.7.10_2/bin/idle
/usr/local/Cellar/python/2.7.10_2/bin/idle2
/usr/local/Cellar/python/2.7.10_2/bin/idle2.7
/usr/local/Cellar/python/2.7.10_2/bin/pip
/usr/local/Cellar/python/2.7.10_2/bin/pip2
/usr/local/Cellar/python/2.7.10_2/bin/pip2.7
/usr/local/Cellar/python/2.7.10_2/bin/pydoc
/usr/local/Cellar/python/2.7.10_2/bin/pydoc2
/usr/local/Cellar/python/2.7.10_2/bin/pydoc2.7
/usr/local/Cellar/python/2.7.10_2/bin/python
/usr/local/Cellar/python/2.7.10_2/bin/python-config
/usr/local/Cellar/python/2.7.10_2/bin/python2
/usr/local/Cellar/python/2.7.10_2/bin/python2-config
/usr/local/Cellar/python/2.7.10_2/bin/python2.7
/usr/local/Cellar/python/2.7.10_2/bin/python2.7-config
/usr/local/Cellar/python/2.7.10_2/bin/pythonw
/usr/local/Cellar/python/2.7.10_2/bin/pythonw2
/usr/local/Cellar/python/2.7.10_2/bin/pythonw2.7
/usr/local/Cellar/python/2.7.10_2/bin/smtpd.py
/usr/local/Cellar/python/2.7.10_2/bin/smtpd2.7.py
/usr/local/Cellar/python/2.7.10_2/bin/smtpd2.py
/usr/local/Cellar/python/2.7.10_2/bin/wheel
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/ (3720 files)
/usr/local/Cellar/python/2.7.10_2/IDLE.app/Contents/ (8 files)
/usr/local/Cellar/python/2.7.10_2/lib/pkgconfig/ (3 files)
/usr/local/Cellar/python/2.7.10_2/libexec/pip/ (499 files)
/usr/local/Cellar/python/2.7.10_2/libexec/setuptools/ (226 files)
/usr/local/Cellar/python/2.7.10_2/libexec/wheel/ (93 files)
/usr/local/Cellar/python/2.7.10_2/Python Launcher.app/Contents/ (17 files)
/usr/local/Cellar/python/2.7.10_2/share/man/ (3 files)
/usr/local/Cellar/python/2.7.10_2/share/python/ (315 files)
Warning: homebrew/python already tapped!
/usr/local/Cellar/numpy/1.10.1/bin/f2py
/usr/local/Cellar/numpy/1.10.1/lib/python2.7/ (396 files)
/usr/local/Cellar/numpy/1.10.1/libexec/nose/ (57 files)
/usr/local/Cellar/swig/3.0.7/bin/ccache-swig
/usr/local/Cellar/swig/3.0.7/bin/swig
/usr/local/Cellar/swig/3.0.7/share/man/man1/ccache-swig.1
/usr/local/Cellar/swig/3.0.7/share/swig/ (720 files)
/usr/local/Cellar/cmake/3.1.1/bin/ccmake
/usr/local/Cellar/cmake/3.1.1/bin/cmake
/usr/local/Cellar/cmake/3.1.1/bin/cmakexbuild
/usr/local/Cellar/cmake/3.1.1/bin/cpack
/usr/local/Cellar/cmake/3.1.1/bin/ctest
/usr/local/Cellar/cmake/3.1.1/share/aclocal/cmake.m4
/usr/local/Cellar/cmake/3.1.1/share/cmake/ (1789 files)
/usr/local/Cellar/cmake/3.1.1/share/doc/ (4 files)
/usr/local/Cellar/cmake/3.1.1/share/man/ (19 files)
Warning: homebrew/science already tapped!
/usr/local/Cellar/hdf5/1.8.15/bin/gif2h5
/usr/local/Cellar/hdf5/1.8.15/bin/h52gif
/usr/local/Cellar/hdf5/1.8.15/bin/h5c++
/usr/local/Cellar/hdf5/1.8.15/bin/h5cc
/usr/local/Cellar/hdf5/1.8.15/bin/h5copy
/usr/local/Cellar/hdf5/1.8.15/bin/h5debug
/usr/local/Cellar/hdf5/1.8.15/bin/h5diff
/usr/local/Cellar/hdf5/1.8.15/bin/h5dump
/usr/local/Cellar/hdf5/1.8.15/bin/h5import
/usr/local/Cellar/hdf5/1.8.15/bin/h5jam
/usr/local/Cellar/hdf5/1.8.15/bin/h5ls
/usr/local/Cellar/hdf5/1.8.15/bin/h5mkgrp
/usr/local/Cellar/hdf5/1.8.15/bin/h5perf_serial
/usr/local/Cellar/hdf5/1.8.15/bin/h5redeploy
/usr/local/Cellar/hdf5/1.8.15/bin/h5repack
/usr/local/Cellar/hdf5/1.8.15/bin/h5repart
/usr/local/Cellar/hdf5/1.8.15/bin/h5stat
/usr/local/Cellar/hdf5/1.8.15/bin/h5unjam
/usr/local/Cellar/hdf5/1.8.15/include/ (74 files)
/usr/local/Cellar/hdf5/1.8.15/lib/libhdf5.10.dylib
/usr/local/Cellar/hdf5/1.8.15/lib/libhdf5_cpp.10.dylib
/usr/local/Cellar/hdf5/1.8.15/lib/libhdf5_hl.10.dylib
/usr/local/Cellar/hdf5/1.8.15/lib/libhdf5_hl_cpp.10.dylib
/usr/local/Cellar/hdf5/1.8.15/lib/ (9 other files)
/usr/local/Cellar/hdf5/1.8.15/share/hdf5_examples/ (71 files)
Creating firedrake virtualenv.
Traceback (most recent call last):
  File "firedrake-install", line 398, in <module>
    virtualenv.create_environment("firedrake", site_packages=True)
  File "/Users/earendilllock/.local/lib/python2.7/site-packages/virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/Users/earendilllock/.local/lib/python2.7/site-packages/virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/Users/earendilllock/.local/lib/python2.7/site-packages/virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/earendilllock...firedrake/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1

**Comment by earendilllock** [comment]
Thanks @dham it seems that anaconda mpi4py package is broken. using pip to install mpi4py I've installed the firedragon. But there is still an issue with script I think.

Thanks all.

**Comment by dham** [comment]
Yes. This is the second Maverick fail we've had this afternoon. Unfortunately, even through most of the development team own Macs, we're all on Yosemite. This makes this one hard to debug. We're still thinking about how to do it. I'm glad you have a complete install, though.
