### ISSUE TITLE
Install script/virtualenv question

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#620]
After running the install script on a clean machine, the final output is
```
Successfully installed virtualenv
Cleaning up...
Virtual env installed. Please run firedrake-install again.
```

Am I supposed to type `source firedrake/bin/activate` at this point?  Or just `python firedrake-install` again (which is what I've been doing)?

**Comment by dham** [comment]
You should run firedrake-install again, as it tells you. It doesn't say anything about activate. I don't understand what the issue is here?

**Comment by dorugeber** [comment]
Okay, it was just a query.  In a previous issue, your previous response was "try running the petsc install instruction on its own, after sourcing firedrake/bin/activate", so I wondered whether I should have been doing that all along.
