### ISSUE TITLE
mpi4py.MPI.Status has the wrong size, try recompiling

### ISSUE THREAD

**Issue by earendilllock** [firedrakeproject/firedrake#639]
Dear all!
I've installed firedrake using pip as was recommended on Download page.
After that I've tried to 
```python
from firedrake import *
```
and obtained the message that is attached

What do I have to do to solve the problem?

[import.txt](https://github.com/firedrakeproject/firedrake/files/41109/import.txt)

Thanks for help

**Comment by gautam1168** [comment]
I have been told that this can happen when you have multiple mpi distributions installed. Like openmpi and mpich2.
