### ISSUE TITLE
Firedrake installation

### ISSUE THREAD

**Issue by earendilllock** [firedrakeproject/firedrake#640]
Hi dear all!
I've installed firedrake step-by-step using the instruction on the web-site.

I tried 
```python
from firedrake import *
```
and obtain an error (in attached file)

[import.txt](https://github.com/firedrakeproject/firedrake/files/41201/import.txt)

Could you please suggest me what to do?

**Comment by miklos1** [comment]
Based on the error message, I would check these:
 * Was the same C++ compiler used to build Firedrake's Python extension modules as the one which was used to build libspatialindex?
 * Was the Firedrake extension module built against the same version of libspatialindex as the one which the dynamic loader picks up?

**Comment by earendilllock** [comment]
Thank you for answer @miklos1 !
Could you please tell me how to check that, cause I'm not very familiar with that kind of stuff?

**Comment by miklos1** [comment]
Have you used the install script or manual installation? If the former, can you send the log?

What platform are you installing on, and how did you install libspatialindex?

Can you give the output of the following:

    $ cc -lspatialindex

If you can find where the libspatialindex is installed (perhaps /usr/lib ?), can you run `readelf -Ws` on it and check if the missing symbol is listed?

If you cannot figure out how to fix this problem, you can try comment out the failing

    import firedrake.spatialindex as spatialindex
line. It is only used for point evaluations, everything else should work without it.

**Comment by earendilllock** [comment]
I used manual installation for 2 reasons:
1) Script doesnt work
2) I want Anaconda be the Python on which firedrake should be installed

I'm running Mac OS X El Capitan. 
I used 
```
brew install spatialindex
```

The result of 
```
cc -lspatialindex
```
is:
```
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have ```greadelf``` but on what I have to cast it?

Where should I comment the line? In which file? Is it significant not to import that lib?

**Comment by miklos1** [comment]
OK, so you have a Mac. Can you try:

    nm -g /usr/local/lib/libspatialindex.dylib

and check if it contains the missing symbol?

Firedrake `Function`s can be evaluated at arbitrary physical points (http://firedrakeproject.org/point-evaluation.html) which is not necessary for solving PDEs, but might be useful for the evaluation of the result. If this is not essential for you yet, you can comment out the import statement in firedrake/mesh.py, exactly where `from firedrake import *` fails.

**Comment by earendilllock** [comment]
As I can see there is no such symbol
[out.txt](https://github.com/firedrakeproject/firedrake/files/41689/out.txt)

But functionality will stay the same as I comment a part of import, won't it?

**Comment by miklos1** [comment]
OK, it seems like Firedrake was not built against this version of libspatialindex. Do you have any other libspatialindex installation by any chance? Did you pip install firedrake? Can you try re-installing just firedrake (not the dependencies)?

If you disable the import, the point evaluation feature won't work, but the rest of the Firedrake should work.

**Comment by earendilllock** [comment]
There is no other version of libspatialindex on my system. I've removed firedrake out of everywhere and then reload it from git, and then ```make``` it. The problem is still the same.
Is it possible that the problem is in firedrake?

**Comment by miklos1** [comment]
I wonder if it's a name mangling problem then.
Can you report these?

    echo $CXX

and

    mpicxx -v

**Comment by earendilllock** [comment]
```
MacBook-Air-Maksim:firedrake earendilllock$ echo $CXX

MacBook-Air-Maksim:firedrake earendilllock$ mpicxx -v
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by dham** [comment]
This was finalised by determining (a) that anaconda is not supported and (b) removing the step by step install.
