### ISSUE TITLE
Buggy autocompletion

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#642]
If I type in IPython:

```
from firedrake import *
mesh = UnitSquareMesh(2, 2)
mesh.
```

and press TAB after the dot, I get the following suggestions:

```
mesh.cell                                mesh.topological_dimension
mesh.coordinates                         mesh.topology
mesh.geometric_dimension                 mesh.ufl_cargo
mesh.init                                mesh.ufl_cell
mesh.init_cell_orientations              mesh.ufl_coordinate_element
mesh.is_piecewise_linear_simplex_domain  mesh.ufl_coordinates
mesh.spatial_index                       mesh.ufl_id
mesh.topological                         mesh.uid
```

then I can finish like this:

```
In [3]: mesh.num_cells()
Out[3]: 8
```

So `num_cells` works despite not being suggested. This is because `num_cells` lives on `mesh.topology`, but accessing `mesh` will also try `mesh.topology`, so the above will work.
Of course, the code assistance problem could be fixed by overriding `__dir__`, however doing so in Python 2 requires ugly stuff (http://stackoverflow.com/a/32453194).

**Comment by wence-** [comment]
This is an annoyance, but I'm going to wontfix it.  Arguably the right thing to do is to "fix" our class inheritance.

**Comment by miklos1** [comment]
> Arguably the right thing to do is to "fix" our class inheritance.

Well, it isn't simply class inheritance, but rather object inheritance. Yes, it is logically true that a `MeshGeometry` is also a `MeshTopology` (it behaves like one in the current API). However, two different `MeshGeometry` objects may have the same `MeshTopology`, 'same' in the sense of object identity. This cannot be expressed by simple class inheritance.

Class inheritance could be used if we had a `MeshTopologyProxy` class, which inherits `MeshTopology`, but overrides all methods and properties with a call to the delegated object. Then `MeshGeometry` could simply subclass `MeshTopologyProxy`, and everything should work just fine - including autocompletion.

The `MeshTopologyProxy` could be:
 * written manually, listing all methods and properties of `MeshTopology` in the source code again.
 * generated using complicated Python magic.

None of which are particularly attractive choices.

**Comment by wence-** [comment]
OK, I see.  That does sound unattractive.  It would be nice to be able to get rid of all the magic `getattr` stuff such that when one does something wrong, the error message makes sense.  However, I haven't thought about how to do so.

**Comment by miklos1** [comment]
I think the `MeshTopologyProxy` should solve the problem with the error messages as well.

**Comment by miklos1** [comment]
Now that we are switching to Python 3, fixing this will be easy.
