### ISSUE TITLE
Discontinuous Coordinate field leads to solve failures

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#649]
In the following code,
https://gist.github.com/colinjcotter/2736e0f63fca695186a2
Setting DGMesh=True causes a zero pivot in the ILU initialisation, suggesting that something has gone wrong with the assembly.

Setting DGMesh=True creates a new DG2 mesh from the old one and uses that.

**Comment by miklos1** [comment]
Can you make this example shorter while still exposing the problem?

**Comment by colinjcotter** [comment]
I tried, but I could not.

On 5 December 2015 at 16:24, Miklós Homolya <notifications@github.com>
wrote:

> Can you make this example shorter while still exposing the problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/649#issuecomment-162218143>
> .
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by colinjcotter** [comment]
Ah, now I can.

On 5 December 2015 at 16:25, Colin Cotter <colin.cotter@imperial.ac.uk>
wrote:

> I tried, but I could not.
>
> On 5 December 2015 at 16:24, Miklós Homolya <notifications@github.com>
> wrote:
>
>> Can you make this example shorter while still exposing the problem?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/firedrakeproject/firedrake/issues/649#issuecomment-162218143>
>> .
>>
>
>
>
> --
> http://www.imperial.ac.uk/people/colin.cotter
>
> www.cambridge.org/9781107663916
>
>
>


-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by miklos1** [comment]
Can you not use VX again? That's still on the old mesh when you use it for a second time.
I don't think we support DG2 (higher-order) on master.

**Comment by colinjcotter** [comment]
Here is a reduction:

https://gist.github.com/colinjcotter/c83f667ef98bba7949f3

**Comment by colinjcotter** [comment]
Do you mean that DG2 coordinate field is not supported?

**Comment by colinjcotter** [comment]
Use it again for what?

On 5 December 2015 at 16:28, Miklós Homolya <notifications@github.com>
wrote:

> Can you not use VX again? That's still on the old mesh when you use it for
> a second time.
> I don't think we support DG2 (higher-order) on master.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/649#issuecomment-162218318>
> .
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by colinjcotter** [comment]
Oh right, because bendy is needed for this.

**Comment by miklos1** [comment]
Yes. Do you want bendy+bootstrapping branches?

**Comment by miklos1** [comment]
@colinjcotter: I've merged you bootstrapping+bendy branches in Firedrake/UFL/FFC, on which your example does not produce a failure.

**Comment by miklos1** [comment]
So DG2 coordinates are not expected to work on master, they work on bendy+bootstrapping branches, and they shall just work when master finally supports non-affine. Closing.
