### ISSUE TITLE
Link against libraries in kernels

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#650]
A feature request, please can we have the option to link against libraries in Firedrake kernels?

**Comment by colinjcotter** [comment]
Also, if we compile a .lib file locally as a user and put it in a directory, which paths will the compiler look in?

**Comment by miklos1** [comment]
Try to put it in /usr/local/include and /usr/local/lib.

**Comment by wence-** [comment]
You'll need OP2/PyOP2#476.

Build a Kernel with:

```python

Kernel(..., ldargs=[list, of, arguments, to, linker])

```

For example, if you want to link against `libfoo.so` which lives in a non-standard directory `/foo/bar`, do:

```
ldargs=["-L/foo/bar", "-Wl,-rpath,/foo/bar", -lfoo",]
```

The `-L` tells the linker where to look, the `-Wl,...` bakes the search path into the resulting shared library so the loader knows where to find libfoo.

**Comment by wence-** [comment]
Please update PyOP2 and this should work (you'll need to `firedrake-clean`).

**Comment by wence-** [comment]
You can now do this.
