### ISSUE TITLE
Firedrake install fails with --user option

### ISSUE THREAD

**Issue by beganthewit** [firedrakeproject/firedrake#654]
I tried to do the following to install firedrake on El Capitain mac. First I did this:

brew uninstall openmpi

brew install gcc
brew install --build-from-source --with-fortran openmpi

But something went astray. Perhaps I'm not starting from a clean-enough copy. 

Anyway, here is the output:
[firedrake.txt](https://github.com/firedrakeproject/firedrake/files/58378/firedrake.txt)

Beth

**Comment by miklos1** [comment]
Can you try calling the install script without the --user option?

**Comment by wence-** [comment]
It looks like the h5py installation failed, because its `setup.py` doesn't support the `--user` option.  I wonder if we should remove the `--user` option to `firedrake-install` and instead only support global (not the default) and `virtualenv` installs.

**Comment by beganthewit** [comment]
That worked so far!

**Comment by dham** [comment]
I think dropping --user is a reasonable idea. I put it in because I thought people would be more resistant to virtualenv than they have been.

**Comment by wence-** [comment]
Fixed in #656 by removing the `--user` option.
