### ISSUE TITLE
0-form is not recomputed after updating variables

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#660]
In the following code:
https://gist.github.com/colinjcotter/72ba5be5c45909655575
the energy is recomputed every timestep. The scheme conserves energy, but there are small fluctuations due to solver tolerances. If disable = True (invoking disable_performance_optimisations() ), then it is correctly updated. If disable = False then energy is never updated.

**Comment by wence-** [comment]
Fixed by that commit in pyop2.
