### ISSUE TITLE
Citation information

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#676]
We don't currently make it explicit which papers to cite when using Firedrake.  There are two things we could do (these not be either or):

1. Add a "Citing Firedrake" section to the publications part of the website (linked from the manual)
    indicating which papers to cite for which bits of functionality.

2. Hook into (or roll our own) the PETSc citations stuff.  If I run with ``-citations`` PETSc prints out papers that I should cite if I used particular functionality.  We could add the appropriate Firedrake papers (e.g. the quad-orientation one) when using particular pieces of functionality.

**Comment by paulhjkelly** [comment]
Great idea.  I vote for both.
Paul



On 7 January 2016 at 09:48:55, Lawrence Mitchell (notifications@github.com<mailto:notifications@github.com>) wrote:

We don't currently make it explicit which papers to cite when using Firedrake. There are two things we could do (these not be either or):

  1.  Add a "Citing Firedrake" section to the publications part of the website (linked from the manual)
indicating which papers to cite for which bits of functionality.

  2.  Hook into (or roll our own) the PETSc citations stuff. If I run with -citations PETSc prints out papers that I should cite if I used particular functionality. We could add the appropriate Firedrake papers (e.g. the quad-orientation one) when using particular pieces of functionality.

**Comment by wence-** [comment]
Addressed, when it lands, in #677

**Comment by wence-** [comment]
Done.
