### ISSUE TITLE
Web site does not mention pytest-benchmark

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#679]
The user wishing to test firedrake is supposed to mystically know that pytest-benchmark is required.

**Comment by wence-** [comment]
Does the test suite not work without the plugin, or do the benchmark tests just not run?

Do we want a section in the install page for "developing firedrake"?

**Comment by dham** [comment]
make test_regression fails because py.test gets passed an unknown option.

I think we should probably actually just install pytest and pytest-benchmark into the virtualenv by default. It's not like they are big.
