### ISSUE TITLE
'petsc4py.PETSc.Sys' has no attribute 'registerCitation'

### ISSUE THREAD

**Issue by twang15** [firedrakeproject/firedrake#681]
=================Description==========================
Basically, I try to install a development environment of firedrake software stack, but not in a virtualenv. I installed all the system dependencies and firedrake's dependencies. But, I cannot succeed in the end.

I want to know whether virtualenv installation is sufficient for firedrake development purpose. My initial objective is to see all the intermediate representations in all the layers of firedrake and to be able debug firedrake's components. 

Thanks a lot for any suggestions and comments !

==================Step to reproduce=======================
#Environment
OS: ubuntu 15.10 X86_64

#system dependencies
sudo apt-get install build-essential cmake gfortran git-core libblas-dev python-dev openmpi-bin mercurial libspatialindex-dev libopenmpi-dev liblapack-dev python-pip

#firedrake dependencies
sudo pip install six sympy git+https://bitbucket.org/mapdes/ffc.git#egg=ffc git+https://bitbucket.org/mapdes/ufl.git#egg=ufl git+https://bitbucket.org/mapdes/fiat.git#egg=fiat git+https://bitbucket.org/fenics-project/instant.git#egg=instant

#install PyOp2
#Follow the instruction in PyOP2 github: https://github.com/OP2/PyOP2
#after installation of PyOP2, sequential backend works properly.

git clone https://bitbucket.org/petsc/petsc.git
./configure --download-hdf5 --download-fblaslapack  --download-ctetgen --download-triangle --download-chaco
make PETSC_DIR=/home/tao/petsc PETSC_ARCH=arch-linux2-c-debug all
make PETSC_DIR=/home/tao/petsc PETSC_ARCH=arch-linux2-c-debug test
make PETSC_DIR=/home/tao/petsc PETSC_ARCH=arch-linux2-c-debug streams NPMAX=4

#all succeed above

#install petsc4py
git clone https://bitbucket.org/mapdes/petsc4py.git
sudo python setup.py install

#install h5py, h5py links to the same hdf5 library as petsc does.
wget https://pypi.python.org/packages/source/h/h5py/h5py-2.5.0.tar.gz
tar zxvf h5py-2.5.0.tar.gz
cd h5py-2.5.0/

#h5py links to the same hdf5 library as petsc does.
python setup.py configure --hdf5=/home/tao/petsc/arch-linux2-c-debug/lib
sudo python setup.py install

#install firedrake
git clone https://github.com/firedrakeproject/firedrake.git
cd firedrake/
sudo python setup.py install
cd demos/
make
cd helmholtz/
python helmholtz.py

=========================Error message=============
Traceback (most recent call last):
  File "helmholtz.py", line 47, in <module>
    from firedrake import *
  File "/usr/local/lib/python2.7/dist-packages/firedrake/__init__.py", line 31, in <module>
    from firedrake.assemble import *
  File "/usr/local/lib/python2.7/dist-packages/firedrake/assemble.py", line 9, in <module>
    from firedrake import assembly_cache
  File "/usr/local/lib/python2.7/dist-packages/firedrake/assembly_cache.py", line 41, in <module>
    from firedrake.parameters import parameters
  File "/usr/local/lib/python2.7/dist-packages/firedrake/parameters.py", line 6, in <module>
    from firedrake.citations import Citations
  File "/usr/local/lib/python2.7/dist-packages/firedrake/citations.py", line 88, in <module>
    Citations().register("Rathgeber2015")
  File "/usr/local/lib/python2.7/dist-packages/firedrake/citations.py", line 62, in register
    PETSc.Sys.registerCitation(cite)
AttributeError: type object 'petsc4py.PETSc.Sys' has no attribute 'registerCitation'

**Comment by twang15** [comment]
The above are the instructions to reproduce the bug and its error message in the end.

Basically, I try to install a development environment of firedrake software stack, but not in a virtualenv. I installed all the system dependencies and firedrake's dependencies. But, I cannot succeed in the end.

I want to know whether virtualenv installation is sufficient for firedrake development purpose. My initial objective is to see all the intermediate representations in all the layers of firedrake. 

Thanks a lot for any suggestions and comments !

**Comment by twang15** [comment]
OS:  ubuntu 15.10 X86_64

**Comment by wence-** [comment]
The issue here is that you've picked up an incompatible combination of petsc/petsc4py and firedrake.  Please use (for both PETSc and and petsc4py) the "firedrake" branch.  In both cases you will need to clone from the respective repositories that we maintain.  For PETSc: http://bitbucket.org/mapdes/petsc, for petsc4py http://bitbucket.org/mapdes/petsc4py.

You can try using the upstream master branches, but we don't track PETSc interface changes as they happen.  The above-linked branches are "known-good" tags that are tested by our build system.

**Comment by twang15** [comment]
Thanks, wence. 
Now, I know how to get the right branch. I have understood the firedrake-install script. Still installing...

BTW, how do you install firedrake for development purpose ? Is it the same to what I have done above (expect the petsc and petsc4py should take firedrake branch)?

**Comment by wence-** [comment]
If you use the `--developer` option to firedrake-install then the src sub directory of the virtual environment has all the checked out repositories. You can just work directly in those and changes should be picked up.

**Comment by twang15** [comment]
I install petsc and petsc4py in firedrake branch.
However, the following error message occurs:

===========ERROR message===========

Traceback (most recent call last):
  File "helmholtz.py", line 47, in <module>
    from firedrake import *
  File "/usr/local/lib/python2.7/dist-packages/firedrake/__init__.py", line 33, in <module>
    from firedrake.checkpointing import *
  File "/usr/local/lib/python2.7/dist-packages/firedrake/checkpointing.py", line 4, in <module>
    from firedrake import hdf5interface as h5i
ImportError: /usr/local/lib/python2.7/dist-packages/firedrake/hdf5interface.so: undefined symbol: PetscViewerHDF5GetFileId

**Comment by wence-** [comment]
You need to build petsc with support for hdf5 `--download-hdf5`. The install script takes care of this for you.

**Comment by miklos1** [comment]
@twang15: BTW I see you presume that the virtualenv installation is not suitable for development, which is simply not true. You will probably want to call the install script with the `--developer` option.

**Comment by twang15** [comment]
@miklos1 : please see my latest two comments in #680 . So far, I don't know whether "--developer" option will be sufficient. What is your idea ?

**Comment by miklos1** [comment]
Working in a virtualenv won't hide anything from you with respect to debugging or looking into IRs. There's also no performance penalty. The reason we adopted virtualenv is to avoid dependency conflicts with any other package that a user may have already have installed. It won't hurt you.

However, we only test Ubuntu and Mac, and CentOS 6 is known not to work by default. IIRC the reason was that its Python is old. We need Python 2.7.

**Comment by twang15** [comment]
@miklos1 Good to know this. Thanks. Still, I have to do this myself on CentOS 6. If it is interesting, I can share my final script after I work it out.

**Comment by wence-** [comment]
OK, this issue I think is resolved (you just needed the correct petsc branches), we'll work out the others as we find them.
