### ISSUE TITLE
New Implementation of Trace for H(div) Elements

### ISSUE THREAD

**Issue by thomasgibson** [firedrakeproject/firedrake#684]
I'm just getting started with firedrake, and I'm interested in reworking the implementation of computing the trace of H(div) elements along cell facets. There is a current implementation in fiat/FIAT/trace_hdiv.py. `dot(u, n)` is computed, where `u` is an H(div) element and `n` is the facet normal in the reference element coordinates. I want to just tabulate the basis function evaluations at points located on the facet (so I should probably throw out all interior points?), but I also want to add information about the facet entity to the class. 

Would it be best to somehow create functions that define the coordinate map (and its inverse), point to point, from the physical domain to the reference element? From this we could find out the correct facet we're on, no? Would this avoid the "multiple facets" problem (i.e. "what facet normal do I use?") when `tabulate` is called to evaluate at or near vertices? Perhaps this is too naive, or I'm missing a crucial detail.

I would also like to think about extending this to finite elements that are tensor products of two known finite elements, but that's for a later time. I'm not quite sure how `tabulate` should interact with `TensorFiniteElement`. I will update as I make more progress.

**Comment by dorugeber** [comment]
[I suspect this is a conversation I should join]
Note that there is also ~~facet_element.py~~ restricted.py, which doesn't do any dotting with `n`.

I don't know what use case you have in mind, so I can't say more at the moment.

**Comment by wence-** [comment]
A few small comments.  FIAT doesn't know about physical space, only reference space, so I'm not sure how the physical domain comes into play.  Simplex cells in FIAT already provide `cell.get_facet_transform(facet_number)`, which provides you a function that maps a point in facet coordinates to a point in cell coordinates, is that what you want?

**Comment by thomasgibson** [comment]
Thank you for pointing out `restricted.py`, dorugeber! This is exactly what I'm looking for to restrict which dofs are relevant.

And wence-, thank you for correcting me. This definitely changes things, but `cell.get_facet_transform(facet_number)` sounds like what I'm looking for. It's in the `ReferenceElement` class, yes? I'll have a chat with David and see where this goes.

**Comment by miklos1** [comment]
Related: #193

**Comment by thomasgibson** [comment]
Update on the new trace class.

So the new class is nearly finished and seems to be working correctly for elements on 2D and 3D simplexes - no quads (yet).

No dot products - just extended the tabulate function arguments in `finite_element.py` to accept arguments `tabulate(order,points,entity)` and used `cell.get_facet_transform(facet_id)`. The new trace class tabulates itself on a particular facet by passing in the entity id: `(d,i)` to this new tabulate function, and returns the appropriate dictionary. The values array has dimension: # of nodes by # of points. Once I check this with David, I will create a pull request in FIAT.

**Comment by miklos1** [comment]
Can we close this now?

**Comment by wence-** [comment]
I think so.
