### ISSUE TITLE
Subtle firedrake-install issue with ssh clones

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#694]
When we run firedrake install, it defaults to cloning over ssh.  We execute commands like:

```
git clone -b master https://github.com/coneoproject/COFFEE.git
```

A result of this is that `.git/config` (at least for me) contains:

```
[remote "origin"]
	url = git@github.com:coneoproject/COFFEE
	fetch = +refs/heads/master:refs/remotes/origin/master
```

i.e. no wildcard fetch matches.  Because of this, when I update, I don't get all the other available branches.  If I install with `--disable-ssh` (or fall back to it), then I get:

```
[remote "origin"]
	url = https://github.com/coneoproject/COFFEE.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

So all branches are available.

I think we can fix this by passing `--no-single-branch` to `git clone`.

**Comment by FrancisRussell** [comment]
Using git 2.7.0 under Debian:

Running `git clone -b master https://github.com/coneoproject/COFFEE.git` gives me
```
[remote "origin"]
        url = https://github.com/coneoproject/COFFEE.git
        fetch = +refs/heads/*:refs/remotes/origin/*
```

Running `git clone -b master git@github.com:coneoproject/COFFEE.git` gives me
```
[remote "origin"]
        url = git@github.com:coneoproject/COFFEE.git
        fetch = +refs/heads/*:refs/remotes/origin/*
```

**Comment by wence-** [comment]
OK, probably pebkac.
