### ISSUE TITLE
Accuracy problem only on Mac

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#695]
On my MacBook:

```
$ py.test tests/regression/test_poisson_mixed_strong_bcs.py::test_poisson_mixed[parameters1-True]
================================== test session starts ===================================
platform darwin -- Python 2.7.11, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /Users/miklos1/firedrake/src/firedrake, inifile:
collected 8 items

tests/regression/test_poisson_mixed_strong_bcs.py F

======================================== FAILURES ========================================
__________________________ test_poisson_mixed[parameters1-True] __________________________

parameters = {'fieldsplit_0_ksp_type': 'cg', 'fieldsplit_0_pc_factor_shift_type': 'INBLOCKS', 'fieldsplit_1_ksp_type': 'cg', 'fieldsplit_1_pc_factor_shift_type': 'INBLOCKS', ...}
quadrilateral = True

    @pytest.mark.parametrize('quadrilateral', [False, True])
    @pytest.mark.parametrize('parameters',
                             [{}, {'pc_type': 'fieldsplit',
                                   'pc_fieldsplit_type': 'schur',
                                   'ksp_type': 'gmres',
                                   'pc_fieldsplit_schur_fact_type': 'FULL',
                                   'fieldsplit_0_pc_factor_shift_type': 'INBLOCKS',
                                   'fieldsplit_1_pc_factor_shift_type': 'INBLOCKS',
                                   'fieldsplit_0_ksp_type': 'cg',
                                   'fieldsplit_1_ksp_type': 'cg'}])
    def test_poisson_mixed(parameters, quadrilateral):
>       assert poisson_mixed(3, parameters, quadrilateral=quadrilateral)[0] < 2e-5
E       assert 2.577859550169138e-05 < 2e-05

tests/regression/test_poisson_mixed_strong_bcs.py:75: AssertionError
---------------------------------- Captured stdout call ----------------------------------
Discontinuous Lagrange element requested on quadrilateral, creating DQ element.
Discontinuous Lagrange element requested on quadrilateral, creating DQ element.
Discontinuous Lagrange element requested on quadrilateral, creating DQ element.
Discontinuous Lagrange element requested on quadrilateral, creating DQ element.
---------------------------------- Captured stderr call ----------------------------------
pyop2:INFO Solving linear variational problem...
pyop2:INFO Solving linear variational problem...done
pyop2:INFO Solving linear variational problem...
pyop2:INFO Solving linear variational problem...done
================================ 1 failed in 1.13 seconds ================================
```

**Comment by wence-** [comment]
I have the same problem on my laptop.  The generated code is *identical* on linux and mac, but the compilers are different (and plausibly some of the maths libraries as well).  I vote for just relaxing this tolerance.

**Comment by wence-** [comment]
I had thought that this might be related to #380, but seemingly not.

**Comment by dorugeber** [comment]
1) What's the error on Linux?  (presumably <2e-5, but are we talking 1.99e-5 or 1e-10?)

2) Is the 2e-5 justified by anything (e.g. solver tolerances), or is it just "what it happened to be"?

**Comment by wence-** [comment]
So we're solving a lowest-order mixed poisson system for the exact solution `42*y` on a square domain.  So I think the solution is not expected to be machine precision exact (since we can't represent `y` exactly).  If I look at the convergence of the solver I see the following differences:

On linux:
```
    0 KSP preconditioned resid norm 1.986699135752e+02 true resid norm 1.187939392393e+02 ||r(i)||/||b|| 1.000000000000e+00
    1 KSP preconditioned resid norm 1.842643558640e-03 true resid norm 2.987112481540e-03 ||r(i)||/||b|| 2.514532728409e-05
    2 KSP preconditioned resid norm 2.298533600728e-09 true resid norm 2.454683259516e-04 ||r(i)||/||b|| 2.066337117225e-06
    3 KSP preconditioned resid norm 7.240204236781e-14 true resid norm 2.454675989990e-04 ||r(i)||/||b|| 2.066330997783e-06
```

On mac

```
    0 KSP preconditioned resid norm 1.986699135752e+02 true resid norm 1.187939392393e+02 ||r(i)||/||b|| 1.000000000000e+00
    1 KSP preconditioned resid norm 2.595862223188e-03 true resid norm 2.987109931343e-03 ||r(i)||/||b|| 2.514530581669e-05
    2 KSP preconditioned resid norm 5.961585133454e-09 true resid norm 4.751799858166e-03 ||r(i)||/||b|| 4.000035598274e-05
    3 KSP preconditioned resid norm 1.959750631238e-14 true resid norm 4.751792789028e-03 ||r(i)||/||b|| 4.000029647518e-05
```

**Comment by wence-** [comment]
On linux, the error comes out at `1.54605033035e-6`, rather than `2.86561665892e-5`

**Comment by colinjcotter** [comment]
Is this an unpreconditioned solve?

On 5 February 2016 at 11:07, Lawrence Mitchell <notifications@github.com>
wrote:

> On linux, the error comes out at 1.54605033035e-6, rather than
> 2.86561665892e-5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/695#issuecomment-180299894>
> .
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by wence-** [comment]
no

**Comment by wence-** [comment]
On mac, the unpreconditioned solve:
```
    0 KSP preconditioned resid norm 1.187939392393e+02 true resid norm 1.187939392393e+02 ||r(i)||/||b|| 1.000000000000e+00
    1 KSP preconditioned resid norm 1.128504298273e+02 true resid norm 1.128504298273e+02 ||r(i)||/||b|| 9.499679070317e-01
    2 KSP preconditioned resid norm 7.086359540732e+01 true resid norm 7.086359540732e+01 ||r(i)||/||b|| 5.965253434735e-01
    3 KSP preconditioned resid norm 6.340831013804e+01 true resid norm 6.340831013804e+01 ||r(i)||/||b|| 5.337672152641e-01
    4 KSP preconditioned resid norm 4.193807987494e+01 true resid norm 4.193807987494e+01 ||r(i)||/||b|| 3.530321508275e-01
    5 KSP preconditioned resid norm 3.997568010619e+01 true resid norm 3.997568010619e+01 ||r(i)||/||b|| 3.365127914956e-01
    6 KSP preconditioned resid norm 2.720492583369e+01 true resid norm 2.720492583369e+01 ||r(i)||/||b|| 2.290093754605e-01
    7 KSP preconditioned resid norm 2.714434001204e+01 true resid norm 2.714434001204e+01 ||r(i)||/||b|| 2.284993677779e-01
    8 KSP preconditioned resid norm 1.956842322829e+01 true resid norm 1.956842322829e+01 ||r(i)||/||b|| 1.647257709744e-01
    9 KSP preconditioned resid norm 1.928810384183e+01 true resid norm 1.928810384183e+01 ||r(i)||/||b|| 1.623660597951e-01
   10 KSP preconditioned resid norm 1.514994000679e+01 true resid norm 1.514994000679e+01 ||r(i)||/||b|| 1.275312537306e-01
   11 KSP preconditioned resid norm 1.416537128444e+01 true resid norm 1.416537128444e+01 ||r(i)||/||b|| 1.192432153959e-01
   12 KSP preconditioned resid norm 1.227118424663e+01 true resid norm 1.227118424663e+01 ||r(i)||/||b|| 1.032980665950e-01
   13 KSP preconditioned resid norm 1.080895531950e+01 true resid norm 1.080895531950e+01 ||r(i)||/||b|| 9.098911433289e-02
   14 KSP preconditioned resid norm 1.017785458769e+01 true resid norm 1.017785458769e+01 ||r(i)||/||b|| 8.567654758196e-02
   15 KSP preconditioned resid norm 7.896126113421e+00 true resid norm 7.896126113421e+00 ||r(i)||/||b|| 6.646909904647e-02
   16 KSP preconditioned resid norm 3.388098279629e+00 true resid norm 3.388098279629e+00 ||r(i)||/||b|| 2.852080081967e-02
   17 KSP preconditioned resid norm 8.175548383143e-11 true resid norm 8.175912215223e-11 ||r(i)||/||b|| 6.882432106869e-13

Final error: 2.07394651446e-12
```

On linux

```
    0 KSP preconditioned resid norm 1.187939392393e+02 true resid norm 1.187939392393e+02 ||r(i)||/||b|| 1.000000000000e+00
    1 KSP preconditioned resid norm 1.128504298273e+02 true resid norm 1.128504298273e+02 ||r(i)||/||b|| 9.499679070317e-01
    2 KSP preconditioned resid norm 7.086359540732e+01 true resid norm 7.086359540732e+01 ||r(i)||/||b|| 5.965253434735e-01
    3 KSP preconditioned resid norm 6.340831013804e+01 true resid norm 6.340831013804e+01 ||r(i)||/||b|| 5.337672152641e-01
    4 KSP preconditioned resid norm 4.193807987494e+01 true resid norm 4.193807987494e+01 ||r(i)||/||b|| 3.530321508275e-01
    5 KSP preconditioned resid norm 3.997568010619e+01 true resid norm 3.997568010619e+01 ||r(i)||/||b|| 3.365127914956e-01
    6 KSP preconditioned resid norm 2.720492583369e+01 true resid norm 2.720492583369e+01 ||r(i)||/||b|| 2.290093754605e-01
    7 KSP preconditioned resid norm 2.714434001204e+01 true resid norm 2.714434001204e+01 ||r(i)||/||b|| 2.284993677779e-01
    8 KSP preconditioned resid norm 1.956842322829e+01 true resid norm 1.956842322829e+01 ||r(i)||/||b|| 1.647257709744e-01
    9 KSP preconditioned resid norm 1.928810384183e+01 true resid norm 1.928810384183e+01 ||r(i)||/||b|| 1.623660597951e-01
   10 KSP preconditioned resid norm 1.514994000679e+01 true resid norm 1.514994000679e+01 ||r(i)||/||b|| 1.275312537306e-01
   11 KSP preconditioned resid norm 1.416537128444e+01 true resid norm 1.416537128444e+01 ||r(i)||/||b|| 1.192432153959e-01
   12 KSP preconditioned resid norm 1.227118424663e+01 true resid norm 1.227118424663e+01 ||r(i)||/||b|| 1.032980665950e-01
   13 KSP preconditioned resid norm 1.080895531950e+01 true resid norm 1.080895531950e+01 ||r(i)||/||b|| 9.098911433289e-02
   14 KSP preconditioned resid norm 1.017785458769e+01 true resid norm 1.017785458769e+01 ||r(i)||/||b|| 8.567654758196e-02
   15 KSP preconditioned resid norm 7.896126113421e+00 true resid norm 7.896126113421e+00 ||r(i)||/||b|| 6.646909904647e-02
   16 KSP preconditioned resid norm 3.388098279629e+00 true resid norm 3.388098279629e+00 ||r(i)||/||b|| 2.852080081967e-02
   17 KSP preconditioned resid norm 8.176266349594e-11 true resid norm 8.176513576050e-11 ||r(i)||/||b|| 6.882938328677e-13

Final error: 2.07435642493e-12
```

**Comment by colinjcotter** [comment]
Conclusion, the preconditioner is different between OS.

--cjc

On 5 February 2016 at 11:21, Lawrence Mitchell <notifications@github.com>
wrote:

> On mac, the unpreconditioned solve:
>
>     0 KSP preconditioned resid norm 1.187939392393e+02 true resid norm 1.187939392393e+02 ||r(i)||/||b|| 1.000000000000e+00
>     1 KSP preconditioned resid norm 1.128504298273e+02 true resid norm 1.128504298273e+02 ||r(i)||/||b|| 9.499679070317e-01
>     2 KSP preconditioned resid norm 7.086359540732e+01 true resid norm 7.086359540732e+01 ||r(i)||/||b|| 5.965253434735e-01
>     3 KSP preconditioned resid norm 6.340831013804e+01 true resid norm 6.340831013804e+01 ||r(i)||/||b|| 5.337672152641e-01
>     4 KSP preconditioned resid norm 4.193807987494e+01 true resid norm 4.193807987494e+01 ||r(i)||/||b|| 3.530321508275e-01
>     5 KSP preconditioned resid norm 3.997568010619e+01 true resid norm 3.997568010619e+01 ||r(i)||/||b|| 3.365127914956e-01
>     6 KSP preconditioned resid norm 2.720492583369e+01 true resid norm 2.720492583369e+01 ||r(i)||/||b|| 2.290093754605e-01
>     7 KSP preconditioned resid norm 2.714434001204e+01 true resid norm 2.714434001204e+01 ||r(i)||/||b|| 2.284993677779e-01
>     8 KSP preconditioned resid norm 1.956842322829e+01 true resid norm 1.956842322829e+01 ||r(i)||/||b|| 1.647257709744e-01
>     9 KSP preconditioned resid norm 1.928810384183e+01 true resid norm 1.928810384183e+01 ||r(i)||/||b|| 1.623660597951e-01
>    10 KSP preconditioned resid norm 1.514994000679e+01 true resid norm 1.514994000679e+01 ||r(i)||/||b|| 1.275312537306e-01
>    11 KSP preconditioned resid norm 1.416537128444e+01 true resid norm 1.416537128444e+01 ||r(i)||/||b|| 1.192432153959e-01
>    12 KSP preconditioned resid norm 1.227118424663e+01 true resid norm 1.227118424663e+01 ||r(i)||/||b|| 1.032980665950e-01
>    13 KSP preconditioned resid norm 1.080895531950e+01 true resid norm 1.080895531950e+01 ||r(i)||/||b|| 9.098911433289e-02
>    14 KSP preconditioned resid norm 1.017785458769e+01 true resid norm 1.017785458769e+01 ||r(i)||/||b|| 8.567654758196e-02
>    15 KSP preconditioned resid norm 7.896126113421e+00 true resid norm 7.896126113421e+00 ||r(i)||/||b|| 6.646909904647e-02
>    16 KSP preconditioned resid norm 3.388098279629e+00 true resid norm 3.388098279629e+00 ||r(i)||/||b|| 2.852080081967e-02
>    17 KSP preconditioned resid norm 8.175548383143e-11 true resid norm 8.175912215223e-11 ||r(i)||/||b|| 6.882432106869e-13
>
> Final error: 2.07394651446e-12
>
> On linux
>
>     0 KSP preconditioned resid norm 1.187939392393e+02 true resid norm 1.187939392393e+02 ||r(i)||/||b|| 1.000000000000e+00
>     1 KSP preconditioned resid norm 1.128504298273e+02 true resid norm 1.128504298273e+02 ||r(i)||/||b|| 9.499679070317e-01
>     2 KSP preconditioned resid norm 7.086359540732e+01 true resid norm 7.086359540732e+01 ||r(i)||/||b|| 5.965253434735e-01
>     3 KSP preconditioned resid norm 6.340831013804e+01 true resid norm 6.340831013804e+01 ||r(i)||/||b|| 5.337672152641e-01
>     4 KSP preconditioned resid norm 4.193807987494e+01 true resid norm 4.193807987494e+01 ||r(i)||/||b|| 3.530321508275e-01
>     5 KSP preconditioned resid norm 3.997568010619e+01 true resid norm 3.997568010619e+01 ||r(i)||/||b|| 3.365127914956e-01
>     6 KSP preconditioned resid norm 2.720492583369e+01 true resid norm 2.720492583369e+01 ||r(i)||/||b|| 2.290093754605e-01
>     7 KSP preconditioned resid norm 2.714434001204e+01 true resid norm 2.714434001204e+01 ||r(i)||/||b|| 2.284993677779e-01
>     8 KSP preconditioned resid norm 1.956842322829e+01 true resid norm 1.956842322829e+01 ||r(i)||/||b|| 1.647257709744e-01
>     9 KSP preconditioned resid norm 1.928810384183e+01 true resid norm 1.928810384183e+01 ||r(i)||/||b|| 1.623660597951e-01
>    10 KSP preconditioned resid norm 1.514994000679e+01 true resid norm 1.514994000679e+01 ||r(i)||/||b|| 1.275312537306e-01
>    11 KSP preconditioned resid norm 1.416537128444e+01 true resid norm 1.416537128444e+01 ||r(i)||/||b|| 1.192432153959e-01
>    12 KSP preconditioned resid norm 1.227118424663e+01 true resid norm 1.227118424663e+01 ||r(i)||/||b|| 1.032980665950e-01
>    13 KSP preconditioned resid norm 1.080895531950e+01 true resid norm 1.080895531950e+01 ||r(i)||/||b|| 9.098911433289e-02
>    14 KSP preconditioned resid norm 1.017785458769e+01 true resid norm 1.017785458769e+01 ||r(i)||/||b|| 8.567654758196e-02
>    15 KSP preconditioned resid norm 7.896126113421e+00 true resid norm 7.896126113421e+00 ||r(i)||/||b|| 6.646909904647e-02
>    16 KSP preconditioned resid norm 3.388098279629e+00 true resid norm 3.388098279629e+00 ||r(i)||/||b|| 2.852080081967e-02
>    17 KSP preconditioned resid norm 8.176266349594e-11 true resid norm 8.176513576050e-11 ||r(i)||/||b|| 6.882938328677e-13
>
> Final error: 2.07435642493e-12
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/695#issuecomment-180305135>
> .
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by wence-** [comment]
Yes.  The solver options are pretty nonsense, I will push a fix.
