### ISSUE TITLE
Check environment in firedrake-install and shout big warnings

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#699]
At the beginning of firedrake-install we should check certain environment conditions, such as:
 * PYTHONPATH
 * PETSC_DIR
 * PETSC_ARCH
 * aliases
 * Potentially already pip installed versions of Firedrake components. Will that ever conflict with the virtualenv?

And if the script sees anything suspicious, it can shout big colourful warnings.

**Comment by miklos1** [comment]
This would help users who are installing with unclean environments, potentially reducing our support load.

**Comment by dham** [comment]
This already happens for PETSC_DIR. #885 sets this up for PYTHONPATH. I don't think that other pip installed versions of Firedrake are a problem (because our virtualenv is closed).
