### ISSUE TITLE
Over appending Dictionary in parloop

### ISSUE THREAD

**Issue by alsgregory** [firedrakeproject/firedrake#709]
Hi @wence- ,

Here is some code to define the problem of too many dictionary items in the parloop function.

The linear combination constants are just a row of an identity matrix.

[test_functions_in_kernel.txt](https://github.com/firedrakeproject/firedrake/files/134262/test_functions_in_kernel.txt)

Many Thanks,
Alastair

**Comment by wence-** [comment]
For this problem, I think the issue is that you need to initialise all the values of matrix_identity, not just the diagonal ones.  If I do that, I don't get any NaNs, even running up to N=200

**Comment by alsgregory** [comment]
Brilliant, thanks. I haven't set the elements off the diagonal. Thanks

**Comment by colinjcotter** [comment]
So, this is coming up in ensemble methods. 

How about we extend the interface to handle lists of Functions?

**Comment by miklos1** [comment]
@colinjcotter: so what is the advantage of `list` have over a `dict`?

**Comment by wence-** [comment]
Also, the bug was that the kernel that @alsgregory had written was incorrect.

**Comment by colinjcotter** [comment]
@miklos : I don't have a strong opinion.

**Comment by alsgregory** [comment]
Problem sorted - it was just a problem as the kernel had a typo. I've now managed to get results with >400 functions so the dict works fine!
