### ISSUE TITLE
Interpolate arbitrary UFL expressions

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#711]
Given the modularity of TSFC, it is not very hard to make `interpolate` accept arbitrary UFL expressions for interpolating them onto `Function`s. This would come with several advantages:
* H(div) / H(curl) functions could be interpolated onto P/Q functions.
* Safer replacement for `Expression`s. For example, `f.interpolate(Expression("2*(x[0]+1.0"))` yields fairly unhelpful error message.
* Directly fixes #485 and #526.
* `Expression` could be deprecated as it confuses users. Occasionally users want to use `Expression`s inside forms which is unnecessary since UFL can express pretty much anything that `Expression`s can. This could help close #53 and #514.

There is very quick and dirty sketch in the branch `interpolate-ufl-expr`.

**Comment by miklos1** [comment]
I wonder if this feature could deprecate `assemble_expressions.py` as well. It seems to me that assembling expressions is a restricted version of this, where all of Functions in the expressions as well as the Function we assemble onto have the same function space.

OK, so we have a restriction here that the target function space must have reference value mapping identity. Not sure if assembling expressions have this restriction.

**Comment by wence-** [comment]
When assembling expressions, basically everything is just done pointwise.  So the mapping is meaningless.

**Comment by dham** [comment]
I don't think these are the same thing at all. The primary use of assemble_expressions is to implement timestepping, so it's basically compiled operations on vectors.

**Comment by miklos1** [comment]
Update here: #715 is now merged. However, we cannot deprecate `Expression`s yet, as they are the only thing accepted by `MeshGeometry.init_cell_orientations`. I have to note that `MeshGeometry.init_cell_orientations` itself should be retired (when one gets the time to implement or wire in the better alternative), as it relies on a user-provided normal vector and the mesh geometry to calculate cell orientations, even though one could get consistent cell orientations by looking only at the mesh topology. (I think `DMPlexOrient` implements exactly this.)

**Comment by miklos1** [comment]
@colinjcotter in #485:
> This would also be useful for writing higher order fields to vtu, since interpolate is more suitable than project, usually.

Now we have the technology to use `interpolate` instead of `project` when outputting to `.vtu`. Shall we make that change?

**Comment by wence-** [comment]
Done (as an option in #737).  Should this be closed?

**Comment by miklos1** [comment]
Yes. We might open separate pull requests for interpolation onto more complicated finite elements etc.
