### ISSUE TITLE
installation broke when APT upgraded OpenMPI

### ISSUE THREAD

**Issue by gdmcbain** [firedrakeproject/firedrake#722]
I had installed via firedrake-install, as per [instructions](http://firedrakeproject.org/download.html), a month ago.  This is on Debian testing.  Yesterday an 'apt-get upgrade' upgraded OpenMPI and broke everything that I'd compiled that depended on it or PETSc, including Firedrake.  The message was (e.g. on 'import firedrake' in Python):

> ImportError: libmpi.so.1: cannot open shared object file: No such file or directory

(Indeed, I now have instead /usr/lib/openmpi/lib/libmpi.so.12.0.2.)

Running (firedrake-clean and) firedrake-update --log failed with:

> Autodetection skipped [libmpi.so.1: cannot open shared object file: No such file or directory]

and

> error "PETSc was configured with one OpenMPI mpi.h version but now appears to be compiling using a different OpenMPI mpi.h version"

(Though I think Firedrake doesn't use my PETSc in /opt/petsc, but its own?)

I attach the [firedrake-update.log](https://github.com/firedrakeproject/firedrake/files/151902/firedrake-update.log.txt).

Can I tell Firedrake to use the new OpenMPI somehow?  Or should I temporarily reinstall the old one?

Thank you.

**Comment by miklos1** [comment]
I would just try `firedrake-update --rebuild`. If that doesn't help yet, then try `make clean` or `git clean -fxd` in the PyOP2 and the Firedrake source directories, then run `firedrake-update` again. Let me know if any these help.

**Comment by gdmcbain** [comment]
Thanks, `firedrake-update --rebuild` runs happily to completion; however, launching Firedrake fails with the above `ImportError`: 

> ImportError: libmpi.so.1: cannot open shared object file: No such file or directory

More directly, the error is from `from mpi4py import MPI as _MPI`.

I then tried the cleaning remedies:

    cd ~/firedrake/src/PyOP2
    make ext_clean
    git clean -fxd
    cd ../firedrake 
    make clean
    git clean -fxd
    cd
    firedrake-update --log

This all ran happily but the resulting Firedrake fails with the same `ImportError` when importing MPI from `mpi4py`.  

I attach the [firedrake-update.log](https://github.com/firedrakeproject/firedrake/files/152062/firedrake-update.log.txt)

**Comment by wence-** [comment]
Can you please try reinstalling mpi4py inside the virtualenv. I think this should then solve your import error: `pip install -U mpi4py`. 

If this is the case we should add it to the list of dependencies that are rebuilt when passing `--rebuild`

**Comment by gdmcbain** [comment]
Thank you, but sorry, that didn't work:

    $ . firedrake/bin/activate
    (firedrake)$ pip install -U mpi4py
   
> Requirement already up-to-date: mpi4py in ./firedrake/lib/python2.7/site-packages

    (firedrake)geordie@laplace:~$ pip show mpi4py

> ---
> Metadata-Version: 2.0
> Name: mpi4py
> Version: 2.0.0
> Summary: Python bindings for MPI
> Home-page: https://bitbucket.org/mpi4py/mpi4py/
> Author: Lisandro Dalcin
> Author-email: dalcinl@gmail.com
> License: BSD
> Location: /usr/local/users/geordie/firedrake/lib/python2.7/site-packages
> Requires: 
> 

I'm not sure whether this is relevant, but I note that outside Firedrake's virtualenv the site Python has /usr/lib/python2.7/dist-packages/mpi4py version 1.3.1 from the python-mpi4py APT package.  This works in that, e.g.,

    (firedrake)$ deactivate
    $ mpirun -np 4 python -c 'from mpi4py import MPI; print(MPI.COMM_WORLD.rank)'

> 1
> 2
> 0
> 3

I then recleaned, reupdated ([firedrake-update.log](https://github.com/firedrakeproject/firedrake/files/153735/firedrake-update.log.txt)), but still: 

   $ . firedrake/bin/activate
   (firedrake)$ mpirun -np 4 python -c 'from mpi4py import MPI'

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: libmpi.so.1: cannot open shared object file: No such file or directory

**Comment by wence-** [comment]
Ah, can you try uninstalling and then reinstalling mpi4py in the virtualenv? Pip doesn't want to reinstall a package that's already the latest version.

**Comment by gdmcbain** [comment]
Thanks again, but sorry, still no good.  This didn't appear to change the version of mpi4py, as reported by `pip show`, nor fix the `ImportError` thrown by importing MPI from mpi4py.

I note that {{firedrake-clean}} throws the same `ImportError`, so may not be working; {{firedrake-update}} does continue to run to completion without complaint.

**Comment by miklos1** [comment]
> This didn't appear to change the version of mpi4py

It's not about changing the version, but about rebuilding it against the newer MPI. Try

    pip uninstall mpi4py
    pip install mpi4py
inside the virtualenv.

**Comment by gdmcbain** [comment]
Right.  That is what I had done, pip uninstall, pip install, inside Firedrake's virtualenv.   The `ImportError` persists.  I'm not sure where it's getting the idea of `libmpi.so.1` from.

**Comment by wence-** [comment]
So the reason we had suggested this is that `mpi4py` (obviously) links against libmpi, and maybe somehow things have gone wrong.  Let's try running with more logging enabled to see what pip is doing:

```
pip uninstall mpi4py
pip install -vvv mpi4py
```

**Comment by wence-** [comment]
Plausibly mpi4py is being downloaded as a binary package (rather than built from source) and therefore something has gone wrong.  You can force a from source build (after uninstalling) with `pip install --no-binary :all: mpi4py`

**Comment by gdmcbain** [comment]
Good morning and thank you for the ongoing help; I have good news: your last suggest resolves the problem and has my Firedrake installation working again.

`pip install -vvv mpi4py` does indeed seem to use a 'wheel' (which I think is a binary), as reported:

>   Using cached wheel link: file:///usr/local/users/geordie/.cache/pip/wheels/d4/f3/94/0ae0e5f8bd28aa4416e38cad31984cc5fa757aee168fcf9f8a/mpi4py-2.0.0-cp27-none-linux_x86_64.whl

I'm surprised that `pip` goes to `~/.cache/pip` from inside a virtualenv, but knowing that it does, the problem can be resolved by `pip uninstall mpi4py` followed by either your suggestion

    pip install --no-binary :all: mpi4py

or explicitly deleting the offending wheel from the cache

    rm $(find ~/.cache -name 'mpi4py*'); pip install mpi4py

**Comment by wence-** [comment]
OK, great.  I'll keep this issue open until we've implemented an appropriate fix in `firedrake-update`.

**Comment by dham** [comment]
Fixed in #905
