### ISSUE TITLE
Adding C/C++ libraries to the Firedrake installation

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/firedrake#725]
I'm trying to think of a way to install libspatialindex via firedrake-install, instead of expecting it as a system-provided dependency. In particular, this would let us use the unbroken C API of libspatialindex before it arrives by the distributions.

Some of the difficulties include that theoretically we support both global and virtualenv installations, so sticking to that we must find a solution that can work with both. I have two ideas so far:
 * *pkgconfig*: Use pkg-config to find the compiler options for using the library. In case of a global installation, the library is installed in /usr/local (?), and pkgconfig will find the `.pc` files automatically. In the virtualenv case, we can install into the virtualenv root. Then we somehow have to add the virtualenv to `PKG_CONFIG_PATH` when the virtualenv is active, so pkgconfig will pick up the correct library.
 * *setup.py* (à la PETSc): We add a setup.py to the library, so that it can be installed via pip, and importing it from python we can get the correct path for the headers and the libraries. This probably composes better with virtualenv as well as not using a virtualenv.

Any more ideas, suggestions, approaches?

**Comment by dham** [comment]
We have exactly the same problem for libadjoint. Although, interestingly, installing it straight into the virtualenv seems to result in it being found by dolfin-adjoint. I am not quite sure why that works.

**Comment by miklos1** [comment]
It seems that the libadjoint package contains Python bindings as well, which are installed via pip.

**Comment by miklos1** [comment]
@dham: Wait, if installing into the virtualenv works, then what is exactly your problem?

**Comment by miklos1** [comment]
I just found `sys.prefix` which points at the Python root, which happens to be the virtualenv root in a virtualenv, and `/usr` on my machine outside a virtualenv.

**Comment by miklos1** [comment]
This has been solved. We deliver libadjoint, GLPK and libspatialindex as part of the installation procedure.
