### ISSUE TITLE
Implicit maps for DG spaces

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#727]
For fully discontinuous spaces, the entity->node map is the identity (or at least has a closed form arithmetic expression).  We could therefore avoid storing it.  This will become particularly of interest when using hybridisation methods where we don't actually need to store the maps for anything other than the trace variable.  This should significantly reduce memory pressure for these cases.

**Comment by dham** [comment]
It's not quite as simple as this, unfortunately. The cell-node map is closed form but the facet-node map is not. This sort of looks like supporting double indirections in PyOP2.. Maybe we should revisit that.

**Comment by wence-** [comment]
Oh, because I need an actual array of numbers to encode the mapping from facet to cells.

**Comment by danshapero** [comment]
Was this ever revisited or should it be closed?
