### ISSUE TITLE
Travis testing for firedrake-update

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#729]
Travis currently always tests clean installs, which is good for debugging issues, but doesn't systematically test the `firedrake-update` route.  One way we might imagine doing this is using the travis caching mechanism to cache the entire build tree and in one of the build matrices running firedrake-update.  It's probably sufficiently only to do this on master.

**Comment by miklos1** [comment]
We could just install master on Travis and then upgrade it for the branch / pull request we are testing. Although it would be a bit more difficult with branches of dependencies.

**Comment by wence-** [comment]
We now at least run firedrake-update immediately after install, so check if the script at least runs.
