### ISSUE TITLE
Error installing firedrake: complain about virtualenv already installed

### ISSUE THREAD

**Issue by dalonsoa** [firedrakeproject/firedrake#733]
Dear all, 

I'm trying to install Firedrake in a brand new iMac with El Capitan. I've just installed Xcode and Hombrew and run the install script. I always end up with the same error:

`... (lots of things being installed here; I can attach the full log if needed)
...
/usr/local/Cellar/spatialindex/1.8.5/lib/libspatialindex.a
/usr/local/Cellar/spatialindex/1.8.5/lib/libspatialindex.dylib
/usr/local/Cellar/spatialindex/1.8.5/lib/libspatialindex_c.4.dylib
/usr/local/Cellar/spatialindex/1.8.5/lib/libspatialindex_c.a
/usr/local/Cellar/spatialindex/1.8.5/lib/libspatialindex_c.dylib
/usr/local/Cellar/spatialindex/1.8.5/lib/pkgconfig/libspatialindex.pc
/usr/local/Cellar/spatialindex/1.8.5/NEWS
/usr/local/Cellar/spatialindex/1.8.5/README

2016-03-16 07:44:05,589 INFO   Installing virtualenv.
2016-03-16 07:44:05,796 DEBUG  Requirement already satisfied (use --upgrade to upgrade): virtualenv in ./Library/Python/2.7/lib/python/site-packages

2016-03-16 07:44:05,796 ERROR  Virtual env installed. Please run firedrake-install again.`

Of course, I run firedrake-install again but with the same result. I had the same problem in a laptop but I assumed it was a conflict between MacPorts and Homebrew and the quite chaotic PATHs I had, but in this case, it is an empty system with just Xcode and Homebrew. 

Do you have any suggestion of what the problem might be or what to do next?

Best wishes, 
Diego

**Comment by wence-** [comment]
Hi Diego,

Hmm, not immediately sure what's going on here.  We test, effectively, a from clean install all the time and haven't seen this error.  Could you please attach the full log output so we can try and debug from there?

**Comment by dalonsoa** [comment]
Of course. Here it is. 

[firedrake-install.txt](https://github.com/firedrakeproject/firedrake/files/175582/firedrake-install.txt)

**Comment by wence-** [comment]
OK, so it looks like what is going on is you run `python firedrake-install ...`, it is unable to import the `virtualenv` python package so it tries to install it, but it's already installed.  And then we tell you to run again (because now things are seemingly in place).  However, you hit the same set of error messages.

So, what do the following print?

```
$ which python
```
```
$ python -c "import virtualenv; print virtualenv.__file__"
```

**Comment by dalonsoa** [comment]
`$ which python
/usr/local/bin/python
$ ls -l /usr/local/bin/python
lrwxr-xr-x  1 diego  admin  34 16 Mar 07:59 /usr/local/bin/python -> ../Cellar/python/2.7.11/bin/python`

So this one seems to be pointing to the Hombrew version of Python

`$ python -c "import virtualenv; print virtualenv.__file__"
/Users/diego/Library/Python/2.7/lib/python/site-packages/virtualenv.pyc`

And this one... doesn't for some reason. This looks like the version that comes with the OS.

**Comment by wence-** [comment]
Hmm, that is indeed probably a problem?  Is `PYTHONPATH` empty?

```
$ echo $PYTHONPATH
$ python -c "import sys; print sys.path"
```

**Comment by dalonsoa** [comment]
PYTHONPATH is indeed empty. 

The second command produce:

`['', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Users/diego/Library/Python/2.7/lib/python/site-packages', '/usr/local/lib/python2.7/site-packages', '/Library/Python/2.7/site-packages']`

I guess the problem is in the last two entries.

**Comment by dham** [comment]
I realise this is a bit of a sticking plaster, but you could try:

pip install --ignore-installed virtualenv

Hopefully that will give you a virtualenv package installed with your
homebrew python. Once firedrake-install manages to bring up the virtualenv,
it will ignore all system and homebrew python packages anyway so at that
point you should be safe.

Regards,

David

**Comment by wence-** [comment]
No, that looks to be fine.  At least, on my system where things work, everything looks basically the same.

So I'm really confused, because if you just run, `python -c "import virtualenv"`, then you don't get an error, but if you instead run `python firedrake-install ...`, which at one point does `import virtualenv`, then you do  get an error...

**Comment by dalonsoa** [comment]
Hi both, 

David solution seems to be working. I've re-run the installation script and it seems to be working (installing petsc right now). 

I'll let you know if I it finishes the installation properly. 

Many thanks, 
Diego

**Comment by dalonsoa** [comment]
Everything has gone OK. Firedrake installed and run the test (mostly) without problems. The last line was this one:

================= 3429 passed, 51 skipped, 12 xfailed, 1 xpassed in 2602.25 seconds ==================

Are the "12 xfailed" important?

Many thanks for your help with the installation.

**Comment by wence-** [comment]
No, those are 12 tests that we know currently don't work because of missing functionality "expected failures".  This looks like everything is working!
