### ISSUE TITLE
Question: Robin boundary conditions and data-set based parameters

### ISSUE THREAD

**Issue by dalonsoa** [firedrakeproject/firedrake#735]
Dear all, 

I´ve started to use Firedrake recently and, trying to formulate my problem, I´m stuck in the following two points:
- Is it possible to define robin-type boundary conditions, depending on both the derivative and the value of the variable at the boundary?
- Can the linear term or a parameter inside the bilinear term be defined in terms of a data set ( for example experimental data), rather than an analytic expression?

Many thanks, 
Diego

**Comment by dham** [comment]
Robin boundary conditions is a good point - we haven't documented how you do that (because you're the first person who has asked!) Robin boundary conditions are quite possible. Because they are a coupling between two terms, you have to apply them weakly (ie like Neumann conditions) by setting appropriate integrals. It's not possible to apply them by changing the function space (as you would for Dirichlet conditions). For example, assume we want to solve:
```
- \nabla^2 u = g
```
subject to:

u + \nabla u \cdot n = f on \Gamma

Then the weak form of the equation (in UFL) is:
```python
dot(grad(u), grad(v)) * dx - dot(grad(u), n) * v * ds == g * v * dx
```
The boundary condition becomes:
```python
u * v * ds  + dot(grad(u), n) * v * ds == f * v * ds
```
Substituting the boundary condition in for the surface integral in the equation yields:
```python
dot(grad(u), grad(v)) * dx + u * v * ds == g * v * dx - f * v * ds
```
and we are done.

**Comment by dham** [comment]
Obtaining coefficients and forcing from externally supplied functions is likewise not so hard. The easiest way to do this is to create a `Function` whose values are interpolated from your outside data source. You can then use this `Function` in your finite element forms as usual. For time varying forms, you can re-interpolate the `Function` every time step if you need to.

There are a few ways of doing the interpolation. In essence, this is the process of mapping the data in whichever form you have it into a finite element function space. Below I assume you have a function `interpolate_data` which takes a list of points and returns your data interpolated at each of those points.
```python
# assume m is our Mesh.
V = FunctionSpace(m, "CG", 2) # For some reason we decide to use 
                              # quadratic elements for the forcing.
VV = VectorFunctionSpace(m, "CG", 2) # Corresponding vector FS for coordinates.

# Get the coordinates of all the nodes in the quadratic space.
coords_p2 = Function(VV).interpolate(m.coordinates)

forcing = Function(V)

# Now actually interpolate the data using the user-provided function.
forcing.dat.data[:] = interpolate_data(coords_p2.dat.data_ro)
``` 
In most cases (depending only on how interpolate_data is implemented), the above will also work out of the box in parallel.

**Comment by dalonsoa** [comment]
Hi David, 

Thank you very much for your fast and detailed response. I haven't got time to test it, yet. I specially appreciate the example on how to use data-set based coefficients. While it is probably well explained in the documentation, my feeling was that the actual values of the functions at the mesh-points were a bit obscure or hard to access "manually" and this example is quite illustrative of the process. 

Best wishes, 
Diego

**Comment by wence-** [comment]
I think this is now covered in the documentation.

**Comment by denbigh** [comment]
@dham Following up on this, is there a simple way of imposing a Robin boundary condition on one particular boundary (e.g. boundary 1)?

**Comment by rckirby** [comment]
Same as Robin everywhere but use ds(1) instead of ds in the boundary integral
