### ISSUE TITLE
Utility function to return a layer coordinate

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#740]
I'd like to implement a function that returns a CG1 Function which takes the value of the number of levels above the base on dS_h facets on an extruded mesh. What are opinions about the interface?

**Comment by wence-** [comment]
You could do this into a `DG0xCG` function like so:

```python
...
V = FunctionSpace(extmesh, "DG", 0, vfamily="CG", vdegree=1)

f = Function(V)
import numpy

f.dat.data[:] = numpy.tile(numpy.arange(extmesh.layers, dtype=f.dat.dtype), extmesh.cell_set.size)
```

**Comment by wence-** [comment]
The firedrake source tree has an "extrusion_utils" file.  You could put the function in there and then maybe import the extrusion_utils module into the global namespace?

**Comment by wence-** [comment]
Do you still want to do this?
