### ISSUE TITLE
"creating DQ element" warning

### ISSUE THREAD

**Issue by tkarna** [firedrakeproject/firedrake#741]
I occasionally see this UFL warning

```
Discontinuous Lagrange element requested on None, creating DQ element.
```

that seems to come from the following
```python
from firedrake import *

mesh2d = UnitSquareMesh(5,5)
mesh = ExtrudedMesh(mesh2d, 10, 0.1)

# raises a warning
fs1 = VectorFunctionSpace(mesh, 'DG', 1)

# does not raise a warning
fs2 = VectorFunctionSpace(mesh, 'DG', 1, vfamily='DG', vdegree=1)

print fs1 == fs2  # returns True
```

Is this just a meaningless warning that can be ignored?

**Comment by dham** [comment]
It's a warning that you're abusing notation. The canonical name for a DG element on a quad is DQ. If you ask for DQ instead of DG it should work without warning (it's to do with the difference between linear and bilinear elements). The "None" in the warning message looks like a bug.

**Comment by dorugeber** [comment]
Actually, that's slightly weird: there's no quads in this code.  The base mesh is one of triangles, and the extruded mesh has prisms.  I wonder if it's related to the fact we don't have official names for elements on prisms...

**Comment by miklos1** [comment]
Extruded also expects the DQ notation, or else emits warning.

**Comment by tkarna** [comment]
I confirm that the short version does not raise error if I use DQ
```python
fs1 = VectorFunctionSpace(mesh, 'DQ', 1)
```
but as stated above this is counterintuitive as the mesh has no quads.

If I use DQ in the longer version
```python
fs2 = VectorFunctionSpace(mesh, 'DQ', 1, vfamily='DG', vdegree=1)
```
I get an error
```
  File "firedrake_DQ_bug.py", line 10, in <module>
    fs2 = VectorFunctionSpace(mesh, 'DQ', 1, vfamily='DG', vdegree=1)
  File "/home/tuomas/sources/firedrake/src/firedrake/firedrake/functionspace.py", line 166, in VectorFunctionSpace
    sub_element = make_scalar_element(mesh, family, degree, vfamily, vdegree)
  File "/home/tuomas/sources/firedrake/src/firedrake/firedrake/functionspace.py", line 52, in make_scalar_element
    degree=degree)
  File "/home/tuomas/sources/firedrake/src/ufl/ufl/finiteelement/finiteelement.py", line 55, in __new__
    canonical_element_description(family, cell, degree, form_degree)
  File "/home/tuomas/sources/firedrake/src/ufl/ufl/finiteelement/elementlist.py", line 271, in canonical_element_description
    'Cellname "%s" invalid for "%s" finite element.' % (cellname, family))
  File "/home/tuomas/sources/firedrake/src/ufl/ufl/assertions.py", line 45, in ufl_assert
    error(*message)
  File "/home/tuomas/sources/firedrake/src/ufl/ufl/log.py", line 158, in error
    raise self._exception_type(self._format_raw(*message))
ufl.log.UFLException: Cellname "triangle" invalid for "DQ" finite element.
```

**Comment by dorugeber** [comment]
I can see some logic behind it: we give the triangular prism version of the DQ elements shown at http://femtable.org/, rather than the DP version.

It's certainly correct that using `DQ` in the longer version breaks things, since that explicitly tries to take the product of a `DQ` horizontal element with a `DG` vertical element, and the former doesn't exist.

**Comment by tkarna** [comment]
OK, that makes sense.

**Comment by miklos1** [comment]
Yes, even for triangular prism cells the dQ and dPc families ([femtable.org](http://femtable.org/)) yield different fully discontinuous finite elements, therefore DG is ambiguous, except for degree zero. That is the reason for the warning.

In the line
```
fs2 = VectorFunctionSpace(mesh, 'DQ', 1, vfamily='DG', vdegree=1)
```
you explicitly specify dQ for the triangle (horizontal element) which is invalid.

**Comment by tkarna** [comment]
Yes that's clear now. So the correct notation (for triangular prisms) is
```python
fs1 = VectorFunctionSpace(mesh, 'DQ', 1)
fs2 = VectorFunctionSpace(mesh, 'DP', 1, vfamily='DP', vdegree=1)
```
