### ISSUE TITLE
Should we roll --developer in to all virtualenv installs

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#747]
Is there ever an advantage to making a virtualenv install which is not in developer mode?

I suspect not. If that is the case, we could abolish the --developer flag and just slave that functionality to `not args.global`

**Comment by miklos1** [comment]
I don't see any advantage of the default installation over `--developer`.

**Comment by colinjcotter** [comment]
It seems that many users will be on branches for new features at some
point, so this would also encourage testing of new features before merging
which might be good.

--cjc

On 7 April 2016 at 09:32, David A. Ham <notifications@github.com> wrote:

> Is there ever an advantage to making a virtualenv install which is not in
> developer mode?
>
> I suspect not. If that is the case, we could abolish the --developer flag
> and just slave that functionality to not args.global
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/747>
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by dham** [comment]
I don't understand what developer mode has to do with branches.

**Comment by colinjcotter** [comment]
If I check out a branch, I need to install again in non-developer mode, I
thought.

--cjc

On 7 April 2016 at 16:25, David A. Ham <notifications@github.com> wrote:

> I don't understand what developer mode has to do with branches.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/747#issuecomment-206952131>
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by dham** [comment]
not if you do it via `--package_branch`

**Comment by wence-** [comment]
Ongoing discussion, migrating existing installs to `--developer` is "hard".  We should flip the default though.

**Comment by rckirby** [comment]
Fine with me.  It did cost me one re-build as a beginner, but I don't mind typing the extra few characters now that I know.

**Comment by dham** [comment]
I agree with flipping the defualt

**Comment by miklos1** [comment]
Change made in master.
