### ISSUE TITLE
Cannot install firedrake, firedrake-install freezing during petsc installation

### ISSUE THREAD

**Issue by ovgeorge** [firedrakeproject/firedrake#754]
I'm trying to install firedrake on fresh ubuntu 15.10

The problem is it seems petsc compilation takes forever, because some packages needed for building it are missing.
I cannot figure our which ones and I've tried to install anything seemingly related, from build-essentials, to all mpi versions, blas, atlas, lapack (dev versions).

The resulting installation log is here http://dpaste.com/27M72HS

I'm also trying with system PETCS, specifying --honor-petsc-dir, but this is inconsistent:
while I'm specifing PETCS location as "/usr/lib/petscdir/3.4.2/"
it says:

error: [Errno 2] No such file or directory: '/usr/lib/petscdir/3.4.2/lib/petsc/conf/petscvariables'

if I create symlink /usr/lib/petsc => /usr/lib/petscdir/3.4.2
it says:

error: [Errno 2] No such file or directory: '/usr/lib/petsc/lib/petsc/conf/petscvariables'

So, I seems it writes in the end of the path anyway, right? 
Then I specify petsc dir as '/usr/' hoping it would add 'lib/petsc/...'

And getting new error 
error: [Errno 2] No such file or directory: '/usr/include/petscversion.h'

Apparently it looks at different places...

**Comment by dorugeber** [comment]
My own experience is that the firedrake-install script *works* on Ubuntu 15.10, but the PETSc installation just takes far longer than on 14.04.  I don't know why.

[See my earlier experience at #617]

**Comment by ovgeorge** [comment]
I have a relatively weak laptop, it's been an hours already and I've lost all hope...

**Comment by ovgeorge** [comment]
But another point, is inability of script to use system's petsc

**Comment by dorugeber** [comment]
Assuming you used the firedrake install script, did you pass the --minimal-petsc option?

I will leave the system petsc discussion to others.  In the past we required very specific PETSc functionality that often wasn't in the master branch (never mind the most recent release).  I don't think this is true any more, but the *firedrake* PETSc/petsc4py branches represent "known good" configurations, and are regularly rolled forward.

**Comment by ovgeorge** [comment]
minimal-petsc seems the same. Is this compiler issue? Does this depend on gcc version?

**Comment by juan42** [comment]
> error: [Errno 2] No such file or directory: '/usr/lib/petscdir/3.4.2/lib/petsc/conf/petscvariables'

This basically doesn't exist. On Ubuntu the path is:

./usr/lib/petscdir/3.4.2/linux-gnu-c-opt/conf/petscvariables

**Comment by miklos1** [comment]
Please don't bother with the system PETSc. Released versions of PETSc are too old for Firedrake.

**Comment by ovgeorge** [comment]
Thank you for clarification, I've left laptop for the night running and got firedrake installed. May be warning in installation (about possibly long installation process) is in order

**Comment by dorugeber** [comment]
As I said, I suspect there is something strange going on in 15.10 that makes PETSc take a lot longer to install.

I vaguely recall running the firedrake test suite and finding that also took longer on 15.10 than on 14.04.  I seem to remember this was caused by the newer GCC taking longer to generate code, but I can't be certain any more.  I wonder if this is also responsible for PETSc time.
