### ISSUE TITLE
PETSc ftbfs on Ubuntu 15.10

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#755]
python firedrake-install

fails on a clean Ubuntu 15.10 VM. Error is in the netcdf configure during the PETSc build.

    configure: error: Can't find or link to the z library. Turn off
    netCDF-4 and opendap with --disable-netcdf-4 --disable-dap, or see
    config.log for errors.

**Comment by dorugeber** [comment]
Ugh, I hit this 6 months ago in #619; sorry for not reporting it properly at the time.
