### ISSUE TITLE
Meshes that are only 1 element thick

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#760]
I would like to construct meshes that are 1 element thick in the y -direction, made out of quadrilaterals, possibly periodic in the x direction. I would also like to be able to extrude these meshes in the z-direction.

**Comment by colinjcotter** [comment]
Lawrence wrote:

So you would like a mesh, I'll draw quads:

x---o
|   |
|   |
y---p

Where the vertical edges and the vertices are periodic (i.e. x and o
are topologically the same and similarly y and p).

I think you might be able to do this if you talk directly to the
dmplex API.  First you make the topological cells you want, then you
build a coordinate section (a functionspace) on that DM and set up
your coordinates appropriately.  We'd then have to do a little bit of
plumbing to make sure that your could tell firedrake that the
coordinate field petsc provides is already discontinuous.

**Comment by colinjcotter** [comment]
Actually I want a mesh with n elements in the x direction but only 1 element in the y direction. I also forgot to wrote above that I would like the mesh topology to be periodic in the y direction.

**Comment by wence-** [comment]
Ok, it's basically the same though. Just rotate my picture through 90 degrees and set n to one :).

**Comment by colinjcotter** [comment]
Yep. Please can you give me some pointers about what needs to be done to talk to dmplex? Which functions should I look at?

**Comment by colinjcotter** [comment]
OK, I see some examples in utility_meshes.py

**Comment by colinjcotter** [comment]
Ah, won't we have the same problem that we had making periodic meshes before, and so we need to build it in 3D space as a torus and then remap it?

**Comment by colinjcotter** [comment]
Hmm, no that won't work either.

**Comment by miklos1** [comment]
I would just build the plex directly, and then override the coordinates.

**Comment by colinjcotter** [comment]
OK, then I do need some further pointers, since I can't use
mesh._from_cell_list for this.

On 25 April 2016 at 13:53, Miklós Homolya <notifications@github.com> wrote:

> I would just build the plex directly, and then override the coordinates.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/760#issuecomment-214460705>
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by miklos1** [comment]
I would indeed start with `mesh._from_cell_list` using vertex coordinates (x, 0). Then create a new mesh with DG coordinates. This still has y = 0 everywhere, so you need to fix up coordinate values. To know which "corners" should stay y = 0 and which should become y = 1 is not so trivial, you need to examine on the mesh topology to figure that out.

**Comment by miklos1** [comment]
Oh wait, even doing edge orientations on such a mesh topology is problematic, since many edges are actually loops around a single vertex, and loops don't really have a direction.

**Comment by colinjcotter** [comment]
How about if we just make sure the mesh orientation is correct by construction, and then don't run the orientation algorithm?

**Comment by miklos1** [comment]
I just don't know what orientation means for a loop edge.

**Comment by colinjcotter** [comment]
I have a geometric understanding of it, I need to understand how you
describe orientation before I can try to translate from geometry to algebra.

--cjc

On 25 April 2016 at 16:04, Miklós Homolya <notifications@github.com> wrote:

> I just don't know what orientation means for a loop edge.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/760#issuecomment-214502911>
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by miklos1** [comment]
[Here](https://gist.github.com/miklos1/19c2e296d671030c47a4eb14726d664a) is a manual sketch for a 3x1 mesh.

**Comment by wence-** [comment]
This is in, closing.
