### ISSUE TITLE
modification of basis functions in mass matrix

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#766]
In this paper:
http://onlinelibrary.wiley.com/doi/10.1002/qj.2189/abstract;jsessionid=C6DC75193A2A91FFC6D59621E28B3B8E.f01t01

we proposed a modification to the mass matrix which fixes a dispersion relation issue in the shallow water equations for RT2 (in UFL nomenclature) elements.

This modification requires to assemble

a = Constant(0.1) #not the actual number
u = TestFunction(RT2)
v = TrialFunction(RT2)
(1-a)*inner(u,v)*dx + a*inner(P(u),P(v))*dx

where P(u) replaces u by the function with the same basis coefficients but different basis functions. The new basis functions are constructed as follows:
(1) Functions with u.n=0 vanishing on all boundaries are replaced by 0
(2) Functions associated with edges, i.e. those functions that change u.n on boundaries, are replaced with functions that decay linearly away from the boundary instead of quadratic.

This would require to tabulate this alternative basis and use it inside the kernel.

**Comment by miklos1** [comment]
Will you need a general framework to support argument basis function replacement, or you just want to solve this specific mass matrix problem? If the latter, I suggest to just write the kernel manually in GEM.

**Comment by colinjcotter** [comment]
Well, I will need to embed this in with some other tools, e.g. as part of a
mixed system, perhaps hybridised. So if that is possible then I am fine to
write the kernel manually [with tuition!].

all the best
--cjc

On 28 April 2016 at 07:49, Miklós Homolya <notifications@github.com> wrote:

> Will you need a general framework to support argument basis function
> replacement, or you just want to solve this specific mass matrix problem?
> If the latter, I suggest to just write the kernel manually in GEM.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/766#issuecomment-215399957>
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by colinjcotter** [comment]
CLosed because I found a better way to achieve  this.
