### ISSUE TITLE
Firedrake extensions to the FEniCS language

### ISSUE THREAD

**Issue by dham** [firedrakeproject/firedrake#771]
For FEniCS I need to make a poster of Firedrake extensions to the FEniCS language. We have:

* Tensor product/extruded
* Bendy?
* GMG
* Quad meshes
* UFL expression interpolation

What else?

**Comment by miklos1** [comment]
We claim to have proper non-affine support, I'm not sure what the state of this is in FEniCS. To my best knowledge they have second-order simplices with UFLACS, but I may be very wrong.

**Comment by colinjcotter** [comment]
Escape hatch?

On 5 May 2016 at 16:14, David A. Ham <notifications@github.com> wrote:

> For FEniCS I need to make a poster of Firedrake extensions to the FEniCS
> language. We have:
>
>    - Tensor product/extruded
>    - Bendy?
>    - GMG
>    - Quad meshes
>    - UFL expression interpolation
>
> What else?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/771>
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by dham** [comment]
Colin: excellent point.

Miklos: well put. We can claim arbitrary order.

**Comment by colinjcotter** [comment]
Too late, but I remembered about Projector ...

--cjc

On 5 May 2016 at 16:43, David A. Ham <notifications@github.com> wrote:

> Colin: excellent point.
>
> Miklos: well put. We can claim arbitrary order.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/771#issuecomment-217190133>
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by colinjcotter** [comment]
... and the expressions compiler ...

On 16 May 2016 at 17:23, Colin Cotter <colin.cotter@imperial.ac.uk> wrote:

> Too late, but I remembered about Projector ...
>
> --cjc
>
> On 5 May 2016 at 16:43, David A. Ham <notifications@github.com> wrote:
>
>> Colin: excellent point.
>>
>> Miklos: well put. We can claim arbitrary order.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/firedrakeproject/firedrake/issues/771#issuecomment-217190133>
>>
>
>
>
> --
> http://www.imperial.ac.uk/people/colin.cotter
>
> www.cambridge.org/9781107663916
>
>
>


-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by dham** [comment]
Expressions interpolation is on the poster.

**Comment by dham** [comment]
Poster is done. Thanks all.
