### ISSUE TITLE
Custom start index for VTK output file numbering

### ISSUE THREAD

**Issue by tkarna** [firedrakeproject/firedrake#772]
Currently VTK output files always start at index 0, i.e. the first file is `field_0.vtu`. However if you need to continue a previous simulation you should be able to set a custom start index.

I guess we could add a custom start index to `File` constructor. Or add a keyword arg in write method

``` python
File.write(..., index=4)
```

that overrides the default counter, similarly to `time`. This requires that the users keeps track of the counter however.

In terms of continuing a simulation, I'm not sure how to handle the pvd file though. Creating a new `File` object will re-create it, therefore wiping out all the previous time steps, which is the right behavior in most cases. For my applications this is not a major issue though.

**Comment by wence-** [comment]
How about `File("foo.pvd", restart=count)`  Which would open the file for "restarted" output, providing the initial value of the counter.  Now we can just call `File.write(...)` as normal and the correct thing will happen (appending to the end of the existing pvd file).

**Comment by wence-** [comment]
IOW, I prefer the custom start index, rather than an extra argument to the write method.

**Comment by wence-** [comment]
One could even (ugh) do the following: `File(..., restart=True)` and I would open the file, figure out how many `DataSet` entries have been written and then set the counter appropriately.

**Comment by tkarna** [comment]
`File("foo.pvd", restart=count)` sounds like a good idea. I guess in this case you could just append to the pvd file instead of regenerating it, or (maybe better) just writing the `0, ..., count-1` entries there first.

The latter form `File(..., restart=True)` assumes that you want to restart from the last written index which might not be true.

**Comment by colinjcotter** [comment]
I also like the custom start index.

**Comment by wence-** [comment]
Fixed by #1059.
