### ISSUE TITLE
Endless loop in RectangleMesh

### ISSUE THREAD

**Issue by ANaumann85** [firedrakeproject/firedrake#794]
Hello Firedrakers,

the command
RectangleMesh(10, 1.0e-5, 1.0, 4.0)

leads to an infinite loop on my system. The float 1.0e-5 is not a valid number of cells in y direction.
It would be better to throw an exception or print a warning, that the number of cells is less than 1 or a float.

Regards,
Andreas

**Comment by dham** [comment]
Fair point. It would be good if we crashed politely in that case.

**Comment by wence-** [comment]
Fixed in #795.
