### ISSUE TITLE
Unexpected results mixing dx and dx(N)terms in forms

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#797]
When solving the following over a 2D domain that consists of two regions marked in gmsh with Physical Surface IDs 1 and 2:

    mesh2d = Mesh('headland.msh')
    V = FunctionSpace(mesh2d, "DG", 1)
    v = TestFunction(V)
    u = Function(V)
    solve(v*u*dx + v*u*dx(2) - v*dx == 0, u)

The answer I get is 1 in region 1 (as expected), but is 2/3 in region 2 where I would expect it to be 1/2. Other equivalent forms that also give a (different) wrong answer are:

    v*u*dx(1) + v*u*dx(2) + v*u*dx(2) - v*dx == 0
    v*u*dx + v*u*dx(2) - v*dx(1) - v*dx(2) == 0

Only by splitting up all dx terms, do I get the correct answer:

    v*u*dx(1) + v*u*dx(2) + v*u*dx(2) -v*dx(1) - v*dx(2) == 0

**Comment by stephankramer** [comment]
Just checked with Dolfin, and it does what you'd expect (i.e. all the variants above give the same answer with 1 in region 1, and 1/2 in region 2).

**Comment by wence-** [comment]
This is a bug in the treatment of the "otherwise" subdomain.  `v*dx + v*dx(2)` is translated into:
`2*v*dx(2) + v*dx("otherwise")`.  Where "otherwise" is all the subdomains that do not appear explicitly in the form.  But we treat "otherwise" as the entire domain, rather than the complement of the explicitly specified subdomains.  So you get two contributions in the `dx(2)` integrals from `2*v*dx(2)` and then a third one from `v*dx("otherwise")`, which is why you get the wrong answer.

**Comment by wence-** [comment]
Related, #281.

**Comment by colinjcotter** [comment]
Does this translation occur in UFL? It seems a rather odd decision.

--cjc

On 31 May 2016 at 20:22, Lawrence Mitchell <notifications@github.com> wrote:

> This is a bug in the treatment of the "otherwise" subdomain. v*dx +
> v*dx(2) is translated into:
> 2*v*dx(2) + v*dx("otherwise"). Where "otherwise" is all the subdomains
> that do not appear explicitly in the form. But we treat "otherwise" as the
> entire domain, rather than the complement of the explicitly specified
> subdomains. So you get two contributions in the dx(2) integrals from
> 2*v*dx(2) and then a third one from v*dx("otherwise"), which is why you
> get the wrong answer.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/firedrakeproject/firedrake/issues/797#issuecomment-222792809>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF0q8g4iCeuesBfHIMFrsxbnl9AMxx5uks5qHIp7gaJpZM4IqyU8>
> .
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by wence-** [comment]
Yes
