### ISSUE TITLE
Optional "max", "min" flags for interpolate method of functions

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#801]
For slope limiters it would be very useful to be able to have the option to max or min instead of assign.

e.g. 

q.interpolate( ufl_exp, max=True)

would replace each node value q_i with max(q_i, u_i) where u_i is the interpolation of ufl_exp to the coordinate value associated with q_i.

**Comment by wence-** [comment]
This is now supported, right `interpolate(expr, access=MIN/MAX/WRITE/INC)` (default is `WRITE`)
