### ISSUE TITLE
Periodic boundary conditions in 1D for DG

### ISSUE THREAD

**Issue by j130792** [firedrakeproject/firedrake#818]
Hi,

I'm trying to implement linear advection in 1D using DG test and trial spaces on a periodic domain but strange things seem to be happening on the periodic boundary. Changing the spaces to CG the periodic boundary works and the code behaves as expected. Is the periodic domain supported for DG elements, and if not is there any known workaround? 

Thanks,
James

<pre><code>
# Linear advection in 1D
# ================
# u_t + u_x = 0
# with periodic boundary conditions

from firedrake import *

#Set up mesh and end time
n = 50
T = 1
mesh = PeriodicUnitIntervalMesh(n)

#Define function spaces
V = FunctionSpace(mesh, "DG", 1)

#Define functions
u_ = Function(V, name="Solution")
u = Function(V, name = "SolutionNew")
v = TestFunction(V)

#Set up some initial conditions
f = Expression("0.0 + 1.0*( 0.25 < x[0] ) - 1.0*( x[0] > 0.75 )")
ic = project(f, V)

#Assign them
u_.assign(ic)
u.assign(ic)

#Set timestep
timestep = float(T)/n

#Define normal
n = FacetNormal(mesh)

#Set up the form using C-N in time
udot = (u-u_)/timestep
ueval = (u+u_)/2

F = udot*v*dx \
    + ueval.dx(0) * v*dx \
    - jump(ueval,n[0])*v('-')*dS

#Create output file
outfile = File("tmp/linadvect.pvd")
outfile.write(u_,time=0.)

#Loop over time and solve
t = 0.0
while (t <= T):
    solve(F==0, u)
    u_.assign(u)
    t += timestep
    outfile.write(u_,time=t)
</code></pre>

**Comment by miklos1** [comment]
> `jump(ueval,n[0])*v('-')*dS`

Why don't you have a `v('+')` term as well?

**Comment by j130792** [comment]
Thank you for the quick reply! 

Adding a `v('+')` term does solve the problem, so the flux choice `jump(ueval,n[0])*avg(v)` behaves as it is supposed to (and this is sufficient for my current application). However the original flux choice is a standard one to choose for this type of problem as it is diffusive, and it does seem to be doing what it is supposed to up to the periodic boundary.

**Comment by miklos1** [comment]
Please be aware, that Firedrake works on unstructured meshes, thus in interior facet integrals you cannot have any assumptions about which one is the + and which one is the - side. Even if you use an upwind flux, which only uses one side, you have to write your form in a way which is indifferent to whether the + or the - side is upwind.

**Comment by dorugeber** [comment]
Yes, this is exactly it.  You cannot assume anything about which side is `+` and which side is `-`.  If you are using upwinding then the steady-state upwind advection example might help you.

**Comment by j130792** [comment]
Thank you both for your help :)
