### ISSUE TITLE
Maybe broken test ?

### ISSUE THREAD

**Issue by FabioLuporini** [firedrakeproject/firedrake#820]
The test in question is ``test_facet_orientation.py``

We define:
``expression = Expression("x[0]*(x[0] + sqrt(2.0)) + x[1] + x[2]*x[2]*x[2]")``

but the test is also run on a UnitSquareMesh, where presumably x[2] won't be defined

non allocated memory is then accessed. Results are "surprisingly" correct untill loop fusion (which I'm testing at the moment) is switched on. Manually changing

``double x[2]``

to

``double x[3]``

seem to make the issue disappear. Am I missing something?

**Comment by wence-** [comment]
Yes, that's clearly nonsense.  Does the test pass if you remove the `x[2]` parts of the expression?

**Comment by FabioLuporini** [comment]
apparently yes. I can file a PR if you are happy with this change

**Comment by wence-** [comment]
Go ahead
