### ISSUE TITLE
test_tsfc_cache_dir_exists fails 

### ISSUE THREAD

**Issue by tmbgreaves** [firedrakeproject/firedrake#822]
test_tsfc_cache_dir_exists fails, reproduced starting from a base ubuntu:trusty (with clean /tmp) then:

apt-get -y update
apt-get -y dist-upgrade
apt-get -y install test_tsfc_cache_dir_exists
pip install virtualenv
curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/master/scripts/firedrake-install
python ./firedrake-install
. firedrake/bin/activate
py.test -v firedrake/src/firedrake/tests/test_tsfc_interface.py

**Comment by wence-** [comment]
Yes, this invariant is no longer true.  I think that's a stupid test, can you just remove it?

**Comment by tmbgreaves** [comment]
OK. Thanks.
