### ISSUE TITLE
MPI installation issue

### ISSUE THREAD

**Issue by mtayachi** [firedrakeproject/firedrake#836]
Hello,
I got this error message when I tried to install Firedrake using the standard install script (python firedrake-install):

firedrake/lib/python2.7/site-packages/petsc/include/H5public.h:63:13: fatal error: 
      'mpio.h' file not found
# include <mpio.h>

```
        ^
```

1 warning and 1 error generated.
error: command 'mpicc' failed with exit status 1
Traceback (most recent call last):
  File "firedrake-install", line 924, in <module>
    build_and_install_h5py()
  File "firedrake-install", line 599, in build_and_install_h5py
    run_cmd(python + ["setup.py", "build"])
  File "firedrake-install", line 404, in run_cmd
    check_call(args)
  File "firedrake-install", line 228, in check_call
    subprocess.check_call(arguments, env=env)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/Manel/Dropbox/CEMRACS2016/Codes/themis/firedrake/bin/python', 'setup.py', 'build']' returned non-zero exit status 1

I'm using Mac OS X (El Capitan). Any assistance would be greatly appreciated!

Thanks,

Manel

**Comment by wence-** [comment]
Dear Manel,

could you please remove the firedrake directory and run `python firedrake-install --log --minimal-petsc` and attach the resulting `firedrake-install.log` file to this issue.  Something must have gone on earlier to get this wrong, but I don't know what.  This will give us more information.

**Comment by mtayachi** [comment]
Dear Lawrence,

Thank you for your quick response. This is the report. I noted that now I
have a new error message.

Sincerely,

Manel

2016-07-26 15:59 GMT+02:00 Lawrence Mitchell <notifications@github.com>:

**Comment by wence-** [comment]
I think your reply via email managed to lose the attached report!  Can you do so via the website?

**Comment by mtayachi** [comment]
sorry this the report! 

Thanks,

Manel

ps: I wasn't able to enclose the file .log so I saved it as a .text
[firedrake-install.txt](https://github.com/firedrakeproject/firedrake/files/384329/firedrake-install.txt)

**Comment by wence-** [comment]
Hmm.  I see you're running MacOS 10.6.  We certainly don't test with a version that old, so I'm not sure if things necessarily will work.  Although most things seemed to install...  Can you please provide the output of the following (typed in the terminal):

```
echo $PATH
echo $PYTHONPATH
python --version
mpicc --version
mpicc -show
alias
which python
which mpicc
```

Thanks.

**Comment by mtayachi** [comment]
hmmm I upgraded to El Capitan so I should have now the version 10.11.6 so curious!

1) echo $PATH
/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/TeX/texbin:/Users/Manel/Softs/Telemac3D/trunk/src/bin:/opt/local/bin

2) echo $PYTHONPATH  

3) python --version 
 Python 2.7.9
4) mpicc --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

5) mpicc -show
clang -I/usr/local/Cellar/open-mpi/1.10.2_1/include -L/usr/local/opt/libevent/lib -L/usr/local/Cellar/open-mpi/1.10.2_1/lib -lmpi

6) alias 
alias freefem++='/Applications/FreeFem++.app/Contents/MacOS/FreeFem++'
alias ll='ls -ltr'

7) which python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python

7) which mpicc
/usr/local/bin/mpicc

**Comment by dham** [comment]
Hi Manel,

Looks like something is going wrong with your mpi install. Looking
at H5public.h, I can see that mpio.h is only #include-d if MPI_FILE_NULL is
not defined in mpi.h. For me, (also on el capitan), mpi.h does define that
symbol:

(firedrake)*dham@schleppmac** firedrake **>* grep -n MPI_FILE_NULL
/usr/local/include/mpi.h

748:#define MPI_FILE_NULL OMPI_PREDEFINED_GLOBAL(MPI_File,
ompi_mpi_file_null)


This makes me suspect that firedrake-install on your system is not picking
up the home-brew openmpi. Do you perchance have multiple mpi
implementations installed?

Regards,

David

**Comment by mtayachi** [comment]
Hi David,

It's probably the problem. I'm trying to figure out how to remove the previous versions of mpi and I will come back to you.

thanks!

Manel
