### ISSUE TITLE
mesh callback not called

### ISSUE THREAD

**Issue by dmculley** [firedrakeproject/firedrake#839]
I'm trying to get at the list of external facets but need to trigger the mesh callback myself - am I doing something wrongly or is this a bug?

```
mesh = UnitSquareMesh(10, 10)
mesh.topological.exterior_facets.unique_markers
```
doesn't work but
```
mesh = UnitSquareMesh(10, 10)
mesh._callback(mesh)
mesh.topological.exterior_facets.unique_markers
```
does. Thanks

Dave

**Comment by miklos1** [comment]
Just call `mesh.init()` if you want to access stuff on the mesh before using in a function space or similar.
