### ISSUE TITLE
dx in combination with restricted ds broken on meshes with cell/region ids

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#840]
The following code:

    from firedrake import *
    mesh = Mesh("square.msh")
    V = FunctionSpace(mesh, "CG", 1)
    v = TestFunction(V)
    u = TrialFunction(V)
    assemble(v*u*dx+v*u*ds(2)).M

fails on a mesh that has cell ids (gmsh Physical Surface in 2D, see attached mesh in square.zip which defines a cell id of 1 everywhere) with the attached backtrace.
[backtrace.txt](https://github.com/firedrakeproject/firedrake/files/386294/backtrace.txt)
[square.zip](https://github.com/firedrakeproject/firedrake/files/386296/square.zip)

The issue is that the `dx` integral is performed as an `otherwise` integral which uses `all_integer_subdomain_ids` defined in line 228 of firedrake/assemble.py. However that list is assembled with complete disregard of what type of integral is performed by the different kernels (i.e. cells vs facet integrals) and thus ends up as the list (2,). Since the mesh does not have a region 2 it crashes. Along the same lines, if the surface integral is changed to `ds(1)`, the dx integral is not added in since `otherwise` is incorrectly interpreted as outside of the 1-region.

**Comment by wence-** [comment]
Oops...

**Comment by wence-** [comment]
On it...

**Comment by wence-** [comment]
Think that branch gets it.

**Comment by stephankramer** [comment]
Does the job for me! Thanks!
