### ISSUE TITLE
NaNs with mixed quadrature degree and coffee

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#847]
So this one is turning out a little tricky to reproduce. But with the following code:

    from firedrake import *
    #parameters['coffee'] = {}
    mesh = UnitSquareMesh(1,1)
    V = FunctionSpace(mesh, "RT", 2)
    P1 = FunctionSpace(mesh, "CG", 1)
    v = TestFunction(V)
    u = Function(V)
    c1 = Function(P1)
    c1.assign(0.001)
    c2 = Constant(1e-6)
    dt = Constant(1.0)
    dx2 = dx(degree=5)
    F = inner(v,u)*dx - dt*(- c2*inner(v,u)*dx2 - c1*(-u[1]*v[0] + u[0]*v[1])*dx2)
    print assemble(derivative(F,u)).M.values.sum()

I'm getting NaNs in the assembled matrix (most of the time!) if I leave COFFEE optimisations switched on. I say most of the times, as running the script multiple times I sometimes get different answers (sometimes the correct one), so I expect some sort of initialised value bug? It seems to be also very sensitive to the precise form of the equation.

**Comment by stephankramer** [comment]
After some more debugging I found the uninitialized variable. If you look at the [kernel code](https://gist.github.com/stephankramer/7f65762ae53e2414f84525f169641d48), line 86 declares array t21 which is first used, uninitialized, on line 109.

**Comment by FabioLuporini** [comment]
I'll be handling this issue in COFFEE (see https://github.com/coneoproject/COFFEE/issues/88)
