### ISSUE TITLE
Assignment to function does not immediately update point evaluation results

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#850]
The following code:

    from firedrake import *

    mesh = UnitSquareMesh(1,1)
    V = FunctionSpace(mesh, "CG", 1)
    u1 = Function(V)
    u2 = Function(V)
    u1.assign(1.0)
    print u2((0.5, 0.5))
    u2.assign(u1)
    print u2((0.5, 0.5))
    print u2.dat.data_ro
    print u2((0.5, 0.5))

gives the following output:

    $ python test.py
   0.0
   0.0
   [ 1.  1.  1.  1.]
   1.0

which shows that the point evaluation of u2 only gets updated after I've explicitly asked for its data array.

**Comment by wence-** [comment]
Thanks, fortunately this was an easy one.
