### ISSUE TITLE
firedrake-install --developer --adjoint requires additional firedrake-update to become functional

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#852]
If I run

```
  firedrake-install --developer --adjoint
```

to build firedrake, it seems the installation process doesn't complete succesfully: although everything builds and (claims to) install successfully, if I try to import firedrake after a `source firedrake/bin/activate` it still can't find it. The required firedrake/lib/python2.7/site-packages/firedrake.egg-link seems to be in place though. If run a firedrake-update however, the issue seems to disappear and it can succesfully import firedrake.

If I run

```
 firedrake-install --developer --adjoint
 cp -ax firedrake firedrake-copy
 python firedrake/bin/firedrake-update
```

and diff the firedrake/ and firedrake-copy/ directories, it seems the main difference is:

```
$ diff -r --exclude="*.pyc" firedrake/lib/python2.7/site-packages/ firedrake-copy/lib/python2.7/site-packages/
diff -r '--exclude=*.pyc' firedrake/lib/python2.7/site-packages/easy-install.pth firedrake-copy/lib/python2.7/site-packages/easy-install.pth
1d0
< /home/skramer/firedrake/src/dolfin-adjoint
3,8c2
< /home/skramer/firedrake/src/COFFEE
< /home/skramer/firedrake/src/ufl
< /home/skramer/firedrake/src/fiat
< /home/skramer/firedrake/src/tsfc
< /home/skramer/firedrake/src/PyOP2
< /home/skramer/firedrake/src/firedrake

---
> /home/skramer/firedrake/src/dolfin-adjoint
```

i.e. immediately after the install it only contains dolfin-adjoint. Is this possibly to do with the "Work around easy-install.pth bug" (line 935 of firedrake-install) which is perhaps then overwritten again by the subsequent `build_and_install_adjoint()` on line 1025?

**Comment by dham** [comment]
That's probably it. easy-install.pth is a nightmare

**Comment by dham** [comment]
Funny. I just had reason to do this:
````
firedrake-install --adjoint
````
note that you now get developer mode for free. I was immediately able to import both firedrake and firedrake-adjoint.

**Comment by wence-** [comment]
Can no longer reproduce.  Please re-open if there are still problems.
