### ISSUE TITLE
DumbCheckpointing with get/set timestep raises petsc error

### ISSUE THREAD

**Issue by dmculley** [firedrakeproject/firedrake#854]
(assuming I'm using it correctly) DumbCheckpointing with get/set timestep raises petsc error

```
from firedrake import *
mesh = UnitSquareMesh(1,1)
V = FunctionSpace(mesh, 'CG', 1)
u = Function(V)
u.assign(Constant(5))
cp = DumbCheckpoint('test')
t = 0
cp.set_timestep(t)
cp.store(u)
cp.close()
```
 then 

```
from firedrake import *
mesh = UnitSquareMesh(1,1)
V = FunctionSpace(mesh, 'CG', 1)
u = Function(V)
cp = DumbCheckpoint('test')
cp.get_timesteps()
cp.load(u)
```

raises

```
PETSc/Vec.pyx in petsc4py.PETSc.Vec.load (src/petsc4py.PETSc.c:94226)()

Error: error code 76
[0] VecLoad() line 975 in /tmp/pip-OXLorA-build/src/vec/vec/interface/vector.c
[0] VecLoad_Default() line 409 in /tmp/pip-OXLorA-build/src/vec/vec/utils/vecio.c
[0] VecLoad_HDF5() line 267 in /tmp/pip-OXLorA-build/src/vec/vec/utils/vecio.c
[0] Error in external library
[0] Error in HDF5 call H5Dopen2() Status -1
```

However leaving out the timestep business works fine

Ta

**Comment by wence-** [comment]
You need to `cp.set_timestep(0)` before trying to load the function.

**Comment by wence-** [comment]
The storage convention is.  If no timestep has been set, fields are stored at `/fields/function_name`.  If a timestep *has* been set, then the fields are stored at `/fields/tidx/function_name`.  When you open a new file it doesn't have any time steps set, so it thinks the fields are in `/fields/function_name`.

**Comment by wence-** [comment]
You could add some error checking inside `DumbCheckpoint` if you like.  You can check that a given path exists in the file by doing `some_path in self.h5file`.  Patches welcome.

**Comment by dmculley** [comment]
Thanks very much
