### ISSUE TITLE
Removing FunctionHierarchy in firedrake/mg

### ISSUE THREAD

**Issue by alsgregory** [firedrakeproject/firedrake#857]
Hi,

To begin removing the unnecessary FunctionHierarchies functionality, how would I go about doing this?

Is this simply a case of removing any uses / tests of this functionality throughout firedrake/mg (and clearly the actual class itself)? Or is this a case of putting warnings where this class is called to alert of 'functionality is now redundant'?

Many Thanks,
Ali

**Comment by wence-** [comment]
Two steps.

1. Remove them all and get everything working with `FunctionHierarchy`

2. Add back in a `FunctionHierarchy` that spews a big warning and just returns a list of functions (I think).

**Comment by alsgregory** [comment]
Is this meant to be *without instead of *with in 1).

**Comment by wence-** [comment]
yes.

**Comment by alsgregory** [comment]
The stage of removing every dependency of FH from tests and other mg scripts is nearly complete, however the only tests that are failing are the poisson_gmg problems in the 'fas' and 'parallel' options. The tests are returning errors of 10e3 instead of 1e-6. I know it's probably hard to know why without seeing the code but could you see any reason why these tests would fail? 

In the solver_hierarchy and utils scripts I've changed all FunctionHierarchy's to tuples of functions and when get_level is used I've got the level off the FunctionSpaceHierarchy instead of the FunctionHierarchy.

**Comment by wence-** [comment]
No idea sorry.

**Comment by wence-** [comment]
I mean, I might be able to guess if I can see what you've done...

**Comment by alsgregory** [comment]
Cool, multiple scripts are altered, what would be the best way to do this? "Send a pull request knowing tests will fail?"

**Comment by wence-** [comment]
You can push the branch somewhere without opening a pull request

**Comment by alsgregory** [comment]
Of course; thanks

**Comment by alsgregory** [comment]
This is now in the branch 'remove_function_hierarchy'

**Comment by alsgregory** [comment]
Unfortunately the same errors are persisting? I've updated the branch code with the fixes. Do you know of any more possible causes?

**Comment by wence-** [comment]
I will look tomorrow

**Comment by alsgregory** [comment]
Any ideas on what could be causing these fails? I have gone through the test manually in a python session and the injections in coarsen_thing are working as they should, so I'm a bit confused as to where the errors are creeping in.

**Comment by wence-** [comment]
Yeah, got it, will push a fix.

**Comment by wence-** [comment]
Try now, I think it's right.  The problem was that the coarsening of the nonlinear problem broke the connection between the state vector we were solving for and the state vector in the forms.  I fixed that.

**Comment by alsgregory** [comment]
Thanks very much for this. I'll pull this and then push my last commit when the tests have passed.

**Comment by alsgregory** [comment]
merged into master -> closing issue.
