### ISSUE TITLE
Point evaluation on moving meshes

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#860]
This from @ANaumann85 (taken from #793).

> I tried the evaluation on a moving mesh using the firedrake-install from yesterday (August 15th). This time, there is a small numerical error, as can be seen by the appended test case.
My mesh moves from 0.2 to units in negative y-direction in 5 steps. Before each movement, I create a new Function u_A and interpolate some values in the lines 20 and 21 respectively. 
After that, I try to evaluate at (0, 2.2), which resides in the mesh in all iterations. But the function call
u_A.at(0.0, 2.2)
returns the correct value only in the first iteration. Every later iteration, it returns a None, i.e. it does not find the point.
Furthermore, the evaluation at the same y-coordinate, but a slightly shifted x-coordinate works, see line 25 in the appended test.
This behavior is interesting, because we move the mesh in x and y direction once (see line 16). After this movement, we find the value at the point (0.0, 2.2). All further movements only effect the y-direction, so the x coordinate values should not change at all.

With code:

```python
from firedrake import *

nx     = 20
ny     = 40

t      = 0.0
tend   = 2.0
nsteps = 5
timestep = (tend-t)/float(nsteps)

meshA = RectangleMesh(10, 10, 0.5, 0.5)
Vc    = meshA.coordinates.function_space()
f2    = Function(Vc).interpolate(Expression(("x[0]-0.5","x[1]+2.0")))
#move the first time
#meshA.coordinates.assign(f2)
meshA = Mesh(Function(f2))

out_A = File('meshA.pvd')
while t < tend:
  V_A = FunctionSpace(meshA, "CG", 1)
  u_A = Function(V_A, name="TemperatureA")
  u_A.interpolate(Expression("1.0*t", t=t))

  # Check value at one specific point, it is allways inside 
  print 'uA(-1.0e-15,2.2):', u_A.at((-1.0e-15, 2.2), dont_raise=True)
  print 'uA(0,2.2):', u_A.at((0, 2.2), dont_raise=True)
  out_A.write(u_A)
  Vc = meshA.coordinates.function_space()
  f2  = Function(Vc).interpolate(Expression(("x[0]", "x[1] - shift"), shift = 0.1*timestep ))
#  del  meshA.spatial_index
#  meshA.coordinates.assign(f2)  
#  del  meshA.spatial_index
  meshA = Mesh(Function(f2))

  t += timestep
```

**Comment by wence-** [comment]
I cannot reproduce this problem with current master.  I get:

```
uA(-1.0e-15,2.2): 0.0
uA(0,2.2): 0.0
uA(-1.0e-15,2.2): 0.4
uA(0,2.2): 0.4
uA(-1.0e-15,2.2): 0.8
uA(0,2.2): 0.8
uA(-1.0e-15,2.2): 1.2
uA(0,2.2): 1.2
uA(-1.0e-15,2.2): 1.6
uA(0,2.2): 1.6
```

**Comment by wence-** [comment]
Could be a roundoff issue I guess.  The interpolation of the new coordinates does a matrix-vector product with what is mathematically the identity but numerically may be very close to (but not exactly) the identity.  Computational geometry is hard.  For discussion of similar issues, see #805.

**Comment by ANaumann85** [comment]
Thanks for your hint for issue #805. It seems to be the same and we could close this issue.
