### ISSUE TITLE
OuterProductElement not found

### ISSUE THREAD

**Issue by ANaumann85** [firedrakeproject/firedrake#866]
Dear firedrakers :)

we try to test the helmholtzsolver 
https://github.com/firedrakeproject/firedrake-helmholtzsolver/

Unfortunatly, the tests use an (older?) firedrake version, especially the type "OuterProductElement".
I could not find any changelog, or other information regarding this structure.
I assume, I have to replace the OuterProductElement by another type? Or something completely different?

Thanky for your help,
Andreas

**Comment by dorugeber** [comment]
`TensorProductElement`

**Comment by wence-** [comment]
There are many changes you will have to make, please try the `update-to-current` branch in that repository.

**Comment by wence-** [comment]
If you want a set of versions that are compatible with the current master, you should checkout the tag: `Firedrake_20160428.0` in the components: `fiat`, `ufl`, `pyop2`, `firedrake`, `coffee`, `petsc`, `petsc4py`.  And you'll need to install `instant` (from bitbucket.org/fenics-project/instant) and ffc (again with tag Firedrake_20160428.0) from github.com/firedrakeproject/ffc.

Note that, as you have noticed, these are out of date components.

**Comment by wence-** [comment]
You'll need to reinstall all of these components "by hand", because unfortunately `firedrake-update` won't do the trick for you.  All of them are easy (just pip uninstall the component first) then cd into the directory, do `git clean -fdx; pip install .`.  Except PETSc, where you'll want to do:

```
PETSC_CONFIGURE_OPTIONS="--download-ctetgen --download-triangle --download-chaco --download-metis --download-parmetis --download-scalapack --download-hypre --download-mumps --download-netcdf --download-hdf5 --download-exodusii" pip install .
```
