### ISSUE TITLE
store dictionary in checkpoint

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#880]
Storing parameters in the checkpoint file
would be very useful, e.g. value of time.

David suggested having a dictionary that 
can be written to in the dumb checkpoint file.

**Comment by wence-** [comment]
This already exists to some extent.  You can write to the HDF5 file attributes using `write_attribute` and `read_attribute`.  Note that you cannot store generic types in HDF5 files, so if you want to store a dictionary (say) you must pickle them first.

Once the new load/store configuration stuff lands, we can think about being able to save a `Parameters` instance on the checkpoint file.

**Comment by colinjcotter** [comment]
ah ok, I missed reading those! I will store time this way.
