### ISSUE TITLE
unique mesh boundary markers not valid subdomain ids in ds

### ISSUE THREAD

**Issue by alsgregory** [firedrakeproject/firedrake#899]
When looping around markers in `mesh.topology.exterior_facets.unique_markers`, the markers are in the form of `int32`, `int64`, `int8` or `int16`, not `int`.

Unfortunately when trying to put these looped markers into `ds(marker)`, they trigger an error `Invalid subdomain_id` given that they are not `int` type.

Is there any way of allowing the markers to be of this type.

Minimal example:

`from firedrake import * `
`mesh = UnitSquareMesh(5, 5)`
`fs = FunctionSpace(mesh, 'DG', 0)`
`A = mesh.topology.exterior_facets.unique_markers`
`ds(A[0])`

**Comment by dham** [comment]
This is actually a UFL bug. UFL is being excessively pedantic about the type at measure.py:169. The test should be relaxed to allow for any type of int.

**Comment by dham** [comment]
relaxing it to allow for numpy.integer as well as int would do it.

**Comment by dham** [comment]
Oh, and ufl already depends on numpy, so this wouldn't even be controversial.

**Comment by alsgregory** [comment]
See pull request: https://github.com/FEniCS/ufl/pull/1

**Comment by miklos1** [comment]
Fixed in UFL.
