### ISSUE TITLE
Parallel assembly of Crouzieux-Raviart facet integral form differs from serial

### ISSUE THREAD

**Issue by stephankramer** [firedrakeproject/firedrake#900]
The following code gives a different norm in serial than when run on 3 processes:

```
mesh = UnitSquareMesh(2,2)
V = FunctionSpace(mesh, "CR", 1)
u = TrialFunction(V)
v = TestFunction(V)
M = assemble(avg(v)*avg(u)*dS).M.handle
print M.norm()
```

This seems to only occur for facet integrals, not element integrals. I think it is going wrong somewhere in the halo.

**Comment by wence-** [comment]
I suspect you're right.  This is the worst kind of bug.

**Comment by dorugeber** [comment]
How are the dofs of the CR element defined?  This isn't necessarily a bug yet.

**Comment by dorugeber** [comment]
Okay, they're just point evaluation, so I *think* this is a bug.

[Otherwise, I don't think there's any apriori reason to expect the matrices to have the same values]

**Comment by stephankramer** [comment]
Some more data points. @dham suggested left and right multiplying with a 1 vector, which comes down to summing the entries of the matrix and should also be the same as the integral 1*dS. Adding to the above code, this is checked by:

    rs = M.getRowSum()
    print rs.sum(), assemble(Constant(1., domain=mesh)*dS)

This does seem to give the same answer in parallel as in serial. However left and right multiplying with slightly less trivial vectors, based on the functions `f(x,y)=x` and `f(x,y)=y` which should both be represented exactly in degree 1 CR, we get:

    xy = mesh.coordinates
    u1 = Function(V)
    u2 = Function(V)
    u1.interpolate(xy[0])
    u2.interpolate(xy[1])
    with u2.dat.vec as u2v:
        y = M.createVecLeft()
        M.mult(u2v, y)
    print assemble(avg(u1)*avg(u2)*dS), assemble(xy[0]*xy[1]*dS)
    with u1.dat.vec as u1v:
        print u1v.dot(y)

Here, in parallel (np=3) the first 2 numbers are the same (as expected), but the 3rd (which is u1v^T M u2v) comes out differently. In serial, all 3 numbers are the same.

**Comment by wence-** [comment]
Probably actually a bug, related to #1014
