### ISSUE TITLE
Issues Installing Firedrake on Mac OSX 10.11.6

### ISSUE THREAD

**Issue by APaganini** [firedrakeproject/firedrake#902]
I'm facing difficulties at installing Firedrake on my MacBook Air.

I've tried installing with `python firedrake-install --log`
The log file is: [firedrake-install.txt](https://github.com/firedrakeproject/firedrake/files/511476/firedrake-install.txt)

**Comment by dorugeber** [comment]
Looks like there was an issue cloning petsc. Has this happened repeatedly?
If not, try again, it might have been a one-off glitch with GitHub.

**Comment by dham** [comment]
Additionally, you appear to have broken permissions for `~/.ssh/config`. You should fix that in any case (note that this issue has nothing to do with Firedrake).

**Comment by APaganini** [comment]
Thanks for the quick reply. My `~/.ssh/config `contains

```
# Hosts we want to authenticate to with Kerberos
Host *.kth.se *.kth.se.
# User authentication based on GSSAPI is allowed
GSSAPIAuthentication yes 
# Key exchange based on GSSAPI may be used for server authentication
GSSAPIKeyExchange yes 

# Hosts to which we want to delegate credentials. Try to limit this to
# hosts you trust, and were you really have use for forwarded tickets.
Host *.csc.kth.se *.csc.kth.se. *.nada.kth.se *.nada.kth.se. *.pdc.kth.se *.pdc.kth.se.
# Forward (delegate) credentials (tickets) to the server.
GSSAPIDelegateCredentials yes 
# Prefer GSSAPI key exchange
PreferredAuthentications gssapi-keyex,gssapi-with-mic

# All other hosts
Host *
```

How should I fix it?

**Comment by wence-** [comment]
https://serverfault.com/questions/253313/ssh-hostname-returns-bad-owner-or-permissions-on-ssh-config

**Comment by APaganini** [comment]
thanks lorenz

**Comment by wence-** [comment]
But as @dorugeber points out, the problem was that cloning PETSc failed for whatever reason:
```
2016-10-05 15:44:33,615 WARNING Failed to clone petsc using ssh, falling back to https.
2016-10-05 15:45:35,537 DEBUG  error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

2016-10-05 15:45:35,537 ERROR  Failed to clone petsc branch firedrake.
```

This can happen if your connectivity drops, or the remote end is momentarily borked.

**Comment by APaganini** [comment]
I see. I've launched the installation once again and it is proceeding further.
I'll close the thread if everything is fine.

**Comment by APaganini** [comment]
The installation terminated with:
```
File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/Volumes/Scratch/Users/paalbert/Documents/Math/firedrake/bin/pip', 'install', '--no-deps', '-vvv', '--ignore-installed', 'petsc/']' returned non-zero exit status 1
```

which doesn't sound promising. The new log file is: [firedrake-install1.txt](https://github.com/firedrakeproject/firedrake/files/511603/firedrake-install1.txt)

**Comment by dham** [comment]
The proximate cause of your problem is:
/tmp/ccYYHnfO.s:70:suffix or operands invalid for `movq'
/tmp/ccYYHnfO.s:81:suffix or operands invalid for `movq'

Some Googling appears to indicate that this might be to do with the build process picking up incompatible compiler and assembler versions. This might occur, for example, due to having old MacPorts compilers lying around or due to the wrong combinations of out of date homebrew and Xcode. As a first step please run `brew doctor` and do anything it tells you.

**Comment by wence-** [comment]
Particularly, what does:

```
as --version
cc --version
which as
which cc
which mpicc
mpicc -show
```

say?

**Comment by APaganini** [comment]
Thanks David and Lorenz.

Brew doctor asked for a more recent xcode (which takes 2 hours)

@Lorenz

```
paalbert@dhcp-163-1-81-19.maths.ox.ac.uk% as --version
FATAL:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../libexec/as/x86_64/as: I don't understand '-' flag!
paalbert@dhcp-163-1-81-19.maths.ox.ac.uk% cc --version
Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
paalbert@dhcp-163-1-81-19.maths.ox.ac.uk% which as
/usr/bin/as
paalbert@dhcp-163-1-81-19.maths.ox.ac.uk% which cc
/usr/bin/cc
paalbert@dhcp-163-1-81-19.maths.ox.ac.uk% which mpicc
/usr/local/bin//mpicc
paalbert@dhcp-163-1-81-19.maths.ox.ac.uk% mpicc -show
clang -I/usr/local/Cellar/open-mpi/2.0.1/include -L/usr/local/opt/libevent/lib -L/usr/local/Cellar/open-mpi/2.0.1/lib -lmpi
```

Hopefully, the first FATAL issue will be resolved with the up-to date xcode version.

I'll post again once I'm done with brew doctor.

**Comment by APaganini** [comment]
And finally, the message
`
Successfully installed Firedrake.`

has been printed. The problem was that the brew doctor
was really disappointed and prescribed many treatements
for my file system.

Thank you David, Lorenz and dorugeber
