### ISSUE TITLE
Minor compatibility issue: `DirichletBC(VectorFunctionSpace, (0, 0), "on_boundary")` doesn't work

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/firedrake#911]
The following code

```
from firedrake import *

mesh = UnitSquareMesh(20, 20)
V = VectorFunctionSpace(mesh, "CG", 1)
bc = DirichletBC(V, (0, 0), "on_boundary")
```

raises an error:

```
UFL:ERROR Invalid type conversion: <type 'tuple'> can not be converted to any UFL type.
The representation of the object is:
(0, 0)
```

The analogous DOLFIN code runs no problem.

Could the `DirichletBC` constructor do whatever casting is required (calling `as_vector`)?

**Comment by dham** [comment]
Actually Firedrake works in this case and no error is raised. What is in fact happening is that as_ufl is raising an exception, which we catch and process correctly. Unfortunately, Martin has decided to write an error message to the log even though we catch the exception. I have raised an issue against UFL. See: https://bitbucket.org/fenics-project/ufl/issues/89/as_ufl-spews-a-log-message-even-if-the

**Comment by dham** [comment]
UFL will stop spewing the spurious error message when https://bitbucket.org/fenics-project/ufl/branch/martinal/topic-add-value-error-exception lands.

**Comment by wence-** [comment]
Which it now has.
