### ISSUE TITLE
Segmentation fault when assembling multiple tensors

### ISSUE THREAD

**Issue by alsgregory** [firedrakeproject/firedrake#972]
Hi, I have a assembly of a loop summing multiple tensors together. I get the following error:

`Segmentation fault (code dumped)`

and my python terminal closed. I was wondering if this is a memory leak or similar?

It may be useful to say that this occurred after running the function successfully a couple of times.

Many Thanks,
Ali Gregory

Minimal Failing Example:    

    from __future__ import division

    from __future__ import absolute_import

    from firedrake import *

    from ufl.classes import IndexSum, Product, MultiIndex

    import numpy as np

    mesh = UnitIntervalMesh(20)

    n = 40

    tfs = TensorFunctionSpace(mesh, 'DG', 1, (n, n))
    vfs = VectorFunctionSpace(mesh, 'DG', 1, dim=n)
    fs = FunctionSpace(mesh, 'DG', 1)

    phi = TestFunction(tfs)
    ensemble_f = Function(vfs)
    ensemble2_f = Function(vfs)
    nc = fs.dof_dset.size
    for i in range(n):
        ensemble_f.dat.data[:, i] = np.ones(nc)
        ensemble2_f.dat.data[:, i] = np.ones(nc) * 2

    i, j = indices(2)
    f = ((IndexSum(IndexSum(Product(nc * phi[i, j], Product(ensemble_f[i], ensemble_f[i])),
                            MultiIndex((i,))), MultiIndex((j,))) * dx) +
         (IndexSum(IndexSum(Product(nc * phi[i, j], Product(ensemble2_f[j], ensemble2_f[j])),
                            MultiIndex((i,))), MultiIndex((j,))) * dx) -
         (IndexSum(IndexSum(2 * nc * Product(phi[i, j], Product(ensemble_f[i], ensemble2_f[j])),
                            MultiIndex((i,))), MultiIndex((j,))) * dx))

    cost_tensor = assemble(f)
    cost_tensor.dat.data[:]`

**Comment by wence-** [comment]
This results in kernels that allocate multi-megabyte stack variables.  This breaks horribly.

**Comment by wence-** [comment]
In particular, the kernel makes an outer product of two 40x40 identity matrices and allocates it on the stack as a 19MB variable.  Ooops.

**Comment by wence-** [comment]
I note that your example doesn't run without adding `from ufl.classes import IndexSum, MultiIndex, Product`.

**Comment by alsgregory** [comment]
Yes sorry, I left that out. That's contained in my package that I've also left out.

**Comment by alsgregory** [comment]
Cool. I thought this would be very memory intensive. Should I call it quits on assembling this cost tensor this way then? I have another way, via kernels, but this one is nicer.

**Comment by wence-** [comment]
I don't know what you mean by "I thought this would be very memory intensive"

**Comment by miklos1** [comment]
@alsgregory: could you please try the TSFC branch `argument-sketch`?

**Comment by alsgregory** [comment]
@miklos1 Yep, it still gives me the same error :(

**Comment by alsgregory** [comment]
@wence- The tensors are going to be very large as N increases so I thought this could cause the assembly to be 'remembering' a great deal.

**Comment by miklos1** [comment]
@alsgregory: what if you also clean cache before trying again?

**Comment by alsgregory** [comment]
I don't know how you do it, but you are a programming genius.

It works. Pumping N up now to test your skills.

**Comment by alsgregory** [comment]
Can this be closed when tsfc/argument-sketch lands?

**Comment by wence-** [comment]
How big do you expect `N` to get?

**Comment by miklos1** [comment]
`argument-sketch` won't be merged... :(
It's a crude, half-baked sketch that is incompatible with COFFEE.

**Comment by alsgregory** [comment]
@miklos1 : Oh that's a shame. Is there anything we can take out of it to allow this still to work? Now I have it working I don't really want to let it go! ;)

@wence- : "how many high resolution realisations of an assimilated QG system can you run in a day or two?". Say ~100 max.

**Comment by miklos1** [comment]
@alsgregory: Once firedrakeproject/tsfc#105 is merged, writing `cost_tensor = assemble(f, form_compiler_parameters={'mode': 'spectral'})` instead of `cost_tensor = assemble(f)` solves this issue on master.
