### ISSUE TITLE
Installation problems for Paris workshop (2017-01-26)

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#976]
This issue is to debug any installation issues attendees at the [workshop on finite element software](http://calcul.math.cnrs.fr/spip.php?article274) have attempting to install Firedrake.

If you have any issues, please post the contents of `firedrake-install.log` (obtained by running `firedrake-install --log`) and details about your environment: operating system, python version.

**Comment by wence-** [comment]
Licensing?

**Comment by paventura** [comment]
Hi, I was unable to install firedrake on my MacBook Pro during the workshop, I used the virtual machine. Here is the log file for the install. Thank you for your help. Pascal
[firedrake-install.log.zip](https://github.com/firedrakeproject/firedrake/files/741945/firedrake-install.log.zip)

**Comment by wence-** [comment]
Hi, this is somewhat strange.  The build of spatialindex failed.  One thing I can maybe think is that you started out from a completely clean mac (no homebrew), then the install script ran and installed various homebrew pieces, and asked you to run again.  However, the shell was caching which python you had, so things ended up in the wrong place?

Can you provide the output of:

`env`

and

`which python`

and

`python --version`

Thanks!

**Comment by paventura** [comment]
Here it is : 

for env : 

MacBook-Pro-de-pascal:installfiredrake pascal$ env 

TERM_PROGRAM=Apple_Terminal 

SHELL=/bin/bash 

TERM=xterm-256color 

TMPDIR=/var/folders/82/jq19y_xs2p7d__353t78fnxr0000gn/T/ 

Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.CEgtUI9762/Render 

TERM_PROGRAM_VERSION=388 

OLDPWD=/Users/pascal/Documents 

TERM_SESSION_ID=3F2A9ACB-1CA6-4131-A926-A3A51D72181F 

USER=pascal 

SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.OKiQcH4qbo/Listeners 

__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x1 

PATH=/opt/local/bin:/opt/local/sbin:/usr/local/ff++/bin/:/usr/local/ff++/mpich/3.44/bin/::/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/ff++/openmpi/3.51/bin 

PWD=/Users/pascal/Documents/installfiredrake 

LANG=fr_FR.UTF-8 

XPC_FLAGS=0x0 

XPC_SERVICE_NAME=0 

SHLVL=1 

HOME=/Users/pascal 

LOGNAME=pascal 

DISPLAY=/private/tmp/com.apple.launchd.qPzmPCBgDX/org.macosforge.xquartz:0 

_=/usr/bin/env 

For which python : 

/usr/local/bin/python 

For python --version 

Python 2.7.13

**Comment by wence-** [comment]
Hmm, ok, I was wrong with my initial estimation.  It looks like you have homebrew and macports (?) and packages installed from various other places.  Do things work if you sanitise your PATH so that it just reads:

```
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

I suspect (although don't know) that you're getting an inconsistent set of compilers and so forth.  We install our own version of spatialindex inside the virtualenv that has a fixed C API, but it looks like some of the include files are coming from elsewhere.
