### ISSUE TITLE
Document how to make performant Firedrake user code

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/firedrake#977]
We should make a documentation section about using LinearVariationalSolver, Projector, etc for faster code. Let's make a list in this issue.

**Comment by wence-** [comment]
This more naturally belongs as a wiki page.

**Comment by danshapero** [comment]
Is this adequately handled in the [DG advection demo](https://firedrakeproject.org/demos/DG_advection.py.html)? This could also be addressed in [this section](https://firedrakeproject.org/solving-interface.html) of the docs.

**Comment by connorjward** [comment]
I added this to the manual a while ago: https://firedrakeproject.org/optimising.html#common-performance-issues. Closing.
