### ISSUE TITLE
Document accessing PETSc objects

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/firedrake#980]
Although matrices and functions are backed by petsc objects, the way they are to be accessed varies depending on what we're after.  Moreover, despite many people needing to get access, we don't really document things properly.  

Related:

- #973 
- #661

**Comment by juan42** [comment]
Would it be desireable to provide small, general wrapper functions so you could use pythons map function to "convert" to PETSc objects? Those could also have documentation entries which are then clear to the user if the object they get is already assembled or not (in case of a matrix handle for example)

**Comment by wence-** [comment]
We have these as dolfin compat shims via `as_backend_type`. The problem is that you need to use a context manager if you want RW access to a Function. If you modify values and want that reflected in the function, it's not enough to take a reference to the the Vec and modify that, you also need to (for mixed spaces) scatter back.

**Comment by danshapero** [comment]
How much of this is covered by [this page](https://firedrakeproject.org/petsc-interface.html) from the documentation? Is there more that needs to be documented or are there more functions that need to be added to the API?

**Comment by wence-** [comment]
I think this is mostly covered.
