### ISSUE TITLE
Error is not of machine precision when solution is in FE space

### ISSUE THREAD

**Issue by APaganini** [firedrakeproject/firedrake#999]
The following code computes a FE approximation of a function
that lies in the finite element space. When this approximation is
performed via interpolation, the error is (roughly) of machine precision
(as expected). However, when the function is approximated by solving a
variational problem, the error is roughly 1e-7. Where is my mistake?

`from firedrake import *

FEMorder = 2 
mesh = UnitSquareMesh(10, 10) 

V = FunctionSpace(mesh, "CG", FEMorder)

#exact solution as Expression
if FEMorder == 1:
    uDBC = Expression('(x[0]-x[1])')
else:
    uDBC = Expression('(x[0]*x[0]-x[1]*x[1])')

#exactsol
x, y = SpatialCoordinate(mesh)
if FEMorder == 1:
    exactsol = (x - y)
else:
    exactsol = (x*x - y*y)

u = TrialFunction(V)
v = TestFunction(V)

#dx(degree=10) #<-this doesn't seem to play any role
A = assemble(inner(grad(u), grad(v))*dx)
floc = Constant(0)
b = assemble(floc*v*dx)

#incorporate Dirichlet bc
bc = DirichletBC(V, uDBC, "on_boundary")
bc.apply(A, b)
        
#compute solution
uh = Function(V)
solve(A, uh.vector(), b)

errH1 = errornorm(exactsol, uh, norm_type="H1")
errL2 = errornorm(exactsol, uh, norm_type="L2")
print errH1, errL2

#interpolate exact solution
uh.interpolate(uDBC)
errH1 = errornorm(exactsol, uh, norm_type="H1")
errL2 = errornorm(exactsol, uh, norm_type="L2")
print errH1, errL2
`

**Comment by pefarrell** [comment]
What's the condition number of the matrix?

**Comment by wence-** [comment]
We can't do magic, when you solve a problem with an iterative method the algebraic error will be O(solver tolerance), even if there is no discretisation error. The default tolerance is either 1e-7 or 1e-8. The manual tells you how to change this.

**Comment by APaganini** [comment]
ok, replacing

`solve(A, uh.vector(), b)'

with

'solve(A, uh.vector(), b, solver_parameters={'ksp_type': 'preonly', 'pc_type': 'lu'})'

solves the issues. Many thanks for your help.
